### ISSUE TITLE
Trusted contact showing up in"My Keepers" and also under manage backup

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1018]
Trusted contact showing up as "My Keepers" and also under manage backup
Also a "tcg" that is "my keepers" shows up in "other contacts" as well

**Comment by Parsh** [comment]
Would require steps to replicate the error, have not been able to regenerate the issue at my end.

**Comment by cakesoft-swati** [comment]
Unable to reprodce this issue.
