### ISSUE TITLE
FastBitcoins UX improvement

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1029]
Add an intermediate screen for FastBitcoins flow. On selecting the option "Buy Bitcoin into Hexa Wallet" do following:

- Present a screen with following options
	- New to Fastbitcoins
	- Already registered with FastBitcoins
	Note: Is FastBitcoins available in my geography? Visit https://fastbitcoins.com/ for more details.
	
If the user clicks "already registered" then take the user to
"Pair a new wallet" screen.
Add following to the message "Scan the QR provided on your FastBitcoins account to pair you Hewa Wallet. 
Go to "Account -> Pair Wallet -->....check the existing flow".

If the user selects "New to Fastbitcoins" option then 
- present the screen "Scan a Fastbitcoins voucher" - change the heading "Register on FastBitcoins"
 -QR code and enter voucher code options
 - message indicating "For a new registration please scan a FastBitcoins voucher.  Visit https://fastbitcoins.com/ on how to buy a voucher in your geography.

In case there is an existing registration for FB within the app then instead of the initial screen directly present  "Scan a Fastbitcoins voucher" screen.

Notify FB team (Danny) to add a message to click on the "hexa" logo to link wallet on FBTC pair wallet screen on their side,

**Comment by ASN-BitHyve** [comment]
I think the location link should be https://fastbitcoins.com/locations

**Comment by ASN-BitHyve** [comment]
Arpan's Comment: "If the user clicks "already registered" then take the user to  
"Pair a new wallet" screen.  "
Abhilash's Suggestion: When a user clicks " already registered" the same screen should not be presented again.

**Comment by hemantsain** [comment]
Need new UX for the same.
