### ISSUE TITLE
Address Book

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1079]
-There are some issues while searching or adding contact:-
1.Not bringing up the contacts if searched by their second name.
2.Not showing contact who don’t have an email or phone number.
3.When you add a new contact, the contact should be auto-selected.
4.Not showing Phone number under selected contact name.

**Comment by antuz123** [comment]
Also when such contact is selected who does not have a phone or email, an OTP is given with a 24-hour timer. OTP should also be key-streached with Hexa ID @Parsh
