### ISSUE TITLE
The buttons are not very responsive.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1107]
-The buttons are still not very responsive and the spinning wheel is coming in the screen. 
-It should come on the top.
![spinningwheel](https://user-images.githubusercontent.com/62699947/88022058-3546b200-cb4c-11ea-9ee3-1e25ff2c505f.jpg)

**Comment by abdulmuneer22** [comment]
For this converting accounts screen to a class or reducing re-renders will help us improve this

**Comment by abdulmuneer22** [comment]
Duplicate of https://github.com/bithyve/hexa/issues/1240
