### ISSUE TITLE
FBTC notification.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1130]
-Notification received even when the sent was not success. 
-The notification is sent before the send. 
![Image from iOS (12)](https://user-images.githubusercontent.com/62699947/88280031-b9db3100-cd02-11ea-9063-4d00cd6b7d57.jpg)

**Comment by Parsh** [comment]
Unable to replicate.

**Comment by cakesoft-swati** [comment]
I was also unable to replicate this.
