### ISSUE TITLE
Misplaced timer

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#1152]
On the keeper card on keeper device side which was set using QR Nan Nan is showing. This is place for OTP timer but for keeper OTP does not come in picture (by Arpan sir).

![Image from iOS](https://user-images.githubusercontent.com/17980466/88387090-6256c700-cdcf-11ea-92b0-f158f508ba86.png)

**Comment by cakesoft-swati** [comment]
<img width="375" alt="81E1B6D9-9E38-4785-9BF4-DDEE3567B2A5" src="https://user-images.githubusercontent.com/62699947/93340897-15312780-f84b-11ea-9823-36eefa53df19.png">
Tested on version 1.1.2(107)
