### ISSUE TITLE
Health check status is not accurate

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1156]
Health check % check is not working as expected
Keeper and qa has a tick, still I see exclamation on android
And as per the screen shot attached, none is tick on the keeper side but has 20% health

![image](https://user-images.githubusercontent.com/8697909/88391427-caa9a680-cdd7-11ea-8b25-6d7fab88a553.png)
![image](https://user-images.githubusercontent.com/8697909/88391448-d1d0b480-cdd7-11ea-97ae-b7336a4e6b8f.png)

**Comment by cakesoft-swati** [comment]
-The health for these three not changing even after confirmations
![Uploading Screenshot_20200727-171005_hexa dev.jpg…]()

-The overall health(%) is also not getting updated. Even after Re-login.
