### ISSUE TITLE
Breaking Hexa recommendations

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1206]
Refer to BE5: Breaking Hexa recommendations for more details. Also added to R1.2 trello list.

**Comment by AliMeer** [comment]
@Arpanjainson I had done this before 0.9 release but it somehow did not get merged in time and the PR went stale.
I will do this again and raise a PR.

**Comment by antuz123** [comment]
@Varunram - all the items mentioned in that article should be resolved if not already

**Comment by Varunram** [comment]
This requires:
1. A dev to bring all old packages (mentioned in the article) in house (ie fork them and replace in package.json)
2. Convert remaining version numbers in package.json to package hashes (could be done along with the rn version bump)

Requires the assignment of a dev for 3-5 days to give time for testing and validation
