### ISSUE TITLE
1.0b: patch with note 

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1213]
See last comment

**Comment by antuz123** [comment]
Need a new UX

**Comment by antuz123** [comment]
Need a tick on the send screen in the Exit flow where the exit key has been used.

**Comment by antuz123** [comment]
The flow would be: 
1. Need Help in 2FA
2. Use Exit Key (put subtest in the option 'to sweep Savings account') 
3. Scan the send address 
4. Show the amount screen (no additional recipients possible) - the amount is prefilled to the 'send max' value which user can change 
5. Scan the exit key 
6. Show the confirmation screen with a tick for 'Exit key used' 
7. When you do send max, the fee selection is not possible so the user just confirms. If not confirmed, the exit key should be deleted from the device.

**Comment by antuz123** [comment]
1.  Send broadcast message to all Hexa 1.0 users. "Hexa 2.0 has been launched: Hexa 2.0 is better, faster and more reliable. Kindly download the new app from the App Store/ Play Store and follow the steps More> Move to Hexa 2.0 
2. Add a Migrate to Hexa 2.0 option in the settings with help page:
- Download the new Hexa 2.0 
- Create the accounts that you want in the new wallet
- Send the funds from the accounts to the accounts in the new wallet 
- Let your contacts know of the new amazing 2.0 app 
- Once they have also downloaded the new app, add them in the new Hexa 2.0 app

**Comment by antuz123** [comment]
Any other bugs for live should be fixed in this patch

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
