### ISSUE TITLE
Label is missing and email text

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1227]
-Part 8th of the PDF (2nd copy for sure") is missing the label.
![image](https://user-images.githubusercontent.com/62699947/88918881-dbe72d00-d287-11ea-917c-a194b1052ca7.png)

**Comment by antuz123** [comment]
Also, add a line on the email body (not inside pdf). 

A Personal Copy of one of your Recovery Keys is attached as a pdf. The answer to your security question (<mention security question>) is used to password protect the PDF.

**Comment by hemantsain** [comment]
Existing email body is: "Please find attached the personal copy 1 share pdf, it is password protected by the answer to the security question."

So do we need to change whole text or append new text?
