### ISSUE TITLE
Personal copy > Store/send pdf using other options.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1258]
-when I click on the " x " in this flow. It shows me sharing failed. 
-It's not a failure however in this case. It's a choice I am making. So when I click x the app should take me back to the "Store personal copy PDF"screen.
![File (18)](https://user-images.githubusercontent.com/62699947/89163671-91b9c080-d593-11ea-8f1b-483a1905cacf.jpg)

**Comment by antuz123** [comment]
Also, make sure that only the right option is disabled.

**Comment by hemantsain** [comment]
This needs to be test in iOS device. I don't have that with me.

**Comment by cakesoft-swati** [comment]
Still it is showing PDF sharing failed when I click on X button.
