### ISSUE TITLE
Scan GA testnet address prefilled with amount using QR 

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1259]
scan this via main QR button
Wrong amount populated. Also if should open the test account send and not the checking account send - this is important as we have a test account for learning

![image](https://user-images.githubusercontent.com/8697909/89177220-8e7cff80-d5a8-11ea-8082-f4d17d6bcce5.png)

**Comment by antuz123** [comment]
Also when tried of HRF donation QR, it gets multiple inputs.

**Comment by Parsh** [comment]
Fixed send routing part(based on testnet/mainnet address)

**Comment by hemantsain** [comment]
This is related to iOS device and I don't have that with me.

**Comment by Arpanjainson** [comment]
This seems to be fixed now.
