### ISSUE TITLE
Wallet ID - include on PDF & App

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1265]
Show Wallet-Id in App settings, on recovery shares on the keeper side, on PDF.
Wallet name on the keeper side share
Shorten the Wallet-Id (will be used during recovery flow to match the recovery key on the keeper side - becomes part of  DL)

**Comment by antuz123** [comment]
Wallet ID should be shown inside the F&F list details screen as well

**Comment by antuz123** [comment]
Not needed in the Recovery Key if it in the F&F list
In wallet settings, it can show along with the version number?

**Comment by antuz123** [comment]
The Wallet ID should be some kind of shortened WalletID that we may use internally. A FIngerprint of the Wallet ID?

**Comment by Arpanjainson** [comment]
Shorten Wallet-Id - collision free, irreversible & no loss of privacy.

**Comment by Parsh** [comment]
@antuz123 Do we still need this?

**Comment by Arpanjainson** [comment]
Assigend Trello card https://trello.com/c/F3SnOXEE/65-wallet-id-include-on-pdf-app-1265

**Comment by AliMeer** [comment]
Do we still need this?

**Comment by antuz123** [comment]
Yes, once we have the F&F details screen it should show the Wallet ID as well. Will put this in 1.8.5
