### ISSUE TITLE
Network fee.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1267]
-Network fee need to be looked at.
- We have very high network fee as compared to say coinbase.

**Comment by antuz123** [comment]
We should have a wider option:
1. Within 30 mins 
2. Within 2 hours 
3. Within 6 hours 
4. Custom (the user eneters the amount, the UI tells it how much time will that take) It shows them a minimum fee which they can enter.

**Comment by antuz123** [comment]
New UI will be needed and some research from @Varunram

**Comment by modl21** [comment]
custom fee option would be ideal, especially since I expect sustained high fees in the near future

**Comment by Varunram** [comment]
@antuz123 @cakesoft-swati I need stats on fees - what's the difference and at what times. The way we calculate fee rate right now is through an average of the average fee rate in certain intervals:
1. High - (2+3)/2
2. Medium - (4+5+6)/3
3. Low = (6+10+20)/3

where numerator denotes the fee at block n. An optimisation of this needs better understanding of the exact differences, so we can weigh the fee at block n accordingly.

**Comment by antuz123** [comment]
We can discuss it on the call. Given the requirement, what is the best way to calculate?

Regards

**Comment by antuz123** [comment]
custom min = 24 hours
