### ISSUE TITLE
Remove the underscore from FastBitcoin.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1282]
-Remove the underscore from FastBitcoins and make it FastBitcoins.com
![20200805_170203](https://user-images.githubusercontent.com/62699947/89408077-7f7b8600-d73d-11ea-96c7-37f2889429ab.jpg)

**Comment by cakesoft-swati** [comment]
Still able to see underscore.

**Comment by Arpanjainson** [comment]
checked and found ok.
