### ISSUE TITLE
Need a new option App Rating

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1287]
-Don’t need this option here. Need a new option, Loving it? Rate Hexa. 
-This should connect to the in app rating mechanism.
![tempFileForShare_20200806-191106](https://user-images.githubusercontent.com/62699947/89538847-b07cb900-d818-11ea-9698-0b2a9a235f7e.jpg)

**Comment by hemantsain** [comment]
Need icon and sub heading text.

**Comment by antuz123** [comment]
@hemantsain - this is where this option will show when ready: https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/cd34bc31-f843-4fab-9f9b-81746d4a44f2

**Comment by antuz123** [comment]
@AliMeer - this is needed and there is some capability OS provides, this just triggers it.

**Comment by AliMeer** [comment]
@antuz123 the screenshot is very old. It's confusing to use this issue for app rating requirement, also app rating has a separate issue already.

**Comment by AliMeer** [comment]
Closing this as we already have https://github.com/bithyve/hexa/issues/3092
