### ISSUE TITLE
F&F/ Keeper using a link failing 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1291]
When you send any request to a contact and the contact clicks on the link but does not complete the process, the next time the link is clicked, the message says that the link has expired. Also cannot reshare as it gives the same link again. 

Also need to let the user delete a contact when pending. This should take care of all the necessary changes like deleting from the other end etc.

**Comment by Parsh** [comment]
I wasn't able to replicate that.
Following is what I've tried:
- Clicked on the DL, it opens the app, click reject on the trusted contact model
- Again clicked on the DL, entered the number, pressed the back button on the Associate contact screen
-  Finally, clicked on the DL, entered the number, on the Associate contact screen close the app

Even after doing the above steps, when I again clicked on the link, I was able to approve the link and add as a trusted contact.

@cakesoft-swati Can you please try this out and confirm?

**Comment by cakesoft-swati** [comment]
-I am not able to replicate this. Followed the same steps as mentioned above.
