### ISSUE TITLE
Transaction submission failing

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1292]
When sending to different address types like Segwit and non-segwit 

A contact and Savings account and an external native segwit address 

Is it failing for all native segwit addresses?

**Comment by Parsh** [comment]
Wasn't able to replicate it over the apps on the simulator. Have tried following addresses for the batched tx over Testnet: BIP-44(HD legacy bitcoin address), BIP-84(native Segwit), BIP-141(backward compatible Segwit), BIP-49(HD backward compatible Segwit)

On 1.1.1 live, I was able to successfully able to send to my contact(BIP-49 address) and to a BIP-84 address within a single tx, a snapshot of which is provided below.


![Screenshot_20200807-124038](https://user-images.githubusercontent.com/17980466/89619592-dc954a00-d8ab-11ea-9201-ee5b696198dc.jpg)

**Comment by antuz123** [comment]
Successfully submitted but does not reflect in the balance or transaction list.

**Comment by cakesoft-swati** [comment]
-Tested it on Live app version 1.2.1(133),got submitted successfully but,does not reflect in the transactionlist.

**Comment by antuz123** [comment]
Txns get dropped off mempool with a very low fee. Is that the case?

**Comment by antuz123** [comment]
Need to get a time for @Varunram  and @Parsh  to sit down and solve this. 

cc: @AliMeer @Arpanjainson
