### ISSUE TITLE
Send All option 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1294]
New UX will come but basically when this option is selected in the amount part. All the remaining amount in that account minus the ‘medium’ fee is put in the amount. 

Now no participant can be added and fee cannot be changed. 

Send all can be done when a previous recipient was selected, in this case the remaining ‘available to spend’ amount will be used. 

This has overlap with one UX work Hemant is doing but this card is for the amount calculation

**Comment by Arpanjainson** [comment]
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/68a2c2f9-34d5-429b-ac03-e2c6ff2c2374   - enter max
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/227ec04a-8e87-426f-bb1e-7fc4273b0ffb
- custom priority

**Comment by Arpanjainson** [comment]
@Parsh - should not be able to select a fees when send max is selected
