### ISSUE TITLE
Configure hexa CI/CD for iOS with version i.e 0.63 of React Native.

### ISSUE THREAD

**Issue by hemantsain** [bithyve/hexa#1295]
- Configure hexa for iOS with latest version i.e 0.63 of React Native.
- Configure multiple flavors of build type for iOS.
- Configure Firebase for iOS.

**Comment by Arpanjainson** [comment]
We need to make sure that our installation instructions are updated if required.

**Comment by Arpanjainson** [comment]
@abdulmuneer22 please handle the iOS RN upgrade related issue

**Comment by hemantsain** [comment]
Latest code of RN upgrade is in **hemant/rn_upgrade** branch. This configuration is working for Android but not for iOS.

**Comment by antuz123** [comment]
Configure multiple flavors of build type for iOS.
