### ISSUE TITLE
Send button on Test account not responsive - iOS

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1296]
Open the app afresh. Go to test account and try clicking the send.

do it 2-3 times by closing and opening the app after a dely.

**Comment by abdulmuneer22** [comment]
@Arpanjainson , could you please add a video of it ? not able to reproduce it consistently

**Comment by abdulmuneer22** [comment]
Duplicate https://github.com/bithyve/hexa/issues/1296

**Comment by abdulmuneer22** [comment]
Duplicate of https://github.com/bithyve/hexa/issues/1240
