### ISSUE TITLE
Intermediate routing screen

### ISSUE THREAD

**Issue by abdulmuneer22** [bithyve/hexa#1300]
Create an intermediate screen to reduce loading time for deep link

**Comment by antuz123** [comment]
This is the pre-HS/ landing/ routing screen we are talking about @CypherPoet

**Comment by AliMeer** [comment]
@antuz123 I don’t think this is an issue anymore

**Comment by antuz123** [comment]
@AliMeer - changed the title. This is still an issue. We need:
1. Ability to lock thee app when the app goes to the background for > x secs
2. Not to do all HS activity when you click on deep link, it takes a long time, if we host the deep link modal on this screen then there are no actions here 
3. This screen can also take the user to the last screen they were on or last step they were doing e.g. creating an account. It will jump the flow past HS so it does not have to wait for all HS stuff before they can take a step.

**Comment by antuz123** [comment]
I have moved it to 2.0.0, please think about the solution till then

**Comment by cakesoft-swati** [comment]
-Verified this issue as discussed with dev.
-

**Comment by antuz123** [comment]
@cakesoft-swati - loading time reduced for the link?
