### ISSUE TITLE
Bug when scanning QR that has amount included

### ISSUE THREAD

**Issue by modl21** [bithyve/hexa#1308]
When you scan a QR code that has an amount of bitcoin to send included, the wallet has an error where it shows multiple "batched" payments to the same address then freezes.

Appears to only happen in the iOS version. Haven't been able to replicate it on android.

![image](https://user-images.githubusercontent.com/50266466/89737342-2e6dd980-da3e-11ea-8de3-e02844749a3b.png)

**Comment by Arpanjainson** [comment]
Thanks @modl21 for notifying this. This issue has been logged already. A fix is planned in next 1-2 days.

**Comment by antuz123** [comment]
Bug fixed. Testing is done. Need to close.
