### ISSUE TITLE
Need a way to delete confirmed contacts.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1310]
-We need a way to delete even confirmed contacts.
![Image from iOS (13)](https://user-images.githubusercontent.com/62699947/89753350-916e7780-daf5-11ea-92b8-0334ca66eb52.jpg)

**Comment by Parsh** [comment]
@antuz123 Need to think further on this. Confirmed TC(non-Keeper & non-ward) removal has been implemented already.

**Comment by antuz123** [comment]
1. Expired Keeper and 'I am the Keeper of', should also be something you can delete
2. Contacts should be deletable irrespective of their status - Expired, Pending or Confirmed
3. When Contacts are deleted, the reflection should be on the other side also. A notification is sent to the counterparty and then the contact is deleted from the other end too
4. On any deletion, a message is shown to the user and only on confirming the same is the action taken

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app vrersion 1.3.0(150)
