### ISSUE TITLE
Manage Backup screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1317]
-New tags on this screen.
<img width="399" alt="Screenshot 2020-08-10 at 1 09 25 PM" src="https://user-images.githubusercontent.com/62699947/89761257-9b9b7080-db0b-11ea-82ed-e7703567a17b.png">

**Comment by antuz123** [comment]
Keeper Device. Status =
setup (grey exclamation) then line = “Use one of your other device with Hexa”
ugly (red exclamation) then line = “Confirm by logging on the Keeper Device”
bad (amber exclamation) then line = “Confirm by logging on the Keeper Device”
good (green tick) then line = “The Recovery Key is accessible”

Friends and Family. Status =
setup (grey exclamation) then line = “Select a contact as a Keeper”
ugly (red exclamation) then line = “Confirm by asking the contact to go online”
bad (amber exclamation) then line = “Confirm by asking the contact to go online”
good (green tick) then line = “The Recovery Key is accessible”

Personal Share. Status =
setup (grey exclamation) then line = “Secure your Recovery Key as a file (pdf)”
ugly (red exclamation) then line = “Confirm by scanning pdf’s first QR”
bad (amber exclamation) then line = “Confirm by scanning pdf’s first QR”
good (green tick) then line = “The Recovery Key is accessible”

Security Question. Status =
ugly (red exclamation) then line = “Confirm the Security Question and Answer”
bad (amber exclamation) then line = “Confirm the Security Question and Answer”
good (green tick) then line = “Security Question and Answer are confirmed”

The main title on each item or the indicators use the same logic as now. Don’t change anything for them

**Comment by cakesoft-swati** [comment]
Tags are not matching for Keeper device and Friends and family.
