### ISSUE TITLE
App navigation after entering the 2FA.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1324]
-Post entering the 2FA or the Exit key, this screen does not come back but it goes through. 
![postentering](https://user-images.githubusercontent.com/62699947/89789683-8855c880-db3e-11ea-80ee-0c844d0ee319.jpg)

**Comment by AliMeer** [comment]
@antuz123 Is this issue still present and if so is it a priority for 1.5.0

**Comment by antuz123** [comment]
@cakesoft-swati - can you explain this issue, I am not sure I understand.

**Comment by cakesoft-swati** [comment]
-Unable to reproduce this issue on dev app v1.7.5(296)

**Comment by antuz123** [comment]
> -Unable to reproduce this issue on dev app v1.7.5(296)

Please mark it fixed then
