### ISSUE TITLE
OTP timer.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1329]
-After restore:- On the  keeper which was not used to restore has OTP timer(anant). 
- It came after I sent a request for TC (to Parshva).
![File (25)](https://user-images.githubusercontent.com/62699947/89863721-4ec99f80-dbc8-11ea-802f-58b8061266ed.jpg)

**Comment by Parsh** [comment]
@cakesoft-swati Can you please try to reproduce it?

**Comment by cakesoft-swati** [comment]
-I'm not able to reproduce this issue.
