### ISSUE TITLE
FastBitcoins get quote/ redeem failing 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1336]
Need to find out from FB what the issue is and why it is failing. Also, we have implemented the new UX now for their wallet connect feature.

**Comment by AliMeer** [comment]
Fixed this in v1.1.1 build # 93

**Comment by Parsh** [comment]
This has been tested and working. @cakesoft-swati Please close this.

**Comment by Arpanjainson** [comment]
works fine using the shared login.
