### ISSUE TITLE
Checking Account pull down

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1393]
-The pull down refresh takes a long time and we try to refresh, it is get stuck on account screen.
![File (28)](https://user-images.githubusercontent.com/62699947/90783748-1f303b00-e31e-11ea-9d4f-b3c913ecfbe9.jpg)

**Comment by antuz123** [comment]
@abdulmuneer22 - seems that the refresh is getting stuck.

**Comment by AliMeer** [comment]
@abdulmuneer22 The server isn’t getting any request when checking account does a refresh by pulling down. We tried this live while checking logs on the server side.
