### ISSUE TITLE
Add dust limit during send transactions

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1400]

**Comment by antuz123** [comment]
minimum allowed should be 550 sats

**Comment by cakesoft-swati** [comment]
I can send 0 sats.
-I sent it from checking account and got a notification with no transaction in test account.

**Comment by cakesoft-swati** [comment]
-when you delete something and then put a lower amount it does no validate again.
- The validation should be after the button is pressed not on entry.
