### ISSUE TITLE
UTXOs received from trusted contacts are not being considered when sending

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#1401]
UTXOs received from trusted contacts are not being considered when sending.

Env: Mainnet

Failing Test Case:
Recieve transaction from a trusted contact
Wait for confirmation(s)
Try to send part of the received balance to any address

Result: Unable to send any amount

Send is successful when receiving and sending from a non trusted contact address.

**Comment by cakesoft-swati** [comment]
-Verified it on Dev app version 1.3.0(156)
-Need to verify it on Mainnet.

**Comment by cakesoft-swati** [comment]
-Verified this on production app version 1.3.2(175)
