### ISSUE TITLE
Friends and Family screen changes.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1411]
-Don’t need the space when there is no item.
![F F](https://user-images.githubusercontent.com/62699947/91005882-9bb06b80-e5f5-11ea-9af8-8b6452ab2d30.jpg)

**Comment by hemantsain** [comment]
Screen will not look good if we will remove these spaces because then there will be a lot white space after 50% of the screen height.

**Comment by antuz123** [comment]
New XD coming

**Comment by cakesoft-swati** [comment]
I'm  not able to see any changes here.
