### ISSUE TITLE
Send via checking account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1425]
-Here should not fail with an amount of 4000 or 5000. As the user can choose the custom fee as very low and send. It fails even if the fastest can’t be sent, that is not correct.
- That option should simply be greyed out.

-Alignment of these messages.

**Comment by antuz123** [comment]
The Send should show insufficient balnce only if the amount to be sent + 1 sat/byte is not enough. It should grey out all that is not applicable in terms of fee brackets.
