### ISSUE TITLE
Default currency.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1426]
-The default currency should be based on the App Store location. 
-Does not seem to be working.

**Comment by antuz123** [comment]
@cakesoft-nikhita - time to fix this please.

**Comment by cakesoft-nikhita** [comment]
@cakesoft-swati @antuz123 As we discussed for this functionality users need to set Language & region India in settings.
In iOS: Setting > General > Language & Region
Change here to India
In Android: Setting > Language and input 
Change here to English(India)

**Comment by antuz123** [comment]
Yes but it does not take any default. The default starts with dollar. That is not what we discussed. The default is what the settings give you and then the user can change if they want. 

Why will a user start with dollar.

**Comment by antuz123** [comment]
Why did we remove the default currency I am not sure.

**Comment by cakesoft-nikhita** [comment]
@antuz123 
Yes, I fixed that its coding issue. If my PR is merging in dev then you can test this in next release.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app version 1.3.2(170)
