### ISSUE TITLE
PDF recovery key deletion on 100% health

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1442]
If the user does not explicitly clicks "Yes I have shared"  button (which can be skipped to be clicked) the PDF still remains on the main device. Need to fix the flow.

Also once 100% health is achieved all the 3 personal shares should be auto deleted from the phone.

**Comment by antuz123** [comment]
mostly fixed, need to check @Parsh

**Comment by cakesoft-swati** [comment]
-Discussed with Parsh.
