### ISSUE TITLE
Need to fix to a certain fee.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1443]
-Need to check, if issue in the app or api and fix to a certain fee.
-The three tiers 400 sats 500 sats 600 sats.
![needtocheck](https://user-images.githubusercontent.com/62699947/91258594-58d3cc80-e78a-11ea-95d8-b54e8a47f115.jpg)

-For test account,transaction fee is NaN.
![tempFileForShare_20200826-133743](https://user-images.githubusercontent.com/62699947/91279320-f4713700-e7a2-11ea-9dd2-6d875148c7bd.jpg)

-so when I'm trying to send Max: it s showing NaN sats.
![Screenshot_20200826-133935_hexa](https://user-images.githubusercontent.com/62699947/91279183-d4da0e80-e7a2-11ea-9e25-bd7873dcbeef.jpg)

**Comment by antuz123** [comment]
For now we can change this to the backend supplying specific values 

224
350
500

The app will not need any changes

**Comment by cakesoft-swati** [comment]
-Tested on Dev app version 1.1.2(101)
