### ISSUE TITLE
Currency for FBTC voucher

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1445]
-Currency : here is my wallet setting currency in usd while the voucher is a pound voucher.
![File (31)](https://user-images.githubusercontent.com/62699947/91257857-8e77b600-e788-11ea-98a4-2428380bc7f9.jpg)

**Comment by AliMeer** [comment]
@antuz123 its actually not picking up the user's chosen or default currency. The $ is a static image used on this screen so will be displayed for all currencies regardless of the voucher currency.

**Comment by CypherPoet** [comment]
@AliMeer @antuz123 I think the way we're handling currency codes throughout the app is highly error-proned. Made a refactoring issue [here](https://github.com/bithyve/hexa/issues/1911) that goes into more detail.

**Comment by antuz123** [comment]
Need GBP and other currency icons. @Arpanjainson

**Comment by antuz123** [comment]
What other voucher currencies FBTC has? 

need to test in test and live.

**Comment by AliMeer** [comment]
> Need GBP and other currency icons with both the shades @Arpanjainson

GBP is there, as well as a few others. But we don’t have icons for all currency symbols.

**Comment by AliMeer** [comment]
This will now work correctly for USD and GBP and will not show currency symbol for other currencies till they are available.
Added a utility to retrieve correct image for currency symbol if it is available and supported.
Once other symbols are available they can be easily added.

**Comment by AliMeer** [comment]
At the moment FBTC test env is not working so this can only be tested on staging.

**Comment by Arpanjainson** [comment]
@AliMeer  the screenshot you shared still shows "$" symbol and that seems to be live from 19th Nov I guess

**Comment by cakesoft-swati** [comment]
![IMG_0320](https://user-images.githubusercontent.com/62699947/104909673-38f9ab00-59ae-11eb-8492-55d90f2a272f.PNG)
-Verified this issue with Ali sir.
