### ISSUE TITLE
Relay Should Pre-Fetch Fee Estimation, Fee trend and Exchane rate

### ISSUE THREAD

**Issue by abdulmuneer22** [bithyve/hexa#1447]
There are two services that the app calls directly for fee estimation and exchange rate. This may impact app performance and we don’t need these calls from the app.

The relay should pre-fetch these values for all apps every x mins and keep a digest ready for the apps to pick up when the check-in with the relay.

**Comment by Arpanjainson** [comment]
@antuz123  we should do this as part of performance, assigning to parshva

**Comment by antuz123** [comment]
Here we may want to pre fetch the Fee trends as well.

**Comment by Parsh** [comment]
Exchange rates Cron to Relay as a part of the following: https://github.com/bithyve/hexa/issues/1994

**Comment by Arpanjainson** [comment]
compare exchange rate on blockchaininfo

**Comment by cakesoft-swati** [comment]
-Veerified on Hexa prod app version 1.3.1(164)
