### ISSUE TITLE
Showing NumPad for the contact t OTP 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1454]
The OTP generated is alphanumeric, not sure why is it showing numbers only.

**Comment by Arpanjainson** [comment]
The receiver has to be Graffin else check on Android

**Comment by Arpanjainson** [comment]
Unable to recreate in the skip contact flow.

**Comment by Arpanjainson** [comment]
alphanumeric keypad is showing for add contact flow where contact does not have mail and phone.

**Comment by Arpanjainson** [comment]
Cant recreate

**Comment by Arpanjainson** [comment]
cant recreate
