### ISSUE TITLE
Link Expiry bug 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1456]
Steps to reproduce: (try the manage backup add keeper flow)

1. Send a F&F request to someone on Android (from iOS) 
2. Let the recipient click the link and accept
3. The recipient then goes to Associate Contact step 
4. Not finding the contact does new
5. Then the user closes the app 
6. Next time the user clicks on the link, it says link expired

**Comment by Arpanjainson** [comment]
Swati and I were not able to recreate

**Comment by Arpanjainson** [comment]
Sent a Keeper request to Anant with following details
https://hexawallet.io/dev/tcg/Arpdev/f35de790544fc3cf8b79c3f6b0965227e8c333e9bfafa32f96f981ae16639ae819d973a3739e27c27846232e0eb7c1674e6d2d09f71272535ec9ac523cdf92f3083b6187f3d4e62b004334fae6ef59d6/otp/xxx/1600233740875/v1.1.2
D31Y3J
Anant received "link expiry" message - he tried this within 30-45 min after link generation

**Comment by cakesoft-swati** [comment]
-Received this contact request from Arpdev Hexa wallet https://hexawallet.io/dev/ptc/Arpdev/6c28af040aaf62f74371112f728a5f0f3c789550eb8c6c79eb7c03286e9cba64969129f241de9fa5f366f9a678f4debc89e7bed3ee191875b56f64cdd9e315ba614483b94e6a29ccfc65003199762758/otp/xxx/1600233400694/v1.1.2
-I followed the same steps as Anant sir mentioned above,then I got this error.
![Screenshot_20200916-115205_hexa dev](https://user-images.githubusercontent.com/62699947/93306709-dd5fbb00-f81d-11ea-9748-af52306ceea2.jpg)

**Comment by antuz123** [comment]
Test it or the live upgrade

**Comment by antuz123** [comment]
QR/Link expiring when re-sharing post expiry time. The app simply gives the same QR/ link but as the time has passed it will mark it expired. The app should generate a new link/ QR in this case?

**Comment by Parsh** [comment]
Deeplink is getting generated after expiry time(24hrs across all environment), doesn't seem to be the root cause for this issue.

**Comment by antuz123** [comment]
Scenario 1: Post link expiry 
1. A link or QR is shared for the Keeper (contact or device) 
2. It gets accepted and 24 hours have passed 
3. Now the user re-shares the link/ QR to a different user 
4. The system sends the same link/ QR as it is assuming the same user but as it has been accepted, the ephemeral channel is no longer there 
5. In this case it will show an error 
(I have tested it for the Keeper Device for this scenario)

**Comment by Parsh** [comment]
> Scenario 1: Post link expiry
> 
> 1. A link or QR is shared for the Keeper (contact or device)
> 2. It gets accepted and 24 hours have passed
> 3. Now the user re-shares the link/ QR to a different user
> 4. The system sends the same link/ QR as it is assuming the same user but as it has been accepted/ 24 hours passed, the ephemeral channel is no longer there
> 5. In this case it will show an error/ expiry
>    (I have tested it for the Keeper Device for this scenario)

@antuz123 Should we disable the reshape button then?

**Comment by antuz123** [comment]
@Parsh - I am thinking of the solution:
1. We need 'Change Device' on the Keeper Device screen, same as change contact so it sends the same RK but to a new device and so a new channel and everything. 
2. When the RK has been accepted once, re-share should not show (Contact and Device). After that, you can only change the contact and resend the RK in a new channel.

**Comment by antuz123** [comment]
Make sure 'Change Contact', 'Change Device' does everything again other than using the same Recovery Key.

It should ideally delete the RK from the old contact and kill any channels (in case of a new contact) or kill the info in the approved channel (in case of an existing contact) so the old contact should not be able to accept now. But if this is a separate issue then we can look at it then.

**Comment by antuz123** [comment]
![Uploading 19D2FCBE-A4A5-4375-A6B7-06236A77BEB5.jpeg…]()

**Comment by antuz123** [comment]
![A99CE22C-2BD3-4917-8E67-DB44E68E7E78](https://user-images.githubusercontent.com/43998049/93745250-d87d7b80-fc10-11ea-889f-a20279222d66.jpeg)

**Comment by antuz123** [comment]
![Uploading 492DFCC5-7421-47F5-9E06-A01EC477F1EA.jpeg…]()

**Comment by antuz123** [comment]
![Uploading 0969FDAC-9674-4B06-BC67-9267E766B8DC.jpeg…]()

**Comment by antuz123** [comment]
Text changes to the two screens above.

**Comment by antuz123** [comment]
@Parsh also note that 

3. Post expiry of the RK and when not accepted, the reshare should do everything again other than asking for contact association

**Comment by Parsh** [comment]
> 1. Post expiry of the RK and when not accepted, the reshare should do everything again other than asking for contact association

Yes, we already do that.

**Comment by Parsh** [comment]
> @Parsh Make sure 'Change Contact', 'Change Device' does everything again other than using the same Recovery Key.
> 
> It should ideally delete the RK from the old contact and kill any channels (in case of a new contact) or kill the info in the approved channel (in case of an existing contact) so the old contact should not be able to accept now. But if this is a separate issue then we can look at it then.

@antuz123 We'll need to look at this one separately
