### ISSUE TITLE
Contact images on Send

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1457]
-The images vanish after a while? Are they not stored locally?
![File (32)](https://user-images.githubusercontent.com/62699947/91522537-1e983580-e918-11ea-832f-4bd29c624cfd.jpg)

-Bad alignment.
![badalign](https://user-images.githubusercontent.com/62699947/91540289-35e71b00-e938-11ea-9167-7b44cdb9c67b.jpg)

**Comment by CypherPoet** [comment]
Closing this for now, as the remaining issues seem to be a duplicate of #2117.
