### ISSUE TITLE
Send confirmation.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1458]
-Stays this way for long. 
-It should show the spinning wheel quickly.
![stayslong](https://user-images.githubusercontent.com/62699947/91523259-e134a780-e919-11ea-814d-0128fcac2f2d.jpg)

-Don’t need the arrow, no further details needed here.
![dntneed](https://user-images.githubusercontent.com/62699947/91523791-41781900-e91b-11ea-9dc5-4ee6079838cb.jpg)

**Comment by cakesoft-swati** [comment]
These changes haven't happened yet.

**Comment by AliMeer** [comment]
This needs to be combined with the wider issue of disabling screen when sending.

**Comment by cakesoft-nikhita** [comment]
I did that arrow change. But that button loader change we already handled last time and as Ali sir said we need to create another issue on which screen disabling while performing any action

**Comment by cakesoft-swati** [comment]
![tempFileForShare_20201124-192104](https://user-images.githubusercontent.com/62699947/100103000-5c124d80-2e8a-11eb-9039-2cada60e547a.jpg)
I can still see the arrow on send confirmation screen.

**Comment by cakesoft-nikhita** [comment]
I resolved this issue https://github.com/bithyve/hexa/commits/39aab1539af6ab396f882bc6e1935a977fc448ab but after that maybe some code changes were there so some code replaced with my code

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app version 1.4.0(180)
