### ISSUE TITLE
Disable the spellcheck.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1460]
-Disable spellcheck in all name entries, answers etc across the app .
![disablespellcheck](https://user-images.githubusercontent.com/62699947/91523572-b434c480-e91a-11ea-9e2f-5f1494a500dc.jpg)

**Comment by antuz123** [comment]
@cakesoft-nikhita - this is for all text areas, not just the screen above. Like the answer text box etc.

**Comment by cakesoft-nikhita** [comment]
> @cakesoft-nikhita - this is for all text areas, not just the screen above. Like the answer text box etc.

Yes, I handled it in all places. But still, if you and swati find anything while testing, please mention that screen.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app version 1.3.2(168)
-Spellcheck is disable for all the text areas.
