### ISSUE TITLE
Transaction does not reflect on the block explorer.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1461]
-Showing the transaction done yesterday on the account but does not reflect on the block explorer. 
-Says transaction not found.
![File (34)](https://user-images.githubusercontent.com/62699947/91540035-df79dc80-e937-11ea-98d7-b283c6c9759d.jpg)

**Comment by antuz123** [comment]
https://blockstream.info/tx/50fa1e7632e406c84a170d0510e0ec218a10ab34985e2a7409bb70cbe23cbd5d

**Comment by Arpanjainson** [comment]
Arpan to recreate referring to the video anant posted

**Comment by Arpanjainson** [comment]
could not recreate
