### ISSUE TITLE
Gap Limit and Sync

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#1478]
- [ ] Increase Derivative Account gap limit to 20 and Donation Account gap limit to 100.
- [ ] Instead of synching all the addresses on every time, we will do soft refreshes (+20 and -20 from free-address index) and will provide a hard refresh option in advance settings (and during restore).
- [ ] Need to benchmark the balance fetching functionality

**Comment by antuz123** [comment]
This needs to be done with the Wrapper Changes and post Account Management.

**Comment by Parsh** [comment]
Re-opening as #2333 depends on it.

**Comment by Parsh** [comment]
For soft refresh, ideally we would like to have a +5 and -x, where x is the index of the address having a tx with confirmations less than equal to 6

**Comment by Parsh** [comment]
Query list for address range strategy

What is the static range: +5 and -5.
What is the input criteria of putting addresses in AQL (additional query list): input utxo belongs to that address and the address is out of range
When do we put addresses in AQL: in the Send flow and on account refresh (where it tells which TXNs and therefore addresses don’t have 6+ Conf)
QL (Query List = Range + AQL) is at a sub account level.
When do you fire the Account QL?: during account refresh for now. This is a combination of sub-account QLs
When do you pop items out of AQL. Post refresh or post query, when the address has 6+ confirmation

**Comment by antuz123** [comment]
Ways of AQL:
1. Send 
2. F&F 
3. Buy journeys (service sub-accounts) that do not have xPubs shared with the 3rd party. Only the app is showing any additional address

**Comment by antuz123** [comment]
The range should only be adding into the list criteria while for taking out it has to be 6+ confirmation.

**Comment by antuz123** [comment]
@Parsh - please split this issue as discussed as we are not doing the AQL as above
