### ISSUE TITLE
Check the icon.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1500]
-Wrong icon.
![wrongicon](https://user-images.githubusercontent.com/62699947/92560394-f43b6600-f28f-11ea-869e-099d58c8843b.jpg)

-
![homeicon](https://user-images.githubusercontent.com/62699947/92560465-18974280-f290-11ea-9893-3335db81ac3b.jpg)

**Comment by hemantsain** [comment]
icon is correct but it's background is white and due to this reason hexa corners are not visible.
Please provide correct image for the same.

![icon_donation_account](https://user-images.githubusercontent.com/4425044/92567002-b263ed00-f29a-11ea-9393-e2c3d1072523.png)
