### ISSUE TITLE
UI issues of Donation account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1513]
-Does not look right.
![doesnot](https://user-images.githubusercontent.com/62699947/92684916-3cbc5780-f354-11ea-88e4-d99c76bdc8dc.jpg)

-Wrong icon. 
-Also we don’t need the balance here. Just the name
![dntneedbal](https://user-images.githubusercontent.com/62699947/92685051-8311b680-f354-11ea-9d79-2be484f3eb69.jpg)

-Tick not coming properly.
![tick](https://user-images.githubusercontent.com/62699947/92685150-ba806300-f354-11ea-873f-704b11d0af2f.jpg)

-Should be pre-filled with Donation Account n. Where n is the number of donation account other than the first one. 
-So Donation Account, then Donation Account 2, Donation Account 3....
![prefilled](https://user-images.githubusercontent.com/62699947/92685245-ea2f6b00-f354-11ea-8ff0-f020a8747554.jpg)

-Pre select as we have only one account type.
![preselect](https://user-images.githubusercontent.com/62699947/92685297-121ece80-f355-11ea-81da-c36de7cb7839.jpg)

-The account name should be what the user enters as Account Name in the first screen selection. The subtitle will be ‘Accept bitcoin’.
![accountnm](https://user-images.githubusercontent.com/62699947/92685373-34b0e780-f355-11ea-89f1-68b62ee6ca20.jpg)

-web view. No ‘-‘
![webview](https://user-images.githubusercontent.com/62699947/92685450-57db9700-f355-11ea-9da0-cf3eff0fe6c6.jpg)

-Should show 2FA as 2FA was enabled
![show2FA](https://user-images.githubusercontent.com/62699947/92685540-89546280-f355-11ea-97de-069a5f582eb8.jpg)

-Donation web view
![donatioweb](https://user-images.githubusercontent.com/62699947/92685591-a7ba5e00-f355-11ea-8c18-0b2afa132c77.jpg)

**Comment by Parsh** [comment]
Have fixed the following:

- Should be pre-filled with Donation Account n. Where n is the number of donation account other than the first one
- Should show 2FA as 2FA was enabled
- The account name should be what the user enters as Account Name in the first screen selection. The subtitle will be ‘Accept bitcoin
