### ISSUE TITLE
Add donation cause and settings 

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1516]
@hemantsain  I will call to discuss this. 
 - Add a text box above "Enter Donee name" as  "Enter cause"
-  Make donation description as text area

Once done with the UI changes required to donation API response to include cause
@antuz123  - do review once
@Parsh

**Comment by antuz123** [comment]
Also should be able to change the settings for the web view like cause, donee, description and should be able to stop the donation. Stopping will keep the account but disable the link and will show the message that this donation campaign has now closed.

**Comment by antuz123** [comment]
Ability to change:

1. Cause
2. Donee Name 
3. Description
4. Hide Transaction details (switch) 
5. Stop donation link
