### ISSUE TITLE
Manage Backup status after wallet Restoration.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1519]
-Still it is showing Backup Now instead of Confirm after recovery.
-It should show Green tick with Confirm button.
![20200910_131910](https://user-images.githubusercontent.com/62699947/92697201-9af33580-f368-11ea-9c90-63bb5ad65d24.jpg)

![20200910_132001](https://user-images.githubusercontent.com/62699947/92697235-af373280-f368-11ea-92a3-719df8539925.jpg)

**Comment by Parsh** [comment]
@cakesoft-swati to confirm the replication of Backup Now button showing up instead of Confirm.
