### ISSUE TITLE
Add an explanation before asking for permissions.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1524]
-Add an explanation before asking for permissions - contacts, camera, etc
-Why do we need access to your address book?
If you want to associate an address book contact with your Friends & Family in Hexa, you will need to give access to your address book. It is a good way to remember who the contacts are with their name and image
<the image>
Don’t worry these details don’t leave your phone and are for your eyes :eyes: only

**Comment by Parsh** [comment]
Updated description: Address book details like name and image are used for you to better recognize your Hexa F&F contacts. Don’t worry, they don’t get stored anywhere else and are for your eyes only.

Tested on iOS (wasn't able to figure out for Android).

**Comment by cakesoft-swati** [comment]
-Android permissions are missing.

**Comment by Parsh** [comment]
Wasn't able to figure out where the permission string for Android is located. @abdulmuneer22 Can you look into the android part of this? Thx.

**Comment by abdulmuneer22** [comment]
For this implementation has to be changed anyways wrt react-native upgrade, at the moment we are using expo-permissions and the same will not be used anymore.

@antuz123  , please move it to 1.1.3

**Comment by antuz123** [comment]
@Parsh - please add the required text for now if we can’t move it to the later part of the process.

**Comment by Parsh** [comment]
> Updated description: Address book details like name and image are used for you to better recognize your Hexa F&F contacts. Don’t worry, they don’t get stored anywhere else and are for your eyes only.
> 
> Tested on iOS (wasn't able to figure out for Android).

@antuz123 I've changed it for iOS, can't figure out for Android(as I've mentioned earlier).

**Comment by AliMeer** [comment]
Current Status: 
After the latest set of changes Android permissions are requested when they are needed and not at startup.
IOS Permissions are requested when they are needed and are accompanied by a reason why they are needed.

What is missing:
Android permissions dont have a reason when permissions are asked.

**What needs to be done:**
Before asking for permissions a new screen needs to be added to show what permissions are being requested and why. After this the permission should be requested.
This should be for:

- Contacts/Address book
- Camera



This is the information screen that should be shown before requesting any permission:
https://xd.adobe.com/view/00485057-d5b7-4b2b-641b-20216b3a38d5-7679/screen/d16432e9-fb2f-457c-98ae-0e9d95fe7db2/

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app version 1.3.2(170) on android and ios device.
