### ISSUE TITLE
RN uppgrade test on iphone 6 and lower end android phones

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1527]
Test on  iphone 6  
lower end android phones
lowest API version and Android 7 that we support

**Comment by cakesoft-swati** [comment]
-we can lower down the android threshold to 3GB from current 4GB, app works on 2GB RAM as well but is too sluggish. Seems like RN & performance upgrade did help. We should do this with 1.3.2 or later release though.

**Comment by Arpanjainson** [comment]
Test blue wallet - with 15 accounts
