### ISSUE TITLE
Donation Account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1539]
-Need a way to edit the details or stop donation.
![needaway](https://user-images.githubusercontent.com/62699947/93045711-87501380-f675-11ea-8207-eef60d9c5f9d.jpg)

-Way to hide the address of the receivers. 
-In show the message issue. Plus when setting are set up.
![waytohide](https://user-images.githubusercontent.com/62699947/93045908-13fad180-f676-11ea-87f5-39b661176e45.jpg)

**Comment by Parsh** [comment]
Disable donation page mech is already in place(including modification of other donation vars: name, cause, desc etc), the UI for the same is pending tho.
