### ISSUE TITLE
Send is unsuccessful.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1540]
-I am on latest 106 staging. Send is failing from both savings and checking. 
-Says insufficient balance
![File (37)](https://user-images.githubusercontent.com/62699947/93046634-eca50400-f677-11ea-953c-ddb59ceb7d94.jpg)

-The icons of accounts within the send flow account list are messed up.

**Comment by Arpanjainson** [comment]
Send was successful from Checking and savings initially but worked today

**Comment by Arpanjainson** [comment]
Send from savings was successful as well.
