### ISSUE TITLE
Health Check Successful.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1543]
-This screen is only in the security question section. 
-Did not get this message when we confirmed the pdf share after scanning first QR. 
-This screen should appear every time a shard is successfully backed up.
![File (41)](https://user-images.githubusercontent.com/62699947/93060354-9f349100-f68f-11ea-89d1-e0f4bfb619f8.jpg)

**Comment by antuz123** [comment]
We need to use a toast message here like in other parts of the app. Also, the second line is not needed.

**Comment by AliMeer** [comment]
@antuz123 I think this is not required anymore.
