### ISSUE TITLE
Change contact during manage backup- shows the new contact but then old contact shows up again

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1558]
https://bithyve-workspace.slack.com/files/UEB7M06KF/F01ABH69MKR/rpreplay_final1600233828.mp4

@antuz123

**Comment by Arpanjainson** [comment]
Change contact on  manage backup using Skip contact flow. The new contact F&F request awaiting shows up on the manage back up card for a 1 second and then the old contact shows up again
Tested on upgraded dev app 1.1.2 (107)

**Comment by Parsh** [comment]
@cakesoft-swati  Can you confirm this on the latest build? It may have already been resolved with other issues of manage backup.

**Comment by cakesoft-swati** [comment]
-Not able to reproduce this issue on version 1.2.0(122)
