### ISSUE TITLE
Skip contact is not a button during manage backup add keeper flow

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1559]

**Comment by Parsh** [comment]
This skip needs to have a button format(similar to what we have on the associate contact modal in Add a contact flow
<img width="1440" alt="Screenshot 2020-12-17 at 2 26 34 PM" src="https://user-images.githubusercontent.com/17980466/102465953-4f8da900-4074-11eb-88b2-2878ab335522.png">
)

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app version 1.4.0(190)
