### ISSUE TITLE
AC2: Account Management -- Home Screen Management -- Cancel/Hide Account

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1567]
#### Trigger
Long-pressing any of the account items on the home screen should activate some kind of "management mode". 

#### Functionality
- Account items have an option for canceling/hiding the account. 
    - On doing so the options given to the user are: 
      - Default visibility (always show), 
      - Duress visibility (show when wrong answer is provided), 
      - Hidden account (show only when correct answer is provided) 
      - Archived account (Accounts no longer in use)

#### Additional Notes
- All this meta data about the accounts should be recoverable when the wallet is restored
- The user can merge a maximum of 3 accounts/ xPubs (not from a technical perspective but more of a UI restriction)

**Comment by AliMeer** [comment]
Closing this one, there is too much history and not too much description. This is not in the roadmap as well.
An issue with the correct set of requirements can be created when required.
