### ISSUE TITLE
Keeper status:in F&F and Manage Bakcup.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1572]
-I had sent Anant a Keeper Request. He accepted it an hour later. It showed in his Wallet that he is my Keeper. He also sent me some test sats which I received.
-When I was checking manage backup, Anant was not showing as my Keeper. I refreshed few times. Still it was not showing Anant as my Keeper. So I resent him a Keeper Request. Please note that at this moment Anant's wallet shows him that he is my Keeper.
-He asked me to refresh my friends and family. I did and it showed Anant as my Keeper.
-Then he asked me to go to Manage backup and refresh, which I did. It did not show him as my Keeper. So the situation at this particular moment is this:
1) Anant's Wallet shows him that he is my Keeper.
2) In my wallet Anant is registered as a Keeper in the F and F section.
3) There is another Keeper Request that I had reshared and Anant had not accepted(as he had already accepted the first one)
4) Manage Backup does not show Anant as my Keeper in this particular moment.

-Expected  Behaviour: If someone has accepted a Keeper Request and it hasn't been registered in the Sender's Wallet, and the sender reshares the request a second, third, or tenth time. If any of the request was accepted, then that needs to be acknowledged by the sender's wallet and not nullifying previously sent requests and their response.

**Comment by Parsh** [comment]
I've tried to replicate it but failed. Seems like it has more to do with the UI element not getting updated rather than the failure of the underlying mech as both F&F screen & Manage Backup picks up there data from the same data store. 

@cakesoft-swati Can you please try to reproduce it?

**Comment by cakesoft-swati** [comment]
Unable to  reproduce this issue on 1.3.0(145),
