### ISSUE TITLE
AC1.1: Add an Account -- New Account Selection Screen

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1579]
## Top-Level Options given:
- Add a new Account
- Add a Service
-  Import a Wallet. 

## New Account options given:
- Test Account
- Checking Account, 
- Savings Account
- Donation Account (directly accept donations),
- Joint Account (Account with Friends and Family). 

## Services options given: 
- Swan Bitcoin (stack sats with Swan), 
- FastBitcoins.com (Use FastBitcoin Vouchers), 
- Whirlpool Account (powered by Samurai)

 
## Import a Wallet options: 
- Watch Only (View a non-Hexa wallet as an account)
-  Full Import (Fully import and manage a non-Hexa wallet) 

(🗒️  Each account setup will have a very different flow)

**Comment by antuz123** [comment]
new UX expected with 'Comming soon' and 'New'

**Comment by CypherPoet** [comment]
@antuz123 I added some initial graying and disabling functionality as part of #2197. Should we tag this to a later release so we can circle back when the design is finished?

**Comment by antuz123** [comment]
Let's see the UX, may not be very difficult to implement. We can take a call then @CypherPoet

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app version 1.4.0(180)

**Comment by cakesoft-swati** [comment]
-Joint Account (Account with Friends and Family).
This option is missing in New account options

**Comment by AliMeer** [comment]
Joint account is not available yet and will be available in a future release. We can close this issue.
