### ISSUE TITLE
AC1.1: Add an Account -- Test/Checking/Savings Account Setup Screen

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1581]
#### Available Options
- Don't mix funds - yes or no (Transactions in this account are kept separate from other accounts which improves the privacy of this account)
    - Default: No

- Account Visibility 
    - Always show (Always shows when you log in) 
        - Default
    - Hidden (Shows only when you want to) 
    - Duress mode (Shows when under duress).

**Comment by CypherPoet** [comment]
Leaving a note here that this has been taken out of the scope for the initial `AC` implementation.

**Comment by antuz123** [comment]
> #### Available Options
> * Don't mix funds - yes or no (Transactions in this account are kept separate from other accounts which improves the privacy of this account)
>   
>   * Default: No
> * Account Visibility
>   
>   * Always show (Always shows when you log in)
>     
>     * Default
>   * Hidden (Shows only when you want to)
>   * Duress mode (Shows when under duress).

We don't need these options for this phase.

**Comment by antuz123** [comment]
The item to test here is the ability to add these account types on the HS with the details.

**Comment by AliMeer** [comment]
Closing this one, there is too much history and not too much description. This is not in the roadmap as well.
An issue with the correct set of requirements can be created when required.
