### ISSUE TITLE
AC1.1: Dynamically list all accounts on the Home Screen

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1582]
> On the Home Screen, the new account with the account name appears with the description. A separate xPub/ xPubs is used for these accounts. The 2FA used is the same if Savings is selected.

**Comment by antuz123** [comment]
When a new account is added this should be the first to be seen on the HS. So LIFO order for accounts.

**Comment by CypherPoet** [comment]
@antuz123 #2191

**Comment by AliMeer** [comment]
CLosing this as this is being tracked via #2191
