### ISSUE TITLE
AC1.1 -- "Add New Account" Screen -- Integrate a Service

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1583]

**Comment by CypherPoet** [comment]
Right now, the idea is that we only allow this to function for Fast Bitcoins service accounts. And we also still need a follow-up story when there's a screen designed for giving users the option to make it its own account or default to a Checking Account.

**Comment by CypherPoet** [comment]
In addition to still needing design, the current plan is to implement the initial service integration functionality within the "Add" bottom-sheet flow on Home -- so I'm going to tag this for a slightly later release.

**Comment by AliMeer** [comment]
@antuz123 will be implementing this functionality. I think we might be having a single account for all BTC purchases. If so this issue can be closed.

**Comment by antuz123** [comment]
Not sure I completely understand the point here.

**Comment by AliMeer** [comment]
We can close this issue. We don't have this as a requirement at the moment.
