### ISSUE TITLE
AC3: Account Settings -- Top-Level Settings Screen

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1586]
### Top-Level Options
- Change Name and Description
- Reassign transactions
- Account Visibility
- Merge Account
- Archive Account

**Comment by CypherPoet** [comment]
Duplicate of https://github.com/bithyve/hexa/issues/1596

**Comment by CypherPoet** [comment]
Closed wrong issue

**Comment by antuz123** [comment]
For this phase, we need only: 

Change Name and Description

**Comment by AliMeer** [comment]
**Completed in 1.4.0:
C**hange Name and Description

**Will be done in a future 1.4.x release:**

Reassign transactions
Account Visibility
Merge Account
Archive Account

**Comment by cakesoft-swati** [comment]
--Verified this issue on dev app version 1.4.0(180)
