### ISSUE TITLE
AC3: Account Settings -- Change Name and Description Screen

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1587]
- Name (limited length to show on the Home Screen)
- Description (limited length to show on the Home Screen)

**Comment by CypherPoet** [comment]
Right now, all of the UI functionality for this seems to be in place. We just need to implement the corresponding backend logic in our [accounts saga](https://github.com/bithyve/hexa/blob/1192b1914cf407b62c919bbba6ad07acb19e1e08/src/store/sagas/accounts.ts#L1275)

(cc @Parsh)

**Comment by AliMeer** [comment]
This PR should address the missing backend logic: https://github.com/bithyve/hexa/pull/2381

**Comment by AliMeer** [comment]
This is fixed barring the below scenario which I have added as a new issue: https://github.com/bithyve/hexa/issues/2394
Default Checking, Savings and Test Account name change will work but will not be visible when app is restored. Restored app will show the default names of the default accounts.
