### ISSUE TITLE
Account Settings.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1598]
- on this (https://xd.adobe.com/view/a9aaad23-c5ea-4067-8734-cf64073bca02-fcf9/screen/5e47c223-3611-4b02-ba96-78c5569ebfd2/)XD screen 
-The Account Settings flow is a good example of how we can use the system-provided modal sheets on both Android and iOS instead of our own bottom sheets.
-This is a general example of the pattern I’m referring to, and in newer versions of iOS, you’d get much nicer-looking sheets.
In addition to some design differences, I think that from a code standpoint, leveraging React Navigation will make transitioning across all of the screens in this flow much simpler and more maintainable than having to manage a large amount of bottom sheets and their presentation states.

**Comment by CypherPoet** [comment]
@cakesoft-swati Was this meant to approve of the idea I brought up [here](https://xd.adobe.com/view/a9aaad23-c5ea-4067-8734-cf64073bca02-fcf9/screen/5e47c223-3611-4b02-ba96-78c5569ebfd2)?

If so, I can close this issue and make a note of it in #1586.
