### ISSUE TITLE
App freezing when the link is pressed and the app is not in the background

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1604]
This was seen several times in the current build on iOS. Can be replicated on Android as well?

**Comment by Arpanjainson** [comment]
Click here to accept Keeper request for AnantS Hexa wallet- link will expire in 24 hours
https://hexawallet.io/sta/atcg/AnantS/b1ce8f509dececd973505aba9116e495ee29bca4000bdc1ea7f62407e2bedb784cc0bd92181391e97d234de6b3fb144460133e492c92c89eadbfb657192344cb69bbc2240efa4aaba283fb05a2ccf538/num/861/1600590329683/v1.1.2

**Comment by cakesoft-swati** [comment]
Not happening with Android device.Tested on 1.1.2(115)
