### ISSUE TITLE
Images vanishing in upgrade. 

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1611]
-Images vanishing in upgrade. 
-We should pull images again after every upgrade/ restore.
![imgvanish](https://user-images.githubusercontent.com/62699947/93733899-ca216680-fbf4-11ea-9a98-2342f3b614eb.jpg)

**Comment by abdulmuneer22** [comment]
@cakesoft-swati  , please mention which env it was and build numbers you were testing out

**Comment by cakesoft-swati** [comment]
Tested on Staging 1.1.2(110) upgraded app.
