### ISSUE TITLE
Link opening on Safari not App

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1612]
Can be seen on Muneer’s phone

**Comment by Arpanjainson** [comment]
Please investigate around the app association file -
http://hexawallet.io/apple-app-site-association

**Comment by Arpanjainson** [comment]
@abdulmuneer22

**Comment by Arpanjainson** [comment]
@abdulmuneer22  can you test it on the latest dev app, I think it will fail.
Did the steps I send help or you tried something else>

**Comment by Arpanjainson** [comment]
this issue can be recreated only on very specific phones at this stage we can provide steps to reset the phone as per below section  App specific links are not opening on my iOS device?
on FAQ page - https://hexawallet.io/faq/
added as part of defect - https://github.com/bithyve/hexa/issues/1616

**Comment by cakesoft-swati** [comment]
-Verified this on Dev app version 1.3.0(155),Link opening on app.
