### ISSUE TITLE
Add link opening issue in FAQ

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1616]
Refer to issue - https://github.com/bithyve/hexa/issues/1612 try this https://developer.apple.com/forums/thread/123554

To refresh the apple-app-site-association on iOS 13.5.1
 Remove you App
 Go to Setting > Safari > Clean history and website data
 Hard reset your iPhone (Vol+ then Vol- then press and hold power button until Apple logo show up)
 Install the App after boot up I'm iPhone 11, It works for me.

Also we can try this https://developer.apple.com/library/archive/qa/qa1916/_index.html

**Comment by Arpanjainson** [comment]
added a section on FAQ page - https://hexawallet.io/faq/
App specific links are not opening on my iOS device?

**Comment by cakesoft-swati** [comment]
- we have added this section in FAQ.
