### ISSUE TITLE
Change contact - change status of shared key & share removal from previous guardian

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1629]
Change contact - 
Old contact card was green, changed to a new contact
The card still showed tick mark - while it should have  shown exclamation mark as the new contact was yet to accept the request

also the key should be deleted from the old contacts app.

**Comment by Parsh** [comment]
Fixed:
- Health updation mech post contact change
- Removal of share from previous guardian (was having a bug)

**Comment by cakesoft-swati** [comment]
-Health updating as expected.
-Filing a new issue to remove the share from previous guardian.
