### ISSUE TITLE
During batch send - Add recipient does not work when send is cancelled

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1639]
Select a contact and an amount and then go to the confirmation screen, hit back, and then try to click Add Recipient. Post adding a new recipient the amount entry screen gets skipped and we land straight on the confirmation screen w/ latest recipient having a zero send value.

**Comment by Parsh** [comment]
The send is being refactored and that might address this issue, will revisit if it still persists post send refactoring.

**Comment by cakesoft-swati** [comment]
-Verified this issue o dev app v1.5.0(248)
