### ISSUE TITLE
UX: Remove arrow buttons from Horizontally scrolling card lists

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1645]
Following up on [this discussion](https://bithyve-workspace.slack.com/archives/CEBLWDEKH/p1600882111003400)

<img width="336" alt="arrows" src="https://user-images.githubusercontent.com/46851636/94049788-042c6d00-fd9b-11ea-8872-7e35f656b50f.png">

**Comment by CypherPoet** [comment]
This is currently in place on #1663

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app version 1.4.0(180)
