### ISSUE TITLE
Optimise Android APK size by using App Bundle

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#1646]
We can optimise Android App release size by using App Bundle.

Current size is 35M and this can go down quite a lot.

Our current APK results in unused code and resources being sent to users. The app could be smaller if we used Android App Bundle. Once we optimise for device configurations the app size will be smaller.

**Comment by AliMeer** [comment]
This one is for Utkarsh.

**Comment by cakesoft-shashank** [comment]
Already done
