### ISSUE TITLE
Android App submission Warning for API Level 28

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#1647]
Note: This will be resolved by RN Upgrade however noting it here for tracking and ensuring resolution.

Warning from Google Play Store: Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance. Change your app’s target API level to at least 29.

**Comment by Arpanjainson** [comment]
@AliMeer I am in the play store console, cant see the warning, where should I look for this warning. May be it is fixed as you mentioned.

**Comment by cakesoft-swati** [comment]
Closing this issue as discussed with Ali sir.
