### ISSUE TITLE
Remove contact.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1648]
-After remove there should be an appropriate warning message for the user to confirm as this cannot be taken back.
-Removing a contact should also delete the contact from the other side with a notification.
![File (45)](https://user-images.githubusercontent.com/62699947/94109340-744ff700-fe5e-11ea-9ae2-e48f3b7a4da6.jpg)

**Comment by cakesoft-swati** [comment]
1.Expired Keeper and 'I am the Keeper of', should also be something you can delete
2.Contacts should be deletable irrespective of their status - Expired, Pending or Confirmed
3.When Contacts are deleted, the reflection should be on the other side also. A notification is sent to the counterparty and then the contact is deleted from the other end too
4.On any deletion, a message is shown to the user and only on confirming the same is the action is taken else the user can always go back
5.On deletion of any F&F, the balances from that F&F is not impacted

**Comment by Parsh** [comment]
Depends on #1819

**Comment by Parsh** [comment]
Update: As per today's discussion, confirmed keepers should also be removable(they basically downgrade to a normal trusted contact).

**Comment by antuz123** [comment]
These rules are still valid: https://github.com/bithyve/hexa/issues/1648#issuecomment-707572678

@Parsh - you can ignore your last comment.

**Comment by antuz123** [comment]
Also note that we should keep the version number on the communication channel for the other side to use.

**Comment by antuz123** [comment]
From a version compatibility side, you have to deal with the scenario where one side of the F&F is on the old version and one in new. As discussed today.

**Comment by cakesoft-swati** [comment]
-Verified this on Dev app version 1.3.0(155)
