### ISSUE TITLE
Formatting styles config in project folder

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#1650]
All developers should be using the same styles.

A lint/prettier config can be added to project root to ensure the project styles are picked up and not the developers styles.

This will make code easier to read.
PR will be easier to review as only code changes will be visible.
Will turn our code into a work of art.

**Comment by AliMeer** [comment]
@Parsh @abdulmuneer22 @CypherPoet 
Please suggest recommended styles to use for the project.

I am going to recommend standard lint styles for js with a few additional styles.

**Comment by CypherPoet** [comment]
@AliMeer We already have config files for eslint, tslint, and prettier, but it doesn't look like they're being used.

**Comment by AliMeer** [comment]
This is done, will look at merging this once dev branch is stabilised. This is a non QA task.
