### ISSUE TITLE
Setup Two Factor Authentication

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1658]
-Need the below flow accessible from setting too

**Comment by antuz123** [comment]
The 2FA should be shown not from the Send flow but as soon as the user comes to the Savings account. 

Also, the message does not go away till the user does not confirm that this has been done by entering a token code. So the user is not able to send or receive from the savings account till we have this setup. 

And once set up the details are anyway deleted from the app. The only option then is to reset the 2FA. So this option should be available from the 'settings' of the Account. It will be 'Having issues with the 2FA' option flow.

**Comment by antuz123** [comment]
This should apply to all 2FA accounts. But once set up for any one of them, all are set up. So if set up from Savings account, should not show on the Donations 2FA account. 

If the user enters Donations 2FA account first, then it should show there also till it is set up and confirmed

**Comment by cakesoft-swati** [comment]
-Verified this on Dev app version 1..4.2(201)

**Comment by cakesoft-swati** [comment]
-reset the 2FA option should be available from the 'settings' of the Account.
-This part is not yet done.

**Comment by cakesoft-swati** [comment]
-Verified his issue on dev app version 1.4.2(203)
