### ISSUE TITLE
UI changes of Donation account on Home screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1675]
-Apply the new add account image.
![File (46)](https://user-images.githubusercontent.com/62699947/94516809-4b57a980-0244-11eb-9733-6c66638cfe20.jpg)

-Need to land the user on home screen or on the donation account screen, currently test or checking account shows up.
![File (47)](https://user-images.githubusercontent.com/62699947/94516877-6d512c00-0244-11eb-8f8d-7711f39d7745.jpg)

-When we click on Donation account from Home screen,it lands on Savings account.

-Donation account name should show on home screen.
![File (48)](https://user-images.githubusercontent.com/62699947/94516995-aee1d700-0244-11eb-83d0-e030a256ac3a.jpg)

-2FA icon not showing on doantion account on home screen
![File (49)](https://user-images.githubusercontent.com/62699947/94517047-c7ea8800-0244-11eb-97fa-7f998ce89880.jpg)

**Comment by Parsh** [comment]
@cakesoft-nikhita I've already fixed the 2FA icon not showing part from this issue.

**Comment by antuz123** [comment]
Donation Webpage modal is getting cut (@cakesoft-swati can elaborate further on that) on iPhone 8 like screen. @cakesoft-nikhita

**Comment by cakesoft-swati** [comment]
-Need to land the user on home screen or on the donation account screen, still it lands on checking account 
![File (47)](https://user-images.githubusercontent.com/62699947/94516877-6d512c00-0244-11eb-8f8d-7711f39d7745.jpg)


-When we click on Donation account from Home screen,still it lands on Savings account.
