### ISSUE TITLE
Modal behaviour.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1677]
-When clicking on deep links the deep link modal does not appear and the screen is as shown below.
![deeplinkmodal](https://user-images.githubusercontent.com/62699947/94569545-76192080-028b-11eb-9f0d-4b28d02a83c4.jpg)

-[RPReplay_Final1601387771.zip](https://github.com/bithyve/hexa/files/5299619/RPReplay_Final1601387771.zip)

**Comment by CypherPoet** [comment]
@cakesoft-swati Is this testing against the latest code on `development`? We recently merge a few fixes for the bottom sheets: #1673

**Comment by CypherPoet** [comment]
Accidentally closed.

**Comment by cakesoft-swati** [comment]
-Tested on latest staging app version 1.2.0(126)
-Not able to reproduce this issue.
