### ISSUE TITLE
Copy address on web page 

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1682]
-Copy address on web page copies message as well.
[bitcoin:2N4VST6UaJp6LCjRypbPenSEbtAPobZZFTb?label=Hexa%20Donation&message=%7B%22donationId%22%3A%2286996f597dde0e9%22%7D]

**Comment by Parsh** [comment]
@Arpanjainson We would need to parse the bip21 URL and only copy the address part, I guess.

**Comment by antuz123** [comment]
@Arpanjainson - have you tested copying this address onto other wallets.
