### ISSUE TITLE
Modals on Home page.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1689]
- This is not the same as other modals in the app. We need to be consistent. 
-When the modals go up the background screen fades away very slowly .
-When you pull it down, sometimes it comes over the bottom menu.

![modalshome](https://user-images.githubusercontent.com/62699947/94677136-07df6700-033a-11eb-921d-dd64d6fa00bc.jpg)

**Comment by CypherPoet** [comment]
@cakesoft-swati I wasn't able to reproduce this or completely understand the meaning:

> When you pull it down, sometimes it comes over the bottom menu.

Could you please see if this is still an issue after we merge the changes for #1700, and perhaps create a separate issue describing the problem?
