### ISSUE TITLE
Loader screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1692]
-Currently the loader screens go away when the wallet exists and the key is found, need to use a flag on the screen loading and the messages to go away when the loading is done.
-This needs to be sequential as well. 
<img width="375" alt="E9B1DA74-44F2-4FCD-BD50-61DAF47B5568" src="https://user-images.githubusercontent.com/62699947/94680771-ec775a80-033f-11eb-822b-53bbbbb39666.png">

**Comment by abdulmuneer22** [comment]
List of actions triggered during the first render of the home screen and login

![Screenshot 2020-10-01 at 08 01 51](https://user-images.githubusercontent.com/4398018/94759015-6b11dd80-03bc-11eb-9b2c-a7feda26955d.png)
