### ISSUE TITLE
Bottom sheet changes 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1699]
1. All bottom sheets should behave the way they are behaving in the HS (fading the background, getting pulled down when clicked anywhere outside etc.) A new library has been used for it.
2. Alerts instead of Bottom Sheets for items like No Internet Modal - list will come from the UX team
3. Instead of nested bottom-sheets, use screens for level 2 onwards - changes will come from the UX team 
4. Android and iOS behave differently when it comes to bottom sheets. We should also use them accordingly. When using the default component from the library this behaviour should come up.

**Comment by abdulmuneer22** [comment]
an Alert would look like very basic UI, it's better to replace it with a snack bar

https://www.npmjs.com/package/react-native-snackbar

![image](https://user-images.githubusercontent.com/4398018/94770042-2b092580-03d1-11eb-827d-14f06d1e528c.png)

**Comment by CypherPoet** [comment]
For 1.4.0’s focus on account management, I think there’s an opportunity to address the bottom sheets on the primary screens it touches:

- Send Screen
- Receive Screen
- Some of the Pan-account settings screens

@antuz123 I'm going to make a separate issue with that specific focus -- and it might be good to use issue as one we can keep returning to to track the overall progress.

**Comment by CypherPoet** [comment]
With the changes on `feature/send-flow-refactoring`, all of the screens in the Send Flow should now be using the latest bottom sheet library/architecture. 

That said, there are many other parts of the UI that aren't, and I'm not quite sure that the scope of fully refactoring everything would be small enough to fit in the current sprint (@AliMeer @antuz123)

**Comment by CypherPoet** [comment]
Given that the main focus for this issue appears to have become centered around the Send UI, I'm going to mark this as implemented on the refactoring feature branch. (cc @AliMeer @antuz123)

**Comment by AliMeer** [comment]
Yes, our objective of s&r refactor was for the bottom sheets in S&R journey to be updated. I am actually going to close this as it’s more of a dev task.
