### ISSUE TITLE
AC2: Implement Account Management Menu from the Home > More menu

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1702]
**Precondition:** 

Accounts to be managed are already created/added.

**Flow:** 

Users can access this menu from Home > More > Account Management. Initially, this will offer options for reordering and activating a "View All" mode.

**Comment by cakesoft-swati** [comment]
Verified this issue on Dev app version 1.4.0(180)
-Account management option is implemented in more menu.
