### ISSUE TITLE
Incorrect health.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1703]
-Incorrect health. Just added accounts and I get this.
![inchealth](https://user-images.githubusercontent.com/62699947/94771664-69a0df00-03d5-11eb-9f67-1777aeb058d5.jpg)

**Comment by Parsh** [comment]
@cakesoft-swati Can you help me with replicating this error? I can see the health being perfectly updated on the current dev.

**Comment by cakesoft-swati** [comment]
-Unable to reproduce this issue on latest app version 1.3.0(151)
