### ISSUE TITLE
App is crashing.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1704]
-If you do not select an account type and enter an account name then the application crashes upon pressing the proceed button.

**Comment by abdulmuneer22** [comment]
@cakesoft-swati  , please add necessary information such as build number, is android or ios and necessary steps to reproduce it

**Comment by cakesoft-swati** [comment]
-It was happening on Dev app version 1.1.2(119).
-Now unable to reproduce this issue in version 1.2.0(121).
