### ISSUE TITLE
Changes on Loader modal.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1712]
-Need 6 cards here which rotate every 4 seconds and again starting from the first one. 
-Right now we have two cards. 
![tempFileForShare_20201005-110556](https://user-images.githubusercontent.com/62699947/95043584-daf4d080-06fa-11eb-8f87-03ba43d05369.jpg)

**Comment by antuz123** [comment]
1. Have total of 6 cards 
2. Changing every 4 secs 
3. Recycling after 6

**Comment by antuz123** [comment]
We have two cards, the 4 new will be: 

3. Introducing Donation Accounts: Start receiving donations directly in your Hexa Wallet, from anywhere in the world

**Comment by antuz123** [comment]
4. Hexa Savings Account: Don’t forget to set up your 2FA code on an authenticator app

**Comment by antuz123** [comment]
5. Friends & Family: Add contacts to Hexa and send sats w/o asking for address every time

**Comment by antuz123** [comment]
6. Non-custodial buys: Get sats directly in your wallet with FastBitcoins vouchers (*select locations)

**Comment by antuz123** [comment]
@abdulmuneer22 see above. 

Ideally these messages should be random if possible. 

In any case they should not impact performance at all.

**Comment by cakesoft-swati** [comment]
Loader screen messages are not rotating( ios 122).
![File (55)](https://user-images.githubusercontent.com/62699947/95159809-9fbad600-07bc-11eb-9f33-1ca2d4328f94.jpg)

**Comment by cakesoft-swati** [comment]
-App Version
1.2.0 (123)
-There was no message which needed this.
![therewas](https://user-images.githubusercontent.com/62699947/95212603-7d03de00-080b-11eb-8472-2444cf6b047d.jpg)

-
![?](https://user-images.githubusercontent.com/62699947/95212628-855c1900-080b-11eb-9adf-a3ee61b613d1.jpg)

![??](https://user-images.githubusercontent.com/62699947/95212649-8c832700-080b-11eb-8e11-873f7584008a.jpg)

**Comment by AliMeer** [comment]
Fixed in PR https://github.com/bithyve/hexa/pull/1744
Will be available in v1.2.0 # 124

**Comment by AliMeer** [comment]
Making further changes: https://github.com/bithyve/hexa/pull/1745
Simplified code and logic. Made the messages random.

**Comment by cakesoft-swati** [comment]
- only one message coming and it is not rotating like it is supposed to. 
-Also it is talking longer on the Home Screen (spinning wheel) than on the Loader Screen.

**Comment by antuz123** [comment]
These changes may not be needed.
