### ISSUE TITLE
Home Screen Performance - Data Structure

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#1733]
Modify and update the data structure to match reducers.
This should take into account the different level of detail required at different stages.
- Health - high level overall health status
- Health - detailed info on each share by share type
- Ability to list and types of accounts.
- High Level Account Information
- Detailed information on account

**Comment by CypherPoet** [comment]
Regarding the `High Level Account Information` and `Detailed information on account`, it might be worth keeping in mind that I'm architecting around both of these needs in the AC the changes that will eventually be merged in from #1663.

**Comment by AliMeer** [comment]
This is a duplicate and not required anymore as we have a number of issues in acc management to resolve this.

**Comment by AliMeer** [comment]
This is not relevant anymore.
