### ISSUE TITLE
Textual change on Donation details screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1739]
-Enter donation name NOT Enter donation account name.
![enterdonation](https://user-images.githubusercontent.com/62699947/95209933-8b9cc600-0808-11eb-9689-9b19a4181a6d.jpg)

-Small d (Donation details) 
-First text - Name for the donation 
-Second text - Organised by 
-Third text - Donation cause or description ‘Enable two-factor authentication’ Same text headers to be used in the settings screen as above.
![smalld](https://user-images.githubusercontent.com/62699947/95211025-b3d8f480-0809-11eb-8a67-b34729e167d0.jpg)

**Comment by AliMeer** [comment]
Fixed: https://github.com/bithyve/hexa/pull/1743
