### ISSUE TITLE
Web alignment.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1741]
-The heading did not come when initial donation name was given. It only came when saved from settings. Some data is not getting passed properly.
![File (56)](https://user-images.githubusercontent.com/62699947/95212885-ce13d200-080b-11eb-82a2-a95caa88114c.jpg)

-Not ended, paused.
![File (57)](https://user-images.githubusercontent.com/62699947/95289299-035e0580-0888-11eb-8f36-ce7409150eb3.jpg)

-I generated the link to be shared for someone to donate. Saved it on telegram. Then clicked on that link. This page opened up. But cannot see where someone could send bitcoin/sats:thinking_face: Also that box with “generating...” did not understand the purpose of it.
![File (61)](https://user-images.githubusercontent.com/62699947/95418119-64eba600-0954-11eb-8c94-3b35a58ea513.jpg)

**Comment by Arpanjainson** [comment]
generating.. test has been removed..
when paused, it will read donation has been paused...
The heading not showing up can not be re-created, @cakesoft-swati  please test it again

**Comment by cakesoft-swati** [comment]
-Verified this on Dev app version 1.3.0(155)
