### ISSUE TITLE
Confirmations.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1751]
-Showing 0 confirmations even though showing 5 confirmation on block explorer.
![showing0](https://user-images.githubusercontent.com/62699947/95290679-71f09280-088b-11eb-9ccb-a492a9c3f2b8.jpg)

**Comment by Parsh** [comment]
@cakesoft-swati Unable to replicate. Please try it out once and let me know if this issue is still there.

**Comment by cakesoft-swati** [comment]
Unable to replicate this,verified on Hexa app version 1.3.0(151)
