### ISSUE TITLE
Account Settings

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1752]
1. Every account should have a settings option .
2. For any 2FA account, the settings will have an option to show the 2FA details. It will show the same flow as reset 2FA/ having problems with 2FA/ Need help.
3. The 2FA token should be visible as soon as the user comes to the account, not from inside Send. And there should be no back button. The user will have to confirm that they have set it up by entering a token before using the Savings/ 2FA account. The user will not be able to see or use the account without confirming the token.
 4. When there are multiple 2FA accounts and the user has set it up at one place, both become active but the user is shown a message that they need to use the same 2FA code as when they set it up for the other account. 
![accsettings](https://user-images.githubusercontent.com/62699947/95290982-2b4f6800-088c-11eb-8582-3843ea85a97c.jpg)

**Comment by CypherPoet** [comment]
Note that the Settings button and related screens are being implemented as part of #1586. It might be better to break the other items here into two issues:

1. UI changes for the account details screen to handle the current 2FA state. 
2. Additional functionality for the Account settings screen to handle configuring 2FA.

(cc @antuz123 @AliMeer @cakesoft-swati)

**Comment by antuz123** [comment]
Seems to be a duplicate @cakesoft-swati - please check and combine.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(243)
