### ISSUE TITLE
UI issues on Donation web view.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1760]
-Alignment is not proper for setting icon n save button on Android device.
![20201007_155049](https://user-images.githubusercontent.com/62699947/95319448-847fc180-08b5-11eb-8c26-6e9f2a9bedd7.jpg)

-![20201007_155135](https://user-images.githubusercontent.com/62699947/95319466-8a75a280-08b5-11eb-91df-7538a55df59a.jpg)

-While entering the doantion details,the screen is going up in android device.

**Comment by Arpanjainson** [comment]
will retest it..
