### ISSUE TITLE
Keeper request.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1763]
-These are Keeper requests. Showing as contact requests. The language is incorrect.
![theseare](https://user-images.githubusercontent.com/62699947/95329199-36be8580-08c4-11eb-93ae-689f98e98a2e.jpg)

**Comment by Parsh** [comment]
This is what it shows as of now(for both keeper & non-keeper contact request acceptancee). @antuz123  Do we want to have some change in that?

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-21 at 12 02 42](https://user-images.githubusercontent.com/17980466/105299979-b6a4fd00-5be0-11eb-85bf-7144b7a02f5e.png)

**Comment by cakesoft-swati** [comment]
Verified this issue on staging app v1.4.5(228)
