### ISSUE TITLE
Xcode 11.0, 11.1 and 11.4 will be deprecated on November 5th

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#1777]
Assess if this impacts us and if we need to update our build configuration:

`Xcode 11.0, 11.1 and 11.4 will be deprecated on November 5th. Please update your build configuration if you are using those Xcode versions.`

**Comment by cakesoft-utkarsh** [comment]
This should not affect us. 
If you could just make sure we are using Xcode 11.7 or 11.6 on App Center for building our app.

**Comment by AliMeer** [comment]
Moving this to 1.3.0 as this is required before 5th Nov.
This is already done but needs verification on live. Dev and Staging builds on app centre have been verified.
