### ISSUE TITLE
Contact access permissions.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1781]
-The permission should be asked for later when the contacts are used not at the beginning. 
-Also the permission message is missing.
[cntpermission.zip](https://github.com/bithyve/hexa/files/5353259/cntpermission.zip)

**Comment by antuz123** [comment]
@cakesoft-swati - not sure if this was fixed. Please check.

**Comment by AliMeer** [comment]
This was happening on iOS as well.
Its fixed for iOS. Can we test on Android as well please?
![Uploading Screenshot 2020-11-02 at 17.59.47.png…]()

**Comment by AliMeer** [comment]
Its fixed for Android as well in 153. Please test.

**Comment by cakesoft-swati** [comment]
-The permission message is missing on android.
![Screenshot_20201103-163426_Permission controller](https://user-images.githubusercontent.com/62699947/97977951-f1be3e00-1df2-11eb-9be8-2a7ccb8b2dba.jpg)

**Comment by AliMeer** [comment]
Android shows the reason for the permission only if the user has denied the permission once. This is the default Android behaviour.

Attached is a screenshot when going back to contacts after denying the permission.

<img width="287" alt="Screenshot 2020-11-03 at 11 38 13" src="https://user-images.githubusercontent.com/7535475/97981422-2d90dd80-1dca-11eb-8d6a-0d4e738b8410.png">

**Comment by AliMeer** [comment]
Showing an alert before the permissions alert doesn't seem like a good experience either. 
The content in the alert isn't formatted as well.

Its best to leave it as it is, or add a text area on the screen or a new screen to display the required reason.

**Comment by antuz123** [comment]
The way apps behave is to show a message before permission is asked. We should do the same. Alerts have a UX component now as per the UX team we will use that for showing the pre-permission message. @AliMeer

**Comment by AliMeer** [comment]
> The way apps behave is to show a message before permission is asked. We should do the same. Alerts have a UX component now as per the UX team we will use that for showing the pre-permission message. @AliMeer

So looks like what we are proposing to do here is the same as this ticket fro 1.3.2 https://github.com/bithyve/hexa/issues/1524

**Comment by antuz123** [comment]
yes seems to be a duplicate @AliMeer 

@cakesoft-swati - such duplicates need to be combined.

**Comment by antuz123** [comment]
Needed for both iOS and Android.

**Comment by Arpanjainson** [comment]
https://xd.adobe.com/view/00485057-d5b7-4b2b-641b-20216b3a38d5-7679/screen/d16432e9-fb2f-457c-98ae-0e9d95fe7db2/

**Comment by AliMeer** [comment]
Closing, this will be done as part of https://github.com/bithyve/hexa/issues/1524
