### ISSUE TITLE
QR scanner.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1782]
-After using the QR scanner (main menu bottom middle button) and hiding it’s “tab” the camera stays toggled on for no reason. -Only when the app is open, goto different app it’s gone, switch back in and camera toggles on.

**Comment by CypherPoet** [comment]
Ideally, this can be tackled as part of https://github.com/bithyve/hexa/issues/1833

**Comment by CypherPoet** [comment]
Closing as a duplicate of #1833.
