### ISSUE TITLE
Android ram and version check - perf

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1792]

**Comment by Arpanjainson** [comment]
Working fine ion 4GB ram phone. check 3GB ram as well

**Comment by Arpanjainson** [comment]
REdmin Not 8  - app crashed while test account send max, - app install - 25 seconds, subsequent login - 20 seconds.

**Comment by Arpanjainson** [comment]
Samsung Galaxy A8 - 2GB ram

**Comment by Arpanjainson** [comment]
added a section on FAQ page -  https://hexawallet.io/faq/
App specific links are not opening on my iOS device?

**Comment by Arpanjainson** [comment]
Got this message
![image](https://user-images@antuz123 hubusercontent.com/8697909/97843826-f2ca6f00-1d0f-11eb-824e-fb9d33fe8850.png)


@antuz123  on android low end devices on browserstack

**Comment by Arpanjainson** [comment]
I think we can move forward to release the app for 3GB android phone running android 7 and above,

**Comment by cakesoft-swati** [comment]
-I have tested the Hexa app on lower end Android device i.e. Samsung Galaxy J7 Prime which has 3GB RAM, the app is working on it.
I also tested it on the Galaxy Note 8 which has 3GB RAM and Android V7.1 but I got an error for this device that it does not support the build OS version.

**Comment by antuz123** [comment]
We need to test against other wallet and open it up if needed to all.

**Comment by Arpanjainson** [comment]
https://browser.geekbench.com/android-benchmarks

**Comment by Arpanjainson** [comment]
Other wallet works fine on 3GB RAM phone. API version 7 and above. Pretty responsive.
Need to check on lower version phones but then will need to lower API version.

**Comment by antuz123** [comment]
@Arpanjainson - this was the understanding ad of yesterday and even before. We need to close it. I don’t see this has moved at all

**Comment by Arpanjainson** [comment]
Worked on 2GB RAM actual motorola device, slower than the phones on browser stack
