### ISSUE TITLE
Minimize homepage modals

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1810]
Concern raised by user -
https://twitter.com/i/status/1314439541315559424
Also, smoothen this out, this happens to all those tabs. It bugs me that it’s not gone when I swipe it down, nor does it work to just tap the same button again to close the tab, out of intuition I tried this

**Comment by Arpanjainson** [comment]
@CypherPoet  - lets discuss during evening call

**Comment by CypherPoet** [comment]
Noting here that I'm going to try and implement [this approach](https://github.com/bithyve/hexa/issues/1810#issuecomment-707778069) after discussing it with @antuz123.

**Comment by CypherPoet** [comment]
Accidentally closed -- this should be kept as `Fixed` pending QA.
