### ISSUE TITLE
Account Management - Data Architecture Refactoring - Support New Account Shell Creation

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1811]
[This](https://github.com/bithyve/hexa/blob/4f045217b9c628f673aaea27533d596f1caeb02c/src/store/sagas/accounts.ts#L1140) is the starting point for where I'm envisioning needing more backend logic for creating a new account, persisting it in the database, and ultimately adding an `AccountShell` instance to the accounts reducer.

**Comment by AliMeer** [comment]
Dev task for implementing new UI data framework. Closing as this has been completed.
