### ISSUE TITLE
Account Management - Data Architecture Refactoring - Support Transaction Reassignment

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1812]
[This](https://github.com/bithyve/hexa/blob/4f045217b9c628f673aaea27533d596f1caeb02c/src/store/sagas/accounts.ts#L1191) is the starting point for where I'm envisioning needing more backend logic for handling transaction reassignment.

**Comment by Parsh** [comment]
Transaction re-assignment is descoped from 1.4.0(stage 1).
