### ISSUE TITLE
Account Management - Data Architecture Refactoring - Support SubAccount Settings Updates

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1813]
[This](https://github.com/bithyve/hexa/blob/4f045217b9c628f673aaea27533d596f1caeb02c/src/store/sagas/accounts.ts#L1169) is the starting point for where I'm envisioning needing more backend logic for persisting updates to a sub-account's settings in the database, and ultimately handling the result of this operation in our account reducer.

**Comment by AliMeer** [comment]
@antuz123 I think we need to define what settings a sec sub account can have. Based on that this issue can be implemented.

**Comment by antuz123** [comment]
I am not sure I understood, is it account or sub-account? There are no settings at sub-account level. @AliMeer

**Comment by AliMeer** [comment]
We don’t have any settings for a sub account, we can pick this up when we have a need for sub account settings.
