### ISSUE TITLE
Account Management - Data Architecture Refactoring - Support AccountShell Merges

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1814]
[This](https://github.com/bithyve/hexa/blob/4f045217b9c628f673aaea27533d596f1caeb02c/src/store/sagas/accounts.ts#L1220) is the starting point for where I'm envisioning needing more backend logic to handle merging one `AccountShell`'s sub-accounts into the sub-accounts of another `AccountShell` -- and ultimately handling the result of this operation in our accounts reducer.

**Comment by AliMeer** [comment]
This one is out of scope for 1.4.0

**Comment by AliMeer** [comment]
Closing this one, there is too much history and not too much description. This is not in the roadmap as well.
An issue with the correct set of requirements can be created when required.
