### ISSUE TITLE
Account Management - Data Architecture Refactoring - Clean up Accounts Reducer state

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1815]
One of my goals with the new `AccountShell` and `SubAccountInfo` models is to allow the Accounts reducer state to hold  lists of theses in its state, and not have to hard code separate sets of properties for each individual account the way it seems to be doing now.

As I indicated in the TODO [here](https://github.com/bithyve/hexa/blob/4f045217b9c628f673aaea27533d596f1caeb02c/src/store/reducers/accounts.ts#L55), I think a lot of the current reducer properties can be removed, and properties like `balances`, `transactions`, and `averageTxFees` can be a part of each individual `SubAccountInfo` instance in some way.

Furthermore, I'd suggest removing the [catch-all `loading` property](https://github.com/bithyve/hexa/blob/4f045217b9c628f673aaea27533d596f1caeb02c/src/store/reducers/accounts.ts#L72), and track various loading states in a more fine-grained manner depending on the individual operation being performed. What I'm doing [here](https://github.com/bithyve/hexa/blob/4f045217b9c628f673aaea27533d596f1caeb02c/src/store/reducers/accounts.ts#L143) with the flags for `isGeneratingNewAccount`, etc. is sort of what I have in mind.

[These are](https://github.com/bithyve/hexa/blob/4f045217b9c628f673aaea27533d596f1caeb02c/src/store/reducers/accounts.ts#L129) [some other TODOs](https://github.com/bithyve/hexa/blob/4f045217b9c628f673aaea27533d596f1caeb02c/src/store/reducers/accounts.ts#L135) I noted related to cleaning up the reducer structure.

**Comment by AliMeer** [comment]
It might be worth breaking this down into more tickets as part of this has been done in 1.4.0 and the rest will be follow in 1.4.x

**Comment by AliMeer** [comment]
We have implemented what was required for 1.4.0 scope, moving this to 1.4.1 for the remaining items

**Comment by AliMeer** [comment]
in 1.5.0 lets review if we are in a position to cleanup based on what has been implemented and refactored in the previous releases.
