### ISSUE TITLE
Account Management - Data Architecture Refactoring - Remove Exchange Rates from Accounts Reducer

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1816]
As indicated [here](https://github.com/bithyve/hexa/blob/4f045217b9c628f673aaea27533d596f1caeb02c/src/store/reducers/accounts.ts#L122), I'm not entirely sure `exchangeRates` is a concern of the Accounts reducer. I'd recommend placing it somewhere else -- perhaps even making a standalone reducer for it -- and also making its structure more strongly-typed (as opposed to `any?`).

**Comment by AliMeer** [comment]
Let's pick this up whenever we are working on exchange rate relation code. Not a high priority item.

**Comment by AliMeer** [comment]
Closing this as it’s covered by exchange rate delta requirements
