### ISSUE TITLE
Account Management - Data Architecture Refactoring - Replace "Service Type" string usage with strongly-typed `SubAccountKind` and `ServiceAccountKind` enums

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1817]
Several parts of the code are relying on performing string comparisons against [a list of "service types"](https://github.com/bithyve/hexa/blob/4f045217b9c628f673aaea27533d596f1caeb02c/src/common/constants/serviceTypes.ts#L1).

Given that these seem to be more like different kinds of accounts -- one of which might be some kind of service-integrated account -- I found that using strongly-type [`SubAccountKind`](https://github.com/bithyve/hexa/blob/feature/account-management/src/common/data/enums/SubAccountKind.ts) and [`ServiceAccountKind`](https://github.com/bithyve/hexa/blob/4f045217b9c628f673aaea27533d596f1caeb02c/src/common/data/enums/ServiceAccountKind.ts#L1) enums will give a much more clear, readable, and maintainable way to organize this and dynamically worth with different account varieties in the UI.

**Comment by AliMeer** [comment]
Lets see if we are in a position to identify if this needs any more work based on the acc management and send refactor work that we have done so far

**Comment by AliMeer** [comment]
This is being done as we come across any instances that require a change.
