### ISSUE TITLE
Trusted Channel Synchronisation

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#1819]
Requirements:
- Last seen updates
- Removal of Trusted Contact from contact's device(related to issue #1648)
- Moving away the TC-setup sync saga from the login screen
- Forwarding new FCM to trusted contacts post wallet restoration
- Replacing Health Schema w/ last seen updates via trusted channels(while maintaining backward compatibility)

Impact Zones:
- Login: Improved performance as the TC-setup sync saga leaves to more apt screens
- F&F Screen: Auto syncs trusted channels once per session, however, on hard refresh(user pull-down) all channels are synched.
- Send Screen: Syncs the selected contact(s) for setup, removal, and other details on the confirmation screen(once per session) and take actions accordingly
- Manage Backup Screen: Syncs the Guardian-TCs and updates the health of the app accordingly as per the last updated status from the channels(if available).

**Comment by Parsh** [comment]
@antuz123 Do add the points, in case, I've missed.

**Comment by Parsh** [comment]
Trusted Channels must contain the version number(so that you can process data accordingly)

**Comment by cakesoft-swati** [comment]
-Discussed this with Parsh.
