### ISSUE TITLE
Issues in RN upgrade build.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1830]
1.Deep link modals are not opening up properly for keeper request. Might be happening for all types of dl
 - Works sometimes only.
![Image from iOS](https://user-images.githubusercontent.com/62699947/96227034-1d4ac700-0fb1-11eb-9baa-19dc44bc9234.png)

2.Try entering OTP to accept share on IOS, one has to continuously do upper case..the cursor does not move to the next box easily.

3.It is taking 14/15 sec on home screen.
-Tested on 1.2.1(135)

**Comment by AliMeer** [comment]
This should be retested in 144.
If there are is more than one defect then each should have its own issue is.

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev version 1.3.0(145)
-All the points are related to the same issue that's why I mentioned it in this issue.
