### ISSUE TITLE
App Refactoring & Component Standardization: Number Keypad Component

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1850]
The code for this is currently very verbose and is [being duplicated on several screens](https://github.com/bithyve/hexa/search?q=%3CView+style%3D%7Bstyles.keyPadRow%7D%3E). We should abstract it to a single, reusable component.

[Design example](https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/acafd6d2-8c52-4ea1-9402-159d94716402)

**Comment by AliMeer** [comment]
This is not required anymore. Closing.
