### ISSUE TITLE
Back action

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1852]
-It’s not going back when I swipe left to right.
![File (64)](https://user-images.githubusercontent.com/62699947/96675390-6b344600-1388-11eb-9e77-c53bdbd12747.jpg)

**Comment by antuz123** [comment]
Also, the back button has a very small reaction area. Needs to be looked at and made uniform for the whole app.

**Comment by antuz123** [comment]
This needs to be for all Back buttons. The system action of 
swipe from left to right (for iOS) and 
bottom system back button (for Android)

**Comment by cakesoft-nikhita** [comment]
> Also, the back button has a very small reaction area. Needs to be looked at and made uniform for the whole app.

For this, I already did changes in my last months commits as Muneer suggested "hitSlop" property for the large touchable area and it's working fine. For reference, I just attaching one screenshot here
![Screenshot 2020-11-13 at 10 12 08 AM](https://user-images.githubusercontent.com/37994396/99029750-4901a280-2599-11eb-9ed7-97eae86cddc3.png)

**Comment by cakesoft-swati** [comment]
-Verified this on Dev app version 1.3.2(168)
