### ISSUE TITLE
Issues on RN Upgrade

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1854]
RN upgrade:
1.UP1(1.2.0(128) > 1.2.1(138)): - F&F list and donation account is lost after restoration of wallet.

2. FI(1.2.1(138)) :- Getting error on Personal copy(Unable to share pdf)
![Screenshot_20201021-122358_hexa dev](https://user-images.githubusercontent.com/62699947/96693360-c5430480-13a4-11eb-8288-13dd56558efa.jpg)

 - contact not getting confirmed Immediately,I've to refresh it multiple times.
 - If contact is not getting confirmed on senders side n it is accepted by receiver then in this case app getting crash when I click on confirmed contact on receivers side.

**Comment by AliMeer** [comment]
This doesn't seem to be an issue in the latest dev app # 144

**Comment by cakesoft-swati** [comment]
Verified this issue on staging app version 1.3.0(145)
