### ISSUE TITLE
Showing zero sats while sending.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1864]
-Test account shows available to spend 10000 sats but shows 0 on the send sceeen. 
-Transaction does not show up either.
![Image from iOS (1)](https://user-images.githubusercontent.com/62699947/96826374-dfd2b780-1450-11eb-86a6-faf9780cb0c8.png)

![Image from iOS (2)](https://user-images.githubusercontent.com/62699947/96826433-fd078600-1450-11eb-9b57-c7c5edcf6727.png)
[Tested ondev version 1.2.1(140)]

**Comment by AliMeer** [comment]
This doesn't seem to be an issue in the latest dev app # 144

**Comment by cakesoft-swati** [comment]
Able to see the same issue on Dev/staging app version 1.3.0(145)

**Comment by Parsh** [comment]
Test txn takes a while to come from BitHyve faucet and therefore for the sake of the user we've hardcoded the 10K value on the test card, however, till the test txn arrives the send would naturally show 0 sats to spend as no uxto is available for the same.

**Comment by antuz123** [comment]
Closing this issue.
