### ISSUE TITLE
Transactions.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1865]
-This screen is to explain that the test account showed funded but the txn did not show up.. other accounts when funded manually via faucets worked fine.
![Image from iOS (3)](https://user-images.githubusercontent.com/62699947/96826927-0e9d5d80-1452-11eb-8b9d-5d2b80e3d152.png)

**Comment by Parsh** [comment]
Duplicate of #1864

**Comment by antuz123** [comment]
Coxed as per the duplicate.
