### ISSUE TITLE
Floating button.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1867]
-The FF floating button looks like this on smaller screen.
-It can be lowered a bit.
<img width="375" alt="201E1C4B-46D2-40D2-A196-19DAA4F45E0A" src="https://user-images.githubusercontent.com/62699947/96827925-41e0ec00-1454-11eb-9f59-1b6424953c6b.png">

**Comment by cakesoft-swati** [comment]
<img width="375" alt="201E1C4B-46D2-40D2-A196-19DAA4F45E0A" src="https://user-images.githubusercontent.com/62699947/97280990-f7e87380-1862-11eb-82f1-434e71a47f3c.png">
Uable to see any changes[Tested on Iphone 7,dev app version 1.3.0(145)]

**Comment by CypherPoet** [comment]
I think the idea is that the button does still overlap a little bit. [This is the design](https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/469863b0-1fcc-4a38-b9dd-7a432d242b8a/) I was going by. (cc @antuz123)

**Comment by antuz123** [comment]
Yes it should overlap. It is a ‘floating’ button. Not sure what is the bug exactly.

**Comment by antuz123** [comment]
Check with UX

**Comment by antuz123** [comment]
@Arpanjainson - pls have a look at what is pending from UX. There seem to be a lot of small tasks.

**Comment by Arpanjainson** [comment]
Discussed with Sumaiah
