### ISSUE TITLE
Donation account transaction received in savings account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1868]
-RNU: FI
I copied donation acc address ,sent some sats from test account but everytime I received it in savings account not in donation acc and when we refresh the donation account   app crashes.
[Same happening on dev(140), transaction received in savings account, only app is not crashing in dev.]
![Screenshot_20201022-133322_hexa dev](https://user-images.githubusercontent.com/62699947/96848231-cb52e700-1471-11eb-9add-e6f4c9982ca1.jpg)

-Total balance got double on upgrade(133-139)
![Screenshot_20201022-132810_hexa dev](https://user-images.githubusercontent.com/62699947/96848286-dc035d00-1471-11eb-8b48-36980bb34b6f.jpg)

**Comment by Parsh** [comment]
Unable to replicate the above issue w/ the current dev branch. 

No transactions, from test acc, ended up landing on the savings acc
<img width="1440" alt="Screenshot 2020-10-22 at 3 18 12 PM" src="https://user-images.githubusercontent.com/17980466/96857082-35708980-147c-11eb-8ee9-f9ca55839bbf.png">
<img width="1440" alt="Screenshot 2020-10-22 at 3 18 15 PM" src="https://user-images.githubusercontent.com/17980466/96857111-3d302e00-147c-11eb-8104-32fb1a4f7846.png">
<img width="1440" alt="Screenshot 2020-10-22 at 3 18 18 PM" src="https://user-images.githubusercontent.com/17980466/96857124-40c3b500-147c-11eb-8252-1b1999534103.png">

Also, the receiving address for savings and donation acc has been consistently different.
<img width="1440" alt="Screenshot 2020-10-22 at 3 28 54 PM" src="https://user-images.githubusercontent.com/17980466/96857387-8ed8b880-147c-11eb-982d-5787ab64d608.png">
<img width="1440" alt="Screenshot 2020-10-22 at 3 29 02 PM" src="https://user-images.githubusercontent.com/17980466/96857419-98fab700-147c-11eb-9272-bb858a3b8fd5.png">

The same has been the case w/ a non-2FA donation account
<img width="1440" alt="Screenshot 2020-10-22 at 3 31 51 PM" src="https://user-images.githubusercontent.com/17980466/96857547-b9c30c80-147c-11eb-85c3-d048a34d794e.png">

The above tests were done on iOS simulator. I've also tried to replicate this on android build 140(from app center). The case remains the same.
![Screenshot_20201022-154158](https://user-images.githubusercontent.com/17980466/96858204-95b3fb00-147d-11eb-97fe-383a4bf1a3ff.jpg)
![Screenshot_20201022-154222](https://user-images.githubusercontent.com/17980466/96858213-98aeeb80-147d-11eb-9a51-cceefe1367a3.jpg)
![Screenshot_20201022-154242](https://user-images.githubusercontent.com/17980466/96858218-99478200-147d-11eb-8b2a-15cdbe28dfe4.jpg)

**Comment by Arpanjainson** [comment]
@Parsh @AliMeer  I got the same issue on RN 142  build ios

**Comment by cakesoft-swati** [comment]
Same issue on RNU 142-FI

**Comment by Parsh** [comment]
Was happening due to RN branch having an older version of donation code.

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev version 1.3.0(145),unable to reproduce this issue.
