### ISSUE TITLE
Disable back option while logging

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1869]
-A user is having Galaxy s20.His wallet gets frozen right at Create password stage. He said that ,Blue light filter is blocking the buttons and it works without Blue light Filter.

-While login, if the back button is pressed, the app gets frozen on the next login.
-This was on Android. The user hits back as it takes time and then kills the app and tries again.On trying again the wallet does not log in.

**Comment by cakesoft-swati** [comment]
I have tried this on My Android device which is Samsung Galaxy A70 but,I didn't face this issue with/without Blue light Filter.

**Comment by AliMeer** [comment]
Is this still an issue? I have not experienced this in the past few releases.

**Comment by cakesoft-swati** [comment]
This issue was only on Samsung Galaxy s20.I tried it on different android device which is having Blue light filter but,unable to reproduce this issue.

**Comment by antuz123** [comment]
Blue light may not be the issue but the system given back button should be disabled. Android has an explicit button while iOS has swipe right for the back. Both need to be disabled.

**Comment by cakesoft-swati** [comment]
Verified this issue on Dev app version 1.3.0(156).
-Now the back button is disabled while loggin.
