### ISSUE TITLE
Deep links for keeper request is not opening the modal

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1872]
App opens but no modal shows up.
RN upgrade - FI - 142

Try this
Click here to accept Keeper request for Devrnnew Hexa wallet- link will expire in 24 hours
https://hexawallet.io/dev/tcg/Devrnnew/1fba69291cbeb83edacfdb7774770880b7452b18b802600c840e0818aef3096cee09a78727c0a3af584409625e8f9468f9f4593296424ce691ebdbcdd15c6ad4085e354b19d3e0a73a00e7e522f46163/num/727/1603394083481/v1.2.1

**Comment by AliMeer** [comment]
hexa://home/dev/tcg/Devrnnew/1fba69291cbeb83edacfdb7774770880b7452b18b802600c840e0818aef3096cee09a78727c0a3af584409625e8f9468f9f4593296424ce691ebdbcdd15c6ad4085e354b19d3e0a73a00e7e522f46163/num/727/1603394083481/v1.2.1

**Comment by AliMeer** [comment]
Click here to accept contact request from Ali Hexa wallet - link will expire in 24 hours

https://hexawallet.io/dev/tc/Ali/c6a6a3aa2f272429298782da6a70778981231968dc8ac92a514db35001b15972ee39838004b33f0666af7120c18aeb9470231109d837870ba843c235dd9ec30f7c157b2e7a1cad7930f481b5bdc91fbe/num/787/1603667995989/v1.2.1


Click here to accept Keeper request for Ali Hexa wallet- link will expire in 24 hours

https://hexawallet.io/dev/tcg/Ali/063e5751f045a3eedf66b691073ea5b76ca2fea75e2463a8d9df7776be9a34a9805eb947270b2b2655534b5c9dd8b6e882a70e277e9893678d8602c7a9fcf2aa576277de6ce9c5aaf94b603887d2fe36/otp/xxx/1603668068825/v1.2.1

**Comment by AliMeer** [comment]
Fixed in 144

**Comment by cakesoft-swati** [comment]
-Dev version 1.2.1(141)
-Deeplinks open when app is in background but not after login.After clicking on deep link,app opens but no modal shows up.

**Comment by cakesoft-swati** [comment]
-Deep links for keeper request is now opening the modal
