### ISSUE TITLE
Transaction view is empty

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1873]
Happens across all accounts - txns are present on the account but do not show up on the Txn modal.
![image](https://user-images.githubusercontent.com/8697909/96919842-f9fcac00-14c9-11eb-84c2-66fed75771fc.png)

**Comment by Arpanjainson** [comment]
RN upgrade - 142

**Comment by CypherPoet** [comment]
I'm not quite sure what the root cause is, but for prioritizing our efforts, it's worth noting that fixing issues like this will benefit greatly from the data flow and data modeling changes being developed on the `feature/account-management` branch.

**Comment by AliMeer** [comment]
This doesn't seem to be an issue in the latest dev app # 144

**Comment by cakesoft-swati** [comment]
-Able to see the transaction view in 1.3.0(145)
