### ISSUE TITLE
Notification for transactions -

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1874]
If a transaction notification is touched, the specific account with the transaction detail screen is shown.
" notification should contain the transaction ID of the transaction to be shown"

**Comment by Parsh** [comment]
@Arpanjainson Do we still need this?

**Comment by summikhan11** [comment]
@ASN-BitHyve this would be one of the notifications

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(489)
