### ISSUE TITLE
Keeper request link not refreshing on reshare after expiry

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1881]
Sent on Saturday from 143 version
https://hexawallet.io/dev/tcg/Dwvworn/e4fd4ab592c11d57dcc63074e002310af75de9ec1b7b9cfce37b3d1cfccb737c6dbbf5e5d333cd16a558c68169d29b776e75a734bd9acedb57252c5167504e44f9286eb08b73911094e7eb49ee4a88a4/num/727/1603481550999/v1.2.1

Reshared today from 144

https://hexawallet.io/dev/tcg/Dwvworn/e4fd4ab592c11d57dcc63074e002310af75de9ec1b7b9cfce37b3d1cfccb737c6dbbf5e5d333cd16a558c68169d29b776e75a734bd9acedb57252c5167504e44f9286eb08b73911094e7eb49ee4a88a4/num/727/1603481550999/v1.3.0

**Comment by Parsh** [comment]
This has worked for me on both Android and iOS. @cakesoft-swati  Can you please replicate and let me know? Also, FYI I've not tried this on Staging yet.

**Comment by Arpanjainson** [comment]
Able to generate 2 new links for keeper request
