### ISSUE TITLE
Unable to upgrade Dev app on Adroid.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1882]
-Not able to upgrade dev app from 1.2.1(133) to 1.3.0(144) on Android device.
![Screenshot_20201026-134932_Package installer](https://user-images.githubusercontent.com/62699947/97152012-50057400-1796-11eb-97a5-b421bb04a2e0.jpg)

**Comment by AliMeer** [comment]
@cakesoft-swati please add models that worked to the issue description above.

Also please try and reproduce the issue on your device by deleting all hexa apps and then installing 133 and try to upgrade to 144. If it works then there isn't an issue. If it fails would be good to ensure you have good about of free space on your phone and repeat.

**Comment by cakesoft-swati** [comment]
-I free up some phones memory and it worked.
-Unable to reproduce this issue.
