### ISSUE TITLE
Refactor Notifications code in `Home`

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1888]
Right now, there's a considerable amount of code in `Home` related to loading and updating lists of notifications, and I'm finding much of it to be indecipherable -- both in terms of what the intent is and how the code is trying to achieve that intent. 

More specifically, it seems like Home is trying to fetch notification state from -- and update notification state in -- both Redux and AsyncStorage throughout a number of different callbacks and component lifecycle methods.

I think there's a great potential to improve Home's loading performance and avoid future bugs if we need can 1) Establish clarity around how to architect the data flow for notifications and 2) have a dedicated effort to refactor the code in `Home` around this architecture.

@cakesoft-nikhita @cakesoft-shivani @cakesoft-swati @Parsh @abdulmuneer22 @AliMeer Any insights into how this was previously built would be greatly appreciated here 🙂 .

**Comment by CypherPoet** [comment]
Furthermore, if the only thing `Home` is using notifications for is the "Header" component, I would just have the Redux state containing notifications data be injected into that component only. This component could also dispatch any necessary update actions back to our reducers -- and we might be able to remove most of the current notifications code from `Home` entirely.

**Comment by AliMeer** [comment]
Closing this as this is being done now via other issues.
