### ISSUE TITLE
Issue with personal copy share.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1890]
-My first PDF was shared alright and was able to confirm it as well.But then I shared the second pdf and it was showing the backup now button and showing the red icon on manage backup screen.
-I again shared it and this time confirm came in But then when I was tryig to confirm it ,scanner was not working[ on another android devcie after 2-3 trials it scans but health didn’t update.]It was still red for the second one.[This is happening only on Android device]

-Also, when we use save as pdf for the 1st pdf ,we can use the same sharing mechanism for the 2nd as well.It didn’t block that sharing option.

**Comment by Parsh** [comment]
For android, I've been able to see the PDF working as expected after the fix. Also, the share buttons are getting disabled accordingly. @cakesoft-swati Please check whether the behavior is consistent on iOS as well.

![Screenshot_20201029-165818](https://user-images.githubusercontent.com/17980466/97563316-de812c00-1a08-11eb-8a12-000d568ae8f3.jpg)
![Screenshot_20201029-165742](https://user-images.githubusercontent.com/17980466/97563305-da550e80-1a08-11eb-93a9-a9ab3d25a238.jpg)
![Screenshot_20201029-165756](https://user-images.githubusercontent.com/17980466/97563313-dd4fff00-1a08-11eb-9767-cc033b28a6b7.jpg)

**Comment by cakesoft-swati** [comment]
-Now the scanner is working. Also, the share buttons are getting disabled accordingly.
-Verified this issue on Dev app version 1.3.0(150)
