### ISSUE TITLE
 F&F request  acceptance flow

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1891]
-Just before confirming the addition it went to the Send Screen for a few seconds . And then automatically came to the HS with the confirmation.
![beforeconfirming](https://user-images.githubusercontent.com/62699947/97274137-3b8aaf80-185a-11eb-9e85-29780d00f2c7.jpg)

**Comment by Parsh** [comment]
Wasn't able to replicate that. @cakesoft-swati Can we have more details about this request, like whether it was a payment+contact request from send or just a plain TC request?

**Comment by cakesoft-swati** [comment]
-Unable to reproduce this issue on latest app version 1.3.0(151)
