### ISSUE TITLE
UI issues while accepting F&F request

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1892]
-Not moving to the next box quickly, after a while. Allowing multiple entries in one box. Should allow only one.
![notmovingnext](https://user-images.githubusercontent.com/62699947/97274688-0337a100-185b-11eb-9c53-acc95be22ded.jpg)

- Sometimes the keyboard covers the text boxes.
![Screenshot_20201026-124527_hexa dev](https://user-images.githubusercontent.com/62699947/97275552-11d28800-185c-11eb-9d17-cb4ab813de48.jpg)

**Comment by cakesoft-nikhita** [comment]
This issue is not reproduced on android as well as on iOS

**Comment by cakesoft-swati** [comment]
-Verified this on dev app version 1.3.2(168)
