### ISSUE TITLE
After upgrade the donation accounts available sats go to zero.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1893]
-After upgrade the donation accounts available sats go to  "0" even though they were confirmed earlier and the user needs to swipe down to see the available sats again.

**Comment by Parsh** [comment]
Upgrading from which version to which one(latest)? @cakesoft-swati

**Comment by antuz123** [comment]
@cakesoft-swati - upgrading from an internal version is not important. Try from the last live version and confirm.

**Comment by cakesoft-swati** [comment]
Unable to reproduce this issue.Upgraded from 133 to 151.
