### ISSUE TITLE
Alignment of the Add tile.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1894]
-Alignment of the Add tile is not correct.
![notgoogidea](https://user-images.githubusercontent.com/62699947/97277314-565f2300-185e-11eb-8fdb-30fdffd0ea56.jpg)

**Comment by CypherPoet** [comment]
@cakesoft-swati I'm not sure I understand the definition of "correct" and "not correct" here.

Furthermore, though, I'm thinking this should be a non-issue after https://github.com/bithyve/hexa/issues/1880, which included removing the explicit titles altogether. @antuz123 Am I correct that icons-only is the what we're going for at the moment?

**Comment by antuz123** [comment]
@CypherPoet - till we get account management with the Add Account at the beginning (TBC?), we continue with this tile being aligned as it was - as the next tile aligned to the rest of the tiles.

**Comment by CypherPoet** [comment]
@antuz123 @cakesoft-swati Please ignore my last comment. I was misreading this issue as being about the four buttons on the bottom tab bar 🤦 .

**Comment by cakesoft-swati** [comment]
Verified this issue on Dev app version 1.3.0(148)
