### ISSUE TITLE
Deeplink modals are landing only on Home page.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1895]
-Now the keeper request modal or any other req modal is landing only on Home page,if I'm on any other tab like more etc then I'll have to go back to the home page.
[deeplink modal.zip](https://github.com/bithyve/hexa/files/5444442/deeplink.modal.zip)

**Comment by CypherPoet** [comment]
This is happening because `More` is now its own route -- separate from `Home`, and the deep-link handler is located on `Home`.

@antuz123 @AliMeer I think we're at a point where properly handling all of these cases is going to require some significant refactoring to our deep-linking architecture, [as we've been](https://bithyve-workspace.slack.com/archives/CEBLWDEKH/p1603666429045500?thread_ts=1603643577.023000&cid=CEBLWDEKH) [discussing on several recent occassions](https://bithyve-workspace.slack.com/archives/CEBLWDEKH/p1603641077013800?thread_ts=1603640827.008500&cid=CEBLWDEKH).

**Comment by antuz123** [comment]
@AliMeer @CypherPoet - this needs to go with the 're-login' piece which we had and took it away as it was not working properly. 

Re-login is what happens when the app goes into the background and is recalled. The user is needed to put the passcode again.

**Comment by AliMeer** [comment]
In that case Login and ReLogin can have the deep link handler and then let the following screens know via navigation properties.

**Comment by antuz123** [comment]
One option here could be to move the app back to the Home Screen every time it goes to the background. I know this can be done and maybe a quick fix for this scenario.

**Comment by antuz123** [comment]
> In that case Login and ReLogin can have the deep link handler and then let the following screens know via navigation properties.

Yes correct, but that is a longer piece so see my previous comment.

**Comment by AliMeer** [comment]
> One option here could be to move the app back to the Home Screen every time it goes to the background. I know this can be done and maybe a quick fix for this scenario.

Yes I was considering this option as well. When app goes in background it should start with re login and go back to home screen.

**Comment by antuz123** [comment]
> > One option here could be to move the app back to the Home Screen every time it goes to the background. I know this can be done and maybe a quick fix for this scenario.
> 
> Yes I was considering this option as well. When app goes in background it should start with re login and go back to home screen.

No, ignore re-login for now, it has its own set of issues. Just make the Home Screen active/ 'in-focus' every time it goes in the background.

**Comment by CypherPoet** [comment]
> No, ignore re-login for now, it has its own set of issues. Just make the Home Screen active/ 'in-focus' every time it goes in the background.

@antuz123 I think this is doable, but have we considered the consequences this might have on the UX for various screens? 

For example, let's say a user is deep inside of some Account Management screen where they're re-assigning transactions. But then they get a text message... background the app while they respond to it real quick... and then come back. All of a sudden, they're at the Home screen, and all of their progress has been lost. I not certain this is ideal.

**Comment by antuz123** [comment]
Yes certainly not ideal but a fix for now? 

The ideal solution would be to have a re-login handler as soon as the app goes in the background. There are many other pieces this handler can do. Example - locking the app if coming from background after x secs. Performing some of the login functions if coming in after y mins. Etc. But this may not go in with the next release. 

So the fix would be to just use the HS? Is the issue also when the user is inside other screens? Like account screen? Or only when the new bottom screens on the HS are open?

**Comment by AliMeer** [comment]
@antuz123  At the moment in the current build. When an app is open on any screen or modal, a deep link is detected and the user is taken to the deep link modal. This works for Account screens, both send receive as well as for manage backups and modals as well. This is not happening only for "more" screen. Please asses the priority based on this behaviour.
@CypherPoet its worth trying to replicate this behaviour for "more" screen for the current release.

**Comment by cakesoft-swati** [comment]
Verified this issue on Dev app varsion 1.3.0(148)

**Comment by antuz123** [comment]
@cakesoft-swati - is this still happening. Please state the details.

**Comment by cakesoft-swati** [comment]
-Right now this is not happening on 'More ' screens and on Notifications modal.

**Comment by antuz123** [comment]
So where is it happening? this is not clear.

**Comment by cakesoft-swati** [comment]
Internal pages of More screen like F&F,Funding sources etc.

**Comment by cakesoft-swati** [comment]
Suppose we are on the funding source page and we click on any deeplink, then the funding source page goes to more screen and we are not able see the deeplink modal, for that we have to go to the home page itself.

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app version 1.3.0(155)
