### ISSUE TITLE
F&F notifications

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1902]
-‘Removed as a Keeper’. Message missing || we use Friends and Family not Trusted Contacts.
![removedaskeeper](https://user-images.githubusercontent.com/62699947/97412280-5d9e3380-1927-11eb-8752-88a5b6f17def.jpg)

**Comment by Parsh** [comment]
The notification text has been fixed, also earlier the share wasn't getting deleted from the old trusted contact's device on doing change contact at manage-backup, now that should work fine.

**Comment by antuz123** [comment]
An F&F contact goes from Keeper to Other Contact when Change COntact happens.
