### ISSUE TITLE
Sending from Donation account is being unsuccessful.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1904]
-Having a issue while spending from Donation account.
![IMG_20201028_135507_168](https://user-images.githubusercontent.com/62699947/97412404-89b9b480-1927-11eb-83bf-fe172bbf0c19.jpg)
1.Fee is heigh.
2.Network connection is solid, still unable to send from donation account.

**Comment by Parsh** [comment]
The sending from both types of donation acc(2FA and non) is working fine on the Testnet. 

The point where the donation send is failing in the above screenshot, from the standpoint of code, could fail due to two reasons: 
- Insufficient fund: But for this err the message under Send Unsuccessful is different (clearly states that insufficiency is the case).
- The coinselect mechanism fails for some reason(this is more of a black box as we've been using a 3rd party lib for that). However, this generally never occurs.

**Comment by antuz123** [comment]
@cakesoft-swati - this still does not have all the details from the TG.

**Comment by Parsh** [comment]
@cakesoft-swati I tried to replicate this issue using two identical transactions to the donation account, however, as can be seen in the images below, I was able to spend from the account(even send max was taking me to the confirmation screen as expected). Let me know if you are able to replicate it.

<img width="1440" alt="Screenshot 2020-10-30 at 2 21 19 PM" src="https://user-images.githubusercontent.com/17980466/97679593-77707f80-1abb-11eb-8c3e-59f61872aee9.png">
<img width="1440" alt="Screenshot 2020-10-30 at 2 21 33 PM" src="https://user-images.githubusercontent.com/17980466/97679700-9b33c580-1abb-11eb-80c2-002df2f0f192.png">
<img width="1440" alt="Screenshot 2020-10-30 at 2 21 56 PM" src="https://user-images.githubusercontent.com/17980466/97679770-b1418600-1abb-11eb-9087-9090db2a1c07.png">
<img width="1440" alt="Screenshot 2020-10-30 at 2 22 07 PM" src="https://user-images.githubusercontent.com/17980466/97679774-b272b300-1abb-11eb-9323-f91b4299b45f.png">

**Comment by antuz123** [comment]
Does not work with the latest app upgrade either

**Comment by Parsh** [comment]
Fallback for coin-select is included(threshold err in blackjack) which might solve this issue.

**Comment by antuz123** [comment]
This will close when user confirms. We need to send it to their donation account.

**Comment by antuz123** [comment]
https://hexawallet.io/donate/?donationid=e2449611f1b1a7c

**Comment by AliMeer** [comment]
I have sent 0.0007 BTC with "from hexa' as a note.

**Comment by antuz123** [comment]
Pls see my comments on the QA channel @cakesoft-swati

**Comment by AliMeer** [comment]
We will push out 1.3.1 to live and check with the user if the 1.3.1 fixes the users problem.

**Comment by cakesoft-swati** [comment]
[Uploading IMG_7289.zip…]()
User video.

**Comment by cakesoft-swati** [comment]
I'm unable to reproduce this issue on staging app version 1.3.1(162)

**Comment by AliMeer** [comment]
We will wait for the user to upgrade to v1.3.1 and see if that resolves the issue.
