### ISSUE TITLE
Reciprocal keeper addition is failing.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1905]
-Reciprocal keeper addition failed 
-I accepted Arpan sir's keeper request - but when he was accepting my request with the same contact name app gave an error "Contact already exists"
![File (67)](https://user-images.githubusercontent.com/62699947/97426234-29cc0980-1939-11eb-968d-d1680bb0bc46.jpg)

**Comment by Parsh** [comment]
@cakesoft-swati Can you post the link that you shared w/ Arpan sir here?

I've tried reciprocal keeper, but this didn't occur to me. Also, Arpan sir should not be seeing an associate contact screen while accepting a guardian(atcg) link from an already established trusted contact, it happens instantaneously after entering the phone-number/email. 

<img width="1440" alt="Screenshot 2020-10-28 at 5 37 39 PM" src="https://user-images.githubusercontent.com/17980466/97434141-97c9fe00-1944-11eb-8efa-c580cfd6e712.png">

**Comment by cakesoft-swati** [comment]
Click here to accept Keeper request for Devnew Hexa wallet- link will expire in 24 hours
https://hexawallet.io/dev/tcg/Devnew/aada755a6b14feec8029a1d7b0acf3b700c3911cc1e9fb72ec2ffba548f966798fa13b6ae8b6bcac04278a497aec352319ab11a3f3525fad7e8a22b8bfbe3b36b2743857a439103955d1fbe8e78b6bdf/num/861/1603877662886/v1.3.0
-This is the link which was send by Arpan sir and I accepted it.I saved his Wallet name by skipping the Associate contact.

Click here to accept Keeper request for Tst Hexa wallet- link will expire in 24 hours
https://hexawallet.io/dev/tcg/Tst/fa7c998fb7a3d47dcbd1a7b38b47829ef7a11472c5349a48fda58edc930d672fa316269a6dff3f79d0f5dd7cf2088efa417aed9c71821520c2c213445c0f2c5f55434e52ad0950955588ab5bff685c8f/num/975/1603877852173/v1.3.0
-and this is My keeper request which was sent by me to Arpan sir .

**Comment by antuz123** [comment]
Keeper goes from Keeper to OC
OC goes to 'Removed' where the user can actually Remove form inside.

**Comment by Parsh** [comment]
Because Swati accepted the request by skipping contact(and not associating Arpan sir's contact), the app had no chance or way to figure out that the contact that Swati is now selecting to be her Guardian(Arpan sir's contact) is the same contact and therefore the app ends up creating a new ephemeral channel(and therefore the tcg link to Arpan sir).

Presently, there's no straightforward way to do reciprocal keeper w/ skipped contact hence this behavior is expected in this scenario.

**Comment by antuz123** [comment]
as wallet ID is the primary key, this does not seem like a bug. @Arpanjainson @cakesoft-swati

**Comment by Arpanjainson** [comment]
I think walletID is not being used as the key here. In case of an upgrade or even a new request the wallet-id should have been used.

**Comment by cakesoft-swati** [comment]
-I've tried it on 1.3.0(150) version and the scenarios is a bit different :-
 - A. sent keeper request to B and he accepted it by associating the contact and at the same time by skippig the contact.B can click on confirm and proceed button and also he can click on skip button at the same time.So B can see the name of A's wallet in his F & F list and also with its contact name.
 - After that B deleted his wallet and installed the new one.Now he sent keeper request to A but when he was accepting B's request with the same contact name app gave an error "Contact already exists".

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app version 1.4.0(184)
