### ISSUE TITLE
Refactor Data structure and usage of Currency Codes.

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1911]
Currently, the usage of currency codes throughout the app is subject to a number of issues:
    - Lots of [hard-coded](https://github.com/bithyve/hexa/blob/49539b28ff36134ceff29c64ad61658104498e6f/src/common/CommonFunctions/index.ts#L54), [copied-and-pasted](https://github.com/bithyve/hexa/blob/d4d36076417c63126258a2b45990ca20a6c2b488/src/pages/Accounts/SendToContact.tsx#L78) string values with [no clear indication of what currency codes](https://github.com/bithyve/hexa/blob/8e1f05312f97898c9decb51095b610e5a34d459a/src/components/home/home-header.tsx#L20) we actually support.
    - Multiple sources of truth for state ([getting and setting values from/in Redux and/or AsyncStorage](https://github.com/bithyve/hexa/blob/d4d36076417c63126258a2b45990ca20a6c2b488/src/pages/Accounts/SendToContact.tsx#L413). Also, see the point above.)
    - [Multiple variables](https://github.com/bithyve/hexa/blob/ad627927a5e07f4a8f4b798f912e5df736a541b4/src/pages/Home/Home.tsx#L165) with the [same name](https://github.com/bithyve/hexa/blob/ad627927a5e07f4a8f4b798f912e5df736a541b4/src/pages/Home/Home.tsx#L173).

Architecting currency codes as a strongly-typed enum, then driving/synching updates through our Redux store (similar to the changes made for the ["Currency Kind" preference](https://github.com/bithyve/hexa/pull/1711)) will clear up the current code considerably, and be tremendously useful for making changes in the future.

**Comment by AliMeer** [comment]
I don't think there is anymore more required to be done for currency codes at the moment. We can park this ticket for now.

**Comment by AliMeer** [comment]
There isn't anything concrete to be done for this issue anynore.
