### ISSUE TITLE
Performance issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1912]
-ios[1.3.0(148)]: It is taking almost 24 sec to logged in on Fresh installed app[No data]

-Android[1.3.0(148)]:It is taking 30/32 sec to logged in on Fresh installed app and almost 15 sec to enter the app after setting up  the wallet .

-It is also taking time to load the QR codes.

**Comment by antuz123** [comment]
Ali  1 hour ago
ooop sorry, just seeing this... did a lot of debugging:
I tried with various time options and also without the timer:
in conclusion startup sync takes 4 to 6 sec
Actual aparent user time is 7 to 9 sec
This is on a simulator so actual device time will vary.
Some data from analysis:
When timer was set to 20 sec
Actual time was 7 to 8 sec
[Thu Oct 29 2020 11:35:22.627]  LOG    starting timer {"LOADER_MESSAGE_TIME": 20000} 1603971322623
[Thu Oct 29 2020 11:35:23.230]  LOG    startupsync started 1603971323022
[Thu Oct 29 2020 11:35:27.901]  LOG    startupsync complete 1603971327899
[Thu Oct 29 2020 11:35:27.977]  LOG    sync complete moving to home {"LOADER_MESSAGE_TIME": 20000} 1603971327960
When timer was set to 20 sec
Actual time to move to home screen 8 sec 
[Thu Oct 29 2020 11:38:39.460]  LOG    starting timer {"LOADER_MESSAGE_TIME": 20000} 1603971519043
[Thu Oct 29 2020 11:38:40.773]  LOG    startupsync started 1603971519432
[Thu Oct 29 2020 11:38:47.271]  LOG    startupsync complete 1603971527260
[Thu Oct 29 2020 11:38:47.334]  LOG    sync complete moving to home {"LOADER_MESSAGE_TIME": 20000} 1603971527318
20 sec
Actual time to move to home screen 8 sec
[Thu Oct 29 2020 11:44:27.608]  LOG    starting timer {"LOADER_MESSAGE_TIME": 20000} 1603971867605
[Thu Oct 29 2020 11:44:29.367]  LOG    startupsync started 1603971868022
[Thu Oct 29 2020 11:44:33.410]  LOG    startupsync complete 1603971873408
[Thu Oct 29 2020 11:44:33.486]  LOG    sync complete moving to home {"LOADER_MESSAGE_TIME": 20000} 1603971873469
20 sec
Actual time to move to home screen 10 sec
[Thu Oct 29 2020 11:51:06.300]  LOG    starting timer {"LOADER_MESSAGE_TIME": 20000} 1603972265999
[Thu Oct 29 2020 11:51:07.663]  LOG    startupsync started 1603972266339
[Thu Oct 29 2020 11:51:13.519]  LOG    startupsync complete 1603972273514
[Thu Oct 29 2020 11:51:13.567]  LOG    sync complete moving to home {"LOADER_MESSAGE_TIME": 20000} 1603972273551
NO TIMER
Actual time 9 sec
[Thu Oct 29 2020 11:51:07.663]  LOG    startupsync started 1603972266339
[Thu Oct 29 2020 11:51:13.519]  LOG    startupsync complete 1603972273514
[Thu Oct 29 2020 11:51:13.567]  LOG    sync complete moving to home {"LOADER_MESSAGE_TIME": 20000} 1603972273551

**Comment by antuz123** [comment]
@cakesoft-swati @Arpanjainson - TL;DR: It seems that the performance has not changed form the last builds or current live build. Please look above from Ali and verify.

**Comment by AliMeer** [comment]
And we are doing this one for the current release to improve performance: https://github.com/bithyve/hexa/issues/1916

**Comment by cakesoft-swati** [comment]
-Now it is taking hardly 4/5 sec to loged in on both Android and ios device.
