### ISSUE TITLE
Send flow changes 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1915]
New UX to be implemented with:
1. Last seen active 
2. New UX logic 
3. Use the new 'Remove' logic

**Comment by antuz123** [comment]
See details: Contacts to have ‘last seen active’ #1307

**Comment by CypherPoet** [comment]
Tweaking the title a bit here... F&F can certainly make use of some of the components developed for this, but should probably have its own set of stories to track/scope at some point.

**Comment by CypherPoet** [comment]
Marking this as fixed, as I think it was mainly the first catch-all issue we created for the Send changes before breaking it out into more fine-grained issues.

**Comment by CypherPoet** [comment]
Closing this for now, as it was mainly the first catch-all issue we created for the Send changes before breaking it out into more fine-grained issues.
