### ISSUE TITLE
Account sync pushed to Account Screen

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1916]
Manual refresh fetches everything. This is before we do the Wrapper Upgrade. 

Part of https://github.com/bithyve/hexa/issues/1912

**Comment by AliMeer** [comment]
This is fixed and deployed with 1.3.0

**Comment by antuz123** [comment]
Test Case:
1. Balance not updating on login. Only on Account refresh. 
2. Login must be faster.

**Comment by cakesoft-swati** [comment]
-Verified this on Hexa app version 1.3.0(151)
