### ISSUE TITLE
Incorrect balance formatting on Send screen accounts list

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1921]
-The values here need to be fixed as a part of the new Send flow.
![File (68)](https://user-images.githubusercontent.com/62699947/97663128-c0660b00-1a9e-11eb-9502-dfb4fe445c66.jpg)

**Comment by CypherPoet** [comment]
@cakesoft-swati Sorry if I'm missing something, but could you please elaborate on how the view above is broken and how it needs to be fixed?

**Comment by antuz123** [comment]
The value shown there is in sats but shows $ as the currency.

**Comment by CypherPoet** [comment]
@antuz123 I see. So the value should be converted to dollars instead? We might also want to have it correspond to the users current preference for displaying fiat currency or BTC.

**Comment by antuz123** [comment]
The value is in sats and should show B symbol. 

Yes it should be as per user preference. This is the case everywhere in the app.

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app version 1.3.1(162)
