### ISSUE TITLE
Fee selection while sending an amount which is less than available to spend.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1922]
-When sending an amount less that available to spend, fee should not be added in the checking for proceed. The user can choose 1 sat/byte or something. So only the min fee possible should be checked and the speed options should be changed accordingly.
![File (69)](https://user-images.githubusercontent.com/62699947/97663238-0de27800-1a9f-11eb-94a2-bc47f71a6cd3.jpg)

**Comment by antuz123** [comment]
Here we should check for ATS>= Amount to be sent + 'Min Custom Fee' which may be different from 1 sat/byte

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(243)
