### ISSUE TITLE
Issues on loader modal messages.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1923]
-The same message is being displayed here. We need random message every time.
![samemsg](https://user-images.githubusercontent.com/62699947/97668021-1e96ec00-1aa7-11eb-925c-dc0b4957aed0.jpg)

**Comment by AliMeer** [comment]
Fixed in 151

**Comment by cakesoft-swati** [comment]
-Only one message is visible on the loader modal and it is different each time when we trying to logged in. (edited) 
-Tested in staging app version 1.3.0(151)

**Comment by AliMeer** [comment]
@cakesoft-swati yes only one message is displayed but it’s different every time.

 Because login speed has increased there is no time for another message. That’s why we are showing only one message.

**Comment by cakesoft-swati** [comment]
got it,verified on Hexa app version 1.3.0(151)
