### ISSUE TITLE
Home Screen Accounts Alignment issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1924]
-The alignment of the left margin has gone for a toss.
![thealignment](https://user-images.githubusercontent.com/62699947/97668358-c6acb500-1aa7-11eb-93b8-1c63f9a70cc9.jpg)

**Comment by AliMeer** [comment]
Fixed in 151

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app version 1.3.0(151)
