### ISSUE TITLE
Send To Contacts Flow: Add "last seen active" color indicators on contact avatars

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1938]

**Comment by antuz123** [comment]
If the user is Last Seen
1. Within last 15 days - Green 
2. Within last 15-45 days - Red 
3. More than 45 days - Grey 
4. Any non-active state lie expired or removed or pending - Grey

**Comment by cakesoft-swati** [comment]
-Unable to see the expected color indicators on contact avatars.

**Comment by cakesoft-swati** [comment]
-Tested on staging app version 1.3.1(164)

**Comment by cakesoft-swati** [comment]
-Tested on dev,staging and production app version 1.3.1(164)
