### ISSUE TITLE
Login and Launch pages click delays

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#1939]
Remove the setTimeOuts from Launch and Login pages as part of the 1.3.1 refactor.

**Comment by AliMeer** [comment]
@antuz123 this is not 1.3.1 but the one after 1.3.1

**Comment by CypherPoet** [comment]
Moving this out of 1.4.0 since it seem fairly separate from account management.

**Comment by AliMeer** [comment]
Closing this as discussed today, this has been taken care of wherever applicable.
