### ISSUE TITLE
Audio cuts out when starting on Android

### ISSUE THREAD

**Issue by dmp1ce** [bithyve/hexa#1940]
While listening to Bitcoin Audible on AntennaPod, I start Hexa and my audio from AntennaPod stops. Why does this happen?

Also, I'm listening with a bluetooth headphones.

Can Hexa not stop my podcast audio when it starts?

**Comment by antuz123** [comment]
We will test it out. Thanks for reporting. 

Do you have an Android or iOS device? Also any other I formation about your device that you can provide will be helpful.

**Comment by AliMeer** [comment]
As @antuz123 would be great to get more information about your device.

I suppose it’s Android as AntennaPod is only for Android AFIK.

While we investigate it might be worth keeping an eye on this particular issue as well https://github.com/AntennaPod/AntennaPod/issues/4530

**Comment by dmp1ce** [comment]
Sure. I'm happy to provide information. I download the apps from the Google Play Store. I'm on an up-to-date Pixel 2 android phone. I am on Android version 11.

**Comment by cakesoft-swati** [comment]
-Unable to replicate this issue on SAMSUNG A70

**Comment by dmp1ce** [comment]
I tried to reproduce today and the issue didn't occur for me! Closing.
