### ISSUE TITLE
Step 1 - Account screen loading improvement (Wrapper)

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1944]
-Acc has been stuck on loading since it was v1.2.1 and loader has not gone away after upgrading to v1.3.0.
Have refreshed a few times and the loader doesn’t go away.
There are at least 2 transactions sent after the latest one shown in the list abs both are visible on block explorer but not in account transactions.
![File (70)](https://user-images.githubusercontent.com/62699947/97832055-dcb0b480-1cf7-11eb-91e3-1fe153aca451.jpg)

**Comment by antuz123** [comment]
Step 1 for Wrapper changes.

**Comment by Parsh** [comment]
App changes have been done for the same, testing is pending w/ the test-wrapper.

**Comment by Arpanjainson** [comment]
@cakesoft-swati - need to test this with atleast 20 transactions

**Comment by Arpanjainson** [comment]
test on live build - do some test txns.
