### ISSUE TITLE
FBTC test not working

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1958]
It should work for our Dev and Staging app with supported locations by FBTC

**Comment by antuz123** [comment]
Need for both scenarios:
1. Hexa to FBTC
2. FBTC to Hexa

**Comment by AliMeer** [comment]
This cannot proceed without support from FBTC. We are disabling FBTC in v1.4.5 we can consider picking this up when we enable FBTC.

**Comment by AliMeer** [comment]
Moving this to a much later time frame. We need support from FBTC to work on this task.

**Comment by ASN-BitHyve** [comment]
We do not have FBTC anymore
