### ISSUE TITLE
Scanner issue in recovery.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1962]
-The scanner in the recovery flow is rejecting the proposal to open.
![Screenshot_20201103-145423](https://user-images.githubusercontent.com/62699947/97978619-d1db4a00-1df3-11eb-8cad-0133f84c9001.jpg)
-QR gets scanned but the app does not request next QR.

**Comment by cakesoft-swati** [comment]
[The scanner in the recovery flow is rejecting the proposal to open.]
-This is still happening on Android device.

**Comment by AliMeer** [comment]
fixed in 159

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app version 1.3.1(162)
