### ISSUE TITLE
Contact gets added multiple times 

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1963]
While accepting a trusted contact or keeper request, select a contact but then instead of Ok, click Skip.
The request gets saved twice,

**Comment by antuz123** [comment]
There are multiple scenarios where the user may have added contacts multiple times... There should be a remove button for all by default unless they are Keeper or Keeping (Confirmed)

**Comment by antuz123** [comment]
This should apply to all new apps and even if the user upgrades his/ her app.

**Comment by cakesoft-swati** [comment]
-Able to click on both the buttons i.e skip and confirm but contact didn't get added twice.
-Tested on 1.3.1(161)
