### ISSUE TITLE
App buttons can be clicked multiple times

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1970]
E.g. on the donation account, skip contact etc buttons the user is able to click the button multiple times. Multiple clicks triggers the activity multiple times.
Skip created multiple contact entries
Donation add button created multiple donation accounts
--
The app buttons should get disabled when clicked once and till the time either error or success is returned.

**Comment by antuz123** [comment]
@Arpanjainson - can you add the screen.

**Comment by Arpanjainson** [comment]
Keep tracking the issues related to skip button and post video, screenshots here

**Comment by cakesoft-swati** [comment]
-When we click on the skip button at the time of associate contact, it becomes inactive and after a few seconds it is getting enabled and the message "You have been successfully added as a keeper" does not appear soon. However, the user feels that there is no action on the skip button and he presses the button again and each time he presses the skip button, he makes several contact entries.

**Comment by cakesoft-swati** [comment]
It is happening on both the devices android and ios.

**Comment by Arpanjainson** [comment]
Refer to this trello card for solution - https://trello.com/c/uALfpF9h/166-ux3-cta-submit-button
UX to be done

**Comment by antuz123** [comment]
It is a simple screen greying with a spinning wheel. So that the whole screen is inaccessible.

**Comment by Arpanjainson** [comment]
![File](https://user-images.githubusercontent.com/8697909/98506789-4eea4180-2282-11eb-9966-fbb12c5fce02.jpg)

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app version 1.4.0(180)
