### ISSUE TITLE
Send Max amount remaining 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1974]
While doing Send max, some amount remains in the account sometimes.

**Comment by cakesoft-swati** [comment]
![send max](https://user-images.githubusercontent.com/62699947/98329342-07637b80-201e-11eb-8b0b-3e5ee2cc39d0.PNG)

![amtremaining](https://user-images.githubusercontent.com/62699947/98329360-11857a00-201e-11eb-97f9-42da6a81a3de.PNG)

**Comment by Parsh** [comment]
@cakesoft-swati Can you confirm this w/ the release containing S&R changes? It might have been resolved as a part of Send max refactoring.

**Comment by cakesoft-swati** [comment]
-I verified it on live app 1.4.6(235) and dev app v1.5.0(243) as well.
-I'm unable to reproduce this issue.
