### ISSUE TITLE
Version specific broadcast notification 

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1987]
On the app initiation, the app checks in with the backend which has a list of upgrades and each one is Mandatory or Voluntary and then allows the user to skip few times.
Refer to  card BE6- https://trello.com/c/sGQEuC2k/73-be6-responding-to-different-versions-of-the-app 
and NF1.1 - https://trello.com/c/Yfyuqnyt/13-nf11-app-notifications-broadcast

**Comment by AliMeer** [comment]
Ability to skip optional upgrades, skip for a number of times and mandatory upgrades is built in and available.

**Comment by cakesoft-swati** [comment]
-Verified this on dev app version 1.3.2(170)
