### ISSUE TITLE
Add "Last Seen Active" Indicators to Friends & Family Screen contacts

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#1989]

**Comment by cakesoft-swati** [comment]
- You can’t have green with request awaiting.Does not look correct.  
-on the F&F list, you can have text 'Last seen active x days back'.

**Comment by antuz123** [comment]
Grey by default if no timestamp

**Comment by cakesoft-swati** [comment]
-Tested on staging app version 1.3.1(164)
-Now showing text 'Last seen a few seconds ago' with grey color.
