### ISSUE TITLE
Step 2 - Account screen loading improvement

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#1992]
We have to make the following changes: https://github.com/bithyve/internal-docs/issues/31#issuecomment-716364536 in addition to the changes made as a part of issue https://github.com/bithyve/hexa/issues/1944.

These changes depend on database refactoring which is going to happen as a part of account management.

**Comment by CypherPoet** [comment]
@Parsh @antuz123 I'm thinking this should be resolved by the new account details screen that has been built out in #1663.

**Comment by antuz123** [comment]
@CypherPoet - this is more about the Wrapper improvement to fetch details faster from the backend. Correct @Parsh?

**Comment by AliMeer** [comment]
This is completed
