### ISSUE TITLE
Don’t need a B symbol in front of the amount when in fiat.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1998]
-We don’t need a B symbol in front of the amount when in fiat.
![File (1)](https://user-images.githubusercontent.com/62699947/98503218-fb73f580-2279-11eb-91f9-732b8641b3f8.jpg)

**Comment by CypherPoet** [comment]
I'm going to try and weave these changes into #1663

**Comment by cakesoft-swati** [comment]
--Verified this issue on Dev app version 1.4.0(180)
