### ISSUE TITLE
new Send flow, sending to contact is not successful 

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2002]
Choosing contact on send screen and sending transaction fails.

**Comment by CypherPoet** [comment]
@AliMeer Do you have a screenshot of the error message and the "unsuccess" bottom sheet that gets displayed when this happened?

**Comment by AliMeer** [comment]
@CypherPoet This was fixed by Nikhita, it’s in dev branch now

![Uploading CE724769-8F61-4CCB-AD90-320B837D6285.jpeg…]()

**Comment by Arpanjainson** [comment]
Send is working across accounts - tested on stage
