### ISSUE TITLE
F&F Issues.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2004]
1.Unable to see the expiry timer on the F&F screen.
![Screenshot_20201109-144543_hexa dev](https://user-images.githubusercontent.com/62699947/98526139-6e439780-229f-11eb-8b43-d87017e18fab.jpg)

2.Unable to see the wallet name on F&F screen even after confirm the F&F request(by skipping the contact name) but ,we can see the wallet name if we click on that contact .
![20201109_153416](https://user-images.githubusercontent.com/62699947/98527593-39d0db00-22a1-11eb-9125-08b16e1d740f.jpg)

![Screenshot_20201109-151409_hexa dev](https://user-images.githubusercontent.com/62699947/98527627-405f5280-22a1-11eb-8c8f-39a5efca727c.jpg)

**Comment by CypherPoet** [comment]
Regarding `Unable to see the expiry timer on the F&F screen.`, this is related to the comment I left [here](https://github.com/bithyve/hexa/blob/c0e2810b3d75aa68d2855a2ef4f24a3749c0a080/src/components/friends-and-family/FriendsAndFamilyContactListItemContent.tsx#L46).

Any clarity about the logic required for displaying the timer would be really useful (@AliMeer @antuz123 @cakesoft-nikhita @Parsh )

**Comment by CypherPoet** [comment]
Regarding `Unable to see the wallet name on F&F screen even after confirm the F&F request`, is the issue that we want to show the wallet name even if other name properties exist? That is, does the wallet name take priority over everything else?

**Comment by antuz123** [comment]
> Regarding `Unable to see the wallet name on F&F screen even after confirm the F&F request`, is the issue that we want to show the wallet name even if other name properties exist? That is, does the wallet name take priority over everything else?

Wallet name is used only when the Contact Name is not there (i.e. skip is used).

**Comment by antuz123** [comment]
If the requester uses 'skip', the app does not know the Contact name or the Wallet name. That is where we use the temp string. Which needs to be replaced when the Wallet name is received back.

**Comment by cakesoft-swati** [comment]
-Unable to see the changes on dev app version 1.3.1(161).
1.Unable to see the expiry timer on the F&F screen.
2.Unable to see the wallet name on F&F screen even after confirm the F&F request(by skipping the contact name) but ,we can see the wallet name if we click on that contact .

**Comment by CypherPoet** [comment]
Maybe I'm still not understanding how to reproduce this, but on the latest dev app version 1.3.1(161), the F&F screen appears to show the wallet name after confirming a request:


![Screenshot_20201112-123912](https://user-images.githubusercontent.com/46851636/98984065-4c3c5600-24e7-11eb-8b75-b8235c76d762.jpg)

**Comment by cakesoft-swati** [comment]
-Still I'm not able to see the wallet name on F&F list after confirming the request.
-Tested on staging app version 1.3.1(162)
![Screenshot_20201116-142523_hexa stage](https://user-images.githubusercontent.com/62699947/99232467-f1bd3580-2817-11eb-88b6-3ee2e3aeb17d.jpg)


![Screenshot_20201116-142527_hexa stage](https://user-images.githubusercontent.com/62699947/99232483-f84bad00-2817-11eb-828c-8475abc06544.jpg)

**Comment by cakesoft-swati** [comment]
I tried it by skipping the contact on both(sender and receivers) side.
I also tried it by skipping the contact on senders side.

**Comment by CypherPoet** [comment]
I think this needs to be fixed by making a few changes on the backend. The UI components that display these names are falling back to the wallet name if a `displayedName` doesn't exist. However, `displayedName` is being derived from the first and last name being set for a contact item -- which is being set to `F&F Request` for contacts where name information can't be found (instead of `null`).

[See the discussion here for more details](https://bithyve-workspace.slack.com/archives/CEBLWDEKH/p1604599120108300)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app version 1.3.1(164)
