### ISSUE TITLE
Notification - important and not important message differntiation

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2011]
Messages are marked as IMP or not-IMP. In the above example, all broadcast messages are IMP and all others are not-IMP.

When the notification list is opened in the app all not-IMP are marked as Read but for IMP notifications, they have to be touched to be marked as Read.

User can visually see the difference between Read and not-Read messages. Also IMP and not-IMP is visible with a tag or something.

refer to card for more details - https://trello.com/c/yp45MeCQ/71-nf10-app-notifications-general

**Comment by AliMeer** [comment]
Is this still relevant?
