### ISSUE TITLE
Notification - NF1.2 - Transfer type transaction notification p2p trusted contact- app side flow

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2012]
refer to card for more details - https://trello.com/c/jBautGpR/70-nf12-app-notifications-contacts
Notification for transactions to be displayed on the receivers side.

**Comment by AliMeer** [comment]
This needs to be retested after firebase upgrade

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.4.2(203)
