### ISSUE TITLE
Notifications - app upgrade notifications- app flow

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2015]
Refer to card  - https://trello.com/c/Yfyuqnyt/13-nf11-app-notifications-broadcast
Handle flow for upgrades with reminders.

**Comment by antuz123** [comment]
1. Env specific and version-specific release broadcast notification. 
2. If there is a notification/ new release when the user logs in, the app has a screen with the details of the notification. 
3. The flow should be as described in the card post the notification is opened or the user logs in.

**Comment by cakesoft-swati** [comment]
-Tested on dev app version 1.3.2(170)
-Need to test on staging and prod app.

**Comment by Arpanjainson** [comment]
tested on dev, lets test on production as well before closing.

**Comment by Arpanjainson** [comment]
@AliMeer  did we add the version specific message on the relat for v1.4.2 and v.1.4.3? I downgraded to older live version (non app store) v1.41. but did not see any update notification/message

**Comment by Arpanjainson** [comment]
@AliMeer  need to send boadcst notification on say Monday 02/8
