### ISSUE TITLE
Notifications - app upgrade notifications  broadcast  - release mechanism

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2016]
Refer to card - https://trello.com/c/Yfyuqnyt/13-nf11-app-notifications-broadcast
Currently app upgrade notifications if generated on dev are broadcasted on stage and production as well.

**Comment by AliMeer** [comment]
Getting the notifications pop up on app start for new release, is this the correct one:
 ![IMG_0201](https://user-images.githubusercontent.com/7535475/99604994-ac0e9180-29fe-11eb-8f25-efb1fc62eac8.PNG)

**Comment by AliMeer** [comment]
This is done. Now each env has its own end point to trigger release notification broadcast. Env end point will only notify apps for that environment. ex: dev end point will only notify dev apps.

**Comment by cakesoft-swati** [comment]
-Tested on dev app version 1.3.2(170)
