### ISSUE TITLE
Phone check at login - look for upgraded version

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2018]
What is the latest version of the app and if that is the latest released or not and then prompt the user to install.
A notification should be created.
In case it is a mandatory upgrade then a notification should be saved in the app with remind feature.
In case of optional the notification is created but marked read.

See NF 1.1 : for more details of the actions here as this just connects to the same notifications.

**Comment by AliMeer** [comment]
This needs to be retested after firebase upgrade

**Comment by cakesoft-nikhita** [comment]
@AliMeer I am assigning this issue to you this change needs to be done on the relay

**Comment by Arpanjainson** [comment]
@AliMeer - please update the entry on the relay for 204 an make it mandatory upgrade.

**Comment by Arpanjainson** [comment]
The check works fine, but need to check the mandatory upgrade.

**Comment by Arpanjainson** [comment]
checked for mandatory upgrade
