### ISSUE TITLE
Checking Account on the Donation Account Send Confirmation Screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2022]
It is showing Checking Account on the Donation Account Send Confirmation Screen.
![image](https://user-images.githubusercontent.com/62699947/98636289-92a97d80-234c-11eb-9333-76ade0c20582.png)
[Tested on Hexa live app version 1.3.0(151)FI]

**Comment by Parsh** [comment]
On version 1.3.1 build 160, it says Donation account only. @cakesoft-swati Can you confirm which version is this or is this a side-effect of updating the app?

![Simulator Screen Shot - iPhone 11 - 2020-11-11 at 13 39 42](https://user-images.githubusercontent.com/17980466/98786213-c86d6580-2423-11eb-9fbc-f761f9f71a52.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on stagging app version 1.3.1(162)
