### ISSUE TITLE
Account Refresh 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2026]
1. Account screen should refresh when you go into the account irrespective if it is pulled down or not
2. When refreshing it should be only specific to that account

**Comment by antuz123** [comment]
For 2, for example: when the user goes to Checking Account, it should only fetch Checking Account and not Savings, Donation, or any other account. All sub-account in that account should refresh.

**Comment by antuz123** [comment]
3. For non-designated sub-accounts (checking subaccount, savings sub-account, etc.), reduce query address range to the current address. And up to the last address which has less than 6 confirmations (on the wallet).
4. For designated sub-accounts (F&F and Swan, etc.), reduce the query address range to the next free address plus 5. And And up to the last address which has less than 6 confirmations (on the wallet).

**Comment by Parsh** [comment]
Updates:
- Auto-refresh is done when you land from home to a specific account and not while swiping between accounts
- Auto-refresh happens once per-session

**Comment by Arpanjainson** [comment]
Send to F&F once the app is closed for the receiver, send on Savings, checking
Send to F&F on an old address - say 5-6 address old
Do all this in a batch send while receives app is closed.
Open on receivers end, the balance should auto-refresh

After the balance has been refreshed, send one more test transaction, it will not auto-reflrect and user needs to pull down to refresh.

**Comment by cakesoft-swati** [comment]
[Send to F&F once the app is closed for the receiver, send on Savings, checking
Send to F&F on an old address - say 5-6 address old
Do all this in a batch send while receives app is closed.
Open on receivers end, the balance should auto-refresh

After the balance has been refreshed, send one more test transaction, it will not auto-reflrect and user needs to pull down to refresh.]
-Tested account refresh in above scenario,it is working properly.
-Auto-refresh is done when you land from home to a specific account and not while swiping between accounts.
