### ISSUE TITLE
Account Screen stuck on refresh

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2030]
Account screen is stuck on loading.

**Comment by antuz123** [comment]
The account screen is stuck on refresh and not loading.

**Comment by antuz123** [comment]
A very heavy app with lots of F&F and a donation account. When you pull down, the account refresh use to take a long time. Now it does not progress.

**Comment by AliMeer** [comment]
To replicate kill app while account refresh is in progress and this will result in the account refresh getting stuck in most cases.

**Comment by cakesoft-swati** [comment]
-Verified this on Dev app version 1.3.1(161),it is taking almost 8/9 sec to refresh on account.
-There are 2 F&F and donation account in my wallet also having 4/5 transactions.

**Comment by AliMeer** [comment]
@cakesoft-swati This issue was to fix an app which gets stuck in refresh mode.

Refresh taking too long is covered by this ticket https://github.com/bithyve/hexa/issues/1944

**Comment by antuz123** [comment]
@cakesoft-swati - please test on Android

**Comment by Arpanjainson** [comment]
Working as expected
