### ISSUE TITLE
Dev and Stage app timings 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2032]
1. For the Health timing, the Staging app should reflect Live
2. For the Last Seen, the Dev app timing should be much lower. (this has been moved to a new issue https://github.com/bithyve/hexa/issues/2035)

**Comment by AliMeer** [comment]
How much should we keep for last seen on dev? 10 min?

**Comment by antuz123** [comment]
Just replace days with mins. It has different tiers. @AliMeer

**Comment by AliMeer** [comment]
1 is done. health timings have been updated.

moving 2 to a new issue as this is a slightly different change as the last seen code first needs to incorporate env specific variables and then we can have the ability to configure different timings on dev and live/staging.

**Comment by Arpanjainson** [comment]
@cakesoft-swati  make sure to not close this issue till testing is done in all dev, stage and prod

**Comment by cakesoft-swati** [comment]
-Tested on dev app,need to test on staging and prod.

**Comment by cakesoft-swati** [comment]
-Tested on dev,staging and Production appversion 1.3.1(164)
