### ISSUE TITLE
Account Management Bottom Sheet Refactoring

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#2033]
For 1.4.0’s focus on account management, there’s an opportunity to address the bottom sheets on the primary screens it touches:

- Send Screens
- Receive Screens
- Some of the Pan-account settings screens.

This will likely involve a combination of refactoring bottom sheets to use the components from `@gorhom/bottom-sheet`, and converting some sheets to toasts.

**Comment by AliMeer** [comment]
This is not relevant anymore as most of it was done and now we are using modals instead.
