### ISSUE TITLE
Last Seen time should be much lower for Dev

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2035]
- Incorporate env specific time for last seen
- dev should be 15 min and 45 min
- staging and live should be 15 days and 45 days

**Comment by cakesoft-swati** [comment]
Tested on Dev app version 1.3.1(164)
![Screenshot_20201118-124819_hexa dev](https://user-images.githubusercontent.com/62699947/99497844-7e90fc00-299c-11eb-99f9-2aedf9bb3dc9.jpg)

![Screenshot_20201118-123523_hexa stage (1)](https://user-images.githubusercontent.com/62699947/99499510-07109c00-299f-11eb-92fb-55b0a48c116d.jpg)
