### ISSUE TITLE
Define and use colors for different account kinds

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#2036]
We have different-colored cards and shadows for the card on the Account Details screen, but these color values are hard-coded at the moment. As we continue to add more account kinds and list/display them dynamically, we'll need to have a well-defined map of color values to reference dynamically as well.

**Comment by Arpanjainson** [comment]
Comment from UX team  - we can define say a set of 10 colors, but at the time of implementing it do consult with UX team in case the icon of say third party integration needs to be matched.

**Comment by AliMeer** [comment]
Yes let’s define, the colours, we need at least 2 new colours for 1.4.5; one for Ramp and one for Wyre.

**Comment by AliMeer** [comment]
For Ramp, I am using this for the dev build:
![Screenshot 2021-02-15 at 22 45 05](https://user-images.githubusercontent.com/7535475/107999622-bf220500-6fdf-11eb-8540-db26763c58dc.png)

**Comment by Arpanjainson** [comment]
@antuz123  this will need to be moved to 1.4.6 - Sumaiah will provide a list of 10 colors but for every new integration the logo needs to be reviewed for the color of the card. If we want to decouple the card and the logo color then as per Sumaiah it will require a design change.

**Comment by AliMeer** [comment]
1. Here is a swan logo to match the colours.
![swan](https://user-images.githubusercontent.com/7535475/108243332-dc70e380-7145-11eb-9bd5-ac482ff805a4.png)
https://www.swanbitcoin.com/

2. The account icon will also be used for Account tile on the home screen as well as on the Add New Account screen. With a white background, the icon is not fully visible so may be good to have a border like all the other account icons have.
![Screenshot 2021-02-17 at 17 21 40](https://user-images.githubusercontent.com/7535475/108243563-26f26000-7146-11eb-9748-18d398171af0.png)
![Screenshot 2021-02-17 at 17 15 47](https://user-images.githubusercontent.com/7535475/108243568-28238d00-7146-11eb-9882-3fb69da2e309.png)
![Screenshot 2021-02-17 at 17 15 27](https://user-images.githubusercontent.com/7535475/108243572-2954ba00-7146-11eb-90b1-f38f09f5212d.png)

**Comment by AliMeer** [comment]
We have already used the new cards and icons fir Wyre and Ramp. Swan will be a new UX with its own card and icons and will be done with Swan. We can close this

**Comment by AliMeer** [comment]
Wyre and Ramp are already using new card colour.
Swan will be done as part of Swan add account.
This issue is not requried anymore.
