### ISSUE TITLE
Send failing on Checking and Donation Account

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2037]
1. Send max is failing in checking and donation account
2. Send is failing in checking and donation account
3. Clicking “confirm and proceed” goes directly to “send unsuccessful” 

These 3 issues are not occurring for the test account

**Comment by Parsh** [comment]
@cakesoft-swati I've tried upgrading the app from 160(commit:4be24b3dcfba81998c83098eb82883c966fba49b) to 161 to see whether I'm able to get myself into these issues but unfortunately they didn't replicate on the simulator. Can you please confirm them once by upgrading from the previous build to the recent one and testing these scenarios out?

**Comment by Arpanjainson** [comment]
This is working as expected.
