### ISSUE TITLE
Refactor Send and F&F

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#2039]
Implementing the [ideas described here](https://bithyve-workspace.slack.com/archives/CEBLWDEKH/p1605108406215600).

> 
> Moreover, I’m still not sure why our Send screens need to be reaching into all of these different places to begin with. It seems like we could just have a focused send reducer that held the following state:
> - source account
> - selected recipients
> - amounts being sent to each recipients
> - Progress/Success/Error state of any initiated Send operation.
>
> …. Then get rid of everything having to do with transfer inside of the accountsState reducer that’s going to be refactored anyway in the AC feature branch so it can scale to a dynamic list of accounts.
>
> This would be in the category of deeper refactoring, because all of the Send screens seem to be reaching in to the other locations mentioned above, but it would clear up the ambiguities involved with doing so and greatly help us make changes to the code across all Send screens. Right now, there’s no clear source of truth for the state listed above, and no clarity about how to properly update it based upon things happening in the UI.
>

**Comment by AliMeer** [comment]
As this is the overall ticket to track the SnR refactor, I am marking this dev task as completed.
