### ISSUE TITLE
Send fails from checking account

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2042]
**THIS BUG IS FROM NUTXO TESTING on` fixes/1.3.1` branch and NOT for development branch**

Send failed from checking account despite having confirmed transactions and sufficient available balance.

Console output from the point of error: `{"balance": 4010, "fee": 1536, "txPrerequisites": undefined}`
BaseAccount of the below line: https://github.com/bithyve/hexa/blob/7bee83a351911d2f5d522b83b725f5170e6ccc91/src/bitcoin/utilities/accounts/BaseAccount.ts#L652

![Screenshot 2020-11-12 at 20 03 57](https://user-images.githubusercontent.com/7535475/98990939-0d2bf600-2523-11eb-9949-2da229f82c9a.png)

**Comment by cakesoft-swati** [comment]
-Tested on dev app version 1.3.2(170)
-Available balance is 3000 still it fails while sending.
![Screenshot_20201125-184201_Gallery](https://user-images.githubusercontent.com/62699947/100232191-0acb9200-2f4e-11eb-88c8-02e6192357df.jpg)

**Comment by Arpanjainson** [comment]
@AliMeer  this has been reopened just now

**Comment by Arpanjainson** [comment]
@cakesoft-swati does this happen on live as well?

**Comment by cakesoft-swati** [comment]
Tested on live app version 1.3.2(171)
-Now the transaction value is showing as 0.
-The old transactions in the checking account are also showing 0 when I am sending from a checking account

**Comment by cakesoft-swati** [comment]
-
![Image from iOS (2)](https://user-images.githubusercontent.com/62699947/100312635-db159c00-2fd8-11eb-8034-e39ad617a98a.png)


![Image from iOS (1)](https://user-images.githubusercontent.com/62699947/100312657-e8328b00-2fd8-11eb-84c5-3b32c808c92b.png)

**Comment by Arpanjainson** [comment]
@cakesoft-swati  please open a new issue for this

**Comment by cakesoft-swati** [comment]
-Now able to send from checking account.
-Tested on live app version 1.3.2(171)
