### ISSUE TITLE
View More Transaction Details Not Visible

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2043]
**THIS BUG IS FROM NUTXO TESTING on fixes/1.3.1 branch and NOT for development branch**

To replicate:
Intermittant issue. not occuring all the time.
`On Accounts` go to `View More` then click on any `transaction` for details

Expected:
Transaction details will be shown with correct amounts

Actual Result:
Sometimes during use the details were zero or blank except data and number of confirmations. 

![Screenshot 2020-11-12 at 20 03 32](https://user-images.githubusercontent.com/7535475/98991605-fb971e00-2523-11eb-8f20-c3a95c3371f9.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app version 1.3.2(170)
