### ISSUE TITLE
Update fetchBalance processing to send sets of addresses to new wrapper end point 

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2044]
**THIS IS FROM NUTXO TESTING on `fixes/1.3.1` branch and NOT for development branch**

Currently we are sending only 1 set of external and internal addresses to NUTXOTXS and gettign back the utxo and transactions for those set of addresses.

Update the fetch balance and transaction processing to send an array of objects each with a set of internal and external addresses as per this linked issue https://github.com/bithyve/internal-docs/issues/44

**Comment by Arpanjainson** [comment]
Make sure that balances are showing up correctly across accounts, for whole wallet, when there are F&F, TCs etc with multiple transactions. Test it after restore as well. 
Test on live for sure.
