### ISSUE TITLE
Properly "disable" adding new accounts for account kinds that arent supported yet.

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#2045]
The designs for the [Add New Account screen](https://xd.adobe.com/view/a9aaad23-c5ea-4067-8734-cf64073bca02-fcf9/screen/44d9a188-30a2-47fc-9764-16c0dd10bbdf/specs/) have us showing all of the potential account kinds that we plan to support. However, functionally, some of these account kinds are still unsupported -- so we need some requirements around how to properly disable their selection from this screen.

**Comment by AliMeer** [comment]
Closing as this is completed and available in the `development` branch.
