### ISSUE TITLE
Disable screen on processing

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2046]
Look for all the flows where processing happens like: 
1. Confirm in Send flow - grey screen with spinning wheel in the center 
2. Account refresh - grey screen with spinning wheel on the top
3. Manage Backup refresh - grey screen with spinning wheel on the top
4. F&F refresh - grey screen with spinning wheel on the top (there is no loader currently on this screen)
5. Skip button on Associate Contact - grey screen with spinning wheel in the center 
6. Donation creation - grey screen with spinning wheel in the center 

More @AliMeer @cakesoft-nikhita 

#1970 - please merge the two

**Comment by antuz123** [comment]
@cakesoft-nikhita - what is pending here?

**Comment by cakesoft-swati** [comment]
4th and 5th one is pending here.

**Comment by cakesoft-swati** [comment]
-Tested on Android live app version 1.3.2(172)
-I selected a contact to send a recovery key(from Maage Backup>Friends and Family).Then I clicked on Share button and before generating the link I clicked on back button.Again I go to that contact and tried Reshare option but now then my share and QR buttons did not work.
-I tried it on second friends and Family but here also I was not ableto click on share/QR button.

**Comment by cakesoft-nikhita** [comment]
@cakesoft-swati Above issue is not reproducible and when we change our bottom sheet with a new home type bottom sheet in the whole app then our background is automatically restricted to click then this type of issue is automatic gets resolve
Also above list point number 5 Skip button on Associate Contact - grey screen with a spinning wheel in the center
for this, there is some coding restriction so I cannot add the whole screen loader but Parsh already disabled skip button when the user clicks first time

**Comment by Arpanjainson** [comment]
@cakesoft-swati  please try again

**Comment by cakesoft-swati** [comment]
-Unable to reperoduce this issue .
-Verified on dev appversion 1.4.0(180)

**Comment by cakesoft-swati** [comment]
On clicking the Proceed button of Donation account, it is being enabled again.

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app version 1.4.1(195)
