### ISSUE TITLE
Cache config values and don't initialise a new config object each time

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2049]
Current Hexa Config initialises a new config object each time it is imported.
This can be optimised to cache the initial version and reused throughout the app.

**Comment by antuz123** [comment]
@AliMeer - important to state what the user impact is here. Not possible to prioritise it otherwise. This is not Account Management so should ideally have a user scenario.

**Comment by Parsh** [comment]
The config object is initialized only once(during the initial import post login), every other import uses the same object within that session, discovered this behavior during the own node configuration changes.

**Comment by AliMeer** [comment]
> The config object is initialized only once(during the initial import post login), every other import uses the same object within that session, discovered this behavior during the own node configuration changes.

That’s a good find 👍

**Comment by AliMeer** [comment]
This issue does not require a change anymore.

**Comment by AliMeer** [comment]
This was a Dev task. This has been completed.
