### ISSUE TITLE
Last Seen indicators showing incorrect status.

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2054]
Last Seen is not showing correct status, it's always grey and message always says "seen a few seconds ago".
<img width="197" alt="Screenshot 2020-11-14 at 19 27 38" src="https://user-images.githubusercontent.com/7535475/99155398-848e9080-26af-11eb-9093-f99703074e57.png">

**Comment by Arpanjainson** [comment]
I can see "last seen a few minutes ago"

**Comment by cakesoft-swati** [comment]
I can see"last seen 35 minutes ago" with green color.
![Screenshot_20201118-123523_hexa stage](https://user-images.githubusercontent.com/62699947/99496596-a4b59c80-299a-11eb-90a6-4bd17ed65675.jpg)
