### ISSUE TITLE
F&F request confirmation not successful

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2055]
F&F request for trusted contact may not be completing successfully we may be showing the countdown even if the request is successful

**See attached images for reference**

**Scenario**
Ali made a "add a contact" request to Jz using Associate Contact via QR code.
Jz accepted by scanning QR code and associating contact.

Result:
A)
Ali can see a countdown timer even though Jz has accepted request.
Jz does not see countdown timer.

![7142D7CD-842E-41AD-A1C7-1B0E18516739_1_105_c](https://user-images.githubusercontent.com/7535475/99156452-d5ef4d80-26b8-11eb-8dd9-d60765e33abc.jpeg)

B) 
Jz is able to send to Ali by choosing as a contact from the send screen.
Transaction is received in Ali's phone and shows up as coming from Jz
However
Transaction is not showing in Jz's phone as having been sent to Ali.

![45F3ECB4-6772-4943-BC36-83F937795CAB_1_105_c](https://user-images.githubusercontent.com/7535475/99156461-e8698700-26b8-11eb-8b6b-89dd54a42cdf.jpeg)

**Comment by AliMeer** [comment]
@CypherPoet please check if the counter display logic is using the right conditions once verified @Parsh can verify if trusted channel is being established correctly.

**Comment by Parsh** [comment]
Only the incoming tx have name tags(if they came via trusted contacts), there's no clean strategy to do it for outgoing txs tho.
