### ISSUE TITLE
Scan old contacts xpub

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2062]
In case of change contact the app should still hold and scan the old contacts xpub

**Comment by Arpanjainson** [comment]
steps to test 
user A to add a trusted contact or keeper and ask the friend to accept the request.
Remove the TC or keeper from User A.
Ask the TC or keeper to send a TXn via FF list to user A. The funds should show up under UserA's wallet, even if the contact/keeper was removed.

**Comment by cakesoft-swati** [comment]
-Unable to test this on app version 1.3.1(163)
-I can't get rid of timer.

**Comment by Arpanjainson** [comment]
It seems the recipient is not able to send to the contact if the other person removed the contact.
