### ISSUE TITLE
UI issue on bulk send.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2064]
-Bulk send - the third recipient or subsequent ones get added towards the end on the recipient list and not visible, possibly make them first on the list i.e. last to first in order.
![File (3)](https://user-images.githubusercontent.com/62699947/99220219-4060d480-2804-11eb-9bea-fe5e7abbace8.jpg)

**Comment by CypherPoet** [comment]
Is the issue here that contacts aren't visible, or that the ordering should be changed? My understanding of the design is that the list is supposed to overflow and then scroll.

**Comment by Arpanjainson** [comment]
tested on stage
