### ISSUE TITLE
The confirmation screen shows number instead of the recipient initials.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2067]
-Selected Send to contact but the confirmation screen shows number instead of the recipient initials.
![File (5)](https://user-images.githubusercontent.com/62699947/99221689-0e04a680-2807-11eb-9252-d04136aacb66.jpg)

**Comment by AliMeer** [comment]
@cakesoft-swati Was this contact added as a F&F contact or as a keeper?

**Comment by cakesoft-swati** [comment]
-Now it is showing "No Name" instead of of the recipient initials.
![Screenshot_20201117-145105_hexa stage](https://user-images.githubusercontent.com/62699947/99371295-bc324e00-28e4-11eb-8aa5-e5f83ed3325b.jpg)

**Comment by Arpanjainson** [comment]
When sending to a contact, the name of contact does not show up on the confirmation screen.

**Comment by Arpanjainson** [comment]
https://files.slack.com/files-pri/TEBLGFFFH-F01EJUP0Z39/file.jpg

**Comment by cakesoft-swati** [comment]
Address icon @ and address first few characters are not showing up when address is a recipient.

**Comment by antuz123** [comment]
This should work for Keeper and F&F

**Comment by cakesoft-swati** [comment]
Verified this on dev app version 1.3.2(170)
