### ISSUE TITLE
Google Pixel 4a Testing

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2069]
Need to verify testing in Google Pixel 4a

UI is not appearing correctly in Google Pixel 4a

![Screenshot_20201116-124406](https://user-images.githubusercontent.com/7535475/99255254-92f1bf00-280b-11eb-98be-9307229038e3.png)
![Screenshot_20201116-123831](https://user-images.githubusercontent.com/7535475/99255256-938a5580-280b-11eb-81f5-104c543cebdd.png)
![Screenshot_20201116-123822](https://user-images.githubusercontent.com/7535475/99255258-9422ec00-280b-11eb-9068-3e24a123a504.png)

**Comment by Arpanjainson** [comment]
@AliMeer  do you happen to have a Google pixel 4a?

**Comment by Arpanjainson** [comment]
1080 x 2340 pixels

**Comment by Arpanjainson** [comment]
@AliMeer  to ask Danny to upgrade to 1.3.2

**Comment by cakesoft-swati** [comment]
Unable to test this.
-As 1080 x 2340 pixels-The android devcie of this resolution is not available on Browser stack.

**Comment by AliMeer** [comment]
Closing this issue as we have not had response from Danny to test this. We have tested this pixel 4a already and did not find the issue.
