### ISSUE TITLE
Tick mark on already selected contact in send

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2077]
- As per design a contact which was already added during bulk send should show a tick mark.
![File (8)](https://user-images.githubusercontent.com/62699947/99350761-23d8a100-28c5-11eb-998b-be801f60d99b.jpg)

**Comment by Arpanjainson** [comment]
cant see the tick mark yet. Added a contact as recipient and then add recipient, the contact does not have an overlay tick mark.

**Comment by Arpanjainson** [comment]
works as expected on stage, but not on latest dev

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app version 1.3.2(170)
