### ISSUE TITLE
Unable to remove expired Keeper from F&F list.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2078]
-An old Keeper shows up in F&F list as expired even if it was replaced by a new. 
-Cant remove it even.

**Comment by Parsh** [comment]
@cakesoft-swati Can you please let me know the steps to replicate the above scenario? I've already tried the standard contact change flow and it didn't cause this issue, is there any specific action that leads to this?

**Comment by cakesoft-swati** [comment]
-Unable to replicate this issue on latest app.
