### ISSUE TITLE
Issue while trying to remove the recipient.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2080]
-I've added two recipients i.e Arpan sir (F&F recipient) and saving account.
![Screenshot_20201117-130555_hexa stage](https://user-images.githubusercontent.com/62699947/99361852-bd5d7e00-28d8-11eb-93f5-3c5c3cfbda1f.jpg)

-When I'm trying to remove Arpan sir,it is showing that I'm removing account(but no name is specified below "Sending to").
![Screenshot_20201117-130639_hexa stage](https://user-images.githubusercontent.com/62699947/99361760-9b63fb80-28d8-11eb-8de2-a06a7f99d262.jpg)

-When I'm trying to remove Savings account,it is showing that I'm removing Arpan sir.
![Screenshot_20201117-130630_hexa stage](https://user-images.githubusercontent.com/62699947/99361833-b898ca00-28d8-11eb-9fbe-d32314e1a240.jpg)

**Comment by cakesoft-swati** [comment]
-Now app is crashing while trying to remove recipient.
-Tested on staging app version 1.3.1(164)

**Comment by Arpanjainson** [comment]
i too was able to recreate this

**Comment by cakesoft-swati** [comment]
-Verified thisissue on dev app version 1.3.2(170)
