### ISSUE TITLE
UI changes on Send screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2081]
![Screenshot_20201117-133439_hexa stage](https://user-images.githubusercontent.com/62699947/99362773-e6324300-28d9-11eb-9200-b9d634efd597.jpg)
-Please create as per the design.
-Reduce the QR scanner size and also decrease the space between QR scannerand Send to contact.

**Comment by AliMeer** [comment]
Lets reduce the scanner and image size so that controls below the scanner are visible.

**Comment by AliMeer** [comment]
Screen shot from previous version of the screen showing a more compact layout with less space between components and a smaller QR scanner.

![File (1)](https://user-images.githubusercontent.com/7535475/99393897-ef211580-28d5-11eb-86a1-f7fe3bcf567d.jpg)

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app version 1.3.1(164)
