### ISSUE TITLE
Sub Account Balance/UTXO failure

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2091]
Balance and utxo set for sub accounts isn't updating post new endpoint integration w/ wrapper.

**Comment by Arpanjainson** [comment]
@Parsh  what needs to be tested here -  test multiple accounts with transactions, check balances are showing up and subsequently send  and check balances again?

**Comment by Parsh** [comment]
We need to test whether the wallet is able to spend the sats received from a trusted contact.
