### ISSUE TITLE
UI changes in Send To Contacts flow.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2092]
Send To Contacts Flow: 'last seen active" color indicators on contact avatars.
![tempFileForShare_20201118-141522](https://user-images.githubusercontent.com/62699947/99509947-7771ea00-29ac-11eb-8474-62da34ae411f.jpg)

-Recipient name(initials)is different(Showing F1/F2 instead of wallet name initials).9-9a1b0eaa4274.jpg)
-Recipient name icon is being cut from the top side.
[This is happening in case of Skip contact]

**Comment by antuz123** [comment]
This example is for Keeper.

**Comment by CypherPoet** [comment]
@antuz123 My understanding is that the wallet name is only supposed to be used as a fallback for when the recipient name doesn't exist. Wouldn't we want the recipient initials to show here?

**Comment by antuz123** [comment]
@CypherPoet - that is ideal but in skip scenarios, we don’t have the initials. What do you suggest the initials to be?

**Comment by CypherPoet** [comment]
I think if we don't have name information for a contact, we should use the wallet name as the `displayedName`. Right now, it looks like we're setting the displayed name to "F&F Request" when there's no actual contact name (see the issue noted [here](https://github.com/bithyve/hexa/issues/2004#issuecomment-728635654))

**Comment by antuz123** [comment]
That is done when the requester has not Associated a Contact, and the request is not yet accepted. In that case, the wallet name from the receiver is not received. So the "F&F Request" is a temporary placeholder that is to be replaced by the wallet name when received from the receiver.

**Comment by CypherPoet** [comment]
🤔 That would suggest this is an issue of the placeholder name not being properly removed, because the UI is still finding it set when it also has a wallet name that should be displayed instead.

**Comment by antuz123** [comment]
yup

**Comment by CypherPoet** [comment]
#2097 Adds a few changes to get around this in the meantime.

**Comment by cakesoft-swati** [comment]
![tempFileForShare_20201125-154614](https://user-images.githubusercontent.com/62699947/100214133-7fde9d80-2f35-11eb-9285-996967537f92.jpg)
Having same issue on dev app version 1.3.2(170)
-This is for both keeper and trusted contact request.

**Comment by AliMeer** [comment]
Doesn't seem to be clipped or cropped. Would be great to know what the residual issue is.

**Comment by cakesoft-swati** [comment]
-Display name is different on 'send to contact' and F&F list. In F&F list it is showing csDev and on in send to contact flow it is showing F1 as a contact image.

**Comment by CypherPoet** [comment]
I haven't been able to replicate this locally -- right now the [code is set up](https://github.com/bithyve/hexa/blob/development/src/common/data/models/interfaces/RecipientDescribing.ts#L67) to check for a name matching `F&F request` to handle the intricacies noted [here](https://github.com/bithyve/hexa/issues/2004#issuecomment-728635654).

@AliMeer @antuz123 @Parsh Is there another string or set of strings that should be checked to detect F&F requests? 

(https://github.com/bithyve/hexa/issues/2056 will also help with these issues)

**Comment by cakesoft-swati** [comment]
Tested on live app version 1.3.2(170)
<img width="375" alt="795EAD0A-5C35-48D7-88F8-04DBA3BF6321" src="https://user-images.githubusercontent.com/62699947/100318347-e3bf9f80-2fe3-11eb-907e-77bd48f4571a.png"

**Comment by Arpanjainson** [comment]
F1 F2 F3 is showing up on the contact circle, it should be the wallet initials instead.. through out the app for skipped contacts

**Comment by CypherPoet** [comment]
@cakesoft-swati  Can we get this re-checked against the latest build

**Comment by AliMeer** [comment]
@cakesoft-swati It will be very useful to know which part of this issue is still outstanding and mention that as a new comment or a new issue.

**Comment by cakesoft-devika** [comment]
Tested on Dev app v1.7.0 (283), still showing F1 instead of wallet initials 
![Screenshot_2021-05-10-12-52-43-154_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/117627989-496ca600-b196-11eb-8725-b1cf3e459d41.jpg)

**Comment by cakesoft-swati** [comment]
-Verified this isue on dev app v1.7.5(302)
