### ISSUE TITLE
Transaction do not show up on the transaction modal.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2093]
-Happens only on Donation account - txns are present on the account and transactions modal of Home screen but do not show up on the View more's Transactions modal.
![Screenshot_20201118-155710_hexa stage](https://user-images.githubusercontent.com/62699947/99521201-22d56b80-29ba-11eb-9e28-75c684c3a082.jpg)

-
![Screenshot_20201118-160028_hexa stage](https://user-images.githubusercontent.com/62699947/99521224-2b2da680-29ba-11eb-8e7b-4f0dcc26d38c.jpg)

**Comment by Parsh** [comment]
Unable to replicate. @cakesoft-swati Is it happening on a consistent basis and are there more details that you can provide that could lead to this?

**Comment by cakesoft-swati** [comment]
-Verified this on dev app version 1.3.2(170)
