### ISSUE TITLE
Uncouple screens from old Accounts structure

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#2104]
Making this as a catch-all issue to track various screens that need to be refactored in ordered to function with the new accounts structure introduced in #1663. (There may well be some that I'm missing, and I'll try to update this as I find them.)

Ideally, these changes can be merged into that PR's branch before merging that PR itself.

- Accounts -> Send screens (#2039)
- Contacts -> Send screens
- Receive screens
- Voucher Scanner
- Funding Sources Screens
- ManageBackup Screens
- Accounts -> TwoFASetup
- Accounts -> Transactions Screens

**Comment by AliMeer** [comment]
Removing tag 1.4.0 from this as this has been done for 1.4.0

**Comment by AliMeer** [comment]
Closing this as this was an generic task for all account management.
