### ISSUE TITLE
Error modal button labels need correction

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2114]
- No passcode set on device modal message has a button with “OkayOk”
- Permission denied message has “OkayTry Again”
- Some have “”OkayContinue”

<img width="517" alt="Screenshot 2020-11-22 at 20 43 35" src="https://user-images.githubusercontent.com/7535475/99916702-900f3680-2d03-11eb-9f7a-4070ff93eaab.png">
<img width="493" alt="Screenshot 2020-11-22 at 20 42 09" src="https://user-images.githubusercontent.com/7535475/99916703-91406380-2d03-11eb-844f-efe377432229.png">

**Comment by cakesoft-swati** [comment]
-Verified this on dev app version 1.3.2(170)
Now showing OK button..
