### ISSUE TITLE
1.3.2 dependencies tracked elsewhere

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2115]
Entire list: https://github.com/bithyve/internal-docs/issues?q=assignee%3AAliMeer+is%3Aopen+label%3A1.3.2

**Comment by antuz123** [comment]
@AliMeer - we don't understand how to close this one. You will have to close this.

**Comment by AliMeer** [comment]
These were tasks for 1.3.2 release, which have been completed. Closing.
