### ISSUE TITLE
Security Answer health  is not being updated

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2116]
Fresh installed phone, going to manage health for the first time. Security answer health is shown as red. Confirming the correct answer is accepted but health continues to show as red.

Restarting app and going back to manage backup shows security answer health as green

<img width="341" alt="Screenshot 2020-11-23 at 00 38 26" src="https://user-images.githubusercontent.com/7535475/99921744-53a00280-2d24-11eb-96e0-6e108e38f9e9.png">

**Comment by Parsh** [comment]
It is working for me on a fresh install of version 1.3.2(168)

![Screenshot_20201124-173703](https://user-images.githubusercontent.com/17980466/100092299-d5567400-2e7b-11eb-8178-8138f4dd1882.jpg)

**Comment by AliMeer** [comment]
This works for me too.

**Comment by cakesoft-swati** [comment]
Now it is showing green tick but the health percentage is different(wrong) on both the devices.
1.Fresh installed app on android device
![Screenshot_20201124-140225_hexa dev](https://user-images.githubusercontent.com/62699947/100096556-3123fb80-2e82-11eb-8c4e-7ad96ebab822.jpg)

2.Fresh installed app on ios.
![IMG_20201124_184229](https://user-images.githubusercontent.com/62699947/100099156-0ab38f80-2e85-11eb-90ac-ebe2ca95a080.jpg)

**Comment by Parsh** [comment]
This seems to be only happening on Android, we tested it on iOS(both device and simulators) and it was working as expected.

**Comment by cakesoft-swati** [comment]
-Still it is showing the wrong Health percentage.
-Tested on Dev app version 1.4.0(180)
![Screenshot_20201210-124349_hexa dev](https://user-images.githubusercontent.com/62699947/101733953-9d8b3580-3ae5-11eb-9d6c-e30107f9d85c.jpg)

**Comment by cakesoft-swati** [comment]
-Unable to reproduce this issue on v1.7.5
