### ISSUE TITLE
Issues when setting up new wallet.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2121]
-while entering the answer, if i click erase once it deletes the entire thing.
-Also, if i click on the previous field, the answer gets deleted.
[2.mov.zip](https://github.com/bithyve/hexa/files/5581827/2.mov.zip)

**Comment by AliMeer** [comment]
@cakesoft-swati was this working before?

**Comment by CypherPoet** [comment]
@AliMeer @cakesoft-swati @antuz123 Clearing the text completely does seem to be the intent of [the current code](https://github.com/bithyve/hexa/blob/17459a3f6b09758979d77243c18d1553e2151928/src/pages/NewWalletQuestion.tsx#L142).

**Comment by cakesoft-swati** [comment]
No it's the same from day one.

**Comment by cakesoft-swati** [comment]
-Verified this on Dev app version 1.3.2(170)
