### ISSUE TITLE
"Last seen active" text and color indicator chnages.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2122]
-Contacts are showing Last seen a few seconds ago while grey indicator? This is incorrect. This may be as these are contacts before we upgraded and so their data structure is different. But as we know they were seen a few seconds ago then we should have a green indicator. However in this specific scenario, I think that these contacts are not active for a while and so there indicator is correct while the statement is not correct.
![IMG_1255](https://user-images.githubusercontent.com/62699947/99958645-c30f0400-2daf-11eb-94e3-2c38b262da6b.jpg)

-I don’t see the logic for seen few seconds ago. It should only be in days. Last seen today and otherwise last seen x days back. In dev also the time may be in minutes but it should show days as text. So less that 1 min in Dev is same as less than 1 day in Live and so should say, Last seen today.
![Screenshot 2020-11-23 at 3 49 18 AM](https://user-images.githubusercontent.com/62699947/99959111-737d0800-2db0-11eb-8f7c-cd4cd62552ae.png)

**Comment by AliMeer** [comment]
@CypherPoet this is because `.fromNow()` for `undefined` returns "a few seconds ago"

**Comment by CypherPoet** [comment]
Noting here that after discussing this, we've decided to not show the "last seen text" if the time is `undefined`. (The grey indicator will still display, though)

**Comment by cakesoft-swati** [comment]
-I'm still able to see the text "Last seen a few seconds ago" only in android device.
-Tested on Dev app version 1.3.2(168)

**Comment by cakesoft-swati** [comment]
Verified this issue on Dev app version 1.3.2(170)
-Now it is showing "last seen today" on both the devices.
