### ISSUE TITLE
Textual changes on F&F list.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2123]
-These lines are needed only if we are maintaining a flat list. So either we make this list a single list or if we are breaking them then we don’t need these lines. I suggest, we go to the latest design here.
![textual](https://user-images.githubusercontent.com/62699947/99959290-be971b00-2db0-11eb-9b8f-33d82e17c97d.png)

**Comment by CypherPoet** [comment]
@antuz123 @cakesoft-swati I agree that completely refactoring this screen with the latest designs is a good solution -- but that's something I'm planning to address [as part of the 1.4.0 changes](https://github.com/bithyve/hexa/issues/2039). 

Given that that would require some significant changes from the current code, it might be better to temporarily remove the line for 1.3.2.

**Comment by antuz123** [comment]
Ok

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app version 1.3.2(168)
