### ISSUE TITLE
Core Architecture Refactoring (src/bitcoin)

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2130]
- Implement functional counterparts of the methods bound with legacy account objects 
- Create data entities(tx, xpubs, utxos etc) in accordance with the AC cards(Trello) and acc-mgmt schema defined in the internal docs
- Implement acc-mgmt specific features such as reassigning txs, merging accounts etc.

**Comment by AliMeer** [comment]
Removing this from 1.4.x scope

**Comment by AliMeer** [comment]
This is open because o the followin issue not being implemented:

_Implement acc-mgmt specific features such as reassigning txs, merging accounts etc._

We should close this and create issue if we want to implement this feature.
