### ISSUE TITLE
Sagas and corresponding integrations(db & reducer)

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2131]
- write new actions & sagas corresponding to the changes done as a part of the new UI data model

This applies to functionalities in scope for Stage 1(1.4.0)
- Update Account Shells for current set of default accounts on wallet creation
- Update Account Shells when refreshing balances and transactions for individual Accounts
- Add New Account Shell for adding a new primary account
- Add New Secondary Sub Account to existing Shell. for addign TC or service acc.

**Comment by AliMeer** [comment]
Updated the description as per stage 1 scope(1.4.0)

**Comment by AliMeer** [comment]
> Updated the description as per stage 1 scope(1.4.0)

@Parsh this one is done as well. please verify and update.

**Comment by Parsh** [comment]
Yep, this is done.
