### ISSUE TITLE
Refactor reducers

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2133]
Reducers need to be refactored in order to streamline the integration with the acc-management UI and have sagas to dispatch appropriate actions to update them.

**Comment by CypherPoet** [comment]
Some related issues:

- https://github.com/bithyve/hexa/issues/2106
- https://github.com/bithyve/hexa/issues?q=is%3Aopen+label%3A%22Account+Management%22+Data+Architecture+Refactoring

**Comment by AliMeer** [comment]
@Parsh I think this one is done. Any further changes might be required after testing.
