### ISSUE TITLE
Wallet Image modifications

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2134]
Update the wallet image synchronization and restoration mechanism based on the refactored account management structure.
Elements that are being backed up as a part of WI can be further divided into smaller chuncks(reducing the encryption and data-transfer size) due to structural refactoring.

Depends on #2130 and #2132

**Comment by AliMeer** [comment]
This task is now smaller in scope, but we still need to assess the current changes for 1.4.0 and accordingly update the wallet image for upgrading from 1.3.x

**Comment by Parsh** [comment]
Yes, we'll need to backup(&sync) account shells such that they can be restored.

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app version 1.4.0(180)
-Able to see the all accounts after restore.
