### ISSUE TITLE
Migration Script

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2135]
Write migration script(s) to upgrade previous app versions(on legacy architecture) to the new acc-mgmt architecture.

Depends on #2130

**Comment by AliMeer** [comment]
Now we don't need to account for migrating data to the new database, but we still need to ensure v1.3.x can be upgraded to 1.4.x

**Comment by Parsh** [comment]
Migration script for upgrading from versions lower than 1.4.0 is in place(have tested with 1.3.2) and for restoring an app that was backed up using a <1.4.0 app.

**Comment by cakesoft-swati** [comment]
Tested this on 1.3.2 to 1.4.0
