### ISSUE TITLE
App Release notifications are not in order

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2143]
https://files.slack.com/files-pri/TEBLGFFFH-F01FT6H9DCH/image_from_ios.png

**Comment by AliMeer** [comment]
This is possibly a relay issue.
This needs to be retested after firebase upgrade

**Comment by Arpanjainson** [comment]
@cakesoft-swati may need help from @AliMeer  to add entries on server to test the ordered release list.

**Comment by cakesoft-nikhita** [comment]
@AliMeer I am assigning this issue to you this change needs to be done on the relay
