### ISSUE TITLE
Send is crashing

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2154]
-App is crashing while scanning the receive QR.
-It crashes as soon as we paste an address on send screen.
-The app is crashing even while sending to a contact.(Only on upgraded app,upgraded from 1.3.1(64)-1.3.2(171))
-It is crashing on both dev and live app.

**Comment by Parsh** [comment]
#2158 fixes the above, tho not all scenarios are tested(but are likely to work). @cakesoft-swati Do specifically test the send via QR scan as I've not been able to test it.

**Comment by AliMeer** [comment]
The fix is in v1.3.2 # 172

**Comment by cakesoft-swati** [comment]
-Verified this issue on hexa live app version 1.3.2(172)
