### ISSUE TITLE
Restore old version apps - F&F list is empty

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2155]
Install older version say 0.7 or 0.8 - add F&Fs and do backup
Upgrade to v1.3.1 and see F&F shows up.
--
Then delete the app and restore to 131 using the shares backed up from 0.7 or 0.8 - check F&F shows up.

**Comment by Arpanjainson** [comment]
@AliMeer @Parsh  how do we have old 0.7 and 0.8 app for iOS?
@antuz123  can we try on a higher version?

**Comment by Arpanjainson** [comment]
We can try testing this after upgrading from 1.1 or what ever is available in testflight for now...
The app does loads the F&F but does not show the list, when a user tries to add the same F&F the app says the contact already exists

**Comment by cakesoft-swati** [comment]
-Unable to replicate this issue.
-I downloaded 1.1.2(115) then upgraded it to 1.3.2(172) n then restored the wallet.But I can see the transactions also the f&F list.
-I will try to replicate this with different scenarios.

**Comment by Arpanjainson** [comment]
Cant recreate from 1.1.1 to 1.3.2 restore

**Comment by cakesoft-swati** [comment]
-Unable to replicate this issue.
-Tried all the senarios of upgrade.
-Upgraded from 1.1.1 to 1.3.2 then 1.4.0
