### ISSUE TITLE
Transaction value is showing as 0 on checking account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2156]
-Tested on live app version 1.3.2(171)
-Now the transaction value is showing as 0.
-The old transactions in the checking account are also showing 0 when I am sending from a checking account.
<img width="375" alt="CDD97A63-A3A2-48C3-92C9-09E47C02FEAB" src="https://user-images.githubusercontent.com/62699947/100312567-b1f50b80-2fd8-11eb-8763-1bb29e9d8687.png">

**Comment by cakesoft-swati** [comment]
![Image from iOS (2)](https://user-images.githubusercontent.com/62699947/100315758-26cb4400-2fdf-11eb-9f93-7710ff9051cd.png)


![Image from iOS (1)](https://user-images.githubusercontent.com/62699947/100315790-36e32380-2fdf-11eb-809c-575f93d77924.png)

**Comment by Parsh** [comment]
Need to replicate this. Depends on #2154

**Comment by Parsh** [comment]
@cakesoft-swati can you please reproduce it and let me know the how-tos? On testnet it doesn't seem to happen, can probably be a mainnet specific issue but ya a confirmation would definiely help.

**Comment by AliMeer** [comment]
Would recommending testing this in v1.3.2 # 172 together with the send crash fix.

**Comment by cakesoft-swati** [comment]
-![Screenshot_20201126-174649_hexa](https://user-images.githubusercontent.com/62699947/100350227-8f321980-300f-11eb-91be-d89d4ca68de8.jpg)
-I sent 15k from Donation account(just did a upgrade from 171-172) to checking account(fresh installed 172),still the transaction value is showing as 0 on checking account.

**Comment by Parsh** [comment]
The mainnet wrapper seems to return an incorrect amount value for the above.

<img width="1440" alt="Screenshot 2020-11-26 at 6 19 04 PM" src="https://user-images.githubusercontent.com/17980466/100353055-edf99200-3013-11eb-8ac4-7d7644396137.png">

**Comment by AliMeer** [comment]
Can we retest this please?

**Comment by AliMeer** [comment]
Screen short from Test-Live v1.3.2 # 172
Mainnet Checking Account
Sent and received transactions are showing correct amount.

![IMG_0239](https://user-images.githubusercontent.com/7535475/100392310-0f677780-302e-11eb-8e6e-a4a905129a27.PNG)

**Comment by cakesoft-swati** [comment]
-Now it's working.Verified on Hexa live app version 1.3.2(172)
