### ISSUE TITLE
Send max(with 2FA and Donation) is failing.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2161]
-When I am doing send max(from saving/donation account with 2FA) it is showing send unsuccessful due to invalid 2FA while sending some less amount instead of send max is being successful.

**Comment by Parsh** [comment]
@cakesoft-swati How frequently is it happening?

**Comment by cakesoft-swati** [comment]
This happened 3 times(send unsuccessful) and was successful only once.

**Comment by Parsh** [comment]
Can you post the screenshot of the error that's being thrown? That would help.

**Comment by cakesoft-swati** [comment]
I had 14k bal in savings account n was trying to send 10k with 2k fees but that was unsuccessful.After that I tried it with 5k+1000 fee and it become successful.
-After this succesfull transaction my bal was 7798.I tried send max with 2416 fee but againg it was faile due to invalid token.
![IMG_1301](https://user-images.githubusercontent.com/62699947/100356873-d91ffd00-3019-11eb-8102-805f10d6d2ef.PNG)

![IMG_1298](https://user-images.githubusercontent.com/62699947/100356960-02d92400-301a-11eb-90c0-8a1edcebafe9.PNG)

![IMG_1299](https://user-images.githubusercontent.com/62699947/100357063-27350080-301a-11eb-990b-0d1a90a2e147.PNG)

**Comment by Parsh** [comment]
Have tested the following:

1. Send from Checking: Both normal send and send max worked fine for checking acc.

![Simulator Screen Shot - iPhone 11 Pro - 2020-11-27 at 13 05 45](https://user-images.githubusercontent.com/17980466/100435777-6cae0800-30c4-11eb-905e-59b8a64e565a.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-11-27 at 13 07 04](https://user-images.githubusercontent.com/17980466/100435785-70418f00-30c4-11eb-9b5e-d3480f3f483f.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-11-27 at 13 07 33](https://user-images.githubusercontent.com/17980466/100435787-70da2580-30c4-11eb-8d34-77ae4e5ba73a.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-11-27 at 13 07 41](https://user-images.githubusercontent.com/17980466/100435790-7172bc00-30c4-11eb-99ba-73da025e6d87.png)


2. Savings: Send max to donation worked(no err while entering OTP)

![Simulator Screen Shot - iPhone 11 Pro - 2020-11-27 at 13 56 46](https://user-images.githubusercontent.com/17980466/100435977-bb5ba200-30c4-11eb-9a77-a01b9ae46b57.png)

3. Donation(2FA): Both normal and send max from donation worked as well

![Simulator Screen Shot - iPhone 11 Pro - 2020-11-27 at 13 57 52](https://user-images.githubusercontent.com/17980466/100436029-cca4ae80-30c4-11eb-8f36-5b545d20e7bb.png)

Note: All the scenarios have been tested on the mainnet for build 1.3.2(172)
