### ISSUE TITLE
Upgrade Firebase to v6 - Notifications, Messaging and Crashlytics

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2176]
1. Remove Fabric Crashylitics and upgrade to firebase crashylitics v6
2. Upgrade Notifications and Messaging to firebase version v6
3. Update notificaitons/Messaging code to use new version of firebase 
4. Setup crash reporting to be delivered with stack trace.
5. Ensure builds are successful on local env and appcentre for all 3 targets

P.S: 
Reference for Crashlytics configuration without logging IP:
https://firebase.google.com/docs/crashlytics/get-started?platform=android

**Comment by antuz123** [comment]
We know now that there is a way to use Crashlytics without logging IP

**Comment by AliMeer** [comment]
> We know now that there is a way to use Crashlytics without logging IP

Yes, this task was actually to upgrade to Firebase as Fabric Crashylitics is now deprecated.

To start using Crashylitics in our app for error reporting will require additional updates to the code in the app.

**Comment by cakesoft-nikhita** [comment]
@AliMeer Sir, @antuz123 Sir, we need to consider Analytics upgrade also. As we are upgrading the Firebase library so Firebase analytics will upgrade. Also for Firebase Notifications and Messaging, we need to use another package as Firebase only suggests this. Please refer to https://rnfirebase.io/migrating-to-v6#notifications link. So, for Crashlytics we use Firebase Crashlytics, and for Notification and messaging we need to use https://github.com/zo0r/react-native-push-notification

**Comment by AliMeer** [comment]
@cakesoft-nikhita yes that’s the correct site for reference and yes the notifications after upgrade will use react-native-push-notifications.
Yes analytics module will need to be migrated to v6 as well.

**Comment by Arpanjainson** [comment]
@AliMeer  could you send me steps where to check the crashalytics and to make sure that IPs are not tracked.

**Comment by Arpanjainson** [comment]
@AliMeer  - bump please

**Comment by AliMeer** [comment]
The steps and links to track crashyltics reports has been sent. This activity has been completed.
