### ISSUE TITLE
AC1.1 -- Home Screen Accounts list -- Display correct Balance for each Account

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#2186]
@AliMeer @antuz123 Is the idea here to display the balance for the primary sub-account in the shell, or the total balance for all sub-accounts in the shell?

**Comment by AliMeer** [comment]
This will be the total of primary and sub-accounts. Currently, the balance updated by the reducer is the total balance and that's what needs to be displayed. this is working in the current build..

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app version 1.4.0(180)
