### ISSUE TITLE
Transactions do not show up on the transaction modal.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2189]
-Happens only on Donation account - txns are present on the account and transactions modal of Home screen but do not show up on the View more's Transactions modal.
-Tested on production app version 1.3.2(175)
![Screenshot_20201202-143706_hexa](https://user-images.githubusercontent.com/62699947/100853447-c724db00-34ad-11eb-921e-e7b53c786c55.jpg)

![Screenshot_20201202-143656_hexa](https://user-images.githubusercontent.com/62699947/100853474-cee47f80-34ad-11eb-846e-e6d27719ade2.jpg)

**Comment by AliMeer** [comment]
This is fixed in 1.4.0 itself in build # 184

**Comment by cakesoft-swati** [comment]
Verified this issue on staging app v1.4.0(184)
