### ISSUE TITLE
Account Refresh.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2198]
-For Account Refresh, we don’t need the grey cover, we should remove that. Also the screen should be active and the user should be able to click on any button.
-The buttons were not clickable properly even in previous releases so it will not be just about removing the grey screen.
![File (13)](https://user-images.githubusercontent.com/62699947/100966561-34d71280-3553-11eb-96fe-790534c53f24.jpg)

**Comment by antuz123** [comment]
@CypherPoet - you may be doing this anyway in the new structure but if not then we want to make sure that while a refresh is happening the screen is accessible and the user can easily go into Send or a Transaction etc.

**Comment by CypherPoet** [comment]
So by "grey cover", this refers to the loading indicator? My understanding was that we wanted to keep this as part of the pull-down-to-refresh UX (#2201). 

If the idea is to remove the indicator, are we also saying we don't want the pull-down-to-refresh behavior at all (in favor of refreshing data invisibly behind the scenes)?

@antuz123 @Arpanjainson @AliMeer

**Comment by CypherPoet** [comment]
Marking this as implemented on #1663 after getting clarification on the difference b/w/ the "grey cover" and the the pull-down-to-refresh indicator.

**Comment by antuz123** [comment]
We want the pull down feature and also the indicator but not the grey screen. 

Also the screen should be actionable like going into send while refresh happens in the background

**Comment by CypherPoet** [comment]
@antuz123 👍 . Tracking that on #2201

**Comment by cakesoft-swati** [comment]
1. while a refresh is happening the screen is accessible and the user can easily go into Send or a Transaction etc.
2."Grey cover"is removed.
-Verified this issue on dev app version 1.4.0(180)
