### ISSUE TITLE
Fee not updating so Send failing and Send Max crashing

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2199]
-Post upgrading the app to 175 (the release is live)
-Main app - the fee is still not showing, Send is failing and Send Max is crashing.

-I upgraded my wallet from 1.3.0 to 1.3.1 then I tried restore n it worked.After that I upgradeed it to 1.3.2 n tried recovery on it.Now the fee was 0 and send max was crashing on 1.3.2(175).
-Then I did a fresh install 1.3.0 and fees were high on 1.3.0(i.e 17854).I tried Restore on it n it also worked.Also the send was working.
-Then again I did a fresh install 1.3.2(175) and the fee was 8588 also the send was working.

**Comment by Parsh** [comment]
The fee discrepancy is due to the way 1.3.0 and 1.3.2 syncs the feeRates (1.3.0 does it every half an hour directly from Esplora while 1.3.2 fetches it from Relay which syncs every hour).

**Comment by antuz123** [comment]
@cakesoft-swati - marking it fixed as it needs to be tested in 1.4.0

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev ap version 1.40(180).
-Need to test it on live app with Upgrade and Restore scenarios.

**Comment by antuz123** [comment]
Will this need a patch? If the fee is ‘0’ the. Do something?

**Comment by antuz123** [comment]
Needs to be tested post production

**Comment by Arpanjainson** [comment]
we can test it on the live hexa release

**Comment by cakesoft-swati** [comment]
Verified this issue on staging app v1.40(184)

**Comment by cakesoft-swati** [comment]
-Verified this issue on live app version 1.4.0(188)
