### ISSUE TITLE
Send flow is failing on SendToContact.tsx

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2205]
The SendToContact screen is crashing, I've tried to ensure that all the navigation parameters are available for the screen, however, it still manages to crash with the below err. 

![Simulator Screen Shot - iPhone 11 - 2020-12-04 at 14 09 27](https://user-images.githubusercontent.com/17980466/101142577-ce79ef00-363b-11eb-94b4-714789dfd9f3.png)

**Comment by cakesoft-swati** [comment]
-Verified this on Dev app version 1.4.0(180)
