### ISSUE TITLE
Support for scanning bech32 addresses 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2211]
Ability to recognise payment URIs with bech32 address scheme. Uppercase, lowercase and combination of upper and lowercase payment uri's should be recognised.

QA: Use staging or live app and scan all 4 types of QR provided under “How to test” at this URL: 
HTTPS://github.com/btcpayserver/btcpayserver/issues/2110

**Comment by cakesoft-swati** [comment]
-I can scan all the 4 bech32 addresses from staging app v1.5.0(256).
- It is taking me to the send screen.
