### ISSUE TITLE
Send Flow for new Acc Management - Send to account

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2215]
Send flow for send to any account in acc management branch.
- All eligible accounts should be displayed in the accounts carousal to choose from.
- Sending to an account should successfully send to the selected account.

**Comment by CypherPoet** [comment]
@AliMeer @cakesoft-nikhita The first item here should already be in place on `feature/account-management`.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev appversion 1.4.0(180)
1.All eligible accounts are displayed in the accounts carousal to choose from.
2.Sending to an account is successfully send to the selected account.
