### ISSUE TITLE
Batch send for new acc management branch

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2216]
Batch send flow in acc management branch.
- All eligible accounts should be displayed in the accounts carousal to choose from.
- All contacts should be displayed in the contacts carousal to choose from.
- Should be able to select multiple contacts and accounts with different amounts.
- Send should successfully send the designated amount to the correct receiver.

**Comment by cakesoft-swati** [comment]
-Verified this on dev app version 1.4.0(178)
