### ISSUE TITLE
Refactor Fast Bitcoins Voucher Scanning to use new AccountShell structure

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#2217]

**Comment by AliMeer** [comment]
moving the refactor of the new fbtc account and the voucher screen to 1.4.1
For 1.4.0 we will keep things as is and track via different issue.

**Comment by AliMeer** [comment]
I think fastbitcoins changes should only be done after fastbitcoin test or dev environment is available

**Comment by AliMeer** [comment]
Moving this to be done after 2.1

**Comment by ASN-BitHyve** [comment]
We do not have fastbitcoins anymore.
