### ISSUE TITLE
UI changes of Receive Help screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2221]
![image](https://user-images.githubusercontent.com/62699947/101443627-ea370b00-3943-11eb-910e-266d2daadade.png)

[XD link]
https://xd.adobe.com/view/f11ac530-31c1-477d-adf4-22524b8b7ed3-a449/screen/8043e25c-3bfb-4f1b-a2bd-e2ab26bfc1dd/

[Issues to be handled -
1,3,4,5,6,8].

**Comment by CypherPoet** [comment]
@cakesoft-swati Could we get a more higher-resolution image attached to this issue? I'm having trouble reading many of the items and seeing what exactly they refer to.

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.1(192)
