### ISSUE TITLE
UI changes of Donation Account screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2222]
![image](https://user-images.githubusercontent.com/62699947/101443849-53b71980-3944-11eb-9a2a-03a58f8dc2ec.png)

[XD link]
https://xd.adobe.com/view/f11ac530-31c1-477d-adf4-22524b8b7ed3-a449/screen/be874862-08da-4bd0-9d51-7163441ee8f7/

[Issues to be handled -
all except -6
1 & 4  need to be checked with developer as it is a common change screens.]

**Comment by CypherPoet** [comment]
@cakesoft-swati Could we get a more higher-resolution image attached to this issue? I'm having trouble reading many of the items and seeing what exactly they refer to.

**Comment by CypherPoet** [comment]
Regarding 7: Whether or not we want to implement this in addition to #2269 seems to be undecided (@antuz123, @Arpanjainson @AliMeer).

#2346 should address the remaining points.

**Comment by cakesoft-swati** [comment]
-Verified these changes on Dev app v1.4.1(193)
