### ISSUE TITLE
Newly added account does not show up in the list of accounts on the send screen

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2231]
Add a new account, it shows up on home screen but does not show up on Send flow
IOS

https://files.slack.com/files-pri/TEBLGFFFH-F01GGLG2TDZ/file.jpg

**Comment by AliMeer** [comment]
@cakesoft-swati I would suggest you test this again in 179 or 180 please.

**Comment by cakesoft-swati** [comment]
-Verified this on Dev app version 1.4.0(180)
