### ISSUE TITLE
Not showing balance on home screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2234]
-Does not show balance.
![tempFileForShare_20201209-121214](https://user-images.githubusercontent.com/62699947/101594525-db218d00-3a17-11eb-9f9b-6b1196ac8123.jpg)

**Comment by AliMeer** [comment]
@cakesoft-swati does it always not show? or does it not show the first time the user logs on?

**Comment by cakesoft-swati** [comment]
-  It does not show the first time the user logs in.

**Comment by CypherPoet** [comment]
I haven't been able to reproduce this with the latest build. Are there any recommended steps for doing so?

**Comment by Parsh** [comment]
Fixed the initial login test-account 0 balance thing

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app v1.4.0(182)
