### ISSUE TITLE
Test accounts.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2236]
-Don’t need the ability to create more Test Accounts.
![tempFileForShare_20201209-122258](https://user-images.githubusercontent.com/62699947/101595481-68b1ac80-3a19-11eb-9ac5-30e6bce0e588.jpg)

**Comment by CypherPoet** [comment]
This seems inconsistent with the requirements listed in https://trello.com/c/qggPMfik

**Comment by antuz123** [comment]
As discussed, we hide it at the UX level for now. We can have it in 1.4.1 when we have discussed further and solved some issues relating to TA.

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app v1.4.0(182)
