### ISSUE TITLE
Order of accounts.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2237]
-The order should be: Not used accounts Then last created account Original set of accounts (Checking and then Savings) So here Donation should be the first item.
![tempFileForShare_20201209-122629](https://user-images.githubusercontent.com/62699947/101595742-e5448b00-3a19-11eb-950d-f7b6b8d6acf1.jpg)

**Comment by CypherPoet** [comment]
I'm not quite sure I understand what's meant by "Not used accounts" in this context.

**Comment by AliMeer** [comment]
Not used here is meant to be the accounts that the user doesn't have yet. So the in this scenario the user does not have a donation account yet so the donation account should be the first in the list.

**Comment by cakesoft-swati** [comment]
I think the order of accounts should be :Checking account n then savings account.
<img width="375" alt="AFC1F8A7-AB92-444C-8ADB-CB5EDF05B0DF" src="https://user-images.githubusercontent.com/62699947/102049018-20720000-3e06-11eb-9351-9f8376e5fbb4.png">

(Now the donation accunt is first in the list.)

**Comment by CypherPoet** [comment]
I ordered the donation account first in response to the [comment here](https://github.com/bithyve/hexa/issues/2237#issuecomment-742718912). 

Just wanted to confirm that the remaining issue is to order Checking before Savings by default. @AliMeer @antuz123 @Arpanjainson
