### ISSUE TITLE
Send from F&F crashing

### ISSUE THREAD

**Issue by cakesoft-nikhita** [bithyve/hexa#2241]
We need to handle navigation default params for F&F Send

**Comment by AliMeer** [comment]
As discussed yesterday send from F&F screen will happen from the default checking account.

**Comment by AliMeer** [comment]
Re Opening this as per update from @Parsh on friday.

**Comment by cakesoft-nikhita** [comment]
@Parsh In this case we need to add spendable balance as navigation props

**Comment by Parsh** [comment]
@cakesoft-nikhita Spendable balance is now available(merged to dev), you can test the send from F&F now.

**Comment by Arpanjainson** [comment]
183 iOS - upgraded from dev 182 - click on send in F&F list crashes the app

**Comment by Arpanjainson** [comment]
crashes on v183 FI dev iOS as well

**Comment by Arpanjainson** [comment]
crashing on staging as well

**Comment by antuz123** [comment]
same as 2430

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app V1.4.1(195)
