### ISSUE TITLE
Donation Account icon is not correct

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2244]
The donation account icon is showing up as different at different times when using the app.

These are screen shots of the same app at different times. between the screen shots the app was being used for send/receive or being rebooted.

![IMG_0035](https://user-images.githubusercontent.com/7535475/101680988-62dbbb80-3a59-11eb-8335-7ca2d016930a.PNG)
![IMG_0030](https://user-images.githubusercontent.com/7535475/101680999-67a06f80-3a59-11eb-89e7-1e296f4bf72c.PNG)
![IMG_0031](https://user-images.githubusercontent.com/7535475/101681001-68d19c80-3a59-11eb-80ef-317fa140b0c3.PNG)
![IMG_0032](https://user-images.githubusercontent.com/7535475/101681003-68d19c80-3a59-11eb-8bb7-b3f90f7cde95.PNG)
![IMG_0036](https://user-images.githubusercontent.com/7535475/101681004-696a3300-3a59-11eb-808f-a18244066f59.PNG)
![IMG_0034](https://user-images.githubusercontent.com/7535475/101681006-6a02c980-3a59-11eb-822c-f15fec508a45.PNG)
![IMG_0029](https://user-images.githubusercontent.com/7535475/101681008-6a9b6000-3a59-11eb-8c65-479f9bb9ee7f.PNG)

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging & dev app version 1.4.0(182)
