### ISSUE TITLE
Available to spend is missing.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2246]
-"Available to spend" is missing on Account screen.

**Comment by CypherPoet** [comment]
I think it's worth considering whether or not we need this. It would be displayed directly under the "card" header, which already shows the available balance on its bottom line. (@antuz123 @Arpanjainson @AliMeer)

**Comment by antuz123** [comment]
The amount you see on the card is the total balance and not available to spend balance. These are two different numbers. @CypherPoet 

Available to spend does not include unconfirmed transactions unless it is your own change.

**Comment by CypherPoet** [comment]
@antuz123 Ah, that makes sense. Thanks for the clarification 👍

**Comment by cakesoft-swati** [comment]
-Verified this on staging app version 1.4.0(182)
