### ISSUE TITLE
AC1.1: Add an Account -- New Account Selection Screen

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2248]
## Top-Level Options given:

-  Import a Wallet. 

## New Account options given:

- Joint Account (Account with Friends and Family). 

## Services options given: 
- Swan Bitcoin (stack sats with Swan), 
- FastBitcoins.com (Use FastBitcoin Vouchers), 
- Whirlpool Account (powered by Samurai)

 
## Import a Wallet options: 
- Watch Only (View a non-Hexa wallet as an account)
-  Full Import (Fully import and manage a non-Hexa wallet) 

(🗒️  Each account setup will have a very different flow)

**Comment by antuz123** [comment]
What is needed here @AliMeer ?

**Comment by AliMeer** [comment]
I think we can close this issue.
Add new account flow for each type of account can be created when adding the new type of account
