### ISSUE TITLE
Textual changes of Donation account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2249]
-The new DA creation does not seem to have these labels.
![File (16)](https://user-images.githubusercontent.com/62699947/101760859-717dad80-3b01-11eb-874d-c7a4e94aa57b.jpg)

-Donation account should work as it is, not any pre filled details if not already there.
![Screenshot_20201210-161129_hexa dev](https://user-images.githubusercontent.com/62699947/101761743-8870cf80-3b02-11eb-994b-38b863c904cd.jpg)

**Comment by AliMeer** [comment]
@cakesoft-swati this is as per the new UX and as you can see from this ticket, this setup page has to be changed to the UX: https://github.com/bithyve/hexa/issues/2223

**Comment by antuz123** [comment]
compare the creation and settings screen on the live app with the dev app. The behaviour should be like the live app.
