### ISSUE TITLE
The order of accounts.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2250]
-This is the order of accounts, so when new Donation Account is added it should be in position 2 not 3.
![thisis](https://user-images.githubusercontent.com/62699947/101761945-c837b700-3b02-11eb-8aad-b36dd911eb40.jpg)

**Comment by CypherPoet** [comment]
Given that this is a horizontally-scrolling list, shouldn't the ordering flow column-wise?

**Comment by antuz123** [comment]
(1,3)
(2,4) 
(5,7)
(6,8) 
(9,11)

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.1(193)
