### ISSUE TITLE
Pending and Confirmed status on account screen

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2252]
Need pending and confirmed.
![tempFileForShare_20201210-162537](https://user-images.githubusercontent.com/62699947/101763178-709a4b00-3b04-11eb-885f-f86c32836ee5.jpg)

**Comment by CypherPoet** [comment]
I'm still a bit unclear as to what this is asking for. Does every list item have a badge indicating whether or not it's pending or confirmed? I wasn't seeing this in the previous UI.
