### ISSUE TITLE
Currency switcher crashes the app

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2267]
Click the currency switch icon during send from test account crashes the app
Ios 181 upgraded from 130
Currency switcher on home screen crashes the app too

**Comment by AliMeer** [comment]
This is an upgrade issue, the migration script needs to account for the change between 1.3.0 and 1.4.0

**Comment by Arpanjainson** [comment]
Crashed on 183 upgraded from 182 dev
works on 183 dev FI

**Comment by AliMeer** [comment]
Upgrade from 1.3.0 to 1.4.0.
Currency switcher is crashing the app.

**Comment by cakesoft-swati** [comment]
-Verified this on staging app version 1.4.0(188)
