### ISSUE TITLE
Pending and Confirmed tabs on account details screen

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#2269]
Add tabs that allow users to filter the list between Pending and Confirmed transactions.

**Comment by antuz123** [comment]
See the new design. They have used an hourglass instead of a tab.

**Comment by CypherPoet** [comment]
@antuz123 @Arpanjainson I'm seeing two potential tasks here:

- Icons on the list items
- Tabs above the list and corresponding filtering functionality  

I think we need to clarify which of these we want to implement, and then make individual stories for each.

**Comment by antuz123** [comment]
Yes, this does not seem to be clear. @Arpanjainson

**Comment by Arpanjainson** [comment]
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/f4153956-42c4-496a-9a21-749aa6cda44d

**Comment by Arpanjainson** [comment]
@antuz123  do we really need a filter for pending transactions - the pending ones will be latest and will be on top anyways. Hourglass as per this spec looks ok to me
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/f4153956-42c4-496a-9a21-749aa6cda44d

**Comment by antuz123** [comment]
We are using an hourglass and not tabs. this issue is not needed.
