### ISSUE TITLE
Support Bech 32

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2278]
Capital and small.

**Comment by AliMeer** [comment]
This was done and released some time ago.

**Comment by antuz123** [comment]
Can't close this as it needs to be tested. @AliMeer 

Unless there is a another issue

**Comment by AliMeer** [comment]
Marking it fixed, this is done and needs to be retested.

**Comment by cakesoft-swati** [comment]
-I already verified this issue.
