### ISSUE TITLE
"Donation Web View" button missing on donation account

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2280]
Test Device: iPhone. 12 Pro Max and iPhone 11 Sim
App Version: v1.4.0 # 179, 181 and 182

The donation account does not have the donation web view button

![IMG_0052](https://user-images.githubusercontent.com/7535475/101992046-6b760100-3ca8-11eb-9414-3bbbcadbce19.PNG)

**Comment by cakesoft-nikhita** [comment]
@Parsh I handled button related changes and model related changes but on Donation account's setting page some objects are missing. Please check I am assigning this bug to you.

**Comment by antuz123** [comment]
Need the correct UX for this
