### ISSUE TITLE
Send and Receive buttons on account screen appear to be cut off

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2281]
Send and Receive buttons appear to be overlayed and hidden when pulling down to refresh

![IMG_0055](https://user-images.githubusercontent.com/7535475/101992218-7aa97e80-3ca9-11eb-9f70-7764134cf6e3.PNG)

**Comment by cakesoft-swati** [comment]
-Send and Receive buttons on account screen still appear to be cut off when pulling down to refresh.
-Only visible on small screen devices.I tested it on iphone 7 v1.4.0(184)

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.1(192)
