### ISSUE TITLE
Some parts of friends and family are crashing.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2285]
One of the user is facing crash issue on FI app.
-He is using FI v1.3.2 on iphone 8.
-His app is crashing on "I am the keeper of"contact of F&F.
![Image from iOS (4)](https://user-images.githubusercontent.com/62699947/102045450-20223680-3dff-11eb-9391-5f03d7c7bb66.png)

**Comment by Arpanjainson** [comment]
@cakesoft-swati  can you please test and assign this to Parsh if the issue is still there

**Comment by CypherPoet** [comment]
This seems to be what's also being described in #2541

**Comment by cakesoft-swati** [comment]
--Observed on UP Live app version 1.4.1(195)
-The screen is getting stuck for a while and we can not refresh it and cannot click anywhere(I have to kill the app).
-I have a contact in "I am the Keeper of", the app is crashing by clicking on it.

**Comment by cakesoft-swati** [comment]
-It is happening only on production app.
-Unable to recreate it on dev app.

**Comment by Arpanjainson** [comment]
Lets test it on latest production after release. We will leave this open for now.
