### ISSUE TITLE
Fallback for Fee Rates

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2287]
As fee-rates are an external dependency and are prone to non-availability, we will need to have a fallback mechanism(beyond the fee/ex-rates patch). In such a scenario where fee rates aren't available in the app, we'll disable the send max option and would remove the priorities from the confirmation screen. The user would be able to enter the fee via the Custom fee option and continue the send.

**Comment by Arpanjainson** [comment]
@cakesoft-swati check with @Parsh to test this.

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.1(193)
