### ISSUE TITLE
Exchange rates fallback

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2288]
As exchange-rates are an external dependency and are prone to non-availability, we will need to have a fallback mechanism(beyond the fee/ex-rates patch). In such a scenario where exchange rates aren't available in the app, we'll disable the currency switch button.

**Comment by Arpanjainson** [comment]
@AliMeer  @Parsh  we will need to test it along with you.
FI - disable the exchange rate api - currency switcher should not work.
FI - currency switcher will work - disable the exchange rate API - currency switcher will still work as app has the data.

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.1(193)
