### ISSUE TITLE
App is crashing on Restored+upgraded app.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2291]
-I installed 1.3.2(175) dev app after that I restored it.Restore worked on 1.3.2 to 1.3.2 n then I upgraded it to 1.4.0 but app started crashing on upgrade.

**Comment by Parsh** [comment]
@cakesoft-swati  This issue is almost a month old, can you confirm that it's still happening?

**Comment by cakesoft-swati** [comment]
-Unable to recreate this issue,tested on Dev app v1.4.2(202)
