### ISSUE TITLE
Manage Backup 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2292]
The manage backup screen should not have a grey cover. 
The actions on the screen should be accessible.

**Comment by cakesoft-swati** [comment]
-The grey cover of the Manage Backup screen( while loading ) is still visible.
-Tested on staging app version 1.4.0(184)

**Comment by CypherPoet** [comment]
I haven't been able to reproduce this locally. Is there a recording or screenshot of this happening?

**Comment by AliMeer** [comment]
@cakesoft-swati are still able to see the grey screen? I am not.

**Comment by cakesoft-swati** [comment]
[Screen_Recording_20201221-105216.zip](https://github.com/bithyve/hexa/files/5722471/Screen_Recording_20201221-105216.zip)
This is the recordig frm Hexa live app version 1.4.0(188)

**Comment by cakesoft-swati** [comment]
-Uable to reproduce this on live app v1.5.1(261)
