### ISSUE TITLE
Connect your own node (step 1) 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2293]
Arpan  12:24 PM
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/e5b9807e-706d-43c2-b05e-6d519021d65f

hexa wallet ui
Link Type
Prototype
Date Modified
Dec 11, 2020
Added by Adobe Creative Cloud (24 kB)
https://public-v2links.adobecc.com/181f3fd2-7aca-4284-61c7-3417e1fe6d8a/component?params=component_id%3Acecc0da5-00f3-476e-88a1-96a3940aa417&params=version%3A5&token=1608015249_da39a3ee_f5e1409475754a0831dc128cf3ec71d3c4190500&api_key=XDCEClient1

Anant  12:26 PM
For the text below Node Settings

‘Configure your node settings’
12:28
When you go inside, there will be two radio buttons.

:radio_button:Connect to BitHyve node
:black_circle_for_record:Connect to my node
12:28
With the first one selected.
12:29
If the user selects the second option, it gives two fields:

IP address: <no info>
Socket: pre filled with the default socket option in Botcoin Core
12:31
On clicking apply, it checks and gives a toast either:
‘Successfully connected to your node’ and moves to the HS

Or

‘Not able to connect to the node, pls check the details and try again’ and stay on the same screen

**Comment by Parsh** [comment]
Awaiting #2326
