### ISSUE TITLE
Do not show Hexa icon for F&F on Account Tiles 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2312]
In the current release it shows a Hexa icon for each F&F on an account. We do not need this.

**Comment by CypherPoet** [comment]
For future reference: good [discussion here](https://bithyve-workspace.slack.com/archives/CEBLWDEKH/p1608140278078200?thread_ts=1608137067.064600&cid=CEBLWDEKH) about how we decided to handle this.

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app version 1.4.0(184)
