### ISSUE TITLE
Own Node Wrapper Setup Guide

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2315]
Document a user guide to help users with:

1. Prerequisites for users to enable own node connectivity
2. Detailed step by step instructions to setup bithyve wrapper on its own

**Comment by Arpanjainson** [comment]
@AliMeer  can you please send over the link or the guide?

**Comment by Arpanjainson** [comment]
@AliMeer  please share the guide link. We need to add the same to FAQs.

**Comment by AliMeer** [comment]
The guide will be here: https://github.com/bithyve/bithyve-wrapper

**Comment by Arpanjainson** [comment]
Added following to FAQs.
@antuz123 @AliMeer  please review and close the issue

**How do I setup own node & connect Hexa Wallet to it?**

Refer the link https://github.com/bithyve/bithyve-wrapper for details on how to install and run your own copy of the wrapper. You may need to apply additional settings as required by the laws of country you are in e.g. restricting transactions to sanctioned entities/countries.

Please refer to the rules and regulations in your country related to setting up a node before installing and running the node.
