### ISSUE TITLE
Currency is showing wrong on sending from test account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2324]
- as the app was crashing while changing currency, I continued with Dollars in the test account. It showed me there were 1.84 USD (equivalent to 10K sats) before sending. After sending it showed me that 2578 USD was sent.
![IMG-20201216-WA0001](https://user-images.githubusercontent.com/62699947/102449202-c5384b80-4059-11eb-887a-e85d48393988.jpg)

**Comment by CypherPoet** [comment]
This is something that will should be covered as part of the changes taking place for #2039. It might be best to focus on those fixes there, as right now, the logic for formatting balances and units across these screens is highly dispersed along a number of places in each Send screen.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(245)
