### ISSUE TITLE
Incorrect available to spend.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2331]
Incorrect available to spend as total seems to be lower. UP-RE app. The order of transactions should be reversed and I should see the latest first
![icorrect avl](https://user-images.githubusercontent.com/62699947/102497199-5c26f700-409e-11eb-9f5b-9679ae7ecb9c.jpg)

**Comment by cakesoft-swati** [comment]
-Unable to reproduce it due to low balance and heigh fees.

**Comment by antuz123** [comment]
This happens once and then on the next login, it gets correct.

**Comment by antuz123** [comment]
@cakesoft-swati - need to recreate it

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.1(192)
-Unable to recreate it.

**Comment by cakesoft-swati** [comment]
-Able to see the Incorrect "available to send" .
-Tested on staging app v1.4.1(194)

**Comment by Parsh** [comment]
Fixed:
- Order of txs(latest first), however, the unconfirmed ones would not be in perfect order as they don't seem to have a timestamp
- Available to spend: was out of sync at the level of the UI

**Comment by cakesoft-swati** [comment]
-Verified this issue on Staging app V1.4.1(195)
-Now it is showing correct available to spend .

**Comment by Arpanjainson** [comment]
unable to recreate
