### ISSUE TITLE
Account sync on pulldown 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2333]
From Account Settings> Rescan the Account

The user can go for this option where all xPubs of all sub-accounts in the account are scanned from the beginning till you find the gap limit. 

A message is shown to the user that it may take a few mins and they should not close the app

Loaders like the ones during login appear

**Comment by antuz123** [comment]
Gap limit (Normal refresh): 5
Gap limit (Hard refresh): 10

**Comment by antuz123** [comment]
@Parsh - is this fixed?

**Comment by Parsh** [comment]
Yes, only the UI portion is left.

**Comment by Arpanjainson** [comment]
Hard refresh was tested in test account.. Will move this issue to 1.4.5 for the UI issue

**Comment by antuz123** [comment]
The term is Manual Sync. From the settings it is Full Wallet Sync.

**Comment by AliMeer** [comment]
There are a number of UX changes as well these can be done together with this change.

**Comment by antuz123** [comment]
@AliMeer - not clear what this is, lets do it in 1.8.0

**Comment by antuz123** [comment]
Account sync (full xPub sync) on pull down, take out the option from setting.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.0(320)
- Full sync option is removed from settings.
