### ISSUE TITLE
Tweak Add New Screen to Further match designs

### ISSUE THREAD

**Issue by CypherPoet** [bithyve/hexa#2334]
See discussion [here](https://bithyve-workspace.slack.com/archives/C01AK731NUS/p1608210263000100)

**Comment by Arpanjainson** [comment]
Posting the discussion here


1. The top does not have a line and has a subtext in the UX
2. Let’s use the row headings to what they are in the UX
3. The edges for each row is truncated and does not touch the screen edge
4. ‘Coming Soom’ should be next to the account image like ‘New’ but in two lines. ‘Coming Soon’ on the top does not look correct

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app 1.4.2(205)
