### ISSUE TITLE
Exchange rates not available modal

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2342]
We need to show a modal(like No internet modal) when the exchange rates aren't available and user taps on currency switcher.

**Comment by AliMeer** [comment]
@antuz123 @Arpanjainson is this message fine?

![Screenshot 2020-12-20 at 14 37 36](https://user-images.githubusercontent.com/7535475/102716292-e3f54700-42d2-11eb-9822-b8395136715f.png)

**Comment by antuz123** [comment]
Message is fine. 

This only happens when someone touches a disabled currency converter switch (on any screen)

**Comment by cakesoft-swati** [comment]
-Exchange rates not availablemodal is not comming up.
-Tested this on Dev app v1.4.1(193)

**Comment by Arpanjainson** [comment]
Swati to test along with ali

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev appv1.4.1(194)
