### ISSUE TITLE
After adding the donation account, a blank white screen is coming up.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2343]
-It is upgraded app from 1.3.0 to 1.4.0
-I restored my upgraded app i.e 1.3.2(175) to 1.4.0(188) n it has the same issue.
-Facing the same issue on staging Restored 1.4.0 app.
[RPReplay_Final1608279879.zip](https://github.com/bithyve/hexa/files/5715891/RPReplay_Final1608279879.zip)

**Comment by CypherPoet** [comment]
I haven't been able to reproduce this locally in development or on a fresh install of 188. Are we sure this isn't an issue related to upgrading? (@antuz123 @Arpanjainson @Parsh @AliMeer)

**Comment by Parsh** [comment]
Definitely has to do with the upgrade. However, this seems like an issue at the UI layer(or in corresponding reducer) as sagas and the layers beneath them can't directly cause the screen to go blank. Somewhat similar to what we had with currency switcher's preferBitcoin err, I guess.

**Comment by CypherPoet** [comment]
@cakesoft-swati Can we re-check this against the latest 1.4.1 release?

**Comment by cakesoft-swati** [comment]
-I just upgraded Live app from 1.4.0 to 1.4.1 n created one donation account successfully.
-so unable to reproduce this issue on upgraded app.
-I also checked it on staging and dev app v1.4.1(Upgraded drom 1.4.0 to 1.4.1)but unable to reproduce this issue.
