### ISSUE TITLE
Not able to refresh the Manage Backup screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2344]
-can't click on the shares.Also not able to refresh the screen.
-Tested on FI 132 test live upgraded to 140 Test live.
-Tested on FI 130 test live upgraded to 1.4.0 Test live.
-It seems like the manag backup screen got stuck.
![File (18)](https://user-images.githubusercontent.com/62699947/102619790-036d6200-4163-11eb-9cb6-3d424a6d7e7e.jpg)

**Comment by Arpanjainson** [comment]
This works on Ali's device. @cakesoft-swati  check today on the android live. moving to 1.4.1.

**Comment by cakesoft-swati** [comment]
-Verified this issue onlive app v1.4.1 and latest dev app version 1.4.2(200).
-Now I can able to refresh the Manage Backup screen.
