### ISSUE TITLE
Move passcode keypad higher so that it is away from the bottom edge

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2351]
Move passcode keypad higher so that it is away from the bottom edge of the phone.

![photo_2020-12-21_11-24-09](https://user-images.githubusercontent.com/7535475/102772314-2d9b6b80-437f-11eb-993c-1c0b5676e544.jpg)

**Comment by cakesoft-swati** [comment]
-Verified this on dev app v1.4.0(190)
