### ISSUE TITLE
Order of transactions.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2360]
-order of transactions is not correct. Looks like the first 3 transactions are being displayed on accounts screen whereas there are many more newer transactions available. This is an iPhone XS with  Live v1.4.0 which has been updated for all releases since 1.1.0
- Latest transactions not displayed on account screen
- Transactions not in correct order
- From/To names showing up as "Checking Account" for all transactions instead of contact name or FastBitcoins.
[RPReplay_Final1608582816.zip](https://github.com/bithyve/hexa/files/5727990/RPReplay_Final1608582816.zip)

**Comment by Parsh** [comment]
The ordering of confirmed tx is fixed now. For unconfirmed tx's, due to absence of blocktime(or any other timestamp), it's relatively complex to order them.

**Comment by cakesoft-swati** [comment]
-verified this issue on Dev app v1.4.1(192)
