### ISSUE TITLE
Textual changes on Send Know More screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2361]
-Not ecosystem but the network.
- Also no connection between the first and the second para. The first page it too bland.
![tempFileForShare_20201222-111638](https://user-images.githubusercontent.com/62699947/102853924-5850f700-4447-11eb-83aa-48a587c04712.jpg)

**Comment by AliMeer** [comment]
@antuz123 can we clarify how to address the issue for "The first page it too bland."

**Comment by AliMeer** [comment]
This will be done after new text is provided

**Comment by Arpanjainson** [comment]
This will be handled once latest Know more text will be available.

**Comment by AliMeer** [comment]
@cakesoft-nikhita please check if we are using new lines in the text.

**Comment by Arpanjainson** [comment]
Latest know more screen text is attached.

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app version 1.4.2(202)
