### ISSUE TITLE
Version history screen under wallet settings

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2371]

**Comment by Arpanjainson** [comment]
Version History
https://xd.adobe.com/view/00485057-d5b7-4b2b-641b-20216b3a38d5-7679/screen/576f0615-1614-424e-807c-53f56319f46c/
https://xd.adobe.com/view/00485057-d5b7-4b2b-641b-20216b3a38d5-7679/screen/a49b133d-7bab-4f34-aa12-b7021443915d/

**Comment by Arpanjainson** [comment]
@AliMeer  @CypherPoet  we can possible do this in 1.4.1 now @antuz123

**Comment by antuz123** [comment]
Version - Installed/ Upgraded/ Restored - Timestamp

**Comment by CypherPoet** [comment]
After our discussion earlier today, it looks like we still need to determine how the app will find/fetch/store this data in the first place. Moving to 1.4.2 for now.

**Comment by CypherPoet** [comment]
After our discussion earlier today, it looks like we still need to determine how the app will find/fetch/store this data in the first place. Moving to 1.4.2 for now. 

@Parsh Is there anything that you envision needing to be done on the backend to support this?

**Comment by antuz123** [comment]
This is not fixed unless all items are fixed. UI fixing does not close it. @cakesoft-nikhita - you need to pick this up E2E as per my understanding, not just the UI.

**Comment by Arpanjainson** [comment]
Version history crashed on ios when upgraded from 143-217 to 144-210 staging

**Comment by Arpanjainson** [comment]
seems like app is not able to read the saved history..
in case the v144 210 app was installed afresh the version history screen works

**Comment by AliMeer** [comment]
fixed, should work now. Please keep an eye on this after restore as well.

**Comment by cakesoft-swati** [comment]
-Version history crashed on ios when upgraded from 1.4.2(216)to 1.4.4(222)

**Comment by AliMeer** [comment]
We need to test this on build 224

**Comment by cakesoft-swati** [comment]
-Not working after restore.
-After restoring, the version history page  appears blank.
![Screenshot_20210212-141201_hexa dev](https://user-images.githubusercontent.com/62699947/107746776-667f0d80-6d3c-11eb-84c3-7e50b8f3cf75.jpg)

**Comment by cakesoft-swati** [comment]
-verified this issue on staging app v1.4.5(230)
