### ISSUE TITLE
UI issue while searching the contacts.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2386]
When we go to search contacts(Manage Backup>F&F>Associate conatct>Search), then that search bar is going up so much that we cannot see it.
![Screenshot_20201229-122448_hexa stage](https://user-images.githubusercontent.com/62699947/103264712-8dbe8d00-49d1-11eb-81eb-c97e717cecc7.jpg)

**Comment by AliMeer** [comment]
@cakesoft-swati Is this in a particular devic only? Can you please try a few different screen sizes in browser stack please.

**Comment by cakesoft-swati** [comment]
-Able to see this issue on SAMSUNG GALAXY A50.
-I'll also check it on few different sizes.

**Comment by CypherPoet** [comment]
I haven't been able to reproduce this yet on iOS. Mocking up a massive list of data, the "Search" header seems to stay fixed at the top of the list and remain in view.

![image](https://user-images.githubusercontent.com/46851636/103691276-86602c00-4f5b-11eb-9542-11cb2c7f6d02.png)


@antuz123 @Arpanjainson @AliMeer

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app version 1.4.2(202)
