### ISSUE TITLE
UI issue on "Node settings" screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2387]
-When we go to enter the node address in the node settings, the "note" is coming above the port textbox.
![Screenshot_20201229-124153_hexa stage](https://user-images.githubusercontent.com/62699947/103265373-6ff22780-49d3-11eb-8426-64727cf8a8f7.jpg)
[It is happening on SAMSUNG Galaxy A50,A70.I think this issue is coming only on big screen devices. ]

**Comment by cakesoft-swati** [comment]
-Still able to see this issue on staging app V1.4.1(191)

**Comment by CypherPoet** [comment]
Noting that this is the same issue we're dealing with in #2386.

Also, https://github.com/facebook/react-native/issues/6785 might be relevant.

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.1(193).
