### ISSUE TITLE
UI issue while entering the OTP to accept the Keeper request.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2388]
![Screenshot_20201229-130207_hexa stage](https://user-images.githubusercontent.com/62699947/103266917-9cf40980-49d6-11eb-88a8-13f419603a17.jpg)
-When we go to enter the OTP, the entire screen is going up that the OTP textbox itself is not visible.
[Tested on SAMSUNG Galaxy A50 v1.4.0(190)]

**Comment by AliMeer** [comment]
@cakesoft-swati you have mentioned the test device, does this mean this issue for a particular device?

**Comment by cakesoft-swati** [comment]
I have also tested this issue on iphone 7 but it didn't happen on that.I think its happening on big screen android devices.Also it does not happen every time.
-I also tested it on Samsung A70

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app v1.4.1(191)
