### ISSUE TITLE
Indicate selection of Account Management Row Items when they're being dragged to re-order.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2392]
-Need UX
![tempFileForShare_20201230-174511](https://user-images.githubusercontent.com/62699947/103350765-07847280-4ac7-11eb-82fe-484001da7c45.jpg)

-Need proper functionality
![tempFileForShare_20201230-174551](https://user-images.githubusercontent.com/62699947/103350807-326ec680-4ac7-11eb-8555-665e7e9d361b.jpg)

**Comment by AliMeer** [comment]
@antuz123 @cakesoft-swati Not sure what exactly needs to be corrected here.

**Comment by antuz123** [comment]
Finding Sources not needed

**Comment by antuz123** [comment]
Make sure the user knows that a particular row is selected

**Comment by cakesoft-swati** [comment]
-Verified this issue on Staging app v1.4.1(194)
