### ISSUE TITLE
Account Sync - AC6

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2393]
Refer to the card - https://trello.com/c/99MbiQNv/155-ac6-account-sync-states

Following UI changes need to be implemented on the home screen.

Show a syncing icon (circle/refresh icon rotating) on the account card when the account is syncing i.e. balance is refreshing.  https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/bc29c80e-fe0b-4a74-b72c-b4fdb3adabc1

In case the user clicks on the account while syncing following screen is presented.
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/6dfc8495-3759-49e2-a4c7-fe0cb86f652b

Account which has synced does not show the circle (refresh) icon.

Accounts which are yet to be synced have the circle (refresh) icon.

**Comment by Arpanjainson** [comment]
@antuz123 FYI

**Comment by antuz123** [comment]
@Arpanjainson - what is the state for not synced. 
the icon is for ‘syncing’ status. Not for stale/ not-sync state. Check the card. We need an icon for not synced state which is not processing.

**Comment by Arpanjainson** [comment]
The decision is to show a moving circle when account is syncing.
Accounts which are not synced will have a static circle (refresh icon)
Accounts which were synced will not show any icon.

**Comment by Arpanjainson** [comment]
Refer to this https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/bc29c80e-fe0b-4a74-b72c-b4fdb3adabc1

**Comment by Arpanjainson** [comment]
@AliMeer  we will need to decide if we need to move it to the next release and who handles this.

**Comment by antuz123** [comment]
for 142, we can have a static icon (not rotating) and this will go away only when the account is refreshed, which happens only when the user goes in. 

If the account has been refreshed IN THAT SESSION, then the icon away.

**Comment by antuz123** [comment]
Split out the one where we call for balances on the HS for 143 @AliMeer. Ideally, we should do it after the Soft Refresh.

**Comment by AliMeer** [comment]
TO TEST:
A static sync icon (not rotating) will be shown on each account tile on the home screen.
This will go away only when the account is refreshed, which happens only when the user goes into the account.
If the account has been refreshed IN THAT LOGIN SESSION, then the icon will not be shown.

**Comment by Arpanjainson** [comment]
Need to test this on lower end android phones as well.

**Comment by Arpanjainson** [comment]
@AliMeer  - have we created another issue for 143 to implement the pending functionalities as per the card
