### ISSUE TITLE
Restored app not showing the changed names for default accounts

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2394]
Default Checking, Savings, and Test Account name change is not visible when the app is restored. 
If default account names are shown as default names after the app is restored. If a default account name was changed the changed name is not visible in the restored app.
non-default account name and description changes are visible in the restored app, this only applies to default Checking, Savings, and Test Account name and description.

**Comment by AliMeer** [comment]
@cakesoft-swati  Let's not change this now as its a minor residual issue. I don't want to change the core functionalities at this late stage.

FYI @antuz123 @Arpanjainson

**Comment by antuz123** [comment]
@cakesoft-swati @Arpanjainson

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.4.2(202)
-Now the restored app is showing the changed names for default accounts.
