### ISSUE TITLE
Notifications to be retested after firebase upgrade 

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2395]
After firebase upgrade to v6 following notifications should be retested to ensure they are being triggered correctly 

> F&F notifications for request accepted 
> Trusted Contact request accepted 
> Trusted contact transaction received 
> FBTC transaction notification 
> Timed notifications
> Keeper request accepted
> Broadcast  notifications (currently for only release)

**Comment by Arpanjainson** [comment]
Only FBTC notification test is remaining. @AliMeer  to help on pre-live prod.

**Comment by Arpanjainson** [comment]
@AliMeer  please test the FBTC notification and then we are good to close this

**Comment by AliMeer** [comment]
FBTC notification were tested in the previous releases.
