### ISSUE TITLE
The account names are too close to the icons on Android (Pixel 2)

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2398]
-The test is too close to the icons on Android (Pixel 2)
![IMG_1133](https://user-images.githubusercontent.com/62699947/103503939-ea132800-4e7b-11eb-91e2-6bbc6660e258.jpg)

**Comment by CypherPoet** [comment]
Considering this to be a duplicate of https://github.com/bithyve/hexa/issues/2402
