### ISSUE TITLE
Need a Receive Option.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2399]
-Need a Receive Option on this screen which shows Checking Account QR.
![File (21)](https://user-images.githubusercontent.com/62699947/103504097-6c9be780-4e7c-11eb-8828-c2f0cd8f59cd.jpg)

**Comment by CypherPoet** [comment]
@antuz123 @Arpanjainson Are there any designs around what's being asked for here? This looks to be the QR scanning screen that we show from Home, is that correct?

**Comment by antuz123** [comment]
Need UX here too @Arpanjainson

**Comment by Arpanjainson** [comment]
@antuz123  what exactly is required here? Do we need a Checking account QR by default on the "QR" option from home screen like a quick receive?

**Comment by antuz123** [comment]
Yes, an option to "Receive" bitcoins, that will take you to the receive screen of the Checking Account

**Comment by CypherPoet** [comment]
@antuz123 Given that users can have multiple checking accounts, how would we determine which one to link to here?

**Comment by antuz123** [comment]
The default Checking Account. We would also give them an option of changing the account from this screen, but that is for the future I think.

**Comment by CypherPoet** [comment]
@antuz123 @Arpanjainson @AliMeer I think this is worth moving to 1.4.2 until we have a design in place.

**Comment by Arpanjainson** [comment]
Proto link - https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/4083bda1-19e0-40b5-bea4-b9b8f048f893

The button text will change..

**Comment by Arpanjainson** [comment]
@CypherPoet  please acknowledge receipt of the ux

**Comment by AliMeer** [comment]
Closing this, created a new issue with end to end journey https://github.com/bithyve/hexa/issues/2829
