### ISSUE TITLE
Caps or special characters should not be allowed

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2401]
-This screen should not allow caps or spaces. 
-A note is needed to say the same. Note: special characters or capital letters are not allowed for the Security Answer
![File (23)](https://user-images.githubusercontent.com/62699947/103504299-0368a400-4e7d-11eb-8a44-90bfb2df5d25.jpg)

**Comment by antuz123** [comment]
also no special characters allowed

**Comment by antuz123** [comment]
Only lower a-z and 0-9 allowed

**Comment by AliMeer** [comment]
@Arpanjainson @cakesoft-swati Would it be possible to find out which versions have this issue. At the moment the assumption is that it’s only in 1.4.0 and not in 1.3.2, it would be very helpful if we can find out.

**Comment by CypherPoet** [comment]
I haven't been able to see where this logic _was_ implemented. Perhaps it's always been an issue that we're just now catching?

**Comment by AliMeer** [comment]
> @Arpanjainson @cakesoft-swati Would it be possible to find out which versions have this issue. At the moment the assumption is that it’s only in 1.4.0 and not in 1.3.2, it would be very helpful if we can find out.

**Comment by AliMeer** [comment]
> @Arpanjainson @cakesoft-swati Would it be possible to find out which versions have this issue. At the moment the assumption is that it’s only in 1.4.0 and not in 1.3.2, it would be very helpful if we can find out.

Did we check this?

**Comment by cakesoft-swati** [comment]
-This issue is also in 1.3.2
