### ISSUE TITLE
Personal node data backup & restoration

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2404]
Need to backup the state data(earlier async) in WI for personal node and restore post wallet recovery

**Comment by cakesoft-swati** [comment]
-Tested this on Dev app v1.4.1(193)
-Added own node in a FI app.Then did a recovery.But did not have own node after recovery.

**Comment by AliMeer** [comment]
@antuz123 @Arpanjainson It’s best to move this to next release, so that we don’t make changes to backup and recovery at the moment. This is not a critical requirement for recovery.

**Comment by cakesoft-swati** [comment]
-Verified this on dev app v1.4.2(202)
