### ISSUE TITLE
New screens for F&F Sharing changes

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2415]
All these screens should show the QR as the primary option and link as a secondary option. This applies to
1. F&F request screen
2. Receive screen
3. Keeper request screen
4. Keeper reshare screen
5. Change Contact screen
6. @cakesoft-swati - what other screens?

**Comment by Arpanjainson** [comment]
Discussed with Sumaiah

**Comment by antuz123** [comment]
More @Arpanjainson note: 
1. When sharing the link, the OS sharing modal should open, and not our modal that we have designed, the benefit is that it is in-app and once you have done that, the user is back in the app. Copying the link to another app leaves the user outside of the app leading to some confusion as there is no message as to what to do. 
2. On sharing the link, currently we show a very good OTP screen (when the skip is done), we need a similar screen telling the requested that the contact has to enter his phone number to confirm the identity and which phone number or email ID it is. The OTP screen does that very well.

**Comment by AliMeer** [comment]
Guidance from @Arpanjainson: When sharing, display the OS provided modal for sharing and don't show the current modal that is being displayed.

**Comment by Arpanjainson** [comment]
Proto link - https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/cb495627-64b9-46ce-9e33-f73da4b50b14

**Comment by cakesoft-nikhita** [comment]
As per comments on bug #2801Latest screens: https://xd.adobe.com/view/3df97271-f272-4dae-975d-95d4785f1b30-68aa/

Latest screens
https://xd.adobe.com/view/7636e956-af9b-4300-bc63-4c3eab0d4f71-2365/screen/538324fe-2358-4d10-939f-86c872b151a3/
Request Share
Request Share – Share
Request Share – OTP
Request Share – Copied Successfully Toast
Request Share – Message shared with trusted contact – Email
Request Share – Message shared with trusted contact – Phone
Accounts – Receive
Accounts – Receive – Enter Amount

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (286)
