### ISSUE TITLE
Waiting sign on share and QR buttons

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2428]
![image](https://user-images.githubusercontent.com/8697909/103733221-3fcc0980-500f-11eb-9dae-285fe472adcf.png)

A new screen is being mocked up which will replace the Share and QR buttons.

**Comment by Arpanjainson** [comment]
May be it was taking a lot of time to process and generate the link..

**Comment by Arpanjainson** [comment]
@cakesoft-swati  please retest

**Comment by cakesoft-swati** [comment]
-Unable to recreate this issue,Verified this on dev app v1.4.2(201)
