### ISSUE TITLE
An error occurred while trying to send from a savings account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2429]
![File (24)](https://user-images.githubusercontent.com/62699947/103734287-aa7e4480-5011-11eb-9886-0b5c443a0116.jpg)
1.Getting this error while trying to pay minor or transfer to checking account.
2.The minor was specific 845.
3.And the checking was max.

**Comment by Arpanjainson** [comment]
can not reproduce.
