### ISSUE TITLE
App is crashing by clicking on send button of any contact in FnF list.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2430]
-Tested on Dev app version 1.4.1(192).
-Also on live app v 1.4.0(188)

**Comment by Parsh** [comment]
Here's the PR which intented to resolve it: https://github.com/bithyve/hexa/pull/2286/

**Comment by antuz123** [comment]
@Parsh - is this resolved?

**Comment by cakesoft-swati** [comment]
-Verified this issue on Staging app v1.4.1(195).
-Now the App is not crashing by clicking on send button of any contact in FnF list.
