### ISSUE TITLE
Security question answer messaging

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2439]
We aren't backing up the security question right - So maybe that sentence needs to be changed
 Did a fresh install and set up the security question and reached the home screen. When I came to this section it says that I already confirmed the security question which I had not.
 
 
![image](https://user-images.githubusercontent.com/8697909/103870164-59de1880-50f1-11eb-9769-d84f43eb35c7.png)
Message should read - "Last confirmed". Also it is a bug that it is showing never. It should be aligned to the date

**Comment by antuz123** [comment]
@Arpanjainson how is this B-H-R?

**Comment by cakesoft-swati** [comment]
-Verified thi on dev app v1.4.2(202)
