### ISSUE TITLE
Allow access to file and storage

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2440]
On android -

![image](https://user-images.githubusercontent.com/8697909/103870385-a4f82b80-50f1-11eb-8f8a-3a1428b81a09.png)

Currently the modal can be closed - it should not be allowed to close and rather a continue and continue or cancel/deny button should be present.

When denied, the pdf sharing will fail - a message to allow access should be displayed, which should present the access modal again.

**Comment by AliMeer** [comment]
@Arpanjainson is this a new requirement? We had talked about this when implementing the message. We cant implement it that way, the message can be displayed first the way are doing now and then the phone will prompt the user for permission. We cant have the accept and deny on the message the OS doesn't support that.
