### ISSUE TITLE
Initial loading issue

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2441]
-Seems like the gif loading is taking longer and we have a fixed time to show it.
-Also Hexa symbol is not visible.
[Screen_Recording_20210107-114716_hexa dev.zip](https://github.com/bithyve/hexa/files/5780611/Screen_Recording_20210107-114716_hexa.dev.zip)

**Comment by AliMeer** [comment]
@cakesoft-swati Please try this in a few other android devices on browser stack.
I think its device specific as I was not able to replicate it.

**Comment by CypherPoet** [comment]
@cakesoft-swati FYI, GitHub now supports uploading videos directly ⚡ 

https://user-images.githubusercontent.com/46851636/103935431-2e0c6400-50ec-11eb-84cf-69c32cccef22.mp4

**Comment by antuz123** [comment]
The initial white screen makes me think that the app is not loading. Not a good sign.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.4.2(202)
-Hexa symbol is now visible

**Comment by antuz123** [comment]
The white screen is still visible for a decent amount of time. Please check on some devices.
