### ISSUE TITLE
Issue on Node settings screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2442]
-After disabling the own node settings , I see this pop up every time I return to this Node settings page.

![Screenshot_20210107-141612_hexa dev](https://user-images.githubusercontent.com/62699947/103874481-361dd100-50f7-11eb-8de4-bd4765f11a89.jpg)

-Also the "view Node Details" button has to be clicked many times.

**Comment by CypherPoet** [comment]
I'm having some trouble reproducing this locally. In the screenshot above, it looks like the node connection _is_ enabled -- so could the issue be that the disable action isn't working and we're retrying the connection unexpectedly?

cc @Parsh

**Comment by CypherPoet** [comment]
https://github.com/bithyve/hexa/pull/2444 should clear up the way we're processing the toggle event, but I'm still not completely certain it gets at the underlying issue here without being able to reproduce it yet

**Comment by cakesoft-swati** [comment]
-This issue is not yet resolved on Android device.
-Tested on Staging app v1.4.1(194)
-Some more chages are there on same screen:
1.There should be a "OK" button instead of "View ode Details".
2.There should be a successful message while we disconnect personal node and connect to BitHyve's node.

**Comment by CypherPoet** [comment]
Regarding `3.Note should be:
: Make sure that your node is accessible at all times for the app to be able to connect to it`

Is this for the note for all success messages, or just the one shown when connecting to BitHyve's node? (@Arpanjainson @antuz123 )

**Comment by antuz123** [comment]
@CypherPoet - this is for the screen where you enter the node details. The note their about the Test node is incorrect and not needed.

**Comment by AliMeer** [comment]
Issues in the list are fixed except point 1. A separate issue is opened to track the residual issue: https://github.com/bithyve/hexa/issues/2468

**Comment by cakesoft-swati** [comment]
-Verified following issues on Staging app version 1.4.1(195)
1.Now it is not showing the pop up every time I visit the Node settings page.
2.There is a "OK" button instead of "View ode Details".
3.There is a successful message while we disconnect personal node and connect to BitHyve's node.
4.Note changes are also visible.
