### ISSUE TITLE
Cant accept keeper request

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2447]
iOS FI staging 194
Cant accept keeper request
tried the link once and it gave white screen after associating the contact
After that when tried the same link again there are loading icons on the buttons and the flow is stuck
https://bithyve-workspace.slack.com/files/UEB7M06KF/F01J2BEP0GN/rpreplay_final1610094134.mp4

**Comment by cakesoft-swati** [comment]
-Verified this issue on Staging app version 1.4.1(194)
