### ISSUE TITLE
Txs not showing up on account screen. shows in view more

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2448]
Balance is displayed but the transaction did not show up on the account screen even after refresh. Can see it on view more.

![image](https://user-images.githubusercontent.com/8697909/103992150-b3117f00-51b9-11eb-9077-facc4b70db2b.png)

**Comment by Arpanjainson** [comment]
The new balance does not show up on the home screen, only on the account.

**Comment by AliMeer** [comment]
@Arpanjainson @antuz123 I did a bunch of debugging and couldn't really see this happening so not sure what the root cause is.
Might as @Parsh to look at it on Sunday.

**Comment by Parsh** [comment]
Fixed the following issues:
- Home screen balance sync(main balance: below wallet name); earlier was only getting sync after login
- Home screen's account tile balance sync (were also getting synched after login)
- Txs not showing up on the account screen(3)

**Comment by cakesoft-swati** [comment]
-Verified these issues on Staging app V1.4.1(195)
1.Now the Txn is showing up on account screen.
2.Also the new balance is now showing up on the home screen.
