### ISSUE TITLE
Upgrade manage backup  Case 1 (Completed only step one Cloud backup)

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#2455]
Pre-condition
1) We have 5 meta share
2) We have not setup or share any RK yet in old manage backup flow
3) We have complete step 1 i.e. cloud backup

Case
We have completed step 1 i.e. cloud backup and if we have not completed next step i.e. Primary Keeper(PK) setup and leave upgrade flow in middle and kill the app

    - Is my upgrade flow start with same point or we should go to new manage backup from here?
    - What we should store on cloud for 1st step ? Is that same as new manage backup i.e. all Primary Mnemonics or one share from that 5 meta shares ?

**Comment by cakesoft-swati** [comment]
Upgrade functionality is not in the app for now.So,closing this issue.
