### ISSUE TITLE
Upgrade manage backup  Case 2 (Completed only step one Cloud backup & Primary Keeper(PK))

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#2456]
Pre-condition
1) We have 5 meta share
2) We have not setup or share any RK yet in old manage backup flow
3) We have complete step 1 & 2 i.e. cloud backup & Primary Keeper(PK)

Case
We have completed step 1 & 2 i.e. cloud backup & Primary Keeper(PK) and if we have not completed next step i.e. contact setup and leave upgrade flow in middle and kill the app

    - Is my upgrade flow start with same point or we should go to new manage backup from here?
    - and if we go to new manage backup at this point then we have just completed level 1 and half of the level 2 
    - and for this then we need to create new meta shares like 2 of 3 it will not work with old one i.e. 3 of 5.
    - and if we goto new manage backup flow with incomplete steps it will work same as our new flow
    
    
    **We are here suggesting that we just complete cloud backup on upgrade flow and then move user to new manage backup page so user can follow same steps to upgrade also**

**Comment by cakesoft-swati** [comment]
Not in the app for now.So,closing this issue.
