### ISSUE TITLE
AC8: 1 to 9: Add Wyre Account

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2458]
This covers AC8: 1 to 9
Please also refer Trello: https://trello.com/c/jw6idytZ/169-ac8-wyre-add-and-buy

Add Account flow with a Wyre option added to list accounts in services. 
Any new properties or types for Wyre account to ensure transactions are marked as Wyre.
Wyre acc should show Wyre icon
In this flow Wyre account will be added as a primary sub account. 
After user clicks proceed to create account, user should be taken to a buy with Wyre screen where the user can buy BTC. The user can choose to cancel buy in which case the user will be taken to home screen.

**Comment by cakesoft-swati** [comment]
-Verified this on dev app v1.4.2(201)
