### ISSUE TITLE
AC8: 10 - 12: Buy with Wyre

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2460]
AC8: 10 - 12
Please also refer Trello: https://trello.com/c/jw6idytZ/169-ac8-wyre-add-and-buy

User has previously setup a wyre account. Wyre account is now disabled in Add New Account screen.
User can use Buy button and on choosing Wyre will be taken to Buy with Wyre screen with the Wyre account or the associated primary account already selected which cannot be switched.
Navigation from Buy button to buy with Wyre screen with all the required checks.
Navigation from Buy with Wyre to Wyre Account Screen after purchase is completed.
Ability to cancel purchase which will take the user to home screen.

**Comment by cakesoft-swati** [comment]
-When the user completes the Buy process, they land on the Account where the buy has happened and it should show a message that the transactions will appear in that account by name, as soon as the transaction is available.

-The above poin is missing,now it lands on Home screen after purchase is completed.
-Also there is no any option to cancle the purchase.

**Comment by AliMeer** [comment]
@cakesoft-swati That is not going to be done as it is technically not possible to this easily at the moment. We will need to consider options for this when we use white label integration with Wyre.
FYI @antuz123
