### ISSUE TITLE
AC9: Buy Button

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2461]
AC9: Please refer Trello: https://trello.com/c/RzPtBFqA/167-ac9-buy-bitcoin

Replace F&F Button with Buy Button.
 Buy button should have - FBTC, Wyre and Swan options . 
 Buy button as per AC9 with FBTC journey starting point moved from bottom menu to Buy Menu 
 F&F starting point moved from F&F button to bottom menu

This ticket should cover:
All UI components
Navigation changes
actions and reducers identified (any additional development for redux will be done in a separate issue)

**Comment by antuz123** [comment]
@AliMeer - as discussed pls look into the concurrent opening of the bottom sheets as a part of this issue or separately.

**Comment by cakesoft-swati** [comment]
Verified this on dev app v1.4.2(201)
