### ISSUE TITLE
Add T&C to Login screen 

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2470]
Please review and the updated Terms of Service. By continuing you have read and accept the Terms of Service.

**Comment by antuz123** [comment]
T&C changes will be by release only. So this will be a part of the Release Notes. It will be an operational activity. We also need to add a note that the T&C will change and it is our discretion. 

Also, put it as a part of the. login screen.

**Comment by AliMeer** [comment]
This has been added to release notes on both Play and App Store with release 1.4.2
