### ISSUE TITLE
Account Shell based balance calculation

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2471]
Instead of directly using the backend account objects on the home screen for calculating/refreshing balance(getBalance fx) use account shells

<img width="1440" alt="Screenshot 2021-01-10 at 1 35 26 PM" src="https://user-images.githubusercontent.com/17980466/104117632-b7b86d80-5348-11eb-9c78-2cb785f70a5f.png">

**Comment by AliMeer** [comment]
This has been completed and verified
