### ISSUE TITLE
The skip button is being selected automatically while the associate contact.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2476]
-After accepting the request(F&F/keeper), when we come to the associate contact screen, the skip button looks already selected and the spinning wheel keeps on rotating.
-Tested in Android devcice(SAMSUNG Galaxy A50) Dev app version 1.4.1(195)
-It is happening only in restored app.
-Also able to reproduce in staging app v1.4.1(195) which is upgraded from 1.4.1(194)

**Comment by antuz123** [comment]
Fresh Install? @cakesoft-swati

**Comment by cakesoft-swati** [comment]
Yes FI on dev app.

**Comment by AliMeer** [comment]
@cakesoft-swati If I recall this was for restored app and only for Android. Please confirm.

**Comment by cakesoft-nikhita** [comment]
This issue is not reproducible now

**Comment by cakesoft-swati** [comment]
-Verified this issue on live app 1.4.1(195) and Dev app version 1.4.2(201)
