### ISSUE TITLE
BitHyve node as fallback

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2477]
The user should be able to select a checkbox while giving the node details which if selected, the app will use the BitHyve node as a backup (after 1 try). So if the app is connected to MyNode, then after one tries to connect to MyNode, if there is a failure, then it tries to connect to the BitHyve node. 

This will impact the following flows:
1. Send
2. Balance fetch

**Comment by antuz123** [comment]
Three options will depend on the response time:
1. App tries automatically 
2. User is shown that it did not work with MyNode and then the app tries to connect to BitHyve node
3. We check for MyNode connectivity during login (for that session)

**Comment by antuz123** [comment]
Make sure that any node connection is a separate instance and any can be used by the app. This is for future requirements.

**Comment by cakesoft-swati** [comment]
If I leave this screen without editing, and come back later, it assumes that I have connected to the node and shows a switch to disconnect. When I come here, my node connection should be shown only when it is actually connected to the node. Not just when the process was started. This can be done along with the BitHyve node as a fallback. And using the edit button properly.

**Comment by Arpanjainson** [comment]
@Parsh @AliMeer  do we have a mainnet own node which we can connect to and test?
