### ISSUE TITLE
Change contact details 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2478]
Once F&F is added, the user should be able to change the contact name if they want. The edit button will give them a way to either associate a contact or just input a name.

**Comment by antuz123** [comment]
For skip or otherwise.

**Comment by antuz123** [comment]
Friends & Family – Contact Details
Friends & Family – Contact Details – Edit
Friends & Family – Contact Details – Edit – Associate
in
Specs Link: https://xd.adobe.com/view/6e89fcde-5787-4d1a-a1ba-c284e770fdad-3bda/

**Comment by AliMeer** [comment]
Need to check if this is still required and if the UX mentioned in previous comment is correct.
