### ISSUE TITLE
Unable to enable the 2FA on android device.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2481]
-I'm unable to enable the 2FA on android device.
-Tested on FI dev app v1.4.1(195)
-Tested on SAMSUNG Galaxy A50
-Also happening on Staging app v1.4.1(195)
[Screen_Recording_20210111-120936_hexa stage.zip](https://github.com/bithyve/hexa/files/5796173/Screen_Recording_20210111-120936_hexa.stage.zip)

**Comment by AliMeer** [comment]
@Parsh Assigning this to you. Would suggest first let’s test after merging the 2FA PR.

**Comment by Parsh** [comment]
2FA PR merged, waiting for the deployment of the Signing server in order to move forward with this

**Comment by Parsh** [comment]
Tried enabling 2FA a couple of times on the simulator(both iOS and Android) and the issue didn't seem to occur. If it's happening on a particular device(with a particular screen resolution) then this could be a UI based issue.

![Simulator Screen Shot - iPhone 12 - 2021-01-13 at 16 27 10](https://user-images.githubusercontent.com/17980466/104449767-2144b000-55c5-11eb-9563-c9a658b500c4.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.4.2(203)
-Unable to recreate this issue.

**Comment by cakesoft-swati** [comment]
-Tested this issue on Dev app v1.4.2(210)
-Now I have to long press it to enable the 2FA.
-Tested on Android device SAMSUNG Galaxy A50.

**Comment by AliMeer** [comment]
Closing this as the issue is related to the button not getting clicked. Tracking this issue here https://github.com/bithyve/hexa/issues/2599
