### ISSUE TITLE
Refresh account balances with and without own node.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2482]
I do not see all the transactions (when I connect to the own node)which I have done using the BitHyve node.
-While using Bithyve node:

![Screenshot_20210111-194630_hexa stage](https://user-images.githubusercontent.com/62699947/104193673-61c9ef80-5446-11eb-930c-f366608f1ccb.jpg)

-When connected to the own node by disconnecting the Bithyve node:
![Screenshot_20210111-194858_hexa stage](https://user-images.githubusercontent.com/62699947/104193857-90e06100-5446-11eb-91d0-18328d354b21.jpg)

**Comment by AliMeer** [comment]
@cakesoft-swati They are all new transactions once they have confirmations they will be visible.

**Comment by AliMeer** [comment]
> @cakesoft-swati They are all new transactions once they have confirmations they will be visible.

@cakesoft-swati please confirm if the balances refreshed after the transactions had confirmations.

**Comment by cakesoft-swati** [comment]
-Unable to reproduce this issue on dev app version 1.4.2(202)
-I can see the all transactions including unconfirmed one.
