### ISSUE TITLE
Send unsuccessful while trying to send from testnet.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2490]
![Screenshot_20210111-193632_hexa dev](https://user-images.githubusercontent.com/62699947/104275404-c332a280-54c8-11eb-9318-4f1fd9a38079.jpg)
-Some technical error occurred while sending failed.
-This issue is rarely coming up.
-Tested on mobile Staging(also on dev app) app v1.4.1(195)

**Comment by Parsh** [comment]
Would require more details about the nature of send(was it send-max and were we spending derivative utxo i.e. utxo from trusted contact, fbtc etc).

**Comment by cakesoft-swati** [comment]
1.Sent some amount from Test account to checking account.(sent 2000sats)
2.Tried it from android device.
3.Tested on dev app v1.4.2(201)
![Screenshot_20210120-103936_hexa dev](https://user-images.githubusercontent.com/62699947/105131763-9b1df180-5b0f-11eb-9f4d-67935255db10.jpg)

**Comment by Parsh** [comment]
Wasn't able to replicate it just yet. The bottom err apparently happens when the broadcasting node doesn't return a txid(and neither an err), parking it for now, we can investigate it further if it occurs frequently.

**Comment by Parsh** [comment]
Should get fixed w/ the #2675 issue

**Comment by cakesoft-swati** [comment]
-Not able to replicate this issue.
-Tested in Dev app v1.4.5(227)
