### ISSUE TITLE
Add update to T&C in the 1.4.2 release notes

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2496]
The T&C were last updated on 13th January 2021.
https://hexawallet.io/terms-of-service/
for
 This Agreement may be amended by BitHyve **without** providing you advance notice of any proposed change. If you do not agree to the amended agreement then your sole remedy will be to stop using the Services, including any Wallet.

Added word "without".

**Comment by Arpanjainson** [comment]
@antuz123  - FYI

**Comment by antuz123** [comment]
Text on the release notes: 
The T&C was last updated on 13th January 2021.
https://hexawallet.io/terms-of-service/
