### ISSUE TITLE
Review of Wyre flow UX

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2504]
Need to review the Wyre flow and get UX feedback/ correction.

**Comment by Arpanjainson** [comment]
UX team Sumaiah is working on this. ETA - Thursday.

**Comment by Arpanjainson** [comment]
Wyre/ramp screen color
https://xd.adobe.com/view/00485057-d5b7-4b2b-641b-20216b3a38d5-7679/screen/a3f25a38-b42a-4374-b63d-d188414f35b2/
https://xd.adobe.com/view/00485057-d5b7-4b2b-641b-20216b3a38d5-7679/screen/8a780aed-2930-43f7-bd27-96edd0c1693e/

**Comment by antuz123** [comment]
Tested by Prasad
