### ISSUE TITLE
Action to add secondary sub account 

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2515]
We currently don’t have an action to add secondary sub account.
Trusted contact and FBTC account should be added via redux actions.
This would include removing non UI code away from screens and moving to Bitcoin and redux saga.
Trusted contact and FBTC don’t need to be added via the same action, as long as it is some action i.e addFBTCSubAccount or addTrustedContact and it accepts the primary sub account to which the sec sub account will be added.

**Comment by Parsh** [comment]
Saga & action to add secondary sub-account are in place, also the FBTC integration for this is done.

**Comment by AliMeer** [comment]
Closing dev task
