### ISSUE TITLE
Unable to scroll if there are more(3/more than 3) transactions.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2527]
-Buttons do not appear after 3 or more than 3 transactions and are not even scrolling.
[IMG_0039.zip](https://github.com/bithyve/hexa/files/5834476/IMG_0039.zip)

![IMG-20210119-WA0007](https://user-images.githubusercontent.com/62699947/105005991-0c03d180-5a5c-11eb-9812-02271fc8f13d.jpg)

**Comment by AliMeer** [comment]
This works fine in IOS so probably only for Android.

**Comment by cakesoft-nikhita** [comment]
> This works fine in IOS so probably only for Android.

For iOS also iPhone 8 simulator having the same issue, spacing is not properly handled and UI also not looks good.. I did with these changes committing shortly

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app version 1.4.2(202)
