### ISSUE TITLE
Savings account:Not able to enter OTP while sending from savings account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2536]
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-20 at 13 48 48](https://user-images.githubusercontent.com/62699947/105151467-04136280-5b2c-11eb-9d18-a69716c725ad.png)

-Not able to enter OTP (OTP to authenticate)when sending from savings account.
-The loader is not moving away from this screen.

**Comment by AliMeer** [comment]
@cakesoft-swati Is this Android only?

**Comment by cakesoft-swati** [comment]
verified this issue on dev app v1.4.2(203)
