### ISSUE TITLE
Friends and Family screen issues.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2541]
-Observed on UP Live app version 1.4.1(195)
-The screen is getting stuck for a while and we can not  refresh it  and cannot click anywhere(I have to kill the app).
-I have a contact in "I am the Keeper of", the app is crashing by clicking on it.

**Comment by antuz123** [comment]
this is on the production app. Try to add some contacts and see if it works well for you. Use skip, expired, pending, a combination and see the performance.

**Comment by cakesoft-swati** [comment]
Duplicate of #2285
