### ISSUE TITLE
There is over 100 branches, most of which are fully merged. Why not delete them?

### ISSUE THREAD

**Issue by Giszmo** [bithyve/hexa#2545]
Just a curious question from a guy who cleans up after his colleagues who forget to delete branches all the time ;)

**Comment by AliMeer** [comment]
@Giszmo thanks for the observation :)
Just did some more clean up and have it down to 30 now :)

We have a very distributed team in different time zones so we don't delete relatively new branches in case the creator still wants to work on it or to refer back to it. Some features are POCs and experimental in nature so we may not merge them for a long time and continue to refer back to it.

**Comment by Giszmo** [comment]
Deleting branches on GitHub does not affect branches on the machine of the developer who introduced or worked on that branch locally. To get rid of upstream deleted branches they have to run

```
git remote prune origin
```

so if they want to revive the branch, they can still just `git checkout featureX; git merge master # which is a fast forward` and hack on using the upstream deleted but soon to be revived branch name.
