### ISSUE TITLE
Need UX for Full Rescan

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2547]
From account settings or should it be from More> Settings. 

A screen that tells the user to wait as it may take a few mins.

**Comment by Arpanjainson** [comment]
From account settings or should it be from More> Settings.
A screen that tells the user to wait as it may take a few mins.
Account settings - Account balance refresh
Wallet settings - whole wallet balance refresh

**Comment by AliMeer** [comment]
@Arpanjainson @antuz123 do we have this?

**Comment by Arpanjainson** [comment]
Proto link
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/291eefe9-fa03-4eb3-aa56-69522da4f866

**Comment by Arpanjainson** [comment]
For full rescan the new icon will be updated on this link https://xd.adobe.com/view/00485057-d5b7-4b2b-641b-20216b3a38d5-7679/screen/2ecd2b97-dfb0-4342-b9d7-f36b98b6daa8/
"Full rescan"

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (286)
