### ISSUE TITLE
Toast message  -as fall back during own node

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2549]
Only during send and Refresh

Toast - We could not connect to your own node.
Refreshed/Sent using the BitHyve node....

If the fall back was not selected.
We could not connect to your  node.
Try connecting to the BitHyve node-  Go to settings ....

**Comment by cakesoft-swati** [comment]
-Verified the second point i.e
[If the fall back was not selected.
We could not connect to your node.
Try connecting to the BitHyve node- Go to settings ....]

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.4(226)
