### ISSUE TITLE
Wyre Account should be first option in service accounts (Add New Accounts)

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2553]
-It Should be the first and not in grey.
![wyracc](https://user-images.githubusercontent.com/62699947/105455783-174c3c80-5caa-11eb-8536-734f46fe0a2a.jpg)

**Comment by AliMeer** [comment]
@cakesoft-swati the Wyre account goes grey when a user already has a Wyre account. We are allowing only one Wyre account in this release.

**Comment by antuz123** [comment]
@AliMeer - yes correct. Just make sure it is first when not created, it appears second even on a fresh wallet

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.2(208)
