### ISSUE TITLE
The Buy icon is not correct.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2556]
-The icon is still not correct.
<img width="375" alt="68423F8B-9658-4BCF-A175-0CAB0DECD0D0" src="https://user-images.githubusercontent.com/62699947/105456724-a9087980-5cab-11eb-91cf-8c5316736420.png">

**Comment by AliMeer** [comment]
@cakesoft-swati What is the correct icon?

**Comment by antuz123** [comment]
@AliMeer - it is cut in the current view. The Bitcoin ball and arrow both are cutting

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.2(208)
