### ISSUE TITLE
Textual change on splash screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2559]
-Bitcoin is for everyone.
<img width="375" alt="DA111FB4-79F6-41F3-A2F3-792155D44C4B" src="https://user-images.githubusercontent.com/62699947/105457448-dc97d380-5cac-11eb-91ce-0203a7d6eb5e.png">

**Comment by AliMeer** [comment]
@antuz123 this is part of the video afaik not a text change.

**Comment by AliMeer** [comment]
Need to understand how this video was created in order to change the text in the video.

**Comment by Arpanjainson** [comment]
Also see if we can reduce the size of the video

**Comment by cakesoft-swati** [comment]
Verified the change on splash screen in Dev app v1.4.4(220)
