### ISSUE TITLE
Changes on more screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2560]
-We don’t need F&F here.
-Text change: Connect Hexa wallet to your own Bitcoin node.
![node settings](https://user-images.githubusercontent.com/62699947/105458043-d6eebd80-5cad-11eb-9ff9-f0c5d9da389f.jpg)

-Incorrect asset for Account management. 
-Don’t need Funding Sources here either.
<img width="375" alt="807BD64B-6C38-4EF2-9D91-63C0B0DF7D34" src="https://user-images.githubusercontent.com/62699947/105467604-ed037a80-5cbb-11eb-86ea-64f51419a911.png">

**Comment by cakesoft-swati** [comment]
-Incorrect asset for Account management. 
-Don’t need Funding Sources here either.
<img width="375" alt="807BD64B-6C38-4EF2-9D91-63C0B0DF7D34" src="https://user-images.githubusercontent.com/62699947/105467604-ed037a80-5cbb-11eb-86ea-64f51419a911.png">


[The above changes are still pending.}

**Comment by AliMeer** [comment]
This can be done when the account management icon is available. The more screen and hence the account management icon is not present in xd. For reference: https://xd.adobe.com/view/a9aaad23-c5ea-4067-8734-cf64073bca02-fcf9/screen/cead3d5f-3e29-4509-ac0a-3e262b77a39b/

**Comment by cakesoft-swati** [comment]
Funding sources are still visible on more screen.

**Comment by AliMeer** [comment]
Fixed this in build 215

**Comment by cakesoft-swati** [comment]
-Verified this issue on Staging app v1.4.2(215)
