### ISSUE TITLE
UI changes on "Node settings" screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2561]
-Why do we still have the edit button? If the user changes the text, it is edited else it is not. See how we have done it for Donation Account change details.
![IMG_1469](https://user-images.githubusercontent.com/62699947/105468195-b843f300-5cbc-11eb-8adc-f0e448111cfc.jpg)

**Comment by CypherPoet** [comment]
This edit button is from the designs here: https://xd.adobe.com/view/00485057-d5b7-4b2b-641b-20216b3a38d5-7679/screen/276f6112-53fe-4692-aaa5-cedd7f455571/specs/

Is this not the correct design spec?

**Comment by antuz123** [comment]
the user should be able to see the node details entered last time and let's leave the edit button

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.4.2(210)
