### ISSUE TITLE
The app is crashing when switching from own node to a Bithyve node.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2562]
After successfully connecting to own node, when I switch to the bithyve node, the app is crashing.
-Steps to follow:
1.Connect to own node.
2.Tick the fallback option(or without fallback option).
3.Click the proceed button.
4.Now switch to the Bithyve's node and observe.
-Tested on dev and staging v1.4.2(205)

**Comment by AliMeer** [comment]
@Parsh refer to the video in slack, its too big for uploading here. https://bithyve-workspace.slack.com/files/UEAGC62D9/F01KQSQ7C20/rpreplay_final1611314136.mp4

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app version 1.4.2(208)
