### ISSUE TITLE
Regarding text layout

### ISSUE THREAD

**Issue by sz3k** [bithyve/hexa#2568]
I am working through some of the code in the hexa/src/components/Helper/ in my fork of the code and noticed some of the Help sheets had manual line breaks (via {'\n'}) and some don't - are these due to different stylistic approaches to the code? Are they necessary, and will text still wrap on these sheets?

**Comment by AliMeer** [comment]
@sz3k Ideally all the new line escape characters  need to be taken out from the text in all the places they are currently present. 
However it’s not just a question of removing them, but rather (1) the screens would need to be verified in different screen sizes to ensure that the text still appears correctly. (2) Some new lines are used to display 2 blank lines at the start of a paragraph, these will need to stay or be replaced with a paragraph tag.

so it’s a bit of a task to get it done and hence has been on our backlog for sometime now.

**Comment by sz3k** [comment]
Good to know. In this case, looks like I'm going to have to break out the old and trusty android emulator and make sure it doesn't break anything.

Thanks!

**Comment by AliMeer** [comment]
Have you been able to build and run the app?

**Comment by sz3k** [comment]
> Have you been able to build and run the app?

@AliMeer I'm currently on the road, but will build and mess around with it tomorrow into early week.

**Comment by AliMeer** [comment]
@sz3k I would say hold on trying to build and run it for now. you need additional information for env files to run the app. Which you will need. I am going to add some of it to the app itself soon so that the need for additional information will be minimal.

**Comment by antuz123** [comment]
@cakesoft-swati - how is this missed out of any release?

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
