### ISSUE TITLE
Txn not showing in Checking account

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2569]
From user:

 I’m a new Hexa wallet user. I tried to send some of the bitcoin I had purchased via Coinbase to my Hexa account using the “Bitcoin Receiving Address” generated in my Hexa Checking account. I have a confirmation from Coinbase that the bitcoin was sent, but it still hasn’t recorded in my Hexa account. Can you help?
Data of Transaction: 21 January 2021
Bitcoin Receiving address utilized (*this is the address generated in my Hexa Checking account): 382H5gNVyYpt9aFosGLdjSEVEQVCVivp1r

Bitcoin USD ($) amount: $98.96

Bitcoin amount: 0.00324024

**Comment by antuz123** [comment]
@AliMeer is testing this on live

**Comment by cakesoft-swati** [comment]
![File (28)](https://user-images.githubusercontent.com/62699947/105946467-581ec980-608d-11eb-8be4-e54a6aba551f.jpg)

**Comment by Arpanjainson** [comment]
![image](https://user-images.githubusercontent.com/8697909/105949230-5efc0b00-6092-11eb-9d1e-3e8422675054.png)

**Comment by antuz123** [comment]
@cakesoft-swati: have you tried it with the upgraded apps with the dates mentioned?

**Comment by antuz123** [comment]
@Parsh - check what the Wrapper is returning
@AliMeer - do one more transaction on FBTC and check if the old one appears, then try to restore 
@cakesoft-swati - try to recreate on staging app 
@antuz123 - try to get another address from the user and send a token amount there

**Comment by Parsh** [comment]
> @Parsh - check what the Wrapper is returning

Wrapper is returning the correct value

<img width="1440" alt="Screenshot 2021-01-27 at 6 14 29 PM" src="https://user-images.githubusercontent.com/17980466/105992846-99ce6500-60cb-11eb-9435-e7506ef9354a.png">

**Comment by AliMeer** [comment]
I have done another FBTC transaction, it does not appear.
I have restored, none of the FBTC voucher transactions have appeared in the restored app.

**Comment by AliMeer** [comment]
FBTC transaction missing issue has been identified and fixed: https://github.com/bithyve/hexa/pull/2613

Checking account receive transaction missing issue still persists.
