### ISSUE TITLE
Styling should be the same on all pages.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2573]
-Check the shadow effect.[Specifically in android device]
![Screenshot_20210125-185855_hexa dev](https://user-images.githubusercontent.com/62699947/105715429-9c9e4e00-5f43-11eb-9445-f9cb47cbf95b.jpg)

-Also the Title and sub-title styles should be the same on home page and "Add new" account page.
[Both the issues are specifically on android device]
![Screenshot_20210125-193103_hexa dev](https://user-images.githubusercontent.com/62699947/105715777-06b6f300-5f44-11eb-8b7c-1b262dcc646c.jpg)

![Screenshot_20210125-193126_hexa dev](https://user-images.githubusercontent.com/62699947/105715815-10d8f180-5f44-11eb-8ced-8921df55642e.jpg)

**Comment by CypherPoet** [comment]
Regarding:

> the Title and sub-title styles should be the same on home page and "Add new" account page.

Is this asking for the Home styles to adopt the look of the "Add new" account page styles, or vice-versa.

Currently, both screens are trying to follow the designs in https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/grid

(@antuz123 @Arpanjainson)

**Comment by antuz123** [comment]
Follow what is on HS. 

Title: Caps on Every Important Word
Subtitle/ description: Only sentence start and proper nouns/ names

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.2(211)
