### ISSUE TITLE
Swan Authentication

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2581]
As a user I should be able to use add swan account option in Hexa and login and authenticate with swan so that I can authorise Hexa to create a Swan Account.

Test Scenario: User is able to start journey on Hexa via (1) Add Swan Account (2) Swan option in Buy menu and able to login to Swan and authorise Hexa to create a Swan account.

**Comment by AliMeer** [comment]
This will be part of v1.4.6 build

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (293)
