### ISSUE TITLE
Localisation framework

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2585]
Identify, assess and add a suitable localisation framework to the app.
The framework and any supporting code should be written so that it can be reused across the app.
A sample screen should be localised as an example.

**Comment by AliMeer** [comment]
Localisation framework added.  
Currently UI doesn't have change language settings so language will be english by default.  
Once translations are available and UI change language settings are available user's will be able to change language.

![Screenshot 2021-02-07 at 21 48 00](https://user-images.githubusercontent.com/7535475/107160618-3a0b7000-698f-11eb-8a3a-7085c7a52c65.png)

**Comment by Arpanjainson** [comment]
We will test it in v1.4.5

**Comment by AliMeer** [comment]
This has been completed.
