### ISSUE TITLE
Buttons not clickable in some some Android devices

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2599]
`onPress` event not getting triggered in some android devices,  Samsung A50 is one of the devices impacted.

https://github.com/bithyve/hexa/issues/2570 - Buy menu item not getting clicked.
https://github.com/bithyve/hexa/issues/2481 - Proceed button not getting clicked.

We had a similar issue in the past with node setting button which was fixed with this commit: https://github.com/bithyve/hexa/commit/c61b880fa4c928cc06ab6236a835c93acaac0b42

**Comment by AliMeer** [comment]
The issues related to this have been fixed, retested and closed.

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.4(222).
-Now able to create a Wyre account using Home > Buy option.
-Able to enable the 2FA on android device.
