### ISSUE TITLE
Rescan Account: Icon and Navigation

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2607]
We need to have appropriate assets for the hard refresh functionality(icon and text). Also, the navigation needs to be sorted, right now clicking on hard refresh does dispatch the corresponding action, however, it doesn't navigate back to the account details screen.

![Simulator Screen Shot - iPhone 12 mini - 2021-01-28 at 12 04 19](https://user-images.githubusercontent.com/17980466/106099814-4e669600-6161-11eb-9bf0-6c2ee61a3e3d.png)

Related to #2333 

Refer to https://github.com/bithyve/hexa/issues/2547 for UX

**Comment by Parsh** [comment]
@Arpanjainson We need the UX for hard refresh

**Comment by AliMeer** [comment]
@Arpanjainson @antuz123 Can we have the link to the xd file please so that we can make the UI screen.

**Comment by CypherPoet** [comment]
[This is the screen](https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/2e69233c-c9e9-4294-abd6-98587304c55d/) I found in the Hexa Wallet UI document. Is that the correct design @Arpanjainson @antuz123?

**Comment by AliMeer** [comment]
@CypherPoet 
Yes thats the one

**Comment by CypherPoet** [comment]
Nice. In the screenshot above, though, the title says "Hard Refresh". In the design, it's Full Rescan. The design is also using Lorem ipsum for the subtitle. Is there any additional clarity on how we want to present this?

**Comment by AliMeer** [comment]
ok, refer to this https://bithyve-workspace.slack.com/archives/CN7K6RY9Z/p1612184750109100

**Comment by Arpanjainson** [comment]
for the account sync and full resync/scan please change the call to action icon - for sync can be the same as the one we have for the sync on the home screen cards, as these are  all sync actions

**Comment by AliMeer** [comment]
Refer to https://github.com/bithyve/hexa/issues/2547 for UX info.
