### ISSUE TITLE
Trusted Contacts: adding secondary sub-account via action

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2610]
Part 2 of the following issue #2515 

This would remove non UI code for TC away from screens and move to redux-saga while adding the sec sub-account to the appropriate parent shell

**Comment by Parsh** [comment]
@cakesoft-swati Would require extensive testing of the flows (TC, TC-Guardian, and TC-payment).

**Comment by AliMeer** [comment]
This is completed, doesn't have a testable functionality yet. This will be tested after we use the new action with trusted contact journey in the next release.
