### ISSUE TITLE
Transaction not showing on receivers side.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2611]
-I sent some sats from FI Prod app(1.4.1(195)) to Upgraded app(Staging app 1.4.1(195) to 1.4.2(211)). 
-I also received a successfully sent message but did not received any transaction on receivers side.

<img width="375" alt="C154FF21-425B-40F3-9D1A-17335DD26908" src="https://user-images.githubusercontent.com/62699947/106140136-60156100-6194-11eb-91f5-9b2e21fc8474.png">

**Comment by Parsh** [comment]
Closing this, Swati plugged in test own-node's configuration into staging app, and therefore the bal-tx scan was failing and hence the tx wasn't showing up.
