### ISSUE TITLE
The text(Long description) is overlaying on the icon.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2614]
![tempFileForShare_20210128-181639](https://user-images.githubusercontent.com/62699947/106140742-2bee7000-6195-11eb-8801-f69f2d18d6ca.jpg)
-Now this is happening only on the account screen, not on the home screen.
-Tested on Staging  app v1.4.2(211)

**Comment by AliMeer** [comment]
part of build 215

**Comment by cakesoft-swati** [comment]
Verified this issue on stagig app v1.4.2(215)
