### ISSUE TITLE
 F&F list is getting stuck on refresh.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2623]
-Also my F&F list is getting stuck on refresh.I have to kill the app everytime.
-I can't even scroll the screen or click on any contact.
-I have lot of contacts(atleast 7) in my F&F list.
-upgraded staging app [from 1.4.1(195)to1.4.2()211 to1.4.2(212)].

**Comment by AliMeer** [comment]
This can be replicated by pulling the F&F screen all the way down. a smaller pull down refreshes the screen and doesn't cause it to get stuck. Pulling all the way down causes screen getting stuck.

This is actually a  live issue and present in the current live app as well and might have been in the app for even longer.

Build 215 fixes this issue.

**Comment by cakesoft-swati** [comment]
-Not able to reproduce it on staging app version 1.4.2(215)
