### ISSUE TITLE
App is crashing on Manage Backup after restore.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2624]
[Screen_Recording_20210129-163948_hexa stage.zip](https://github.com/bithyve/hexa/files/5893593/Screen_Recording_20210129-163948_hexa.stage.zip)

**Comment by AliMeer** [comment]
I have not been able to replicate this on IOS. can we retest this in build 215 please.

**Comment by cakesoft-swati** [comment]
-It is still happening on Android device(SAMSUNG Galaxy A50).
-Now I upgraded the app from 1.4.2(112) to 1.4.2(115),still the app is crashing.
