### ISSUE TITLE
Home auto sync complete status is not being updated

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2631]
On login, this is is called https://github.com/bithyve/hexa/blob/c4edcad2c4a98acce12bf0629da742cbdfd553f6/src/pages/Login.tsx#L138
Which updates `syncStatus` for each account Shell to `syncStatus.PENDING`

The following needs to be verified and if not occurring has to be implemented

1. When soft or hard refresh starts syncStatus for the account shell should be updated to `syncStatus.IN_PROGRESS`

2. When soft or hard refresh has completed syncStatus for the account shell should be updated to `syncStatus.COMPLETED`

**Comment by AliMeer** [comment]
This commit addresses this issue: https://github.com/bithyve/hexa/commit/747a9e5e103c0f312d3e71970c997a7f5ee2526b

**Comment by AliMeer** [comment]
Not able to replicate this anymore after the fix.

**Comment by AliMeer** [comment]
Using all gif files for the animation sequence instead of a mix of gif and png: https://github.com/bithyve/hexa/commit/a9e5c57994906d6cef616df37f6f669ab3ecbd7a

If this does not fix the issue then it is related to:
https://github.com/facebook/react-native/issues/9280

**Comment by Arpanjainson** [comment]
on dev 1.4.4-v200 ios fresh install
@AliMeer  at the start of the app all 3 acconts test, checking and savings have refresh icon, click on test the account does not show the refresh icon and when the user moves back to the home screen the refresh icon is gone on test and checking account, but the savings account does have the static refresh icon.

-

**Comment by Arpanjainson** [comment]
It did auto refresh but only after the user stays on the home screen for 5-6 seconds.
