### ISSUE TITLE
Add message for rooted device

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2641]
Linked to https://github.com/bithyve/internal-docs/issues/52

The rooted device message on the bottom should include some sort of additional information, letting rooted users know that it may be trivial for other apps to extract their data and perhaps to tell them to use a strong passphrase to mitigate this.

![100807181-c77b9280-3429-11eb-9669-39ce96e3bdfb-2](https://user-images.githubusercontent.com/7535475/106650591-ff6a9780-658a-11eb-9d05-37da18d778ee.png)

**Comment by Arpanjainson** [comment]
@antuz123  we will need a rooted device
@Varunram  do u have on?

**Comment by Arpanjainson** [comment]
@AliMeer  could please post what additional message was added for rooted device?

**Comment by AliMeer** [comment]
Here are the messages, this has been verified:

**iOS:**

You are using a jailbroken device hence in built security features of the app as well as the phone will not work as intended. We recommend you use a non jailbroken device with the latest iOS updates installed to ensure the security of your app data

Android:
You are using a rooted device hence in built security features of the app as well as the phone will not work as intended. We recommend you use a non rooted device with the latest Android updates installed to ensure the security of your app data
