### ISSUE TITLE
Archive account 

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2650]
Add account archive functionality.
Account can only be archived if there is no balance.
The archived account can be restored back.

**Comment by Arpanjainson** [comment]
Still needs to be speced out. The proto links are
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/affa2576-d026-44b8-9321-4065766f6195

look for screens
Checking Account – Settings – Archive
Checking Account – Settings – Archive Error
More – Account Management
More – Account Management – Un Archive
Success Screen – Un Archive

**Comment by AliMeer** [comment]
Closing this as it is a duplicate of https://github.com/bithyve/hexa/issues/2332
