### ISSUE TITLE
Balance not correct after sending transaction

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2656]
After sending transactions the balance increased instead of decrease.
This was corrected after doing a refresh.

![File (3)](https://user-images.githubusercontent.com/7535475/106892109-86cb1e80-66e3-11eb-818e-4f4c1af04599.jpg)

**Comment by Parsh** [comment]
Haven't been able to encounter this scenario yet. Keeping an eye on it tho.

**Comment by AliMeer** [comment]
Closing this issue as it has not re occurred.
