### ISSUE TITLE
Lowering the minimum fee

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2657]
We should use mempool's lower bound(sats/byte) as our custom fee lower bound

Connected to: #2618

**Comment by Parsh** [comment]
Custom fee lower bound set to mempool's default [minimum relay feerate](https://bitcoin.org/en/release/v0.12.0#memory-pool-limiting)

**Comment by Parsh** [comment]
> We shouldn't block a user from sending if the low priority fee + amount to send > balance. User should be able to send w/ however low fee(till it's greater than or equal to the minimum fee to relay).

Will be moving this to 1.4.5

**Comment by Arpanjainson** [comment]
we will need a staging build.

**Comment by Arpanjainson** [comment]
tested on testnet for 1 sat/byte

**Comment by Arpanjainson** [comment]
Will need to test on mainnnet

**Comment by Arpanjainson** [comment]
@AliMeer  for this to test we need to update the minimum relay fee on testnet atleast

@antuz123 - FYI

**Comment by Arpanjainson** [comment]
moving to v1.4.5 for testing.

**Comment by cakesoft-swati** [comment]
Mentioned this issue in #2749
-So closing this issue.
