### ISSUE TITLE
Provide list of new transactions after rescan

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2658]
We would require a list of new transactions(delta b/w soft and hard refresh) after account rescan.
These will be picked up by the re-scan UI from the designated reducer.

The UI will retrieve the list of transactions from the state after it gets syncStatus.COMPLETE

**Comment by Parsh** [comment]
Note: Hard refresh shouldn't start w/ a blank tx slate, it should ideally scan all the addresses from the initial index but should only append the missing txs and these txs can then be supplied to the appropriate reducer as well.

**Comment by Arpanjainson** [comment]
@Parsh  can this be QA'ed indepedently?

**Comment by AliMeer** [comment]
Closing this as it is a dev task.
