### ISSUE TITLE
Answer validation info are getting hidden

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2660]
The answer validation details are getting hidden in some devices. Probably because of the note moving up with the keyboard.
Perhaps we can keep the note in its place and not move it.

![Screenshot 2021-02-04 at 20 05 35](https://user-images.githubusercontent.com/7535475/106949499-ec8bca80-6724-11eb-9ec0-53d3c0ec1ea5.png)

**Comment by cakesoft-swati** [comment]
-Need to test this on build 224.
-It is still happening on Android device SAMSUNG Galaxy A50

**Comment by cakesoft-swati** [comment]
-Still happening this on dev app v1.45(230)

**Comment by antuz123** [comment]
either use the keyboard height and not show the note. Or if that is not possible, just hide notes when keyboard comes up.

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
