### ISSUE TITLE
UI issues of Keeper app.

### ISSUE THREAD

**Issue by cakesoft-nikhita** [bithyve/hexa#2662]
1.Keeper loading screen icon is too blurry.
2.Even when the app is killed it remembers the last screen you were on
3.The fonts and the overall spacing is not as per the specs
4.Back button is too high and is overlapping with the clock on iPhoneXR
5.Back using "left to right" slide is not working on iOS.
6.Somehow I can zoom in the app.
7.Landscape mode is totally distorted.

**Comment by cakesoft-nikhita** [comment]
Back using "left to right" slide is not working on iOS
This is not possible currently. We can use the back arrow on the top. Other than this all issues are done. 
Please check in the next release

**Comment by cakesoft-swati** [comment]
Old KBHR flow
