### ISSUE TITLE
Not able to land on the main screen of the Keeper app.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2668]
-On scanning the Keeper's QR, the hexa side set-up(Primary Keeper) is being completed, but the user is not able to land on the main screen of the Keeper app.
-It is happening only on iphone 7.

**Comment by cakesoft-nikhita** [comment]
@cakesoft-swati Please check this in the next release as we are removing done button on this Page

**Comment by cakesoft-swati** [comment]
-Verified this issue.
-Now we can land on the main screen of the Keeper app.
