### ISSUE TITLE
Total balance on test account does not add up

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2685]
Was able to see the big transaction in the test balance and then made sent test txns to checking account. Now when i logged in after an hour the balance on test account does not add up as what came in and what went out
![image](https://user-images.githubusercontent.com/8697909/107338901-14db4680-6ae2-11eb-95a7-30588fd0ddbc.png)
![image](https://user-images.githubusercontent.com/8697909/107338913-17d63700-6ae2-11eb-8e4e-6f658c9e9cf2.png)
![image](https://user-images.githubusercontent.com/8697909/107338924-1b69be00-6ae2-11eb-8bf1-c3f277d9eb1c.png)

**Comment by Arpanjainson** [comment]
You can also see the 452 fee with no amount txns which was sent as 2.5 being sats/byte fee

**Comment by Arpanjainson** [comment]
https://files.slack.com/files-pri/TEBLGFFFH-F01MCRH2ZJ9/file.jpg
![image](https://user-images.githubusercontent.com/8697909/107339219-6daadf00-6ae2-11eb-8021-e4a8870b1987.png)

**Comment by Arpanjainson** [comment]
hard refresh did not help. After hard refresh the order of transactions in the view more transactions went for a toss

**Comment by Parsh** [comment]
Have tried this out a bunch of times, however, wasn't able to really replicate it. Tho the transfer to self bug is known and we have a separate issue to address that.

**Comment by cakesoft-swati** [comment]
-I saw this issue on iphone 7.But it appears very rare.
-The transaction that was visible disappears after some time and it shows the wrong balance.
<img width="375" alt="A49BDFAF-777D-4F84-92B3-D4D1A6E78555" src="https://user-images.githubusercontent.com/62699947/113561705-a4a0fb00-9622-11eb-872f-cc8aac917f46.png">

**Comment by cakesoft-swati** [comment]
-Unable to reproduce this issue on dev app v1.8.0(304)
