### ISSUE TITLE
Change in the ordering.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2693]
-The order should be Wyre then FBTC and then Swan.
![ordershouldbe](https://user-images.githubusercontent.com/62699947/107469109-29294d00-6b8f-11eb-8c4f-da8f6f92a63f.jpg)

**Comment by AliMeer** [comment]
Will be part of 224

**Comment by cakesoft-swati** [comment]
Noe the wyre and swan options are disabled.
