### ISSUE TITLE
UI issue on savings account/Donation account while entering wrong OTP for setup a 2FA authentication.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2697]
//steps to reproduce//
1.Go to the savings account /Donation account. Now set up two factor authentication and click the continue button.
2.now enter the wrong OTP and click on confirm button.
3. observe the screen,That confirm button is clicking but not moving.
4.It is coming on the "2F validation unsuccessful screen."
-It is happening only in android device.I tested it on SAMSUNG GALAXY A50.
![Screenshot_20210210-152108_hexa dev](https://user-images.githubusercontent.com/62699947/107540342-f5304500-6beb-11eb-967d-5818679df653.jpg)

**Comment by AliMeer** [comment]
I was able to replicate this on Samsung A50.

**Comment by cakesoft-swati** [comment]
-Still happening on SAMSUNG GALAXY A50.
![Screenshot_20210331-165429_hexa dev](https://user-images.githubusercontent.com/62699947/113137291-ff60de00-9241-11eb-960d-28dec81fffbc.jpg)


-I will check this on other android device as well.

**Comment by cakesoft-devika** [comment]
- Tested on Dev app v1.7.0 (286) and now, bottom section looks hidden
- 
![Screenshot_2021-05-13-10-15-51-499_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/118087738-aad58480-b3e3-11eb-8495-1abc2cdf9767.jpg)

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (288)
