### ISSUE TITLE
App is getting stuck on splash screen when I clicked on expired keeper link.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2698]
-App is getting stuck on splash screen when I clicked on expired keeper link.
[Click here to accept Keeper request for devio Hexa wallet- link will expire in 24 hours
https://hexawallet.io/dev/tcg/devio/4416b571f30d36270eb4c8886187ee15f495f9c77d1510e87dde58eff798e7a9d7326f72dfba53060453499fc8ec32f2a9d13e4223e817fc9910d34b7317411cee6d8e56ae1d4f8dbfb22b2ecb388774/otp/xxx/1612951449941/v1.4.4]
-It is happening on Android .
-Tested on latest dev build1.4.4(223) and 1.4.3(217).

**Comment by cakesoft-swati** [comment]
-I think I opened the deeplink in the wrong place. I just tried one scenario. I opened one live link on dev env after that I got a message of Invalid link,I clicked on ok and app got stuck on the splash screen.

-after that,the app didn't even close. It just stuck on the splash screen.

**Comment by AliMeer** [comment]
Using dev link on live app resulted in app was causing this issue. App shows invalid link message and then stays on splash screen

**Comment by AliMeer** [comment]
I don't this this is a valid issue.
