### ISSUE TITLE
-Not able to enter the OTP while accepting the request

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2699]
[Screen_Recording_20210210-153843_hexa dev.zip](https://github.com/bithyve/hexa/files/5959903/Screen_Recording_20210210-153843_hexa.dev.zip)
1.Not able to enter the OTP while accepting the request 
-This is happening only on android device(Tested on SAMSUNG Galaxy A50)
-It appears very rarely.

2.And when the app is not in the background/foreground and then we click on the deep link, the module is going up while entering the OTP(same for the phone no and email).
3.Happening only in android device version 1.4.4(223)
4.Tested on SAMSUNG Galaxy A50

**Comment by AliMeer** [comment]
Tested this on A50. i was able to enter the OTP.

![IMG_0633](https://user-images.githubusercontent.com/7535475/107560705-9a8bee80-6bd5-11eb-9364-7599c2763814.jpg)

**Comment by AliMeer** [comment]
Not a new issue for this build.
Issue occurs when a dev app deep link is opened by a live app and only when the app is in background.

**Comment by cakesoft-swati** [comment]
-Unable to reproduce this issue on dev app v1.7.5(296)
