### ISSUE TITLE
Restricting sub-account instances

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2702]
Number of instances per sub-accounts:
1. F&F - 20
2. Checking - 5
3. Savings - 5
4. Donation - 5
5. FBTC - 5

**Comment by Parsh** [comment]
Restrictions implemented at the backend, would have to check the restriction logic at the UI.

**Comment by Parsh** [comment]
Upgrade script would be required to change the instance counts for upgraded apps

**Comment by AliMeer** [comment]
is this still required?
