### ISSUE TITLE
Splash screen video text

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2704]
-UX: should the tag line be bigger? Or appear earlier?
- Did not have enough time to read it.
- 
![tagline](https://user-images.githubusercontent.com/62699947/107612232-c8237700-6c6b-11eb-83de-f5b116cecc52.jpg)

**Comment by Arpanjainson** [comment]
https://user-images.githubusercontent.com/8697909/110074887-f1857d80-7da7-11eb-9a2d-d644a8258923.mp4

@antuz123  the size of text "Bitcoin is for everyone" has been increase and the time on screen for the text has been increased.

**Comment by Arpanjainson** [comment]
Review and return if required,

**Comment by cakesoft-swati** [comment]
-Verified this on Dev app v1.5.0(239)
