### ISSUE TITLE
Need the UX with full sync.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2707]
-This is called Manual Sync.
-Need the UX with blind refresh (Full Sync).
![tempFileForShare_20210211-133312](https://user-images.githubusercontent.com/62699947/107613200-d07cb180-6c6d-11eb-835d-99d115082cec.jpg)

**Comment by antuz123** [comment]
"Account sync" = Hard Refresh = Happens at the account level from Account> Settings (Does hard refresh - starting from 0 index - for all sub accounts in the Account) 

"Full Wallet sync" = Blind Refresh = Happens at the wallet level from more> Settings (Does hard refresh for all possible sub accounts) 

Highlights new transactions in both cases

**Comment by antuz123** [comment]
@cakesoft-nikhita @AliMeer

**Comment by Arpanjainson** [comment]
Starts from here  - https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/2e69233c-c9e9-4294-abd6-98587304c55d

**Comment by Arpanjainson** [comment]
@AliMeer  please review the UX

**Comment by antuz123** [comment]
Check with 2547. Seems like a duplicate

**Comment by antuz123** [comment]
- Change the word from "Full Rescan" to "Wallet Manual Sync" 
- Use the proper icon in the UX 
- Use the warning screen like in the Account Sync process 

- In Account Sync, in accounts, the icon is incorrect there too 
- Use the correct icon there too
