### ISSUE TITLE
Description is not required.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2715]
-We don’t need the description here.
![descnoneed](https://user-images.githubusercontent.com/62699947/107627982-0463d100-6c86-11eb-91f0-86cea007a664.jpg)

**Comment by cakesoft-nikhita** [comment]
@AliMeer @antuz123 We can't remove this If we remove this then our App will reject from the App store. We can change this text

**Comment by AliMeer** [comment]
@cakesoft-nikhita I thought so too. Thanks for confirming.

**Comment by antuz123** [comment]
We have already explained it in the previous screen. Just replace the whole text with “Address book details are only stored locally”

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app v1.4.5(228)
