### ISSUE TITLE
UI Changes when adding a new account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2717]
-The title should be empty. Description should be editable but defaulted to ‘User Checking Account’. 
-Applies to Checking and Savings.
![tempFileForShare_20210211-163619](https://user-images.githubusercontent.com/62699947/107628996-77ba1280-6c87-11eb-83e6-27b34018f29f.jpg)

**Comment by AliMeer** [comment]
Part 1 is done.
This part is outstanding:  Description should be editable but defaulted to ‘User Checking Account’ and 'User Savings Account'

**Comment by cakesoft-swati** [comment]
-Part 1 is verified but second part is pending.

**Comment by AliMeer** [comment]
Second part will be done in 1.4.6

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(254)
