### ISSUE TITLE
Buy options are being cut off.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2718]
-More Buying options on Buy Bitcoin are  very lower down on the screen and is being cut off.
![Screenshot_20210211-184654_hexa dev](https://user-images.githubusercontent.com/62699947/107641545-c53f7b00-6c99-11eb-8474-cbe357c7a86a.jpg)

-Tested on both ios and android app v1.4.4(225)

**Comment by AliMeer** [comment]
Fixed in 226

**Comment by cakesoft-swati** [comment]
-Verified this issue on Staging app v1.4.4(226)
