### ISSUE TITLE
Use geographical location to display specific buy options

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2724]
A buy option should be shown only in geographies where it’s available

**Comment by AliMeer** [comment]
Ramp availability: https://support.ramp.network/en/article/what-countries-do-you-support-1ua7sn1/
Wyre NON-availability: https://support.sendwyre.com/en/articles/1863574-geographic-restrictions

**Comment by antuz123** [comment]
We need this for:  
1. When to show Ramp or not 
2. In future we need it for choosing on-ramp
3. User should be able to change it in settings

**Comment by antuz123** [comment]
this will apply to the Buy process and the Add Account process

**Comment by ASN-BitHyve** [comment]
Closing this based on issue #2467
