### ISSUE TITLE
Send and TC Enhancement:  Utilizing a new `AddressBook` structure 

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2735]
Support utilising a new `AddressBook` structure for where we’re organising different kinds of trusted contacts.

https://github.com/bithyve/hexa/compare/feature/send-flow-refactoring#diff-234c270f5e617d5465e01e5cb081d9fa6d037ce5b152c2cf474beec6908390b6R37

FYI @CypherPoet

**Comment by Parsh** [comment]
Would need to have further discussion in order to understand the required changes.

**Comment by AliMeer** [comment]
This has been completed.
