### ISSUE TITLE
Send and TC Enhancement: New signature for the update trusted contact action

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2736]
Support the new signature for the UPDATE_TRUSTED_CONTACTS_INFO action

https://github.com/bithyve/hexa/compare/feature/send-flow-refactoring#diff-234c270f5e617d5465e01e5cb081d9fa6d037ce5b152c2cf474beec6908390b6R218

FYI @CypherPoet

**Comment by Parsh** [comment]
Will require more details.

**Comment by AliMeer** [comment]
This is done. Trusted contacts getting added is a test for this which has been done.
