### ISSUE TITLE
Blind Refresh: 505 form Wrapper

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2750]
Esplora is sending 505 err while doing blind sync(when F&F's are included 40 ext/internal address sets)

**Comment by Varunram** [comment]
Will investigate this

**Comment by Varunram** [comment]
updated rust + wrapper versions. Set timeout to 30s on the wrapper's end to accommodate electrs. Please perform further testing and update this issue, thanks!

**Comment by Parsh** [comment]
I'm not sure whether [this issue](https://github.com/bithyve/hexa/issues/2772) is related to the changes made yesterday or not, however, wrapper is sending the following error: "sendrawtransaction RPC error: {"code":-22,"message":"TX decode failed"}",  when txHex is sent to the broadcasting endpoint(https://testapi.bithyve.com/tx)

**Comment by Parsh** [comment]
Just confirming: Blind sync has started to work perfectly post timeout extension.
