### ISSUE TITLE
UI changes on Ramp account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2751]
-This screen needs to be more about just a message with Account details at the bottom. The user can’t change it. May be more like a half screen/ modal. This is very intrusive for the buy process. We already have a message screen after this.
![rampacc](https://user-images.githubusercontent.com/62699947/108189981-5cdc1800-7137-11eb-98a8-917abe3665be.jpg)

**Comment by AliMeer** [comment]
- Changed this to be more like the order form with a similar note as the buy order form.
- There is no other screen after this, clicking on proceed to Ramp will take the user to Ramp
- Added powered by ramp
- I think the name should be specified but it should still be editable like it is for all accounts.

**Comment by cakesoft-swati** [comment]
-Verified this on staging app v1.4.5(228)

**Comment by cakesoft-swati** [comment]
- It should be like a half screen/ modal.

**Comment by cakesoft-swati** [comment]
- "Proceed to Ramp" button is coming over  the text in iphone 7.
 - Tested on Dev app version 1.4.5(230) 
 
![IMG_1558](https://user-images.githubusercontent.com/62699947/108666182-8eb8fa00-74fc-11eb-8488-8b533296e1e5.PNG)

**Comment by antuz123** [comment]
@cakesoft-swati - which other device is it on?

**Comment by AliMeer** [comment]
Fixed for 1.4.6

**Comment by cakesoft-swati** [comment]
-Verified this on staging app v 1.4.6(231).
-This was only on iphone 7.
