### ISSUE TITLE
Swan UX

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2756]
Buy with Swan
Swan has payment integration similar to Fast bitcoin. User registers with Swan and then is presented with payment details to which he needs to make incremental payments and the sats are delivered.

**UX**
Add Swan as service - takes the used to Swan to authenticate, which is a custom page on Swan with Hexa branding.
User authenticates on swan side and is presented with two options - to go back to hexa using a deep link or copy the code and paste it on hexa.
On the Hexa side - at step 1 when the user clicked to integrate with Swan, the app presents a screen similar to below with steps like
authenticating..
Processing..
Failed.. with ticks and cross.
And the payment details like bank account, IBAN swift code etc.
If the return to the app via deep link is successful then all steps will show as ticked and the user can click OK and then will be directed to the Swan account home page.
In case the deep link does not work then on the initiating/status screen in the app there will be a CTA enter the Swan code - once the user enters the code he is presented with success message with the payment details - handle failure message.
The settings on Swan account should have an option to view the payment details.

**Comment by AliMeer** [comment]
Proto: https://xd.adobe.com/view/3db366dc-fc84-4167-ad12-e8a8cd27034c-68e0/

Specs: https://xd.adobe.com/view/91d3b24d-96da-420e-adc7-a7115884db1c-c480/screen/c67130ae-00cc-49d6-ad36-e207eb6ff096

**Comment by cakesoft-devika** [comment]
- Verified this ticket on Dev app v1.7.0 (289)
