### ISSUE TITLE
UI issues on "Add New Accounts"screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2766]
-The word account and the number 2 is getting cut.
![File (29)](https://user-images.githubusercontent.com/62699947/108461656-1acee580-72a1-11eb-9c1f-7d82324846f3.jpg)

-The word custody is getting cut
![File (30)](https://user-images.githubusercontent.com/62699947/108461696-2b7f5b80-72a1-11eb-91a1-a72088e0a293.jpg)

**Comment by AliMeer** [comment]
Are these issues new? I think this screen and the displayed names have always been this way.
