### ISSUE TITLE
"Available to spend" is missing on Ramp account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2769]
- All other accounts have "Available to spend". Not seeing it here.
 - Also "Available to Spend" > "Available to spend" across all accounts.

![Screenshot_20210218-164237_Chrome](https://user-images.githubusercontent.com/62699947/108462653-01c73400-72a3-11eb-8f9f-f2449c863a3c.jpg)

**Comment by AliMeer** [comment]
Cannot reproduce. Available to spend is visible, tested in build 218 and 219. The screen shot above is from UX design.

**Comment by cakesoft-swati** [comment]
-Not able to reproduce this on dev app v1.5.0(250)
