### ISSUE TITLE
Ramp Buy User Journey

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2771]
Changes to Buy Screen/Buy Form used in Ramp option from "Buy Button" 

- Change screen to be a modal similar to other modals on the home screen.
- The user info note should be displayed as normal text in the modal.
- Mention the account name as part of the text instead of displaying as a separate visual element.
- Mention bitcoin receiving address as part of the text.
- Proceed button with "powered by ramp" should be in modal.

**Comment by cakesoft-swati** [comment]
-Verified this issue on Staging app v1.4.5(230)
