### ISSUE TITLE
Transaction not showing in Checking account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2778]
-I have upgraded staging app from 1.4.4(226) >1.4.5(227)> v1.4.5(228)>1.4.5(230).
-Also having upgarded live app from 1.4.4(226) to latest 1.4.5(230).
-Both the apps(staging and live) are connected to own node.
-I tried to send some sats to the another Hexa account.I have a confirmation that the sats was sent, but it still hasn’t recorded in my account.
-I also tried to send to the savings account (within the app).but again I got the confirmation but it did not appear in the txn list.
-Also the fees are different.(#2773 )
-The Manage Backup page is continuously loading on Android device(A50).
-The overall balance is also not decreasing. 
-In between these upgrades I did a restore and I also tested the node settings myself.
-And now my sats are stuck.I can do a whole send procedure but it doesn't showing that txn in transaction list.

**Comment by Parsh** [comment]
Seems to be connected w/ the following issue: https://github.com/bithyve/hexa/issues/2772

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app v1.5.0(260)
