### ISSUE TITLE
MH6: Option to backup wallet on cloud - new account  MH6

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2780]
During the new wallet creation flow the user will be presented with an option to upload wallet back up on the cloud

If the user does not select the option at wallet creation then the backup will be at Level-1 but Red.
If the user selected then automatically the backup will be uploaded to the cloud account for the user.

**Comment by Arpanjainson** [comment]
@antuz123  - I think we should present this option after the Q&A step as part of new wallet creation. Please comment.

**Comment by Arpanjainson** [comment]
Store wallet backup in iCloud drive?
The wallet backup will be encrypted using the answer to your question. 
@antuz123 please review

**Comment by Arpanjainson** [comment]
Backup wallet on cloud latest screen
https://xd.adobe.com/view/7636e956-af9b-4300-bc63-4c3eab0d4f71-2365/screen/482e3b2f-6949-451b-a7c6-a3756606943e/

**Comment by Arpanjainson** [comment]
Latest screen  https://xd.adobe.com/view/a2211587-164a-47be-9d67-85811bb511ea-f772/
Refer to screen number 1-5
@AliMeer 
Some more changes are expected and this is not final.

**Comment by AliMeer** [comment]
@antuz123 We have added the cloud opt-out option in the current dev release. Should we change it? 
Here the cloud opt out option is shown on home screen, but we are supposed to start cloud backup before we land on the home screen.
Can the user pull down the bottom sheet to dismiss it without clicking Backup or skip? Does this mean we dont backup to cloud?

**Comment by antuz123** [comment]
@AliMeer - in screen number 4, the background screen is incorrect. It should be when we ask for opt out pre HS.

**Comment by AliMeer** [comment]
We currentl use a checkbox for cloud opt out selection.
We need to use a bottom sheet instead as shown in screen: 
1.1 Login & Errors Specs: Home – Backup (Please note the background shows Home screen which is wrong, it should be the wallet name screen in the background)

**Comment by ASN-BitHyve** [comment]
Shivani Here's sharing the proto link with the text updated. https://xd.adobe.com/view/525a1912-c20b-444d-8025-cc68255488b8-0709/screen/8a7ccbc6-66d2-477a-a189-638250d80ec0

**Comment by cakesoft-devika** [comment]
-Verified this issue on Staging app v1.6.5(281)
