### ISSUE TITLE
New BHR Level 1 Fresh: Fresh Install

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2797]
BHR1’.2.
The user lands on the Home Screen with the health status at Level 1 with the default accounts. [same as Old BHR, in Keeper BHR Savings Account is inactive]

A. Fresh Install Scenario

Changes Required:
- Remove  the primary keeper dependency in KBHR for savings account secondary mnemonic creation.
- Use savings account creation code from OBHR.
- All defaults account available on Home Screen.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(243)
