### ISSUE TITLE
New screens receive screen

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2801]
Refer to this spec link
New Receive  https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/screen/37317854-6c72-4dd9-b17f-edb97b68f3c3/
Share with friends and family
https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/screen/e1e01642-afff-4e96-b574-365af7069685/
after sharing once the user returns to the app show the 
modal with email if  message was encrypted using email - https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/screen/4296ace8-09d9-4602-af65-c6bf3aa94af5/
Handle for phone.
We already have one for OTP.

**Comment by Arpanjainson** [comment]
For Receive screen please do not put the settings icon  - its future ux

Once the recovery key etc is shared say by email/phone a screen confirming receivers email/phone needs to be presented same as OTP flow.

**Comment by Arpanjainson** [comment]
https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/screen/6c3f1c0b-d7bf-45fd-883c-4cb2e8f83ed9/
Recovery Secrets – Trusted Contacts – Request Share
Recovery Secrets – Trusted Contacts – Request Share – 1
Recovery Secrets – Trusted Contacts – Request Share – Message shared with trusted contact – Email
Recovery Secrets – Trusted Contacts – Request Share – Message shared with trusted contact – Phone

**Comment by Arpanjainson** [comment]
Latest screens
https://xd.adobe.com/view/7636e956-af9b-4300-bc63-4c3eab0d4f71-2365/screen/538324fe-2358-4d10-939f-86c872b151a3/
Request Share
Request Share – Share
Request Share – OTP
Request Share – Copied Successfully Toast
Request Share – Message shared with trusted contact – Email
 Request Share – Message shared with trusted contact – Phone
 Accounts – Receive
 Accounts – Receive – Enter Amount

**Comment by antuz123** [comment]
https://xd.adobe.com/view/3df97271-f272-4dae-975d-95d4785f1b30-68aa/

**Comment by Arpanjainson** [comment]
Latest Receive screen with content are under https://xd.adobe.com/view/321e13db-60d2-4034-b47b-fbcdb7803dd7-674d/
Accounts – Receive
Accounts – Receive – Enter Amount

**Comment by Arpanjainson** [comment]
@cakesoft-shivani  I do not see the latest receive screen in the 254 version
https://xd.adobe.com/view/321e13db-60d2-4034-b47b-fbcdb7803dd7-674d/

**Comment by cakesoft-nikhita** [comment]
@Arpanjainson This change is completed for the Home screen QR. @AliMeer Is we need to change our current Recieve flow also? If yes then there is contact selection flow in the Current scenario so we need to remove that? We need to change our whole current Receive flow

**Comment by antuz123** [comment]
@cakesoft-nikhita - pls split the issues in different issues

**Comment by cakesoft-devika** [comment]
-Verified "HS Receive" and "Accounts Receive" on Staging app v1.6.5(281)
