### ISSUE TITLE
Revisit Ramp & Wyre flow UX edits

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2802]
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/77cb554b-4047-4a5a-97b6-10e809d0437a

Look for corresponding screens in the XD link
Home – Add New – Ramp Selected
Add – Ramp Account – Details
Ramp Account
Wyre account
 https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/4ea71c58-e297-4194-8b7e-19b39f64c437

**Comment by Arpanjainson** [comment]
Dev- do not add "saved transactions" to the screen - it is a future feature

**Comment by Arpanjainson** [comment]
the reviewed updated flow with screens is on this spec
review the logos, the car color, flow etc.
https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/screen/37317854-6c72-4dd9-b17f-edb97b68f3c3/

**Comment by AliMeer** [comment]
Update Ramp buy modal to add account and address icon.

https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/
