### ISSUE TITLE
No transactions available -UX

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2804]
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/6dab2856-7f40-4b34-8db2-4bbb8483018f
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/731d1efe-6b29-4ac3-88a3-aa8dd65d8a5e
Transactions – No transactions
Accounts – Secure – No Transactions

**Comment by Arpanjainson** [comment]
DEv- do not put saved transactions.

Message to read confirmed/unconfirmed transactions.

**Comment by AliMeer** [comment]
Is this a new requirement or a requirement that was not implemented?

**Comment by antuz123** [comment]
Old requirement that was not implemented. But not needed anymore either
