### ISSUE TITLE
New BHR: include secondary mnemonic 

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2809]
MH2’
6. Along with other data to be sent to the two Keepers, the second Recovery Key is also sent to the Keepers (of the 2 of 3 SSS scheme) [Same as KBHR but the Secondary Mnemonic and 2FA secret are also sent to the Keepers like in OBHR]

- Use current(OBHR) code to include secondary mnemonic and 2FA secret as part of recovery key.

**Comment by cakesoft-shivani** [comment]
1) Create Metashares for Secondary Mnemonics (SM) [DONE]
2) Share SM share with
    contact [DONE]
    device [DONE]
    pdf [DONE]
3) Upload SM share from 
    contact [DONE]
    device [DONE]
    pdf [DONE]
4) Scan and download Sm share for approval for level 3 from
    contact 
    device 
    pdf
5) Scan and download SM share for 2FA reset
6) Scan and download Sm share for approval for change keeper from
    contact 
    device 
    pdf
7) Delete Sm and Sm share from hexa and wallet image after level 2 completion [DONE]
