### ISSUE TITLE
New BHR: Restore NBHR to NBHR

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2811]
RF3’
Please refer https://trello.com/c/LmKaWddX

The old and the new app both are with NBHR

Same as KBHR with changes for newBHR as below:
- [question used by user should be shown and not a list of questions]
- if restore is on same platform read the cloud recover key automatically.
- Once reading the cloud recovery key extract the details of remaining recovery keys
- User is given an option to Scan Recovery Key (for any Keeper) or send Recovery Request (to Friends and Family Keeper)
[The whole flow is same as KBHR without the checks needed for PK for enabling Savings Account etc.]

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(243)
