### ISSUE TITLE
Text for all screens in new BHR

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2813]
Abhilash is working on them

**Comment by antuz123** [comment]
Expect it in the later part of the week.

**Comment by AliMeer** [comment]
Link to xd files with content: https://xd.adobe.com/view/33e15a26-1ad4-4bff-4ceb-4b3ef0a29a7d-45d0/grid

**Comment by antuz123** [comment]
Only spec link is what devs should use. The proto link is for internal UX and content.

**Comment by AliMeer** [comment]
https://xd.adobe.com/view/33e15a26-1ad4-4bff-4ceb-4b3ef0a29a7d-45d0/grid/

Backup and Health: Image 18 to 66

Upgrade: Image 88 to 106

**Comment by Arpanjainson** [comment]
This is not the correct link - will update once UX team sends that.

**Comment by cakesoft-devika** [comment]
-Verified this issue on Staging app v1.6.5(281)
