### ISSUE TITLE
UI changes on Know more screens.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2815]
-When we press this button, it goes to the next screen, but the last line in the second paragraph is getting cut.
- Need to arrange the screen/text so that
 1. It is completely visible
  2. There is enough margin space left on top and bottom.
![tempFileForShare_20210225-213642](https://user-images.githubusercontent.com/62699947/109492473-0f559880-7ab1-11eb-9901-0a95cd2945bc.jpg)

**Comment by AliMeer** [comment]
I have already fixed this

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(250)
