### ISSUE TITLE
Rotation direction of arrows is not  fixed.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2816]
-The rotation direction of these arrows hasn't been fixed.
![tempFileForShare_20210222-205203](https://user-images.githubusercontent.com/62699947/109493190-221c9d00-7ab2-11eb-8486-6e9c094f39cd.jpg)

**Comment by AliMeer** [comment]
Good catch 👍

**Comment by cakesoft-swati** [comment]
-Verified these changes on Dev app v1.4.6(232).
-Now the direction of arrows is fixed.It is moving in anti-clockwise direction.
