### ISSUE TITLE
Send screen UI changes

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#2817]
![Send Screenshot](https://user-images.githubusercontent.com/68264080/109493185-20eb7000-7ab2-11eb-975d-aefbd8034c18.jpg)

Couple of changes required on this screen:
1) The QR code image is stuck to the header. We need to lower it a little, giving appropriate spacing between header and that image.
2) Enter Address Manually > Enter address manually
3) Send to Accounts > Send to account 
4) In the Ramp account section, Zero is a little higher than the word "sats". The number and sats should be aligned. 
5) Send To Contacts > Send to contact

**Comment by Arpanjainson** [comment]
@antuz123 not sure why this is UX - should be a dev task looking at the latest screens

**Comment by cakesoft-swati** [comment]
-Verified these changes in dev app v1.5.0(254)
