### ISSUE TITLE
Changes on "Buy Bitcoin" model.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2818]
1. Low fee for those big buys.
 2. Remove coming soon.
 3. Wyre is first Ramp is second.
 
<img width="375" alt="51FCD061-5F97-4781-AD01-19E88D00C6E7" src="https://user-images.githubusercontent.com/62699947/109502512-17b4d000-7abf-11eb-810e-ba2b1698bb82.png">

**Comment by AliMeer** [comment]
@antuz123 
for this release, Wyre is first Ramp is second, so is FBTC 3rd and Swan fourth?

**Comment by cakesoft-swati** [comment]
-Verified these changes on Dev app v1.4.6(232)
