### ISSUE TITLE
Send Flow: Amount & SendMax Error

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2823]
- Amount is not being set accurately, 2000 sats get converted into 20 sats.

![Simulator Screen Shot - iPhone 11 - 2021-03-02 at 12 24 38](https://user-images.githubusercontent.com/17980466/109610097-4d56c900-7b52-11eb-9da4-f4a5b0a3d5a9.png)
![Simulator Screen Shot - iPhone 11 - 2021-03-02 at 12 24 44](https://user-images.githubusercontent.com/17980466/109610109-4fb92300-7b52-11eb-920d-b58232b5464b.png)

- Send max value isn't getting updated in the input box even after sendMaxFee is available 

<img width="1440" alt="Screenshot 2021-03-02 at 5 44 29 PM" src="https://user-images.githubusercontent.com/17980466/109647680-97a26f00-7b7f-11eb-8d66-58eb1601ec11.png">

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(245)
