### ISSUE TITLE
Batch send failing

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2824]
Send is failing in the case of multiple recipients. Probably because the amount is missing for the recipient added initially.

<img width="1440" alt="Screenshot 2021-03-02 at 12 21 49 PM" src="https://user-images.githubusercontent.com/17980466/109610263-898a2980-7b52-11eb-9fb5-3b0e34a405c0.png">
<img width="1440" alt="Screenshot 2021-03-02 at 12 22 05 PM" src="https://user-images.githubusercontent.com/17980466/109610281-9018a100-7b52-11eb-9ea5-6bfbc56a648e.png">

**Comment by cakesoft-swati** [comment]
-Batch send is still failing.
-Tested on dev app v1.5.0(245)
![Screenshot_20210318-183156_hexa dev](https://user-images.githubusercontent.com/62699947/111630408-57e2b500-8818-11eb-8413-8a12123b9c69.jpg)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(249)
