### ISSUE TITLE
Remove white horizontal lines from all know more sheets

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2826]
Makes sure there are no white lines on any of the know more sheets

![Screenshot 2021-03-02 at 12 21 59](https://user-images.githubusercontent.com/7535475/109648229-4af46f00-7b52-11eb-85a3-a0f9083d8f0a.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.6(232)
