### ISSUE TITLE
Custom priority send: Err display

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2827]
Have done most of the custom priority tx integration, however, I wasn't able to update the error(if saga throws any) on the bottomsheet.

<img width="1440" alt="Screenshot 2021-03-02 at 5 47 19 PM" src="https://user-images.githubusercontent.com/17980466/109648078-2b743b00-7b80-11eb-9d1a-6f978c7f847f.png">

Following is what I've done to propagate the error(customPriorityErr) to the bottomsheet, however, it's not updating anyway. Maybe you'll be able to better judge why it's not re-rendering that bottomsheet.
<img width="1440" alt="Screenshot 2021-03-02 at 5 58 27 PM" src="https://user-images.githubusercontent.com/17980466/109648911-31b6e700-7b81-11eb-947f-c88d8224000a.png">
<img width="1440" alt="Screenshot 2021-03-02 at 5 58 38 PM" src="https://user-images.githubusercontent.com/17980466/109648931-37143180-7b81-11eb-834a-798f797494b2.png">

**Comment by cakesoft-swati** [comment]
-Verified thid issue on dev app v1.5.0(243)
