### ISSUE TITLE
Send and Receive Option from Scanner Screen

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2829]
Have send and receive options on scanner screen.

Current scanner screen can scan and send but doesn't have option to (1) generate a QR to receive and (2) to enter a address to send

1. New Scanner Screen: This screen is accessed from Home bottom tab bar.

if user enters a bitcoin address here the validation should be done as other screens and on validation the user should be taken to send screen for the default checking account.

If user clicks on receive the receive screen should be shown(see point 2 below)

https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/4083bda1-19e0-40b5-bea4-b9b8f048f893/

![Screenshot 2021-03-02 at 19 17 32](https://user-images.githubusercontent.com/7535475/109702927-c8d56c00-7b8c-11eb-9319-5735ee2b387a.png)

2. New receive screen:

https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/screen/ac4b8d15-390a-4c6a-86eb-8852b3caae89/specs/

![Screenshot 2021-03-02 at 19 18 57](https://user-images.githubusercontent.com/7535475/109702749-8dd33880-7b8c-11eb-933e-907b5e1ef942.png)

3. Enter amount bottom sheet:

https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/screen/37317854-6c72-4dd9-b17f-edb97b68f3c3/specs/

![Screenshot 2021-03-02 at 19 24 53](https://user-images.githubusercontent.com/7535475/109703585-8bbda980-7b8d-11eb-8d1f-0e1faf4bae4a.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app version 1.4.6(233)
