### ISSUE TITLE
Enhance buy modal for Ramp and Wyre

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2830]
Current modals displayed when clicking on Wyre or Ramp option from Buy Button need to be updated with new UI elements.

https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/screen/ad6e34aa-39a2-4842-b182-7a53e8de924d/specs/

![Screenshot 2021-03-02 at 19 46 13](https://user-images.githubusercontent.com/7535475/109705748-01c31000-7b90-11eb-8263-89ce4b0c0815.png)

**Comment by CypherPoet** [comment]
#3008 has some of the initial changes for this. However, as noted in the discussion [here](https://bithyve-workspace.slack.com/archives/CEBLWDEKH/p1616592822026700), we still need new image assets for the Ramp, Wyre, and Account circles shown in the latest specs (cc @Arpanjainson @antuz123 @AliMeer)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(250)
