### ISSUE TITLE
Localisation settings UI

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2831]
Change currency option in settings to Currency and Language.

Currency and Language screen with Country, Currency and Language option

https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/screen/49efc643-9a36-4ea9-adae-454ca7723a5d/specs/

https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/screen/85899a9e-fcc6-43a6-bba3-d9cd4c6480e7/specs/

https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/screen/ef2acb01-1f72-49cf-a0d9-30810fa8d0c4/specs/

![Screenshot 2021-03-02 at 19 54 14](https://user-images.githubusercontent.com/7535475/109706829-561abf80-7b91-11eb-99f6-445bfff170a9.png)  ![Screenshot 2021-03-02 at 19 56 44](https://user-images.githubusercontent.com/7535475/109706917-7185ca80-7b91-11eb-8f82-82fa8aeca2ba.png).  ![Screenshot 2021-03-02 at 19 57 52](https://user-images.githubusercontent.com/7535475/109707043-9aa65b00-7b91-11eb-900e-eacbf5b59e1a.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.01(375)
