### ISSUE TITLE
"2FA" Flow Changes.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2835]
- Put the setup 2FA flow in both Send, Receive and WebView (2FA Donation Account) instead of on the main screen.
 - Put an option in the Account Settings to SetUp 2FA which works till you are on Level 1. After that it gets greyed out.

**Comment by antuz123** [comment]
@cakesoft-swati - not sure I understand this one

**Comment by AliMeer** [comment]
@antuz123 is this a requirement?
