### ISSUE TITLE
Textual change for Donation account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2846]
- The sub title should be:- Accept donations.
![tempFileForShare_20210303-212625](https://user-images.githubusercontent.com/62699947/109951714-0c061b00-7d04-11eb-9cfe-741a1898ee75.jpg)

-

**Comment by AliMeer** [comment]
Bought it forward to 1.4.6

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.4.6(233)
