### ISSUE TITLE
Textual change on Ramp account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2847]
- Sub title should be - “Buy with ApplePay, Bank or Card”
![tempFileForShare_20210303-223537](https://user-images.githubusercontent.com/62699947/109952176-8cc51700-7d04-11eb-8748-587402662ed0.jpg)

-"Account Details" > "Setup Ramp Account"
![tempFileForShare_20210303-225247](https://user-images.githubusercontent.com/62699947/109952429-d281df80-7d04-11eb-9e3f-c158c0e4dcd0.jpg)

**Comment by AliMeer** [comment]
@antuz123 would it be better to use “BTC purchased from Ramp” as the account description?

**Comment by cakesoft-swati** [comment]
-Verified this on Dev app v 1.4.6(233)
