### ISSUE TITLE
Review Floating Buy button

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2851]
Review how the floating buy button should look on different screen sizes and decide the UI i.e. size and poistion of button depending on the screen size.

**Comment by Arpanjainson** [comment]
https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/screen/be9add79-7dfd-440f-a975-e2d856273c91/
https://xd.adobe.com/view/35f7d5d7-6dd0-44e8-91c3-8ea30c6994b4-60a4/screen/3e5a1098-2bfa-47f8-bd19-4178ae4dd116/
@AliMeer  please review

**Comment by AliMeer** [comment]
@antuz123 What exactly needs to be done here?

**Comment by antuz123** [comment]
@Arpanjainson - the issue does not mention anything. Can you pls explain the issue?

**Comment by Arpanjainson** [comment]
Updated comment

**Comment by AliMeer** [comment]
@antuz123 now that we have a new UX for home screen do we still need this?
