### ISSUE TITLE
Console errors when going to Manage Backup

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2857]
Errors in logs when navigating to Manage Backup need to be investigated and resolved.
These are probably impacting performance to some degree.

[Fri Mar 05 2021 20:24:59.440]  ERROR    Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ManageBackup`. See https://fb.me/react-warning-keys for more information.
    in View (at ManageBackup/index.tsx:1765)
    in ManageBackup (created by SceneView)
    in SceneView (at StackViewLayout.tsx:900)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at StackViewCard.tsx:106)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.js:94)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:975)
    in RCTView (at View.js:34)
    in View (at src/index.native.js:123)
    in ScreenContainer (at StackViewLayout.tsx:384)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at StackViewLayout.tsx:374)
    in PanGestureHandler (at StackViewLayout.tsx:367)
    in StackViewLayout (created by withOrientation)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at View.js:34)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (created by Navigator)
    in Navigator (created by KeyboardAwareNavigator)
    in KeyboardAwareNavigator (created by SceneView)
    in SceneView (created by SwitchView)
    in SwitchView (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (at App.tsx:129)
    in AppContent (at App.tsx:51)
    in BottomSheetModalProviderWrapper (at App.tsx:50)
    in Provider (at App.tsx:49)
    in AppWrapper (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in ChildrenWrapper (at wrapRootComponent.js:9)
    in _default (at wrapRootComponent.js:8)
    in Root (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Fri Mar 05 2021 20:24:59.179]  ERROR    Warning: Each child in a list should have a unique "key" prop.

Check the render method of `RegenerateHealper`. See https://fb.me/react-warning-keys for more information.
    in View (at RegenerateHealper.tsx:35)
    in RegenerateHealper (at ManageBackup/index.tsx:246)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:240)
    in AnimatedComponent(View) (created by TapGestureHandler)
    in TapGestureHandler (created by BottomSheetBehavior)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:240)
    in AnimatedComponent(View) (created by PanGestureHandler)
    in PanGestureHandler (created by BottomSheetBehavior)
    in RCTView (at View.js:34)
    in View (created by BottomSheetBehavior)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:240)
    in AnimatedComponent(View) (created by BottomSheetBehavior)
    in BottomSheetBehavior (at ManageBackup/index.tsx:1926)
    in RCTView (at View.js:34)
    in View (at ManageBackup/index.tsx:1689)
    in RCTView (at View.js:34)
    in View (at ManageBackup/index.tsx:1666)
    in RCTView (at View.js:34)
    in View (at ManageBackup/index.tsx:1659)
    in ManageBackup (created by SceneView)
    in SceneView (at StackViewLayout.tsx:900)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at StackViewCard.tsx:106)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.js:94)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:975)
    in RCTView (at View.js:34)
    in View (at src/index.native.js:123)
    in ScreenContainer (at StackViewLayout.tsx:384)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at StackViewLayout.tsx:374)
    in PanGestureHandler (at StackViewLayout.tsx:367)
    in StackViewLayout (created by withOrientation)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at View.js:34)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (created by Navigator)
    in Navigator (created by KeyboardAwareNavigator)
    in KeyboardAwareNavigator (created by SceneView)
    in SceneView (created by SwitchView)
    in SwitchView (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (at App.tsx:129)
    in AppContent (at App.tsx:51)
    in BottomSheetModalProviderWrapper (at App.tsx:50)
    in Provider (at App.tsx:49)
    in AppWrapper (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in ChildrenWrapper (at wrapRootComponent.js:9)
    in _default (at wrapRootComponent.js:8)
    in Root (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Fri Mar 05 2021 20:24:59.280]  ERROR    Warning: Each child in a list should have a unique "key" prop.

Check the render method of `SecondaryDeviceHealthCheck`. See https://fb.me/react-warning-keys for more information.
    in AppBottomSheetTouchableWrapper (at SecondaryDeviceHealthCheck.tsx:106)
    in SecondaryDeviceHealthCheck (at ManageBackup/index.tsx:278)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:240)
    in AnimatedComponent(View) (created by TapGestureHandler)
    in TapGestureHandler (created by BottomSheetBehavior)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:240)
    in AnimatedComponent(View) (created by PanGestureHandler)
    in PanGestureHandler (created by BottomSheetBehavior)
    in RCTView (at View.js:34)
    in View (created by BottomSheetBehavior)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:240)
    in AnimatedComponent(View) (created by BottomSheetBehavior)
    in BottomSheetBehavior (at ManageBackup/index.tsx:1940)
    in RCTView (at View.js:34)
    in View (at ManageBackup/index.tsx:1689)
    in RCTView (at View.js:34)
    in View (at ManageBackup/index.tsx:1666)
    in RCTView (at View.js:34)
    in View (at ManageBackup/index.tsx:1659)
    in ManageBackup (created by SceneView)
    in SceneView (at StackViewLayout.tsx:900)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at StackViewCard.tsx:106)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.js:94)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:975)
    in RCTView (at View.js:34)
    in View (at src/index.native.js:123)
    in ScreenContainer (at StackViewLayout.tsx:384)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at StackViewLayout.tsx:374)
    in PanGestureHandler (at StackViewLayout.tsx:367)
    in StackViewLayout (created by withOrientation)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at View.js:34)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (created by Navigator)
    in Navigator (created by KeyboardAwareNavigator)
    in KeyboardAwareNavigator (created by SceneView)
    in SceneView (created by SwitchView)
    in SwitchView (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (at App.tsx:129)
    in AppContent (at App.tsx:51)
    in BottomSheetModalProviderWrapper (at App.tsx:50)
    in Provider (at App.tsx:49)
    in AppWrapper (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in ChildrenWrapper (at wrapRootComponent.js:9)
    in _default (at wrapRootComponent.js:8)
    in Root (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

**Comment by AliMeer** [comment]
We need to check if these are still occuring.

**Comment by cakesoft-utkarsh** [comment]
Did not observe any log by react-native while going to Manage backup. All the logs printed are manual logs.
Can we mark this closed now?

**Comment by cakesoft-utkarsh** [comment]
Closing this.
