### ISSUE TITLE
Console errors when Navigating to specific keepers in Manage Backup

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2858]
Development branch, need to verify in NewBHR branch as well.

Errors when navigating to keeper from Manage Backup screen. These are another cause of performance degradation.

[Fri Mar 05 2021 21:03:52.808]  LOG      {"tcInstance": undefined}
[Fri Mar 05 2021 21:03:56.350]  ERROR    Warning: Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"131775":{"module":"ReanimatedModule","method":"getValue"},"131785":{},"131796":{"module":"ReanimatedModule","method":"getValue"},"131808":{"module":"ReanimatedModule","method":"getValue"},"131812":{"module":"ReanimatedModule","method":"getValue"},"131817":{"module":"ReanimatedModule","method":"getValue"},"131836":{"module":"ReanimatedModule","method":"getValue"},"131847":{"module":"ReanimatedModule","method":"getValue"},"131869":{"module":"ReanimatedModule","method":"getValue"},"131876":{"module":"ReanimatedModule","method":"getValue"},"131906":{"module":"ReanimatedModule","method":"getValue"},"131932":{"module":"ReanimatedModule","method":"getValue"},"131976":{"module":"ReanimatedModule","method":"getValue"},"132016":{"module":"ReanimatedModule","method":"getValue"},"132019":{"module":"ReanimatedModule","method":"getValue"},"132033":{"module":"ReanimatedModule","method":"getValue"},"132063":{"module":"ReanimatedModule","method":"getValue"},"132112":{},"132144":{"module":"ReanimatedModule","method":"getValue"},"132157":{"module":"ReanimatedModule","method":"getValue"},"132174":{"module":"ReanimatedModule","method":"getValue"},"132179":{"module":"ReanimatedModule","method":"getValue"},"132182":{"module":"ReanimatedModule","method":"getValue"},"132210":{"module":"ReanimatedModule","method":"getValue"},"132223":{"module":"ReanimatedModule","method":"getValue"},"132236":{"module":"ReanimatedModule","method":"getValue"},"132264":{"module":"ReanimatedModule","method":"getValue"},"132267":{"module":"ReanimatedModule","method":"getValue"},"132277":{"module":"ReanimatedModule","method":"getValue"},"132283":{"module":"ReanimatedModule","method":"getValue"},"132351":{"module":"ReanimatedModule","method":"getValue"},"132358":{"module":"ReanimatedModule","method":"getValue"},"132364":{"module":"ReanimatedModule","method":"getValue"},"132368":{"module":"ReanimatedModule","method":"getValue"},"132375":{"module":"ReanimatedModule","method":"getValue"},"132379":{"module":"ReanimatedModule","method":"getValue"},"132382":{"module":"ReanimatedModule","method":"getValue"},"132427":{"module":"ReanimatedModule","method":"getValue"},"132433":{"module":"ReanimatedModule","method":"getValue"},"132445":{"module":"ReanimatedModule","method":"getValue"},"132449":{"module":"ReanimatedModule","method":"getValue"},"132468":{"module":"ReanimatedModule","method":"getValue"},"132480":{"module":"ReanimatedModule","method":"getValue"},"132484":{"module":"ReanimatedModule","method":"getValue"},"132489":{"module":"ReanimatedModule","method":"getValue"},"132508":{"module":"ReanimatedModule","method":"getValue"},"132519":{"module":"ReanimatedModule","method":"getValue"},"132531":{"module":"ReanimatedModule","method":"getValue"},"132550":{"module":"ReanimatedModule","method":"getValue"},"132565":{"module":"ReanimatedModule","method":"getValue"},"...(truncated keys)...":451} 

**[Fri Mar 05 2021 21:03:56.440]  ERROR    Warning: Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"131775":{"module":"ReanimatedModule","method":"getValue"},"131785":{},"131796":{"module":"ReanimatedModule","method":"getValue"},"131808":{"module":"ReanimatedModule","method":"getValue"},"131812":{"module":"ReanimatedModule","method":"getValue"},"131817":{"module":"ReanimatedModule","method":"getValue"},"131836":{"module":"ReanimatedModule","method":"getValue"},"131847":{"module":"ReanimatedModule","method":"getValue"},"131869":{"module":"ReanimatedModule","method":"getValue"},"131876":{"module":"ReanimatedModule","method":"getValue"},"131906":{"module":"ReanimatedModule","method":"getValue"},"131932":{"module":"ReanimatedModule","method":"getValue"},"131976":{"module":"ReanimatedModule","method":"getValue"},"132016":{"module":"ReanimatedModule","method":"getValue"},"132019":{"module":"ReanimatedModule","method":"getValue"},"132033":{"module":"ReanimatedModule","method":"getValue"},"132063":{"module":"ReanimatedModule","method":"getValue"},"132112":{},"132144":{"module":"ReanimatedModule","method":"getValue"},"132157":{"module":"ReanimatedModule","method":"getValue"},"132174":{"module":"ReanimatedModule","method":"getValue"},"132179":{"module":"ReanimatedModule","method":"getValue"},"132182":{"module":"ReanimatedModule","method":"getValue"},"132210":{"module":"ReanimatedModule","method":"getValue"},"132223":{"module":"ReanimatedModule","method":"getValue"},"132236":{"module":"ReanimatedModule","method":"getValue"},"132264":{"module":"ReanimatedModule","method":"getValue"},"132267":{"module":"ReanimatedModule","method":"getValue"},"132277":{"module":"ReanimatedModule","method":"getValue"},"132283":{"module":"ReanimatedModule","method":"getValue"},"132351":{"module":"ReanimatedModule","method":"getValue"},"132358":{"module":"ReanimatedModule","method":"getValue"},"132364":{"module":"ReanimatedModule","method":"getValue"},"132368":{"module":"ReanimatedModule","method":"getValue"},"132375":{"module":"ReanimatedModule","method":"getValue"},"132379":{"module":"ReanimatedModule","method":"getValue"},"132382":{"module":"ReanimatedModule","method":"getValue"},"132427":{"module":"ReanimatedModule","method":"getValue"},"132433":{"module":"ReanimatedModule","method":"getValue"},"132445":{"module":"ReanimatedModule","method":"getValue"},"132449":{"module":"ReanimatedModule","method":"getValue"},"132468":{"module":"ReanimatedModule","method":"getValue"},"132480":{"module":"ReanimatedModule","method":"getValue"},"132484":{"module":"ReanimatedModule","method":"getValue"},"132489":{"module":"ReanimatedModule","method":"getValue"},"132508":{"module":"ReanimatedModule","method":"getValue"},"132519":{"module":"ReanimatedModule","method":"getValue"},"132531":{"module":"ReanimatedModule","method":"getValue"},"132550":{"module":"ReanimatedModule","method":"getValue"},"132565":{"module":"ReanimatedModule","method":"getValue"},"...(truncated keys)...":451} 
Container@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:143480:38
RCTView
ScreenContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:143124:36
RCTView
AnimatedComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:64250:24
AnimatedComponentWrapper
PanGestureHandler@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:139150:38
StackViewLayout@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:142218:36
withOrientation@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:137382:38
RCTView
Transitioner@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:145959:36
StackView@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:142000:36
Navigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:132822:38
KeyboardAwareNavigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:137007:38
SceneView@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:135127:36
SwitchView@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:135070:36
Navigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:132822:38
NavigationContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:136480:38
AppContent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:131452:48
BottomSheetModalProviderWrapper@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:416522:25
Provider@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:263248:21
AppWrapper@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:131400:26
RCTView
ChildrenWrapper@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:290311:77
_default@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:290492:36
Root
RCTView
AppContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:70973:22

**Comment by AliMeer** [comment]
We need to check if these are still occurring.

**Comment by cakesoft-utkarsh** [comment]
This is not occurring now. Verified on development. Can we close this now?

**Comment by AliMeer** [comment]
These errors are not triggered anymore
