### ISSUE TITLE
Backup PDF language

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2861]
As a non-English speaking user, I want my backup pdf to have my own language instead of English, so that I can understand and follow restore instructions.

Changes required:
- Java and Swift/Objective C code updates to pdf creation code
- Update pdf creation code to consider language as a parameter 
- Native code to add the user-selected language to the pdf if the translation is available else English.

**Comment by cakesoft-shashank** [comment]
Not applicable now
