### ISSUE TITLE
Button click responsiveness

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2864]
Some button clicks are very slow in responding.
Manage Backup.
Individual Keeper buttons on Manage Backup.
"Confirm and Send" in Send flow

**Comment by AliMeer** [comment]
We need to check if this is still occuring.

**Comment by antuz123** [comment]
@cakesoft-utkarsh @cakesoft-nikhita - 

The login button works perfectly fine, that is the model we need for the following as well: 
1. Send flow buttons 
2. Add contact 
3. Account tiles on HS 
4. Share QR 
5. Several buttons when sharing in NBHR 

see if you can find any more

**Comment by antuz123** [comment]
@cakesoft-rohit - note the instances and the fix done

**Comment by cakesoft-utkarsh** [comment]
I have observed this is not reproducible on all the listed places, such as Send flow buttons, Add contact, Share QR.

Can we revisit, to check if its valid after 2.0?

**Comment by cakesoft-swati** [comment]
@ Rohit please check the following Buttons:
1.Account >Account Settings >Name&Description >Confirm&Proceed button
2.Buy>Ramp Bitcoin > Buy bitcoin button.
3.Buy > Wyre Bitcoin >Buy Bitcoins.

**Comment by antuz123** [comment]
Ramp and Wyre will be fixed as pet of another issue @cakesoft-swati

**Comment by cakesoft-swati** [comment]
- Verified this issue ond ev app v1.8.5(326)

**Comment by cakesoft-swati** [comment]
-   The initial button is clickable several times (when creating the wallet).
- Need to check other button click responsiveness.

**Comment by cakesoft-swati** [comment]
-There is a lag between - A user clicking on "confirm and send" - the button going light blue - the button becoming dark blue again and then the "Sent Successfully" modal becoming visible. (Live app:.67 Android).
- The lag should not be there ideally. Also, the color of the button should definitely not change back to dark blue.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(470)
