### ISSUE TITLE
Options for improving performance during autoSync

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2868]
When autoSync is in progress after login, the app is not very responsive.
Need to identify ways of making this more responsive.

**Comment by antuz123** [comment]
@cakesoft-utkarsh @cakesoft-nikhita - the auto sync is currently turned off but still there is something on the HS that does not let you go into the accounts quickly. In the first 2-3 secs. We need to remove that call and put it during the loading when the user is looking at the loader screens.
