### ISSUE TITLE
HS QR scanner cannot scan the address QR.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2880]
-QR that used from Coinbase that did not work on the HS screen.
![IMG_9A451ACF0AEA-1](https://user-images.githubusercontent.com/62699947/110466614-ffb30100-80fb-11eb-8322-31dda36d00f2.jpeg)
-Did not work on Live app v1.4.6(235) which is upgraded from 1.4.5(230)
-Tested in iphone 7.
-I can scan it through the staging app v1.4.6(235) which was not upgraded from 1.4.5

**Comment by AliMeer** [comment]
Tested on upgraded iPhone 12 Pro Max and iPhone XS Max

**Comment by cakesoft-swati** [comment]
- worked on Live app v1.4.6(235) which is upgraded from 1.4.5(230)
-Unable to reproduce this issue
