### ISSUE TITLE
Upgrade actions (Old BHR to New BHR)

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#2891]
UP2’
Please refer https://trello.com/c/rjuZbdkZ/182-up2-upgrade-actions-old-bhr-to-new-bhr

**Comment by cakesoft-shivani** [comment]
Upgrade flows
Total available Keepers (TAK)
1) If we have TAK 0/1 [Done]
    NBHR will be on level 1 and push Primary mnemonics to cloud

2) If  we have TAK 2-3 
    - NBHR will be on level 2
    - init levels to Level 2 with current level 1 [Done]
    - Fetch trusted channel to fetch versions
    if (old keeper == new version)
        - update new share
        - send notification 
        - share will be "accessible"
    else 
        - update new share
        - send notification
        - share will be "notAccessible"
        - show modal in history page that "your keeper need to update app / come online" or "Something error message"
    Again in this case there will be again cases be like 
    KD = Keeper device
    CK = Contact Keeper
    PDF = pdf keeper
    if(TAK has no of pdf == 2 || TAK has no of pdf == 1){
        - share 1st share on cloud and delete other keeper for this keeper (share 1)
        - create new 1 pdf (share 2)
        - delete old pdf (if has 2 pdf)
        - setup new keeper of any type between keeper device and keeper contact (share 3)
    }
    if(TAK has no of pdf == 0){
        - share 1st share on cloud (share 1)
        - Reshare share to old keeper (share 2)
        - delete one of the keeper
        - setup new keeper of any type between keeper device and keeper contact (share 3)
    }
    manage other condition such as 1st keeper type can change and other conditions might be there for level 2
2) If  we have TAK 4-5 
    - NBHR will be on level 3
    - init levels to Level 3 with current level 2 [Done]
    - Fetch trusted channel to fetch versions
    if (old keeper == new version)
        - update new share
        - send notification 
        - share will be "accessible"
    else 
        - update new share
        - send notification
        - share will be "notAccessible"
        - show modal in history page that "your keeper need to update app / come online" or "Something error message"
    Again in this case there will be again cases be like 
    KD = Keeper device
    CK = Contact Keeper
    PDF = pdf keeper
    if(TAK has no of pdf == 2 || TAK has no of pdf == 1){
        - share 1st share on cloud and delete other keeper for this keeper (share 1)
        - create new 1 pdf (share 2)
        - delete old pdf (if has 2 pdf)
        - setup new keeper of any type between keeper device and keeper contact (share 3)
    }
    if(TAK has no of pdf == 0){
        - share 1st share on cloud (share 1)
        - Reshare share to old keeper (share 2)
        - delete one of the keeper
        - setup new keeper of any type between keeper device and keeper contact (share 3)
    }
    manage other condition such as 1st keeper type can change and other conditions might be there for level 3

**Comment by cakesoft-devika** [comment]
-Verified this ticket on Staging app v1.6.5(280)
