### ISSUE TITLE
The icon looks like Refresh.

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2902]
Refer to trello card
https://trello.com/c/zcqk4xT6/39-the-icon-looks-like-refresh

**Comment by Arpanjainson** [comment]
Refer to the the icon on screen - Backup – Level 1 expanded Security Question
https://xd.adobe.com/view/306fd70c-6cc6-4d76-a5c4-46490c6831ef-653c/

**Comment by Arpanjainson** [comment]
@antuz123  check once

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(257)
