### ISSUE TITLE
2FA Setup Validation broken

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2903]
2FA setup isn't working. We are able to generate the key to be used in the authenticator, however, on entering the totp on the validation screen, there's no response whatsoever and the screen remains as it is.

![Simulator Screen Shot - iPhone 12 mini - 2021-03-12 at 15 30 25](https://user-images.githubusercontent.com/17980466/110924362-f6b66f80-8347-11eb-870b-7b476ebfdb3d.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app v1.5.0(239).
-Now it is working.
