### ISSUE TITLE
Textual changes .

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2907]
- Bitcoin > bitcoin
![File (39)](https://user-images.githubusercontent.com/62699947/110934734-6df20080-8354-11eb-9b49-6e84d664873c.jpg)

- “Your order is successful” no need for has been
![File (40)](https://user-images.githubusercontent.com/62699947/110934801-8530ee00-8354-11eb-88b7-625478dc262e.jpg)

- Purchased > purchased
![File (41)](https://user-images.githubusercontent.com/62699947/110934864-a09bf900-8354-11eb-94f5-34863dc917ac.jpg)

- Purchased > purchased
![File (42)](https://user-images.githubusercontent.com/62699947/110934959-c32e1200-8354-11eb-8746-fe1e4693cbc6.jpg)

- Anon > Anon’s. Another example Swati > Swati’s
![File (43)](https://user-images.githubusercontent.com/62699947/110935016-dccf5980-8354-11eb-9cdd-0355eacf49c6.jpg)

- No need of the word details here. The user is only entering the amount on this screen.
- for all of these screens other than the donation account screen
![File (45)](https://user-images.githubusercontent.com/62699947/110935719-cfff3580-8355-11eb-9048-9ff1be08582f.jpg)

- purchases of BTC > “BTC purchases”
![File (50)](https://user-images.githubusercontent.com/62699947/110937596-9976ea00-8358-11eb-83cf-42afad4e5def.jpg)

-a and m small. Bitcoin not Bitcoins
![File (52)](https://user-images.githubusercontent.com/62699947/110938509-fcb54c00-8359-11eb-9614-9b24b6c6185e.jpg)

**Comment by cakesoft-swati** [comment]
- Following changes are pending:
-Bitcoin not Bitcoins
![File (52)](https://user-images.githubusercontent.com/62699947/110938509-fcb54c00-8359-11eb-9614-9b24b6c6185e.jpg)

- purchases of BTC > “BTC purchases”
(It should be for both wyre and Ramp account)
![File (50)](https://user-images.githubusercontent.com/62699947/110937596-9976ea00-8358-11eb-83cf-42afad4e5def.jpg)

-- No need of the word details here. The user is only entering the amount on this screen.
- for all of these screens other than the donation account screen
![File (45)](https://user-images.githubusercontent.com/62699947/110935719-cfff3580-8355-11eb-9048-9ff1be08582f.jpg)
[Send screen is different now]

**Comment by AliMeer** [comment]
@cakesoft-swati please make a new issue with the bugs that are still not fixed.

**Comment by cakesoft-swati** [comment]
-Okay made new issues for pending bugs.
-Now closing this issue.
