### ISSUE TITLE
Add New Account Screen UI changes

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2912]
- Add New Accounts > Description
-we can remove the second line altogether. The reduced size of the logos is not looking good.
-Make it fit in one line.
![File (47)](https://user-images.githubusercontent.com/62699947/110936777-6bdd7100-8357-11eb-9fa1-e48403e4d98a.jpg)

**Comment by antuz123** [comment]
1. Use the text same as in the buy menu for services. 
2. Watch Only: View a non-Hexa wallet as an account 
3. Full Import: Fully import a non-Hexa wallet

The UX needs to be done properly to support two lines here. Plus the alignment and size is not correct. 
Please see the design here: https://xd.adobe.com/view/91d3b24d-96da-420e-adc7-a7115884db1c-c480/screen/0f336575-dd6a-40e5-9303-f9d21b0f6ca1

**Comment by summikhan11** [comment]
Specs Link: https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/screen/f0acbfc5-2ee6-4b2d-9277-dbb02fb313a6/

**Comment by antuz123** [comment]
We should use the same screen as Account Selection during initialisation

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.0(322)
