### ISSUE TITLE
Issue of Proceed button of Wyre and Ramp account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2913]
- I pressed this once. It went to Ramp. With Ramp open in browser I came back to the wallet and pressed it again. No response.
![File (48)](https://user-images.githubusercontent.com/62699947/110937389-51f05e00-8358-11eb-8479-b4e4ef78a548.jpg)

- Same issue with this button. It went to ramp once. I came back. The button is not responding.
![File (49)](https://user-images.githubusercontent.com/62699947/110937463-66ccf180-8358-11eb-9d4d-79803cb1f95e.jpg)

**Comment by cakesoft-swati** [comment]
-Still this proceed button is not responding if I came back to the wallet and pressed it again.

**Comment by AliMeer** [comment]
@cakesoft-swati this is not an issue. There is already a browser window open, so the user shouldn't leave that and come back to the app. just like you switched the app, you can switch back to the browser window.
If you close the modal and click on buy button again then it will open the browser again but not if you have just done that.

**Comment by cakesoft-swati** [comment]
Oh got it.
-Verified tis issue o dev app v1.5.0(245)
