### ISSUE TITLE
IOS Builds failing

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2918]
IOS Builds failing in appCentre for newBHR and also the branch where newBHR has been merged with send refactor code(feature/send-flow-refactoring)

newBHR
newBHR-sendRefactor-merge

Errors are:

**newBHR** fails with the folloiwng error

error: Multiple commands produce '/Users/runner/Library/Developer/Xcode/DerivedData/HEXA-finfogjaplkrgpghmhvkxxsnlxkx/Build/Intermediates.noindex/ArchiveIntermediates/HEXA Dev/IntermediateBuildFilesPath/HEXA.build/Release-iphoneos/HEXA Dev.build/DerivedSources/Pods-HEXA Dev-checkManifestLockResult.txt':
1) That command depends on command in Target 'HEXA Dev' (project 'HEXA'): script phase “Bundle React Native code and images”
2) That command depends on command in Target 'HEXA Dev' (project 'HEXA'): script phase “Run Script”
3) That command depends on command in Target 'HEXA Dev' (project 'HEXA'): script phase “[CP] Check Pods Manifest.lock”

**newBHR-sendRefactor-merge** fails with the folloiwng error

error: Multiple commands produce '/Users/runner/Library/Developer/Xcode/DerivedData/HEXA-finfogjaplkrgpghmhvkxxsnlxkx/Build/Intermediates.noindex/ArchiveIntermediates/HEXA Dev/IntermediateBuildFilesPath/HEXA.build/Release-iphoneos/HEXA Dev.build/DerivedSources/Pods-HEXA Dev-checkManifestLockResult.txt':
1) That command depends on command in Target 'HEXA Dev' (project 'HEXA'): script phase “Run Script”
2) That command depends on command in Target 'HEXA Dev' (project 'HEXA'): script phase “[CP] Check Pods Manifest.lock”

**Comment by AliMeer** [comment]
I tried building **newBHR-sendRefactor-merge** branch with HEXA variant instead of HEXA DEV and it was able to build:

So that means the HEXA DEV variant scripts are not correct. Not sure about staging

![Screenshot 2021-03-12 at 22 20 47](https://user-images.githubusercontent.com/7535475/111004671-5aa95a00-8381-11eb-87af-87649fd37a68.png)

**Comment by cakesoft-utkarsh** [comment]
Resolved by commit cd1188ac270a101fbda056a807c3044929b35530

**Comment by AliMeer** [comment]
HEXA DEV and HEXA are working
HEXA Staging is not building.

** ARCHIVE FAILED **


The following build commands failed:
	CompileC /Users/runner/Library/Developer/Xcode/DerivedData/HEXA-finfogjaplkrgpghmhvkxxsnlxkx/Build/Intermediates.noindex/ArchiveIntermediates/HEXA\ Stage/IntermediateBuildFilesPath/HEXA.build/Release-iphoneos/HEXA\ Stage.build/Objects-normal/armv7/AppDelegate.o /Users/runner/work/1/s/ios/HEXA/AppDelegate.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65

**Comment by AliMeer** [comment]
Dev, Staging, and Live builds for Android and IOS are working now. Verified on App Centre.
