### ISSUE TITLE
Android build failing

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2919]
Android fails in app centre with

Android dev target build fails branches **newBHR** and **newBHR-sendRefactor-merge**

> Task :app:copyDevelopmentReleaseBundledJs
> Task :app:mergeDevelopmentReleaseJavaResource
> Task :app:desugarDevelopmentReleaseFileDependencies
> Task :app:transformClassesWithDexBuilderForDevelopmentRelease
> Task :app:validateSigningDevelopmentRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningDevelopmentRelease'.
> Keystore file '/Users/runner/work/1/s/android/app/***.keystore' not found for signing config 'release'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 41s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/***guide/command_line_interface.html#sec:command_line_warnings
966 actionable tasks: 911 executed, 55 up-to-date
Error: /Users/runner/work/1/s/android/gradlew failed with return code: 1
    at ChildProcess.<anonymous> (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/1.128.0/node_modules/vsts-task-lib/toolrunner.js:569:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
##[error]Error: /Users/runner/work/1/s/android/gradlew failed with return code: 1
##[section]Finishing: Gradle Task

**Comment by cakesoft-utkarsh** [comment]
keystore file should be present at hexa/android/app folder.
If keystore cannot be at this location change the path in hexa/android/gradle.properties "MYAPP_UPLOAD_STORE_FILE"

**Comment by cakesoft-nikhita** [comment]
@AliMeer, Please remove `signingConfig signingConfigs.release` from build.gradle file inside Android -> app -> build.gradle. If we need to give manual release this line is necessary but using App Center we need to remove this.

**Comment by AliMeer** [comment]
OK. Will do this for the next build.

**Comment by AliMeer** [comment]
> @AliMeer, Please remove `signingConfig signingConfigs.release` from build.gradle file inside Android -> app -> build.gradle. If we need to give manual release this line is necessary but using App Center we need to remove this.

OK. Will do this for the next build.

**Comment by AliMeer** [comment]
> @AliMeer, Please remove `signingConfig signingConfigs.release` from build.gradle file inside Android -> app -> build.gradle. If we need to give manual release this line is necessary but using App Center we need to remove this.

@cakesoft-nikhita this worked 👍
