### ISSUE TITLE
Clicking Send on Contact

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2920]
Home >> F&F >> Select Contact

On the contact screen, clicking on Send in the top right corner of the screen crashes the app.

**Comment by CypherPoet** [comment]
@AliMeer Is there a good way to reproduce this in the Simulator? Right now, I'm not able to get any contacts in a state where I can send to them (it only shows the "Resend Request" button)

**Comment by AliMeer** [comment]
@CypherPoet
On a phone keep v1.4.6 or v1.5.0 installed from test flight. Run in debug mode on simulator.
Add  a contact from the simulator by sharing QR and scan with phone. When sharing you can choose any name from the contact list, it doesn’t matter as you will be scanning the QR.
Once you scan with the phone, associate it to any contact in your address book.
This should add the contact. If the contact doesn’t show green or if the timer doesn’t disappear, then restart the app on the phone and restart the app in the simulator.

**Comment by cakesoft-swati** [comment]
-It is still happening on dev app v1.5.0(243)

**Comment by AliMeer** [comment]
@CypherPoet Clicking on send on contact screen shows the send screen to enter the amount.

Clicking Confirm and Send does not show the fees options screen and directly shows "Sent Unsuccessful"

![Screenshot 2021-03-17 at 19 53 00](https://user-images.githubusercontent.com/7535475/111530027-bd706c00-875a-11eb-885c-3caeaff9d6e1.png)

**Comment by cakesoft-swati** [comment]
-Verified "On the contact screen, clicking on Send in the top right corner of the screen crashes the app." this issue on dev app v1.5.0(243)
