### ISSUE TITLE
Adding address in new Home Scanner screen causes app to crash

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2921]
Home >> Scanner

On the scanner screen, adding or pasting an address in the address input box causes the app to crash.

**Comment by CypherPoet** [comment]
@AliMeer Is there a good sample address that can be used to debug this

**Comment by AliMeer** [comment]
@CypherPoet this shows sent successful message but the transaction is not actually sent.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(249)
