### ISSUE TITLE
Send confirmation modal UI issues

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2922]
1. Send confirmation modal is too big.
2. Title for send confirmation always says " Sent successfully to contact" even when sending to an address or to own account.

![Screenshot 2021-03-13 at 19 33 50](https://user-images.githubusercontent.com/7535475/111042035-27bf9e80-8433-11eb-8ea4-76f61d03599e.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(243)
