### ISSUE TITLE
Service and F&F Accounts 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2932]
Account for Ramp, FBTC and Wyre needs to be one. Swan may need its own xPub/ Account.

**Comment by AliMeer** [comment]
@antuz123 I dont think we need an issue for this at the moment. When we have decided to do it we can create an issue.

**Comment by antuz123** [comment]
Also need a F&F account with one xPub 

Will need a upgrade script which transfers accounts to new ones. The new accounts will also include old UTXOs but any change or receive will be made with the new account. 

Objective is to get to one account - one xPub

**Comment by AliMeer** [comment]
Which release?
