### ISSUE TITLE
App Offloading.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2939]
-When the app is in inactive mode and then we download it again or upgrade it,it shows a blank screen.
(-If upgrading from a loder version of hexa it will show blank screen irrespective of offload or on load.)
 - App offloading should work when app is reinstalled.
 - [App offloading only removes the app binary. Your documents and settings stay on your iOS device. This means that if you reinstall the app in the future, it will be like picking up exactly where you left off.]

https://user-images.githubusercontent.com/62699947/111284448-24602900-8666-11eb-8cb0-a4d0365848c0.MOV

**Comment by cakesoft-utkarsh** [comment]
Offloading of app is not a reason for his blank screen.
App state and data is completely restored when app is reinstalled. 

Verified by offloading the app multiple times.

**Comment by cakesoft-devika** [comment]
-Verified this issue on Staging app v1.6.0(277)
