### ISSUE TITLE
UI issue on Sent successful modal.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2952]
![Screenshot_20210317-105258_hexa dev](https://user-images.githubusercontent.com/62699947/111433550-69e32b80-8724-11eb-8450-4e564cb6676b.jpg)
-It looks like the two different  modals are coming one on top of the other.

-Also the send successful model can be easily pull down.It should not be pulled down.Only the "View account" should be active.

**Comment by CypherPoet** [comment]
Are there any recommended steps for reproducing this? I haven't been able to do so yet.

**Comment by AliMeer** [comment]
@CypherPoet sending a transaction successfully brings up the send confirmation sheet. The screen shot attached above is from a Samsung A50. The dimensions of the screen are probably causing the overlap issue. On iPhone pro max there is a slight overlap as well. Attached is a screen shot from iPhone pro 12.

![807881CE-1E17-4619-A1A6-77546EBE44E0](https://user-images.githubusercontent.com/7535475/111846882-a5861d00-88ff-11eb-8ef2-1b3351867601.png)

**Comment by AliMeer** [comment]
![D8029AF1-F7B4-426C-9974-7232AB53F9E0](https://user-images.githubusercontent.com/7535475/111846987-d8c8ac00-88ff-11eb-83f7-8e5469487bb5.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v 1.5.0(248)
