### ISSUE TITLE
Issues of Send confirmation screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2953]
![tempFileForShare_20210317-142545](https://user-images.githubusercontent.com/62699947/111440845-c0ecfe80-872c-11eb-9618-ea292bb42bd9.jpg)

-Alignment (Arrival Time) is not correct.
-It is always showing $ as a Fee currency.

**Comment by Parsh** [comment]
There are few more places on the send confirmation screen

![Simulator Screen Shot - iPhone 12 mini - 2021-03-17 at 14 50 54](https://user-images.githubusercontent.com/17980466/111444385-5342d180-8730-11eb-9d50-467c2d0c9b58.png)

**Comment by cakesoft-swati** [comment]
> There are few more places on the send confirmation screen where conversion unit is off(USD mode is on)

this isssue is still happening on dev app v.1.5.0(246)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(248)
