### ISSUE TITLE
After adding custom priority the "Confirm and Send" button is going down.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2954]
<img width="375" alt="56E2BE41-9819-4E2A-9A56-0AC401DE4777" src="https://user-images.githubusercontent.com/62699947/111442853-cd725680-872e-11eb-83a0-b9bcf4bde87c.png">
-The "Confirm & Send" button is going down even further by adding custom priority.Because of this we can not complete the send flow.
-It is happening on iphone7.
-Tested on 1.5.0(243)

**Comment by cakesoft-swati** [comment]
-Still the button is going down.I have to scroll the page then I can see that button.
-Tested on dev app v1.5.0(246)

**Comment by CypherPoet** [comment]
So the fix here was to allow for exactly that -- scrolling when the content is too large for the screen. 

Is there another approach/design required instead? (@AliMeer @antuz123 @Arpanjainson)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(248)
