### ISSUE TITLE
Send to an immediate F&F fails

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2964]
As soon as an F&F contact is added(i.e. the expiry timer goes away) and you try to send sats to it by clicking the send button on the contact details screen, the send fails w/ the error shown below.

![Simulator Screen Shot - iPhone 12 mini - 2021-03-18 at 14 18 04](https://user-images.githubusercontent.com/17980466/111598273-0ffe6680-87f5-11eb-95e3-5b2a8a60c1b4.png)

Connected to #2920

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(243)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(246)
