### ISSUE TITLE
Issues of level 2> secondary device.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2967]
- Generating the QR to share for secondary device is taking a long time .
- confirm button of sec device is not reacting quickly will have to click it 2/3 times.

**Comment by antuz123** [comment]
> 2 of 3 SSS to do after K2 is added - we show the user loader messages - "Preparing your Recovery Keys" 
(suggestion - if the refresh of Manage Backup is taking time)

**Comment by cakesoft-swati** [comment]
-Still facing these issues on Staging app v1.5.0(252)
 - Generating the QR to share for secondary device is taking a long time .
 - confirm button of sec device is not reacting quickly will have to click it 2/3 times.

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app v1.5.0(256)
