### ISSUE TITLE
Home Screen Scanner does not recognise paymentURI

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2970]
Home Screen Scanner does not recognise paymentURI

**Comment by CypherPoet** [comment]
Is there an error message that's being thrown when this occurs?

**Comment by AliMeer** [comment]
@CypherPoet 
No. Try it yourself. You can generate a payment URi QR on the same screen by entering amount

**Comment by CypherPoet** [comment]
So it doesn't seem to be recognizing the full URI, for example, `bitcoin:2NCkhuXvbV2dTzFD6u3X3xisVet8LxGXhai?amount=0.00002222`. But when I remove the `bitcoin:` prefix and `amount...` suffix, the address gets recognized and the app transitions to the Send to Contact screen -- albiet without knowing the amount 🤔 .

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(248)
