### ISSUE TITLE
Deep links issues on android device.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2978]
-If app is closed and we click on the deep link to accept the request (Keeper request/Contact request) then App got stuck on splash screen.

-Request accept module is not coming up even if app is in backgrond.

-Both the issues are happening only on Android device.
-Tested dev app v1.5.0(246) on SAMSUNG GalaxyA50

**Comment by Parsh** [comment]
I've not been able to replicate that. On my Android(1+) F&F request accept modal showed up perfectly fine both the times upon clicking a deeplink. Tho when the app is not in the background and the deeplink bootstraps the app, the modal take a little while to show up as there's quite a bit of processing(synching of accounts) happening in parallel which might have been causing the delay.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(248)
-Not able to reproduce this issue on same device.
