### ISSUE TITLE
After accepting the request the contact does not appear in the F&F list.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2982]
-Even after accepting the "Keeper"/"contact" request, that contact does not appear in f&F list .
-This is happening only in ios device.
-Tested on dev app v1.5.0(246)

**Comment by Parsh** [comment]
Update: This is happening when keepers are involved in either of the wallets. They seem to corrupt the F&F list.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(248)
