### ISSUE TITLE
Send screen QR scanner does not recognise payment URI

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2984]
Send screen QR scanner is not able to recognise a payment URI QR code. It is able to recognise a address QR code only.

Sample payment URI QR code:

![91E6D9A4-DE9F-4BC2-869F-07E238D70BE8](https://user-images.githubusercontent.com/7535475/111847398-a23f6100-8900-11eb-94a7-2caaf08497e4.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v 1.5.0(248)
