### ISSUE TITLE
Sent transactions from Test Account are not visible 

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2985]
Sent transactions from test account are visible once after sending but are not present in the list when coming back to the test account screen.

https://user-images.githubusercontent.com/7535475/111848383-d7e54980-8902-11eb-8989-21b7e1b10a4c.MP4

**Comment by Parsh** [comment]
Is it replicable? There might be something that could have gone wrong(likely to be at the level of the UI, some sort of caching could be in play). However, after trying a bunch of outgoing txs from test account I wasn't able to reproduce it.

**Comment by AliMeer** [comment]
After sending it shows up. Going back to the test account it’s not present. I tried this with 3 transactions.

**Comment by AliMeer** [comment]
This issue is not occurring anymore. closing.
