### ISSUE TITLE
Recipient remove crash

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#2989]
Removing a recipient(during the send flow) crashes the app w/ the following err

![Simulator Screen Shot - iPhone 12 mini - 2021-03-21 at 14 49 42](https://user-images.githubusercontent.com/17980466/111899835-007d5880-8a55-11eb-91ef-ec4453bd90b5.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(248)
