### ISSUE TITLE
Able to see the old Manage Backup screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2992]
-After installing the app, if I jump directly from the home page to the Manage Backup screen, I see the old flow.

**Comment by Arpanjainson** [comment]
Issue with Android only

**Comment by cakesoft-swati** [comment]
-Verified this on dev app v1.5.0(249)

**Comment by cakesoft-swati** [comment]
-I'm able to reproduce this issue on Android Dev app v1.5.0(250).
-Login pop-up is not visible while wallet set up.
-Level 1 was not completed when I landed on the home screen.

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app v1.5.0(252)
