### ISSUE TITLE
MH6: Cloud Opt Out Option

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2999]
As a user, I should be asked if I want to opt-out of cloud backup so that I can opt-out in case I don’t want to allow cloud access.

UX: Refer to screen 1: New Wallet – Enter Name & Cloud checkbox

https://xd.adobe.com/view/a2211587-164a-47be-9d67-85811bb511ea-f772/specs/

**Extract from MH6. 3**

_3. The user is then informed that their backup will be stored on the cloud and they can opt out of it if needed. If they decide to not opt out (take no action), the backup is stored on the cloud. We can show loading messages again if needed._ 

-----------

Changes required:

 1. Update UI to show cloud opt-out option.
2. Cloud opt-out should have a new reducer to track response - cloudPermissionGranted or doCloudBackup
3. Cloud backup should only start if cloudPermissionGranted is true.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(254)
