### ISSUE TITLE
MH6: Start wallet initialisation at or before wallet name is provided

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3000]
Wallet initialisation should start as soon as possible, preferable right after the user lands on the wallet name screen.

- If there is a noticeable performance lag on wallet name screen then we can move this to Q&A

**Comment by Parsh** [comment]
WI is now happening as soon as the user lands upon the wallet name screen, seems to work perfectly fine in the background. We might just wanna check the behavior on lower-end devices.
