### ISSUE TITLE
Optimise wallet initialisation 

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3001]
Currently, we are using timeouts to cycle through loader messages. We should modify this to  cycle through an array of messages while wallet initialisation is in progress.

This can then be extended to show loader messages till cloud backup is completed.

**Comment by antuz123** [comment]
Also see:
1. What processes are being done here and what needs to be taken out 
2. Can we do any background processing 
3. See comment above in timeouts from Ali

**Comment by antuz123** [comment]
Make sure that there is no account sync happening during initialisation

**Comment by antuz123** [comment]
Steps: 
1. New Wallet process selection 
2. Wallet Name entry 
3. Select Account (only Checking Account selected by default) 
3.1 When user selects Savings Account, Test Account or other accounts, the account process happens there with a grey screen and once done a simple toast message is shown with the account being added. 
4. Cloud Backup/ Security Question screen 
4.1 User selects backup - Backup is done behind loader messages 
4.2 User skips backup - no action 
5. Lands on the Home Screen

**Comment by AliMeer** [comment]
This is not required anymore. Message are only shown for a short period and time and this level of optimisation was required for a large number of messages.
