### ISSUE TITLE
Wallet freezes after the initial start up with a white screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3006]
-A user is not able to get into the wallet.It freexes right after the initial start up with a white screen.

- Operating system: Android
- Hardware device: OnePlus 6
- Version last used: 1.4.6
- Backup secured:  no
- App last accessed: Half a year ago or so.
- sequence of events performed:Opened the app, it started up fine and then froze with a white page. Does not get 
to the point where I need to enter the PIN.
[It must have to do with people upgrading after a long time and something at the login, before pin is needed goes missing. May be the way data is stored and retrieved before the PIN page]

**Comment by cakesoft-swati** [comment]
-Verified this issue on upgraded staging app i.e 1.4.2(216) to 1.4.4(226) to 1.5.0(252)
-Also tried it on upgraded app i.e version 1.4.4(226)to 1.5.0
-Not able to reproduce this issue.

**Comment by antuz123** [comment]
New issue reported: Android 10 MIUI 11 Xiaomi  MI 9

**Comment by antuz123** [comment]
Correction: looks like upgraded from 132 (175)

**Comment by cakesoft-devika** [comment]
-Verified this issue on Staging app v1.6.0(277) for android devices
