### ISSUE TITLE
UI issue of contact icon.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3016]
-The contact icon is different from the initial app.Also it is different on both ios and android device.

 - Icon in Android(SAMSUNG A50) device 
 
![Screenshot_20210326-122628_Gallery](https://user-images.githubusercontent.com/62699947/112594287-b5858b80-8e2e-11eb-8383-49a38108e29f.jpg)

 - Icon in ios(iphone 7)device
 
<img width="375" alt="53A8FF00-5716-4CA2-ABAD-B092874F6CE2" src="https://user-images.githubusercontent.com/62699947/112594487-0b5a3380-8e2f-11eb-93ed-db8d07c1db5d.png">

-Also the contact image is not available while doing "Send To Contacts"
<img width="375" alt="95C25210-5E6A-456C-8A7B-BFD71596ADAC" src="https://user-images.githubusercontent.com/62699947/112594681-4ceade80-8e2f-11eb-8199-aaf784e3f6d0.png">

**Comment by cakesoft-swati** [comment]
-Now the contact icons are same on both the devices i.e ios and Android.
-But the contact image is still not available while doing "Send To Contacts"
![tempFileForShare_20210331-154545](https://user-images.githubusercontent.com/62699947/113134053-fe2db200-923d-11eb-94ea-3261c5a739ac.jpg)

-Tested in dev app v1.5.0(254)

**Comment by cakesoft-swati** [comment]
-Now the contact image is available while doing "Send To Contacts".
-Tested on staging app v1.5.0(255)
-But -And F&F request awaiting still not showing the wallet name.
<img width="375" alt="886AEDE6-14A1-43B4-A2BC-42EB6E3A9586" src="https://user-images.githubusercontent.com/62699947/113257349-1bb75600-92e8-11eb-896a-2c625d9a17c0.png">
-It is showing F1/F2...instead of wallet name.

**Comment by AliMeer** [comment]
Will be available in build 257

**Comment by cakesoft-swati** [comment]
-F&F request awaiting still not showing the wallet name on "Send to contact".
-But in F&F list it is showing the wallet name after confirmation.
![tempFileForShare_20210405-150426](https://user-images.githubusercontent.com/62699947/113560271-5d196f80-9620-11eb-9112-82bc1a9b3dc6.jpg)

**Comment by cakesoft-swati** [comment]
Filed a new issue for this f&F request awaiting.so closing this issue for now.Remaining changes are verified on staging app v1.5.0(260)
