### ISSUE TITLE
AC5: Account Settings, Hide and Archive

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#3025]
Details on https://trello.com/c/Pj45lW4y/154-ac5-account-settings 

**Current Screens**
https://xd.adobe.com/view/6e89fcde-5787-4d1a-a1ba-c284e770fdad-3bda/
More – Account Management – Unhide Account
Success Screen – Account Unhidden
Home – Hidden & Archived Account Tags
More – Account Management
More – Account Management – Advanced Settings
More – Account Management – Advanced Settings – Confirm Pin
More – Account Management – Advanced Settings – Confirm Q&A
More – Account Management – All
More – Account Management – Restore Account
Success Screen – Restore Account
More – Account Management – Unhide Account
Success Screen – Account Unhidden

https://xd.adobe.com/view/3db366dc-fc84-4167-ad12-e8a8cd27034c-68e0/
Checking Account – Settings
Settings – Name & Description
Checking Account – Settings – xPub
Checking Account – Settings – Visibility
Checking Account – Settings – Archive
Checking Account – Settings – Archive Error

Proto link if u need to refer to

https://xd.adobe.com/view/d97f9303-d123-44a2-b821-df9670411814-8c2c/
https://xd.adobe.com/view/91d3b24d-96da-420e-adc7-a7115884db1c-c480/

**Comment by Arpanjainson** [comment]
@CypherPoet @AliMeer this is for 1.6.0

**Comment by AliMeer** [comment]
This is UX for Hide and Archive Account functionality. Moving it together with other account-related features.

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (286)
