### ISSUE TITLE
Wallet initialisation is not being completed.- Dev

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3028]
-Wallet initialisation is not completing. This is working for some and not for others.
-Taking a lot more time during initialisation[ Is it because of the cloud backup even though we are not doing SSS?].
-we can enter the wallet if we kill the app and relogin.Level 1 is not being completed even after relogin to the app.
-It is happening only on Dev app v1.5.0(252)
-Tested on iphone 7 and SAMSUNG A50
-It is working on staging app v1.5.0(252)

![takingtimeiniti](https://user-images.githubusercontent.com/62699947/112939917-ee34a600-9149-11eb-8899-cbf7bed2832f.jpg)

**Comment by cakesoft-swati** [comment]
-Facing same issue on both ios and android Dev app v1.5.0(253)

**Comment by AliMeer** [comment]
Please test this in # 254

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(254)

**Comment by cakesoft-swati** [comment]
Able to reproduce this issue on dev app v1.5.0(255)

**Comment by AliMeer** [comment]
This is fixed in # 256

**Comment by cakesoft-swati** [comment]
-Verified this issue in dev app v1.5.0(257)

**Comment by cakesoft-swati** [comment]
-Able to reproduce this issue on dev app v1.5.0(258)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(258)
