### ISSUE TITLE
Send Max is not responding quickly.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3038]
-I have to click it 5/6 times then it works.
-Tested this on dev app v1.5.0(254)

**Comment by CypherPoet** [comment]
@cakesoft-swati Is this an Android issue, or something that happens more broadly? iOS seems to respond instantly.

**Comment by cakesoft-swati** [comment]
-This is happeing on both android and ios.I'm using iphone 7.Able to reproduce this issue on staging app v1.5.0(255).
-You can increase the touch area. Because if I click on the exact text i.e "Send Max" then it is working.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(257)
