### ISSUE TITLE
Level 3 is not getting complete.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3039]
-Level 3 shares have been confirmed but still the exclamation mark is visible.

**Comment by antuz123** [comment]
@cakesoft-swati - were you able to test any aspect of level 3? Did you try restore?

**Comment by cakesoft-swati** [comment]
-I tried restore but on level 1 and level 2.
-On level 3 I shared  a recovery key using a PDF and with a contact. This was confirmed but an exclamation mark was still present there.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.5.0(258)
