### ISSUE TITLE
Restore button is not responding quickly.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3040]
-After clicking it reacts after 7/8 seconds.

**Comment by AliMeer** [comment]
We can fix this as part of restore in the next release

**Comment by cakesoft-swati** [comment]
-It is also happening on dev app v1.5.0(257)

**Comment by cakesoft-nikhita** [comment]
It already fixed by the new Flow

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (285)
