### ISSUE TITLE
Contact image not aligned in Circle

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3043]
To replicate choose a contact which has a profile pic in the phone contacts.

<img width="334" alt="Screenshot 2021-03-31 at 15 12 50" src="https://user-images.githubusercontent.com/7535475/113198472-f5d07980-9233-11eb-9d7e-477ab1e3a2c9.png">
<img width="327" alt="Screenshot 2021-03-31 at 15 13 09" src="https://user-images.githubusercontent.com/7535475/113198485-f9fc9700-9233-11eb-96c3-eb67ef4391f3.png">
<img width="334" alt="Screenshot 2021-03-31 at 15 13 16" src="https://user-images.githubusercontent.com/7535475/113198491-fc5ef100-9233-11eb-82c3-d108818bf4f4.png">

**Comment by cakesoft-swati** [comment]
-Now the outline here is in square form instead of circle.
![tempFileForShare_20210402-204430](https://user-images.githubusercontent.com/62699947/113560469-aff32700-9620-11eb-8115-96298a445ca0.jpg)

**Comment by cakesoft-devika** [comment]
- Issue still replicated in on staging app v1.6.0(277) 
![Screenshot_2021-05-02-19-41-43-776_io hexawallet hexa staging](https://user-images.githubusercontent.com/75297509/116863351-cc847e00-ac23-11eb-8d47-3a9d9316e4c8.png)

**Comment by cakesoft-devika** [comment]
@AliMeer I checked on the Android device (Redmi) and Issue seems to be still replicated.
