### ISSUE TITLE
pdf is not getting attached in the email.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3053]
-while I'm trying to share the recovery key via email,the pdf is not getting attached in the email.
-It is only happening in android device(tested on SAMSUNG A50)and email only.

**Comment by cakesoft-swati** [comment]
-I'm still not able to attach the pdf in email.
-Tested staging app v1.5.0(259) on SAMSUNG Galaxy A50

**Comment by antuz123** [comment]
@AliMeer - speak to Nikita about this

**Comment by AliMeer** [comment]
Lets retest this in this release.
