### ISSUE TITLE
Trusted contacts are not getting confirmed.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3062]
-I can't get rid of the timer.
-Tested on dev app v1.5.0(257)
-And that contact appears as" FnF request awaiting"  on send screen.
-And when I try to send to that unconfirmed contact, then it is giving an unknown error.
<img width="375" alt="6E717AD8-7834-4452-AF6F-98C5EEB5229C" src="https://user-images.githubusercontent.com/62699947/113396654-7c629380-93b9-11eb-90c2-209731c251d8.png">

**Comment by AliMeer** [comment]
Please retest on 258

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v 1.5.0(258)
