### ISSUE TITLE
Suggest a way so users can wipe out all the backups from iCloud and Google Drive.

### ISSUE THREAD

**Issue by cakesoft-utkarsh** [bithyve/hexa#3063]
This doesn't need to be a functionality in the app.

**Comment by cakesoft-utkarsh** [comment]
Go to Settings > You Name  (Apple ID, iCloud, Media & Purchases) > iCloud > Manage Storage > Hexa > Delete Data.

**Comment by antuz123** [comment]
Need to test this @cakesoft-swati

**Comment by cakesoft-utkarsh** [comment]
Tested this on build 288.
Once App data is deleted all the backups are deleted. But if you try to restore when App data is deleted then the app is non-responsive.

**Comment by cakesoft-swati** [comment]
-Tested this issue on dev app v 1.8.0(304)
-I can wipe out all the backups from icloud.
