### ISSUE TITLE
 UI issues when setting up a new wallet.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3064]
-Key-board is overlapping this check box.
![Screenshot_20210331-150942_hexa dev](https://user-images.githubusercontent.com/62699947/113388171-57ffba80-93ab-11eb-860c-65fba8ce854e.jpg)

-The  "terms of service " box is being cut from below.
![Screenshot_20210402-105812_hexa dev](https://user-images.githubusercontent.com/62699947/113388551-086dbe80-93ac-11eb-978b-0410e37ad684.jpg)

**Comment by Arpanjainson** [comment]
@cakesoft-swati  I guess this is only for android?

**Comment by AliMeer** [comment]
The 1st one is not required as we will not be removing the checkbox in 1.6.0
The 2nd one can be fixed for 1.6.0

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
