### ISSUE TITLE
restore from level 2 with level 3's 1st keeper accessible not working after pdf scan

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#3069]
If we go to 3rd level we have to change metashare(SSS for 3 of 5) so we do not have old metashares(SSS 2 of 3) and in this case our 2nd level's 2nd keeper is pdf so when we setup 1st keeper of 3rd level we need to update keeper info to all other keepers and in case of pdf we have to update new metashere because we store keeper info to metashare in pdf and while sending this share we share new metashare for level 2.

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app v1.5.0(259)
