### ISSUE TITLE
Restore for failed manage backup

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#3075]
For the user the iCloud was full but the app did not detect and set the level backup as complete during inital setup.

At the time of restore the app was stuck as there was no backup found - to be checked.

**Comment by cakesoft-nikhita** [comment]
Please check this case in the next release I tried to reproduce but it's not reproducing my side. We handled errors of cloud so maybe this will solve. Please check in the next release.

**Comment by cakesoft-devika** [comment]
@AliMeer Need to verify this issue when iCloud was full. Could you confirm how I can verify this issue on my side.
