### ISSUE TITLE
Currency icon on account screen does not show up for cad

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#3076]
![image](https://user-images.githubusercontent.com/8697909/113490245-774f3280-94e6-11eb-83c1-a4e9d473db29.png)

**Comment by Arpanjainson** [comment]
check for other currencies as well - works for usd

**Comment by cakesoft-swati** [comment]
-Able to reproduce this issue on dev app v1.8.0(304)

**Comment by cakesoft-swati** [comment]
- verified this issue on dev app v1.8.0(315)
