### ISSUE TITLE
Change keeper won't work if we are in middle of any level 

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#3077]
Case 1: we are in the process of level 3 completion and we have setup only one keeper of level 3 or not completed level yet
Case 2: we are in the process of level 2 we have not completed level yet

**Comment by antuz123** [comment]
Two issues: 
1. 160: don't show Change Contact when the level is not completed 
2. 2.0.0: show the button and let the user change the contact

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.1(277)
