### ISSUE TITLE
Lorem ipsum.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3098]
-Need text for this screen. This screen arrives at the time of approval.
![IMG_5586](https://user-images.githubusercontent.com/62699947/113572808-87762780-9636-11eb-9979-649960fa5d74.PNG)

**Comment by antuz123** [comment]
"Please approve this request by scanning the Secondary Key stored with any of the other backups"

**Comment by cakesoft-swati** [comment]
-Verified this change on dev app v1.5.0(260)
