### ISSUE TITLE
If there is background processing happening and the screen is inactive, it should grey out the screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3106]
- The screen is inactive for a long time and no action can be taken in it. If there is background processing happening, it should grey out the screen.
![Screenshot_20210405-192508_hexa stage](https://user-images.githubusercontent.com/62699947/113581422-bf846700-9644-11eb-8b16-6c9f393b374e.jpg)

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
