### ISSUE TITLE
Textual changes on Manage Backup screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3114]
1) Cloud backup incomplete. Please complete Level 1 
 2) No full stop after attention
 
![tempFileForShare_20210405-204538](https://user-images.githubusercontent.com/62699947/113590202-ff048080-964f-11eb-87e0-9d7d998893ba.jpg)

**Comment by cakesoft-swati** [comment]
- No full stop after attention
 
![tempFileForShare_20210405-204538](https://user-images.githubusercontent.com/62699947/113590202-ff048080-964f-11eb-87e0-9d7d998893ba.jpg)

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
