### ISSUE TITLE
Xpub Integration

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3121]
Backend changes and integration w/ frontend UI modal for displaying xpub for an account

**Comment by AliMeer** [comment]
1. Upgrade script to add xPub to all existing subAccounts
2. Going forward all new subAccounts have a xPub property populated at initialisation

**Comment by antuz123** [comment]
The test case would be to test it in a service that is expecting xPubs. E.g. watch only wallets

**Comment by AliMeer** [comment]
This can be closed after xPub functionality is tested

**Comment by AliMeer** [comment]
This is done and tested
