### ISSUE TITLE
UI issue on contact screen of F&F list in the upgraded app.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3125]
-I had an old app 1.4.4 (226) I upgraded it to 1.5.0 (260). Then I shared the "Keeper Device" QR with the FI app i.e 1.5.0 (260) and after accepting this QR I noticed these buttons overlapping each other in the contact screen of the F&F list.
![tempFileForShare_20210406-155637](https://user-images.githubusercontent.com/62699947/113817878-a4c10800-9794-11eb-85f6-c9d804e76014.jpg)

**Comment by cakesoft-devika** [comment]
-Verified this issue by upgrading staging app v1.4.5 to v1.6.0
