### ISSUE TITLE
AC7: Swan Account (Add and Buy) - UI

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#3127]
https://trello.com/c/B9XbQCXU/168-ac7-swan-account-add-and-buy

**Comment by AliMeer** [comment]
Proto: https://xd.adobe.com/view/3db366dc-fc84-4167-ad12-e8a8cd27034c-68e0/

Specs: https://xd.adobe.com/view/91d3b24d-96da-420e-adc7-a7115884db1c-c480/screen/c67130ae-00cc-49d6-ad36-e207eb6ff096

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (289)
