### ISSUE TITLE
Transaction:  Not showing, fee estimation and currency

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3129]
-I have upgraded staging app from 1.4.4(226) to 1.5.0(260)
-I tried to send some sats to the another Hexa account.I have a confirmation that the sats was sent, but it still hasn’t recorded in my account, not in receivers account.
-I also tried to send to the savings account (within the app).but again I got the confirmation but it did not appear in the txn list.
-Also the txn priority is same for all i.e 226 sats.(I can even send 500 sats)
<img width="375" alt="89F3CD50-6127-4996-BF04-277694F5A313" src="https://user-images.githubusercontent.com/62699947/113828867-7b0edd80-97a2-11eb-975a-ba892bb38b86.png">
-The overall balance is also not decreasing.
- I did a restore also.
-And now my sats are stuck.I can do a whole send procedure but it doesn't showing that txn in transaction list.

**Comment by antuz123** [comment]
- [ ] Transaction not sowing 
- [ ] Fee calculations incorrect 
- [ ] The fee does not show in $ even when the currency is $

**Comment by cakesoft-swati** [comment]
- Tested on staging app v2.0(357)
