### ISSUE TITLE
Handle cloud errors better

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3131]
When running in a simulator, cloud backup starts but doesn't complete if a user is not logged in with an apple id.
this causes a new wallet to stay stuck on generating keys message and doesn't move to the home screen.

This can be handled better to ensure that cloud issues don't cause users to get stuck on the initialisation bottom loader message.

**Comment by cakesoft-devika** [comment]
@AliMeer, Need to test this ticket when not logged in with an apple id. I'm unable to verify on BrowserStack as the iOS setting won't launch.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.7.5(299)
