### ISSUE TITLE
Some data is missing on restore + upgrade flow.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3133]
-I have upgraded staging app from 1.4.4(226) to 1.5.0(260).After that I restored the app but restore didn't work with old RK's.So I reinstalled 1.4.4 (226) then restored it and then I upgraded it to 1.5.0 (260).
-After all this I went to the F&F list but my F&F list was missing And the version history page was also blank.

**Comment by cakesoft-nikhita** [comment]
I tried 1.4.5 version upgrade to 1.5.0 this issue is not reproducible I can see Version history and my F&F list also. @cakesoft-swati could you Please check again and please login again once you install or restore

**Comment by cakesoft-devika** [comment]
-Verified issue with upgrading 1.4.5 to 1.6.0
