### ISSUE TITLE
Level 1 is not being completed in the live app.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3135]
-I have a FI live app v1.5.0(260) in my android device SAMSUNG Galaxy A50.
-After installing the app, when I landed on the home page, Level 1 was not completed.
-After that I went to the Manage backup screen and the loader started rotating and rotating continuously.Still Level 1 was not completed.
-Then I clicked the "Google Drive" button of Level 1, then I got a pop-up of "Chose on account". I selected the account even then the loader was rotating.
-I installed the app 2 times and tried but it still did not work.

**Comment by cakesoft-swati** [comment]
-Still the level 1 is not being completed in the live app.
-It is only happening on adroid device.

**Comment by AliMeer** [comment]
@cakesoft-nikhita this is happening for Swati and Abhilash. Probably cloud backup isn't completing for some reason.

**Comment by cakesoft-swati** [comment]
-Still happening on live app v1.5.1(262).

**Comment by cakesoft-nikhita** [comment]
@cakesoft-swati Please check this on Internal Testing live app which is there on playstore v1.5.1(265)
If app is not available then please check settings -> Apps -> Shows list of all apps installed → Google Play Store → Storage (if displayed) → Clear Cache
if you want to add some new user for testing please send me email of playstore

**Comment by cakesoft-devika** [comment]
Verified this issue on Live app v1.6.0(277) and I'm able to complete Level 1 on Android devices.
Hence, closing the issue.
