### ISSUE TITLE
Red outline even after confirmation of the share.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3142]
-Red even after confirming when cloud backup not done.
![redoncnf](https://user-images.githubusercontent.com/62699947/114344722-f6470980-9b7d-11eb-9408-5c8d4342f84e.jpg)

**Comment by cakesoft-nikhita** [comment]
@cakesoft-swati on which version this issue reproduced? as our side, I try to reproduce this issue but it's working it's already fixed by us. So, I mark it as "fixed" please check this in new build

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(276)
