### ISSUE TITLE
No full stops in any of the sentences.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3144]
-No full stops in any of the sentences
<img width="375" alt="F10F8BD8-736F-4149-9986-A675BE1DEF57" src="https://user-images.githubusercontent.com/62699947/114347237-432cdf00-9b82-11eb-8c5e-412cb1b6a3ce.png">

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
