### ISSUE TITLE
Get the right assets.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3146]
-Get the right assets.
<img width="375" alt="7C87CDCE-106C-415B-9B24-66B7F7C3C020" src="https://user-images.githubusercontent.com/62699947/114350515-e7b12000-9b86-11eb-9ec6-8c9522e35d3b.png">

**Comment by AliMeer** [comment]
@ASN-BitHyve when we have the assets agreed we can pick this up.

**Comment by antuz123** [comment]
Spec link: https://xd.adobe.com/view/3db366dc-fc84-4167-ad12-e8a8cd27034c-68e0/screen/c0ea6267-1531-4769-b344-a716740f8c36/ 

Account Sync - the sub text should be "Manually scan the account"

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (286)
