### ISSUE TITLE
Note for xPub

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3147]
-This xPub is for this particular account only and not for the whole wallet. Each account has its own xPub
<img width="375" alt="B38E3A51-DD2D-4BFC-81F9-38B9AEA6CC55" src="https://user-images.githubusercontent.com/62699947/114350862-6c03a300-9b87-11eb-86fc-6fda74f0716a.png">

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
