### ISSUE TITLE
Account xPub

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3148]
-Back button not working. 
-No full stop
<img width="375" alt="F290E42B-8E2E-4AAE-9192-469ECCB2B9F4" src="https://user-images.githubusercontent.com/62699947/114357882-e33d3500-9b8f-11eb-873a-57d34d1ce05d.png">

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
