### ISSUE TITLE
Text chnages on levels if previous levels are not completed.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3151]
-‘First complete Level 2, before proceeding with Level 3’ Same for Level 2, when Level 1 is not set up.
<img width="375" alt="68AB1EEE-39BC-4173-B51E-1E901708DD0B" src="https://user-images.githubusercontent.com/62699947/114373810-9b72d980-9ba0-11eb-8a3a-a5b36c03f1ff.png">

**Comment by AliMeer** [comment]
@cakesoft-nikhita  Instead of "Setup/upgrade your backup" It should say: ‘First complete Level 2, before proceeding with Level 3’
Similarly for leve 1 incomplete it will say: ‘First complete Level 1, before proceeding with Level 2’

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.6.0(265)
