### ISSUE TITLE
Text changes for completed levels.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3152]
-All the levels that are completed will say “Backup Level 1 is secure, upgrade to Backup Level 2” or “Backup Level 1 is secure, upgrade to Backup Level 3”
<img width="375" alt="603AA763-D27A-4616-A666-414366AAEF64" src="https://user-images.githubusercontent.com/62699947/114374062-de34b180-9ba0-11eb-8b91-6a8527613dd3.png">

**Comment by AliMeer** [comment]
@cakesoft-nikhita 
On Leve 1 complete the message should be, “Backup Level 1 is secure, upgrade to Backup Level 2” 

On Level 2 complete the message should be, “Backup Level 1 is secure, upgrade to Backup Level 3”

**Comment by ASN-BitHyve** [comment]
@cakesoft-nikhita "Backup Level 3 is secure"...when it is!

**Comment by cakesoft-nikhita** [comment]
@ASN-BitHyve That note is "Multi-key Backup complete"

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
