### ISSUE TITLE
Text change on Level 2 and Level 3 after completion of previous level..

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3153]
-When level 2 or 3 not setup (not for level 1), “Share the Recovery Key(s) to upgrade your backup to Level 2”
<img width="375" alt="FE9A97A1-08FC-466B-A42C-6C0AB0F637D4" src="https://user-images.githubusercontent.com/62699947/114374552-67e47f00-9ba1-11eb-8bf7-a4f081540f17.png">

**Comment by AliMeer** [comment]
@cakesoft-nikhita When level 1 is complete and Level 2 is not complete: replace "Setup/upgrade your backup"  with “Share the Recovery Key(s) to upgrade your backup to Level 2”

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.6.0(265)
