### ISSUE TITLE
Reduce the font.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3154]
-Reduce font to the same as NEW.
<img width="375" alt="4B5391AB-0AE3-4655-BF02-ACF383E71705" src="https://user-images.githubusercontent.com/62699947/114375540-636c9600-9ba2-11eb-8bac-f34f57428c0e.png">

**Comment by AliMeer** [comment]
The two fonts are already the same size.

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(276)
