### ISSUE TITLE
Change text for "secondary device".

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3155]
-Personal Device

<img width="375" alt="BDB87061-9333-4F3B-BBD5-E16B9A024924" src="https://user-images.githubusercontent.com/62699947/114376024-e4c42880-9ba2-11eb-8e1f-c41c5c49d7a2.png">

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
