### ISSUE TITLE
Text if a particular RK is not accessible

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3157]
-When a Level has been setup. I.e. Setup = true. Then later if a particular RK becomes inaccessible, the text should be : 
1) For contacts: “Your backup stored with xyz is inaccessible, pls confirm/ manage the Recovery Key” 
2) For devices “Your backup stored on xyz is inaccessible, pls confirm/ manage the Recovery Key” 
3) For pdf: “Your backup stored as Personal Copy (pdf) is inaccessible, pls confirm/ manage the Recovery Key”......... Again this text is when inaccessible after setup was completed in the past
<img width="375" alt="12DABC9B-6F2B-465C-9671-3CED30B0F800" src="https://user-images.githubusercontent.com/62699947/114377722-9b74d880-9ba4-11eb-9472-68418093be3b.png">

**Comment by cakesoft-devika** [comment]
@cakesoft-nikhita Staging app v1.6.0(277): For contacts and devices, xyz text is missing in the text

![Screenshot_2021-04-30-15-55-58-919_io hexawallet hexa staging](https://user-images.githubusercontent.com/75297509/116683721-a4034680-a9cd-11eb-8a6e-aaa5a6dd2d2a.png)

**Comment by cakesoft-nikhita** [comment]
![Screenshot 2021-05-11 at 4 38 44 PM](https://user-images.githubusercontent.com/37994396/117807323-1b13c700-b279-11eb-9b81-f6263a44e589.png)
I tried to reproduce this I am getting proper text as suggest

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (285)
