### ISSUE TITLE
Need to check this screen with UX.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3159]
-Need to check this screen with UX
![IMG_1883](https://user-images.githubusercontent.com/62699947/114381633-f4df0680-9ba8-11eb-8c96-2c2ca7f12279.jpg)

**Comment by cakesoft-swati** [comment]
- @summikhan11 Can you please update the UX link?
- I could not find the above screen in the specs link which is mentioned in the epic.

**Comment by cakesoft-rohit** [comment]
UX link - https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/screen/7df54f2d-1726-4329-9012-069178547e9f/

**Comment by cakesoft-swati** [comment]
-  Verified this issue on dev app v1.9.0(328)
