### ISSUE TITLE
Generating SM on the personal device

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3160]
1. When the user initially is at Level 1 (complete or not complete, the Savings account is inactive. On opening the Savings Account instead of the 2FA QR modal it shows a message that the user needs to upgrade to Level 2 to activate the Savings account. - Needs the modal message UX (may be there in the original Keeper UX). The Savings account is shown differently on the HS (look at UX for original Keeper requirement) 
2. The SM is generated on the Personal Device (in Level 2). And when Level 2 is completed the xPub and other details (not SM but one shard) needed for creating Savings Account is transferred to the main app for activating the Savings account. This should be pulled from the Savings when user goes in the Savings account so the user does not have to log in again to check if they have the data. When Level 2 is not completed, it will not even try to pull the data to activate it 
3. The logic of SM and its SSS shards remains the same as in 160 but will have to be done on the Personal Device and when 'approval' is being done, to add a Keeper, the relevant shard is sent from the Personal Device to the Keeper device
4. The 2FA secret and the flow remains the same (from the main app in the Savings Account). And on restore, the 2FA should have to be reset - i.e. the 2FA secret is not stored in the main app Wallet Image.

**Comment by ASN-BitHyve** [comment]
Closing as we have moved away from SSS
