### ISSUE TITLE
UI issues while restoring the wallet.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3161]
-When you touch them, they blink which makes it feel as though they are clickable but they are not.
![touchblink](https://user-images.githubusercontent.com/62699947/114395353-dfbea380-9bb9-11eb-9ed4-1a3aa037236e.jpg)

-Should be Personal Device and should not touch the Let Received tag
![Screenshot_20210402-205033_hexa dev](https://user-images.githubusercontent.com/62699947/114396514-4abcaa00-9bbb-11eb-855c-c488b6de2c5b.jpg)

**Comment by cakesoft-devika** [comment]
- Tested on Dev app v1.7.0 (286). As per the 2nd point, still showing secondary device instead of Personal device 
![Screenshot_2021-05-13-14-14-30-234_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/118102301-3f48e280-b3f6-11eb-836e-b8798e3ea8fe.png)

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (289)
