### ISSUE TITLE
Text change on Home screen and wallet security screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3177]
-“Cloud Backup complete, you can upgrade the backup to Level 2”. This kind of text should be used for all levels. And on both screens (Wallet Security screen and Home Screen). Note the text will be Cloud Backup, Double Backup and Multi-key Backup. With capital B in backup.
![cbc](https://user-images.githubusercontent.com/62699947/114681251-98582480-9d2b-11eb-8251-689bbe040ca5.jpg)

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(276)
