### ISSUE TITLE
Status of a levels

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3178]
1) The status of a level should be in ‘setup’ and therefore the grey colour as long as it is not completely setup. Once setup is done and one of the RKs become inaccessible then you move it to red. 
2) Also when it is red, the text on HS should be what is suggested for red status.
![level1status](https://user-images.githubusercontent.com/62699947/114681675-0270c980-9d2c-11eb-932b-c335ed29628c.jpg)

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(276)
