### ISSUE TITLE
Account Sync progress should have Account Screen in the background

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3184]
-Ideally this should be on the Account Screen.
<img width="375" alt="D6CB795B-9B1D-4B42-A8D0-92B16D7AED78" src="https://user-images.githubusercontent.com/62699947/109505124-497b6600-7ac2-11eb-81c4-d68cffcc870a.png">

**Comment by antuz123** [comment]
@Parsh - this may not be needed as we are doing it in pull down and not through the menu? 

If so it will only be a grey screen. 

Assigning this issue to you to close.
