### ISSUE TITLE
UI change on Upgrade screen

### ISSUE THREAD

**Issue by cakesoft-nikhita** [bithyve/hexa#3194]
1) Screen should go grey.
![original (1)](https://user-images.githubusercontent.com/37994396/114987820-388c8580-9eb3-11eb-935a-119938648640.jpg)
2) Not gDrive. ‘iCloud Backup’. Also, If we are backing up on the cloud, why do you need to select the backup. This is not a restore flow
![original (2)](https://user-images.githubusercontent.com/37994396/114988173-a638b180-9eb3-11eb-900e-1d4f7707e96b.jpg)
3) Heading: Cloud Backup Text 1: “Hexa will use the cloud to backup your wallet”. Add space after the text and the cloud backup grey thing. Remove the arrow in the end
![original (3)](https://user-images.githubusercontent.com/37994396/114988512-09c2df00-9eb4-11eb-83a5-0a1b14bcf832.jpg)

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
