### ISSUE TITLE
Full ReScan if not complete then hide

### ISSUE THREAD

**Issue by cakesoft-nikhita** [bithyve/hexa#3195]
If this is not completed, we need to hide this. Also the text is wrong. Check the text I have suggested in the issue.
![original (4)](https://user-images.githubusercontent.com/37994396/114988729-47276c80-9eb4-11eb-8d0f-45041f19b080.jpg)

**Comment by cakesoft-devika** [comment]
Closing this issue as it is present in v1.6.5(281)
