### ISSUE TITLE
1 Share OBHR to NBHR upgrade

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3206]
1 share(Contact): OBHR to NBHR Upgrade

Before Clicking Upgrade.

![IMG_1127](https://user-images.githubusercontent.com/7535475/115230821-c4e5b500-a10c-11eb-99fa-76016b84dacc.PNG)

After Clicking Upgrade:
![IMG_1128](https://user-images.githubusercontent.com/7535475/115230870-d202a400-a10c-11eb-9367-72b417b5d3e2.PNG)

![IMG_1129](https://user-images.githubusercontent.com/7535475/115230843-cadb9600-a10c-11eb-869a-ac2a5e63a6cb.PNG)

**Comment by AliMeer** [comment]
Old BHR screen should not be shown

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
