### ISSUE TITLE
Wallet Backup: Level 2 is not completing

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3207]
The Backup process is getting stuck at level 2. Even after confirming Personal Device 1 and a contact at level 2(as can be seen in my F&F screen), the shares aren’t turning green and therefore level 3 is kind of locked.

![Screenshot_20210419-171204](https://user-images.githubusercontent.com/17980466/115232434-51f03480-a134-11eb-972c-8da4d92e4fd7.jpg)
![Screenshot_20210419-171212](https://user-images.githubusercontent.com/17980466/115232445-54528e80-a134-11eb-9316-3a2786c94488.jpg)
![Screenshot_20210419-171217](https://user-images.githubusercontent.com/17980466/115232450-561c5200-a134-11eb-93af-bc2780054a7a.jpg)

**Comment by cakesoft-nikhita** [comment]
@Parsh Could you please check again? I can complete level 2 (1 cloud, 1 device, 1 contact) and (1 cloud, 1 device, 1 pdf)

**Comment by Parsh** [comment]
Update: I've tried it today as well and I'm still finding it hard to complete level 2. Especially the personal device health is behaving oddly, initially, it gets confirmed after acceptance of share by the Guardian but then the app sends a new keeper info updated notification to the guardian and then the expiry timer on my device again start appearing with health going to red on manage backup for the personal device.

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
