### ISSUE TITLE
Create Actions for Temporary Swan Account and later making it permanent

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3217]
Need action, Sagas, and reducers for creating a Swan Account Shell and maintaining it in a reducer. This will be maintained till all API calls to swan succeed. After all API calls are successful the temporary Swan Account Shell needs to be added as a permanent Account on the home screen. 

- Use branch https://github.com/bithyve/hexa/tree/swan to create a working branch

- Add action, saga to Implement these reducers: https://github.com/bithyve/hexa/blob/swan/src/store/reducers/SwanIntegration.ts#L36-L40

- The action to create a Swan account shell will be used here: https://github.com/bithyve/hexa/blob/a6a8b7a2607a4d31125db477eea82be5a999ade7/src/components/bottom-sheets/swan/BottomSheetSwanInfo.tsx#L73

- Write an action + saga to store the temporary swan account to make it a permanent account on home screen
- The store account action will be called here:  https://github.com/bithyve/hexa/blob/a6a8b7a2607a4d31125db477eea82be5a999ade7/src/components/bottom-sheets/swan/BottomSheetSwanInfo.tsx#L78

**Comment by cakesoft-devika** [comment]
@AliMeer Can you please verify this and update the ticket status.
