### ISSUE TITLE
Level 2 restore

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3226]
Not restoring with Level 2, one Personal Device and one cloud backup. 

The messages don't change on the wallet creation when restoring either.

**Comment by cakesoft-devika** [comment]
Issue replicated in staging app v1.6.0(277) with one Personal Device and one PDF backup.  
![Screenshot_2021-05-02-17-45-32-427_io hexawallet hexa](https://user-images.githubusercontent.com/75297509/116841547-2fabeb80-abf7-11eb-9867-2088f2756c8a.jpg)

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (286)
