### ISSUE TITLE
PDF confirmation 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3229]
It marks the PDF RK as accessible once I click on 'Yes, I have sent' without getting a confirm
action. A PDF after sharing needs a QR scan for the first QR to confirm accessible. 

- Did not let me send the PDF on Level 2, bit when I clicked that I have sent, it marked it complete. We need the user to confirm by scanning the QR. This step is needed only for pdfs
![c](https://user-images.githubusercontent.com/37994396/116033840-cc164100-a67f-11eb-9713-70c6cbc9d02a.jpg)

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
