### ISSUE TITLE
Text change on Request

### ISSUE THREAD

**Issue by cakesoft-nikhita** [bithyve/hexa#3230]
- Wrong Text. This is someone asking you to be the Keeper. Backup Request. Text: You have a request for securing the Recovery Key

![a](https://user-images.githubusercontent.com/37994396/116033535-3b3f6580-a67f-11eb-8e26-9314570d1711.jpg)

**Comment by cakesoft-devika** [comment]
Verified this issue on staging app v1.6.0(276)
