### ISSUE TITLE
ManageBackup model text change

### ISSUE THREAD

**Issue by cakesoft-nikhita** [bithyve/hexa#3231]
![b](https://user-images.githubusercontent.com/37994396/116033651-6c1f9a80-a67f-11eb-9f93-ad3f4c6b0b01.jpg)

**Comment by antuz123** [comment]
Replace Primary Keeper with ‘Personal Device’ in the three places. Setup in not capital S when in the text. Headline can be capital.

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
