### ISSUE TITLE
Disable share via link if contact is not available and text change also

### ISSUE THREAD

**Issue by cakesoft-nikhita** [bithyve/hexa#3234]
![aq](https://user-images.githubusercontent.com/37994396/116035428-99ba1300-a682-11eb-806c-dc4920f18435.jpg)

**Comment by cakesoft-nikhita** [comment]
@antuz123 Text for this model

**Comment by antuz123** [comment]
First fix the bug of contact not showing. 

Heading: Select Contact 
Text at top: Select contact to send a Wallet Restore request link 

no bottom text needed

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(277)
