### ISSUE TITLE
DH channels data sync

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3238]
1. The data may change from the F&F side, like the new FCM token on restoring in a new phone, so it should always be fetched when needed or fetched regularly and synced locally.
2. The restored data should always be the location and encryption key as the data may be dynamic and changed when it was not synced up.
3. Going forward this is very important as it may have a PSBT transaction to be picked up etc.

**Comment by Parsh** [comment]
Addressers:

1. The local copy syncs up w/ the channel on relay every time someone lands on the F&F screen as the saga to sync channels is called from there as of now. So it’s not like that the local copy is something static(if that’s what the concern is).
2. To address this we might want to shift that channel syncher saga to home that way it would be able to pick new stuff up as soon as user lands up on the home screen

**Comment by cakesoft-swati** [comment]
-Closing this issue as discussed with dev.
