### ISSUE TITLE
App crashes when add google account for backup

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3240]
It happens when adding google account which is not signed in to google drive.

**Comment by cakesoft-rohit** [comment]
Tried following scenarios to reproduce the issue
1. Create new account in the app while selecting account
2. Created new account outside the app and then use that account
3. Using account which is not logged in before in mobile and don't have drive access
4. Previously used account which already have json file uploaded but not currently logged in the app

I did not get any crash, tried on different simulator and physical devices
The app gets restart once, while testing but no crash

**Comment by cakesoft-devika** [comment]
- Closing this issue on Dev app v1.7.0 (288) as it is not reproducible.
