### ISSUE TITLE
Security Question 

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3244]
Level 1 : Clicked on Security Question. Went to confirm it. Confirmed the answer. Then got this page.

1) Remove Know More button
2) Remove the line " Hexa will remind you..." 
3) The plug image being used on a Successful page.
![File](https://user-images.githubusercontent.com/68264080/116354792-8d66bf00-a816-11eb-8c7b-d10b066713db.jpg)

**Comment by cakesoft-devika** [comment]
-Verified this issue on staging app v1.6.0(276)
