### ISSUE TITLE
Show logic for Contacts 

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3247]
- Show "Awaiting acceptance" on Skip contact
- After confirm contact/Keeper Show contact Name if exist or show WalletName

![File](https://user-images.githubusercontent.com/68264080/116360040-213b8980-a81d-11eb-98be-937f21af3323.jpg)

Change 1) Button: "f and f request awaitng 1" > " Awaiting acceptance"
Change 2)  In the message below Double backup: "f& f" > " F & F"

**Comment by antuz123** [comment]
Logic: Show Contact Name when available, else show Wallet Name, else show Awaiting Response text

**Comment by antuz123** [comment]
@AliMeer - I have added the logic/ details above. What of this is done by Shivani and what by Parsh, you can decide and split the issue accordingly.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.7.5(302)
