### ISSUE TITLE
Wallet Settings: Page freeze

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3249]
The wallet settings page freezes(no touch gets registered) once we start the blind sync. Irrespective of whether blind sync completes or we dismiss the scanning bottom sheet, the wallet settings page remain disabled.

![Simulator Screen Shot - iPhone 12 mini - 2021-04-28 at 16 31 24](https://user-images.githubusercontent.com/17980466/116393638-899b6280-a83f-11eb-868e-6b850d899178.png)
![Simulator Screen Shot - iPhone 12 mini - 2021-04-28 at 16 33 06](https://user-images.githubusercontent.com/17980466/116393643-8b652600-a83f-11eb-9baf-52b15f1c3c95.png)

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (286)
