### ISSUE TITLE
To be checked

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3254]
I have saved Anant's name as AT in my phone. But when Hexa detected it, it changed it into a t ( small letters). Why this happened needs to be checked.
![To be checked](https://user-images.githubusercontent.com/68264080/116453778-e36e4d80-a87c-11eb-87ec-5649c2041cf5.jpg)

**Comment by cakesoft-shashank** [comment]
Not able to reproduce. I created two contacts: AT and A T. For both this seems to be working fine.

![simulator_screenshot_E453A1C9-35B9-4226-869D-D968D68E3C53](https://user-images.githubusercontent.com/50690016/122531522-3672ae80-d03d-11eb-8869-1206d8b31110.png)
![simulator_screenshot_EC73C661-2461-40F0-B4C0-59BEB2F55EF8](https://user-images.githubusercontent.com/50690016/122531565-425e7080-d03d-11eb-997a-74de849c62d1.png)

**Comment by cakesoft-swati** [comment]
-Unable to reproduce tis issue on dev app v1.8.0(304)
