### ISSUE TITLE
Text Change after QR is scanned at level 3

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3257]
1) "Approve new setup" > "Share Recovery Key"
2) Remove the line, "Using the other device..."
![share Rec  Key](https://user-images.githubusercontent.com/68264080/116457042-8e343b00-a880-11eb-8237-36d98806e75d.jpg)

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (289)
