### ISSUE TITLE
Level 2>PDF Backup>Reshare button disabled

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3263]
"Reshare" button disabled when navigates to the "PDF Backup" screen for the second time without confirming the share.

![Screenshot_2021-04-30-12-59-13-672_io hexawallet hexa staging](https://user-images.githubusercontent.com/75297509/116663625-fedc7400-a9b4-11eb-975f-0451da0acffa.jpg)

**Comment by AliMeer** [comment]
If you have not shared it will be share
if you have shared you can reshare or change keeper
if you have confirmed you can change keeper

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (286)
