### ISSUE TITLE
Level 2 and 3: Tap on Share Recovery opens backup recovery window

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3281]
In Level 2 and Level 3, Tap on "Share recovery 1/2" open the backup recovery window when Level 1 not completed

![Screenshot_2021-05-04-12-28-14-881_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/116971787-b3d5a000-acd7-11eb-88dc-f8c3fee373a2.jpg)

**Comment by cakesoft-nikhita** [comment]
This issue is fixed on ButtonClick Branch. Once that branch is merged on dev it will available

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (283)
