### ISSUE TITLE
Showing badge for viewed notifications

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3303]
I viewed all notifications (e.gF&F) and reinstall the app. After restoring with the same wallet, Red badge showing over the notification icon.

![Screenshot_2021-05-07-15-40-55-190_io hexawallet hexa](https://user-images.githubusercontent.com/75297509/117438812-b2161180-af4f-11eb-9461-d5365ccc6266.png)

**Comment by cakesoft-swati** [comment]
-Restore is not working so I'll check this issue after it'll start working.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(330)
