### ISSUE TITLE
Level 1>Showing backup needs your attention when trying to set next level

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3317]
When share/confirm Personal device 1 in Level 2 then Level 1 asking to confirm a security question 

Step 1:
![Screenshot_2021-05-10-14-35-15-716_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/117637091-1d095780-b19f-11eb-8582-c957a977c297.jpg)

Step2:
![Screenshot_2021-05-10-14-37-57-429_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/117637128-24306580-b19f-11eb-8681-7d7e75b1e8d2.jpg)

Step3:
![Screenshot_2021-05-10-14-37-36-225_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/117637137-272b5600-b19f-11eb-9940-1d1d4bdc238b.jpg)

**Comment by cakesoft-shivani** [comment]
If we came after our time based expiry to setup new level need to confirm our share and in this case need to confirm security question

**Comment by cakesoft-devika** [comment]
OK, Noted.
