### ISSUE TITLE
Level 2>Backup using a PDF>"Store personal copy PDF" window fail to open

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3318]
"Store personal copy PDF" window won't open when select "Backup using a PDF" option and taps on the "Share Recovery Key" button.

**Comment by cakesoft-shivani** [comment]
Not Able to reproduce
![WhatsApp Image 2021-05-12 at 12 46 22 PM](https://user-images.githubusercontent.com/50820210/117934321-2e2da200-b320-11eb-941d-42eb8e0709b8.jpeg)
![Screenshot_20210512-124145_Android System](https://user-images.githubusercontent.com/50820210/117934367-3d145480-b320-11eb-9383-f4e5561002c9.jpg)

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (285). It is not reproducible now.
