### ISSUE TITLE
Showing irrelevant section when confirm security question on restore

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3319]
"Send OTP to Contact" section appears when closing the keypad after confirming the security question on the"Restore"

![Screenshot_2021-05-10-16-24-59-072_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/117650080-e38c1880-b1ad-11eb-93a5-be96ae4ac1cf.jpg)

**Comment by cakesoft-nikhita** [comment]
In Android, it happens it's not new issue its library issue of bottomSheet when Keyboard open and close it will show random bottomSheet but this behaviour is too fast. And we tried to fix this but it somehow library issue for Android

**Comment by cakesoft-devika** [comment]
- Closing this issue as it is a library issue for Android
