### ISSUE TITLE
Know More modals for on-ramps 

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3326]
Issue replicated on the following account details
1. Swan Bitcoin
2. Wyre Account
3. Ramp Account

![Screenshot_2021-05-11-11-02-48-185_io hexawallet hexa development (1)](https://user-images.githubusercontent.com/75297509/117763908-3961ce80-b249-11eb-8313-e4f39105b654.jpg)

**Comment by antuz123** [comment]
https://xd.adobe.com/view/e74a06be-c6d2-4ee1-a8aa-dc3c61d017f9-b219/grid

The UX is done with the content. 

Specs Link: https://xd.adobe.com/view/3ebba4c6-dfc4-4062-baa4-9f1fde256bc5-6be8/

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (292)
