### ISSUE TITLE
Notification Logic

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3332]
Show only the latest upgrade notification in the notification list. Currently, it is showing all the previous upgrade notifications.

**Comment by antuz123** [comment]
Not sure where the notification logic went but this is how it will be. 

1. Show a red dot on notifications and on the app icon whenever notification flag is true. This flag is defaulted to false and turned true every time there is a new notification. It is turned false whenever the user touches the notification icon and sees the messages list or an action notification turns on the message details automatically or the user opens a message by touching an out of app notification 
2. Messages are marked unread unless they are opened up and the details viewed. Messages being unread has no bearing on the red dot 
3. Action (urgent) notifications like upgrade is opened for the user as soon as they log in (broadcast message follows the cycle designed for it) 
4. When a user touches a out-of-app notification, the message body opens up when the app is logged in 


@cakesoft-shashank - most of this must be done but clarifying the requirements here

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.0(349)
