### ISSUE TITLE
App release broadcast 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3335]
Release notification (relay/ admin piece): 
1. Every release to have a release note that will be a copy of what is there on the App Store and GH
2. Only the latest one is important and is available on the Relay 
3. Each release note also has a MAN release number with it
4. When the note is put in, it also triggers a general FCM notification for all apps 'new update is available' 

Action on the app (app side): 
1. When an app opens (via. notification or otherwise) and there is a Release Note it fetches the same 
2. If the app = note version: No action, else if app version > MAN version then show upgrade notification with reminders possible (no need to keep a count), else (app version <= MAN version) show notification with no reminders possible 
3. Also look at the UX of the release note while doing this.
4. The app should take the message when type = broadcast and act as per the logic in the ticket 
 

Additional considerations:

Admin function to use the same function as any F&F notification where FCM notification is sent and the message centre is sent the message payload 

Issues related to this functionality:

1. Update relay database for storing release notes and user notifications - https://github.com/bithyve/hexa/issues/3476
2. Update relay endpoints or notifications - https://github.com/bithyve/hexa/issues/3477
3. Update release notes UX: https://github.com/bithyve/hexa/issues/3506

**Comment by antuz123** [comment]
#2547

**Comment by antuz123** [comment]
#3285

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
