### ISSUE TITLE
On Home>Text change for swan account

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3343]
Change "BTC" text into "Sats"

![screenshot_01](https://user-images.githubusercontent.com/75297509/117919884-7c847600-b30b-11eb-822c-80cc2b16c2c9.jpg)

**Comment by cakesoft-devika** [comment]
-Tested on Dev app v1.7.0 (289) and Issue still replicated
![Untitled 2](https://user-images.githubusercontent.com/75297509/118630164-ec9f6a00-b7eb-11eb-9643-52171223a592.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.7.5(299)
