### ISSUE TITLE
FBTC logo color needs to be their brand color

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3348]
We've used the brand colors of all the other merchants except FBTC. It needs to be their precise Orange.
![FBTC Logo](https://user-images.githubusercontent.com/68264080/117956903-20cfe200-b337-11eb-8fc1-24a93a2bdb28.jpg)

**Comment by cakesoft-rohit** [comment]
duplicate of https://github.com/bithyve/hexa/issues/3690
