### ISSUE TITLE
Space between the words Google and Drive

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3349]
![Capture](https://user-images.githubusercontent.com/68264080/117959271-773e2000-b339-11eb-9778-59fcf6f7df94.PNG)
![Reference](https://user-images.githubusercontent.com/68264080/117959340-88872c80-b339-11eb-9e84-6f19f82886da.PNG)

**Comment by cakesoft-devika** [comment]
@cakesoft-shivani Similar issue needs to be fixed on "Google Drive Backup" screen.

![Screenshot_2021-05-27-12-31-56-374_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/119781137-48eb4380-bee8-11eb-96f0-517b3c87da19.jpg)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.7.5(299)
