### ISSUE TITLE
Level 2/3>QR code not generating to send RK to contact

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3360]
![Screenshot 2021-05-13 at 1 48 57 PM](https://user-images.githubusercontent.com/75297509/118103141-33a9eb80-b3f7-11eb-8cd0-26f33ae4c050.png)

**Comment by cakesoft-rohit** [comment]
I'll check this

**Comment by cakesoft-devika** [comment]
- Tested on Dev app v1.7.0 (288) and Issue still replicated

![Screenshot_2021-05-17-13-20-42-164_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/118451930-5ac42e00-b713-11eb-89bb-5ad2b3d65d91.png)
