### ISSUE TITLE
Status, messages and colors derived from RK statuses

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#3365]
- Local health object handle
- Status management 
- Messages for levels

![Screenshot 2021-05-25 at 12 57 18](https://user-images.githubusercontent.com/7535475/119494126-db5cdd00-bd58-11eb-9776-31702b3b4b61.png)

![Screenshot 2021-05-25 at 12 57 24](https://user-images.githubusercontent.com/7535475/119494140-e0ba2780-bd58-11eb-81a3-e8b775954e39.png)

![Screenshot 2021-05-25 at 12 57 33](https://user-images.githubusercontent.com/7535475/119494160-e6177200-bd58-11eb-987d-1dd5c5a5859f.png)

**Comment by cakesoft-swati** [comment]
-Verifed this issue on dev app v1.7.5(301)
