### ISSUE TITLE
SM Shards stored on the Keepers and the Main App, Never on the shared channel

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#3366]
1) Need to add shard to cloud
2) Need to add separate shard not a part of RK

SM: Encrypted with a CH2 key. SM is encrypted with another key, not the CH key.
•During restore, Keeper shows the Recovery Key or sends the RK over the link. RK = CH Key + CH2 Key
•During Approval (change keeper or level change) or 2FA reset flow, the Keeper just shows the QR (Show Approval Key/ Show Secondary Key). Approval Key = CH ID + CH2 Key.
•This helps the requester/ ward get the SM and this is never stored locally in the requester/ ward app. So there is no need to upload and then download, the SM is also on the relay but encrypted with CH2 Key which is not on the requester/ ward app so that it can never access it independently.

**Comment by cakesoft-swati** [comment]
Bakend issue
