### ISSUE TITLE
Deeplink in email on Android - Assess Bitly solution

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3370]
Deeplinks sent in an email are not opening the app on Android.
This is because the Android email app is opening the link inside the email app, the deeplink opens the app correctly if used in a browser.

This is related to this issue.
https://github.com/bithyve/hexa/issues/3351

**Comment by cakesoft-devika** [comment]
- Tested on Dev app v1.7.0 (289) and Issue still reproducible.

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (292)
