### ISSUE TITLE
Buy UX changes 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3374]
The UX for buy journeys was reviewed and this is how the UX should be: 

Proto Link: https://xd.adobe.com/view/d97f9303-d123-44a2-b821-df9670411814-8c2c/grid

Specs Link: https://xd.adobe.com/view/6e89fcde-5787-4d1a-a1ba-c284e770fdad-3bda/

Look at the Buy Menu, Swan pop-up, Wyre and Ramp. The text needs to be what it is today in the app. The styling has to be followed from this.

**Comment by AliMeer** [comment]
2 screens are missing in the spec

**Comment by antuz123** [comment]
Check after new UX is implemented to see if this is still needed.

**Comment by cakesoft-rohit** [comment]
@antuz123  https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/screen/74205434-34a6-40d8-976a-ec45316f5226/
this specs link is currently implemented
But it does not include modal for FastBitcoin & GetBitter

In Ramp & Wyre modals, Account Type dropdown UX is not yet given

**Comment by antuz123** [comment]
Currently we will have only 2 options - Ramp, Wyre and FBTC

**Comment by cakesoft-rohit** [comment]
@summikhan11  ![Simulator Screen Shot - iPhone 11 - 2021-08-10 at 11 24 10](https://user-images.githubusercontent.com/74172232/128815321-8ba8855c-df8b-4840-9c99-ed237595a318.png)
This is how we have currently in our app on home screen temporarily
Only Get bitter model screen is not in UX

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(331)
