### ISSUE TITLE
Tap on any account crashes the app

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3375]
In live v1.6.5(281), touch on any account crashes the app when upgraded version in following manner: v1.4.4(226)>1.4.5(230)>1.4.6(235)>1.5.1(261)>1.6.0(277)>1.6.5(281)

**Comment by AliMeer** [comment]
Do we need to analyse and fix this scenario? Issue is or upgrading from v1.4.4.

**Comment by cakesoft-swati** [comment]
Closing this issue cause the upgrade scenario is not  in the app for now.
