### ISSUE TITLE
Live v1.6.5(281): Ramp account issues

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3377]
Case I: Not able to send from a Ramp Account. It shows sent successfully but the amount is not sent or received. The fee also stays constant for all options and does not change.

Case II: When restarting the app and now it let me send. Some data was persisted in the Send flow

**Comment by AliMeer** [comment]
This was reported as a bug. Once add new account for on ramp accounts is done this can be retested.

**Comment by antuz123** [comment]
Test with Deposit Account

**Comment by Parsh** [comment]
Should be resolved via Deposit account.

**Comment by cakesoft-swati** [comment]
- Verified this issue.
