### ISSUE TITLE
Account Settings>Showing same icon

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3380]
On all account settings page, same icon is showing for "Account Sync" and "Account Visibility"

![Screenshot_2021-05-17-15-44-10-448_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/118475062-6b7f9e80-b729-11eb-99b7-a90f0ad922d8.jpg)

**Comment by cakesoft-nikhita** [comment]
@Anant @AliMeer for Account sync icon is not spec out

**Comment by antuz123** [comment]
@summikhan11 - pls add the link

**Comment by cakesoft-swati** [comment]
Still I can see the same icon for  for "Account Sync" and "Account Visibility".
-Tested in dev app v1.7.5(301)

**Comment by cakesoft-rohit** [comment]
@summikhan11  can't find a spec link for this UX
