### ISSUE TITLE
Account Management>Text change

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3381]
Incorrect text showing on following modal:
1. Unhide Account
2. Successfully Unhidden
3. Restore Account
4. Successfully Restore

![Screenshot_2021-05-17-15-24-00-104_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/118480094-6c1b3380-b72f-11eb-878c-ffdeedf081c4.jpg)

![Screenshot_2021-05-17-15-25-57-479_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/118479608-db445800-b72e-11eb-8557-d77100df5b82.jpg)

![Screenshot_2021-05-17-15-37-01-252_io hexawallet hexa development (1)](https://user-images.githubusercontent.com/75297509/118479644-e8f9dd80-b72e-11eb-9e1d-5358ef42c933.jpg)

![Screenshot_2021-05-17-16-07-51-545_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/118479684-f44d0900-b72e-11eb-9f78-2071d746c040.png)

**Comment by cakesoft-nikhita** [comment]
@antuz123 Please suggest text for this models

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (290)
