### ISSUE TITLE
Text Changes - Security Question Confirmation

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3386]
Changes:
Line 1: Security Answer confirmed
Line 2: Answer backed up successfully

![C1](https://user-images.githubusercontent.com/68264080/118593835-fca45300-b7c5-11eb-933b-ac5e5c140ee6.jpg)

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (290)
