### ISSUE TITLE
Text Change and image issue in Sent Successfully screen

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3387]
1) Should be t-sats and not bitcoin.
2)  The image below is getting cut.
![c2](https://user-images.githubusercontent.com/68264080/118594699-7ab52980-b7c7-11eb-990c-dc4a9b3a4149.jpg)

**Comment by cakesoft-devika** [comment]
- Tested on Dev app v1.7.0 (290) and Issue still reproducible.

![Screenshot_2021-05-19-15-43-49-226_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/118797503-48d0bf80-b8ba-11eb-912a-6e77bd74aa38.png)

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (293)
