### ISSUE TITLE
Send and receive names

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3388]
I sent some tsats to Swati. I think it should mention Swati's name here and not Test Account. Thus the wallet should: 1) Detect the name of the person sats are being sent to. 2) Display the name in the relevant area. If one transaction has many people, we can consider using "/" to give few names and then "+7" or "+3" if there are more. 
![C3](https://user-images.githubusercontent.com/68264080/118595057-06c75100-b7c8-11eb-8844-3779a0ca6459.jpg)

**Comment by antuz123** [comment]
This will happen with Transaction population...

**Comment by cakesoft-shashank** [comment]
@antuz123 currently sender name is shown

**Comment by cakesoft-swati** [comment]
@Shashank I can see names instead of account names but it is visible only on receiver side(as you mentioned "sender name" above) not on sender side. It should be visible on both the sides i.e. sender and receiver.

**Comment by cakesoft-swati** [comment]
- As discussed with shashank there is another  issue for receiver.Now I can only see the sender name so closing this issue.
