### ISSUE TITLE
Keeper should download SM Shard

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3391]
When accepting keeper only SM Shard should be downloaded to the keeper device. The rest of the recovery key should not be downloaded and should remain on the permanent channel.

**Comment by Parsh** [comment]
@antuz123 Can you confirm this? As far as I remember we just want the keeper to hold the channel key 2 and provide back during recovery while SM share(like PM) remains on the server.

**Comment by antuz123** [comment]
Correct, no need to download
