### ISSUE TITLE
New 2.0 UX

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3393]
New UX upgrade for 2.0

**Comment by cakesoft-rohit** [comment]
Links-
https://xd.adobe.com/view/d97f9303-d123-44a2-b821-df9670411814-8c2c/screen/38c93fba-1367-495d-b49a-96c8c1dcb534
Spec https://xd.adobe.com/view/6e89fcde-5787-4d1a-a1ba-c284e770fdad-3bda/

**Comment by AliMeer** [comment]
@cakesoft-rohit 

Look at the last screen in all these XD files:

5 Friends & Family
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/
4 Portfolio Add Account Buy
https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/
6 More Settings
https://xd.adobe.com/view/902817ab-b10b-4f5e-8991-1f2142fd4a84-c57b/
7 Manage Backup
https://xd.adobe.com/view/3c76a519-ed48-4944-a7a5-026a2aca5a6d-6925/

**Comment by antuz123** [comment]
Check modals in all epic links...

**Comment by cakesoft-swati** [comment]
- Verified this issue on app 2.0.0(365) with dev.
