### ISSUE TITLE
Cross version and backward compatibility simplification

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3394]
Cross Version:

- [x] For existing contacts, the version number updates in the channel as soon as the contacts update their apps, we should also update the version number in-app history and WI.
- [x] Instead of having a server module mediating the incompatibility call, the older version apps try to process the F&F requests and if fails shows the incompatibility message by default

Backward Compatibility

- [x] The recovery keys have version number embedded in them at the time of creation itself

**Comment by antuz123** [comment]
@AliMeer - again no tagging. We will miss it out as it does not appear in any release and will never come up for prioritisation

**Comment by Parsh** [comment]
Not sure what needs to be done here.

**Comment by Parsh** [comment]
On app update, the version history is updating however there's something odd with the version display box in the app-info section(as can be seen in the screenshots attached) that might need a fix.

![Simulator Screen Shot - iPhone 12 mini - 2021-08-23 at 17 42 55](https://user-images.githubusercontent.com/17980466/130445293-3256c815-f51a-4cf9-93e2-6ae5f230e741.png)
![Simulator Screen Shot - iPhone 12 mini - 2021-08-23 at 17 42 59](https://user-images.githubusercontent.com/17980466/130445305-a25240af-7e04-4004-b934-342506a563f2.png)

**Comment by Parsh** [comment]
Also, I'm not sure of whether the WI is being updated w/ the new version number when the app updates. Someone who worked on WI would need to confirm that.

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed wih dev.
