### ISSUE TITLE
Not able to receive sats on swan account

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3396]
![Untitled5](https://user-images.githubusercontent.com/75297509/118670330-22f0df80-b814-11eb-926e-0c66ffb4fc09.png)

**Comment by cakesoft-swati** [comment]
- Still not able to receive sats on swan account.

**Comment by Parsh** [comment]
Not sure how I can help here. @antuz123

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.95(330).Able to receive sats in Swan account.
![Screenshot_20210823-120513](https://user-images.githubusercontent.com/62699947/130401693-658f3eae-0782-46f6-a18d-8eddadbbe31f.jpg)
