### ISSUE TITLE
Shared Channel data on the Relay

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3398]
- Modifying permanent channel schema on relay
- Updating relay APIs to use new schema

**Comment by antuz123** [comment]
### **F&F Data** 

**Unencrypted:**
- New Flag 
- Version Number 
- Timestamp 
- Active Flag 
- CH ID 

**CH Key Encrypted:** 
- Payment Addresses (Key-value pair): Test and Checking for now 
- Wallet ID
- FCM Token 
- Wallet Name 
- Relationship Type 

**Keeper Data (Backup Data)** 
CH Key Encrypted: 
- PM Shard (enc with ans) 
- Validator
- Creation timestamp
- Question ID 
- Question text (if ID = -1) 
- Scheme/ Level  
- Keeper Info/Index: List of Keepers 
- Share ID 

**CH 2 Key Encrypted:**  
- SM Shard (enc with ans) 
- BH xPub (enc with ans)

**Comment by antuz123** [comment]
User Keys: 
- Show Recovery Key = Channel ID + CH1 Key 
- Show Approval Key = Channel ID + CH2 Key
