### ISSUE TITLE
Share Recovery Key and Share Approval Key

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3407]
show Recovery Key and show Approval Key on contact details page

**Comment by cakesoft-swati** [comment]
check approval key at level 3 or at 2FA and recovery key at the time of restore

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.7.5(303)
-It worked for Level 3 and PDF but it didn't work for 2FA reset. For 2FA reset there is another issue reopened so closing this issue.
