### ISSUE TITLE
Send to F&F (from details or from send flow)

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3410]
Send to F&F (from details or from send flow)

**Comment by Parsh** [comment]
@cakesoft-swati Right now the send to F&Fs would only work from the test account(as checking acc is broken when it comes to sending to trusted contacts). Also, the send button on the details page of a given contact would select test account by default for the send instead of checking for now.

**Comment by cakesoft-swati** [comment]
> @cakesoft-swati Right now the send to F&Fs would only work from the test account(as checking acc is broken when it comes to sending to trusted contacts). Also, the send button on the details page of a given contact would select test account by default for the send instead of checking for now.

This is workin now.Tested on dev app v1.7.5(300)
