### ISSUE TITLE
Add a new F&F and Keeper

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3411]
- Add a new F&F
- Add a new Keeper
- Mak an existing F&F a Keeper

Add new F&F would most probably remain the same if state and reducers continue to have the same data.
Need to consider user same trusted channel mechanism for sharing RK to all types of keepers
Review the journeys related to Keeper and making changes based on new communication mechanism using trusted channel

**Comment by cakesoft-shivani** [comment]
1) Changes for contact and device create channel
2) Encrypt sm share with ch2 key
3) Accept Request by qr scan and link
4) Fetch last seen and update status to accessible after process complete

**Comment by cakesoft-shivani** [comment]
1) Changes for contact and device create channel [Done]
2) Encrypt sm share with ch2 key (Issue #3436) [Done]
3) Accept Request by qr scan and link [Done]
4) Fetch last seen and update status to accessible after process complete [Done]

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app 1.7.5(300)
1.Can add new F&F.
2.Can add New Keeper.
-Mak an existing F&F a Keeper-this will be covered in another issue.So closing this issue .
