### ISSUE TITLE
2FA reset - update WI

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3414]
2FA reset - update WI

- Reset 2FA by scanning approval key 
- If we already have secondary mnemonics then ask for confirm question n continue to reset 2FA without approval key

**Comment by cakesoft-swati** [comment]
check reset with level 1 and level 2

**Comment by cakesoft-swati** [comment]
-2FA reset is not working as described. On both levels i.e on Level 1 and Level 2 it asks for confirm question.
- For level 1 it should ask for Confirm Question.
- And for level 2 it should ask to scan the approval key.

**Comment by antuz123** [comment]
2FA secret is stored in WI when reset is done (SM is not stored in WI)

**Comment by cakesoft-swati** [comment]
- Reset 2fa is not working as expected.
- In Level 1, it should be reset using the password and pin. It is still asking for the Exit Key from the PDF when there is no PDF.This is happening on the live app

**Comment by Parsh** [comment]
Fixed the Reset 2FA part, also the transactions from 2FA based accounts were failing, they've been fixed as well.

**Comment by cakesoft-swati** [comment]
- We are no longer allowing access to the Savings Account without completing Level 2. So at level 2 it is asking to scan the exit key, where it should ask to scan the approval key.

**Comment by cakesoft-swati** [comment]
- As per the dev approval key and exit key bothe are same.So I tested it on dev app v2.0(351.I can scan the approval key but it is taking time to show the new QR code.

**Comment by cakesoft-shivani** [comment]
This might be because of Network speed. Not able to reproduce my side
