### ISSUE TITLE
Show messages on HS and show message details 

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3418]
Show messages on HS and show message details 
https://xd.adobe.com/view/d97f9303-d123-44a2-b821-df9670411814-8c2c/screen/d7132061-7777-4bc4-9f4e-b4f995a7008b

**Comment by antuz123** [comment]
@cakesoft-swati - can you describe what the issue is here? 

@AliMeer - the issue is not clear... what was expected here.

**Comment by cakesoft-swati** [comment]
-This is related to Upgrade notification.Earlier it was visible before the login screen.As per the UX it should be on the Home screen.
