### ISSUE TITLE
F&F confirmation message

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3419]
F&F acceptance confirmation notification (end of acceptance flow)

**Comment by cakesoft-swati** [comment]
- Not getting any message or notification for F&F confirmation on dev app v 1.7.5(303)

**Comment by cakesoft-swati** [comment]
-Still not getting the F&F confirmation message. 
- Tested on dev app v1.8.0(304)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.0(315)
