### ISSUE TITLE
Changes in RK structure 

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#3433]
- Change RK structure
- Remove SM metashre Generation 
- Keeper info structure update

### Keeper Data (Backup Data)

**CH Key Encrypted:** 
- PM Shard (enc with ans) 
- Validator
- Creation timestamp
- Question ID 
- Question text (if ID = -1) 
- Scheme/ Level  
- Keeper Info/Index: List of Keepers 
- Share ID

**CH 2 Key Encrypted:**  
- SM Shard (enc with ans) 
- BH xPub (enc with ans)

**Comment by cakesoft-swati** [comment]
-This issue is for dev reference.
