### ISSUE TITLE
Swan Authentication>Deeplink not showing permission again once canceled

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3439]
Dev app v1.7.0 (292): "Authorize Hexa Wallet" doesn't show the permission again once canceled it. To view it again I need to go in-app and proceed with the swan account.

**Comment by AliMeer** [comment]
@cakesoft-swati either lets re test this. the button wont show the permission again if you deny it. User will have to go to the email again.

**Comment by cakesoft-swati** [comment]
-Able to reproduce this issue on dev app v1.8.0(304)

**Comment by cakesoft-swati** [comment]
- Still having the same issue in dev app 1.8.5(326).
- "Authorize Hexa Wallet" doesn't show the permission again once canceled it. To view it again I need to go in-app and proceed with the swan account.If I cancel and click on Open again, then I am getting this error.
<img width="375" alt="F6430C43-D7E9-4224-B32A-F08C1BCA4A8F" src="https://user-images.githubusercontent.com/62699947/127863585-e2397ec2-4aa2-49f6-8258-26e47af4813b.png">
- This is happeing only in ios device.
- Tested on iphone 7.

**Comment by cakesoft-shashank** [comment]
not able to reproduce

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v 2.0.75(455)
