### ISSUE TITLE
QR and scanner requirements 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3451]
QR thoughts:

1. Every QR should have QR type and version number 
2. This other than the payload for the specific 
3. The QR should show a Hexa logo in the centre with the QR type
4. QR types so far: Bitcoin Address, Testnet Address, F&F request, Keeper request, Recovery Key and Approval Key
- For Bitcoin and Testnet addresses, make sure that the type or version does not interfere with the scanning of the QR on another app 

6. Testing: All scanners in the app should be able to scan all QRs 
7. Testing: External scanners (non Hexa) should be able to scan the address QR (Receive) from Hexa - with or without amount

**Comment by cakesoft-swati** [comment]
- Verified this issue o dev app v1.8.0(322)
- All scanners in the app are able to scan all QRs.
- External scanners are also able to scan the address QR from Hexa-with or without amount.
