### ISSUE TITLE
Home Screen activities

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3456]
Add an on focus event to home screen for actions which need to be called whenever user lands on home screen. This should be triggered every time user navigates to home screen from another part of the app.

The actions to be done when landing on Home Screen every time are:

- Fetch exchange rate for user's currency
- Fetch transaction fees
- Fetch BTC exchange rate delta
- Update last seen

When landing on HS after launching APP(Directly Open)

In addition to the above:
- Show notifications.

Following should be moved out:

- Move fetching notifications to Launch screen
- Move DB decryption to loader messages screen
- FCM check and update to be moved to loader screen

**Comment by AliMeer** [comment]
on Focus in HS is here:  https://github.com/bithyve/hexa/blob/37aa75b6ee9b1ab88916d2cb4b9877d2ca90046b/src/pages/Home/Home.tsx#L1374-L1379

Anything else that needs to be called when visiting the home screen can be added here

**Comment by cakesoft-swati** [comment]
This is dev task.Closing this issue as discussed with Nikita.
