### ISSUE TITLE
Login ReLogin Scenarios

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3457]
![Screenshot 2021-05-24 at 11 04 46](https://user-images.githubusercontent.com/7535475/119332142-19d29900-bc80-11eb-8611-d32b94f2e4c5.png)

This is the overall requirement for Login and Re Login scenarios.
Following are the individual issues that will complete this functionality.

1. Add background state management capability for IOS and Android: https://github.com/bithyve/hexa/issues/3425
2. Modularise deep link code to be used from launch, login and home screen:  https://github.com/bithyve/hexa/issues/3454
3. Fetch Exchange rate for only user currency: https://github.com/bithyve/hexa/issues/3448
4. Exchange rate change in the last 24 hours: https://github.com/bithyve/hexa/issues/3449
5. Last active time: https://github.com/bithyve/hexa/issues/3455
6. Re distribution of current home screen activities: https://github.com/bithyve/hexa/issues/3456
7. Wallet Checkin changes: https://github.com/bithyve/hexa/issues/3458
8. App to fetch exchange data directly: https://github.com/bithyve/hexa/issues/3459

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.7.5(301)
