### ISSUE TITLE
QR>Receive bitcoin>UI issue on Android

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3463]
Account drop-down list is not easily scrollable under the "Receiving To" section

![IMG_20210525_125003](https://user-images.githubusercontent.com/75297509/119456838-afd9f280-bd58-11eb-9a0b-8417872c6bd2.jpg)

**Comment by cakesoft-swati** [comment]
Able to reproduce this issue on dev app v1.7.5(301)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.7.5(302)
