### ISSUE TITLE
Account>Send to Contact>Watermark text truncated on "Amount" field

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3465]
On Android devices, Watermark text: "Enter amount..." looks truncated when clears amount field on "Send to Contact" screen

![image](https://user-images.githubusercontent.com/75297509/119483847-07855780-bd73-11eb-81c5-3bc5712a60eb.png)

![image](https://user-images.githubusercontent.com/75297509/119484002-37ccf600-bd73-11eb-829f-7c9bff5871cb.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.7.5(295)
