### ISSUE TITLE
Android: On Send>Showing blank section when allowing QR permission 

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3475]
Allowing the permission showing a blank section instead of an opening QR scanner on the "Account>Send" screen

![Screenshot_2021-05-27-11-57-16-505_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/119779285-248e6780-bee6-11eb-8d7b-47897ff9b920.png)

**Comment by cakesoft-swati** [comment]
-Unable to reproduce this issue.
-Tested on android device SAMSUNG A50
