### ISSUE TITLE
Ability to make an existing contact a keeper

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3494]
Ability to make an existing contact a keeper
 - Permanent channel is already established between contacts
 - Only additional information to pass is to make the contact type a guardian
 - The guardian will need to accept the request for the backup to be succesful

**Comment by antuz123** [comment]
@cakesoft-shashank 

1. A contact selects a recovery key option in the security screen
2. It is currently given an option in 'Backup Recovery Key' screen to select - backup with a contact, device or pdf. 
3. On this screen there will be an additional option 'Backup with an exiting contact' and the existing contacts (non Keepers) will be shown there. This new screen will be done by UX 
4. If the user selects an existing contact then the Recovery Key is stored in that channel and a *action* notification for the other person to accept the Keeper request 
5. If the other person accepts the request, the contact type is changed to a Keeper (not just F&F) and the success notification is sent back. 
6. If declined, a declined *action* notification is sent back and the initial user deletes the Recovery Key from the shared channel 

In this flow most of the functionality is reused including screens and notifications etc. There is only one new screen which will come from UX. if you find any new piece (frontend or backend) that you think is needed new then we should discuss

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/3c76a519-ed48-4944-a7a5-026a2aca5a6d-6925/screen/43aec3f9-de30-43ca-96cf-a22de90c51aa/

**Comment by summikhan11** [comment]
not sure what to do here?

**Comment by cakesoft-rohit** [comment]
@summikhan11 
https://xd.adobe.com/view/3c76a519-ed48-4944-a7a5-026a2aca5a6d-6925/screen/43aec3f9-de30-43ca-96cf-a22de90c51aa/specs/
In this screen we need 'Choose from contacts' instead of 'Add new contact'

**Comment by summikhan11** [comment]
link updated
https://xd.adobe.com/view/3c76a519-ed48-4944-a7a5-026a2aca5a6d-6925/screen/43aec3f9-de30-43ca-96cf-a22de90c51aa/specs/

**Comment by cakesoft-swati** [comment]
- For now we removed the existing contact keeper flow.
