### ISSUE TITLE
Donation account issue when user aborts the process.

### ISSUE THREAD

**Issue by cakesoft-utkarsh** [bithyve/hexa#3495]
If the user aborts the donation and still does a transaction from any wallet, donor info will be lost.

Donor info is sent to relay every 2 seconds from the Waiting for donation screen. And server only saves the the info when relay confirms the transaction.

**Comment by antuz123** [comment]
Under the donation account properly from Swati and see what is remaining

**Comment by cakesoft-shashank** [comment]
Not applicable now
