### ISSUE TITLE
Donation web view>UI issues

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3497]
On Android devices:
1. Settings icon should slightly right-aligned on the "Donation Webview" modal
![Screenshot_1](https://user-images.githubusercontent.com/75297509/119953997-2fb3c700-bfbc-11eb-98c0-54a5018e0091.png)

2. There is no space between a screen name and "Save" button on the "Web View Settings"
![Screenshot_2](https://user-images.githubusercontent.com/75297509/119954045-3b06f280-bfbc-11eb-83ff-a1ecf2ffa887.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.7.5(300)
