### ISSUE TITLE
"Donation Webpage" button truncated

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3500]
On "Donation Account Details", "Donation Webpage" button looks truncated when more than one transaction history created

![Screenshot_2021-05-28-17-48-12-575_io hexawallet hexa development](https://user-images.githubusercontent.com/75297509/119983895-66023e00-bfde-11eb-8cb3-d2cf3917c1a9.jpg)

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.7.5(300)
