### ISSUE TITLE
Donation account screen does not match to XD design

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3501]
![image](https://user-images.githubusercontent.com/75297509/119985472-4cfa8c80-bfe0-11eb-9d24-5d4bb6906707.png)
![Screenshot_4](https://user-images.githubusercontent.com/75297509/119985650-8d5a0a80-bfe0-11eb-83f7-a0b6d55e199f.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(455)
