### ISSUE TITLE
Remove Trusted Contact

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3505]
- All contacts on the F&F screen are removable and should appear under the expired category once removed(could later be re-activated)
- Once removed, the channel is deactivated(top-level active flag turned false), the encryptedBackup(PM shard) & secondaryEncryptedData(SM shard) is removed and a removal notification is delivered to the contact.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.7.5(300)
