### ISSUE TITLE
UX 2.0 - Modals thumb rule

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3512]
Modals thumb rule:

- Know More
- Error messages
- Success messages
- Alerts
- Permission messages
- Loader messages
- Pin/ answer confirmation
- Info messages
- Optional selection - like custom fee

**Comment by antuz123** [comment]
Need heights for these as two standard types

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(339)
