### ISSUE TITLE
Notification types

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3513]
The message centre along with notification capability should support the following message types:

1. F&F request response - this can be accepted or rejected. CTA = Ok
2. F&F Keeper request - making the F&F as a Keeper. CTA = Accept/ Reject
3. F&F transaction - a txn made from a contact. CTA = Go to Account
4. Release Broadcast - a release broadcast is avaIlable and triggered from Relay. CTA = Upgrade

  // FNF_REQUEST_ACCEPTED
  // FNF_REQUEST_REJECTED
  // FNF_KEEPER_REQUEST
  // FNF_KEEPER_REQUEST_ACCEPTED
  // FNF_KEEPER_REQUEST_REJECTED

**Comment by cakesoft-swati** [comment]
-Closing this issue as discussed with dev.
