### ISSUE TITLE
Screen issue when the app is in the background

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3517]
1. When the app is in the background the displayed screen seen is blank. Instead, display the screen that the user had last left on or display a screen with a static logo without animation, whichever is possible.
2. When the user returns back to the app by tapping on the app screen in the background, display a screen with static logo. In the current situation it opens the splash screen but the animation doesn't complete. This issue is inconsistent as follows:
    - When the user returns to the app instantly or within 1 or 2 minute then no splash screen is seen.
    - When the user returns to the app after 5 min then a blank screen(without any animation on it) splashes for a fraction of a second and user is landed on the login screen.
    - When the app in on the automated cloud backup error popup then in that case when you return to the app the splash screen with incomplete animation appears. But not always.
3. Issue 1 is not consistent across various devices.
    - On Samsung Galaxy M21 with 4Gb Ram size, blank screen not seen when app is in the background.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(330)

**Comment by antuz123** [comment]
The app is not locking when it comes from the background. It should get locked after 10 seconds
