### ISSUE TITLE
Account sync post login

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3521]
### Description: 
Epic link:: https://github.com/bithyve/internal-docs/issues/75
1. Account sync should happen on loader screens post login. 
2. Sync all the transactions and calculated balances for each respective account.
3. The user will be landed on the home screen only after the account sync is complete.
4. This will be only for accounts on the first page (first 4 accounts)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.7.9(312)
