### ISSUE TITLE
F&F: QR based comm flow

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3527]
Following have not been done out of issue #3337

Requester:
5. The requester confirms that the QR has been scanned 'Done'
6. The app checks for the active flag from the contact's side on the channel

The above two happen on the pull-down of the F&F screen. Would be done once the new UI is in place.

Approver:
4.4. FCM notification isn't being sent yet. Would be in place once the message center is ready.

QR code image should have Hexa Logo and QR Type (would need some assistance with the UI work)

**Comment by antuz123** [comment]
@cakesoft-shashank - this is where you are fixing the issue relating to the QR scanning and process following that

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
