### ISSUE TITLE
Message modal categories and modal behavior templates

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3532]
### Description:
Epic Link: https://github.com/bithyve/internal-docs/issues/92

**1. Loader message modals**
- Tapping outside the modal to exit from it should not be supported
- No cross button to exit/close the login loader message modals. For the other loader message modals we might allow user to close the modal. For e.g. during the login loaders, we don’t want the user to stop the loading. So there will be no cross button as there is nothing the user can do without loading. 
On the other hand when the user does ‘Manual Sync from settings’, which is an optional step and the user may cancel the sync at any time, if its taking too long. In that case, the user just gets back to the settings screen. 
The process is aborted where it is. So the decision will be based on which process can be aborted and there is a equilibrium state for the app and which processes cannot/ should not be aborted

**2. One step action modals**
- A cross button to exit/close the modal
- Tapping outside the modal to exit from it should not be supported
- Either the user will perform the action or tap on cancel/cross button to return to the screen

**3. Know more/info modals**
- Cross button to close the modal
- Support tapping outside the modal to exit from it

**4. Toaster messages**
- Display these at the bottom of the page as an overlay on the screen
- Will display for a few seconds and vanish away automatically. No need for the user to close them.

### Modal proportion options
TBD

### Specs Links:
Loader message: https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/d4106792-2405-491a-8c54-5ebd17a9b810/

**Comment by summikhan11** [comment]
Loader message: https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/d4106792-2405-491a-8c54-5ebd17a9b810/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.1(375)

**Comment by antuz123** [comment]
Check if the modals are behaving properly when coming from background @cakesoft-shivani

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(463)
