### ISSUE TITLE
Auto reshare new RK with same Keeper on 2nd level for level 3 setup

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#3537]

**Comment by cakesoft-swati** [comment]
Check level 3 is getting complete or not.

**Comment by cakesoft-swati** [comment]
-Not able to complete level 3.After scanning the secondary key QR, the approval model is not showing up

**Comment by cakesoft-swati** [comment]
- verified this issue on devapp v1.9.5(337)
