### ISSUE TITLE
Combine initial wallet backup and security question modal together

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3542]
### Description: 
Epic Link: https://github.com/bithyve/internal-docs/issues/75

When a user installs a new app, the initial cloud backup modal that appears is to be combined with the security question and answer modal. 
Page Title will be: "Initial Cloud Backup"
Description for will be: "Create initial wallet backup on your iCloud/Google Drive. This can be changed later from the Security Centre." `Note: remove iCloud from description for android users and Google Drive for iOS users .`
Subtitle will be: "Encrypt your wallet"
Under the subtitle there will be these 2 options:

_Option 1:_ Text/Title for option 1 will be "Use answer to a Security Question (Easier to remember)"
Security question dropdown with question selected by default

_Option 2:_ Text/Title for option 2 will be "Use your own encryption password" (there will also be an option to provide a hint for that password)

CTA on this screen is Proceed and Skip Initial Backup.
If skipped the user is given a warning: "You have chosen not to backup your wallet which may lead to loss of funds if you lose access to the Hexa app." There they can choose ‘I don’t want a backup’ or ‘Create backup’.
Remove the bottom note saying "This answer is used ........."

UX Links:
TBD

**Comment by summikhan11** [comment]
Specs link: https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/aa9c8b8b-04f8-4963-908a-915a8ba70006/
