### ISSUE TITLE
Identify possible issues occurring for offloaded apps and solutions to handle them

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3547]
### Description:
Identify possible issues or errors occurring incase of offloaded apps and find solutions to handle them.

iOS related issues:
1. Unable to reinstall offloaded apps: https://discussions.apple.com/thread/8644724
2. Problem in offloading the app: https://discussions.apple.com/thread/251233581
3. Problem recovering offloaded app data: https://www.reddit.com/r/applehelp/comments/787usz/problem_recovering_offloaded_app_data/

**Comment by cakesoft-priyanka** [comment]
@cakesoft-swati please test offloading the app and report the possible issues.

**Comment by cakesoft-swati** [comment]
- Verified this offloading issue with Shashnk.
