### ISSUE TITLE
F&F details screen

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3556]
### Description:
1. Use different icons for "Help Restore" and "Show Secondary Key"
2. CTAs on this screen:
- Before approval: Re-share, remove
- After approval: Share Recovery key, Share Approval key, Send Bitcoins, edit contact details (associate a new contact here), Remove contact
3. Info on this screen: contact status, contact details, last seen time stamp, relationship (Keeper/ F&F etc.), when created time stamp, contacts wallet ID and contacts wallet name

**Comment by summikhan11** [comment]
where do the first set of CTA's appear? @antuz123

**Comment by cakesoft-rohit** [comment]
Specs Link: https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/2647eb6d-ef18-47c2-8c54-3a063a344b71/

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/a75f84eb-9ba1-4455-8906-873eef142768/

**Comment by cakesoft-swati** [comment]
**F&F details screen:**
- CTAs on this screen:
1.After approval: Share Recovery key, Share Approval key, Send Bitcoins, edit contact details (associate a new contact here), Remove contact
- **After approval I did not see any Remove contact option.**

2.Info on this screen: contact status, contact details, last seen time stamp, relationship (Keeper/ F&F etc.), when created time stamp, contacts wallet ID and contacts wallet name
-  **when created time stamp is also not there.**

**Comment by cakesoft-shivani** [comment]
- [ ] contact status 
- [ ] contact details
- [ ] last seen time stamp
- [ ] relationship (Keeper/ F&F etc.)
- [ ] when created time stamp
- [ ] contacts wallet ID and contacts wallet name

**Comment by cakesoft-shivani** [comment]
Need to add created timeStamp on creation @Parsh

**Comment by Raheel1258** [comment]
When created timestamp is remaining in contact data. @Parsh

**Comment by cakesoft-swati** [comment]
- When created timestamp is still remaining in contact data.
- Tested on dev app v2.0.75(455)

**Comment by Raheel1258** [comment]
there*

**Comment by cakesoft-swati** [comment]
![temp - 2022-05-05T152541 019](https://user-images.githubusercontent.com/62699947/166901133-0745e765-8866-40a5-90bc-eef03684ea53.jpg)
- "When created timestamp" appears twice

**Comment by GourabSanyal** [comment]
https://github.com/bithyve/hexa/pull/5756

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(485)
