### ISSUE TITLE
App Info

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3557]
### Description:
1. In App Info (currently App Version), the App Version should be seen on the menu item itself. Rest of the details inside:
   - Wallet Name (edit possible here)
   - Wallet ID
   - Version History
2. Add Wallet-Id and Wallet name on the keeper details
3. Show Wallet-Id in App settings, on recovery shares on the keeper side and on the PDF
4. Wallet name on the keeper side share

**Comment by antuz123** [comment]
@cakesoft-rohit - we need this if you have taken it out

**Comment by antuz123** [comment]
Need Wallet Name and ID on:

1. In your own app in App Info 
2. For F&F details 
3. PDF

**Comment by antuz123** [comment]
@summikhan11 - the edit option for name is not obvious on the screen, can you pls modify the CTA to be obvious

**Comment by cakesoft-rohit** [comment]
@summikhan11 
<img width="1440" alt="Screenshot 2021-07-30 at 11 14 00 AM" src="https://user-images.githubusercontent.com/74172232/127606452-d8f06b81-f851-4d22-981b-405012afdec3.png">
As we are showing number pad everywhere in our app when we enter pin, this UX needs to be updated as shown in simulator

**Comment by summikhan11** [comment]
Wallet ID on App Info: https://xd.adobe.com/view/902817ab-b10b-4f5e-8991-1f2142fd4a84-c57b/screen/1bc6f66e-02d7-4a1c-abef-8f26e965dd58/specs/

**Comment by summikhan11** [comment]
When they numpad slides up, please remove the note and keep the CTAs. We'll do this everywhere there is less space

**Comment by cakesoft-swati** [comment]
@cakesoft-rohit When numpad slides up, please remove the note and keep the CTAs. Right now Numpad is overlapping the buttons.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(377)
