### ISSUE TITLE
Buy screen

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3558]
### Description:
Buy will become a full fledged screen of its own with:
1. All the exchanges showing with info (up to 10): Name, small description, exchange rate, fee (not all data may be available all the time), already have an account with, tags like 'Sats Back' etc.
2. The list is sorted by groups: what the user has already used, then available exchanges and finally not available exchanges (due to country mostly)
3. The user can enter at the top of the screen these details based on which the below options will change: Payment methods (multiple selection: apple pay, Bank Card, Bank transfer, etc - all will be selected initially which user can unselect, Amount (in BTC/ fiat)
4. They can finally select any one exchange, a message is displayed like today with address and default account mentioned along with a warning message. The user can change thee account selection if the rules allow.

When we introduce more assets like Liquid, the user will be able to choose

Specs Link: https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/

**Comment by ASN-BitHyve** [comment]
Already implemented.
