### ISSUE TITLE
Add accounts

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3559]
### Description:
Add accounts can be trimmed down now and does not require any services as we have moved them to the Buy flow. The categories now can be:
1. "Add a Hexa Account" - This will be the heading
"Your keys, your coins, manage them the way you want" - This will be the text
Accounts in that order - Test, Donation, Checking, Saving and Vault (A super secure account) - These will be the accounts

2. "Create a Shared Account" - This will be the heading 
"Bitcoin is for everyone, share an account" - This will be the text
Accounts in that order: F&F Account(account to receive and send to F&F in Hexa), Joint Account (an account with someone), Community Account (like a cooperative bank account with a small community), Enterprise Account (for businesses)- These will be the accounts

3. "Import a wallet" - This will be the heading 
"Have your sats somewhere else? Import it in Hexa" - This will be the text
View Only, Full Import and Transfer funds - These will be the accounts

May need to design the different type of accounts which are not already there

**Comment by antuz123** [comment]
@summikhan11 - pls add the link

**Comment by summikhan11** [comment]
I'll need some descriptions for accounts to create their icons

Specs: https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/screen/f0acbfc5-2ee6-4b2d-9277-dbb02fb313a6

**Comment by antuz123** [comment]
@summikhan11 - I have updated the description and that will give you more info. The sub heading for each account is on another issue that you will see. That you can use here
