### ISSUE TITLE
F&F screen refresh issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3565]
1. The loader is getting stuck on refreshing the F&F screen on Android devices.This is mostly happening on removing the contact.[This is happening only on Android device.Tested on SAMSAUNG A50]
2. F&F Auto refresh is also taking time on both the devices.
3. And because of this the contacts are also appearing late.

**Comment by cakesoft-swati** [comment]
https://user-images.githubusercontent.com/62699947/121696521-c79bcf80-cae9-11eb-949e-3688de73ad6b.mp4
-The 1st point i.e "The loader is getting stuck on refreshing the F&F screen on Android devices." is still the issue n android device even after every post login.In ios it take time but not getting stuck.
-The second and third points are rare.I was not able to make a video of these.

**Comment by cakesoft-rohit** [comment]
This need to be tested after merging UX 2.0 branch to feature 2.0

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.8.0(304)
