### ISSUE TITLE
Test Account address

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3570]
F&F should be able to send to each other from Test Account as well

As testnet coins are a different asset, if someone wants to send from Test Account, they will need a different address. So this needs to be stored as well in the channel, same as mainnet address of choice (Checking Account or F&F account etc.) 

In general the architecture should be such that there can be multiple addresses on the channel depending on the assets we support - LBTC, USDt, etc. May be a key-value pair or something

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v18.0(304)
