### ISSUE TITLE
Account selection during Wallet Initialisation 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3573]
### Description:
Facility for the user to select accounts to be shown on home page during wallet setup. Default selected accounts will be Checking, Savings and Test but, it can be changed later. Checking account cannot be removed. 
If Test and Savings are not selected, they are marked hidden only as the underlying structure exists. If someone goes to the Add Account, they can add Test and Savings, that will only make them visible for the first time. 

Flow:
1. User installs the app, taps on the icon and sets the login passcode.
2. User will then be redirected to a screen where he will have an option to select the accounts from the given list in order to show/hide them on the home page. Each account name will have a know more button next to it so that the user can get a brief idea of that account. CTA's will be "Skip" and "Proceed".
3. Currently for 2.0 the accounts we will have are:
- Test Account
- Checking Account
- Savings Account
- Donation Account
- Friends and Family Account (A separate account where you can receive funds from your contacts)
- Bought BTC Account (or Exchange Account where newly bought bitcoins land)
- View Only Wallet (if you have a wallet somewhere else or a hardware wallet, you can import it in Hexa with the xPub and view the balance plus receive funds from Hexa)
4. Tapping on proceed will redirect user to home page where he/she will see only those accounts that he/she had selected in order to view them on home page.
5. A user can later choose to hide/unhide any particular account from home page by tapping on the settings icon -> Account Settings -> Account Visibility

**Comment by antuz123** [comment]
@summikhan11 - currently for 2.0 the accounts we will have are: 

1. Test Account 
2. Checking Account
3. Savings Account 
4. Donation Account 
5. Friends and Family Account (A separate account where you can receive funds from your contacts) 
6. Bought BTC Account (or Exchange Account where newly bought bitcoins land)
7. View Only Wallet (if you have a wallet somewhere else or a hardware wallet, you can import it in Hexa with the xPub and view the balance plus receive funds from Hexa)

**Comment by antuz123** [comment]
Steps: 
1. New Wallet process selection 
2. Wallet Name entry 
3. Select Account (only Checking Account selected by default) Get the screen from: #3573 
3.1 When user selects Savings Account, Test Account or other accounts, the account process happens there with a grey screen and once done a simple toast message is shown with the account being added. 
4. Cloud Backup/ Security Question screen 
4.1 User selects backup - Backup is done behind loader messages 
4.2 User skips backup - no action 
5. Lands on the Home Screen

**Comment by summikhan11** [comment]
Specs Link: https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/6f3bc6f2-b76b-42bd-adac-6eddb9db2a5b/

**Comment by cakesoft-swati** [comment]
@cakesoft-rohit Know more screens should also be visible here.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.7.9(312)
