### ISSUE TITLE
Account structure refactoring

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3574]
Instead of having a class-based model, we'll take the functional approach for accounts which would further modularise the data updates to database and would allow for incremental WI update.

Account Properties:
- xpub
- free address markers
- address to tx mapping w/ tags(tag: address consuming entity)
- Active addresses

**Comment by antuz123** [comment]
Active Addresses will be a list not a marker. @Parsh

**Comment by antuz123** [comment]
Add new account is pending

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with parsh.
