### ISSUE TITLE
Archive Account 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3579]
- Once you archive an account, it should land on the Home Screen 
- Same for restore (of an archived account), once restored it should take you to the specific account

**Comment by cakesoft-swati** [comment]
- On archiving an account, it returns to the home page but the account is still visible on the home page.That account is no longer visible on the home page when I log in again.
- I have to log in again all the time after archiving the account.
- On restoring the archive account, it is not landing on that specific account.

**Comment by cakesoft-swati** [comment]
- @cakesoft-rohit On restoring the archive account, it is still not landing on that specific account.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(330)
