### ISSUE TITLE
Hide Account 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3585]
Once account is hidden, it should land on the HSS and the account should not be visible (not in a 'hidden' mode)

**Comment by cakesoft-swati** [comment]
- When we hide the account it land on the home page, but the account is not hidden immediately. We have to login the app again only then that particular account will not appear on the home page.
-The account should disappear from the home page immediately.
- Testedon dev app v1.8.0(320)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.5(325)
