### ISSUE TITLE
Change Keeper flow is not working.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3591]

**Comment by antuz123** [comment]
@cakesoft-shivani - this has been on for a while. Is this still not done?

**Comment by cakesoft-shivani** [comment]
PDF to other keeper type and contact to pdf this scenarios are left to test but this issue is about only for contact to contact type change

**Comment by antuz123** [comment]
State the scenario left and move the rest to 1.8.5

**Comment by cakesoft-shivani** [comment]
Remaining scenarios
- Pdf to device

**Comment by cakesoft-swati** [comment]
-We have an issue for change keeper flow in 2.05
