### ISSUE TITLE
Once confirmed the recovery key is not being confirmed again.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3592]
- If the status changes after the contact is confirmed (Red Exclamation Mark) In this case again that recovery key is not getting confirmed , due to this the red outline is also not getting removed.
![Screenshot_20210617-174806_hexa dev](https://user-images.githubusercontent.com/62699947/122395126-4edabe80-cf94-11eb-8101-f16ac4cdef9c.jpg)

**Comment by cakesoft-swati** [comment]
-Able to reprduce this issue on dev app v1.8.0(304)

**Comment by antuz123** [comment]
Last Seen to be updated on HS along with fee and exchange rate call.

**Comment by cakesoft-swati** [comment]
- Still having the same issue on dev app v1.9.5(335)

**Comment by cakesoft-swati** [comment]
- Able to reproduce this issue on dev app v2.0(345).I have to refresh the F&F list after every login then only that expired share get confirmed which is not correct.
- We should fetch for Keepers and Keeping contacts on the Security and Privacy screen as well.Like we do on the F&F screen.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.01(374)
