### ISSUE TITLE
Disallow Caps or special characters for Security Questions Answer.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3598]
- Caps and special characters should not be allowed for Answer Confirmation screen and Security Answer screen when doing recovery and  new wallet creation.
- Answers must contain lowercase characters(a-z) and digits (0-9) 

![IMG_1946](https://user-images.githubusercontent.com/62699947/122555653-30d69200-d058-11eb-933a-fd99ab0d0dc4.PNG)
- It is still allowed on the security answer screen at the time of recovery.

**Comment by antuz123** [comment]
Add note like with the initial screen. 

Check post confirmation.

**Comment by cakesoft-swati** [comment]
@cakesoft-rohit It is still allowing caps and special characters on the security answer screen at the time of recovery.

**Comment by cakesoft-swati** [comment]
- Verfied this issue on dev app v1.9.0(327)
