### ISSUE TITLE
Account sync.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3613]
- These seem to be gone when I come from the background. Not sure if the accounts were synced or not.
![tempFileForShare_20210628-113328](https://user-images.githubusercontent.com/62699947/123588024-c6b2af80-d804-11eb-9287-b285a273ffa7.jpg)

**Comment by antuz123** [comment]
1. Accounts are synced by default when wallet creation happens. Sync flag is true. Pls check 
2. When logging in, first 4 accounts should be synced with smart sync (active address list) and the sync flag should be true (no sign shown)

**Comment by antuz123** [comment]
1. Sync should happen on login 
2. Ideally for first 4 accounts only 
3. All the sync flags are false when login. Once synced, the flag is true fir accounts synced

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(330)
