### ISSUE TITLE
Loader message.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3614]
-The Loader message is not correct.
![loadrmsgntcorr](https://user-images.githubusercontent.com/62699947/123591597-d254a500-d809-11eb-8b0e-34b6a50214c9.jpg)

**Comment by summikhan11** [comment]
Specs Link: https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/e04f153b-336f-4cd5-8563-c631966f38f2/

**Comment by cakesoft-swati** [comment]
- The loader message is not as per the Ux.

**Comment by antuz123** [comment]
See the screen attached

**Comment by cakesoft-rohit** [comment]
![Screenshot_1625574886](https://user-images.githubusercontent.com/74172232/124602774-d37b7700-de86-11eb-852c-f5b1db26ab3d.png)
ANDROID ScreenShot

**Comment by cakesoft-rohit** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2021-07-06 at 18 54 24](https://user-images.githubusercontent.com/74172232/124607551-9665b380-de8b-11eb-810e-1f1679575989.png)
iOS ScreenShot

**Comment by summikhan11** [comment]
Loader Message: https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/d4106792-2405-491a-8c54-5ebd17a9b810


Access Address Book: https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/fefffee2-8219-49af-ba20-c35770e47883

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.5(326)
