### ISSUE TITLE
Sats Back on Ramp.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3615]
- Take Samurai Wallet out and put SatsBack on Ramp. 
![samurai](https://user-images.githubusercontent.com/62699947/123592144-776f7d80-d80a-11eb-9cf5-104087cd063e.jpg)

**Comment by antuz123** [comment]
Remove Samurai Wallet and add Swan @summikhan11

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/screen/1dd8a584-3271-4ce7-bef8-80077656b19a/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.7.9(312)
