### ISSUE TITLE
Choose your own question:is not required.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3621]
- Don’t need this.
![dnt need](https://user-images.githubusercontent.com/62699947/123607943-f5885000-d81b-11eb-8aed-a34f8105aafe.jpg)

**Comment by summikhan11** [comment]
Specs Link: https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/bebf5f62-5fa9-4d79-9f6b-c5257f3e418c/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.7.9(312)
