### ISSUE TITLE
Not fitting in

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3625]
- Unable to scroll the page after entering the answer to the security question.
<img width="375" alt="5FC0E6AD-C131-44F3-BD4E-CE18BC94AE77" src="https://user-images.githubusercontent.com/62699947/123612006-ca076480-d81f-11eb-9a9b-dc2b1f7efe1d.png">

**Comment by antuz123** [comment]
You do not scroll for pop ups/ modals

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.7.9(312)
