### ISSUE TITLE
Need a realistic image.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3632]
- Need a more realistic image.
![realisticimg](https://user-images.githubusercontent.com/62699947/123641357-d0a5d400-d83f-11eb-883c-4b7fef9bbf3e.jpg)

**Comment by summikhan11** [comment]
Specs: https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/

**Comment by cakesoft-swati** [comment]
- verified this issue on dev app v1.7.9(312)
