### ISSUE TITLE
The "Add new" should be the last

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3633]
-"Add new" is not the first item but last. So 4th, when initially appearing.
![Uploading 63E41E70-BD71-4585-BDD4-37D0C7D074FA..png…]()

**Comment by antuz123** [comment]
Also the ordering of accounts should be left to right then top to bottom for the first 4 accounts. Then it can be one column at a time

**Comment by cakesoft-swati** [comment]
- verified this issue on dev app v1.7.9(312)
