### ISSUE TITLE
Final F&F design for 2.0

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3636]
![image](https://user-images.githubusercontent.com/43998049/123673112-b7ac1b80-d85d-11eb-9b74-903609d70a60.jpeg)

On this screen, Recently Sent is not important and is a repetition. So we can remove it. 

We need additional CTAs on this screen as follows: 
1. Gift Sats to Someone (I can merely send a link to someone and when they click it, they will have the sats I have sent them) 
2. Invite as an Angel (I will be more than a Keeper of that person, even keeping an eye on their spending etc) 

Only UI for now

**Comment by summikhan11** [comment]
Specs: https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/

**Comment by antuz123** [comment]
Hi Summi, I suggest we have three explicit actions:
1. Add a Contact: Add to your F&F list
2. Invite to Hexa: Onboard someone to Bitcoin with an Angel Link 
3. Send a Gift: Send sats using a simple link

**Comment by cakesoft-swati** [comment]
- UI is completed for this.Feature is not yet implemented in the app.

**Comment by antuz123** [comment]
Demo options to be taken out

**Comment by antuz123** [comment]
@summikhan11 - given we don't have the Gift or Angel option for 2.0, what should go on the top area? I saw you showing an add button and text in that space. Please confirm the final

**Comment by summikhan11** [comment]
add stays on the F&F page, once the user clicks on that they can see options on the next page

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(330)
