### ISSUE TITLE
Assets Missing

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3639]
Home > QR icon
Security & Privacy > active icon
Setting > active icon
Setting > App info Icon

**Comment by summikhan11** [comment]
Specs Link: https://xd.adobe.com/view/902817ab-b10b-4f5e-8991-1f2142fd4a84-c57b/specs/

**Comment by cakesoft-rohit** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2021-06-30 at 18 30 21](https://user-images.githubusercontent.com/74172232/123964747-66249d80-d9d1-11eb-822f-537fe86b74ca.png)
These images needs border

**Comment by antuz123** [comment]
@cakesoft-rohit - pls list all that need border. And do you really need one? 

@summikhan11 - it may need one due to colour change. There are others like this too

**Comment by cakesoft-rohit** [comment]
@antuz123  Yes I need border to these icons. If icon color and background colour is same then it doesn't look right

**Comment by cakesoft-rohit** [comment]
@summikhan11 update png files also

**Comment by cakesoft-rohit** [comment]
Same issue in account selection screen at login for Test Account and Bought BTC Account

**Comment by summikhan11** [comment]
Specs Links
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/d6f3cd5f-e32d-44ee-99bd-05a3e0070e05/specs/
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/ef550d10-ee45-40fc-83de-14ddb7f1f900/specs/

**Comment by cakesoft-rohit** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2021-07-01 at 14 34 24](https://user-images.githubusercontent.com/74172232/124098358-1f3eb280-da7a-11eb-9e74-c7b001f021bf.png)
Border required to Add a ward icon

**Comment by cakesoft-rohit** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2021-07-01 at 14 44 29](https://user-images.githubusercontent.com/74172232/124099160-daffe200-da7a-11eb-9fbf-ee35a38ce3a4.png)
Border not in Add Contacts icon

**Comment by antuz123** [comment]
@cakesoft-rohit - the assets are there. Please look at other screens

**Comment by cakesoft-swati** [comment]
Setting > active icon
Setting > App info Icon
- These two icons are missing.

**Comment by summikhan11** [comment]
both are there, please check again

**Comment by antuz123** [comment]
@summikhan11 - can't find the assets pls help

**Comment by summikhan11** [comment]
<img width="931" alt="Screen Shot 2021-07-23 at 6 06 11 PM" src="https://user-images.githubusercontent.com/85475736/126782458-e265a218-096d-445f-8143-b35faefe4941.png">
both assets are there, please check

**Comment by cakesoft-rohit** [comment]
@summikhan11 
Security and Privacy (4th tab) Active icon is missing
If you find the one please attach the specs link here

**Comment by cakesoft-rohit** [comment]
@summikhan11 Wallet icon is not in assets
https://xd.adobe.com/view/902817ab-b10b-4f5e-8991-1f2142fd4a84-c57b/screen/ad63ab93-2c6d-424e-af3c-c333c2cca6e1/specs/

**Comment by summikhan11** [comment]
Security & Privacy - https://xd.adobe.com/view/3c76a519-ed48-4944-a7a5-026a2aca5a6d-6925/

**Comment by summikhan11** [comment]
Wallet Illustration: https://xd.adobe.com/view/902817ab-b10b-4f5e-8991-1f2142fd4a84-c57b/screen/ad63ab93-2c6d-424e-af3c-c333c2cca6e1/specs/
