### ISSUE TITLE
Step 2: Personalize your accounts.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3647]
- Test Account asset not looking proper on selection 
- Change the name of Bought BTC account to Exchange Account and make sure the asset is proper.
![TAasset](https://user-images.githubusercontent.com/62699947/123966382-016a4280-d9d3-11eb-8eec-27110dd0be5a.jpg)

- Know More is not showing the Know More info but rather selecting the account. Need to show Know More properly.
![knowmore](https://user-images.githubusercontent.com/62699947/123967507-011e7700-d9d4-11eb-8e36-20f25682e74d.jpg)

**Comment by cakesoft-swati** [comment]
- make sure the Exchange Account asset is proper.
![TAasset](https://user-images.githubusercontent.com/62699947/123966382-016a4280-d9d3-11eb-8eec-27110dd0be5a.jpg)

**Comment by cakesoft-rohit** [comment]
@summikhan11  Wrong Bought BTC Account Icon is available in assets

**Comment by antuz123** [comment]
Deposit Account - instead of Bought BTC

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/efed4d69-eb20-4ed2-8dc2-d0ac93623b06/
