### ISSUE TITLE
Login still taking a long time.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3654]
![lnglogi](https://user-images.githubusercontent.com/62699947/123969813-30ce7e80-d9d6-11eb-86da-f138d68489fc.jpg)

**Comment by AliMeer** [comment]
This may need more work and tweaks, lets test the current build and update this issue if performance at login is still slow.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.7.9(312)
