### ISSUE TITLE
Last seen missing and the alignment of text is not proper.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3660]
![romiss](https://user-images.githubusercontent.com/62699947/124102334-e6084180-da7d-11eb-9875-909a9e98645e.jpg)

**Comment by antuz123** [comment]
Need to show Last Seen unknown

**Comment by antuz123** [comment]
Show Last seen _unknown _ when no value present

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.0(315)
