### ISSUE TITLE
UI issue on splash screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3661]
- This image is very pixelated and not good quality. 
![pixalated](https://user-images.githubusercontent.com/62699947/124074617-640a1f80-da61-11eb-9fce-7ab38f1e9d99.jpg)

**Comment by antuz123** [comment]
Hexa 2.0 on the splash screen video and the high quality image @summikhan11

**Comment by summikhan11** [comment]
Specs: https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/

**Comment by antuz123** [comment]
@summikhan11 - we also need a video with 2.0

**Comment by summikhan11** [comment]
https://user-images.githubusercontent.com/85475736/125735577-d0de528d-fd41-49a7-aad2-a7596a3137e0.mp4

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.5(325)
