### ISSUE TITLE
White screen appears when we relogin after clearing the app from background.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3670]
- White screen appears when we relogin after clearing the app from background.
- This also appeard when app is in background n we reopen it after some time.
- I have to kill the app everytime
- Tested on android device one plus 9R.
![Screenshot_20210701-084845](https://user-images.githubusercontent.com/62699947/124078781-ec8abf00-da65-11eb-975b-2f6499df52be.jpg)

**Comment by cakesoft-shashank** [comment]
Unable to reproduce @cakesoft-swati

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.8.0(317).Unable to reproduce this issue.
