### ISSUE TITLE
Temp

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3671]
For the demo put these things in which need to be taken out later. 

1. Show red dot for notifications and Savings Account like in the UX @cakesoft-rohit 
5. Don't need a node sign against each contact may be one or two of all the contacts @cakesoft-rohit 
6. Increase the time for health expiry to 2 hours @AliMeer -Done
2. The graph image is temp and needs to be removed 1.8.0 
3. The text on the header should be the text from the Health section. Currently it is static 1.8.0 
4. Show a link on the QR code for F&F instead of 'Generating a link...". @AliMeer - Done

**Comment by antuz123** [comment]
@AliMeer - please reverse the items that were done for Demo only

**Comment by AliMeer** [comment]
Done 3 and 6. The rest need to be reverted.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.7.9(315)

**Comment by cakesoft-swati** [comment]
1.I can see a node sign on all contact.
2.Also I can see a graph image in 1.8.0
- Tested on dev app v1.7.9(315)

**Comment by cakesoft-rohit** [comment]
We are going to do graph related changes in 1.8.5

**Comment by cakesoft-swati** [comment]
- Verifed this issue on dev app v1.8.0(317)
