### ISSUE TITLE
Unable to proceed.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3683]
![noproceed](https://user-images.githubusercontent.com/62699947/124109560-e7893800-da84-11eb-9524-7a98dac48f01.jpg)

**Comment by AliMeer** [comment]
not an issue. Proceed button is displayed after correct answer is confirmed

**Comment by antuz123** [comment]
Check the exact issue

**Comment by cakesoft-swati** [comment]
- Closing this issue.Verified on dev app v1.7.9(315)
