### ISSUE TITLE
Step 3:Note 

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3684]
- Note: The Answer is used to encrypt the backup. The security Question acts as a hint to remember the same
![ansnte](https://user-images.githubusercontent.com/62699947/124114707-819faf00-da8a-11eb-963f-166790160688.jpg)

- Note: Make sure you remember the encryption password and keep it safe

![encryptpwd](https://user-images.githubusercontent.com/62699947/124114526-4f8e4d00-da8a-11eb-9a8f-eb1283d85896.jpg)

**Comment by cakesoft-swati** [comment]
- I can't see the changes.
- Tested on dev app v1.7.9(312)

**Comment by antuz123** [comment]
Also add a field for 'Hint:'

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.0(317)
