### ISSUE TITLE
Functionalize Trusted Contacts

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3687]
Trusted Contacts(F&F) mechanisms need to be separated out from the contact objects, similar to accounts.  
Post-separation, the contacts object needs to be stored in realm instead of SQL, and corresponding changes to the TC-reducer and referencing points needs to be made.

**Comment by antuz123** [comment]
@AliMeer - who and how this needs to be done?

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
