### ISSUE TITLE
FastBitcoins spelling plus logo colour

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3690]
1) "FastBitcoin"> "FastBitcoins"

2) We've not used their logo colour.

![FastBitcoins](https://user-images.githubusercontent.com/68264080/124145297-4b722780-daaa-11eb-8320-82fd111090d5.jpg)

**Comment by summikhan11** [comment]
Specs Link:
https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/screen/74205434-34a6-40d8-976a-ec45316f5226/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.0(321)
