### ISSUE TITLE
Add Account and Account selection 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3691]
Optimise these two functionality: 
- [x] Option 1: Do all account addition in the end after step 3
- [ ] Option 2: Do it on the go on the account selection screen when selected, one by one. But when unselected - we mark it delete. Checking account needs to be initialised with another account if we go with Option 2
- [ ] Option 3: Try to do it in the background and see the impact on screen performance

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with Parsh.
