### ISSUE TITLE
Tech and Operational handover

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3695]
1. App release and signed APK: https://github.com/bithyve/internal-docs/issues/29
2. Backend re deployment: https://github.com/bithyve/internal-docs/issues/147
3. Backend deployment and issues: https://github.com/bithyve/internal-docs/issues/148

**Comment by antuz123** [comment]
Do 180 with Ali

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
