### ISSUE TITLE
backend relay housekeeping

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3696]
https://github.com/bithyve/internal-docs/issues/149

**Comment by Parsh** [comment]
Cleaned up Dev but I don't have access to Staging. Also, I'm not sure whether we need to backup dev/staging clusters.

**Comment by antuz123** [comment]
No need to backup dev and staging.

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
