### ISSUE TITLE
Match bottom curvature

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3699]
Can the modals to match the bottom curvature of phones

![image](https://user-images.githubusercontent.com/43998049/124278644-20e4a500-db64-11eb-88a9-d7b7b968e313.jpeg)

**Comment by cakesoft-swati** [comment]
UI changes are pending.

**Comment by antuz123** [comment]
Maintain apple like (min) height and gap.

**Comment by antuz123** [comment]
Also make sure the shade of blue for cross and button matches.

**Comment by antuz123** [comment]
@summikhan11 - we are going with the apple like loader messages

**Comment by summikhan11** [comment]
Specs: https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/d4106792-2405-491a-8c54-5ebd17a9b810

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
