### ISSUE TITLE
Home page landing time seems different for 2 different cloud backup options.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3705]
- At the time of wallet set up when we enter the security answer it immediately redirects to the home page. Not being able to see the loader messages seems too fast.
- Rather, it is slow when we choose the option "Own Encryption Password".Able to see each loader messages.

**Comment by AliMeer** [comment]
This is probably because the backup mechanism needs to use the answer and currently it is not doing so.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.0(321)
