### ISSUE TITLE
The hexa icon is not visible on push notifications.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3713]
- The hexa icon is not visible on push notifications. Only a blank icon is visible.
![temp](https://user-images.githubusercontent.com/62699947/124598713-872e3800-de82-11eb-847c-b248d87f904a.jpg)

**Comment by cakesoft-shashank** [comment]
Need an image with all parts that we don’t want to show in transparent pixels and all colors and non transparent pixels are in white
Example:

![notificationicon](https://user-images.githubusercontent.com/50690016/124600671-94e4bd00-de84-11eb-8932-d8ebb52e48e7.png)

**Comment by summikhan11** [comment]
![For Notifications@3x](https://user-images.githubusercontent.com/85475736/125374820-72333680-e3a5-11eb-87a4-52e94138a343.png)
![For Notifications@2x](https://user-images.githubusercontent.com/85475736/125374821-73fcfa00-e3a5-11eb-886e-1b8bdd7bc060.png)
![For Notifications](https://user-images.githubusercontent.com/85475736/125374823-74959080-e3a5-11eb-9aa8-07d185fb7455.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.0(321)
