### ISSUE TITLE
New Deposit Account

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3722]
Add a new deposit account when the user selects the deposit account option(for the first time) during the buy journey.

**Comment by antuz123** [comment]
- [ ] Backend @Parsh 
- [ ] UX/ FrontEnd @cakesoft-rohit

**Comment by cakesoft-swati** [comment]
- Ramp/Wyre > Select Deposite account from drop down.
- Verified this issue on dev app v1.8.5(326)
