### ISSUE TITLE
Trusted Contacts Collection

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3730]
We'll need to store trusted contacts(as defined [here](https://github.com/bithyve/hexa/blob/2e1fd7544d6cb01f5744db334a447c07e47ae371/src/bitcoin/utilities/Interface.ts#L584)) in Realm and would require endpoints to perform CRUD operations on them. 

Required for #3687

**Comment by cakesoft-swati** [comment]
- Closing this issue as  discussed with dev.
