### ISSUE TITLE
Deeplink not opening 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3732]
Mostly done, need to be tested

**Comment by cakesoft-swati** [comment]
- Verified this on dev app v1.8.0(317)

**Comment by cakesoft-swati** [comment]
- Verified this Swan Buy integration in dev app v1.8.0(317)
- It is working properly in android device.
- In ios it is asking to open in "Hexa Stage"? and when we click on "Open" it gives a msg as ""Hexa stage" Beta has expired" and after clicking on "OK" when we again click on "Authorize Hexa wallet" it throws an error as {"message : "invalid_request"}.

**Comment by cakesoft-swati** [comment]
- Still the Swan is not working on both the device android ans ios as well.
-Tested on dev app v1.8.0(319)
-
Uploading 21-07-13-19-48-24.mp4…

**Comment by AliMeer** [comment]
I was able to complete Swan journey in #317. The deeplink didn't open the modal in #319.

**Comment by antuz123** [comment]
@cakesoft-swati - are any deep links working?

**Comment by antuz123** [comment]
- [ ] swan deeplink not opening from the app

**Comment by cakesoft-swati** [comment]
- Now the deeplink is working for swan account.
- Tested in dev app v1.8.5(325)
