### ISSUE TITLE
Cloud backup should not be performed when security questions are not available.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3739]
- If Security Question is not available the cloud backup cannot be done and the message is shown to the user.
- Also the SQ has both options as during initialisation.
![temp (3)](https://user-images.githubusercontent.com/62699947/125101603-05dfdb00-e0f8-11eb-9d81-e58ccb259654.jpg)

**Comment by antuz123** [comment]
Also change the text for Security Question text on the button to Set Password 

cc: @summikhan11

**Comment by antuz123** [comment]
@summikhan11 - can you pls also reverse the direction of the buttons in the UX. Set Password first and then cloud backup

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/3c76a519-ed48-4944-a7a5-026a2aca5a6d-6925/screen/2844f53f-22fe-489c-b3b5-d9aee96a9c6f/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.0(322)
