### ISSUE TITLE
Use the proper icons.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3741]
- These are not proper icons.
![temp (5)](https://user-images.githubusercontent.com/62699947/125102450-ea290480-e0f8-11eb-8d0f-b682d1acabb1.jpg)

**Comment by antuz123** [comment]
@summikhan11 - we will need the icons.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.5(326)
