### ISSUE TITLE
The home page message should be in one line

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3742]
- Need to be one line.
![temp (6)](https://user-images.githubusercontent.com/62699947/125102722-3aa06200-e0f9-11eb-8f90-d5f7829eef31.jpg)

**Comment by antuz123** [comment]
Pls remove 'you can' 

For name you can truncate the name

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.0(320)
