### ISSUE TITLE
Initial cloud backup > Answer to a security Question.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3744]
- The heights don’t seem proper. 
![heightnpro](https://user-images.githubusercontent.com/62699947/125103291-d500a580-e0f9-11eb-826b-3c65f42de5ba.jpg)

**Comment by antuz123** [comment]
@summikhan11 - we need two standard heights. Suggest to keep the minimum to what iOS has.

**Comment by summikhan11** [comment]
Specs: https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/54f4f01e-67b9-4401-85f9-3122e3bf4e1c/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.5(326)
