### ISSUE TITLE
Account sync and account selection at the time of wallet initialisation.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3757]
1. Sync still showing when wallet just initialised. This is not needed as no balance fetch needed on initialisation. 
 (Check with Ali).

![accsync](https://user-images.githubusercontent.com/62699947/125432698-f5f860ee-7cc2-4865-aac2-47e0ac1fb955.jpg)

**Comment by AliMeer** [comment]
I have resolved the sync icon issue. Sync icon will not show for new accounts.

**Comment by cakesoft-swati** [comment]
- Verified this issueon dev app v1.8.0(320)
