### ISSUE TITLE
Test Account does not have test sats.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3760]
- Test Account still does not have test sats.
![nosats](https://user-images.githubusercontent.com/62699947/125434373-a58846fa-7dab-49e7-914a-a8f7cebf1eef.jpg)

**Comment by Parsh** [comment]
It does have test sats, but because it is not getting auto-synced the tx and balance aren't appearing.

**Comment by antuz123** [comment]
Put the Test Account in Add and the test sats filling from there. Also if type=testnet then sync post creation. While other accounts don't @Parsh

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.0(321)
