### ISSUE TITLE
QR code is not loading.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3763]
- After selecting a contact in "Add Contact", the QR code is not showing up only the loader is loading.
- Happening only on staging app v1.8.0(319)

**Comment by antuz123** [comment]
Staging specific

**Comment by cakesoft-swati** [comment]
- still facing the above issue.Tested on staging app v1.9.0(328)
- Happening only on staging app.

**Comment by antuz123** [comment]
This was done by Parsh I think.

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v1.9.5(330)
