### ISSUE TITLE
Update Wallet schema => Answer question and question Id

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#3771]

**Comment by antuz123** [comment]
@cakesoft-shashank - don't close any issue. Mark it fixed, only Swati/ QA can close a issue

**Comment by cakesoft-shashank** [comment]
Okay, it its just developer task. Testing not required

**Comment by antuz123** [comment]
Sure, but let's keep this the way it is as a protocol

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
