### ISSUE TITLE
Add notification types to relay

### ISSUE THREAD

**Issue by cakesoft-shashank** [bithyve/hexa#3779]
FNF_REQUEST = 'FNF_REQUEST',
  FNF_TRANSACTION = 'FNF_TRANSACTION',
  RELEASE = 'RELEASE',
  FNF_REQUEST_ACCEPTED='FNF_REQUEST_ACCEPTED',
  FNF_REQUEST_REJECTED='FNF_REQUEST_REJECTED',
  FNF_KEEPER_REQUEST='FNF_KEEPER_REQUEST',
  FNF_KEEPER_REQUEST_ACCEPTED='FNF_KEEPER_REQUEST_ACCEPTED',
  FNF_KEEPER_REQUEST_REJECTED='FNF_KEEPER_REQUEST_REJECTED',
  CONTACT = 'contact',
  SECURE_XPUB = 'secureXpub',
  APPROVE_KEEPER = 'approveKeeper',
  UPLOAD_SEC_SHARE = 'uploadSecondaryShare',
  RESHARE= 'reShare',
  RESHARE_RESPONSE = 'reShareResponse',
  SM_UPLOADED_FOR_PK = 'smUploadedForPK',
  NEW_KEEPER_INFO = 'newKeeperInfo'

**Comment by antuz123** [comment]
@AliMeer - pls also show how this is done to one of the team members

**Comment by Parsh** [comment]
Addressed by https://github.com/bithyve/Relay/pull/154

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
