### ISSUE TITLE
Buttons of Full Rescan modal are not responding.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3783]
- "Continue" and "Back"buttons of full Rescan modal(Settings & More > Wallet settings> Full Rescan) are not responding.
![Screenshot_20210715-134009](https://user-images.githubusercontent.com/62699947/125753715-9493afe6-47d6-475b-b807-f30d333b96b5.jpg)
- I have to kill the app everytime to close that modal.
- Tested on dev app v1.8.0(319)

**Comment by antuz123** [comment]
We need to remove this button. No longer needed. @cakesoft-swati @cakesoft-rohit

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.0(320)
