### ISSUE TITLE
Account descriptions

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3798]
For HS and Add Account

Name - HS description - Add Account Description 

Checking Account - Bitcoin Wallet - SingleSig on-chain bitcoin wallet 

Savings Account - MultiSig Wallet - 2 of 3 MultiSig bitcoin wallet 

Test Account - Testnet Wallet - Preloaded Testnet wallet 

Donation Account - Receive Donations - Receive bitcoin donations 

Swan Bitcoin - Withdrawal Wallet - Swan Bitcoin withdrawal wallet 

Deposit Account - Exchange BTC - default exchange account 

F&F Account - Friends and Family - Account for your contacts 

View Only Account - View Only Account - View non-Hexa wallet as an account 

Full Import - Imported Account - Fully import a non-Hexa wallet 

Joint Account - with 'contact name'- MultiSig account with a contact 

Community Account - Community Account - MultiSig Account for a group 

Important that HS text is in one line, Add Account can be in two

**Comment by summikhan11** [comment]
@antuz123 i dont see Enterprise Account details

also, can you check "Joint Account" HS descriptions as well?

**Comment by summikhan11** [comment]
Add Account: https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/screen/4ccce799-4f03-4c60-8f8b-cef5e5b9cdef/

**Comment by cakesoft-rohit** [comment]
@summikhan11 
white border is required for all assets to make it visible on blue background
![Simulator Screen Shot - iPhone 11 - 2021-07-27 at 20 54 12](https://user-images.githubusercontent.com/74172232/127181596-06c6c21b-4475-47d3-b07a-78d884855ced.png)

**Comment by cakesoft-swati** [comment]
@cakesoft-rohit 
I'm not able to see the border for Test account and Savings accounts icon.
![temp (17)](https://user-images.githubusercontent.com/62699947/127468691-5347b3cc-b299-40bf-9a9a-78833a0672f2.jpg)

![temp (18)](https://user-images.githubusercontent.com/62699947/127468735-a3eefae7-99fc-4138-b812-860d68634e45.jpg)

![temp (19)](https://user-images.githubusercontent.com/62699947/127468772-ef19e4ad-7228-4dbe-bef5-c0b401c01f5c.jpg)

**Comment by summikhan11** [comment]
Savings Account: https://xd.adobe.com/view/69730b23-793e-4df6-b663-0c680f65329d-3c20/specs/

**Comment by summikhan11** [comment]
Test Account: https://xd.adobe.com/view/2f42c330-be9a-4b0a-963d-698d60da4894-7a11/

**Comment by summikhan11** [comment]
Add Account: https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/screen/b44ad3c1-124e-4315-b3ec-31e9e21313a2/

**Comment by antuz123** [comment]
using SVG should fix this

**Comment by cakesoft-swati** [comment]
- verified this issue on dev app v1.9.5(338)
