### ISSUE TITLE
Use SVG assets 

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3807]
- Use proper images.
![temp (12)](https://user-images.githubusercontent.com/62699947/126130152-3f344f9c-433e-44e4-bc93-2c6bc6a425c0.jpg)

**Comment by cakesoft-rohit** [comment]
Need Icon for F&F account @summikhan11

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/screen/4ccce799-4f03-4c60-8f8b-cef5e5b9cdef

**Comment by cakesoft-rohit** [comment]
@summikhan11  Not able to see the icon in blue background, icon need a white border
![Simulator Screen Shot - iPhone 11 - 2021-08-02 at 11 58 21](https://user-images.githubusercontent.com/74172232/127814006-2613b3b6-13fa-4466-8b0d-c746fb232f6c.png)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/2f42c330-be9a-4b0a-963d-698d60da4894-7a11/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.6(394)
