### ISSUE TITLE
Need UI to Design.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3808]
- UI to design
![temp (13)](https://user-images.githubusercontent.com/62699947/126130566-0192fae2-865b-4910-be63-0f3553ede085.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/182db13e-dc6a-40ec-a319-5bf018182399-4d7e/screen/f5bd120e-aa6f-4478-a67c-a0cae74f1f9c/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.0(329)
