### ISSUE TITLE
Functionalise S3-Services(BHR)

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3819]
The mechanisms that perform the BHR activity(s3-service) need to be upgraded from an object-oriented model to a functional model. The ejected state variables need to be migrated from legacy DB to Realm. 

Here's how we can achieve it:

- [x] Functionalize S3-service @Parsh 
- [x] Refactor sagas to use functionalized s3-service and update points of reference(also the sss reducer needs to be refactored to hold BHR data) @cakesoft-shivani 
- [x] Formulate a collection in Realm for storing BHR data @cakesoft-shashank @cakesoft-shivani

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
