### ISSUE TITLE
F&F bottomsheet: linking broken

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3821]
The F&F bottom sheet is not opening on clicking the deep link. Also, we would require a field to enter phone-number(acceptors) to decrypt the key.

**Comment by cakesoft-swati** [comment]
- Still facing the same issue on dev app v1.8.5(325)

**Comment by cakesoft-swati** [comment]
@cakesoft-rohit now F&F bottom sheet is opening on clicking the deep link but are we not showing phone-number field?

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.0(329)
