### ISSUE TITLE
Savings Account changes

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3825]
### Description:
Ability for the user to make test account as default and add savings account on the basis of level 1 or level 2.

**Flow:**
1. Make test account as default instead of savings account.
2. User can add savings account from add account on home page. If the user has completed only level 1 and on tapping on savings account from add account user will be prompted with a message stating for eg. @summikhan11  
`"Hexa recommends that it is more secure to setup a Savings account after you complete level 2. Click here to know why?". Know why will be a link which will open an info modal to know more on this. CTA's will be "Skip" and "Ok".`

 Skip will redirect to savings account creation screen and Ok will redirect to home page. While creating a savings account there are 2 scenarios as follows:

_Level 1 scenario_
- If the user is at level 1 and if the user creates a savings account while being on this level then the app will take the secondary mnemonic from the primary device itself.

_Level 2/level 3 scenario_
-

` If the user is at level 2/3 and if the user creates a savings account while being on this level then the app will ask/prompt the user to take the secondary mnemonic from the personal/secondary device and not from the primary device. When the user tries to complete level 2, app will perform a check whether a savings account has been already created. If its created then it will take the secondary mnemonic from the primary device itself. And if it does not exist then user will be asked to take the secondary mnemonic from the personal/secondary device while creating the savings account.`

 @summikhan11 
3. If savings account is created on level 2, then while setting up 2FA also user will be asked to take the secondary mnemonic from the personal/secondary device.

**Comment by summikhan11** [comment]
not sure what to do here @cakesoft-priyanka @antuz123

**Comment by cakesoft-priyanka** [comment]
> not sure what to do here @cakesoft-priyanka @antuz123

Need to display messages

**Comment by cakesoft-swati** [comment]
-  Default test account is visible but the flow of savings accounts is not as per the description.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/

can you please elaborate point no 3
@cakesoft-priyanka

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(338)
