### ISSUE TITLE
“Enter OTP” modal is popping up to accept the F&F request.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3838]
![Screenshot_20210722-113839](https://user-images.githubusercontent.com/62699947/126613641-b29d685a-fd6a-438e-aff1-88343ae7ddde.jpg)
- The "Enter OTP" modal is coming up on receivers side after scanning the QR code and even in case of "Skip" contact, the "enter OTP"option is coming on receivers side after scanning the QR code.
-  It is asking for OTP and if I enter the phone number then "Invalid key" message is coming up.
- And on clicking on the Deeplink it came to the Home page but the modal did not come.
- Tested on dev app v1.8.0(322)

**Comment by antuz123** [comment]
@cakesoft-swati - OTP should come up for Skip Contact flow 

OTP does not come up for contact selection and when they have a number

**Comment by antuz123** [comment]
@cakesoft-swati - please state the scenarios. QR or link. Sender or receiver. Contact selected or Skip.

**Comment by cakesoft-swati** [comment]
- F&F Request Accept/ Reject modal is not opening on clicking the deeplink.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.5(324)

**Comment by cakesoft-swati** [comment]
- F&F Request Accept/ Reject modal is not opening on clicking the deeplink.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.5(324).
- Now the "Enter OTP" modal is not popping up to accept the F&F request.
