### ISSUE TITLE
Active address population

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3840]
Account specific Active Address list - suggested approach

**Comment by antuz123** [comment]
Initial state: 
For every account the Active Address list is empty initially and the marker is on the first address. 

How addresses get added: 
1. When the user goes to the Receive Screen the address shown is added to the list if it is a new address (not already on the list). The marker moves here to the next one. 

2. When a contact is added the relevant account gives the next free address to the channel, adds it on the list and moves the marker 

3. When a buy process is done an address is sent to the on-ramp platform, address is stored on the list and the marker is moved forward 

How addresses get removed: 
1. When a transaction is received on any active address, it is removed from the list (on account sync) 
2. If this address belongs to a F&F a new address is placed on the relevant F&F channel and the marker is moved ahead

**Comment by antuz123** [comment]
Every account has a function "Assign Next Free Address (NFA)". This can be called from Add Account, Add Contact, Account Receive screen, HS receive screen or the buy process. The parameter to pass to this function is only the account ID and what you get back is a single address from the account. 

What this function does:
1. Returns the marker address 
2. Moves the marker to the next address 
3. Puts the new marker address in the accounts Active Address list 

For Add Account/ Account creation: 1. Assign the marker to the first address 
2. Call Assign NFA 

For Add Contact: 
1. Check which is the F&F account (Checking or F&F account) 
2. Call Assign NFA for that account 
3. Put the address in the channel 

On Receive screen:
1. Check the account selected (in HS) 
2. Call Assign NFA 
3. Show the address received

**Comment by antuz123** [comment]
Updated the last para @Parsh as per our discussion

**Comment by Parsh** [comment]
> On Account Sync (Smart Sync and Full Sync), if any Active Address gets a transaction:
> 
> 1. Remove it from the list

On Account Sync (Smart Sync and Full Sync), if any Active Address gets a transaction:
Remove it from the list.

Should it be removed as soon as a transaction is received or post 6+ confirmation @antuz123 ?

**Comment by antuz123** [comment]
On login for 2.0 - all account sync (smart sync) 
On pull down - full sync of that account 


Take out the account settings - hard refresh and full settings - blind refresh

**Comment by Parsh** [comment]
> On login for 2.0 - all account sync (smart sync)
> On pull down - full sync of that account
> 
> Take out the account settings - hard refresh and full settings - blind refresh

@antuz123 I've created a separate [issue](https://github.com/bithyve/hexa/issues/3884) for this. It will need some discussion and exploration prior implementation.

**Comment by Parsh** [comment]
> If there are more than 25 addresses in the Active Address list, remove the oldest address in the list
Also, this restriction is not placed yet as it can lead to quirky balance outcomes(till #3884 is not implemented)

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
