### ISSUE TITLE
BTC value and Buy 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3841]
For 2.0, we will have just the BTC value displayed instead of the graph and a buy button next to it. 

We won't need the Buy tab and the buy will be a simple list of options without any filtering on the top

**Comment by cakesoft-swati** [comment]
@cakesoft-rohit I'm still able to see the graph on Home page.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.5(325)
