### ISSUE TITLE
App Icon for 2.0

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3842]
New App Icon for 2.0 (?)

**Comment by summikhan11** [comment]
![App Icon – 2 0](https://user-images.githubusercontent.com/85475736/132608937-381c3a5c-e301-44b1-b5cc-cae889963ab9.png)

let me know if i need email this to anyone.

**Comment by antuz123** [comment]
![image](https://user-images.githubusercontent.com/43998049/133251428-80ee48ff-14ae-4704-afc3-8f471ca2fccf.png)

**Comment by antuz123** [comment]
@cakesoft-rohit - Can you put the two above on an app and show me? Side by side?

**Comment by cakesoft-rohit** [comment]
@summikhan11  also want rounded icon if you can share

**Comment by cakesoft-rohit** [comment]
need rounded icon, in some android phone we need 
![Screenshot_1631794747](https://user-images.githubusercontent.com/74172232/133618159-1ad3f5b9-a910-400f-aadc-b643f8439a2b.png)

**Comment by ASN-BitHyve** [comment]
Feedback for Shashank: Rohit needed feedback from Sumaiah. She gave it to him on call. I was also there in that call. But what action was taken after that call I don't know. Sumaiah's answer to the question Rohit had posed was this link: https://developer.android.com/distribute/google-play/resources/icon-design-specifications 

@cakesoft-shashank

**Comment by cakesoft-shashank** [comment]
> Feedback for Shashank: Rohit needed feedback from Sumaiah. She gave it to him on call. I was also there in that call. But what action was taken after that call I don't know. Sumaiah's answer to the question Rohit had posed was this link: https://developer.android.com/distribute/google-play/resources/icon-design-specifications
> 
> @cakesoft-shashank

I have added adaptive icon now

**Comment by cakesoft-swati** [comment]
- Verified this issue on live app v2.0.0(365)
