### ISSUE TITLE
Loader Messages

### ISSUE THREAD

**Issue by cakesoft-rohit** [bithyve/hexa#3852]
**List of loader Messages during Wallet Initialization:**
> heading: 'Bootstrapping Accounts',
>     text: 'Hexa has a multi-account model which lets you better manage your bitcoin (sats)',
>     subText: '',

> heading: 'Filling Test Account with test sats',
>     text: 'Preloaded Test Account is the best place to start your Bitcoin journey',
>     subText: '',

> heading: 'Generating Recovery Keys',
>     text: 'Recovery Keys help you restore your Hexa wallet in case your phone is lost',
>     subText: '',

> heading: 'Manage Backup',
>     text: 'You can backup your wallet at 3 different levels of security\nAutomated cloud backup | Double backup | Multi-key
 backup',
> subText: '',

> heading: 'Swan Bitcoin',
>     text: 'Register with Swan Bitcoin to get $10',
>     subText: '',

> heading: 'Level 1 - Automated Cloud Backup',
>     text: 'Allow Hexa to automatically backup your wallet to your cloud storage. It ensures you can easily recover your wallet in case your phone gets lost',
>     subText: '',

> heading: 'Level 2 - Double Backup',
>     text: 'Starting to hodl sats and bitcoin? Ensure that you backup your wallet atleast to Level 2 backup called Double Backup',
>     subText: '',

> heading: 'Level 3 - Multi-key Backup',
>     text: 'For hardcore Bitcoiners who understand Bitcoin, stack large amounts of sats or bitcoin and care for utmost security of their wallet',
>     subText: '',

**List of loader Messages during Login:**

> heading: 'Non-custodial buys',
>     text: 'Get sats directly in your wallet with compatible exchanges vouchers',
>     subText: '',

> heading: 'Friends & Family',
>     text:
>       'Add contacts to Hexa and send sats w/o asking for address every time',
>     subText: '',

>  heading: 'Hexa Savings Account',
>     text: 'Don’t forget to set up your 2FA code on an authenticator app',
>     subText: '',

 

> heading: 'Donation Accounts',
>     text:  'Start receiving donations directly in your Hexa Wallet, from anywhere in the world',
>     subText: '',

> heading: 'Satoshis or Sats',
>     text: '1 bitcoin = 100 million satoshis or sats',
>     subText: 'Hexa uses sats to make using bitcoin easier',

> heading: 'Hexa Test Account',
>     text: 'Test Account comes preloaded with test-sats',
>     subText: 'Best place to start if you are new to Bitcoin',

**List of loader Messages during Restore:**

> heading: 'Bootstrapping Accounts',
>     text: 'Hexa has a multi-account model which lets you better manage your bitcoin (sats)',
>     subText: '',

> heading: 'Filling Test Account with test sats',
>     text: 'Preloaded Test Account is the best place to start your Bitcoin journey',
>     subText: '',

> heading: 'Generating Recovery Keys',
>     text: 'Recovery Keys help you restore your Hexa wallet in case your phone is lost',
>     subText: '',

> heading: 'Manage Backup',
>     text: 'You can backup your wallet at 3 different levels of security\nAutomated cloud backup | Double backup | Multi-key backup',
>     subText: '',

>  heading: 'Level 1 - Automated Cloud Backup',
>     text: 'Allow Hexa to automatically backup your wallet to your cloud storage and we’ll ensure you easily recover your wallet in case your phone gets lost',
>     subText: '',

> heading: 'Level 2 - Double Backup',
>     text: 'Starting to hodl sats and bitcoin? Ensure that you backup your wallet atleast to Level 2 backup called Double Backup',
>     subText: '',

> heading: 'Level 3 - Multi-key Backup',
>     text: 'For hardcore Bitcoiners who understand Bitcoin, stack large amounts of sats or bitcoin and care for utmost security of their wallet',
>     subText: '',

**Comment by antuz123** [comment]
Get the right text that the user should see while login and 3 such texts while wallet creation.

**Comment by cakesoft-rohit** [comment]
This is what we are currently doing in wallet initialization.
![Simulator Screen Shot - iPhone 11 - 2021-08-11 at 11 12 25](https://user-images.githubusercontent.com/74172232/128975659-7320bcac-cb17-4b89-8070-bbae0073aeec.png)

**Comment by ASN-BitHyve** [comment]
List of loader Messages during Wallet Initialization:

heading: 'Test Account',
text: 'If you're a new user, the best place to start exploring the wallet is the Test Account',


heading: 'Free sats!',
text: 'Register with Swan Bitcoin to get $10 USD worth of free sats',


heading: 'Manage Backup',
text: 'Make sure to backup your wallet to secure your sats. The first level of backup is done automatically once you allow it',

**Comment by ASN-BitHyve** [comment]
List of loader Messages during Login:

heading: 'Savings Account',
text: 'The Savings Account unlocks once your backup is at Level 2. Once unlocked, setup your 2FA code on an authenticator app ',

heading: 'Non-custodial buys',
text: 'Get sats directly in your wallet from compatible exchanges',

heading: 'Friends & Family',
text:
'Add contacts to Hexa and send sats w/o asking for their wallet address every time',

heading: 'Donation Accounts',
text: 'Start receiving donations directly in your Hexa Wallet, from anywhere in the world',

heading: 'Satoshis or Sats',
text: '1 bitcoin = 100 million satoshis or sats',
subText: 'Hexa uses sats to make using bitcoin easier',

**Comment by ASN-BitHyve** [comment]
List of loader Messages during Restore:

heading: 'Manage Backup',
text: 'You can backup your wallet at 3 different levels of security\nAutomated cloud backup | Double backup | Multi-key backup',

heading: 'Level 1 - Automated Cloud Backup',
text: 'Allow Hexa to automatically backup your wallet to your cloud storage and we’ll ensure you easily recover your wallet in case your phone gets lost',

heading: 'Level 2 - Double Backup',
text: 'Starting to hodl sats and bitcoin? Ensure that you backup your wallet atleast to Level 2 backup called Double Backup',

heading: 'Level 3 - Multi-key Backup',
text: 'For hardcore Bitcoiners who understand Bitcoin, stack large amounts of sats or bitcoin and care for utmost security of their wallet',

heading: 'Recovery Keys',
text: 'Make sure you only share your Recovery Keys with trustable contacts',

**Comment by cakesoft-swati** [comment]
@ASN-BitHyve should have some message in the Login Screen for savings account.

**Comment by antuz123** [comment]
@cakesoft-rohit - we are going with small changing loader messages, not a single big one. Use the above for the three scenarios.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(339)
