### ISSUE TITLE
Text Change - Initial cloud backup

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3854]
"Choose any password. Keep it safe" to be changed to "Create a password. Make sure to remember it."

![2](https://user-images.githubusercontent.com/68264080/126957022-972a8735-ffc7-4459-8bdc-00f08d0358a1.jpg)

**Comment by summikhan11** [comment]
Doesn't fit the word limit @antuz123 
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/3e39ab7f-d7f0-4034-9fa0-9121accad1b4/

**Comment by antuz123** [comment]
"Make sure to remember it"

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(337)
