### ISSUE TITLE
Text changes - Initial cloud backup (2)

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3855]
1) The word "to" to be removed in images 2a and 4
2) S capital in Security Question in image 3

![2a](https://user-images.githubusercontent.com/68264080/126957803-b79750f7-7481-41a3-8213-e5b5d2c30544.jpg)
![3](https://user-images.githubusercontent.com/68264080/126957576-08bf9d22-5012-427b-93ab-85811ed105e3.jpg)
![4](https://user-images.githubusercontent.com/68264080/126957578-16fa8b8c-745e-4aea-abb5-a128856f7bda.jpg)

**Comment by cakesoft-swati** [comment]
- The changes contained in this issue have not been completed.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.5(325)
