### ISSUE TITLE
Home Screen minor changes

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3856]
Image 5- Cloud Backup > Cloud backup  
(Please disregard the highlight in image 5)

Image 6 - The Bitcoin symbol looks a little squished. 

![5](https://user-images.githubusercontent.com/68264080/126958459-2c987ceb-0e56-4ed5-b589-a6aeee0cba4f.jpg)
![6](https://user-images.githubusercontent.com/68264080/126958465-5f76ab43-f57b-45ea-adbd-7a7519c80449.jpg)

**Comment by cakesoft-swati** [comment]
Cloud Backup > Cloud backup
 @cakesoft-rohit The "B" of the backup should be in lowercase.
 
![temp (16)](https://user-images.githubusercontent.com/62699947/127336056-226527d0-d250-42c0-b21b-ab82aa5b9fd1.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.5(325)
