### ISSUE TITLE
Transaction population and enrichment

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3866]

**Comment by cakesoft-shashank** [comment]
@antuz123 please check these parameters 
accountName: "Test"
accountType: "TEST_ACCOUNT"
address: "2My916rwh5aVpaNCtXVmNGKZZbRNCLHD9Sz"
amount: 228
blockTime: 1627546160
confirmations: 8
date: "Thu, 29 Jul 2021 08:09:20 GMT"
fee: 226
primaryAccType: undefined
recipientAddresses: ["2Mx8eQJgymAJ7BdKCeCj3KCDLEXcgsLiDiA"]
senderAddresses: []
status: "Confirmed"
transactionType: "Sent"
type: "F&F"
sender: ""
receiver: ""
notes: ""
tags: []

**Comment by antuz123** [comment]
@Parsh - make sure the items marked as from AAL are present in AAL and are getting populated there

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
