### ISSUE TITLE
Wallet Name change

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3867]
When wallet name is updated, it should update the following too:
1.	Wallet name in the Wallet Image 
2.	Wallet name in the shared channels 
3.	Wallet name in the cloud backup 

4. Any other area

**Comment by antuz123** [comment]
Also need the edit button obvious in the App Info screen. @summikhan11

**Comment by cakesoft-swati** [comment]
Verified this issue on dev app v1.9.5(338)
