### ISSUE TITLE
F&F Request Accept/ Reject modal is not opening on clicking the deeplink.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3879]

**Comment by Parsh** [comment]
@cakesoft-rohit The model is opening sometimes(even on the simulator), I just confirmed it. There's something at the level of the UI which blocks the model from showing up or the linking listener is not able to pick up the URL and send it to deep link processing mechanism.

**Comment by cakesoft-swati** [comment]
- The model is not opening on iphone.
- In ios when I click on the link it opens the following page.
<img width="375" alt="2A9EB4DB-11F3-4240-A56F-9152958F213B" src="https://user-images.githubusercontent.com/62699947/127838999-924a8b4c-c7fe-421c-8fc0-267eeb84603b.png">

- On Android it is opening only when the app is closed.If I click on the deeplink when the app is in background the this model is not opening.

**Comment by cakesoft-utkarsh** [comment]
The SSL certificate for hexawallet.io expired today, so we are getting security warnings on opening links, which prevents opening deep-linking.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.0(329)
