### ISSUE TITLE
Smart vs Hard sync

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3884]
- [x] On login for 2.0 - all account sync (smart sync) 
- [x] On pull down - full sync of that account 

Take out the account settings - hard refresh and full settings - blind refresh

_Originally posted by @antuz123 in https://github.com/bithyve/hexa/issues/3840#issuecomment-888262044_

**Comment by Parsh** [comment]
All accounts(w/ default visibility) smart sync, post-login, has been activated

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.0(329)
