### ISSUE TITLE
Unable to proceed on Ramp & Wyre buy

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3891]
- Clicking on the "Buy Bitcoins" button on both the accounts is doing nothing further.

https://user-images.githubusercontent.com/62699947/127508200-edaa3941-928e-4947-83ad-0902efb293d3.mp4

**Comment by Parsh** [comment]
Probably ramp/wyre sagas are expired(using legacy account structure) and would need to be refactored.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.0(329)
