### ISSUE TITLE
The "Note" is getting cut from the bottom.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3892]
![Screenshot_20210728-161933](https://user-images.githubusercontent.com/62699947/127508820-38e9b6fc-aa3f-4997-b7f5-d4f80d0079d4.jpg)

**Comment by cakesoft-rohit** [comment]
@summikhan11 If we add Note then it does not fit-in on small screen devices

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/99d6634c-fa8d-4f4a-bfcd-f0474121d854/

**Comment by cakesoft-swati** [comment]
@cakesoft-rohit still having the same issue on dev app v1.8.5(326)
