### ISSUE TITLE
Use personal device for secondary mnemonic - L2 for savings account 

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3896]
### Description:
Ability for the user to create savings account only after security level 2 is completed by fetching the secondary mnemonic from the personal device of level 2.

**Flow:**

User taps on add new from home page -> savings account
If the user has not completed security level 2, he/she will be prompted to complete level 2 first to create savings account.
After creating level 2, savings account will fetch the secondary mnemonic from the personal device of level 2 instead of creating it within the app.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(338)
