### ISSUE TITLE
BTC value and Buy.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3898]
- @summikhan11 It does not look right please check.
![temp (21)](https://user-images.githubusercontent.com/62699947/127660908-f5ee334a-a705-47fc-ba91-56eb7de86356.jpg)

**Comment by summikhan11** [comment]
this looks like the old design, not sure why we're using it
@antuz123

**Comment by antuz123** [comment]
@summikhan11 - we are not doing the graph or the Buy tab in 2.0. 

We need a buy button on Home and 4 tabs. 

Only 2-3 integrations in any location and no sell etc. 

So suggest the right design with Buy on Home with exchange rate.

**Comment by cakesoft-rohit** [comment]
Moved to 1.9.5 in https://github.com/bithyve/hexa/issues/3943 issue
