### ISSUE TITLE
Changes in Buy bitcoin > Ramp

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3899]
- Don’t need this. And the second one will be checking Account with the Checking Account logo. Not Ramp
![temp (22)](https://user-images.githubusercontent.com/62699947/127664930-8f383a90-af8c-4028-bdb8-a1559fca846f.jpg)

**Comment by cakesoft-rohit** [comment]
@summikhan11 
Here we have to add a drop down list for 'Account Type' selection in both Ramp and Wyre Modals
Need UX for this screen

**Comment by cakesoft-rohit** [comment]
Will be doing after 2.0 as discussed

**Comment by cakesoft-swati** [comment]
The mentioned change has not happened.

**Comment by cakesoft-swati** [comment]
- I'll have to check this in the next build.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.8.5(327)
