### ISSUE TITLE
Buy options 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3906]
Buy will have only 2-3 options in 2.0 and will not have a complete tab in 2.0. 

Need more details with each option though. 

Name, short description, "Fee details" link, "Supported regions" link, "Supported methods" link

**Comment by antuz123** [comment]
Ramp 

Fee link: https://support.ramp.network/en/article/what-are-your-fees-1atf5lv/
Supported regions: https://support.ramp.network/en/article/what-countries-do-you-support-1ua7sn1/

**Comment by antuz123** [comment]
Wyre

Fee: https://support.sendwyre.com/hc/en-us
Regions: https://support.sendwyre.com/hc/en-us/articles/360055233754-Geographic-Restrictions-

**Comment by antuz123** [comment]
FastBitcoins

Fee: https://fastbitcoins.com/help
Regions: https://fastbitcoins.com/help

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(337)
