### ISSUE TITLE
Transaction Population: receivers integration

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3920]
Receiver/SentTo entity can be picked up in the following ways
At successful end of the send flow, we can either
- take the recipients and store them against the txid in a txid to recipients mapping
- store the recipients against one of the input UTXO addresses for this transaction in the AAL

**Comment by cakesoft-swati** [comment]
- Txn not showing the Sender name in received transaction.
 - Txn showing "Undefined" tag for address in multi send.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(338)
