### ISSUE TITLE
Two-FA for Contact QRs

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#3925]
We would like to have the QR encrypted when the user selects a 2FA option(num/email/OTP) along w/ the deep link.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.0(329)

**Comment by Parsh** [comment]
Fixed:
- Email incorrect error
- On scanning 2FA enabled QR code, I'm getting bottom sheet for all the 3 cases(num, email and otp) w/ proper input boxes. Number decryption worked fine, email after fix is also working, for OTP @cakesoft-rohit is looking into it as the accept button wasn't working, plus OTP display bottom sheet doesn't come up till copy button is used(which doesn't really works in QRs case).

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(335)
