### ISSUE TITLE
Show all accounts

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3939]
Once a user clicks on "Confirm" they should be brought to the Account Management Screen.
![15](https://user-images.githubusercontent.com/68264080/128524474-a47f90c5-56f6-4e88-8cb5-355a10ca7454.jpeg)
![16](https://user-images.githubusercontent.com/68264080/128524482-ac76806a-cec5-4a3c-afb5-a3fc19973cd4.jpeg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(339)
