### ISSUE TITLE
Line Placement FBTC

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3944]
The placement of the line in the app looks a little weird.
![3](https://user-images.githubusercontent.com/68264080/128641252-13572357-c441-436a-8f18-1e9a3dea2571.jpg)

**Comment by cakesoft-rohit** [comment]
@ASN-BitHyve 
Please suggest what we can do here

**Comment by cakesoft-rohit** [comment]
@ASN-BitHyve 
Is this looks okay? ![Simulator Screen Shot - iPhone 11 - 2021-08-11 at 11 16 14](https://user-images.githubusercontent.com/74172232/128976003-76452191-18ce-4051-b19c-4b7e09e9be9d.png)

**Comment by cakesoft-swati** [comment]
- FBTC is removed for now.
