### ISSUE TITLE
New Passcode Screen

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3948]
1) I went to change my passcode. I entered wrong passcode there. It gave me error message, but did not clear out the code I had entered. The app should clear out the wrong code and the cursor shoudl come back to the leftmost box.
![6](https://user-images.githubusercontent.com/68264080/128642094-560905d3-b720-46ef-a5b4-335ae80052f9.jpg)

2) “Please enter a new passcode”
![7](https://user-images.githubusercontent.com/68264080/128642114-5d9e5ebf-2357-4410-ac3e-b352ac83d967.jpg)

3)  “Please re-enter new passcode”
![8](https://user-images.githubusercontent.com/68264080/128642129-5f548608-0bdf-494f-9bdd-de5de0bd15dc.jpg)

**Comment by cakesoft-swati** [comment]
1) “Please enter a new passcode”
![7](https://user-images.githubusercontent.com/68264080/128642114-5d9e5ebf-2357-4410-ac3e-b352ac83d967.jpg)

2)  “Please re-enter new passcode”
![8](https://user-images.githubusercontent.com/68264080/128642129-5f548608-0bdf-494f-9bdd-de5de0bd15dc.jpg)

**Comment by ASN-BitHyve** [comment]
@cakesoft-swati to check and close.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0(349)
