### ISSUE TITLE
Wherever appropriate, replace "Restore" with "Recover" across the entire app. 

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3950]
This particular issue shows just one image. Abhilash to help the developers if need be.
Suggestion: An issue could be created with every line that has "restore" in it and Abhilash could take a look and make changes based on context. Something similar to the Error Messages issue. 

![9](https://user-images.githubusercontent.com/68264080/128642261-c98d98ee-658f-4c25-83cd-17701b31b667.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(338)
