### ISSUE TITLE
Text Change (Will require coding effort)

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3951]
Checking Account > Send > Send to Account - On clicking on any account once we go to the next screen, on top it says, " Send to Contact". It should say, "Send to Savings Account" or whatever corresponding account a user is sending sats to.

**Comment by cakesoft-rohit** [comment]
@ASN-BitHyve  What if we selected multiple account?
All account will not fit in Header
![Simulator Screen Shot - iPhone 11 - 2021-08-10 at 13 48 47](https://user-images.githubusercontent.com/74172232/128833034-4de63a48-934a-4939-bf10-55645fa57c75.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(338)
