### ISSUE TITLE
Send Button Color

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3953]
Suggestion: The send button should not have a red hue as it conveys a sense of danger/caution, etc.
Observation: Looking at 4 wallets revealed that all of them are using same color for send and receive.

@summikhan11 to give this a thought. 

![14](https://user-images.githubusercontent.com/68264080/128642694-ae81693b-1d7a-4708-b214-f21d200dba28.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/2f42c330-be9a-4b0a-963d-698d60da4894-7a11/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0(349)
