### ISSUE TITLE
Receive > "The amount should show on the main screen"

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3954]
Anant's Feedback: "The amount should show on the main screen"

https://bithyve-workspace.slack.com/files/USH7J1J9F/F02AB98HXV1/20210805_205852.mp4

**Comment by cakesoft-swati** [comment]
Also @cakesoft-rohit Unable to scan the QR code of Receive bitcoin> Receive screen.

**Comment by cakesoft-swati** [comment]
- Receive and Back buttons are still not working.Tested on dev app v1.9.5(335)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(338)
