### ISSUE TITLE
Text changes

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3955]
1) "A" and "D" need not be capital

![19](https://user-images.githubusercontent.com/68264080/128642916-5797bba4-8a4a-4fc6-9cba-99fb4fcb4eae.jpg)

2) Approved > Accepted
![21](https://user-images.githubusercontent.com/68264080/128642978-f208eb8e-2d59-46ab-87ff-a0aa3946566b.jpg)
![20](https://user-images.githubusercontent.com/68264080/128642967-28a5aee5-8dd5-4c80-aeb8-b165a7257755.jpg)

3.1) "Last seen: Unknown"
3.2)  No "_ (Underscore)" before and after "Unknown".
![22](https://user-images.githubusercontent.com/68264080/128643018-5ede2fb9-113e-4d82-b556-ca34ad499931.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(338)
