### ISSUE TITLE
Text addition on Swan Bitcoin Account

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3960]
Please disregard the marker highlight on Not Now.

Add the line: "Note: Please register with Swan Bitcoin to use this account" below second para.

![29](https://user-images.githubusercontent.com/68264080/128643736-4fb0cf67-a0da-4a3e-8c5d-5ebbf703107c.jpg)

**Comment by cakesoft-swati** [comment]
- Verified tis issue on dev app v1.9.5(330)
