### ISSUE TITLE
On iPhone 12, Header works incorrectly (Touching SafeArea on top)

### ISSUE THREAD

**Issue by cakesoft-rohit** [bithyve/hexa#4038]
<img width="1440" alt="Screenshot 2021-08-19 at 6 05 23 PM" src="https://user-images.githubusercontent.com/74172232/130069247-d58e471c-b2c1-44e9-a6a7-2b5c1cdad1d6.png">

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v 1.9.5(338)
