### ISSUE TITLE
Swan disabling from background 

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4039]
![Screenshot_20210819-123532](https://user-images.githubusercontent.com/62699947/130082440-fc8743a8-5ae0-492c-92c5-9b2656ec1e8f.jpg)

![Screenshot_20210819-123540](https://user-images.githubusercontent.com/62699947/130082508-12c0897c-d3ac-4f10-a4a3-597d28ca41d0.jpg)
- Need to check the messages.

**Comment by antuz123** [comment]
Sending it separately to Swati

**Comment by antuz123** [comment]
First screen: 

Stack Sats with 
Swan Bitcoin 

This is your Swan Bitcoin auto-withdrawal wallet. When you stack with Swan Bitcoin, your sats will automatically get transferred to this self-custody account in Hexa once it reaches auto-withdrawal limit of 0.01 btc. 

Claim a signup credit of $10 when you complete the process 

CTA: Sign me up; Not Now

**Comment by antuz123** [comment]
Second screen (new screen on clicking Sign me up on the first screen 

Stack Sats with 
Swan Bitcoin 

By proceeding you understand that you will be taken to Swan Bitcoin to complete the process

Please check the available payment methods along with Terms and Conditions for using Swan Bitcoin as per your jurisdiction 

CTA: Sign Me Up; Not Now

**Comment by antuz123** [comment]
Bug: if you take the app to the background and come back the Swan Account becomes accessible and does not show the modal. you can even Send and Receive.

**Comment by antuz123** [comment]
Third screen (when you come back from Swan. The first screen above) 

Your Hexa Wallet is communicating with Swan Bitcoin...
This account is being linked with your profile on Swan Bitcoin. All auto-withdrawal sats will be sent to this account in Hexa

**Comment by antuz123** [comment]
Fourth screen (Second screen above)

Successfully linked
Your Hexa Wallet is now successfully linked to your Swan Bitcoin account. Sats will be transferred to Hexa as soon as you accumulate 1 million sats or 0.01 btc

**Comment by cakesoft-swati** [comment]
> Bug: if you take the app to the background and come back the Swan Account becomes accessible and does not show the modal. you can even Send and Receive.

Still having the same issue on dev app v1.9.5(337)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0(349)
