### ISSUE TITLE
BTC Symbol alignment on home page

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4048]
The btc symbol is not properly aligned with zero. In the account section its weirdly placed and top aligned with zero. Beneath the wallet name it is bottom aligned.

Anant's comment: Check with UX @cakesoft-swati 

![17](https://user-images.githubusercontent.com/68264080/130390292-840bfb39-e45d-4430-ac80-f66956aba129.jpg)

**Comment by cakesoft-swati** [comment]
- The BTC symbol is still not properly aligned. See the XD link The BTC symbol is exactly in front of the zero.
https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/?fullscreen

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(335)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(335)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(335)

**Comment by ASN-BitHyve** [comment]
Reopening this age old issue. The problem persists.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(469)
