### ISSUE TITLE
Text changes beneath QR

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4055]
"A" should be small letter in image below.

Anant's comment: Make the second word of **all** QR to begin with a small letter. 

![7](https://user-images.githubusercontent.com/68264080/130391344-e6e3ad7c-bf48-4acd-ac9a-a703f3e9e2ff.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(331)
