### ISSUE TITLE
FAQ UX on the website

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4059]
FAQ is going to HEXA website. It should directly go to faq section within the website : https://hexawallet.io/faq/

![10](https://user-images.githubusercontent.com/68264080/130392683-8a882af1-4c79-468b-99f1-86a3c9883f52.jpg)

**Comment by cakesoft-rohit** [comment]
@antuz123 want link for FAQ

**Comment by cakesoft-swati** [comment]
![temp (39)](https://user-images.githubusercontent.com/62699947/130591586-677aaac3-a5db-41bb-b942-470c70eadc28.jpg)
-Now the heading (Hexa FAQ) is being cut from above.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(331)
