### ISSUE TITLE
Account Settings - Arrow visibility

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4063]
Ux suggestion: Should the arrows be a little more prominent? Maybe a little bigger and in black color? I'm sure older people would have to squint to see it.

![14](https://user-images.githubusercontent.com/68264080/130393406-8cc47c11-4f46-4857-8f75-f2f3771110f2.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(330)

**Comment by summikhan11** [comment]
they seem fine here
https://xd.adobe.com/view/586337d9-4b1f-4d3b-9431-d48711ef8697-0d30/screen/fa994876-936a-4324-9cea-a582c39e759a/
