### ISSUE TITLE
Changes for existing contact

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4069]
1. change keeper type option to normal options like - contact, pdf and device
2. use existing contact if present or redirect to contact flow 
3. changes in UI like change icon for contacts and change title for existing contact and phone book
https://xd.adobe.com/view/3c76a519-ed48-4944-a7a5-026a2aca5a6d-6925/screen/43aec3f9-de30-43ca-96cf-a22de90c51aa/

**Comment by cakesoft-swati** [comment]
- For now we removed this existing contact functionality from 2.0
