### ISSUE TITLE
Textual change for donation account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4071]
- There is some Dummy text on Donation page, would need actual text.
- Actual text: “Scan the bitcoin address QR or copy it in your wallet to send donation”
![Screenshot from 2021-08-23 15-09-15](https://user-images.githubusercontent.com/62699947/130435897-79c8d5b5-439f-4b64-b1b4-5d98407e7ef6.png)

**Comment by cakesoft-utkarsh** [comment]
![Screenshot 2021-08-24 at 10 46 50 AM](https://user-images.githubusercontent.com/18442573/130559813-4f182173-74ab-4c10-9fdc-dd0c8e660959.png)
Need text on this section as well. @cakesoft-swati

**Comment by cakesoft-swati** [comment]
@antuz123 Please suggest the text for above screen as well.

**Comment by cakesoft-swati** [comment]
@cakesoft-utkarsh The text should be:

Our Supporters
Join the community by donating to the cause

**Comment by cakesoft-utkarsh** [comment]
Done.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0(351)
