### ISSUE TITLE
Existing contact UI changes

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4074]
https://xd.adobe.com/view/3c76a519-ed48-4944-a7a5-026a2aca5a6d-6925/screen/43aec3f9-de30-43ca-96cf-a22de90c51aa/
![Screenshot 2021-08-23 at 5 02 18 PM](https://user-images.githubusercontent.com/50820210/130445354-6513cf6a-b50c-4fd5-bfce-d898b388ce38.png)

**Comment by antuz123** [comment]
Subtitle: Select an exerting contact or add from the address book 

"Choose from address book" against the Address Book

**Comment by antuz123** [comment]
We will have F&F list at the top like on the Send screen and the phonebook will appear at the bottom.

**Comment by antuz123** [comment]
Title: Send Recovery Key 
Text: Send the Recovery Key to your Friends & Family, or select a new contact from the address book 

The heading for existing contacts will be "Friends and Family", then for address book it will be "Select from address book"

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/3c76a519-ed48-4944-a7a5-026a2aca5a6d-6925/screen/43aec3f9-de30-43ca-96cf-a22de90c51aa/

we dont need another heading here

**Comment by cakesoft-swati** [comment]
- For now we removed the existing contact functionality from 2.0
