### ISSUE TITLE
Text change after Secure with 2FA

### ISSUE THREAD

**Issue by cakesoft-rohit** [bithyve/hexa#4083]
Number >>>
![Simulator Screen Shot - iPhone 11 - 2021-08-25 at 09 12 14](https://user-images.githubusercontent.com/74172232/130722798-061f549a-dcf4-44de-b906-ff9612eda2b7.png)

Email >>>
![Simulator Screen Shot - iPhone 11 - 2021-08-25 at 09 12 56](https://user-images.githubusercontent.com/74172232/130722844-c7da8264-ae9d-45c9-b3e8-2f994bde6958.png)

OTP >>>
![Simulator Screen Shot - iPhone 11 - 2021-08-25 at 09 13 31](https://user-images.githubusercontent.com/74172232/130722895-cc509664-755d-4f32-9cf7-c52e4743a28b.png)

**Comment by cakesoft-rohit** [comment]
OTP Model
![Simulator Screen Shot - iPhone 11 - 2021-08-25 at 10 34 03](https://user-images.githubusercontent.com/74172232/130729912-e763bd97-58f8-4edf-958a-48794bca3d57.png)

**Comment by antuz123** [comment]
Initial message: 
Heading: Secure with additional factor 
Text: You can optionally add a second factor when you are sending the link/ QR through an unencrypted channel

On selecting email: 
Heading: Secure with contacts email 
Text: Your contact will have to verify their email '<abc@xyz.com>' to accept the request 

On selecting phone number: 
Heading: Secure with contacts phone number 
Text: Your contact will have to verify their phone number '<12345>' to accept the request 

On selecting OTP: 
Heading: Secure with OTP 
Text: Your contact will have to confirm the OTP <12345> to accept the request

**Comment by antuz123** [comment]
Remove the OTP modal for now as its flow is not clear. We need it to come for the QR as well if we want to use the modal. @cakesoft-rohit

**Comment by antuz123** [comment]
On the selection modal. 

Heading: Select the second factor 
Tope text: Select one of the below to add as a second factor to your link/ QR 
Below text: (Use the Note format) Note: If the communication channel is not encrypted/ secure, the second factor sent through a different channel improves the security guarantees

**Comment by antuz123** [comment]
Bug: if you don't make any selection on the model and come back, the screen hangs.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(337)
