### ISSUE TITLE
F&F Refresh shouldn't take time.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4086]
- [x] F&F refresh should not take much time. Very little to gauge at this stage.
- [x] if Network in not there list do not shows any contacts in list. List is empty when network is not there.

**Comment by GourabSanyal** [comment]
The contact list is there when the internet is off.

**Comment by cakesoft-swati** [comment]
- As discussed with dev,this happens on slow interenet, otherwise it takes a very standard time.
- Also, because we’re shifting to Hexa-Keeper and Pay, the architecture of F&F would anyway get modified
