### ISSUE TITLE
Textual changes on wallet setup screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4089]
1. This does not seem as per the UX. Check the UX For the way bands are used only.
Use the below text:
2. Top text is New Wallet (remove the term Hexa)
3. Subheading is: The app creates a new wallet for you with accounts you can start using right away
4. Second heading is “Existing Wallet”. Sub heading: If you previously had a Hexa wallet you can recover it
Leave the Terms and Condition thing at the bottom.
![File (59)](https://user-images.githubusercontent.com/62699947/130768788-be890d50-8188-4564-b64a-c47022eb5e01.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/182db13e-dc6a-40ec-a319-5bf018182399-4d7e/screen/e2b5fd4a-d31d-464e-8b14-3202deb28a52/

**Comment by cakesoft-shivani** [comment]
Done point 2,3,4 UI changes remaining

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0(349)
