### ISSUE TITLE
Donation webpage: broken link

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#4101]
The new donation webpage is not showing up for staging and apparently for live as well.
Staging links to old webpage works: https://hexawallet.io/donate-stage/?donationid=7f4eb02e49e21ae
But not to the new one: https://hexawallet.io/donation-stage/?donationid=7f4eb02e49e21ae

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev and staging app v2.0.0(352)
