### ISSUE TITLE
Buy with Ramp/Wyre.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4106]
- Nothing is happening next to it while doing Buy with Ramp .

https://user-images.githubusercontent.com/62699947/130930070-532a9b45-f414-460b-82f5-f0b54ee42f54.mp4

- Also when we do the Buy with Wyre,I can put all the card details but at last didn't get any verification code.
- Bitcoin should be transferred to Checking Account .
- Tested on dev app v1.9.5(332)

**Comment by antuz123** [comment]
I am facing the same issue.

**Comment by cakesoft-swati** [comment]
Ramp and Wyre are working properly.Anant sir has confirmed this.
