### ISSUE TITLE
Expanding Universal link/deeplink beyond SSS

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#413]
We should have a prefix in the URL that can be used to indicate type for different Universal Links. At the moment we only have SSS based deep links/universal links. 
 We can have many other types in the future so we should have a way to know the difference for each one.  
We need to come up with one for getBittr and fastBitcoins next.

Note: To avoid confusion Universal Links will refer to both Universal Links and Deep Links.

**Comment by Parsh** [comment]
The new format for DL would resolve the given issue. Available in the latest version.
