### ISSUE TITLE
getBittr Account Setup

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#414]
Currently the saga for getBittr xpub verification is sending a dummy xpub. 
Correct xpub should be generated and sent instead of the dummy.
The allocated path and other details should be saved in the app database.

  xpub is sent via this service [https://github.com/bithyve/hexa/blob/ef1ee0a030e1797331d260988157c952bd1b2e50/src/services/bittr.ts#L41
](https://github.com/bithyve/hexa/blob/ef1ee0a030e1797331d260988157c952bd1b2e50/src/services/bittr.ts#L41
)

All the dummy data is currently being picked up from here: https://github.com/bithyve/hexa/blob/development/src/storage/bittr.ts

We need to update to retrieve this set of data from the correct location in our database where required. Most of the data will be sent by the screens as it will be available in the existing state.

Depends on issue #412

**Comment by Parsh** [comment]
GB Xpub generation available as a part of derivative accounts
