### ISSUE TITLE
Check the UX.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4145]
![temp (59)](https://user-images.githubusercontent.com/62699947/131345659-2c8bbaa7-aa5c-4fc6-b303-9a1f8475d53a.jpg).
- Check the text color.

**Comment by cakesoft-shashank** [comment]
@cakesoft-shivani please check sats color

**Comment by cakesoft-swati** [comment]
- The color is still different on dev app v1.9.5(335)
![Screenshot_20210831-193612](https://user-images.githubusercontent.com/62699947/131517981-fbddc37f-daea-4aec-a800-376da23b8da5.jpg)
- This is from live app.

![Screenshot_20210831-193553](https://user-images.githubusercontent.com/62699947/131518176-74b647cc-f09b-43a2-92b6-66379009d7ff.jpg)
- This is from dev app.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(339)
