### ISSUE TITLE
1.0b: Need a message on HS

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4168]
Need a message somewhere on HS of version 1. For the user to move to 2.0. With a link to download 2.0.

**Comment by cakesoft-shivani** [comment]
Want text to put on home page @antuz123

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/

**Comment by ASN-BitHyve** [comment]
Message: Hexa wallet is better than ever before. Faster loading, new features, improved security and a host of other features have been built into Hexa 2.0 
Button Text: Upgrade to Hexa 2.0 

@cakesoft-shivani @antuz123

**Comment by antuz123** [comment]
@ASN-BitHyve - there is very little space on the HomeScreen. 

@cakesoft-swati - what is the limit?

**Comment by cakesoft-swati** [comment]
- Verified this issue on app v 1.7.0(298).
