### ISSUE TITLE
Total Balance of accouts.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4181]
- Test account's total balance is showing wrong after wallet restore. 
![Screenshot_20210901-160328](https://user-images.githubusercontent.com/62699947/131656928-bddbee08-9851-46a9-ba1d-6d23195e40ad.jpg)

- Also the  balance is not visible on the home page( Before and after restore).I put 2.5k test sats in my checking account and yet the number on top is zero.

![tempFileForShare_20210901-155658](https://user-images.githubusercontent.com/62699947/131656696-8d38b77b-c945-4c1a-aa00-cd8317e3254e.jpg)

**Comment by Parsh** [comment]
Test account restored perfectly fine for me both the times(using cloud).

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(338)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(338)
