### ISSUE TITLE
Swan bitcoin logo.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4182]
- Swan bitcoin logo is different outside and different within the account.
![tempFileForShare_20210901-160006](https://user-images.githubusercontent.com/62699947/131657408-0331e287-bf3a-482f-89f3-2ec563e4d87f.jpg)
![Screenshot_20210901-160804](https://user-images.githubusercontent.com/62699947/131657899-7925158e-5478-4249-8dc7-5c8d0f599cf9.jpg)

**Comment by cakesoft-rohit** [comment]
@cakesoft-swati  Refer to these links
HomeScreen: https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/
Swan Acc: https://xd.adobe.com/view/9ddd4098-4cc4-4b13-bdb6-7a3bfb95826c-c88e/screen/beb54a8d-a4ed-4e80-9422-cce44990ac8e/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v.9.5(337)
