### ISSUE TITLE
Check the UX.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4190]
- In the current live app, it shows that there is something when you scroll but here that effect is not there. Check UX.
![temp (65)](https://user-images.githubusercontent.com/62699947/131661874-674b8e56-3985-45af-a9e5-a7407c3df193.jpg)

**Comment by summikhan11** [comment]
we show additional cards like that. so if there's only four, you dont see anything on the right. if there's more you will

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/screen/34afa180-7e2e-44fc-956b-13afd43b6f03/
this is a view where there's just four cards so no scroll, the screen next to this is where the user has scrolled @Raheel1258

**Comment by cakesoft-swati** [comment]
- Verified by Gourab on dev app v2.0.75(455)
