### ISSUE TITLE
Text change on Swan bitcoin.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4195]
- Remove ‘auto-withdrawal limit’. Note should be: “Please login/ register your Swan Bitcoin Account to use this wallet”
![temp (67)](https://user-images.githubusercontent.com/62699947/131668232-f4778903-906a-42e4-a3e5-28440f0ab78a.jpg)

- Use the same note as the previous screen. New text sent. Also this screen should use a step indicator like we have with wallet initialisation steps. With a dot and dash etc.
![samenote](https://user-images.githubusercontent.com/62699947/131677140-2acb4fe8-2ab1-41d5-a401-ebf5160b56d3.jpg)

 - Add: “This may take a few seconds, please do not close the application”
![thismaytake](https://user-images.githubusercontent.com/62699947/131677462-4862b960-2428-4412-bb9c-c58726828c61.jpg)

**Comment by cakesoft-rohit** [comment]
@antuz123 
Referring to 1st image if we remove 'auto-withdrawal limit' then sentence looks incorrect. 
Need feedback

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(338)
