### ISSUE TITLE
Enable Swan

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#4198]
- Need to use the usable flag for registration process as well
- This flag should be properly backed up and used after restore
- Both UI restrictions should be with the flag

**Comment by Parsh** [comment]
I've written the swan account [enablement](https://github.com/bithyve/hexa/pull/4197/commits/c3d7256301f617fc0397ab65f672ec63a0e694a7) code where Ali sir mentioned it.

The UI restriction using isUsable flag is what's left

**Comment by cakesoft-swati** [comment]
- Tested by @antuz123
