### ISSUE TITLE
Notification chanages.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4201]
- Once notification list is opened, all unread items become read and the red dot goes away.
![onceopen](https://user-images.githubusercontent.com/62699947/131676701-ae23d51d-af35-4d7d-b131-c3b27e2e7e07.jpg)

**Comment by cakesoft-shashank** [comment]
Not able to reproduce

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0(349)
