### ISSUE TITLE
Minor chnages for Swan account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4202]
-  we don't want a red dot here if there is no new transaction.
![don't need red dot](https://user-images.githubusercontent.com/62699947/131677951-e248d63b-c021-40e0-a0cf-0ee8999d7eb0.jpg)

**Comment by cakesoft-rohit** [comment]
@antuz123 
As discussed with Summi we are not showing Register tag on Swan, so we are using red dot as indicator for that.
Need clarity on this

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(338)
