### ISSUE TITLE
Check the note format.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4229]
- Notes have a very different layout. Use that, here and in Security> I am the Keeper of
![noteshvdiff](https://user-images.githubusercontent.com/62699947/131993909-e984f9f0-f020-488e-a956-ba24d4fb00a2.jpg)

- This is the notes format to be used.
![Screenshot_20210903-162617](https://user-images.githubusercontent.com/62699947/131994870-7790caa0-f136-4ad9-983c-706a4f1096b5.jpg)

**Comment by cakesoft-rohit** [comment]
<img width="1440" alt="Screenshot 2021-09-03 at 5 22 24 PM" src="https://user-images.githubusercontent.com/74172232/132000985-6a0ea0b1-8c4a-4323-8fdd-f4745f773096.png">

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.0(353)
