### ISSUE TITLE
[Dev] GetBittr: SEPA details for GetBittr.

### ISSUE THREAD

**Issue by cakesoft-utkarsh** [bithyve/hexa#423]
We are only getting the transaction remark from GetBittr customer API.
Along with the transaction remark we need to show 
Amount:
Occurrence: 
Account Holder:
IBAN Number:
BIC Code:
So we need a simple API that returns these details from server.  ANd mobile app do not have to hardcode this within the app.

**Comment by Parsh** [comment]
API is now available on the Relay.
