### ISSUE TITLE
Donation web changes.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4240]
- Need to change the color of donation icon. It is purple in the app.
![temp (72)](https://user-images.githubusercontent.com/62699947/132180915-3f7b4ec4-ad4e-4230-b699-dbd01b598b4f.jpg)

- Check the space with UX. There is so much space that I have to scroll the page every time.Also due to this I can't see the heading "waiting for donation".So check the alignment and if necessary do it centrally aligned as well.
![temp (73)](https://user-images.githubusercontent.com/62699947/132182126-8b928801-5e59-4142-b42f-b8db127ae3cd.jpg)
![temp (74)](https://user-images.githubusercontent.com/62699947/132182179-3a7bf2c6-bea9-4942-9e1e-7c5386bf4878.jpg)

- "Waiting for donation" should be moving.There should either be 3 dots that will keep moving or just a moving gear icon should appear as we show it on loader messages.
![temp (75)](https://user-images.githubusercontent.com/62699947/132182402-50d58f76-4a40-4a1d-a4df-281b6c011d96.jpg)

- No need of Twitter handle here again. So remove this text box and also remove that "Post to Twitter" button.
![Screenshot_20210906-120333__01](https://user-images.githubusercontent.com/62699947/132183855-6bbd5e20-336f-456f-a1a3-52f4fbf39401.jpg)

- Check the shadow with Ux.
![temp (77)](https://user-images.githubusercontent.com/62699947/132189688-b37a2c95-80cb-4b09-994e-b11f8116a5aa.jpg)

- Text change :
 "I just donated some sats to <cause name>. You too can support them here: (give link)"
 
![Screenshot_20210906-123932](https://user-images.githubusercontent.com/62699947/132231505-35138300-7cc3-4086-908d-e5f89a2f378a.jpg)

**Comment by cakesoft-utkarsh** [comment]
These comments are fixed and verified on 
https://hexawallet.io/donation-test/?donationid=dafc3d1fecd762b

**Comment by cakesoft-swati** [comment]
- Text change :
 "I just donated some sats to <cause name>. You too can support them here: (give link)"
 
![Screenshot_20210906-123932](https://user-images.githubusercontent.com/62699947/132231505-35138300-7cc3-4086-908d-e5f89a2f378a.jpg)
- This text change is not updated on webpage.

**Comment by cakesoft-swati** [comment]
- Verified these changes in 2.0
