### ISSUE TITLE
Cloud error message change 

### ISSUE THREAD

**Issue by cakesoft-rohit** [bithyve/hexa#4271]

**Comment by antuz123** [comment]
@cakesoft-rohit - the text should be very small. This is not correct. 

Use:

Cloud Backup Error 

The wallet could not be backed up. This may be due to network issues. Please try again and if the problem persists, contact us at hexa@bithyve.com

**Comment by antuz123** [comment]
You won't need any icons

**Comment by antuz123** [comment]
Also reduce the size of the modal accordingly

**Comment by cakesoft-rohit** [comment]
Ok

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.01(374)
