### ISSUE TITLE
UI issue 

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4273]
![Image from iOS](https://user-images.githubusercontent.com/50820210/132631334-3d5c8161-8465-4c2f-8e7b-e62bd21826ab.jpg)
![Image from iOS (1)](https://user-images.githubusercontent.com/50820210/132631415-f3a4a400-5de9-4f40-a385-4a81deabd5b2.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0(351)
