### ISSUE TITLE
Getting stuck after restore when we skip backup on wallet creation

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4275]

**Comment by cakesoft-swati** [comment]
- Wallet name is not being found in the dropdown at the time of wallet restore.

**Comment by cakesoft-shivani** [comment]
Might be cloud data get full because of testing data

**Comment by cakesoft-shivani** [comment]
delete app fron cloud and check
Not reproducing my side

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(378)
