### ISSUE TITLE
Flow change of approval for New keeper setup or change keeper

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4283]
1. Create channel from primary hexa app and put RK to channel and other data except Secondary share
2. After setup channel keeper will scan QR from Primary hexa app
3. After that Keeper will scan Approval key from other keeper 
4. Then download Secondary key and store to your own channel with Primary hexa app

**Comment by cakesoft-swati** [comment]
- Approval key flow is not woring as expected in dev app v2.0(345)
- I scanned the secondary key for level 3 share,after scanned the QR it got stuck on security & Privacy page.
- Also the level 2 was completed still it was showing the confirm button and the page is showing only the contact icon, not the contact name.
![temp (90)](https://user-images.githubusercontent.com/62699947/133274623-4e19b501-3fcb-4120-8f5d-8e44901b28dd.jpg)
- It is not seeking approval at level 2. Can't understand the flow. There is no message to scan the approval key. It requires UI.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.0(353)
