### ISSUE TITLE
Minor UI issue if we Skip Backup.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4293]
- In the case of skip backup, when we go to set the password, there is a dot of background image which overlaps the "got it".
![temp (82)](https://user-images.githubusercontent.com/62699947/132895714-8fd3372f-2c91-4ce3-bad7-578d10c7b5a6.jpg)

**Comment by cakesoft-shivani** [comment]
https://github.com/bithyve/hexa/commit/94edafcc58058ab33adbb86c4e498f9789e26c49

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0(351)
