### ISSUE TITLE
Text change on Swan Bitcoin.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4295]
- This text should change to “Auto-withdraw wallet” once the registration is done.
![File (65)](https://user-images.githubusercontent.com/62699947/133035523-4f330ebb-d2e6-4260-8d81-1ba582efa919.jpg)

**Comment by antuz123** [comment]
Also change the initial text to "Register and claim $10". This is before registration.

**Comment by cakesoft-swati** [comment]
- ![File (65)](https://user-images.githubusercontent.com/62699947/133035523-4f330ebb-d2e6-4260-8d81-1ba582efa919.jpg)
- The text is not being changed to "auto-withdraw wallet" after registration.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0(351)
