### ISSUE TITLE
Release 2.0 to stores

### ISSUE THREAD

**Issue by cakesoft-shashank** [bithyve/hexa#4307]
- [x] Change bundle identifier
- [x] Create certificates and keystore
- [x] Add new firebase config files
- [x] Add APNs certificate fo firebase
- [x] Store assets
- [x] App text- description(long and short), ASO
- [x] Create an app in appcenter
- [x] Exclusion rules: https://github.com/bithyve/internal-docs/issues/172
- [x] Release 1.0 w/ broadcast notification 
- [x] Production deployment of backends 

Note: don't add any device/ OS version restrictions

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
