### ISSUE TITLE
App is getting stuck on Home button of "Edit Wallet Name".

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4310]
![temp (91)](https://user-images.githubusercontent.com/62699947/133276559-a7e99e59-e8dc-49b2-8bcf-f516cbd80f2d.jpg)
- App is getting stuck on Home button of "Edit Wallet Name".On clicking that home button nothing is happening. Every time I have to kill the app.

**Comment by cakesoft-rohit** [comment]
not able to reproduce for me now

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0(349)
