### ISSUE TITLE
Checking account is showing wrong balance after wallet restore.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4311]
![temp (92)](https://user-images.githubusercontent.com/62699947/133280258-b0bd7735-01a8-492f-9808-8d97ae194f0f.jpg)
- Checking account is showing wrong balance after wallet restore. It is showing correct balance on home page and account screen but some transactions are missing on account screen.

**Comment by antuz123** [comment]
@cakesoft-swati - does it work when you do account sync from settings?

**Comment by cakesoft-shashank** [comment]
@cakesoft-swati not able to reproduce

**Comment by cakesoft-swati** [comment]
- Unable to recreate this issue so closing it for now.
