### ISSUE TITLE
Change text italic and bold as suggested in UX

### ISSUE THREAD

**Issue by cakesoft-rohit** [bithyve/hexa#4312]
In the app some words in text are expected to be bold/italic as per UX

**Comment by summikhan11** [comment]
the text is like that in a lot of places, im sending beta feedback for those but it'll be difficult to post each link here

**Comment by Raheel1258** [comment]
Please forward me the beta feedback here so that I can fix them ASAP

**Comment by summikhan11** [comment]
what is required from me? @Raheel1258 @cakesoft-shashank

**Comment by Raheel1258** [comment]
@summikhan11 , We need feedback from you where we have to change text to italic and bold.

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.Tested on dev app v2.0.75(469)
