### ISSUE TITLE
Changes on "Language".

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4314]
-Selected language was Hindi but none of the items in Hindi.
![nonehindi](https://user-images.githubusercontent.com/62699947/133375676-506e6e97-5ff1-45e3-b407-b3ee9264cb23.jpg)

- Shows the previous language and new language
![prennew lang](https://user-images.githubusercontent.com/62699947/133375805-77493893-198a-4466-b26a-f206e933b303.jpg)

- Need to translate it in selected langauage.
![transaltion](https://user-images.githubusercontent.com/62699947/133376102-798df941-bbfd-4ed2-b74c-74ed4f487049.jpg)

**Comment by cakesoft-swati** [comment]
-Selected language was Hindi but none of the items in Hindi.
![nonehindi](https://user-images.githubusercontent.com/62699947/133375676-506e6e97-5ff1-45e3-b407-b3ee9264cb23.jpg)

- Still this page is not showing in the selected language.

**Comment by cakesoft-shashank** [comment]
Duplicate of #4384

**Comment by cakesoft-swati** [comment]
Duplicate of #4384.So closing this issue.
