### ISSUE TITLE
"Yes,I have scanned" should not be enabled unless the QR is generated.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4319]
- Should not be enabled unless the QR is generated.
![noenable](https://user-images.githubusercontent.com/62699947/133389675-3d02d445-c86f-4074-b305-b374ef3acd2d.jpg)

**Comment by antuz123** [comment]
Also need a message while the QR is being generated. "Generating your Recovery Key. Hold on"

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.01(374)
