### ISSUE TITLE
Notification changes.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4323]
- [x]  when you click on a notification for F&F request accepted, it does not do anything (app was in the background). It should take me to the specific contact and do a full contact sync.
- [x] When the app is not open the notification opens up but when you click ok, it goes no where. 
- [x] Transaction notification must go to accounts: on click of notification it opens details notification then it redirect to account 
- [x] The notification should open on the contacts detail screen and when you press ok, it stays there. The same should happen when the app is in the background. 
- [x] #5863
- [x] Notifications works same when opens from notification tray

**Comment by cakesoft-swati** [comment]
- Unable to see the above notification changes in dev app v2.0.75(471)

**Comment by cakesoft-swati** [comment]
- Transaction notification is not going into the accounts.
- Tested on dev app v2.0.80(486)

**Comment by Deveshshankar** [comment]
1.when you click on a notification for F&F request accepted, it does not do anything (app was in the background). It should take User to the specific contact and do a full contact sync.

2.Transaction notification must go to accounts: User clicks on notification it opens details notification then it redirect to account. One extra step is involved that could be avoided

https://user-images.githubusercontent.com/107177634/180271844-8b72363a-ce12-4717-ab06-c4d4ea3f5970.mp4

**Comment by Deveshshankar** [comment]
To test this item with the issue raised in F&F

**Comment by Deveshshankar** [comment]
done
