### ISSUE TITLE
Text change for PDF.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4339]
![Screenshot_20210915-200307](https://user-images.githubusercontent.com/62699947/133453663-16f34ea4-92eb-4827-94bb-a5aac4a44681.jpg)
- Now the PDF is not password protected so we need to change the text here. 
- ‘The’ Personal Copy not ‘A’

**Comment by antuz123** [comment]
Recovery Key for <wallet name>'s Wallet is attached as a Personal Copy PDF.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0(349)
