### ISSUE TITLE
Google drive login modal permission message.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4352]
- This is still shows that it will share name, email etc. We don't need other message.

**Comment by cakesoft-shashank** [comment]
This is the default message, we are requesting just for email auth. 
Kindly refer to this similar issue: https://github.com/googlesamples/google-services/issues/453

**Comment by ASN-BitHyve** [comment]
@cakesoft-swati to review and either close or assign a dev.

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
