### ISSUE TITLE
Images are disappearing after some time.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4357]
-F&F Images vanish after some time. 

![issue](https://user-images.githubusercontent.com/62699947/133589200-36c9ee7a-fe65-4af9-9ca6-afe2c35e84b6.jpg)

**Comment by cakesoft-rohit** [comment]
not able to reproduce the issue

**Comment by Raheel1258** [comment]
This issue is not reproducing now.

**Comment by GourabSanyal** [comment]
fixed, tested feature/2.0.75
