### ISSUE TITLE
Test upgrade notifications

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4365]
Send notification for 1.0 and 2.0

**Comment by cakesoft-swati** [comment]
- Close: App should not show the notification on relogin.
- Remind me later: App should show the notification on every relogin.
- Notes: Notes should be visible.

**Comment by cakesoft-shivani** [comment]
Only download button changes to Release notes screen 
- Make the donwnload button long and center
- Take out ‘Remind me later’
- Make the text ‘Download Hexa 2.0’
- Link it to the relevant App Store/ PlayStore listing

**Comment by cakesoft-swati** [comment]
- Verified this issue on live app v1.7.0(298)
