### ISSUE TITLE
Existing contact Keeper.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4370]
- [x] Showing unconfirmed contact as an option to make a Keeper.
- [x] Wrong notification language when the request goes
- [x] The request should only be through notification and a QR/ Link screen is not needed. Instead a message that a notification has been sent to the contact and when they accept it, they will become a Keeper
- [x] Notification not received on the other side. It should be an action notification with accept and reject.
- [x] Both send a notification back to the sender depending on the button selected. If declined it should keep the - -- contact a contact and remove them from the Share RK option and any data kept on the channel should be deleted.
- [x] If accepted, And then approval key scan if accepted. The type becomes a Keeper.
Any other scenario in this flow

**Comment by cakesoft-shivani** [comment]
on request acceptance tance of exting contact redirect to contact details to scan approval key

**Comment by cakesoft-shivani** [comment]
Once request send to contact that time keeper type become KEEPER and after one sync it again become CONTACT

**Comment by cakesoft-shivani** [comment]
![Screenshot 2021-10-08 at 11 39 45 AM](https://user-images.githubusercontent.com/50820210/136547357-84ae8d9d-ef2f-459b-ac30-55da28368776.png)
When we select existing contact then all phone book contacts get disappear for 1st time when app reload when we go back and comes to same list then it works well 

When I reject request for being Keeper then type is not changing KEEPER to CONTACT @Parsh need to look into this issue
