### ISSUE TITLE
Stuck after using approval key.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4376]
- Stuck after using approval key for the pdf.
![approvalkeystuck](https://user-images.githubusercontent.com/62699947/133728020-1058841d-bdff-4aea-95a2-a47804f3e845.jpg)

**Comment by cakesoft-shivani** [comment]
Not reproducing on ios neither on android

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0(353)
