### ISSUE TITLE
Contacts last seen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4377]
- Still not syncing contacts last seen in this page.
![stillnosync](https://user-images.githubusercontent.com/62699947/133728158-fa496ee8-42e3-4b31-9754-c5908c860b1f.jpg)

**Comment by cakesoft-shivani** [comment]
Not reproducing

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0(349).Not able to reproduce this issue.
