### ISSUE TITLE
Language updates

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4382]
Make sure that the languages we are going live with are not very incorrect. Though we are using it as beta.

**Comment by antuz123** [comment]
Ok let’s do the main screens 
	wallet initialization screens 
	Home screens (all 4) 
	Account screen
	Loading messages 

For 
	Spanish 
	Hindi 
	German 
(Take out all other languages (?)) 


Do what you both can do by the weekend starting from the above list.

**Comment by antuz123** [comment]
Spanish, German, Hindi, French and Portuguese and may be Russian.  Need to merge them @cakesoft-shashank

**Comment by cakesoft-swati** [comment]
> Make sure that the languages we are going live with are not very incorrect. Though we are using it as beta.

**Comment by antuz123** [comment]
Beta tag fix
Hide other languages 
Add the latest translation

**Comment by cakesoft-shashank** [comment]
@cakesoft-swati please talk to @ASN-BitHyve before closing this
