### ISSUE TITLE
App is crashing on Skip contact.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4387]
- Tested on dev app v2.0(349)
- App is crashing when we do Backup with contact > Skip .
-  Also app crashes when we add contact using skip

**Comment by cakesoft-shivani** [comment]
Same happening on F&F contact skip butto
![Screenshot 2021-09-17 at 4 30 56 PM](https://user-images.githubusercontent.com/50820210/133772173-f45c8b2e-be26-4aeb-a3c4-bfb3734fa784.png)
n

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0(351)
