### ISSUE TITLE
 Google Drive Backup.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4390]
![Screenshot_20210917-153427](https://user-images.githubusercontent.com/62699947/133765717-bae7c00a-c2e7-498a-a7a0-d3b21946b10d.jpg).
- It is showing Level 1 cloud backup is complete and that "Backup on Google" still not confirmed.
- Also when I click on "Backup on Google" nothing is happening.

**Comment by cakesoft-shivani** [comment]
Not reproducing @antuz123 @cakesoft-swati Please check

**Comment by cakesoft-shivani** [comment]
Added Error modal for cloud if auto cloud upload

**Comment by cakesoft-swati** [comment]
- Once again facing the same issue on android device staging app v2.0(349).
- Hard to reproduce this issue.

**Comment by cakesoft-swati** [comment]
Duplicate of #4425
