### ISSUE TITLE
Wallet is not getting restored.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4391]
- Wallet is not getting restored with contact recovery key.
- I did thebackup with contact without approval key.
<img width="375" alt="EA638353-D636-4BAC-8520-C2141FD6D703" src="https://user-images.githubusercontent.com/62699947/133769289-9b5e3f8d-7b9a-49f2-94f8-5899d86ffa9b.png">

**Comment by cakesoft-swati** [comment]
- Still the wallet is not getting restored with contact recovery key.
- Tested on dev app v2.0.0(353)

**Comment by cakesoft-swati** [comment]
- At the time of recovery if I click on back button and again come back to the screen to scan recovery keys then it is not showing me share option which helps to recover wallet.
- Tested on dev app v2.0.0(353)
![Screenshot_20210924-114619](https://user-images.githubusercontent.com/62699947/134641376-ed508915-77a4-43f1-b796-686245c33cea.jpg)

**Comment by cakesoft-shivani** [comment]
If approval not done it shows error while restore

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.01(374)
