### ISSUE TITLE
Reset 2FA

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4404]
- When we go to reset 2FA it says Scan the Regenerate/Exit Key but if scan the 1st QR of PDF then also it works and shows  new QR code.
- It should only scan the Exit key.
- If I enter wrong OTP while sending then nothing is happening and that loader does not go away.
-

**Comment by cakesoft-swati** [comment]
- It is not working properly on dev app v2.0.01(374)
- It is still asking for Scan the Regenerate/Exit Key and when I scan the recovery key from PDF then it is showing "wrong QR scanned " message and nothing is happening after that only the loader is loading continuously.

**Comment by cakesoft-shivani** [comment]
- the approval key is removed from pdf so pdf will not work now for 2fa rsset

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging ap v2.0.5(381)
