### ISSUE TITLE
Font and styling not as per UX

### ISSUE THREAD

**Issue by cakesoft-rohit** [bithyve/hexa#4419]
![checkfont](https://user-images.githubusercontent.com/62699947/136516598-a0f3e2cd-1808-4ce1-90a2-c88a2fea51b4.jpg)

![space](https://user-images.githubusercontent.com/62699947/136522290-d54d3161-dab8-422f-8734-5f81484dc850.jpg)

**Comment by cakesoft-rohit** [comment]
![Image from iOS (1)](https://user-images.githubusercontent.com/74172232/134364293-afa9108c-e5d0-47cd-a114-f0e5d8b795f3.jpg)
![Image from iOS (2)](https://user-images.githubusercontent.com/74172232/134364315-406bbdbc-631b-48a7-b0a7-4664ffb1426d.jpg)
![Image from iOS](https://user-images.githubusercontent.com/74172232/134364318-2b89fe32-8627-4704-a0bf-5aeea56ec93a.jpg)

**Comment by summikhan11** [comment]
![image](https://user-images.githubusercontent.com/85475736/134473311-cad4c266-bceb-45c7-950a-f54e6864dc83.jpeg)

**Comment by summikhan11** [comment]
![image](https://user-images.githubusercontent.com/85475736/134473350-ccb46b3c-d915-4c9b-8627-2c43bbf627c2.jpeg)

**Comment by cakesoft-swati** [comment]
![temp (100)](https://user-images.githubusercontent.com/62699947/136547779-b35e322b-ef05-415e-9f27-7be78a2b0b9c.jpg)
![temp (101)](https://user-images.githubusercontent.com/62699947/136547790-0bfa76c5-e8b1-4b08-9c3d-973550daf0a3.jpg)

**Comment by summikhan11** [comment]
few are not fixed

check 
1. btc font on home page
2. add account fonts
3. "f&f request" under QR

**Comment by GourabSanyal** [comment]
#5680

**Comment by cakesoft-swati** [comment]
- "f&f request" under QR is not yet fixed.check with XD.

**Comment by summikhan11** [comment]
@GourabSanyal 

Scan screen for f&f request 
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/08346ae0-34b5-4e12-8813-ee5a7d75d6e5/

**Comment by GourabSanyal** [comment]
https://github.com/bithyve/hexa/pull/5720

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v 2.0.75(472)
