### ISSUE TITLE
Startup access for store

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4424]
15%

**Comment by antuz123** [comment]
@cakesoft-utkarsh - do you remember what this was?

**Comment by cakesoft-utkarsh** [comment]
I think this could be about APple and Google reducing their fees 30% to 15% on In-App purchases for Small Buisness

Android: https://android-developers.googleblog.com/2021/03/boosting-dev-success.html
iOS: https://developer.apple.com/app-store/small-business-program/

**Comment by cakesoft-shashank** [comment]
This is being followed in keeper
