### ISSUE TITLE
Sync from channel on I have shared button for Secondary device 

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4444]

**Comment by cakesoft-shivani** [comment]
If I press Personal device > "Yes  have shared" it should fetch n scan everything.

**Comment by cakesoft-swati** [comment]
- Verified this issue as discussed with dev.on dev app v2.0.1(373)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.01(374)
