### ISSUE TITLE
Personal device share is not getting confirmed.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4448]
- If I press  "Yes  have shared" button of Personal device  it should fetch ann scan everything.

**Comment by cakesoft-shivani** [comment]
https://github.com/bithyve/hexa/commit/ac676bd2ed859c63e2b05250574f17cc4931ab6e
https://github.com/bithyve/hexa/commit/062f5b666995f7873c817987e84274cba10ac9b8

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0(357)
