### ISSUE TITLE
Modal behavior when the app is in the background.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4452]
- App hangs when a modal is open and we go to background.
- If any modal is open and we keep the app in background and open it back then that modal is disappearing.

**Comment by cakesoft-swati** [comment]
- If any modal is open and we keep the app in background and open it back then that modal is disappearing.Following are some modals:
1.F&F request accept/decline modal.
2.Keeper request accept/decline modal.
3.Notifications.

**Comment by cakesoft-shashank** [comment]
> * If any modal is open and we keep the app in background and open it back then that modal is disappearing.Following are some modals:
>   1.F&F request accept/decline modal.
>   2.Keeper request accept/decline modal.
>   3.Notifications.
> * If we are on any account page and we keep the app in background and open it back then it shows a "Complete Level 2" modal  everytime on any account that we show it for savings account before level 2 completion
>   ![Screenshot_20211101-145238](https://user-images.githubusercontent.com/62699947/139681023-dda47094-f971-413e-b962-0c567cbd851e.jpg)

This is fixed now @cakesoft-swati

**Comment by cakesoft-swati** [comment]
- The following are some of the models that disappear when it is opened and we put the app in the background and open it again:
1.F&F request model accept / reject.
2. Accept / reject the keeper request model.
- Tested on dev app v2.0.75(469)

**Comment by Raheel1258** [comment]
I have tested it in 80, It is working fine on my side 

https://user-images.githubusercontent.com/28229449/167799810-b0772863-ec0a-4d71-a013-bc6695b79f86.mov
