### ISSUE TITLE
Success message after accepting the gift sats.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4455]
- After accepting, it should show a success message.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/f97e58ed-d49d-449b-aa1b-6571288e1dc5/

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(381)
