### ISSUE TITLE
Status of Gift.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4457]
- I can use that gift link multiple time there is no any message or no any restrictions.
<img width="375" alt="8A316DC7-4AC8-450E-8F90-53A1ECFAEB57  (1)" src="https://user-images.githubusercontent.com/62699947/135041669-e3f8d89d-6785-4fb1-b85f-b36d8b9a3ef2.png">

1.Once claimed, the gift should be marked claimed and the private key deleted.
2.Status of a gift can be - created, sent, claimed, expired, retrieved.
3.Created is only a local status, the rest are on the relay.And should be used properly.
4.When expired or claimed or retrieved - the private key should be deleted.

**Comment by antuz123** [comment]
Statuses - screen label - CTAs 

1. Created - Active - Send and Expire 
(Send goes to send flow, expire and put it back in the account) 

2. Sent - Sent - Expire 

3. Claimed - Accpeted

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/b9075c92-c49a-4c1f-adc1-3e0f65307d8e/

**Comment by summikhan11** [comment]
the fonts in the screenshot looks different, please check

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
