### ISSUE TITLE
Showing different currency while creating gift.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4458]
- If this is in sats, why is this showing dollars?
![showingdiffcurr](https://user-images.githubusercontent.com/62699947/135042321-f0dc3019-d351-43c5-acee-70643eab4ec3.jpg)

- **For gifting, the default currency in all screens should be fiat, with an option for them to choose sats if needed. Like the Send screen**

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/e151d4ef-3852-42d9-bd9c-08cc2d5ca1ba/

lets use this switch.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.1(337)
