### ISSUE TITLE
Manage Gifts.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4462]
- This screen should be showing cards and not just rows. Check the UX.
![managecards](https://user-images.githubusercontent.com/62699947/135050979-696e066b-c113-431b-b9d4-3959362071b9.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/a792d286-1d9e-4e0d-afa4-cf806531c7dc/

**Comment by cakesoft-swati** [comment]
- Not as per the UX.
