### ISSUE TITLE
Skip contact.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4464]
- When we do Skip Contact on the receiving side, it should use the wallet name.It is using Awaiting Acceptance. I have already accepted it.
![awaitingstatus](https://user-images.githubusercontent.com/62699947/135051766-a80a87fc-c8e2-40fd-ac35-f2fe19464548.jpg)

**Comment by cakesoft-shivani** [comment]
Not reproducing on dev debug

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.1(373)
