### ISSUE TITLE
Manage Gifts : Need to categorise as per gift statuses.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4480]
- Need categories here as per the statuses defined for gifts.
-  Active - Open Sent & Received, - collapsed Claimed & Expired - collapsed
![activeopen](https://user-images.githubusercontent.com/62699947/135260699-48889999-1203-4070-ab86-088a91199092.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/a792d286-1d9e-4e0d-afa4-cf806531c7dc/

**Comment by summikhan11** [comment]
@antuz123 can you provide CTA's for different statuses.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/b9075c92-c49a-4c1f-adc1-3e0f65307d8e/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.1(373)
