### ISSUE TITLE
The t-sats are appearing in the success message.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4485]
![Screenshot_20210930-123815](https://user-images.githubusercontent.com/62699947/135416259-599e5da9-5604-4be3-b28c-dbeed2936e6b.jpg)
-On staging mainnet, t-Sats appear in the success message that is displayed after sats has been sent successfully.
- Tested on staging app v2.0.0(360)

**Comment by Parsh** [comment]
I've done the changes to appropriately switch between sats and t-sats based on the network type. However there's another err that I can see, the above sub-text is not even getting visible in the current development build.

![Simulator Screen Shot - iPhone 12 Pro - 2021-09-30 at 16 44 25](https://user-images.githubusercontent.com/17980466/135448466-a383a3a4-bede-4d8b-b733-312ba601bbc3.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on live app v1.7.0(298)
