### ISSUE TITLE
Optional Name

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4500]
1. We need a new field 'user name' at the wallet level. This will be initially have the same value as Wallet name. And should also be backed up. 

2. During the gift process, along with the message the user can also provide their name. This will be pre populated with the user name. This user name is used in the message to be sent.   

3. If this is provided again and the value is not used,the user name field will be changed to the new value.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.1(373)
