### ISSUE TITLE
Add screen before 'Gift QR' screen with Note, Name, Greetings

### ISSUE THREAD

**Issue by cakesoft-rohit** [bithyve/hexa#4525]
Name(Editable), Greeting(Fixed Text) and add Note(Editable) should come in a screen before QR generation screen
and remove note form QR screen

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/b0a9fb76-99fa-45cc-ac25-eb9d19235aaa/
