### ISSUE TITLE
Existing contact to keeper contact list issue

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4537]
When we select existing contact then all phone book contacts get disappear for 1st time when app reload when we go back and comes to same list then it works well
![Screenshot 2021-10-08 at 11 39 45 AM](https://user-images.githubusercontent.com/50820210/136558743-84b657fd-0b59-4e1c-9eaf-21169c349910.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(431)
