### ISSUE TITLE
Keeper QR/link: Ramp Up

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#4544]
https://github.com/bithyve/hexa/pull/4542 ramps up the F&F deep link generation by allowing the initTrustedContact worker to do the channel setup in the background w/ Relay. Despite that, the keeper QR/link generation is taking quite a bit of time and we would ideally want to do all the asynchronous setup processes in the background, thereby, showing the QR/link almost instantaneously.

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
