### ISSUE TITLE
UI changes on Manage Gifts screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4546]
- Need a Know More here with the help screen that is in the UX. It should open up the first time automatically. 
- Move the Create New button down as a floating button bottom center. And instead of top right, create new put ‘Know More’. 
![needknowmore](https://user-images.githubusercontent.com/62699947/136794336-5ef87770-537b-4dc1-b53a-7b67a7bd1c15.jpg)

![temp (103)](https://user-images.githubusercontent.com/62699947/136905094-b56acc76-86ba-471b-942a-e377df25334f.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/3f878511-0040-4b0b-83fd-eb86c2af6557/
