### ISSUE TITLE
Google Drive backup

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4555]
![Screenshot_20211012-170952](https://user-images.githubusercontent.com/62699947/137081845-896e0a15-e7e8-4c88-9061-0af426c644b8.jpg)
![Screenshot_20211012-171015](https://user-images.githubusercontent.com/62699947/137081880-e0491c29-c654-447e-bde8-b3d1ae3e5c6b.jpg)
- Everytime when cloud share got expire and if we go to confirm it again then it says GoogleDrive backup failed and home page it shows that "Level 1 Automated Cloud BAckup is complete".
- First time after wallet initialsation it shows  "Level 1 Automated Cloud BAckup is complete" on home page. but when we go to the history page it is showing "GoogleDrive backup failed".
- Even after wallet restore when I go to confirm googledrive backup then it is showing that error modal but on home page it is showing  "Level 1 Automated Cloud BAckup is complete".
- It is only happening on Adroid device.Tested on One plus 9R dev app v2.0.1(372)

**Comment by cakesoft-shivani** [comment]
_'Everytime when cloud share got expire and if we go to confirm it again then it says GoogleDrive backup failed and home page it shows that "Level 1 Automated Cloud BAckup is complete'_
Not reproducing

**Comment by cakesoft-swati** [comment]
- Same issue is happening again on android device.
- Tested on dev app v2.0.69(426)
- It shows "Level 1 Automated Cloud BAckup is complete" on home page. but when we go to the history page it is showing "GoogleDrive backup failed".
![Screenshot_20220127-191636](https://user-images.githubusercontent.com/62699947/151374006-2d719735-3fa5-410c-a7f8-77b7d897399d.jpg)
![Screenshot_20220127-191648](https://user-images.githubusercontent.com/62699947/151374009-eada3897-e4ef-4cc4-8eef-19642d24eb89.jpg)

**Comment by Parsh** [comment]
The Google Drive backup messaging seems to be working fine on my android. I've tried quite a few times. 
@cakesoft-swati Can you please take a look at it again and come back with more details(exact steps taken)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(431)
- Unable to recreate this issue.
