### ISSUE TITLE
Level 2> Share Recovery Key 1 is not getting confirmed immediately.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4558]
- Level 2> Share Recovery Key 1 is not getting confirmed immediately.Every time I have to pull it to refresh 2/3 times.Sometimes when I refresh the F&F list that recovery key gets confirmed.

**Comment by Parsh** [comment]
> There is other is if I kill app before channel creation and after 2fa call done then it getting stuck because of error [Error: 2FA is already enabled for this wallet]

This has been resolved.

**Comment by Parsh** [comment]
> @Parsh Please look why secondary data is not updating to channel that is why in manage backup keeper is not getting confirmed

I've not encountered this issue. The secondary data gets updated perfectly on my end.
