### ISSUE TITLE
Contact Image should be local copy or base64 data 

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4561]

**Comment by Raheel1258** [comment]
@Parsh  Halting it for now as server-side work is yet to be completed on this one as instructed by @cakesoft-shivani

**Comment by cakesoft-swati** [comment]
-I'm unable to recreate this issue. I will check this issue in 70.

**Comment by GourabSanyal** [comment]
fixed, tested feature/2.0.75
