### ISSUE TITLE
Building Zeus

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#4577]
Build Zeus locally(iOS), connect it with [Polar](https://lightningpolar.com/), and explore.

**Comment by Parsh** [comment]
Encountered the following error after cloning the repo, doing npm i and pod install:

<img width="1440" alt="Screenshot 2021-10-13 at 6 00 20 PM (1)" src="https://user-images.githubusercontent.com/17980466/137885779-2f4d8660-a469-42f7-a858-da813049bbda.png">

However, the above issue got resolved by the following:

Replacing: `pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"` with `pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"
` in Podfile

Followed by;
- pod deintegrate(removed podlock)
- pod install

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev
