### ISSUE TITLE
Gift flow changes

### ISSUE THREAD

**Issue by cakesoft-rohit** [bithyve/hexa#4587]
User should provide encryption key to accept gift model only
![Simulator Screen Shot - iPhone 11 - 2021-10-25 at 07 05 18](https://user-images.githubusercontent.com/74172232/138622117-6e1a718e-7760-4204-84ed-7ba3f685d79a.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(377)
