### ISSUE TITLE
Gifting - Issues list by ASN.

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4605]
- [x] When the section below is blank, say, "...would be visible below". Once there is data in the relevant section, then let it say what it currently says that is, "... are visible below". 
- [x] create new gift button not stable on click of available sent received expired buttons 
- [x] I think there is too much shadow here. Especially around the button. Please check how Sumaiah has done it.
- [x] "Gifts that you create, ready to be sent, would be visible below"
- [x] Get "them" back and not "it".
- [x] Too much shadow here also. Please check UX.
- [x] 1) "Enter name" text is not properly aligned. Notice how the cursor extends below the letter E. Please check all other alignments of that text, like left alignment, etc. 
- [x] 2) That white box need not be so far away from the word, "from".
- [x] 3) I can see lorem ipsum in the theme section. I have given text in the spec link. Please use that.
- [x] Remove the word "at"
- [x] Text does not seem middle aligned with white box.
- [x]  It should be, "Available to spend: <amount of sats>" That ":" symbol is required
- [x] It should say, "Sats would be deducted from". Not Bitcoin.
- [x] Received spelling. "... received a gift..."
- [x] Remove the line, who are we delighting today.
- [x] G capital

![Screenshot_20211028-111933_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/139195100-8571b7e8-4dea-4a19-a5ff-98f2df5d3a60.jpg)

**Comment by ASN-BitHyve** [comment]
https://user-images.githubusercontent.com/68264080/139657833-08bd039e-67b2-4e26-bbe6-fbb14f8547f1.mp4

**Comment by ASN-BitHyve** [comment]
There should be a filter that allows people to filter their gifts based on the date/month/year it was sent on (basically based on earliest to latest)

![Screenshot_20211101-161835_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/139660331-0aee47c5-0bdc-4c76-ad97-7288fd086e20.jpg)

**Comment by ASN-BitHyve** [comment]
After accepting gift. On clicking "View Account", the app is crashing.

**Comment by ASN-BitHyve** [comment]
When a user clicks on a gift link they themselves created, the app should be able to identify it and let the user know that, "You have clicked on a gift link that was created in this wallet."

**Comment by GourabSanyal** [comment]
fixed, tested feature/2.0.75
