### ISSUE TITLE
Delete created gifts

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4612]
- [ ] Add back to account in available 

I should be able to delete the gift on long pressing on it. When a user long presses on the gift, a modal opens saying:

Headline: Delete Gift?
Subheading: If you delete the gift, sats would revert to the account you created the gift from. 

Buttons: Delete | Cancel

![Screenshot_20211029-132412_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/139397548-501ddddc-d55c-434f-a267-0b467c580e00.jpg)

**Comment by summikhan11** [comment]
isn't "expire gift card" the same as deleting it? @cakesoft-shivani
