### ISSUE TITLE
Gift removed from available section 

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4614]
- [x] Change status on click of share link or QR
Change CTA of sent gift
- [x] if not accepted give option to resend and reclaim
- [x]  if accepted not a single CTA will be there

        

https://user-images.githubusercontent.com/68264080/139657833-08bd039e-67b2-4e26-bbe6-fbb14f8547f1.mp4

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app v2.0.5(382)
