### ISSUE TITLE
Hide Diwali and Halloween as themes in the gifts feature.

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4634]
- Remove Diwali and Halloween from the gift themes and add Thanksgiving

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/914419d8-218d-42c8-8d69-f1ab2dd6c7a2/

scroll to find gift card design too

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(377)

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(379)
