### ISSUE TITLE
Changes the button size if enable disable gift create button 

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4638]
![Screenshot 2021-11-02 at 4 47 48 PM](https://user-images.githubusercontent.com/50820210/139836963-0186f7ab-888c-43e1-af9a-292a8c9ef3de.png)
![Screenshot 2021-11-02 at 4 47 42 PM](https://user-images.githubusercontent.com/50820210/139836976-8668c52c-1a90-4051-9f3b-485af06bc49d.png)

**Comment by cakesoft-swati** [comment]
-Verified this issue on staging app v2.0.5(382)
