### ISSUE TITLE
Add account selection modal

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4639]
- [ ] Add account selection on both places

![Screenshot_20211029-141650_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/139405305-a8e80593-5fc3-4cce-acb8-db189413faf7.jpg)

![Screenshot_20211029-131748_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/139396422-e756a64c-381c-493c-9ce9-97fbbf820819.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on live app v2.0.5(379)
