### ISSUE TITLE
Donation account-Loader and Web view issues.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4648]
- Loader is loding continously when we refresh the page for latest transaction.It doesn't stop even after killing the app and coming back.It is happening on android device.
- Also when we go to web view it is not showing the Total funds raised and Total amount remaining.It is always showing 0 sats.
- Tested on dev app v2.0.01(374)
![Screenshot_20211103-182312](https://user-images.githubusercontent.com/62699947/140063546-079325d6-6ce6-40c2-8254-c2f92f1575c1.jpg)
![Screenshot_20211103-182332](https://user-images.githubusercontent.com/62699947/140063597-d05be059-6394-4855-b278-e859d8e4cff0.jpg)

**Comment by cakesoft-utkarsh** [comment]
Donation Web is now resolved.

**Comment by cakesoft-swati** [comment]
- Verified this issue on live app v2.0.2(376)
