### ISSUE TITLE
2.0 link(F&F/Keeper) is opening in 1.0 app.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4655]
- If the user is having both the app 1.0 & 2.0 then link is opening in 1.0.

**Comment by cakesoft-utkarsh** [comment]
This needs to be verified with appropriate links on Hexa 2.0. 
LInks I used were of the Dev app.

**Comment by cakesoft-utkarsh** [comment]
Deeplink generated from 2.0 App is: https://hexawallet.page.link/AGSr
Which is redirected to: https://hexawallet.io/app/CONTACT/Jj/DbuDbQBAKml5vF32EoMtRMy6-/DEFAULT-/v2.0.1

If you open the original URL it does open in Hexa 2.0
Not sure of the Firebase Dynamic Link setup and how it works.
@cakesoft-shashank @antuz123

**Comment by cakesoft-utkarsh** [comment]
I have updated the apple-app-site-association on hexawallet.io
Now the links will open with hexa2.0. Marking this fixed.

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
