### ISSUE TITLE
App is crashing on 'Add New' of F&F.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4656]
- When we go to Add new contact from F&F,we select one contact then when we click on "Confirm & Proceed" or we click on Skip then the app crashes.
- Happening only on ios app v2.0.1(375)

https://user-images.githubusercontent.com/62699947/140784378-24bafdc5-09d1-4792-8707-1331e15f7b9c.MOV

**Comment by Parsh** [comment]
I wasn't able to replicate that, contacts were getting added seamlessly.
![Simulator Screen Shot - iPhone 12 Pro - 2021-11-09 at 17 05 40](https://user-images.githubusercontent.com/17980466/140917176-61672956-8c7d-40cb-98e0-251bf7ee1b1b.png)

@cakesoft-swati Can you please try and replicate that? Also, please update this issue with the steps once you successfully replicate it.

**Comment by antuz123** [comment]
@cakesoft-swati - this is happening when updated from 2.0 to 2.0.1. 

Please check accordingly

**Comment by Parsh** [comment]
@cakesoft-swati Any updates on that?

**Comment by ASN-BitHyve** [comment]
@cakesoft-swati to test and do the needful

**Comment by cakesoft-swati** [comment]
- Unable to reproduce this issue
