### ISSUE TITLE
Getting Network error on "Awaiting accepance" of F&F.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4657]
- When a contact is added by using skip contact and until that contact request is accepted, we show "Awaiting acceptance".
- When we click on this "Awaiting acceptance" of F&F then getting 'network error' message.
![temp (112)](https://user-images.githubusercontent.com/62699947/140725906-cc1c64e0-9c5e-464e-b8c9-172d5cde9ba5.jpg)

**Comment by Parsh** [comment]
The toast is triggered by the highlighted BHR action. 

<img width="1440" alt="Screenshot 2021-11-09 at 5 17 58 PM" src="https://user-images.githubusercontent.com/17980466/140918936-10f6a426-7d91-4345-89c6-99b2d32b2bcb.png">

@cakesoft-shivani Can you please take a look at why the Network Err toast is popping up?

**Comment by cakesoft-shivani** [comment]
On every contact 
If already present secondary updated

**Comment by cakesoft-swati** [comment]
- Verified this issue on Hexa app v2.0.2(376)
