### ISSUE TITLE
Swan integration Announcement

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4672]
Internal Doc issue #180

**Comment by ASN-BitHyve** [comment]
An image with Hexa and Swan logo with our respective tag lines underneath (Hexa: Bitcoin is for everyone | Swan: Own Your Future) and a general Bitcoin themed background. This is for the Swan integration announcement that would be going out sometime this week. 

@summikhan11

**Comment by summikhan11** [comment]
![Twitter Announcement](https://user-images.githubusercontent.com/85475736/142470884-0d7b332b-7b73-40f4-bf5b-16397b769411.png)


let me know if you wanna change the content

**Comment by antuz123** [comment]
1. You don't really buy bitcoin from your Hexa wallet 
2. Is the Swan line correct? "Own your future"? 
3. The name of the company is Swan Bitcoin, not Swan. 

@ASN-BitHyve

**Comment by ASN-BitHyve** [comment]
First off, the b should be small letters. Have told Summi. 

Point1: It should be "from within" or "through" Hexa Wallet. But using those words makes the sentence longer. I can live with "from". Its a matter of a user logging in once to understand that they'll be purchasing sats from Swan.

Point 2: "Own Your Future" is displayed prominently on their home screen. Have assumed its their tag line.

Point 3: Have seen them use both. For example in the co-branded asset, they've simply used Swan.

@antuz123

**Comment by ASN-BitHyve** [comment]
@summikhan11 suggest using the Hexa 2.0 logo: https://xd.adobe.com/view/ec019ed7-5d7f-4e9f-a73d-ba75f254b45c-b952/screen/3305ec0d-0854-40b5-9943-9cd5934a8184/?x_product=cc-slack%2F1.5.1

**Comment by summikhan11** [comment]
![Twitter Announcement](https://user-images.githubusercontent.com/85475736/144186476-367cca04-47ca-4130-bf66-36ce79ed69bb.png)
@ASN-BitHyve

**Comment by ASN-BitHyve** [comment]
@antuz123 this is good to go for me.

**Comment by ASN-BitHyve** [comment]
@summikhan11 please share the announcement image in appropriate sizes to put on desktop website and mobile website.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/ff175839-dd75-4d46-8208-5fe20355d683-aa44/screen/e71751d5-0e6f-407c-b4a5-75bdc5b4c3d5/
scroll to find mobile version too
