### ISSUE TITLE
Enable camera by default when scanning QR codes

### ISSUE THREAD

**Issue by darbsllim** [bithyve/hexa#4678]
People are confused by the QR scan screen.

[Uploading 141698958...]

It's not intuitive to have to tap the image to enable scanning.

We should either enable the camera by default, or replace the image with a call to action like "tap to scan" rather than the current image.

**Comment by cakesoft-swati** [comment]
- I go to Test Account to send test sats. Click on Send > Click on the QR image, the screen goes blank. I have to come out and go back in, this second time clicking on the QR image starts the camera.
- Also when we go to Confirm the personal copy when we click on confirm it asks for camera permission and when we allow it the screen came out and I came back to the confirm screen and second time clicking on the confirm starts the camera.
- Sometimes even after scanning the QR, the camera remains on and there is a modal of accept/reject on it.

**Comment by Raheel1258** [comment]
https://user-images.githubusercontent.com/28229449/146383232-e7d0cada-7c23-41f2-a15c-bf53bfc50853.mp4

@cakesoft-swati working fine as per described in build 403
