### ISSUE TITLE
Content Issues - Numbers & Special Characters

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#4680]
Lets maintain if we want to display what the entry "must contain" or "must not"

PFA

![issue example 1](https://user-images.githubusercontent.com/85475736/141717533-add7891f-82fc-4170-8f28-64cf6ff8c53c.png)
![issue example 2](https://user-images.githubusercontent.com/85475736/141717541-7215b560-52c2-4b5d-8de6-98d2960291af.png)

**Comment by summikhan11** [comment]
@ASN-BitHyve need your input here

**Comment by ASN-BitHyve** [comment]
@summikhan11 I think it is ok the way it is right now. The messages are very clear. 

In the first image, if I say "Only alphabets allowed" and the user tries to name their wallet as " Abhilash Nair" the space between Abhilash and Nair is also a special character (leave apart the more obvious ones like @#$%,etc) which they might only realize after a try or two which is frustrating.

In the second image, it makes no sense to say "Answer must not contain Upper case letters and special characters".

Thus I'm ok retaining the text the way it is.
