### ISSUE TITLE
Appropriate Hexa logo should be visible.

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4682]
@cakesoft-swati please send www.hexawallet.io website link on as many places you can think of:

1. Twitter DM
2. Twitter comment 
3. FB DM
4. FB comment
5. Linkedin DM
6. Linkedin comment
7. Instagram DM
8. Slack DM
9. Youtube comment
10. Whatsapp
11. Telegram 

Please do this using both Android and iPhone. Hexa logo should be visible. Not the wordpress logo we see in Brad's screen shot.

@cakesoft-shashank to confirm.  

![Image from Brad](https://user-images.githubusercontent.com/68264080/141790081-1a59b9ae-67f1-46c2-a03f-29a2a96ab676.jpg)

**Comment by ASN-BitHyve** [comment]
@akshaytikle please take a look.

**Comment by cakesoft-shashank** [comment]
This is fix a few days back, @cakesoft-swati please test

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
