### ISSUE TITLE
Ui Issues - Home Screen

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#4683]
PFA
![Errors 1 – Home Screens](https://user-images.githubusercontent.com/85475736/141811474-2d31551e-d9c7-4d0a-ac2e-0dd1d32bd5ad.png)
,

**Comment by just1and0** [comment]
@summikhan11 @antuz123 is there a figma file for the designs I can look at? so I get the correct dimensions?

**Comment by summikhan11** [comment]
we use xd, I'll attach a link here
https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/screen/0e3ab21b-d16c-4387-a762-2251d4675ddf/

**Comment by just1and0** [comment]
thanks

**Comment by summikhan11** [comment]
I don't see this fixed in dev app 2.0.68 (418)

**Comment by summikhan11** [comment]
![IMG_2735](https://user-images.githubusercontent.com/85475736/149929405-dee00e7c-b6a1-45f8-81ad-4b975d108968.PNG)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(469)
