### ISSUE TITLE
Ui Issues - Login Screen

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#4684]
PFA,
![Errors 2 – Login](https://user-images.githubusercontent.com/85475736/141811948-2c59781a-389a-4573-a1eb-3c305da96254.png)

**Comment by summikhan11** [comment]
![IMG_2733](https://user-images.githubusercontent.com/85475736/149929332-ac307940-8cf8-47d2-9df3-8011225d1454.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(469)
