### ISSUE TITLE
Ui Issues - Error Screen

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#4685]
![Errors 3 – Error Screen](https://user-images.githubusercontent.com/85475736/141813018-54717cd1-7fba-4f79-a09e-8a15a348dd9d.png)

**Comment by just1and0** [comment]
hey @summikhan11 can I get the link for this, or better still, could you add my email to the design so I can go through them myself? it's ayoshokz@gmail.com

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/577ebacd-80e0-449f-a332-a73f2908307c/

we use adobe xd its very similar to sigma, I'll walk you through it on call @just1and0

**Comment by Raheel1258** [comment]
![simulator_screenshot_F15831C1-F93B-4C72-A5EF-8CCB5804BB58](https://user-images.githubusercontent.com/28229449/147641177-d5c3db07-089a-4a37-99bc-f8c41912b7dd.png)

**Comment by summikhan11** [comment]
can you recheck, I see the problems noted above not resolved @Raheel1258 @cakesoft-swati
