### ISSUE TITLE
PGP fingerprint/ public key on FAQ

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4686]
Have removed it from the Twitter bio so need to add it to the FAQ section

Shashank to provide it for hexa@bithyve.com and Abhilash to update the FAQ

**Comment by cakesoft-shashank** [comment]
Hexa's PGP key 389F 4CAD A078 5AC0 E28A 0C18 1BEB DE26 1DC3 CF62 @ASN-BitHyve

**Comment by ASN-BitHyve** [comment]
FAQ updated.
