### ISSUE TITLE
API for Add contacts while Send and Receive

### ISSUE THREAD

**Issue by cakesoft-nikhita** [bithyve/hexa#469]
1) From receiver side We need Sagas/API for QR changes from BTC address to an AES key (?) Also API for Get an address is stored for the Sender on the relay against that AES key

2) From sender side need API Request for fetching the bitcoin address from relay and then the Send process continues with the pre-filled address

**Comment by Parsh** [comment]
Saga available for communicating the requisites over ECDH channels
