### ISSUE TITLE
Contact Keeper is not getting confirmed.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4692]
![File (78)](https://user-images.githubusercontent.com/62699947/141929606-39193fb9-ab49-4b83-91d9-b5eeb10aa812.jpg)
- This did not get confirmed as soon as it was accepted. It showed on F&F but no green here even on refresh.Not even on login again.

**Comment by cakesoft-shivani** [comment]
- [ ] Check why QR is not opening after request acceptance
- [ ] Toast is not clear what the message is after accepting request
- [ ] Add message to approve from keeper side

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.7(398)
