### ISSUE TITLE
Level 2: First keeper> Personal Device- Change Keeper flow

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4694]
![Screenshot_20211116-130508](https://user-images.githubusercontent.com/62699947/141941198-4b0e08b5-1a81-4979-ae59-271ffbc42cff.jpg)
1.
- After level 2 is completed, I see 2 buttons 'confirm' and 'change' on the first share (personal device) of level 2
- when I clicked the 'Change' button it showed me 2 options one is "Backup with contact" and another one is "Backup on a device".
- I have selected "Backup to device" but it is not showing the QR code only the loader is loading.

2.
**- I Created the Recovery key once but didn't share.Then it was showing the option to "Reshare" and "Change".When I clicked either of them it was not creating the QR(Recovery key).When I closed the modal suddenly it gave me "Share Now" option and when  I clicked on that,nothing was happening.**

**Comment by cakesoft-shivani** [comment]
https://github.com/bithyve/hexa/issues/4884 this should be done after 4694

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(431)
