### ISSUE TITLE
 UI Issues - Wallet initialization screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4695]
- keyboard is hiding the CTA. please align it properly.
![hidingcta](https://user-images.githubusercontent.com/62699947/141930006-5442fd03-ccaf-40bf-adab-1a53fb5f3296.jpg)

- align the CTA and the pagination on the right, look at the VD for reference.
![temp (117)](https://user-images.githubusercontent.com/62699947/141956804-a24975a2-a95b-4d29-bc35-16d68d7d98c7.jpg)

- CTA should be visible on this screen. refer to VD.
![Screenshot_20211116-144634](https://user-images.githubusercontent.com/62699947/141957232-9c0cceb9-9ffe-42b3-b3c2-10d3a00599b5.jpg)

**Comment by cakesoft-swati** [comment]
- CTA should be visible on this screen. refer to VD.
![Screenshot_20211116-144634](https://user-images.githubusercontent.com/62699947/141957232-9c0cceb9-9ffe-42b3-b3c2-10d3a00599b5.jpg)

**Comment by cakesoft-swati** [comment]
- @summikhan11 Can you put Xd link here?

**Comment by Raheel1258** [comment]
@summikhan11 Please provide XD

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/

all screens are here

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(431)
