### ISSUE TITLE
UI issues on various screens.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4696]
- Add new is light blue please follow the design specified.
![Screenshot_20211116-145110](https://user-images.githubusercontent.com/62699947/141957922-4cfa8551-8dde-47ee-9b00-e7ce2f689796.jpg)

- check the placement of the illustration.
![temp (118)](https://user-images.githubusercontent.com/62699947/141958256-07957faa-11a5-47b7-9e99-5fecd2c29977.jpg)

- check the shadow of the CTA the image seems distorted
![temp (119)](https://user-images.githubusercontent.com/62699947/141958578-c76a849a-9a8a-4ba5-9854-48d499da4b79.jpg)

- content is incorrect. the user is selecting contacts from their phone to add to F&F. content and heading should reflect that
![Screenshot_20211116-145737](https://user-images.githubusercontent.com/62699947/141958996-8ebe1be4-a69f-4dbb-b0b2-8796797b6e2c.jpg)

**Comment by ASN-BitHyve** [comment]
@ASN-BitHyve to review content of last image.

**Comment by GourabSanyal** [comment]
1. Light blue: fixed
2. Distorted image: fixed
3. Illustration Placement: fixed
4. Addressbook illustration: fixed
5. Addressbook contact content: fixed
