### ISSUE TITLE
App getting stuck while adding contact

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4700]
In 2.0 live app I was able to add contacts. I upgraded the live app to 2.0.2. Now when I'm trying to add contact the app is getting stuck.https://user-images.githubusercontent.com/68264080/142012011-23841bcc-d0a9-43ae-833d-417d5b3efec9.mp4

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(282)
