### ISSUE TITLE
Hexa 1.0 not restoring

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4702]
User unable to restore Hexa 1.0. The app is able to reach his cloud it seems but is unable to restore the wallet. The image shows where the app is getting stuck.

![photo4945072311090915694](https://user-images.githubusercontent.com/68264080/142133225-1e3f80c1-bb6a-43e3-be1e-3f5353dbc097.jpg)

Feedback from: Pinocchio
Feedback on: Telegram DM

**Comment by ASN-BitHyve** [comment]
@cakesoft-swati can you test if this is working as expected please?

**Comment by cakesoft-swati** [comment]
- Verified this issue on live app v1.7.3(301).I'm able to restore Hexa 1.0

**Comment by ASN-BitHyve** [comment]
We know for a fact that Restore works in Hexa 1.0. The user is unable to restore the particular instance of Hexa 1.0 that he had money in. Its a unique issue. Not necessarily a bug in the release.

**Comment by cakesoft-shashank** [comment]
Closed after discussion with @ASN-BitHyve
