### ISSUE TITLE
Sending From Swan

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#4703]
- The send functionality on Swan isn't working.
- The incoming transaction got confirmed but not able to send from it.
- Nothing happens after you press the Confirm and Send .

**Comment by antuz123** [comment]
@cakesoft-swati - this is fixed, only test it. I was checking on the live app which does not have the fix.

**Comment by cakesoft-swati** [comment]
- Tested on staging app v2.0.5(378).I was able to send from swan.
