### ISSUE TITLE
Forgot passcode option required

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4705]
![photo4945313928771119590](https://user-images.githubusercontent.com/68264080/142134351-daf59ab7-8c6a-44a9-8d97-93dbbe740b38.jpg)

**Comment by summikhan11** [comment]
how did i miss that 😨

**Comment by antuz123** [comment]
@ASN-BitHyve @summikhan11 

There is no technical solution to this yet. 

Moving it to 2.2
