### ISSUE TITLE
The app is crashing on accounts.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4707]
- Tested on dev app v2.0.5(376).App is crashing on any account of Home page.

**Comment by cakesoft-shivani** [comment]
![Screenshot 2021-11-17 at 4 45 24 PM](https://user-images.githubusercontent.com/50820210/142190315-b27b2413-7ca3-4f19-ad11-e99ea35fc5b8.png)
@Parsh

**Comment by Parsh** [comment]
The app was crashing as fee wasn't available(for testnet) due to [testnet-wrapper crash](https://github.com/bithyve/hexa/issues/4688). However, it won't crash anymore tho the accounts operating over testnet won't function till testnet wrapper is up and running.

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(377)
