### ISSUE TITLE
Text message image for Hexa 1.0 and release the patch 

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4713]
Require an image that says  ‘New Users Please do NOT download. Please search Hexa Wallet 2.0'

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/ec019ed7-5d7f-4e9f-a73d-ba75f254b45c-b952/

**Comment by ASN-BitHyve** [comment]
@cakesoft-utkarsh / @cakesoft-shashank please find the image above. It needs to be updated in both app stores as the first image in Hexa 1.0

**Comment by ASN-BitHyve** [comment]
Need other resolutions as well @summikhan11 

"Single resolution wont work for Android, iOS 5.5" and iOS 6.5" comment from @cakesoft-utkarsh

**Comment by summikhan11** [comment]
both are there. please scroll to find

**Comment by cakesoft-utkarsh** [comment]
Single resolution won't work for Android, iOS 5.5" and iOS 6.5" (edited) 

Image resolutions
Android  :  Its Uploaded already should be live once update is processed.
iOS 5.5" : 1242 x 2206 ( I have cropped 6.5" image )
iOS 6.5" : 1242 x 2688 ( Is available on XD link)

**Comment by antuz123** [comment]
Text should be: 

For New Users: 

Do not download. This release is only for existing users to upgrade. 

Download our new app. Search for "Hexa 2.0"

**Comment by cakesoft-shashank** [comment]
I have updated image on playstore

**Comment by antuz123** [comment]
Please do a release for 1.0 patch

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/ec019ed7-5d7f-4e9f-a73d-ba75f254b45c-b952/
text updated

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
