### ISSUE TITLE
Ability to name Personal Device

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4715]
User should be able to name the Personal Device in the flow when adding a personal device 

They should also be able to associate a contact if they want instead. So the default will be name entry but with an option to associate a contact instead 

They should also be able to change the name later if they want from the details screen. Like with F&F

**Comment by Parsh** [comment]
We'll require UI for naming the PD.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(431)
