### ISSUE TITLE
Ui Issues - Associate/Add contact from address book

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#4716]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/d08b1f1c-bdcc-4fa7-b7e6-f388848fb1a0/

Pls look at the next 3 screens

**Comment by summikhan11** [comment]
![1](https://user-images.githubusercontent.com/85475736/144028685-0151b654-0e89-4142-a8db-08ee71d8ee5a.png)
![2](https://user-images.githubusercontent.com/85475736/144028703-6a014676-e420-461f-937c-844a8c9df8f0.png)
![3](https://user-images.githubusercontent.com/85475736/144028709-8333ff90-f8a7-427b-a403-295773a497fb.png)
![4](https://user-images.githubusercontent.com/85475736/144028719-b101b0b8-e29e-4b92-8a9a-6590546b80e3.png)

![5](https://user-images.githubusercontent.com/85475736/144028726-d2d73d5e-5509-4ef0-ad81-e489cae58d47.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue by Gourab in dev app v2.0.75(455)
