### ISSUE TITLE
Ui Issues - CTA and Keyboard

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#4718]
When the user clicks on the text field, the CTA should move up with the keyboard, not hide behind it
![IMG_1002](https://user-images.githubusercontent.com/85475736/142330489-57a59703-2432-418a-beb8-497dec1140bd.PNG)
![IMG_1003](https://user-images.githubusercontent.com/85475736/142330601-87b8a18d-97e5-4fff-a44a-63efb91f00f3.PNG)

Reference
https://xd.adobe.com/view/902817ab-b10b-4f5e-8991-1f2142fd4a84-c57b/screen/4424735c-0fc6-4da2-9df5-75c60147ec59/

**Comment by Raheel1258** [comment]
It is fixed on Android but still pending on ios.

**Comment by Raheel1258** [comment]
@cakesoft-swati  mentioned that this step is skipped from 2.0.5

**Comment by cakesoft-swati** [comment]
- Verfied this issue on dev app v2.0.66(404)
