### ISSUE TITLE
Ui Issues - Add Account Alignment Issues

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#4719]
PFA,
![Errors 4 – Add Account](https://user-images.githubusercontent.com/85475736/142337021-390265cb-5e85-4c2f-a5b8-5c889d24a88e.png)

**Comment by summikhan11** [comment]
![IMG_8D1F7DA94AA0-1](https://user-images.githubusercontent.com/85475736/147518232-a5203549-83a7-494e-9374-6603203f9e0d.jpeg)
doesn't seem resolved - staging app 2.0.67 (409)

**Comment by summikhan11** [comment]
![IMG_2737](https://user-images.githubusercontent.com/85475736/149929248-2c0d89a0-4c9b-4949-a773-403e56aaa1c0.PNG)
latest dev app

**Comment by cakesoft-swati** [comment]
- Verified by Gourab in dev app v2.0.75(455)
