### ISSUE TITLE
Sending… Sent successfully

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4726]
From Brad 
On TG 

another UX issue ... after you hit send, the message should pop up immediately confirming that the transaction is sending.

There's a 5 second period after you click send until the "sent successfully" message pops up.

It should pop up the window right away and say "sending..." then switch to "sent successfully" 

it's a confusing UX for new users, and even myself sometimes I'm clicking the button again thinking the send didn't work.

**Comment by Raheel1258** [comment]
@antuz123, what should be the sending message in the popup?

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(455)
