### ISSUE TITLE
Difficult to find the Add Contact link 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4727]
From Brad 
On TG

**Comment by antuz123** [comment]
<img width="292" alt="Screenshot 2021-11-18 at 21 50 16" src="https://user-images.githubusercontent.com/43998049/142454968-000938b7-2254-42c4-aaea-b0e789f11a83.png">

**Comment by ASN-BitHyve** [comment]
@mide66 to review.

**Comment by mide66** [comment]
@ASN-BitHyve About this screen. I'll host a mini usability study to see how it can be improved.
