### ISSUE TITLE
Sweep funds flow

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4728]
- Sweep funds flow is not correct, it goes back to the same screen. Should go to the send screen.
- After some time the screen goes blank when it comes back to the same screen.

**Comment by cakesoft-swati** [comment]
- After scanning the approval key it goes back to the same screen and not the send screen.
- Tested on Dev App v2.0.68 (415)

https://user-images.githubusercontent.com/62699947/148954957-70f85d07-bd6d-403c-a26d-77e8a05a6a33.mp4

**Comment by cakesoft-swati** [comment]
- Sweep fund flow does not work when we try to sweep funds from Savings Account> Settings.
- Tested on dev app v2.0.68(417)
