### ISSUE TITLE
 The balance is being set to zero.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4731]
![File (79)](https://user-images.githubusercontent.com/62699947/142570393-b6bdfa79-cdb6-4b04-aff9-441663237559.jpg)

**Comment by cakesoft-swati** [comment]
- Unable to replicate this issue.Verified on staging app v2.0.5(382)

**Comment by ASN-BitHyve** [comment]
Have requested Brad to confirm if the issue still persists.
