### ISSUE TITLE
User Flow Issue - Donation Account Settings & Webpage

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#4733]
“Donation Webpage” is a CTA to open the webpage

Settings will open from the gear icon on top

Please follow the flow of screens in settings from the prototype

https://xd.adobe.com/view/319a403f-183f-4eb6-bdbe-9cd9dc9c4450-64c9/

**Comment by Raheel1258** [comment]
@cakesoft-swati  I do not have access to the code of the website. This ticket is not relevant to the app.
