### ISSUE TITLE
Ui Issue - Status Bar

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#4734]
Please check "Status bar" colors. on pop-up screens it should be white, everywhere else is blac
![IMG_0782](https://user-images.githubusercontent.com/85475736/142586081-d51965b2-a066-4d0b-9780-fec09332e1de.png)
![IMG_0809](https://user-images.githubusercontent.com/85475736/142586091-8bbcbec8-dcc3-4bef-b6ef-da09a941b18a.png)
k

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.67(408)
