### ISSUE TITLE
Create gift:Not allowing more than 1000 sats

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4754]
- Not allowing more than 1000 sats. 
![moresats](https://user-images.githubusercontent.com/62699947/142719053-bf27d224-c6c4-4fda-b0a1-e9b3d64bdf56.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)

**Comment by GourabSanyal** [comment]
fixed, tested 2.0.75
