### ISSUE TITLE
UX and language.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4755]
1. This does not indicate that the receiver will be added as a F&F. Does not seem to be associated with the Sending action. 
 2. Plus not sure it is about recipient being added to F&F or gift being added. 
 3. Also does it need a ‘Send Later’ action to make it clear, instead of the cross. UX and language to be looked at.

![forsuminabhi](https://user-images.githubusercontent.com/62699947/142719100-412d0a6a-db44-4c16-904f-3e1378ee13d6.jpg)

**Comment by ASN-BitHyve** [comment]
Regarding Points 1 and 2: "Add recipient to Friends and Family"
Point 3: I like the thought on the "Send later" button. Still the X button should also be there i think.

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
