### ISSUE TITLE
Enter gift datails page: Text change.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4756]
- This is not correct Abhilash. It should have instructions around how to claim it… scan the QR or click the link etc.
![giftdetail](https://user-images.githubusercontent.com/62699947/142719189-1c343eb4-fb36-40f9-bba8-d7a8d59402a4.jpg)

**Comment by ASN-BitHyve** [comment]
"You have received **a** gift from"
"Scan the QR or click the link to claim your gift.
(I think we should also retain the line that's currently there) @antuz123 
"

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
