### ISSUE TITLE
Redirection after sending gift.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4758]
- After sending is done, it should not come back to this screen but go to Sent section in Gifts.
![navigationgift](https://user-images.githubusercontent.com/62699947/142719417-251b76db-79c0-486a-bcde-c4f48e959867.jpg)

-  This Gift was sent but did not appear in Sent but available. It should be marked sent as soon as the QR/ Link button is pressed.
![sentbutnotavailable](https://user-images.githubusercontent.com/62699947/142719672-263c5414-aed7-4c20-b41c-6959a23dee5e.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)

**Comment by cakesoft-shashank** [comment]
Need to check how we can redirect to the sent section. I have redirected to the manage gifts page

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.6(385)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.6(386)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.6(388)
