### ISSUE TITLE
Manage Gifts:Status and text change.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4759]
- This category is for Sent but not yet accepted. And Sent and Accepted. The text should reflect that and the Gift should be called - Sent to recipient (as shown) or Accepted by recipient. 
![senttorec](https://user-images.githubusercontent.com/62699947/142719965-90fec286-6da1-410c-b609-80fba6f4e60b.jpg)

- 
![Screenshot_20211120-142628](https://user-images.githubusercontent.com/62699947/142720627-4d7cd8a1-9edf-46a0-895d-53614b805590.jpg)

1. Available has Created and Received Gifts. 
2. The status should show that. 
3. Also on all tabs, there should always be a description text of what it means like here it will be - “All the gifts you have created and not sent, plus gifts you have received are shown here” 
4. We don’t need the Received tab

**Comment by ASN-BitHyve** [comment]
Available status when no gift has been created or received: "All the gifts you create and receive would be visible below"

**Comment by ASN-BitHyve** [comment]
@Parsh there was a mistake from me in the Expired text above. I have changed the word unclaimed to "not accepted". Please update in the app. Have removed the fixed label. Apologies for the inconvenience.

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
