### ISSUE TITLE
Gift card details:Consistent language needed 

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4762]
- Consistent language needed across.
![consistent lang](https://user-images.githubusercontent.com/62699947/142731031-ca5a31c6-34f5-48d3-a991-839a89376b59.jpg)

**Comment by ASN-BitHyve** [comment]
On top it should say, " Gift sats details"

Status should be" Gift created", "Gift sent" etc.

Button text: "Send Gift sats"

**Comment by Parsh** [comment]
This has already been addresses here: https://github.com/bithyve/hexa/issues/4772

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
- Duplicate of #4772
