### ISSUE TITLE
When we add the gift back to the account...

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4765]
- When you add the gift back to the account, it shows in the balance but not in the transactions. Even on hard refresh.
![whenweadd](https://user-images.githubusercontent.com/62699947/142736595-a4543ba7-3b0b-4236-a9f2-94e5c5d2c723.jpg)

- Gift cards visible even after they are added back to the account. It should move to expired.
![availableexpir](https://user-images.githubusercontent.com/62699947/142747862-10a36ebe-762a-4d5b-81fd-204fb1c333c1.jpg)

**Comment by Parsh** [comment]
Gifts once added to the account are now visible under the expired section. However, there is going to be no corresponding transaction as the gift has simply been imported into the account and no txn has been performed.

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(381)
