### ISSUE TITLE
Gift sats:currency issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4766]
- Not sats but the currency that was chosen. I had chosen £
- 
![notsatbtcurrency](https://user-images.githubusercontent.com/62699947/142732022-e01b5d0a-9c1c-483f-ae2b-bd64daeabf58.jpg)

**Comment by cakesoft-swati** [comment]
- Able to reproduce this issue on staging app v2.0.5(381)

**Comment by cakesoft-swati** [comment]
- This needs to have an option to be in the $/£ amount
![needtooption](https://user-images.githubusercontent.com/62699947/142748051-3c6aa6a7-0343-4411-b6e7-c3d65a61550b.jpg)

**Comment by Parsh** [comment]
@cakesoft-shashank can you implement the switch? I'll do the conversion part based on the state of the switch.

**Comment by antuz123** [comment]
@Parsh - pls take help from Tobi

**Comment by cakesoft-swati** [comment]
![IMG_2598](https://user-images.githubusercontent.com/62699947/145956521-91e84665-a6a5-46a5-ad19-913a03091cb3.jpg)
- Tested on dev app v2.0.66(401)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.66(402)
