### ISSUE TITLE
Gift flow

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4768]
There are 3 sections:

1) Available 
2) Sent
3) Expired

Available shows the ones that the user creates as well as has received but hasn't moved into any account.

Sent shows gifts that 1) a user has sent but hasn't been accepted by the other party.... 2) sent and HAS BEEN accepted.

Expired shows gifts that a user Sent, but got expired as the other party didn't claim it. It also shows gifts that the user reclaimed and Expired herself.

The Received tab is to be removed.

(Issue created to be explicit about Gift flow)

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
