### ISSUE TITLE
Timer getting cut

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4769]
I have enlarged my fonts slightly.
 ![Screenshot_20211121-001456_hexa stage~2.jpg](https://user-images.githubusercontent.com/68264080/142737742-461acfe1-926c-47a7-80b7-3cb370da1bda.jpg)

**Comment by cakesoft-swati** [comment]
- Unable to replicate this issue.- Verified this issue on staging app v2.0.5(382)
