### ISSUE TITLE
OTP not visible

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4771]
![Screenshot_20211121-002152_hexa stage.jpg](https://user-images.githubusercontent.com/68264080/142737860-5d6884c9-37f6-4217-a8c2-0d2c1e0fdc82.jpg)

**Comment by Parsh** [comment]
Need more information about this scenario. Not able to recreate it.

**Comment by antuz123** [comment]
@ASN-BitHyve - how did you get this?

**Comment by ASN-BitHyve** [comment]
> @ASN-BitHyve - how did you get this? 

Strangely, I got that only once. As you can see behind that image. I am in the gift flow, have generated a gift and clicked on share via link.

**Comment by Parsh** [comment]
@ASN-BitHyve @cakesoft-swati I'm unable to replicate this. Marking it as fixed for now.

**Comment by cakesoft-swati** [comment]
- Unable to replicate this issue.Verified on live app v2.0.5(379)
