### ISSUE TITLE
Remove the word "card"

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4772]
![Screenshot_20211121-062826_hexa stage~2.jpg](https://user-images.githubusercontent.com/68264080/142745309-105ed009-60c8-4844-9b2b-f3e0f7bb7fc1.jpg)

**Comment by ASN-BitHyve** [comment]
![Screenshot_20211121-065951_hexa stage.jpg](https://user-images.githubusercontent.com/68264080/142745794-3af93c92-ede4-4fb4-bbb8-97cc0effb687.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(381)
