### ISSUE TITLE
Improper message

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4773]
I had not sent the gift. Its still in the Available section. Still somehow the app thought that I had sent the gift.

![Screenshot_20211121-063630_hexa stage.jpg](https://user-images.githubusercontent.com/68264080/142745408-27844d46-712d-4e0f-863d-2070d2477ae0.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on live app v2.0.5(381)
