### ISSUE TITLE
Receiver end not accepting OTP

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4779]
![Screenshot_20211121-075237_hexa stage.jpg](https://user-images.githubusercontent.com/68264080/142746903-173c6fff-f138-4d93-b704-06c5b223b50d.jpg)

https://user-images.githubusercontent.com/68264080/142746907-c56c84c5-16ce-4eef-9d41-0a11d9a981d3.mp4

**Comment by Parsh** [comment]
Unable to replicate, was able to accept the gift post entering OTP, need more details to debug this.

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
