### ISSUE TITLE
Multiple gifts

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4782]
1. Need an advanced option on the create gift screen where you can enter a number. E.g. 5 for 5 gifts. The amount will remain the same that is entered on the main screen. The entry modal can be as simple as for custom priority 
2. Once a number is entered, it shows on the gift screen like a simple indication that this is 5 gifts being created.
3. On the next success modal also an indication of how many of those gifts are created. And when user clicks send, it is only one of the gift that is picked up for send.

**Comment by antuz123** [comment]
We will be creating 100 gifts of 10k each. The app should be able to do that. @Parsh @cakesoft-shashank

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/7b80e533-289b-466c-ab83-88825bcb68e1/

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
