### ISSUE TITLE
Create Gift: After click on button it is taking long time for next screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4789]
- After clicking this. It takes a long time for the next screen.
![temp (125)](https://user-images.githubusercontent.com/62699947/142801283-9690513c-caf4-4a4f-a797-2344c22831e4.jpg)

**Comment by antuz123** [comment]
Need to put a grey screen with waiting timer here

**Comment by antuz123** [comment]
Need a loader modal with a note "Wrapping your gift"

**Comment by Parsh** [comment]
Looking into gift creation ramp-up at https://github.com/bithyve/hexa/issues/4834

**Comment by Parsh** [comment]
There seems to be not much scope when it comes to ramping the creation process up, however, I've done [some changes](https://github.com/bithyve/hexa/issues/4834#issuecomment-976298006) that may help a little.

We might want to have a loader modal while the creation is ongoing.

**Comment by cakesoft-shivani** [comment]
@summikhan11 Need UX for the modal like this Or just Image for this modal to add on gift creation 
![Screenshot_20211123-171643_hexa dev](https://user-images.githubusercontent.com/50820210/143018980-d8b0d5f1-a42c-4020-8ddd-a0ade17e4491.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/723f353e-15ed-44f6-982b-38bff01b9bbf/

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
