### ISSUE TITLE
UX issues:Check the icons.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4791]
- check icon
![temp (127)](https://user-images.githubusercontent.com/62699947/142801932-aa7a1c2f-9381-411e-9f41-b150e5b66a1c.jpg)

- icon should be like the ones listed above.
![temp (128)](https://user-images.githubusercontent.com/62699947/142802191-c3935692-810e-4ed7-ba52-71a1be8d1669.jpg)

- options icons missing
![temp (129)](https://user-images.githubusercontent.com/62699947/142802389-b75578f0-d875-4019-ad46-d78d2f1afa7c.jpg)

-

**Comment by summikhan11** [comment]
Settings & More : 
https://xd.adobe.com/view/902817ab-b10b-4f5e-8991-1f2142fd4a84-c57b/

App Info:
https://xd.adobe.com/view/902817ab-b10b-4f5e-8991-1f2142fd4a84-c57b/screen/1bc6f66e-02d7-4a1c-abef-8f26e965dd58/specs/

Account Management:
https://xd.adobe.com/view/902817ab-b10b-4f5e-8991-1f2142fd4a84-c57b/screen/45609ea9-a5d2-42c4-a0f0-a01fd955be83/specs/

**Comment by cakesoft-swati** [comment]
icons are not as per the UX.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(471)
