### ISSUE TITLE
Last gift getting cut in list of gifts

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4797]
https://user-images.githubusercontent.com/68264080/142812191-51891f64-3d2e-4528-82b9-3779b048de1a.mp4

**Comment by cakesoft-swati** [comment]
- Still having the same issue on live app v2.0.5(381)
![temp (133)](https://user-images.githubusercontent.com/62699947/142991314-0510e245-8f20-479e-9b5f-f2c9383fdb10.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
