### ISSUE TITLE
Indication required

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4798]
Three dots or downward arrow required to indicate that a user could select some other account.![Screenshot_20211122-120333_hexa stage.jpg](https://user-images.githubusercontent.com/68264080/142813301-01ec847b-bdea-43c0-8e28-ca1d6e88d1a9.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on live app v2.0.5(381)
