### ISSUE TITLE
Swan not working

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4801]
![Screenshot_20211122-130535](https://user-images.githubusercontent.com/62699947/142830923-b8dd4cc4-182d-4acb-82e7-1e41a6c53bb0.jpg)
-Getting error when I came back to the app after entering the passcode.

**Comment by cakesoft-shashank** [comment]
https://api.swanbitcoin.com/oidc/token is failing with status code 400
Our request is:

headers: {
      Accept: '*/*',
      'Content-Type': 'application/x-www-form-urlencoded',
      'Cache-Control': 'no-cache',
      'Sec-Fetch-Dest': 'empty',
      'Sec-Fetch-Mode': 'cors',
      'User-Agent': 'axios/0.18.1',
      'Content-Length': 415
    },

data: {
  "client_id": "hexa",
  "client_secret": "S3kSaC1BC4kEuaguL5uMF2GWNjVduHowgtE%K!74MNBBnumen&WH82HMKSAuQLh1",
  "code": "d8Sydi2LswtKuTx0GLlEgtEcSH0dIhGfWLLAP_7MqfJ",
  "code_verifier": "lCWJ8sJJhuAACDSfQsn02yAN1J67e0_ttkeK2IrcLf7_ZWQhHlAndpZwAwicWSpDyHSzL8eP4pz8GiUkBHsrnSlsdIR2gDvkD2fzMSX_vIoRj3xyv6df-eWbhVN2RiYC",
  "grant_type": "authorization_code",
  "redirect_uri": "https://relay.bithyve.com/deepLink/dev/swan/",
  "state": "53035238560-k1"
}

**Comment by cakesoft-swati** [comment]
- It is still happening on staging app v2.0.6(384)

**Comment by antuz123** [comment]
@cakesoft-swati - happening on Live? Else move to 2.1

**Comment by ASN-BitHyve** [comment]
Happened on Dev - 70 (445) Upgraded. Android.

**Comment by cakesoft-shashank** [comment]
@ASN-BitHyve @cakesoft-swati swan will work only on live app

**Comment by ASN-BitHyve** [comment]
Closing as its an old issue and we would've heard from people if Swan was not working still.
