### ISSUE TITLE
Status should change

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4803]
I sent Anant a gift. He accepted it. I got a notification for it as well. The status in sent section of that particular gift should change to "Accepted"
![Screenshot_20211122-152830_hexa stage.jpg](https://user-images.githubusercontent.com/68264080/142841095-df26d40f-84a8-4e23-bd2f-a7eae269de25.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
