### ISSUE TITLE
Mac certificate

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4823]
![image](https://user-images.githubusercontent.com/43998049/142959744-f472e372-2a27-4d0a-9a8b-6e588cccad9c.jpeg)

**Comment by cakesoft-utkarsh** [comment]
Certificates come with 365 days validity, They can be easily regenerated by developers once expired without affecting the exiting live apps.

We can ignore this. @antuz123 We can mark this closed.

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
