### ISSUE TITLE
Ui Issue - Terms & Service Marketing Website

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#4832]
change design to

https://xd.adobe.com/view/ff175839-dd75-4d46-8208-5fe20355d683-aa44/screen/b59592d6-d75d-4cca-97b8-1aa76427dd91/

**Comment by Raheel1258** [comment]
@summikhan11 , I don't have access to the website.

**Comment by ASN-BitHyve** [comment]
@akshaytikle please update the website Terms and Conditions section.

**Comment by ASN-BitHyve** [comment]
@akshaytikle is this done?

**Comment by akshaytikle** [comment]
Working on it in some time it will done.
