### ISSUE TITLE
Loader message describing gift feature

### ISSUE THREAD

**Issue by cakesoft-shashank** [bithyve/hexa#4833]
![image](https://user-images.githubusercontent.com/50690016/142973338-13e101e2-2fd7-4927-9032-503c1399853a.png)

**Comment by ASN-BitHyve** [comment]
Heading: "Gift Sats"
Sub-heading: "Send sats as gifts to your friends and family. Gift sats that you receive can be added to your account or gifted further without any extra fees"

@cakesoft-shashank

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
