### ISSUE TITLE
Create Gift

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#4834]
Gift creation is taking time(>3s), look if we can ramp the creation process up.

**Comment by Parsh** [comment]
Gift creation is taking standard tx creation, signing, and broadcasting time. However, I've updated the saga to communicate the creation right after successful tx broadcast rather than post DB updates. It might add a little bit of speed but not a lot.

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
