### ISSUE TITLE
User can add PDF for Primary Keeper

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4835]
User upgrade or reinstall app then user able to add pdf for 1st keeper of level 2

**Comment by cakesoft-shivani** [comment]
Not able to reproduce

**Comment by cakesoft-swati** [comment]
- Able to recreate this issue.I installed the app and went to security and Privacy section.There on level 2 when I clicked on Share Recovery key 1 it showed me backup recovery key modal then I chose Personal device to backup.
![File (88)](https://user-images.githubusercontent.com/62699947/145159968-b0102c6f-c7b6-4a62-9b7c-0d4920dce0dd.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(463)
