### ISSUE TITLE
Send Gift:Wrong message.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4837]
- The messages here are still wrong. The 30 day sentence is the instructions in the previous screen. And the message from the user is the second message, not what is here.
![temp (130)](https://user-images.githubusercontent.com/62699947/142976726-36c918f9-eec5-4324-8c9d-4b8cf5221246.jpg)

**Comment by Parsh** [comment]
@ASN-BitHyve I'll make the necessary changes once I've apt message from your end.

**Comment by ASN-BitHyve** [comment]
1) Gift Card > Gift sats

2) "You have received a gift from (name of gift giver). You can choose to add the sats to any of your accounts, or forward the gift to any of your friends and family (at no extra fees!)"

@Parsh

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
