### ISSUE TITLE
Reclaimed gifts:Didn't see that coming back to the account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4841]
- Reclaimed gifts are not coming back in here.
![reclaimegft](https://user-images.githubusercontent.com/62699947/142977727-50d8e9a9-8844-48f3-92fb-be35558f7f05.jpg)

**Comment by Parsh** [comment]
I've tried the following combinations:
- gift added back to account post creation
- gift created, sent and reclaimed, and then added back to the account
- gift created, sent, accepted by other party and added to account

All the 3 scenarios worked perfectly fine on my end, with gift sats getting credited into the associated account. While the transaction was visible only in the 3rd scenario(when someone else accepted and associated the gift). Associating a gift to the account which was the source of the gift doesn't lead to a transaction.

@ASN-BitHyve @cakesoft-swati

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.5(382)
