### ISSUE TITLE
Gift advanced options

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4842]
- The OTP or number or email used 
 1. Should be more prominent 
 2. It should be copiable by touching 
 3. Should be changeable if you want to.
 4. You could choose encryption options available or choose not to encrypt it. (Very similar to what we do with F&F requests).

**Comment by cakesoft-swati** [comment]
- The OTP message should be visible on the screen where a user is about to share QR or link.
- The user should be able to copy the OTP to share with the receiver easily.
- We already have a modal that we use in F&F when an encryption key is selected - phone/ email or OTP

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/1938a770-0d88-40ae-a590-cb528420fb18/

there's a few more options there.

**Comment by antuz123** [comment]
If there is no encryption chosen, then the link code should be longer (?) @cakesoft-shashank - need to discuss this

**Comment by cakesoft-shashank** [comment]
> If there is no encryption chosen, then the link code should be longer (?) @cakesoft-shashank - need to discuss this 

You mean shortlink?

**Comment by antuz123** [comment]
Yes, see here:
<img width="828" alt="Screenshot 2021-11-24 at 13 21 11" src="https://user-images.githubusercontent.com/43998049/143196895-22ebf7bd-de1a-430a-906b-8591ca3e8b2c.png">

**Comment by antuz123** [comment]
@cakesoft-shashank: 
We should go with 10 characters - 6 years option. This will be the default 
- This will remove the attack where someone else can brute force and guess the link. 
- This should also be the default for any shortlink - F&F request, Donations, etc 

@summikhan11 @Parsh 
It is however still possible for man in the middle or BitHyve to attack this 
- For that we will give an option of adding a second factor for 'larger amounts' 
- Here the user can select the 2FA they want to add 
- This is exactly like the F&F request 
- This should happen during the send flow where the user is entering a message 
- On the last screen (share) it should show if a second factor is selected and it being prominent and copiable

**Comment by cakesoft-shashank** [comment]
@antuz123 we have these options 

```
ShortLinkType {
    /**
     * Shorten the path to a string that is only as long as needed to be unique, with a minimum length
     * of 4 characters. Use this if sensitive information would not be exposed if a short
     * Dynamic Link URL were guessed.
     */
    SHORT = 'SHORT',
    /**
     * Shorten the path to an unguessable string. Such strings are created by base62-encoding randomly
     * generated 96-bit numbers, and consist of 17 alphanumeric characters. Use unguessable strings
     * to prevent your Dynamic DynamicLinks from being crawled, which can potentially expose sensitive information.
     */
    UNGUESSABLE = 'UNGUESSABLE',
    /**
     * By default, Firebase returns a standard formatted link.
     */
    DEFAULT = 'DEFAULT',
  }
```

**Comment by antuz123** [comment]
@cakesoft-shashank - need to figure out if we can do a 10 character long thing else wee will go with 17

**Comment by antuz123** [comment]
I think Shashank has implemented the 17 char OTP. Rest can be done with Tobi @Parsh

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/bd2d2f2b-a93a-405e-b154-5cb41209d297/

**Comment by antuz123** [comment]
@summikhan11 - the items for Advanced Options are: 

2nd Factors (we will call them something else)
1. F&F identification - this will be only when F&F option is selected. Will be  email or phone number depending on what data we have. And the user can change it if they want from within this option. This selection can be shown on the next screen. 
2. Simple OTP - when selected, the app generates it but does not show there. Not even on the next screen (it just says that the user will have to confirm an OTP which will be shown later) but only after the user has clicked 'Yes I have Shared'. A modal opens up where the user can copy this OTP. 
3. Long OTP - same as above but will be much longer 
4. User provided Secret Phrase - Here the user can provide anything and a 'Hint/ question' for the receiver 

(Timelock) 
1. The user can add a time lock for a month, 6 months or a year or choose a date
2. They are warned that this can't be undone 
3. Timelock can be selected irrespective of any of the above. 

Validity 
1. The user can add a validity to the Gift. I.e. the gift will be called 'expired' if the receiver trues to claim after that period 
2. The sender will see the gift in the available section after the validity has run out (when they come to the gift section and it gets refreshed)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/37d6d24f-6be7-4ed1-a2dd-01f39e367f42/

remove "add to friends & family" from here
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/da6e795d-c890-4ff1-bbc7-54c9f690be4a/


multiple denominations pending

**Comment by antuz123** [comment]
Depending on what you select as a 2FA mechanism, that should also be visible in the gift details when you go back there - like top or answer or something

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/


look for screens: 
Gift Details – Advanced Settings – Custom Secret Phrase
Gift Sats – Send – QR – Change contact
Gift Sats – Send – Short OTP
Gift Sats – Send – Long OTP
Gift – Details – Available Gift


content updates pending

**Comment by summikhan11** [comment]
added screens:

Home – Accept Gift Sats – Enter email address
Home – Accept Gift Sats – Enter OTP

**Comment by antuz123** [comment]
1. Sender side - post "I have shared" modals - Simple OTP and Long OTP - touch to copy - check UX @Raheel1258 
2. Receiver side - on accepting - simple OTP, Long OTP, email, phone number, Secret phrase - make it like F&F request acceptance @cakesoft-shashank 
3. Sender side - gift details - all scenarios - touch to copy - Check UX (only the row to show, rest of the gift details can follow later) @Raheel1258 @cakesoft-shashank

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.67(408)
