### ISSUE TITLE
Transaction not showing up in the list of transactions.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4845]
- Sent a normal transaction. Not showing up in the list of transactions though the total is down and the txn has been broadcasted as per explorer.
-I had too many trancations in the txn list. When I sent a normal txn it didn't show up in the list.

**Comment by antuz123** [comment]
Assume this for 2.0 and check

**Comment by Parsh** [comment]
@cakesoft-swati I've not been able to replicate it on Hexa 2.0. Can you please try and come back with more details if you are able to recreate it.

**Comment by cakesoft-swati** [comment]
Not able to replicate this issue.
