### ISSUE TITLE
Donation account deeplink issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4846]
- When we paste donation link in browser it provides me option "Open with hexa or different app" and when we open it with hexa it opens in hexa app but nothing happens after that.
- So, it should open in browser and not in hexa app.
- I have Hexa 1.0,Hexa live app 2.0.5(381) and Hexa staging app 2.0.5(381) installed on phone.But the option is showing only Hexa 1.0 app.
- This is happening on Android upgraded app from 2.0.5(379) to 2.0.5(381) and also on newly installed app.
![temp (131)](https://user-images.githubusercontent.com/62699947/142984302-a45091be-9bb1-4cbe-9d7b-40398329f719.jpg)

**Comment by antuz123** [comment]
Should not be needed when we decommission 1.0

**Comment by tumul-vikash** [comment]
is this issue fixed

**Comment by akshay8551** [comment]
This issue is not reproducible.

**Comment by cakesoft-swati** [comment]
- Unable to reproduce this issue on dev app v2.0.80(485)
