### ISSUE TITLE
Send Gift:Add recipient in F&F-Associate a contact using Skip.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4853]
![Screenshot_20211123-172340](https://user-images.githubusercontent.com/62699947/143024431-3e537597-aaee-4c22-972a-736066220943.jpg)
- When we add recipient in F&F while sending gift and we have selected Skip contact then it is showing blank icon and also showing a message "F&F contact number missing".

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/50f3a2cc-f211-4431-bd6b-e98e028834d2/

**Comment by cakesoft-swati** [comment]
- Able to reproduce this issue in dev app v2.0.66(401)

**Comment by cakesoft-swati** [comment]
- When we select Skip contact to send the gift to the F&F, it is showing blank icon and also the QR code is constantly loading and the link is also showing that it is being created and yet we try to share that link then it shows "Null" message or shows "unable to share file".

**Comment by GourabSanyal** [comment]
fixed, tested on 2.0.75
