### ISSUE TITLE
Show total for multiple gifts on creation

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4861]

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/7b80e533-289b-466c-ab83-88825bcb68e1/

will this total include fee too? @cakesoft-shivani

**Comment by cakesoft-shivani** [comment]
> 

@Parsh

**Comment by Parsh** [comment]
@antuz123 Any comments on that?

> https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/7b80e533-289b-466c-ab83-88825bcb68e1/
> 
> will this total include fee too? @cakesoft-shivani

**Comment by antuz123** [comment]
Yes disable the fee

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/332d0427-1f35-45bb-b50e-29257811336d/

**Comment by Raheel1258** [comment]
![simulator_screenshot_5FB35D95-58E4-4E8C-AC49-871195A3309F](https://user-images.githubusercontent.com/28229449/146191696-0300a8ba-b0ee-400d-84dc-c97909ba69cb.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.66(404)
