### ISSUE TITLE
Gift creation failure modal

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#4867]
Connected to #4865

When gift creation fails, we dispatch giftCreationSuccess with false as the parameter, this should let the UI know that the gift creation has failed and show appropriate failure modal.

Right now when the gift creation process fails, the gift creation modal just keeps showing.

**Comment by Raheel1258** [comment]
@summikhan11

**Comment by summikhan11** [comment]
@ASN-BitHyve please provide content

https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/adab612b-fb2c-451b-875a-c0c0f24a57fa/

**Comment by GourabSanyal** [comment]
@Raheel1258

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(469)
