### ISSUE TITLE
Remove extra space 

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4880]
![Screenshot_20211125-113330_hexa stage.jpg](https://user-images.githubusercontent.com/68264080/143388297-9d02adfc-ea77-4268-8fc4-9d23ff9926a5.jpg)

**Comment by antuz123** [comment]
@ASN-BitHyve - look at this message with many options. There are other textual mistakes. Plus cloud/ drive should not be an option there.

**Comment by ASN-BitHyve** [comment]
Dear Dev, kindly replace the text in the image with this:  "To proceed please scan the Approval Key stored on your Personal Device or Personal Copy(pdf)".

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(415)
