### ISSUE TITLE
Post restore issues.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4886]
- I had completed level 2 with Personal Device 1 and Personal Device 2.
- I had created one gift and reclaimed it.
- I also changd the wallet name.Sent some sats from savings account.

- [x]  But at the time of recovery it showed me the Old wallet name and also showed that the backup at level 1.Still I recovered the wallet.After recovery it showed that the  only  level 1 was completed and also the saving account was not enable.

Post recovery the gift transaction was also not there on account.

- [x] After recovery when I try to share personal device QR then that QR was not visible only the loader was loading.

**Comment by cakesoft-swati** [comment]
- Tested this issue on Dev App v2.0.70 (431). I changed the wallet name but at the time of recovery  it showed me the old wallet name again.

**Comment by Parsh** [comment]
Changed wallet name from Based to BasedCH and it shows the updated name on all steps to restoration.

![Simulator Screen Shot - iPhone 12 - 2022-02-05 at 14 48 48](https://user-images.githubusercontent.com/17980466/152636532-c39b2978-b8c9-4268-84c3-bc06305debb3.png)

![Simulator Screen Shot - iPhone 12 - 2022-02-05 at 14 55 01](https://user-images.githubusercontent.com/17980466/152636534-042df12a-b60b-4837-a014-28bd10bf8375.png)

![Simulator Screen Shot - iPhone 12 - 2022-02-05 at 14 55 13](https://user-images.githubusercontent.com/17980466/152636536-a1f9b815-a82f-479a-b78a-8722954a5b45.png)

**Comment by Parsh** [comment]
Tried it on iPhone and wallet name change worked perfectly. Changed from blinkblink to xest and then did the restoration.

![IMG_0197](https://user-images.githubusercontent.com/17980466/152641217-06a23d65-f5dc-41ed-8f87-c338c840d295.PNG)

![IMG_0198](https://user-images.githubusercontent.com/17980466/152641222-ed3d7b68-3189-4366-bf45-3d68b2fcf83b.PNG)

![IMG_0200](https://user-images.githubusercontent.com/17980466/152641223-d11653e4-7301-4f2f-ab4a-a5e7f666f633.PNG)


Here's a video of the restoration with the wallet name change:


https://user-images.githubusercontent.com/17980466/152641242-549d0c76-df46-47b3-9ac9-ee90bc1c1191.MP4

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(472)
