### ISSUE TITLE
Can we distribute the buttons evenly?

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4889]
![Screenshot_20211125-163439_hexa stage.jpg](https://user-images.githubusercontent.com/68264080/143430315-f1ad73f6-89d6-4dff-8eaf-a2beb8cbc1d3.jpg)

**Comment by summikhan11** [comment]
@cakesoft-swati please check the fonts on this screen.

**Comment by cakesoft-swati** [comment]
- @summikhan11  The font size on this screen was the default. It looks the same for all font sizes.

**Comment by cakesoft-shashank** [comment]
@ASN-BitHyve 
![simulator_screenshot_55938493-4B03-4748-8EFB-91EC6F54C9BB](https://user-images.githubusercontent.com/50690016/143991113-414b5328-730b-4750-a891-7dfe0701e574.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.6(385)

**Comment by summikhan11** [comment]
please dont make ui changes that i dont suggest.

please revert this. it looks out of proportion.

**Comment by cakesoft-swati** [comment]
- Verified this issue as discussed with dev.
