### ISSUE TITLE
Savings account post recovery.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4893]
- I had completed level 3 But the message was incorrect on Home screen.
- After that I received some sats in savings account and restored the app.
- After post recovery level 2 was completed still I could not use the savings account.It was showing me the message "Complete Level 2".
![Screenshot_20211125-184724](https://user-images.githubusercontent.com/62699947/143460382-651803b5-9a68-4373-ae95-03a399b519ec.jpg)

![Screenshot_20211125-200512](https://user-images.githubusercontent.com/62699947/143460459-5a4c58b7-19e5-404a-a5e1-cb994a50cf93.jpg)

**Comment by Parsh** [comment]
- I had completed level 3 But the message was incorrect on Home screen. (Resolved in 2.07)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.66(404)
