### ISSUE TITLE
Saving Account un-hide

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4894]
I created 2 Savings Account

Changed the name of all the accounts including the Checking Account 

Hide all the three accounts 

Not able to unhide them

**Comment by antuz123** [comment]
Then I also hid the Donations and Swan account. Not able to unhide them either.

Restored the wallet on another device, still not able to see any account.

**Comment by cakesoft-swati** [comment]
- Verifiy this issue on staging app v2.0.6(384)
