### ISSUE TITLE
Change Keeper 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4895]
Changed the Keeper on L3. Thee old Keeper still showed as Keeping me though needed an approval key to scan. It should not show me as a Keeper. Only F&F 

Downgrade to F&F

**Comment by Parsh** [comment]
This is connected to the following: https://github.com/bithyve/hexa/issues/5219#issuecomment-1030863486

@cakesoft-swati We need inputs here whether the change keeper is working in the first place.

**Comment by cakesoft-swati** [comment]
- Change Keeper flow was working in previous version but Change contact fuctionality was breaking in prevoius.

**Comment by cakesoft-swati** [comment]
This is connected to the following: https://github.com/bithyve/hexa/issues/5219#issuecomment-1030863486
