### ISSUE TITLE
Ability to restore without using the cloud 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4897]
The user should be able to cancel the modal where cloud options are given and directly restore from any other two/ three keys 

Once restored, the other RKs are marked red unless confirmed or changed.

**Comment by cakesoft-swati** [comment]
- Unable to see the above changes.

**Comment by cakesoft-shashank** [comment]
This will be after we introduce other than cloud options in backup

**Comment by cakesoft-swati** [comment]
- flow is changed for now.
