### ISSUE TITLE
Not use cloud for Level 1

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4898]
If the user wants they can change the Keeper for the cloud option. 

They may have done on cloud but want to change or may have skipped thee option entirely. The details screen will give a share now option with 4 options - cloud, Contact, Device and PDF. 

So it applies that any other Keeper can also be cloud if not already one

**Comment by cakesoft-shivani** [comment]
- [ ] Change cloud to other keepers
- [ ] Setup other keeper on level 1

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.6(394)
