### ISSUE TITLE
Currency for Gift

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4899]
Check the last comment

**Comment by cakesoft-swati** [comment]
![temp (136)](https://user-images.githubusercontent.com/62699947/143824085-451778dc-ce70-4305-8756-40e186acad29.jpg)
- The amount entry field only shows sats option, no other option. Gift cards kits show value in sats no matter the currency on the Home Screen.

**Comment by antuz123** [comment]
1. Put back the currency switch for Gits (both when creating and in Manage Gift screen) 
2. The gifts should have no relation to the switch in the accounts 
3. Both the switches (Create and Manage) should be linked - be the same 
4. The details on the Manage screen should reflect the currency chosen 
5. The currency on the Create screen should be used for all details used on that screen and going forward. 
6. The receiver should see the gift in the amount sent. For this we may need to pass the amount at that time as text. It will be shown in the card only. Once it is accepted and in the Gift list, the currency there will work according to the above. The amount sent ($5, £10 or 100k sats) can show exactly like that on the receiver side ignoring the receiver side currency or the exchange rate at that time. So a simple text as Amount should suffice.

**Comment by cakesoft-swati** [comment]
- 6th point is still pending.So filing a new issue for this and closing this one.
