### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4900]
Enable theme selection with:

General, Birthday, Christmas and Wedding.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/914419d8-218d-42c8-8d69-f1ab2dd6c7a2/
there's thanksgiving too, lemme know if you want that removed

**Comment by ASN-BitHyve** [comment]
Christmas 

Heading: Merry Christmas 

Subheading: Yuletide cheers to you and yours


Wedding 

Heading: Wedding best wishes

Sub: A special gift for a special couple

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.6(383)
