### ISSUE TITLE
Donation account:issues on web page.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4902]
1.cant see the Donation description on the Web Page.The name of the donation change to name of the Account which is Donation Account. These are two different variables. This is why the description does not come.

**The variables are:**
- Web Variables:
1.Donation Name (different from Account Name and entered by the user).
2.Organised By (provided by the user)
3.Donation Description (Long description for the donation)
![Screenshot_20211130-095131__01](https://user-images.githubusercontent.com/62699947/143985384-68cfc107-4df0-455d-ae53-26b5033cb3fc.jpg)

![temp (137)](https://user-images.githubusercontent.com/62699947/143985438-8eb78c59-8923-4283-a620-05577838b77f.jpg)

2. Still cant see post on Twitter after donating. Only showing close.

**Comment by cakesoft-swati** [comment]
@akshaytikle @ASN-BitHyve We need to fix this issue in 2.0.6 today itself.

**Comment by cakesoft-utkarsh** [comment]
@Parsh Staging Relay is blocking the reuqests from hexawallet.io. CORS issues. 
Can you please allow CORS on staging relay, this would solve the missing donation info issue on Donation Staging.

**Comment by Parsh** [comment]
@cakesoft-utkarsh 
I'm not sure what extra needs to be done to activate CORS on the staging relay, as all three versions of the relay have the same codebase w/ [cors activated](https://github.com/bithyve/Relay/blob/6334fb3f378a23895b9bad6194fcc1311429f80c/src/index.ts#L16).

**Comment by cakesoft-utkarsh** [comment]
Donation Staging web pages were using staging-relay.bithyve.com as the base relay base URL, which I believe is incorrect.
Changed the base URL on donation Staging web to  baseUrl = "https://new-staging-relay.nw.r.appspot.com/"

Can see the donation info now. 
Please verify the other issue about twitter posting @cakesoft-swati  and mark close if it works.

**Comment by cakesoft-swati** [comment]
Dupicate of #4937
