### ISSUE TITLE
Donation account:Account name and description.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4903]
- cant see the description on the Web Page.
- The name of the donation change to name of the Account which is Donation Account.  These. are two different variables. This is why the description does not come.
![Screenshot_20211126-104242](https://user-images.githubusercontent.com/62699947/143530330-acd8d337-1d75-4daf-bd34-56dec9088eb5.jpg)

![temp (135)](https://user-images.githubusercontent.com/62699947/143530361-5ee1faa0-0db8-4229-ba0e-51ac8fe78e61.jpg)

 **The variables are:**
- Web Variables:
1.Donation Name (different from Account Name and entered by the user).
2.Organised By (provided by the user)
3.Donation Description (Long description for the donation)
- Account Variables:
1.Account Name (like any other Account, defaulted to 'Donation Account')
2.Donation Name becomes the Account Description (which is a variable like any other account)

**Comment by antuz123** [comment]
Only Web variables to be sent to the web. It has nothing to do with the account variables.

**Comment by cakesoft-swati** [comment]
Duplicate of 4902
