### ISSUE TITLE
Font size should be bigger by a few pixels?

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4907]
Can we increase the font size of the heading and subheading @summikhan11 ?

Personally I would prefer a font size increase. Leave it for you to take a call.

![simulator_screenshot_435e0b3c-4165-45fa-9b2b-ac34750adb8a.png](https://user-images.githubusercontent.com/68264080/143541330-73f40d22-c85d-416c-b961-48694d7c6c27.png)

**Comment by summikhan11** [comment]
the font sizes are smaller compared to VD. ive sent beta feedback for this

**Comment by summikhan11** [comment]
this doesn't seem fixed. please check again. the font is different as well. 
Ive sent beta feedback as well
