### ISSUE TITLE
Need indication that on which level user is currently 

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#4910]
In screenshot I am on level 3 completed 
![Screenshot 2021-11-26 at 1 55 40 PM](https://user-images.githubusercontent.com/50820210/143556060-e446f4df-0571-4f64-8ca3-69e2114a871c.png)

**Comment by summikhan11** [comment]
the design of this screen needs to be changed.
when we go into manage backup the current level is shown there

**Comment by antuz123** [comment]
Level 2 should be open. And the action when you touch the right keeper should be suggested.
