### ISSUE TITLE
App is crashing on Send of any account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4911]
- I upgraded the staging App v2.0.5 (382) to 2.0.6 (384)
- Then I opened Hide accounts and went to that account.
- The app crashed when I clicked the send button.

**Comment by cakesoft-shashank** [comment]
![simulator_screenshot_5874B80F-BC82-4E70-8317-0F77230B36DE](https://user-images.githubusercontent.com/50690016/143588145-0afec027-e870-4f44-a264-18099827b8ea.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.6(385)
