### ISSUE TITLE
Message for gifts

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4914]
1. The Sender side text for themes from Abhilash 
2. The custom message that sender puts should also be on the receiver side. The card should be identical on both sides.

**Comment by ASN-BitHyve** [comment]
Birthday:
The only better birthday gift is time.

Wedding:
Give a gift fit to be an heirloom

Christmas:
This Christmas be the Santa who gifts sats

Gift Sats:
Gift something that appreciates with time

**Comment by cakesoft-shashank** [comment]
> 1. The Sender side text for themes from Abhilash
This is done

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.6(386)

- [ ] 1.The Sender side text for themes.

2.The custom message that sender puts also there on the receiver side. The card is identical on both side.
