### ISSUE TITLE
No new installs for 1.0

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4915]
The user should be able to upgrade an existing wallet. 

The user should be able to use the recovery flow. 

But when they download and press new wallet, they should be given a message that they should download 2.0 instead.(We can show them the notification screen we used)

**Comment by ASN-BitHyve** [comment]
Notification message:

"This app is not operational anymore. New users are requested to download Hexa 2.0. It is faster, more secure, and packs in a bunch of performance improvements over Hexa 1.0."

 _Note to Dev: (Please give "Download Hexa 2.0" button beneath the message above. The button should take the user to the corresponding app/play store based on OS detection)_

"If you previously had sats in Hexa 1.0 and wish to recover the wallet, please go to the Restore Wallet section, click on "Using Recovery Keys" and follow the steps to restore your wallet. Once restored, please transfer your funds to Hexa 2.0."

**Comment by cakesoft-swati** [comment]
- Verified this on Hexa 1.0 app v1.7.4(303)
