### ISSUE TITLE
Icons should be visible in different language settings 

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4917]
Notice how there are icons in this section in English but missing here in Russian. Its missing in other languages as well.

![IMG_20211128_102634_907.jpg](https://user-images.githubusercontent.com/68264080/143730203-d0bcd973-8703-4d41-9d60-13268db053c0.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.6(386)
