### ISSUE TITLE
Pre Live: App Store submission

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4927]
- [ ] Release notes(up to 500 characters) - App Store, APK
- [ ] Image change?

**Comment by ASN-BitHyve** [comment]
2.0.6 Release Notes
**Hexa Wallet partners up with Swan Bitcoin**

Now Hexa has a built in Swan Bitcoin wallet. Stack with Swan, hodl non-custodially with Hexa!

Setup auto-DCA in your Swan Account and seamlessly transfer sats to your Hexa Wallet

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/ec019ed7-5d7f-4e9f-a73d-ba75f254b45c-b952/
App Store & Google play images

**Comment by ASN-BitHyve** [comment]
@cakesoft-shashank just tagging you as Summi has given the image.

**Comment by ASN-BitHyve** [comment]
Release Notes 2.0.66: 

Introduce your friends and family to bitcoin with Gift Sats

Fees is charged only once, while creating the gift. 

After receiving Gift Sats you could add the sats to your account or gift it forward to your friends without incurring any fees.

Be a Sats Santa. Gift Sats this Christmas.

**Comment by antuz123** [comment]
Use bullets

**Comment by ASN-BitHyve** [comment]
> Use bullets

Done

**Comment by antuz123** [comment]
2.0.67 release notes: 

Advanced Second Factor option for gifts
Bug fixes and improvements

**Comment by cakesoft-shashank** [comment]
@antuz123 @ASN-BitHyve these are 2.0.66 release notes. Should I append it with above?

Introduce your friends and family to bitcoin with Gift Sats

•  Fees is charged only once, while creating the gift.

•  After receiving Gift Sats you could add the sats to your account or gift it forward to your friends without incurring any fees.

Be a Sats Santa. Gift Sats this Christmas.
_________________________________________

• Bug fixes and improvements.

**Comment by ASN-BitHyve** [comment]
2.0.69 release notes shared with Shashank.

**Comment by ASN-BitHyve** [comment]
Release Note 2.0.70:
Lightning strikes Hexa Wallet! (Beta)
It took us a while to get there, but Hexa is now Lightning enabled. Its still in its infancy though and this is the first of a planned 3 stage roll out process.
Do play around with it and help us improve Lightning within Hexa. We're all ears for bug reports, and performance enhancement suggestions.   

Other updates:
Gift Sats security improved
Bug Fixes and performance improvements

**Comment by antuz123** [comment]
- Lightning Account introduced in Hexa
- Connect your LND node and manage your channels
- (Coming Soon) Integration of Lightning in other parts of the wallet 

Other updates:
- Gift Sats security improved
- Streamlined initial onboarding flow 
- Bug Fixes and performance improvements

**Comment by ASN-BitHyve** [comment]
@summikhan11 need an image for the app stores with a relevant lightning screen.
Heading: "Lightning enabled"

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/ec019ed7-5d7f-4e9f-a73d-ba75f254b45c-b952/screen/3b506661-5216-4a99-b911-0161dcce082e/
scroll to find the other size

**Comment by ASN-BitHyve** [comment]
Release Notes for 2.0.75:

Backup and restore your wallet using Seed Words
Backup using Recovery Keys - Flow overhauled and simplified
Hexa now has a Lightning enabled account!
Bug Fixes and performance improvements

@cakesoft-shashank
