### ISSUE TITLE
Post Live: Website 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4928]
- [x] FAQ changes 
- [ ] Announcement banner? 
- [x] Latest News updation
- [ ] AOB

**Comment by ASN-BitHyve** [comment]
FAQ section updated to reflect Swan's FAQ: https://hexawallet.io/faq/

**Comment by antuz123** [comment]
Abhilash, the FAQ about Swan has nothing. That is not what FAQ we should have.

**Comment by ASN-BitHyve** [comment]
Website updated announcing 2.0.71 availability. FAQs to be updated.
