### ISSUE TITLE
Pre Live: Staging Test 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4929]
- [ ] Main net testing @antuz123 
- [ ] Content Check @ASN-BitHyve 
- [ ] UX check @summikhan11

**Comment by summikhan11** [comment]
Based on resolutions the categories are 

For iOS 

1. iPhone 12 (same resolution different size -iPhone 12Pro Max, 12 Pro, X, XS, 11 Pro, XR, XS Max, 11) - this one I already own

2. iPhone 6 (same resolution different size -iPhone 7, 8, 8 plus & SE) 


For android

1. Google Pixel 5 - I own Samsung Galaxy M31- which has almost the same resolution
2. Google Pixel 4 (or 4XL)
3. Samsung Galaxy S10
