### ISSUE TITLE
21 Days of Christmas

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4936]
We will be giving away gifts for 21 days leading up to Christmas. Will need:

1. Image for the announcement @summikhan11 
2. A logo to reflect a Santa/ Christmas themed Hexa @summikhan11 
3. A tweet long message @ASN-BitHyve

**Comment by summikhan11** [comment]
App Icon (can use this as twitter profile picture too) 
https://xd.adobe.com/view/ec019ed7-5d7f-4e9f-a73d-ba75f254b45c-b952/screen/3978f8df-5ed1-4b0a-9905-ae5f67b43935

**Comment by summikhan11** [comment]
Need copy for the announcement image @ASN-BitHyve

**Comment by ASN-BitHyve** [comment]
Copy for announcement image: "This year be the sats Santa!"
(Suggestion: 1) We could depict a happy Santa with a mobile phone(with its screen visible to the viewer). The screen on the phone shows our gifting icon prominently, but subtly. 2) The atmosphere of the image could have 1 or 2 of the typical Christmasy bells and whistles (Lit Tree, star, snow, food, gathering of people, etc.))

@summikhan11

**Comment by ASN-BitHyve** [comment]
Tweet Text: "Starting today, we will be giving away Gift Sats for 21 days leading upto Christmas. Scan the QR, DM us for the OTP. Redeem your gift and keep it for yourself or gift forward to friends and family!" 
(Insert appropriate emojis)

@antuz123

**Comment by summikhan11** [comment]
sent the image via email, its too big to upload here

**Comment by antuz123** [comment]
@summikhan11 - additionally I will need a profile pic for me as a laser eyed Santa. Can just use a filter or something. 

@ASN-BitHyve - let's think of people we want to gift for recognition. And the announcement on the 12th

**Comment by antuz123** [comment]
https://bithyve-workspace.slack.com/archives/C021PTT2R5M/p1639108259028700

**Comment by summikhan11** [comment]
@antuz123 i'll need a picture of you as Santa.

**Comment by ASN-BitHyve** [comment]
"Starting 21-12-21, we will start pleb giveaways. Where we will randomly put out QR codes for people to scan and accept."

Abhilash to lead this.

**Comment by antuz123** [comment]
Use all channels...

**Comment by summikhan11** [comment]
anything required from me? @ASN-BitHyve
