### ISSUE TITLE
Donation account: issues on website.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4937]
1.cant see the Donation description on the Web Page.The name of the donation change to name of the Account which is Donation Account. These are two different variables. This is why the description does not come.

**Doantion link(Dev app):https://donation.hexawallet.io/K2FE**
**Donation link(Live app):https://donation.hexawallet.io/sejT**

**The variables are:**
- Web Variables:
1.Donation Name (different from Account Name and entered by the user).
2.Organised By (provided by the user)
3.Donation Description (Long description for the donation)
![Screenshot_20211130-095131__01](https://user-images.githubusercontent.com/62699947/143985384-68cfc107-4df0-455d-ae53-26b5033cb3fc.jpg)

![temp (137)](https://user-images.githubusercontent.com/62699947/143985438-8eb78c59-8923-4283-a620-05577838b77f.jpg)

2. Can not see the post on Twitter after donating. Only showing close.
3. Need to show Trasactions tabs on webpage.Don't need transaction details screen on the site, only the list with basic ten info is enough
- Here is the UX link:
https://xd.adobe.com/view/319a403f-183f-4eb6-bdbe-9cd9dc9c4450-64c9/screen/5224a22e-70f7-4258-ae04-d7d0f43a543d/

**Comment by akshaytikle** [comment]
I have co ordinate with @cakesoft-utkarsh and understand issue and checked in detail and its beyond my skill , its not CSS  issue, Its related with jQuery functions. Let me know if anything related with UI only  like if we need to hide that transaction detail popup.

**Comment by cakesoft-utkarsh** [comment]
- [ ] Displaying Transactions.
- [ ] Missing Donation info 
Are done.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.6(388)
