### ISSUE TITLE
Exclusive option for multiple gifts

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4939]
When the user selects multiple gifts as an option from advanced: 

1. A text box with the number of gifts appear 
2. The total of the gift is shown 
3. The 'include the fee' option is gone as fee cannot be included 

In the same way, 

4. we need to have an option to select "Make each gift exclusive", same as the fee selection option. A subtext will be "(Restricts the gift to one per person or per Hexa app)"

5.  This will be selected by default 

6. When selected, it generates a small random code - may be using the senders wallet ID and timestamp. This code is sent with the metadata unencrypted. 

7. When the recipient tries to accept the gift, the app checks for the exclusive gift the app has accepted and if the code exists there, the app shows a message that they can't accept the gift as they have already claimed one. 

8. This means that the gift data in any app, maintains a small list of "Exclusive gift codes". And anytime you accept a Exclusive gift, the code gets added to that list. This is also backed up aptly. (You don't want to check against all the gifts as you may have added the gift to the account or something else. Checking against this list is better which will be empty most of the times.

**Comment by summikhan11** [comment]
do we need a "know more" for this? @antuz123

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/8cea1360-8194-4496-961e-a73d57e20c18/

**Comment by Parsh** [comment]
The exclusive gift lookup hasn't been backed up in the WI tho.

**Comment by cakesoft-swati** [comment]
- The flow is not according to UX.
- Not showing total amount on Create Gift page.
- Not showing the total amount while sending the Gift.

**Comment by antuz123** [comment]
Just make sure that the total is on the Create screen

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev appv2.0.6(387)
