### ISSUE TITLE
Shift screen after backup

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4942]
Once a user has backed up on the Cloud, they don't need to remain on this screen. They can be led back to the Security and Privacy section.
![Screenshot_20211130-115531_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/143996734-272a9067-2121-4e53-a78f-4d9f5c18245e.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on ios dev app v2.0.70(431)
