### ISSUE TITLE
Gifting text changes

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4946]
Please retain heading. And replace the subheading with: "Give sats as gifts to your friends and family."
![Screenshot_20211130-165717_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/144039394-e21c09bc-3c61-4838-bb9b-7e67b83ac3f8.jpg)

**Comment by ASN-BitHyve** [comment]
Please replace the text on top in Gifting Know More with: "Hexa creates a link or QR code that allows you to send sats as gifts to anyone using Hexa Wallet"

Please replace the text at the bottom in Gifting Know More with: "You can manage these Gifts from here. Send them when you want to and reclaim them if not accepted. The recipient will be directed to download Hexa wallet if they don't have it already"

**Comment by cakesoft-swati** [comment]
- I didn't see any changes on dev app v2.0.66(401)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.66(404)
