### ISSUE TITLE
Pre-Live: Check if a new icon is required for a new feature being released

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4948]
When the wallet is loading, the image in the right corner should correspond with the message being displayed. So a message about Gifting should have a corresponding image with the gift icon, a message about Donation should have image with donation Account. 

@summikhan11

**Comment by summikhan11** [comment]
each image doesn't really stay for that long, a generic gear one is enough.

**Comment by ASN-BitHyve** [comment]
Summi's comment to be kept in mind: "For special scenario we can have dedicated animations with static content." Abhilash and whichever dev would be leading that feature, need to check whether loading image needs to be changed or not.

**Comment by antuz123** [comment]
Need a LN logo for Hexa. We can get rid of "2" if we want. @summikhan11

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/ec019ed7-5d7f-4e9f-a73d-ba75f254b45c-b952/screen/d790b1bc-61f7-4183-9d4c-96ca7be05049/

**Comment by summikhan11** [comment]
should we need an animation @ASN-BitHyve

**Comment by ASN-BitHyve** [comment]
> should we need an animation @ASN-BitHyve

Lets do that when lightning stage 3 is ready and we're making a lasting change in the logo.
