### ISSUE TITLE
Gift wrapping modal

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4949]
When a gift is being prepared, an animation  wrapping a BTC coin in a box to appear in lower right hand corner instead of the gear animation.

Abhilash to give better text.

![Screenshot_20211130-171925_hexa stage.jpg](https://user-images.githubusercontent.com/68264080/144042629-934ef5fd-b8c0-4499-a5bd-1a78aa08704b.jpg)

**Comment by antuz123** [comment]
This applies to the loader messages and when Create Gift.

**Comment by ASN-BitHyve** [comment]
Heading: Packing Your Gift
Sub-heading: 

- You can reclaim sent gift sats

- Gift sats that you receive can be added to an account or gifted further without any extra fees

@cakesoft-shashank

**Comment by antuz123** [comment]
Heading: Packing Your Gift

Sub-heading:

Once created, you can send the Gift Sats right away or keep them for later 

If not accepted, you can reclaim your Gift Sats

**Comment by summikhan11** [comment]
@cakesoft-shashank try this
![gift](https://user-images.githubusercontent.com/85475736/144366509-97a21b6d-59b5-4069-96a5-dcce27bb9a48.gif)
