### ISSUE TITLE
Highlighted text to be removed

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4950]
![Screenshot_20211130-172543_hexa stage.jpg](https://user-images.githubusercontent.com/68264080/144043026-226c279d-738b-4b06-a52b-cf2314c42cdc.jpg)

**Comment by antuz123** [comment]
Please replace not remove

**Comment by cakesoft-swati** [comment]
Verified this issue on dev app v2.0.6(386)

**Comment by cakesoft-swati** [comment]
- Not able to see the Personal note if we send Gift to F&F.
- Not on both side sender and receiver.

**Comment by Parsh** [comment]
Addressed by #4976

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.6(388)
