### ISSUE TITLE
Logo should be Hexa 2.0!

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4951]
![Screenshot_20211130-173229_hexa stage.jpg](https://user-images.githubusercontent.com/68264080/144043947-6d480776-5e10-4857-a535-3af1a6e66f09.jpg)

**Comment by ASN-BitHyve** [comment]
https://xd.adobe.com/view/ec019ed7-5d7f-4e9f-a73d-ba75f254b45c-b952/screen/3978f8df-5ed1-4b0a-9905-ae5f67b43935/?x_product=cc-slack%2F1.5.1 

@cakesoft-shashank here's the logo link. You'll find the normal logo in those set of files as well. Do you need anything else from Summi?

**Comment by cakesoft-swati** [comment]
- Hexa logo is not visible on shared image when we share QR with other apps.
![ReactNative-snapshot-image7856494204729547050 (1)](https://user-images.githubusercontent.com/62699947/144390913-5f391c4f-0983-4bc9-b3e7-85dee25aafea.jpg)

**Comment by summikhan11** [comment]
should it be though? it won't even be visible. @ASN-BitHyve

**Comment by summikhan11** [comment]
please keep "h" in the QR

**Comment by antuz123** [comment]
Leave the original logo for Hexa @Raheel1258

**Comment by summikhan11** [comment]
what is needed from me?

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.66(401)
