### ISSUE TITLE
Gift:UX issues.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4954]
- change icon.
![temp (138)](https://user-images.githubusercontent.com/62699947/144176228-ecc68767-22fb-46e2-b52e-9f8940d76ea5.jpg)

1. use specified icon for "back"
2. icon should be of a gift. content should say "from checking account" 
3. remove white background
![original](https://user-images.githubusercontent.com/62699947/144177079-14cacb29-047c-4801-8dd0-5c11119dc2bd.jpg)

- check font sizes
![original (1)](https://user-images.githubusercontent.com/62699947/144177189-ded60d91-ffa4-4d8b-a43e-e3f868cd938b.jpg)

1. use the specified back icon 
2. check font 
3. update the gift illustration 
4. check placement of CTA
![original (2)](https://user-images.githubusercontent.com/62699947/144177303-e5827389-4216-4a59-bab5-f3d6e1477423.jpg)

- active text felid has a shadow, inactive one doesn't.
![original (3)](https://user-images.githubusercontent.com/62699947/144177381-3884f68b-3b88-4816-93e6-0c4a2d9d9502.jpg)

- check font sizes on the screen. 
1. check alignment 
2. message should be left aligned not center aligned 
3. check opacity for line 
4. remove background and increase button sizes.
![original (4)](https://user-images.githubusercontent.com/62699947/144177504-0c1d47a6-518e-4469-9ad9-0877c307249c.jpg)

- change toast notification design.
![original (5)](https://user-images.githubusercontent.com/62699947/144177638-2a853c3c-d8cc-40cf-afb2-54c186ea18c6.jpg)

- remove white shadow
![original (6)](https://user-images.githubusercontent.com/62699947/144177689-95d17ecb-d01f-4a12-ad31-21a810f2a775.jpg)

**Comment by Raheel1258** [comment]
@summikhan11, can you provide me the relevant designs?

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/da6e795d-c890-4ff1-bbc7-54c9f690be4a/specs/

you'll find all screens on this link @Raheel1258

**Comment by cakesoft-swati** [comment]
- change icon.I'm still able to see the old icon.
![temp (138)](https://user-images.githubusercontent.com/62699947/144176228-ecc68767-22fb-46e2-b52e-9f8940d76ea5.jpg)
