### ISSUE TITLE
Swan-Browser support

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4956]
- After clicked on "Link Swan Account" it momentarily poped up a screen that then disappeared and its back to Home screen.
![image (3)](https://user-images.githubusercontent.com/62699947/144179306-1dd501c3-1e8e-4cab-a24f-c75f05e2a49f.png)
-  Browser: Firefox.
-  Device: Samsung Galaxy S20+5g,android.

**Comment by cakesoft-swati** [comment]
Browser:Firefox

https://user-images.githubusercontent.com/62699947/155955596-4e7196c7-51fd-4df7-9168-f9df7c5c8957.MP4

![File (121)](https://user-images.githubusercontent.com/62699947/155955687-53b267cd-be2e-48a1-9492-0ae2eecb9f66.jpg)
- On opening the link on Firfox, first this message appears and later the link opens in the app.

**Comment by antuz123** [comment]
Default browser is not chrome on an android and the Swan link (from the app) is not opening

**Comment by cakesoft-swati** [comment]
- It s happening when the default browser is Firefox in android.
- Tested in android device One plus 9R.

**Comment by antuz123** [comment]
Comment to Swan @cakesoft-shashank 

Update our FAQ and Swan FAQ

**Comment by cakesoft-shashank** [comment]
FAQ updated

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
