### ISSUE TITLE
Message to recipient.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4963]
![original (7)](https://user-images.githubusercontent.com/62699947/144218040-f751b385-5019-4aba-966f-d6e015c15adb.jpg)
- -Where is the actual message. Also theme is missing here.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/45497806-ad0b-4d06-be3c-0c0f730c883a/

**Comment by cakesoft-swati** [comment]
- Didn't see any changes in dev app v2.0.66(401)

**Comment by cakesoft-swati** [comment]
- Theme is still missing here on Gift Detail screen.
- Tested on dev app v2.0.66(404)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/45497806-ad0b-4d06-be3c-0c0f730c883a/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(431)
