### ISSUE TITLE
F&F request for already created gift.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4964]
- When sending an already created gift, there is no way to add a F&F request. This screen should give an option to add the person as a F&F like when you send directly after creating. As soon as you select that, Associate Contact screen opens.
![original (8)](https://user-images.githubusercontent.com/62699947/144218329-be0146a3-b3c8-4f8a-9355-3ec5e336ebb4.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/bd2d2f2b-a93a-405e-b154-5cb41209d297/

**Comment by summikhan11** [comment]
link is already provided, anything else needed from me?

**Comment by cakesoft-swati** [comment]
- I did not see any changes in dev app v2.0.66(401)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.66(404)
