### ISSUE TITLE
Minimum Gift Value:Note change.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4965]
![File (84)](https://user-images.githubusercontent.com/62699947/144219909-1a227344-14cf-461c-84e1-80c7836cc1e7.jpg)
- remove that note word and colon from there.
- Summi want to out that message in a different place,So @summikhan11  where you'd like to put it.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/332d0427-1f35-45bb-b50e-29257811336d/specs/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev appv2.0.6(387)
