### ISSUE TITLE
Manage Gifts:Ux issues.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4967]
- when I click on gift sats for the first time, know more should opn up on an empty screen.
-  "create new" should be dark blue.
- check the shadow of "available"
![original (9)](https://user-images.githubusercontent.com/62699947/144233368-5fc50b97-cc43-4dff-ab95-1abff0ea16f2.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/c4d67eb1-c038-40e6-a921-15517d461d52/specs/ @Raheel1258

**Comment by cakesoft-swati** [comment]
- Unable to see the changes as per the XD link.
- "create new" should be dark blue.
- check the shadow of "available"
- Tested on dev app v2.0.66(401)

**Comment by cakesoft-swati** [comment]
Chech the icon in UX.The "+" icon of Create New Gift is also dark blue.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(431)
