### ISSUE TITLE
Minor textual changes

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4970]
1) S capital in "sats" where highlighted.
2) Fullstop to be removed where highlighted 

![file-1.jpg](https://user-images.githubusercontent.com/68264080/144388238-cb244e7f-4459-4082-9a8b-a04aac72cc20.jpg)

![file-2.jpg](https://user-images.githubusercontent.com/68264080/144388266-fa898cd7-e10e-43c1-89ca-47b671ffe719.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.6(388)
