### ISSUE TITLE
Create Gift:Not allowing to create gift post recovery.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4974]
![Screenshot_20211202-154202](https://user-images.githubusercontent.com/62699947/144405160-2a5b0f45-ce6d-42b9-aefb-a3b0ac66e108.jpg)
- I retsored the wallet, now I have 7000 sats in my checking account still it is not allowing me to cretae the gift with or without fee.

**Comment by Raheel1258** [comment]
@cakesoft-swati Unable to recreate this. FLow is working fine here with me

**Comment by cakesoft-swati** [comment]
-  Verified this issueon dev app v2.0.66(401)
