### ISSUE TITLE
Adding F&F on pixel

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#4980]
- Some issue with name/ middle name and sometimes it does not work.
- After allowing access to contacts for adding Friends and Family, I was looking through the list. For any of my contacts that I had a First Middle and Last name, the First and Middle names were what appeared in the list in Hexa. Last name did not appear.
- on iOS we can't search by last name. We should be able to search by any. 

https://user-images.githubusercontent.com/62699947/145810508-271bf047-f736-4117-a8da-28f4966a4851.mp4

**Comment by GourabSanyal** [comment]
UI behaving weirdly. 

https://user-images.githubusercontent.com/63765514/158347415-1943695c-a8ea-446c-aacc-1c64bab88fcd.mp4

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(469)
