### ISSUE TITLE
Test Account: Unhide on upgrade

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#4981]
- [x] Unhide the test account(if hidden), when user upgrades from a previous version(<2.07) to the current version(2.07).
- [x] Test account should be in the correct order on the home screen when un-hided

**Comment by Raheel1258** [comment]
My task here is completed @Parsh

**Comment by cakesoft-swati** [comment]
I upgraded staging app v2.0.65(393) to 2.0.66(404).My test account was hidden in previous version and when I upgrade it to 2.0.66(404) test account was there it got unhide automatically in upgraded version.
