### ISSUE TITLE
Accept Gift:Text change.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4984]
- Top should be: Accept Gift Sats
- Some space after “You have received a gift from…”
- The instruction message should be (instead of “You can choose ….. till fees!)):
 “Add the data to an account or keep them to send to someone else”
![Image from iOS (4)](https://user-images.githubusercontent.com/62699947/144579512-4c64b3ab-edc5-42db-94a4-8a14b604e3f6.jpg)

**Comment by antuz123** [comment]
Top should be: Accept Gift Sats 

First line “You have received bitcoin gift from…” 

Some space after that 

The instruction message should be (instead of “You can choose ….. till fees!)): 

“Add bitcoin to an account or keep them to send to someone else”

**Comment by antuz123** [comment]
The buttons should be Accept and Deny

**Comment by cakesoft-swati** [comment]
- Verified this issue on live app v2.0.65(393)
