### ISSUE TITLE
Accept Gift changes

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#4989]
@ASN-BitHyve I've moved copy around for this screen 

![IMG_1492](https://user-images.githubusercontent.com/85475736/144602848-13198709-977e-4eea-a317-16f7f163958f.PNG)

https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/000dce01-3316-49d4-9ce4-98ec88219dbe/specs/

**Comment by antuz123** [comment]
This screen has changed slightly last minute. Check on live when it comes @summikhan11 @ASN-BitHyve

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/000dce01-3316-49d4-9ce4-98ec88219dbe/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.66(402)
