### ISSUE TITLE
Wallet name exception

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4993]
The wallet should be able to detect when a name ends with an "s" and remove the "s" it adds after a name ( As per standard English practices Tomas's is wrong. It should be Tomas' )

![Screenshot_20211204-172308_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/144708462-d2c826b7-17d7-401d-aaeb-8d0dbceb5fae.jpg)

**Comment by cakesoft-swati** [comment]
![temp (148)](https://user-images.githubusercontent.com/62699947/145384492-74db99ad-8443-47c2-822a-88ffbe5ed26a.jpg)
- This change has not happened on the home screen.

**Comment by cakesoft-swati** [comment]
- Still I can't see the changes on Home screen and on Edit screen.
- Checked this on dev app v2.0.66(401)

**Comment by cakesoft-swati** [comment]
- Verified this issue on deva pp v2.0.66(402)
