### ISSUE TITLE
Automated Cloud Backup

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5002]
- After setting up the wallet, when we land on the home page, it displays a message on the home page saying "Automatic cloud backup is incomplete, please complete level 1" and if I click on the "Security and privacy" tab, level 1 is getting completed.
- It should complete the level 1 as soon as we land on the home page otherwise it should show an error message.

https://user-images.githubusercontent.com/62699947/144836891-07d52d9f-f4e7-44fc-bfe1-b0132f324454.mp4

**Comment by cakesoft-shashank** [comment]
not able to reproduce

**Comment by cakesoft-swati** [comment]
-Still facing same issue on android One plus 9R dev app v2.0.7(394)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(431)
