### ISSUE TITLE
Donation account:Donating from the same phone doesn't refresh the webpage and does not confirm the donation.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5014]
- When I donate from the same phone, the webpage does not refresh and confirm the donation. Stays in the waiting for the transaction mode.
- The page needs to keep pinging even if someone puts it in the background
- If you refresh it (with or without going to the background) it should come back to the same page and not go back to home.

**Comment by Parsh** [comment]
I wasn't able to replicate the above issue.

Created a donation account from my dev app(2.06) and donated to it using the same app's test account and it went through as expected.

<img width="1440" alt="Screenshot 2021-12-07 at 3 24 41 PM" src="https://user-images.githubusercontent.com/17980466/145009003-e99b6add-51a8-49f8-b201-6a542c105d69.png">

<img width="1440" alt="Screenshot 2021-12-07 at 3 25 47 PM" src="https://user-images.githubusercontent.com/17980466/145009022-91f0c515-d8a9-48d7-86fe-bb73c5b832e8.png">

![Simulator Screen Shot - iPhone 12 mini - 2021-12-07 at 15 25 35](https://user-images.githubusercontent.com/17980466/145009026-85c511f4-b356-48f3-b1f5-0df13975ed0e.png)

![Simulator Screen Shot - iPhone 12 mini - 2021-12-07 at 15 26 05](https://user-images.githubusercontent.com/17980466/145009028-be14dbdd-66f4-408f-87e2-013083771c8b.png)

**Comment by Parsh** [comment]
@cakesoft-swati Can you retry it once again and let me know the specifics if you are able to replicate it.

**Comment by cakesoft-swati** [comment]
- Steps to reproduce:
1.Copy the donation link and open it in browser.
2.Click the Donate >Donate Now button and copy the address.
3.Now come to the app from same phone and send some sats to that address.
4.Now go to the website and check.
5.I have to refresh that page manually.

**Comment by Parsh** [comment]
Note: This is happening only when the browser app is sent to the background while the phone switches between the app and the browser, thereby, the continuous ping from the browser gets halted.

**Comment by cakesoft-utkarsh** [comment]
Added an option to manually refresh the donation status.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.67(409)
