### ISSUE TITLE
Text updating needed

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5018]
"...choose a new CONTACT from..."

![IMG_20211207_180957_380.jpg](https://user-images.githubusercontent.com/68264080/145030775-5f178b23-a0ae-4137-828f-36f949b99fb8.jpg)

**Comment by cakesoft-swati** [comment]
- Text not changed
![temp (140)](https://user-images.githubusercontent.com/62699947/145151604-4eb95fb2-3cb2-4a0a-bc68-3bc0b177860d.jpg)

**Comment by cakesoft-swati** [comment]
- "...choose a new CONTACT from..."
![temp (179)](https://user-images.githubusercontent.com/62699947/152303990-cc9ac3ba-d831-48b3-a07c-897d2397cd6b.jpg)
- Contact word must be capital.

**Comment by cakesoft-swati** [comment]
- Verified this issue on upgraded dev app v2.0.80(485)
