### ISSUE TITLE
Shortlink redirection page

### ISSUE THREAD

**Issue by cakesoft-shashank** [bithyve/hexa#5021]
Option 1: Disable the page and test deeplinks

Option 2: Customize the page with title, subtitle and image for each link type

**Comment by cakesoft-shashank** [comment]
@antuz123 @summikhan11 please check the redirection page preview. We can customise title, subtitle and image

![simulator_screenshot_EC02666F-6D32-436A-8E02-5580FAAADE43](https://user-images.githubusercontent.com/50690016/145966992-9e4e9a7d-1cbc-4505-88f1-636f3d5fd98b.png)

**Comment by cakesoft-shashank** [comment]
@summikhan11 need images for these link types:

  CONTACT and KEEPER = 'https://request.hexawallet.io',
  GIFT = 'https://gift.hexawallet.io',
  DONATION = 'https://donation.hexawallet.io',

**Comment by summikhan11** [comment]
![Donation](https://user-images.githubusercontent.com/85475736/147627259-9d372a4d-0b67-464a-9a2d-3ab74b9953ca.png)
let me know if this size works. I'll send the rest @cakesoft-shashank

**Comment by summikhan11** [comment]
![gift](https://user-images.githubusercontent.com/85475736/147808751-ac435ef3-8d0c-4f5c-a90b-34e5de6929d1.png)
![f f](https://user-images.githubusercontent.com/85475736/147808758-6c85427a-79f9-4cfb-b15b-c55f5db0892b.png)

@cakesoft-shashank

**Comment by ASN-BitHyve** [comment]
Friends and Family:
You've received a request to be added as a contact. You'll be able to transact bitcoin more efficiently if you accept this request. 

Keeper Request 
You've received a request to store a Recovery Key. You'll be able to help your contact recover their wallet if you choose to become their Keeper.

Gift Sats:
You've received some sats from your contact! open the link to accept the gift. You can add the gift to your account or forward it to your friends and family at no extra fees.

 
Donation Request
You can give sats as donation with this link. Accepting the link will take you to a webpage for you to donate sats to the cause.

@cakesoft-shashank

**Comment by cakesoft-swati** [comment]
- Donation link is opening the F&F request also the Donation image is showing the F&F image.
- Text suggested by Abhialsh is also not there in the app.

**Comment by cakesoft-swati** [comment]
@ASN-BitHyve Can you please reduce the text?Can not see the last 3/4 words on Preview page.
![File (109)](https://user-images.githubusercontent.com/62699947/149882188-f57d73df-5f5e-4d65-86ab-6dd5a1d81333.jpg)

**Comment by ASN-BitHyve** [comment]
Have edited the text above @cakesoft-swati , @cakesoft-shashank .

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(420)
