### ISSUE TITLE
Possible insufficient balance bug

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5025]
I have sufficient balance. I told the app to include fees in the gift amount and chose to create a gift of as much money as I could. Don't think there is any reason for the app to say "insufficient balance", except that the fees is higher than 6100 sats which I doubt.

![photo6161036277676354837](https://user-images.githubusercontent.com/68264080/145194638-2b3a41d4-75d3-45a1-add3-93c4d7a998b7.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.66(402)
