### ISSUE TITLE
Level 2 > Recovery Key 2

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5033]
Once a user has backed up Recovery Key 1 at level 2, and organically, logically clicks on Recovery key 2, he should not be told to back up Recovery Key 1. He should not have to come out of the modal, pull down the screen when the section refreshes, Personal device icon changes to the blue phone, and then go back in to try again.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(485)
