### ISSUE TITLE
1.0: Logo and name 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5049]
- [x] Change the name of the 1.0 app to: "Legacy Hexa app - do not download"

- [x] Change the logo to something not even close to Hexa and having the word legacy/ do not download on it. 

Idea if for making sure users don't download it. Both stores. 

- [x] Also for 2.0: I suggest we change the names to 'Hexa 2.0 Bitcoin App' from 'Bitcoin wallet Hexa'

**Comment by summikhan11** [comment]
![App icon – Legacy](https://user-images.githubusercontent.com/85475736/145548940-3d2f76c1-3fe6-49a6-a009-d51ba779a138.png)

**Comment by antuz123** [comment]
Check the updated name "Hexa 2.0 bitcoin wallet"

**Comment by cakesoft-shashank** [comment]
@antuz123 app name "Hexa 2.0 Bitcoin App" for hexa 2.0 is updated on stores. Its under review on playstore and on appstore it'll update with build

**Comment by cakesoft-swati** [comment]
Tested on playstore and Appstore.
