### ISSUE TITLE
Recovery keys are not getting confim again.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5052]
- I had completed Level 3 and after sometime it expired and I had to confirm. I Clicked on Confirm. But the backup was not getting confirmed.
- Personal copy,Cloud backup,Conatcat backup are not getting confirmed again.

**Comment by cakesoft-shivani** [comment]
Personal Copy and Cloud will need user action to confirm 
@cakesoft-swati

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(431)
