### ISSUE TITLE
Not able to restore the wallet.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5054]
![Screenshot_20211210-103815](https://user-images.githubusercontent.com/62699947/145530269-5097f342-ece0-46a1-a2ea-51447c6f404c.jpg)

- I had completed level 3, the message was right on the home page too. But when I restored the wallet, the accounts were missing from the home page.
- The same thing happens when Level 1 is completed

**Comment by cakesoft-shashank** [comment]
@Parsh need to check why transactions are not getting restored

**Comment by cakesoft-swati** [comment]
- I can see the balance on the home page and also on the accounts.
- I can also create and send gifts. Only I can't see the transaction on the account page and in the list of all transactions.

**Comment by Parsh** [comment]
Unable to replicate.

I've been able to perfectly restore my level-3 backed-up wallet.

Pre-restore:
![Simulator Screen Shot - iPhone 12 - 2022-02-01 at 17 20 51](https://user-images.githubusercontent.com/17980466/151964645-8594d277-1d00-4cf6-93ce-0eda56148f9f.png)


Post restore(All accounts available as well the transactions appeared as they should have)
![Simulator Screen Shot - iPhone 12 - 2022-02-01 at 17 30 27](https://user-images.githubusercontent.com/17980466/151964853-17f22dca-935c-43dd-bdbd-9a45a4edb5e8.png)

![Simulator Screen Shot - iPhone 12 - 2022-02-01 at 17 27 29](https://user-images.githubusercontent.com/17980466/151964657-2173f551-2e93-44b0-8d22-cbadcd69b31c.png)

![Simulator Screen Shot - iPhone 12 - 2022-02-01 at 17 27 36](https://user-images.githubusercontent.com/17980466/151964660-7907200f-7b2d-459c-95d5-db3c164fecd3.png)

![Simulator Screen Shot - iPhone 12 - 2022-02-01 at 17 30 24](https://user-images.githubusercontent.com/17980466/151964822-fcc02eaa-ee41-42c2-8c98-20b4a02b94c5.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(431)
