### ISSUE TITLE
Deeplink to QR

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#5055]
We would like to include deeplink directly into QR rather than having a JSON object. This would allow for an external scanner to scan it and either open the app or redirect the user to the app store for download.

**Comment by cakesoft-swati** [comment]
- Need to check this issue on live app.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.66(404)
- I scaned the Gift QR from external scanner and it open in the app.

**Comment by cakesoft-swati** [comment]
- Verified this issue on live app v2.0.67(409)
