### ISSUE TITLE
Gift Concurency  Lock

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#5058]
We would need to have a lock around the fetch Gift API as multiple entities can try to fetch the gift concurrently and would end up w/ the gift(the round trip time of fetching, accepting, and updating gift status and removing the encrypted gift is in the order of few seconds). 

The lock(lock timestamp?) would be applied as soon as an entity fetches the gift and would stay there for say 10/15 seconds by which it is expected that either the gift would be accepted and therefore removed(by the fetching entity) or abandoned/rejected.

**Comment by Parsh** [comment]
Fetch API now has a lock(can only be used once), tho the source can still reclaim the gift in case of accidental breakdown of the gift acceptance saga.

**Comment by cakesoft-swati** [comment]
- Tested it on dev app v2.0.66(404)
