### ISSUE TITLE
Various images required

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5059]
1) Swan Integration Announcement Image required for Home Page banner - Desktop + Mobile

2) Gift Sats Feature Announcement image required for Home Page Banner - Desktop + Mobile

3) Appropriate celebrating Bitcoiners image:
a) One Announcement image, announcing that we're doing it.
b) A template to put in people's Twitter images to celebrate them. This image should have the Gift Card with the QR code that can be scanned. An OTP can be DMed to the person of the day we would be celebrating. 

4) Pleb giveaway image (This Chritmas be a Sats Santa) image is fine for this. But we need the image in appropriate size for Twitter, Desktop and Mobile.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/ff175839-dd75-4d46-8208-5fe20355d683-aa44/screen/e71751d5-0e6f-407c-b4a5-75bdc5b4c3d5/

scroll to find mobile too

**Comment by ASN-BitHyve** [comment]
@akshaytikle please update the website with the images.
