### ISSUE TITLE
Image to be repurposed for App and Play stores

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5061]
This is regarding the image that says "This year be a Sats Santa".

We need that image repurposed a little for the app stores. Text for the image:  "(1)This year be a Sats Santa (2) Follow @hexaWallet on Twitter to know how!" 

Image required for both App stores in appropriate dimensions.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/ec019ed7-5d7f-4e9f-a73d-ba75f254b45c-b952/

scroll to find both sizes

**Comment by cakesoft-shashank** [comment]
@ASN-BitHyve ss is updated
