### ISSUE TITLE
Add pdf for level 1 

### ISSUE THREAD

**Issue by cakesoft-shivani** [bithyve/hexa#5063]
- So the option for level 1 will be personal device and cloud
- If someone has skipped backup or it did not work, they can have any of these two options.
- If they have not provided an answer/ password, that will be asked first and then the backup step

**Comment by Parsh** [comment]
Note: We need an option on level one to have PDF as the backup as well.

![Simulator Screen Shot - iPhone 12 - 2022-01-29 at 12 14 59](https://user-images.githubusercontent.com/17980466/151650786-e149a143-ee9b-4e6c-810b-96e915d29f90.png)

**Comment by antuz123** [comment]
When you get to Level 2, what is the approach for PDF? New PDF or storing more data in PDF image?

**Comment by cakesoft-swati** [comment]
Now the options will be cloud and seed words.So,closing this issue for now.
