### ISSUE TITLE
Upgrade Script: MB Data Pipeline

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#5064]
We would need to write an upgrade script for versions upgrading from <2.07. The [pipeline](https://github.com/bithyve/hexa/pull/5044) re-structuring for BHR flow requires few variables to be introduced to the redux state(BHR reducer) from the database, ensuring that the flow doesn't break for the apps being upgraded.

Storage reducer: 
Wallet::smShare

BHR reducer: 
metaSharesKeeper & oldMetaSharesKeeper

**Comment by Parsh** [comment]
How to test:
Upgrade from version <2.0.69(level 2 completed) and you should be able to complete level 3 after you upgrade to 2.0.70.

**Comment by Parsh** [comment]
Dependency: #5335

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
