### ISSUE TITLE
Unable to send funds after accepting gifts.

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5068]
The user accepted a gift on 9th December. 

The transaction has 6 confirmations.

This is the first transaction that the user is trying after accepting the gift.

Iphone. Fresh install. 2.0.65.

The user has tried sending sats via all the different priorities.

User Name: M**o
Platform: Telegram

https://user-images.githubusercontent.com/68264080/145716645-22547dd3-f131-495d-baff-52a505c02ea6.mp4

**Comment by Parsh** [comment]
@cakesoft-swati Can you please try to reproduce this? I've not been able to replicate this.

**Comment by ASN-BitHyve** [comment]
Abhilash:
 "1) Did you have funds in the wallet (either purchased or received) before accepting the gift?
2) If yes, were those transactions confirmed?
3) Did you create a gift before or after receiving the gift that you did?
4) If you had created and sent a gift, had you reclaimed it?"

User: 
1)no funds prior. 
2)no prior funds
3)no, I haven’t created any gifts
4)no

**Comment by Parsh** [comment]
Haven't been able to replicate it. @cakesoft-swati Can you take a look at it?

**Comment by Parsh** [comment]
@ASN-BitHyve We should ask this user to upgrade his/her app and try the flow again. The idea is to see what error gets displayed after pressing the Confirm&Send button(as the latest version shows the specific error unlike the version used while creating the above video), once we have more information regarding the error, we can look further into this.

**Comment by antuz123** [comment]
"Missing inputs" is the error you get after upgrading

**Comment by Parsh** [comment]
@antuz123 Please provide the transaction id of the Gift that you've added to your account post which the missing input error started showing up.

**Comment by Parsh** [comment]
![Simulator Screen Shot - iPhone 12 - 2022-01-05 at 16 44 57](https://user-images.githubusercontent.com/17980466/148209053-4aea1585-52f8-4288-8aae-5706407fec1d.png)

**Comment by ASN-BitHyve** [comment]
Have given the user the latest update. Haven't heard back from them. Closing this issue.
