### ISSUE TITLE
User unable to restore Hexa 1.0 

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5069]
Hi there! I have an issue with the login. I destroyed my old iPhone, buy a new one, and at the same time, I downloaded Hexa 2.0. I cannot log in to my old Hexa (with the pin), I can log into the new one with the same pin, but then I tried to recover my account with no success. The recovery key did not work at all. It seems that it just don’t react. And with other option - is said to answer some question- but I don’t know which question:) does anybody else have the same problem? Help, please:)

![photo5884232932598592983](https://user-images.githubusercontent.com/68264080/145993780-b4cc0651-1670-46b3-b550-ee6022db7968.jpg)

Anant to User: "Hexa 1 and Hexa 2 are separate apps. The way to migrate from v1 (legacy) to the v2 app is to transfer the funds. You can’t use the Recover Keys from v1 on v2 or the other way around."

User's reply: "Ok, but I cannot log into the Hexa 1…
My old pin doesn’t work in the new app.. and I cannot switch on the old phone, because it is totally destroyed. What should I do?"

Anant: "So did you download Hexa 1 again in a new phone?"
User: "Yes, I did. I recovered my iPhone from backup with all the apps. So maybe I should delete and download Hexa 1 again and then try to recover?"
Anant: "Yes, you need to recover Hexa 1 it with Hexa 1 Recovery Keys"
User: Ok, but when I open the Hexa 1 app now- there is this:

![photo5884232932598592990](https://user-images.githubusercontent.com/68264080/145995460-0961ab79-1fc3-4475-8a7d-e7b71bdb10cc.jpg)

User: "And my pin does not work.. so I have to delete it and download again?"
Anant: "Yes pls"
User: "Thank you. I will let you know!"

User: "So I scan the key and nothing has happened…"
![photo5884232932598593093](https://user-images.githubusercontent.com/68264080/145995663-3690a580-a309-4028-b36c-47052236d078.jpg)

User: The screen after I scan the recovery key from another app- on iPad. And if I’d want to recover from backup- there is this question/answer situation again...
why does it not work?? Even with the correct recovery key?"

Anant: "So did you answer the question correctly ?"

User: "I don’t know. I don’t know the question- So I tried something and it went through - but it did not display if I answer correctly.. how can I know"

Anant: "Ok, I have logged a ticket with the technical team. Meanwhile do try a few more answers and let us know if that helps. Will get back to you when we have a response from the tech team"
User: "Thank you! The problem is that it does not react at all. If I answer something possibly wrong it shows this:"

![photo5886484732412278618](https://user-images.githubusercontent.com/68264080/145996086-b8b96b21-f2d6-4a80-998a-cdb36fcb8cf9.jpg)

User: "When I try possibly correct the answer there is just a blank page. Some with the recovery key- it just shows the page again with no progress"

Anant: "Ok, are you sure you are selecting the right backup. It is actually a list/ a drop down with name and timestamp. Would it be a different backup on the ‘Restore from iCloud’ screen"

![photo5886484732412278648](https://user-images.githubusercontent.com/68264080/145996295-9364a462-1bb3-4517-b21b-89a43c4670fb.jpg)

![photo5886484732412278649](https://user-images.githubusercontent.com/68264080/145996356-ac4b32be-c0f9-4d53-9fac-36e558027a5b.jpg)

User: "I can see only this.."
Anant: "Ok, understand. Let us look into it with the tech team"

User name: ***teri** Ce***va
Platform: Telegram

**Comment by cakesoft-shashank** [comment]
For pin restore issue:
We are using [rn-secure-storage](https://github.com/talut/rn-secure-storage) to store the hash of pin. [rn-secure-storage](https://github.com/talut/rn-secure-storage) uses iOS Keychain api to store the values. There is this thread [app keychain not getting backed up/restored using iCloud backup](https://developer.apple.com/forums/thread/93373)

**Comment by cakesoft-shashank** [comment]
Improvement suggestions:
1. Detect if using encryption password or security question and answer and change UI accordingly
2. Show message if password is incorrect
3. Show password hint on UI

**Comment by cakesoft-shashank** [comment]
> Improvement suggestions:
> 
> 1. Detect if using encryption password or security question and answer and change UI accordingly
> 2. Show message if password is incorrect
> 3. Show password hint on UI
> 4. ~Pin backup on cloud~

Point 4 will be tracked in #5094

**Comment by cakesoft-swati** [comment]
- Verified this issue on Hexa 2.0 dev app v2.0.66(404)
- Need to test this for Hexa 1.0 Moving it in 2.07

**Comment by ASN-BitHyve** [comment]
Updates from the user after updating Hexa 1.0:

"Hello, so I downloaded the app, but the problem persists. I chose to restore from iCloud, and then there is this mysterious question."


![photo5931697780122826347](https://user-images.githubusercontent.com/68264080/147925970-f48c0de7-a66e-48a5-a3f6-34d411652213.jpg)

"I don’t know what is the security question.. in ma email I had “the first city you’ve visited”. But here.. Why there is no question?! I can remember the answer not the question. So I tried answer the first city I’ve visited and it just went through with no feedback to this:"

![photo5931697780122826348](https://user-images.githubusercontent.com/68264080/147926021-472d0d0b-a625-4e8d-862b-43417bf740f1.jpg)

"And when I tried to scroll down it closed the whole app."


Comment from user for the image below: This is my keeper account and when I scan the recovery key- nothing is happening."

![photo5935911765810460856 (1)](https://user-images.githubusercontent.com/68264080/147926169-8a14ca3f-4640-4978-9d7d-15ea1664687d.jpg)

Do you have any idea what is the health question?!

**Comment by ASN-BitHyve** [comment]
@cakesoft-shashank few more comments from the user logged above.

**Comment by ASN-BitHyve** [comment]
The user replied that the issue isn't resolved yet. Abhilash has invited the user for further discussion. Response from user is pending as on 7th Feb.

**Comment by ASN-BitHyve** [comment]
Feedback from the user: 
![1](https://user-images.githubusercontent.com/68264080/165491664-d5cbd083-3f24-445e-811f-824637643722.jpg)
![2](https://user-images.githubusercontent.com/68264080/165491669-81039bba-3778-46a8-8656-217d13472cc4.jpg)
![3](https://user-images.githubusercontent.com/68264080/165491671-70f30d9d-3646-491c-8fbb-dd00b7a6fb61.jpg)
![4](https://user-images.githubusercontent.com/68264080/165491672-544176d8-3878-4802-8959-5f85343144c1.jpg)
![5](https://user-images.githubusercontent.com/68264080/165491675-63a8b606-1802-4207-9d44-67a2ca65181c.jpg)
![6](https://user-images.githubusercontent.com/68264080/165491678-4c003cf6-309b-4cdc-84d6-62a07d8702b5.jpg)

This is my path to recover hexa and ipad with recovery key. When I scan the QR code (help restore) it doesn’t show anything. When I push it down (like scroll down) it close the app

**Comment by cakesoft-swati** [comment]
- Closing this issue for now.
