### ISSUE TITLE
Dust limit issue

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5071]
![Image from iOS (8)](https://user-images.githubusercontent.com/62699947/145758402-bc4ac179-af4c-4e54-a581-94d0e2dfe847.jpg)
-  Dust limit keeps varying.I have seen this message before, but have easily been able create gifts of 1500 sats.
- Tried sending 5k out of 5.5k and it did not go. Sent 2k and it went.
- The dust limit is not the problem, the message is incorrect for sure.It should say reduce the amount and try as fee needs to be higher

**Comment by Parsh** [comment]
Here: change UTXO is invalid atm(< dust limit). We might wanna include the change in the fee and get the tx going. 
This is happening because the fee is getting statically included thereby not allowing the coinselection to expand fee to include the otherwise invalid dusty change into the fee.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.66(402)
