### ISSUE TITLE
Gift sats:Changes on 'Send Gift' screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5073]
![Image from iOS (9)](https://user-images.githubusercontent.com/62699947/145793140-5a2cfc05-453c-434a-b92b-6f273c626acf.jpg)
- It should be Gift Sats with capital S.
- The ratio of the card should be that is a regular card/ Twitter post, it seems to be higher.
- The first line should fit in one line for upto 15 characters in length.
- Company should also come in the same line.

**- Message (instructions)**
1. For QR card - “Scan the QR and receive bitcoin in your Hexa 2.0 bitcoin wallet”
2. For link card - “Click on the link and follow the steps to receive bitcoin in your Hexa 2.0 bitcoin wallet”
Also,
When the link is shared as text then the message that goes before the link should be: “You have received a bitcoin gift from <name>. Click on the link and follow the steps to receive bitcoin in your Hexa 2.0 bitcoin wallet”.  This will be followed by the link on a new line.
The title of this card should be “Gift Sats” instead of Gift Card. The first line should be “You have received a bitcoin gift from <name>”
![File (91)](https://user-images.githubusercontent.com/62699947/145944757-7f84d6d4-f51a-4885-af53-63b7e3d9deeb.jpg)

**- Also the text user enters should allow smileys/ special characters. Currently it crashes**

**Comment by cakesoft-swati** [comment]
- Message (instructions)
1. For QR card - “Scan the QR and receive bitcoin in your Hexa 2.0 bitcoin wallet”
2. For link card - “Click on the link and follow the steps to receive bitcoin in your Hexa 2.0 bitcoin wallet”
Also,
When the link is shared as text then the message that goes before the link should be: “You have received a bitcoin gift from <name>. Click on the link and follow the steps to receive bitcoin in your Hexa 2.0 bitcoin wallet”.  This will be followed by the link on a new line.
The title of this card should be “Gift Sats” instead of Gift Card. The first line should be “You have received a bitcoin gift from <name>”
![File (91)](https://user-images.githubusercontent.com/62699947/145944757-7f84d6d4-f51a-4885-af53-63b7e3d9deeb.jpg)

**Comment by Raheel1258** [comment]
@cakesoft-shashank

**Comment by cakesoft-swati** [comment]
![temp (150)](https://user-images.githubusercontent.com/62699947/146352598-964f860c-29aa-4796-95f6-107576b92dca.jpg)
- The text of the link is going outside the box while sharing.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.66(404)
- Filed another issue regarding theme and text.

**Comment by cakesoft-swati** [comment]
- For link card - “Click on the link and follow the steps to receive bitcoin in your Hexa 2.0 bitcoin wallet”
Also,
When the link is shared as text then the message that goes before the link should be: “You have received a bitcoin gift from . Click on the link and follow the steps to receive bitcoin in your Hexa 2.0 bitcoin wallet”. This will be followed by the link on a new line.
- Like we get in a F&F request “You have a request from F&F..."

**Comment by cakesoft-shashank** [comment]
Duplicate of #5126

**Comment by cakesoft-swati** [comment]
Duplicate of #5126
