### ISSUE TITLE
Gift Reject

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#5078]
Once a gift is rejected, we don't delete it from the server(already implemented). Rather only a notif goes to the source wallet, that the gift has been rejected by xx, if the user reclaims and resend it that's only when the gifts land on a new channel w/ a new link.

Gift status should show that the gift has been rejected, on the gift details page(might already be happening).

**Comment by Parsh** [comment]
Note: Gift post rejection is not visible on any of the tabs at Manage Gift screen

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.66(402)
