### ISSUE TITLE
Issue raised by Swan User

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5080]
Message from Reed in Hexa + Swan Channel (that a user sent him): 

We have a new bug report from user  ID: ba71d6aa-e4c0-4477-ba8c-db3e49afb3b5
“Hi!
By the way, I’m a seed investor in Hexa wallet.
I am unable to connect my Swan account to my Hexa wallet through the link provided within in Hexa.
Here’s the background. I’ve been doing weekly buys on Swan for 1-1/2 years and already had auto-withdrawals set up at the 0.05 threshold to other wallets. I tried the instructions provided within Hexa to link my Swan account and was unable to do so. I deleted all addresses within Swan and turned off auto-withdrawals and still was unable to succeed. I assumed the Hexa link would auto-fill the wallet address into Swan, but I’m unable to see what the address even is. Of course, I do know that I could “manually” connect my “checking account” within Hexa to Swan by using a Receive address from within the app....but newbies might be frustrated that Swan is not automatically linking to Hexa with the designated Swan wallet. By the way, I am using an older iPhone 6S which may be a factor. Let me know if you need any other info.”

Anant: "Yes, would like to know what happens on the Swan side when someone disconnects or deletes old address and then tries to connect Hexa wallet"

Reed has tagged Pablo. Reply expected from Pablo next.

**Comment by cakesoft-shashank** [comment]
No further update, already sent a msg https://bithyve-workspace.slack.com/archives/C02H7PTBXQX/p1641471750000400?thread_ts=1639168951.100100&cid=C02H7PTBXQX

**Comment by cakesoft-shashank** [comment]
Asked again, not reply

**Comment by cakesoft-swati** [comment]
No further updates from swan.Closing this issue for now.
