### ISSUE TITLE
App is crashing on Account Management.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5086]
- After an account has been archived (on one of the test cases)
- iOS and Android both - new install. 
- The app crashes when we click on Account Management from "Settings and more".

**Comment by Parsh** [comment]
fixed by 6c4b6c7f7834e7717efa68deff0461a378616845

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.66(404)
