### ISSUE TITLE
Gift notification.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5088]
- Not receiving "gift denied" notification.
- It is visible in android device but notifications are coming late.
-  And I have not received notification in ios device.

**Comment by Parsh** [comment]
On Android, the notification got delivered perfectly(came in a couple of seconds).

![Screenshot_20211216-162727](https://user-images.githubusercontent.com/17980466/146359563-7e3f6c59-0921-4317-949b-f2fc77ebd0da.jpg)

Someone needs to debug for iOS as I don't have an iPhone(and apparently on simulator notifications don't get delivered).

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.67(406)
