### ISSUE TITLE
Gift status.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5089]
- After the gift decline, the status is not refreshing automatically, for this I had to go back to the F&F screen and re-open that gift detail page.Only then it is showing the Gift Accepted/Rejected status.

**Comment by Parsh** [comment]
We need a pull-down to refresh action on the Manage Gift screen(similar to what we've for F&F)

**Comment by antuz123** [comment]
@Parsh - gifts should be auto refreshed when you go to gifts. You should not need a pull down.

**Comment by Parsh** [comment]
@antuz123  Do we need to do something on this?

The Manage Gift page auto-refreshes once the user land on it but there's no way to refresh Manage Gift page while the user is on it.

**Comment by antuz123** [comment]
Pull down to refresh is needed

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(417)
