### ISSUE TITLE
Gift: Max send

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#5101]
With included fee checked, the app is not able to create a Gift using the complete available to send. A toast appears saying insufficient balance.

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-12-17 at 16 31 16](https://user-images.githubusercontent.com/17980466/146534922-7d2ffc85-1b12-4d4b-9d4f-ee9f721ddecc.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.67(406)
