### ISSUE TITLE
Error message while setting up passcode.

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5102]
When setting up a wallet, if a user enters a different passcode the second time. A message should pop up that says, "Passcode entered is different from the first one." 

![Uploading u{1ed050b} (f686ef3b-01e6-4e18-acca-56489f5f71d5 id=0x7f0a0190 tag=CreateIssueFragment) …]()

**Comment by summikhan11** [comment]
![First time – Login – Errors](https://user-images.githubusercontent.com/85475736/146762957-f140674e-ab4f-4c4d-bce1-991715a8bf24.png)
all errors to show like this.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/b0f25375-b377-4c08-85bf-f2a6c7feca0a/

**Comment by cakesoft-swati** [comment]
- This is still not showing any error message when setting up a wallet, if a user enters a different passcode the second time.
![Screenshot_20220203-143955](https://user-images.githubusercontent.com/62699947/152313416-ceb556af-8818-4701-a810-f8332f52194a.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(465)
