### ISSUE TITLE
7 day validity 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5103]
Default option of - This link is valid for 7 day. 

Option 1 - Let user insect it 
Option 2 - Let user give a different date
Option 3 - always has a validity. No need to change (suggested)

**Comment by Parsh** [comment]
- Validity check happens at the API level(rather than the sender expiring gifts explicitly)
- Once a gift has been expired(time-passed > validity), the sender app does an auto reclaim for such gifts and puts them into the available gift section while the manage gift screen syncs.

**Comment by Parsh** [comment]
@cakesoft-swati Gift validity expires in 10 mins on the Dev app(would help with testing, expiry, and auto-reclaim).

**Comment by antuz123** [comment]
Where to put the text @summikhan11

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/7d0d5473-d062-4f57-b424-b2f6e181c2cc/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.67(406)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(415)
