### ISSUE TITLE
The arrow head should be other way.

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5111]
Right now their directions indicate going backwards. Let's show forward motion.

![Screenshot_20211218-151127_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/146636728-cfb6e1dc-ac8f-4be1-88f4-815e1890a2b4.jpg)

**Comment by summikhan11** [comment]
backup is indicated in a backward direction. not sure forward arrow will make sense

**Comment by ASN-BitHyve** [comment]
When someone is clicking on "Using Recovery Keys" they are about to get into the recovery flow. They are not backing up the wallet. Infact they are recovering a wallet which will be used henceforth.
