### ISSUE TITLE
Text updating during login

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5112]
"... you can recover it..." 

The word "it" needs to be added.

![Screenshot_20211218-151644_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/146636779-7b4d84bd-970c-4d49-a92d-9067e61eb24a.jpg)

**Comment by cakesoft-swati** [comment]
- Unable to see the changes in dev app v2.0.68(411)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(315)
