### ISSUE TITLE
Backup flow messaging

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5116]
Level 2 > Recovery Key 1

"Click the button below after scanning" This line to go between QR Code and the button.

![File (1)](https://user-images.githubusercontent.com/68264080/146641032-0f7e5975-7742-42e4-a75a-3f4138adff17.jpg)

**Comment by ASN-BitHyve** [comment]
Level 2> Recovery Key 2:
Below the QR it should not say f and F Request. It should say "Recovery Key 2"

![File (2)](https://user-images.githubusercontent.com/68264080/146641901-8ca88b87-5a42-434e-9d1d-deebf759f0e9.jpg)

**Comment by ASN-BitHyve** [comment]
Scan QR section: Replace the text highlighted with: "Ask your Contact to scan QR and click Accept"

Share link section: Replace the text highlighted with: " Ask your Contact to click on the link, then click Accept" 

![File (1)](https://user-images.githubusercontent.com/68264080/146642128-35789635-20dc-42fe-ab34-f063c84097a8.jpg)

**Comment by ASN-BitHyve** [comment]
Below the link - The following message should go:

After your Contact accepts above F and F Request, ask them to scan the Approval Key from your Personal Device > Security & Privacy > I am the Keeper of > " <user wallet name> "      


![IMG_0005](https://user-images.githubusercontent.com/68264080/146643213-bb64b63c-006a-4011-99a6-1010ff2cd313.PNG)

**Comment by cakesoft-shashank** [comment]
Not applicable now
