### ISSUE TITLE
Backup flows to be checked 

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5118]
Level 1 - Usual process
Level 2 - Personal Device - Usual process.

Set 1
Level 2 - Recovery Key 2 - Backup with contact
Level 3 - Rec. Key 1 - Backup with contact
Level 3- Rec. Key 2 - Backup with contact

Set 2
Level 2 - Recovery Key 2 - Backup on a device
Level 3 - Rec. Key 1 - Backup with a contact
Level 3- Rec. Key 2 - Backup with contact

Set 3
Level 2 - Recovery Key 2 - Backup using a pdf
Level 3 - Rec. Key 1 - Backup with a contact
Level 3- Rec. Key 2 - Backup with a contact

Set 4
Level 2 - Recovery Key 2 - Backup on a device
Level 3 - Rec. Key 1 - Backup on a device
Level 3- Rec. Key 2 - Backup with a contact.

Set 5:
Level 2 - Recovery Key 2 - Backup with pdf
Level 3 - Rec. Key 1 - Backup on a device
Level 3- Rec. Key 2 - Backup with a pdf

Set 6:
Level 2 - Recovery Key 2 - Backup with pdf
Level 3 - Rec. Key 1 - Backup on a contact
Level 3- Rec. Key 2 - Backup with a pdf

**Comment by antuz123** [comment]
What needs to be checked here?

**Comment by ASN-BitHyve** [comment]
Closing as we've stopped using levels.
