### ISSUE TITLE
Apple buttons hiding "Yes I have shared button" 

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5120]
![Screenshot 2021-12-18 at 8 51 32 PM](https://user-images.githubusercontent.com/68264080/146646452-37c3301f-6695-4265-9ad1-fe6c699a4095.png)

**Comment by Raheel1258** [comment]
@cakesoft-swati can please explain this issue a little bit more?

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(431)
