### ISSUE TITLE
User facing issue in transfering sats from Savings Account in Hexa 1.0

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5124]
Hexa 1 is crashing when the user is trying to move their funds from Savings Account into Hexa 2.0

Username: @chagomanso - Telegram 

https://user-images.githubusercontent.com/68264080/146683117-e10c4f15-9dbe-413b-93a8-3c4ff75bf2da.mp4

Version history:

![IMG_20211219_221413_716.jpg](https://user-images.githubusercontent.com/68264080/146683240-0ac8fc46-a053-4583-97c6-f57d3ce40ddd.jpg)

![IMG_20211219_221418_757.jpg](https://user-images.githubusercontent.com/68264080/146683245-39663914-22c4-4954-897d-5fce22717cf0.jpg)

**Comment by Parsh** [comment]
I didn't see the app crashing in the above video, what I did notice tho is that the app is working really slowly, nor do I see the send journey being completed.

Nevertheless, I've tried sending from the Savings account(Hexa 1) to check whether 2FA based transactions are getting appropriately signed by the Signing Server and the tx went through perfectly fine.

![Screenshot_20220103-154302](https://user-images.githubusercontent.com/17980466/147920585-ccab3a3f-7b91-46ac-9bc4-b8b0cecff0c8.jpg)

![Screenshot_20220103-154316](https://user-images.githubusercontent.com/17980466/147920593-77b28f8a-5db7-4a47-8ff0-30f20a973771.jpg)

![Screenshot_20220103-154329](https://user-images.githubusercontent.com/17980466/147920596-cec9ad98-8d44-4650-90fc-8fa312b77e86.jpg)

**Comment by ASN-BitHyve** [comment]
Abhilash has DMed the user asking them to get on a Zoom call.

**Comment by ASN-BitHyve** [comment]
- User logs into Hexa 1.0
- He doesn't see any account on the home screen. He had to unarchive the accounts to see them.
- He goes to Savings Account. Enters the amount he wants to send. Clicks "Confirm and Proceed". It takes a forbiddingly long time for the app to respond after clicking Confirm and Proceed.
- When the app finally responds it asks the user to enter OTP.
- He goes to his authenticator app to copy the OTP. Hexa 1.0 is now in the background.
- When he comes back to Hexa 1.0 he doesn't see the OTP screen. Instead he's asked to enter passcode again. He enters the passcode and is greeted by the blank homescreen. Thus he's back to square one.

**Comment by antuz123** [comment]
Add the error messages so that we know where the issue is.

**Comment by Parsh** [comment]
> Add the error messages so that we know where the issue is.

Addressed by https://github.com/bithyve/hexa/commit/db2816ca1b7e6ac1f4d35c91c4fed868aec9fe2e

**Comment by ASN-BitHyve** [comment]
User issue resolved.
