### ISSUE TITLE
Message on Gift cards.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5126]
-  Message (instructions)

1.For QR card - “Scan the QR and receive bitcoin in your Hexa 2.0 bitcoin wallet”
2.For link card - “Click on the link and follow the steps to receive bitcoin in your Hexa 2.0 bitcoin wallet”
Also,
- When the link is shared as text then the message that goes before the link should be: “You have received a bitcoin gift from . Click on the link and follow the steps to receive bitcoin in your Hexa 2.0 bitcoin wallet”. This will be followed by the link on a new line.

- Like we get in a F&F request “You have a request from F&F..."

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.67(406)

**Comment by cakesoft-swati** [comment]
Check the messages(instructions) on gift card.There are two different messages for QR and link as mentioned above.

**Comment by antuz123** [comment]
" Scan the QR/ click the link and follow the steps on your Hexa wallet to claim the gift" - this is the message before the user selects link or QR. 

After selection: 
1.For QR card - “Scan the QR and receive bitcoin in your Hexa 2.0 bitcoin wallet”
2.For link card - “Click on the link and follow the steps to receive bitcoin in your Hexa 2.0 bitcoin wallet”

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.71(451)
