### ISSUE TITLE
Post restore:Backup with Contact.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5145]
- If we have backed up the contacts, this option does not show the heading at the time of wallet recovery.
![IMG_0076](https://user-images.githubusercontent.com/62699947/146974519-24e12eea-e59f-4166-a8e9-bee07f904e39.jpg)

**Comment by Parsh** [comment]
Working alright now.

![Simulator Screen Shot - iPhone 12 - 2022-02-03 at 17 16 35](https://user-images.githubusercontent.com/17980466/152337169-a79b8f2c-8306-4793-87af-c8d708c32131.png)

**Comment by cakesoft-swati** [comment]
- Tested this issue on dev app v2.0.70(431) Still it is not showing the heading for conatcts.
![Screenshot_20220203-191643](https://user-images.githubusercontent.com/62699947/152484316-d4f83cd1-c515-49d9-a27d-e33424cde0f3.jpg)

**Comment by Parsh** [comment]
Still works well on the simulator, test a few times. 

![Simulator Screen Shot - iPhone 12 - 2022-02-05 at 14 45 56](https://user-images.githubusercontent.com/17980466/152635922-9fa9a893-d0c5-4f0e-b403-ae595713d412.png)

![Simulator Screen Shot - iPhone 12 - 2022-02-05 at 14 47 16](https://user-images.githubusercontent.com/17980466/152635924-1627afb9-b1ba-4687-87ac-9511521750ad.png)

**Comment by Parsh** [comment]
I've tested the restoration process on the actual device as well, and it worked perfectly.

You can check the keepers in the screenshots and how their names showed up correctly during restoration(as reflected in the video), here: https://github.com/bithyve/hexa/issues/4886#issuecomment-1030609557

**Comment by Parsh** [comment]
We'll need more testing here to actually get to the root scenario which leads to the issue, more information and exact steps might help replicate. @cakesoft-swati
