### ISSUE TITLE
Custom Secret Phrase.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5150]
![image (5)](https://user-images.githubusercontent.com/62699947/147055728-0aa82475-8eeb-4ad2-950f-90064ac080cb.png)

- I had added 21 million in custon secret phrase and got these errors.

![Image from iOS (10)](https://user-images.githubusercontent.com/62699947/147054516-6125dbd2-7601-4670-9a93-09033115f152.jpg)
![Image from iOS (11)](https://user-images.githubusercontent.com/62699947/147054525-2fcd6a5f-98eb-4065-b90f-c77fe788d969.jpg)

**Comment by Parsh** [comment]
Cause: Base 64 encoding of the hint/note(to retain special characters, like spaces), base 64 has / as a valid char and therefore the deeplink was breaking(as it uses / as the separator)
Solution: Hex encoding of hint/note

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.67(408)
