### ISSUE TITLE
Regarding gift message

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5152]
1) I (as a user) create a gift. Write a custom message send it. Click on yes I have shared. Let's say via QR.

2) Come to the sent section. I can see the gift I sent. I want to resend the gift. This time via a link.

3) So I click resend. The message that I previously wrote is not getting caught in this process and I'm given the default message. Thus I will have to rewrite my message.

A user's message should get captured in this scenario.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(415)
