### ISSUE TITLE
Gift link creation is taking a long time

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5153]
In 2.0.65 Android live - I say share via link, the phone's modal opens up to share via different apps, but the link does not get ready. I click anywhere outside the phone's sharing modal to return to Hexa wallet share screen. Still the link hasn't been created. I click the back button. Click the share via link button again. Then the link is instantly visible to me.

**Comment by cakesoft-swati** [comment]
It is not reproducible.
