### ISSUE TITLE
Resend Gift: If the status of the gift hasn't changed we can resend it to multiple people.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5158]
- If I have sent a gift but it is not accepted on the other side, then I can resend that gift.In this case if the user has accepted this gift but the status of the gift has not changed.
- So I can send this same gift to other people also and they are able to accept it.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.67(408)

**Comment by Parsh** [comment]
Pending:

Scenario: When the sender has already entered into the resend flow and the previous link has been used and the gift has been accepted. 
Issue: If the sender then resends the gift, the channel won't be created on the server(therefore the new link is not gonna lead to a gift acceptance from the new recipient), however, the status of the gift would be sent to recipient on the sender's end.
