### ISSUE TITLE
User name swap

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#5161]
<img width="1440" alt="Screenshot 2021-12-22 at 6 05 12 PM" src="https://user-images.githubusercontent.com/17980466/147095210-71a43c3a-d8ce-4166-8bf8-46ccfa5a4ea6.png">

@Raheel Ahmed @Shashank This change should default the name to username(and if username is not present then use the wallet name)

Note: one useEffect has been broken into two separate useEffects

**Comment by Parsh** [comment]
This is the code; 

 useEffect( () => {
    setDropdownBoxList( ThemeList )
  }, [] )

  useEffect( () => {
    setName( wallet.userName? wallet.userName: wallet.walletName )
  }, [ wallet.walletName, wallet.userName ] )

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.67(408)

**Comment by cakesoft-swati** [comment]
- Now it is showing wallet name as a user name on Gift detail screen.After that I changed the wallet name but user name was still same as old wallet name.In case of F&F it is not showing user name on Send screen. and on acceptance gift card it is showing Changed wallet name.
- And in case of other scenarios it was showing user name on both Enetr gift details screen and send screen.

**Comment by Raheel1258** [comment]
@cakesoft-swati, closing this one as discussed on call with @antuz123 sir. the flow is working fine.

**Comment by cakesoft-swati** [comment]
- In case of F&F it is not showing user name on Send Gift screen.
- Tested on dev app v2.0.68(410)
![temp (163)](https://user-images.githubusercontent.com/62699947/147821338-4a125630-30d8-417d-9e56-476c0967d199.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(417)
