### ISSUE TITLE
Share OTP.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5167]
- If we click on "Show OTP" after sharing the link/QR then it pops up Share OTP modal.If we click proceed button then it came back to the "Enter gift details screen" and again I had to do the same procedure.
- In case of "Custom secret phrase" if we click Show OTP button after sharing the link/QR it came back to the send screen.
-  we need to take out the proceed button

**Comment by antuz123** [comment]
Remove the proceed button from the modal.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.67(409)
