### ISSUE TITLE
UI issues for Advanced options.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5168]
![Screenshot_20211222-233350](https://user-images.githubusercontent.com/62699947/147136370-348aa65e-3347-4680-9dda-331d377f3b94.jpg)
- Long OTP is going to another line.

![Slack Image (2021-12-22_23-46-42-451)](https://user-images.githubusercontent.com/62699947/147138092-78db5010-c1a9-4a81-a620-0d9921acceaa.jpg)
- Email Id is getting cut.

**Comment by Raheel1258** [comment]
@cakesoft-swati Duplicate ticket
