### ISSUE TITLE
Text Going haywire - Reported by a user on Twitter

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5177]
https://twitter.com/HexaWallet/status/1474027693897252866

Tagging @summikhan11 to observe.

**Comment by summikhan11** [comment]
the currency switch is missing the symbol too.

**Comment by Raheel1258** [comment]
@cakesoft-swati unable to reproduce the bug on iPhone 12. ios version, 14.5

**Comment by summikhan11** [comment]
what is needed from me?

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(421)
