### ISSUE TITLE
App was crashing while trying to accept gift.

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5179]
The user has iphone 11 Pro and ios is 15.1.

Don't know if it was an upgraded app. 

Abhilash sent a gift and the app crashed when gift link was clicked. 

Abhilash requested the user to download and setup a new wallet, which the user did. Clicked on the gift link, was able to accept easily.

Anant's comment: "The new links are not recognised by the old apps that have been upgraded."

**Comment by Parsh** [comment]
@cakesoft-swati Can you please check and confirm `The new links are not recognized by the old apps that have been upgraded `?

**Comment by cakesoft-swati** [comment]
- sender side app version history:upgraded app from 2.0.6(391)to 2.0.65(393) to 2.0.67(409)
- eceiver side app version history:upgraded app from 2.0.0(361)to 2.0.67(408)
- By clicking on the receiver side link, the app opened and crashed immediately.

**Comment by cakesoft-swati** [comment]
- Unable to reroduce this issue on dev app v2.0.80(485)
