### ISSUE TITLE
Bug in version history

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5183]
https://user-images.githubusercontent.com/68264080/147328567-6d893c7e-484b-44dc-a61f-1c4904962499.mp4

**Comment by cakesoft-swati** [comment]
![Screenshot_20220118-143638](https://user-images.githubusercontent.com/62699947/149907002-15a2e189-58e6-446b-b32c-d23c0ad9e5d7.jpg)
- In case of upgrade+restore, the version history page is showing blank.
