### ISSUE TITLE
Post recovery:Unable to send from Savings account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5188]
- Not able to send from Restored Savings account.
- Hexa 2.0 
![Image from iOS (12)](https://user-images.githubusercontent.com/62699947/148063818-e64cb693-43d4-43c8-9e76-32abbfe35296.jpg)

**Comment by Parsh** [comment]
@cakesoft-swati Please check with @antuz123 and add more details to this issue.

**Comment by antuz123** [comment]
after entering the token, nothing happens.

**Comment by Parsh** [comment]
Unable to replicate it. The above info doesn't really help.

**Comment by cakesoft-swati** [comment]
- Unable to replicate the above issue.Verified this issue on dev app v2.0.69(428)
