### ISSUE TITLE
Show selected advanced option on the screen where Gift theme is selected.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5190]
- The advanced option selected by the user should also appear on the screen where Gift theme is selected.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/bd2d2f2b-a93a-405e-b154-5cb41209d297/

**Comment by cakesoft-swati** [comment]
- Unable to see advanced options on the screen where the gift theme is selected by the user.
![temp (165)](https://user-images.githubusercontent.com/62699947/148368144-ab49d6b2-7226-4797-999a-a43d073ac727.jpg)

**Comment by Raheel1258** [comment]
@cakesoft-swati, it is fixed but the code is not merged yet.

**Comment by cakesoft-swati** [comment]
- It is not showing the selected advanced option,by default it is showing Custom phrase.
- We need to show the selected advanced option.
- Tested on dev app v2.0.68(415)

**Comment by cakesoft-swati** [comment]
- For now we are showing advanced as a heading instead of selected advanced option.
- Verifed this issue on dev app v2.0.68(417)
