### ISSUE TITLE
Cross compatibility issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5191]
- Live app 2.0.65 crashes when I try to accept secret phrase (or any advanced option) gift from app v2.0.67.
- Also When I try to scan the F&F request,app crashes.

**Comment by Parsh** [comment]
@cakesoft-swati Can you please try to replicate this and provide me with more details(if this is replicable)?

**Comment by cakesoft-swati** [comment]
- Unable to recreate the above issue on same version.
