### ISSUE TITLE
No need of 2 CTA's for the same purpose.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5200]
- Don't need 2 CTA's with the same purpose. maintain "return" on the keyboard in case the user wants to move to the next line.
![original (10)](https://user-images.githubusercontent.com/62699947/147657235-59d5b943-301a-4d0a-952b-7f5e7c95eb2d.jpg)

**Comment by antuz123** [comment]
Change done to - return and disable after one return

**Comment by antuz123** [comment]
Show return button disabled

**Comment by antuz123** [comment]
Replace the button where "Done" means the keyboard goes down.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(414)
