### ISSUE TITLE
Welcome message to new followers

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5201]
1) To go on TG
2) To go on Twitter a) Anant's profile b) Hexa profile

**Comment by ASN-BitHyve** [comment]
"Hello everyone and wish you all a very happy new year! I'm Anant, Co-founder/CEO of the Hexa app. This message is a quick introduction about us to the 150 or so new people to our telegram. I welcome you all. 

Hexa is a self-custodial, bitcoin only wallet. Our mission is to create the best entry level wallet for newcomers to bitcoin, while satisfying the expectations of seasoned bitcoiners. The feedback we've received over the last month or so has been extremely valuable. Based on your feedback, we're in the process of a major overhaul of our backup system. Plus the wallet will have lightning soon.

I have 2 asks: 1) Please play around with the wallet and continue to share feedback. 2) Please rate and review us on the App/Play store. Helps immensely with the algorithms.

Thank you SO much for trying out Hexa.
With best regards,
Anant"

**Comment by antuz123** [comment]
Done
