### ISSUE TITLE
AGSP 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5204]
Putting all the points that we have discussed for an App Generated Strong Password, in one place 

**During wallet creation,** 

1. The user is given the option to:
- Use an App Generated Strong Password (akin to Long OTP for Gifts but in Apple format xxxxxx-xxxxxx-xxxxxx). Subtext: "Most secure"
- Use their own password (the way it is now) Subtext: "Provide your own"
- Use a security Q/A (the way it is now) Subtext: "Most memorable"
- Skip initial cloud backup Subtext: "Can be set up later from Wallet Security" 

2. AGSP is visible on the screen here and is the default. A checksum is also put into the AGSP such that you know if a AGSP is incorrect 
3. If the user choses this option, and goes next, a popup displaying the AGSP again and asking the user to "Make sure you have noted down the Strong Password and secured it. It may also be a good idea to make more than one copy of the Strong Password". 
4. The user can simply confirm and lands on the Home Page

1.a Each of the option in 1 needs to have its own explanation - so may be a (i) for every option explaining more details

**Comment by antuz123** [comment]
For the existing users (migration script): 

1. When users are upgrading to the new version from any of the old version 
2. Check if they have a Security Question and Answer in place 
3. If they have then, suggest with a message that they consider using AGSP. They can agree or decline 
4. Decline, no action 
5. Accept, ask them to copy the AGSP and keep it secure like in the wallet creation step 
6. The encryption mechanism of their existing shares is changed from the Security Q/A to AGSP 

2.a - if they don't have a SQ/A in place - then if the user goes in to set the password, they will get the same screen as they got during wallet creation which has the AGSP option (same as the behaviour today but with additional option)

**Comment by antuz123** [comment]
Ability to change to AGSP/ any encryption key (anytime) 

1. The user can simply go into the Password option and change the encryption used 
2. They are taken back to the same options screen and the process continues based on the change they have made (similar to migration flow)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/9ef1c605-d4f3-4e77-bd8d-eea60404d912

**Comment by antuz123** [comment]
@summikhan11 - AGSP does not replace the login passcode but more at the Security Q/A step. From the UX it seems to be at the login passcode step. Also did not understand the screen where 4 digit passcodes are suggested.

**Comment by antuz123** [comment]
AGSP is numbers + lower case + upper case and can be copied on touch

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/c7aa2e89-3843-4d9e-854c-85a45611f5e1/

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/c6895a05-a4ff-43e4-86dd-e7382b1c9f86/

@antuz123 can you comment the content for Know more screens, I'll make illustrations based on the space available

**Comment by summikhan11** [comment]
change encryption : 
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/ed9c68da-85ba-4c8d-a2e8-a00f64d9ba81/

**Comment by summikhan11** [comment]
link is updated @cakesoft-shashank 

@antuz123 need content on this screen and the next
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/

**Comment by cakesoft-swati** [comment]
@cakesoft-shashank Here https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/bf43224d-bcdf-468a-8fbd-e9d89ea21cd5/ copy icon is suggested which is not in app.

**Comment by cakesoft-swati** [comment]
- Put this note on New Wallet - AGSP
Note: If you lose this, you will not be able to access the wallet backup or reset the Login Passcode. It may be a good idea to secure more than one copy of the Strong Password
Put this note on New Wallet - Step 2 Encryption
Note: If you forget this, you will not be able to access the wallet backup or reset the Login Passcode. It may be a good idea to secure more than one copy of the Encryption Passphrase

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(417)
