### ISSUE TITLE
Using Encryption Key to reset passcode

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5206]
When the user forgets their passcode, they should be able to enter AGSP (or any other password mechanism they have chosen) to reset the pin 

Once reset, they are logged into the wallet like normal 

Also, need to understand where is the pin stored and the state of the app as that may change. Mention issue number here https://github.com/bithyve/hexa/issues/5094

Also is there an upgrade script needed?

**Comment by summikhan11** [comment]
what happens when the user wants to login again and still doesn't the remember the passcode?

Post entering the AGSP (or other mechanism the user has selected) they should be asked to set a new passcode (like we do in emails)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/968e3af5-dede-4c37-b9e7-a87806515170/

scroll to find all options

**Comment by summikhan11** [comment]
link updated

**Comment by cakesoft-swati** [comment]
- Skip initial cloud backup:In case of skip backup,app crashes when we click on 'Forgot password'.

**Comment by cakesoft-swati** [comment]
- Following issues are still pending:
- After the "Forgot Passcode" process, if we go directly to the Settings> Manage Passcode screen and enter an existing passcode, it directly shows the "Passcode successfully changed" screen. The first attempt does not show the "Enter new passcode" screen but the second attempt shows the correct flow.

https://user-images.githubusercontent.com/62699947/148928536-a67a999c-8737-4e41-96cb-927444799131.mp4

- If I forgot pin and also I forgot the passphrase, that I did at the time of setting up the wallet then it shows "Password is incorrect" message at the time of enter that passphrase.But after 3 trial it again ask me for pin and if I enetr wrong pin then it is not showing the "forgot passcode" option.For this I have to kill the app and then on 3 wrong pin it shows the "Forgot passcode" option.

**Comment by cakesoft-swati** [comment]
- Verified this issue on live app v2.0.68(421)
