### ISSUE TITLE
Redux Persist: State Migration

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#5210]
We need a [standard way](https://github.com/rt2zz/redux-persist/blob/master/docs/migrations.md) to migrate from one version of the redux store to another in order to avoid redux-persist overriding. This would various issues moving forward such as #5179.

Reference:
[How to use Redux Persist when migrating your states](https://www.freecodecamp.org/news/how-to-use-redux-persist-when-migrating-your-states-a5dee16b5ead/)
[Chaning structure of your persisted store](https://blog.bam.tech/developer-news/redux-persist-how-it-works-and-how-to-change-the-structure-of-your-persisted-store)

**Comment by Parsh** [comment]
@antuz123 I'll need some help from @cakesoft-shashank as I'm not able to figure out exactly how to go about doing this.

**Comment by Parsh** [comment]
Addressed by #5408

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
