### ISSUE TITLE
User unable to purchase sats from Wyre

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5214]
He says his app is up-to-date.

"This occurs after I use wyre paying with Apple pay" he says.

(Username: Rick -TG)

![IMG_20220105_104200_426.jpg](https://user-images.githubusercontent.com/68264080/148163828-a83d29cd-e00d-4b6b-8268-f10d20897e08.jpg)

**Comment by cakesoft-shashank** [comment]
Here app deeplinks with https://hexawallet.io/dev/wyre/failed/1641456422454, which is not processed yet

**Comment by antuz123** [comment]
Handle the issue in the app

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev
