### ISSUE TITLE
Send/Create-Gift: Tx-mempool-conflict

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#5215]
The following error props up during the send and create gift flow. 

![Screenshot_2022-01-03-19-30-23-758_io hexawallet hexa development](https://user-images.githubusercontent.com/17980466/148189479-ae0a7de6-ae47-4c3d-8992-efb9ece41cd7.jpg)

Reported by @Raheel1258 & @cakesoft-swati

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(415)
