### ISSUE TITLE
Change Contact:This flow is not working for Keeper.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5219]
https://user-images.githubusercontent.com/62699947/152099243-47d21e52-95d2-4561-92be-99c69dadf9ac.mp4

- I cliked on Change and select another contact and send a request to that contact and came back to the "Security Center" page but that contact share was not showing the changed contact name it was still showing the old contact name.

**Comment by antuz123** [comment]
@cakesoft-swati - what is not working here?

**Comment by Parsh** [comment]
@cakesoft-swati We need more information here.

**Comment by Parsh** [comment]
This is not just about the contact name not changing on the Manage Backup screen, the whole change contact functionality doesn't seem to work in the current version.

@cakesoft-swati Can you confirm that this works on the previous releases?

**Comment by cakesoft-swati** [comment]
- Change contact fuctionality was breaking in prevoius verion so we moved it in 70.
- It was giving "Failed to add Keeper/Contact" error.

**Comment by cakesoft-swati** [comment]
- Changed contact is not getting confirmed on Security center page.It is showing green dot in F&F list on both sides  but still showing yellow circle(unconfirmed) on security center page.
![temp (216)](https://user-images.githubusercontent.com/62699947/163818149-9289731e-1939-47a9-a4b6-6aa2ca3fa6c9.jpg)
![temp (217)](https://user-images.githubusercontent.com/62699947/163818157-cfb927ee-af0f-4800-bd6f-e33d5695c094.jpg)
