### ISSUE TITLE
UX getting messed up in Android (Default font size)

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5222]
![Screenshot_20220106-171741_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/148378544-01a52a84-8aa1-4bd3-8e0b-733b42eacfb7.jpg)

**Comment by ASN-BitHyve** [comment]
I am told that UI is not completed yet as on 6.01.22. @cakesoft-swati to test and close at an appropriate time.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(415)
