### ISSUE TITLE
Level 1 > Encryption password:History page is showing different heading and text.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5224]
![File (102)](https://user-images.githubusercontent.com/62699947/148369412-08198e80-d4d3-456f-add4-a5b4bdd3e569.jpg)
![File (103)](https://user-images.githubusercontent.com/62699947/148369419-55452fb8-b2b9-471f-b50d-f8ec64278924.jpg)
- I had selected the app generated password.But on level 1 history page it is showing "Encryption password" as a heading and content on history page is "Security Question created" and "Security Questions confirmed".It should be same as what ever was used for encryption

**Comment by ASN-BitHyve** [comment]
Closing as we're not doing levels anymore
