### ISSUE TITLE
User feedback regarding Donation Account.

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5225]
![photo6289567855523507692](https://user-images.githubusercontent.com/68264080/150290316-26b93696-8f50-41e4-8933-a1a9e790fb18.jpg)

**Comment by ASN-BitHyve** [comment]
The same user, while raising the issue also complimented us: "It’s a great app by the way it has almost everything I’d want from a bitcoin wallet.  Your team has nailed this."

**Comment by ASN-BitHyve** [comment]
User: Blackhistorybuff 
Platform: Twitter DMs

**Comment by ASN-BitHyve** [comment]
Further Feedback from user:

From a user point of view what I would want to see is:

- the name of the person who donated or something that told me they wished to be kept anonymous. 

"If the donate button is going to work this way I think you need to give the owner of the link the ability to remove comments. The page I run is dedicated to sharing black history and trust me when I say that things gets incredibly nasty when it comes to comments sometimes.  I would definitely want the ability to remove a comment I didn’t like."

**Comment by ASN-BitHyve** [comment]
Tumul to Copy/paste this issue into into Campaigns 0.0.5.

**Comment by tumul-vikash** [comment]
copy/paste done
please close
