### ISSUE TITLE
Password strength checker

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5246]
Need a way to check the strength of a password entered on a field

**Comment by antuz123** [comment]
Introduce it for the Own Password option for now.

**Comment by antuz123** [comment]
Also need the "Password field" to be autofill enabled such that password managers like Last Pass/ Apple Key Chain can be used if the user wants.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/e2e7db4c-94fb-4479-be60-c32d502f9dd4/

@ASN-BitHyve lets have text for all scenarios? (can have two for each) limit to 3 words max

Red - Easily Guessable
Yellow - "Could be stronger"
Green - "Strong Password"

**Comment by cakesoft-swati** [comment]
- Verified this isue on dev app v2.0.70(431)
