### ISSUE TITLE
Font and screens - mismatch

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5247]
![Screenshot_20220111-190304](https://user-images.githubusercontent.com/62699947/148956432-27173b2b-089b-4bfa-8883-c55dd3221dec.jpg)

![temp (168)](https://user-images.githubusercontent.com/62699947/148956491-3b0a7d06-c53a-4727-8b65-e89f8e514dba.jpg)

![Screenshot_20220112-142058](https://user-images.githubusercontent.com/62699947/149096864-13bc2dc0-04ff-4090-928e-2723a24176c4.jpg)

![Screenshot_20220112-155154](https://user-images.githubusercontent.com/62699947/149136634-979f25e5-67c0-4b76-a3bc-bae7cd751409.jpg)

- Check the font size,colour.Text is going in second line.

**Comment by cakesoft-swati** [comment]
![Screenshot_20220112-155154](https://user-images.githubusercontent.com/62699947/149136634-979f25e5-67c0-4b76-a3bc-bae7cd751409.jpg)
- Still the font size and style looks different than other screen n modal.
- Tested on dev app v2.0.68(417)

**Comment by antuz123** [comment]
Look at all the new screens for 68 and match for iOS and Android

**Comment by cakesoft-swati** [comment]
![Screenshot_20220117-142603](https://user-images.githubusercontent.com/62699947/149743393-8b374fbc-9997-49f6-88e7-e3a102c97b29.jpg)
- Here when I click on copy button this button "Use strong passcode" is going down like this  and after few seconds it comes up.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(419)
