### ISSUE TITLE
Personal Device backup not getting reconfirmed.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5255]
- Personal Device backup not getting reconfirmed.
![tempFileForShare_20220112-170931](https://user-images.githubusercontent.com/62699947/149145437-c19c72e7-e57a-4227-9d94-49ec134efc8e.jpg)

**Comment by Parsh** [comment]
Unable to replicate, the personal device backup got reconfirmed after logging into the keeper app.

![Simulator Screen Shot - iPhone 11 Pro Max - 2022-01-13 at 15 42 35](https://user-images.githubusercontent.com/17980466/149314570-8ff11630-5c42-463e-b45a-0f0995386437.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(431)
