### ISSUE TITLE
Change EK

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5259]
Cannot change EK unless you change the shards if shards are also encrypted. 

Else hide the option

**Comment by cakesoft-shashank** [comment]
- [ ] Add an alert to let user know the impact of enc password change: reshare shares
- [ ] Expire existing level 2,3 shares and re-encrypt it in the same process

**Comment by Parsh** [comment]
Not relevant at this point in time(shifting to Hexa-Keeper).
