### ISSUE TITLE
Security & Privacy :Text change.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5260]
![temp (171)](https://user-images.githubusercontent.com/62699947/149278562-799f4d30-2eca-4ef6-abd9-428a30a3e868.jpg)

- Change the name of Security & Privacy tab to **Security Center.**
@summikhan11 please make changes in design too.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.68(418)

**Comment by summikhan11** [comment]
updated 
https://xd.adobe.com/view/3c76a519-ed48-4944-a7a5-026a2aca5a6d-6925/
