### ISSUE TITLE
The link of the app to be shifted from Legacy to Hexa 2.0

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5275]
https://hexawallet.io/donation/?donationid=adf6daace9ea94b

**Comment by akshaytikle** [comment]
I need cpanel details for this, i don't have cpanel details.

**Comment by ASN-BitHyve** [comment]
@cakesoft-utkarsh please help here.

**Comment by cakesoft-utkarsh** [comment]
I have WordPress access, not CPanel.
@akshaytikle Donation web pages are on WordPress under the file system. 
Please ping me if you need help locating these on WP. 

For any other queries ping me.
