### ISSUE TITLE
Donation account: UX issues.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5288]
- The bitcoin symbol is looking hazy.
![File (111)](https://user-images.githubusercontent.com/62699947/149909618-57e158bd-7e81-48a7-88a1-78dbee7b6247.jpg)

- Donors’ Twitter images were supposed to look staggered
![File (112)](https://user-images.githubusercontent.com/62699947/149909765-a8726486-edc3-4d10-959c-b80983baa9bf.jpg)

- In Android the images are looking horizontal, while in Apple it's looking vertical.
![tempFileForShare_20220118-150529](https://user-images.githubusercontent.com/62699947/149913610-1dbb84ff-6f3b-4626-a2a7-d15b1f60a1b0.jpg)

-  In iPhone 6 the word optional is getting cut.
![File (110)](https://user-images.githubusercontent.com/62699947/149908453-55b81ebe-3423-4c89-b4bb-f72843ccc8bb.jpg)

- The Donation Amount not updating:
 " When someone donates sats, the web page gets updated with the thank you message. But to see the latest sats total, the donor will have to refresh her/his page which isn't ideal. I as a donor, should immediately be able to see my contribution added to the total. So when the web page updates to the thankyou message. The Donation total should also update."

**Comment by akshay8551** [comment]
@cakesoft-swati  Please note before testing, some following points(issues) ignored:
- Donors’ Twitter images were supposed to look staggered
- In Android the images are looking horizontal, while in Apple it's looking vertical.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(465)
