### ISSUE TITLE
Version history:The version history page is showing blank after Upgrade and then restore.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5289]
- ![Screenshot_20220118-143638](https://user-images.githubusercontent.com/62699947/149907002-15a2e189-58e6-446b-b32c-d23c0ad9e5d7.jpg)
- In case of upgrade+restore, the version history page is showing blank.
- I upgraded the dev app v2.0.67(409) to 2.0.68(419) and then I restored the app.

**Comment by ASN-BitHyve** [comment]
@Deveshshankar to test and close.

**Comment by Deveshshankar** [comment]
completed
