### ISSUE TITLE
Step 2 wallet creation note should be followed by VD.

### ISSUE THREAD

**Issue by Raheel1258** [bithyve/hexa#5306]
In designs.
<img width="233" alt="Screenshot 2022-01-20 at 4 04 21 PM" src="https://user-images.githubusercontent.com/28229449/150327750-c4facc8c-3350-488f-99d1-8e9e05108fba.png">

In app.
![Simulator Screen Shot - iPhone 12 Pro Max - 2022-01-20 at 16 01 27](https://user-images.githubusercontent.com/28229449/150327826-e895a478-8be2-491f-a2d4-2a0e66807652.png)

**Comment by cakesoft-swati** [comment]
- Still it is not followed by the VD.
In XD
<img width="233" alt="Screenshot 2022-01-20 at 4 04 21 PM" src="https://user-images.githubusercontent.com/28229449/150327750-c4facc8c-3350-488f-99d1-8e9e05108fba.png">

In App
![Screenshot_20220203-140727](https://user-images.githubusercontent.com/62699947/152308497-1fb19ea3-27e5-40db-a90b-585d0cbed7d2.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(433)
