### ISSUE TITLE
Lightning and on-chain Home Screen variation

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#5307]
@cakesoft-shashank @violet360 
please describe the issue in detail here for @antuz123 

UI that Zeus currently has
![IMG_87726E5748E0-1](https://user-images.githubusercontent.com/85475736/150337564-b192223b-8dcb-4785-a1fd-2eea1237c07e.jpeg)

UI that I've worked off of
![First app open view](https://user-images.githubusercontent.com/85475736/150337763-b721edc2-ddb5-4e83-ad45-65243af785f4.png)

UI that ive created based on the second screen
![Zeus Account – Lightning](https://user-images.githubusercontent.com/85475736/150337833-f2fd51f4-2bc7-4456-a2f1-033bbd8f79cb.png)
![Zeus Account – On Chain Selected](https://user-images.githubusercontent.com/85475736/150337845-4b50d02a-cef7-47bc-a984-1635b972e2ab.png)

**Comment by cakesoft-shashank** [comment]
@summikhan11 there is no change the screen just need these options/flow
- Need an indicator on account details to display chainType (mainnet, testnet, regtest)
- Redesign in receive screen to have on chain and off chan QR with option to add amount and note
- Separate settings page
- In LN settings there should be an option for channels
- Option to create channels either from channels or from settings

**Comment by cakesoft-shashank** [comment]
![simulator_screenshot_64DC3AC7-3302-4D4A-807E-1E0C54AE8F6C](https://user-images.githubusercontent.com/50690016/152770262-5dde9652-eb78-4b81-a551-19ad3af3910f.png)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/1b7355c9-e125-47f4-895c-1a6d1d5dc438-4e20/screen/8e4d140f-bc7f-411c-871a-5a659f004769/

**Comment by summikhan11** [comment]
@cakesoft-shashank can you attach a screenshot for the qr screen too.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(438)
