### ISSUE TITLE
Icons should depict the button

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5308]
"Donation Total" and "Pause Donation" buttons should have corresponding icons.  ![Donation](https://user-images.githubusercontent.com/68264080/150459138-692dfdcf-dd1d-4a0e-9a79-c14b1ee8c0ab.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/319a403f-183f-4eb6-bdbe-9cd9dc9c4450-64c9/screen/dd95cdec-f34d-4f99-8e01-376fe8bd1602/

https://xd.adobe.com/view/319a403f-183f-4eb6-bdbe-9cd9dc9c4450-64c9/screen/38c286c2-3c34-4a36-a030-bb3203cec88d/

**Comment by cakesoft-swati** [comment]
- Icons are not same as mentioned in xd link.
- Tested on dev app v2.0.75(455)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(465)
