### ISSUE TITLE
Accounts related issue

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#5309]
- [ ]  The pre-hidden account tiles are not visible in one of the apps(even in account management's show-all, the accounts aren't visible).
- [ ] Also the home QR scanner crashes immediately(it uses the default checking account to send but as the default checking account is not available, it crashes).
- [ ] When the above app is restored on another device, the accounts are now visible, however, the send from the savings account was failing with the `Transaction Signing failed: could not find private key` error.
- [ ] On hard-refreshing the savings accounts(as the hard-refresh fixed the send error from Checking), it showed zero balance with all transactions showing zero amount(whether it was incoming or outgoing) and many transactions were duplicate(same txid). 
- [ ] On the restored app, the sweep flow also doesn't seem to work, it gets stuck after scanning the approval key and never navigates to the send screen.

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
