### ISSUE TITLE
Building Hexa on M1

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#5316]
Building Hexa on Apple M1 fails with the following error.

<img width="1440" alt="Screenshot 2022-01-24 at 7 25 04 AM" src="https://user-images.githubusercontent.com/17980466/150770176-8f89020e-217f-4c6b-a784-f1a31b97ca90.png">

**Comment by Parsh** [comment]
Steps to build Hexa on M1
- yarn install
- import UIKit to iCloud.m `#import <UIKit/UIKit.h>`
- update Podfile as per the [troubleshooting guide](https://github.com/facebook/react-native/issues/31941)

<img width="1440" alt="Screenshot 2022-01-25 at 9 59 06 AM" src="https://user-images.githubusercontent.com/17980466/150914573-a2e8855a-8348-4234-ba63-e2efb6d04279.png">

<img width="1440" alt="Screenshot 2022-01-25 at 9 59 16 AM" src="https://user-images.githubusercontent.com/17980466/150914587-7ae5129e-55c9-4564-9b1b-9865839e5e75.png">

**Comment by cakesoft-swati** [comment]
Closing this issue as discussed with dev.
