### ISSUE TITLE
Hexa Logo file for Welcome kits

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5322]
[Logo file.pdf](https://github.com/bithyve/hexa/files/7932397/Logo.file.pdf)

**Comment by summikhan11** [comment]
@ASN-BitHyve can you specify what products from the pdf do we need the logo for, also if it is print or embroidery

**Comment by ASN-BitHyve** [comment]
@summikhan11 all the five products. And it is print. Not embroidery.

**Comment by summikhan11** [comment]
@ASN-BitHyve should we wait for the re-branding?

**Comment by ASN-BitHyve** [comment]
@summikhan11 I asked Prasad about it and he said that we'll send these now to the new joinees and once re-branding is done we'll order for the entire team.

**Comment by summikhan11** [comment]
[Welcome Kit Logos.pdf](https://github.com/bithyve/hexa/files/8000221/Welcome.Kit.Logos.pdf)



@ASN-BitHyve

**Comment by Praasd** [comment]
> [Welcome Kit Logos.pdf](https://github.com/bithyve/hexa/files/8000221/Welcome.Kit.Logos.pdf)
> 
> @ASN-BitHyve

@summikhan11 is there a possibility to get the logos in jpg.

**Comment by ASN-BitHyve** [comment]
Received.
