### ISSUE TITLE
Sweep Funds:This flow is not working.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5328]
- In case of Sweep Fund flow when we scan the exit/approval key nothing happens after that just the scanner closes and comes back to the previous page.

https://user-images.githubusercontent.com/62699947/151396080-1f6afe40-f6e0-4e46-8d0e-d75394e18094.mp4

- **After restore:** When we go to do sweep fund  and we scan the approval key then app crashes.

**Comment by Parsh** [comment]
Not able to replicate it.

The sweep funds flow worked on both my simulator and device in both setups; fresh and restored.

![Simulator Screen Shot - iPhone 12 - 2022-01-28 at 09 58 07](https://user-images.githubusercontent.com/17980466/151487398-de381b47-e4e0-4439-b975-1b69ab20c700.png)

**Comment by antuz123** [comment]
@cakesoft-swati - is this an upgraded app?

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(431)
