### ISSUE TITLE
Secondary Device UI chnages.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#534]
Following are some UI changes for Secondary device on Manage Backup screen:
-Use Keeper Device instead of Secondary Device. 
-Initial subtitle should be, “Another device running Hexa app that you own”.
- When the setup of that device is done, the subtitle should change to show the name of that device 
  like “Anant iPad Wallet”
![secondary device](https://user-images.githubusercontent.com/62699947/82323267-6f34f400-99f5-11ea-86f4-07345541e70c.jpg)

-We need a Know More for all types of Keepers.Plus a help screen opens up when you come for the first time.
![SD_know more](https://user-images.githubusercontent.com/62699947/82442649-af5fa980-9abd-11ea-818c-10e98d8ca8fe.jpg)

**Comment by shreyasnisal** [comment]
QR code loading issue is preventing testing subtitle text based on backup state
