### ISSUE TITLE
User of Hexa 1.0 facing issues to transfer sats from Savings Account

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5345]
OS: Android
Hexa 1 version: 1.7.8

Version History: (2 images below)
![photo6314308215768199501](https://user-images.githubusercontent.com/68264080/151912724-4d90c5c1-d998-4b69-9ec4-33743dc3ba0e.jpg)

![photo6314126542946545247](https://user-images.githubusercontent.com/68264080/151912736-11a45d3e-95d4-4332-b89f-2e8715cf2deb.jpg)

User tried to transfer 0.5 BTC from his Savings Account to another wallet (Presumable Hexa 2.0 as I had spoken about it). He couldn't send it. 

Then he sent 0.1 BTC and 0.2 BTC. The transactions were successful.

The user says, " I know there is around 20,000,000 sats but its showing 45,000,000"

![photo6323108839980904466](https://user-images.githubusercontent.com/68264080/151912871-e666e712-ada9-496c-8c86-aec4766560d0.jpg)

Thus we have 2 issues to resolve:
1) Make sure that Hexa 1.0 is showing the latest balance correctly.
2) Help the user transfer remaining sats from his Savings Account out of Hexa 1.0

**Comment by Parsh** [comment]
@cakesoft-swati Need to test whether the refresh is working properly on the device(pull down to refresh).

**Comment by cakesoft-swati** [comment]
@Parsh Refresh is working properly.

**Comment by Parsh** [comment]
Waiting for user feedback.

**Comment by ASN-BitHyve** [comment]
Have dropped him a text with Parsh's exact request

**Comment by ASN-BitHyve** [comment]
Issue resolved.
