### ISSUE TITLE
New Wallet creation

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#5349]
https://xd.adobe.com/view/d7c94aa6-eb66-403c-8246-4cfe87d6bab9-829a/

**Comment by antuz123** [comment]
Name Screen: 

1. Allow number for wallet name so the message is not needed @summikhan11
2. Only allow a certain length. @summikhan11 - what is the max length we should allow
3. I am new is not selected by default 

Password Screen: 
1. Follow the UX - cloud backup is selected by default 

Wallet Creation logic: 
1. If "I am new selected", then the Test Account will be provided else not. (It can either be hidden or not initialised at all - check with @parsh). The user can Add the Test Account from the Add Account option 
2. If cloud backup is un-selected, then the backup is not done and the message is shown on the top that the wallet is not backed up (existing logic make sure we connect to it) - check with Shashank

**Comment by cakesoft-swati** [comment]
- Unable to see the above changes in dev app v 2.0.75(461)

**Comment by cakesoft-swati** [comment]
- Unable to see the above changes in dev app v2.0.75(463).

**Comment by cakesoft-swati** [comment]
- we removed the above screens for now.
