### ISSUE TITLE
Channel Detail Screen UI

### ISSUE THREAD

**Issue by Raheel1258** [bithyve/hexa#5357]
Make Channel Detail Screen Ui according to designs.

**Comment by antuz123** [comment]
@cakesoft-shashank - what kind of screen do you need?

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/1b7355c9-e125-47f4-895c-1a6d1d5dc438-4e20/screen/bc4d8ef6-d5d0-4f14-8db7-d91ad0e76be3/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(438)
