### ISSUE TITLE
'Split screen' feature in android is breaking the UI 

### ISSUE THREAD

**Issue by GourabSanyal** [bithyve/hexa#5364]
Snapshot of the passcode screen

![WhatsApp Image 2022-02-04 at 1 32 01 PM](https://user-images.githubusercontent.com/63765514/152493613-50398567-1378-4082-8b76-c1f0e8203f32.jpeg)

1. Opening 70 in split-screen  breaks the UI
2. Going back to fullscreen restarts the app, and the UI is still broken

Full video of the split-screen error:

https://user-images.githubusercontent.com/63765514/152493995-82695d6a-1c47-437b-82d7-c6519b86dece.mp4

**Comment by antuz123** [comment]
Don't allow split screen when using Hexa

**Comment by cakesoft-swati** [comment]
Verified this issue by Gourab on dev app v2.0.75(455)
