### ISSUE TITLE
Post recovery:Unable to re-confirm cloud backup.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5365]
https://user-images.githubusercontent.com/62699947/152507122-e0670f6b-900c-416c-92bf-697f823c5bd2.mp4
- I completed level 2 and restored the app. After a while my share was not confirmed so when I went to confirm Google Drive Cloud Backup I clicked on it but nothing happened. It didn't even open the details page.

**Comment by Parsh** [comment]
Unable to replicate on iOS.

@antuz123 Would need to assign someone who can look at the android part of this(could turn out to be a case specific to Google Drive) as I can't build the android version of the app on my system.

![Simulator Screen Shot - iPhone 12 - 2022-02-05 at 16 01 07](https://user-images.githubusercontent.com/17980466/152638517-bac6d4da-aae0-45bc-8048-dab5cbbe3698.png)

![Simulator Screen Shot - iPhone 12 - 2022-02-05 at 16 02 10](https://user-images.githubusercontent.com/17980466/152638522-677f3bcc-a1b1-4b6b-88c3-0bb14affcf26.png)

**Comment by Parsh** [comment]
@cakesoft-swati Can you please check this one again? I'll also try to see if during the restore journeys that I'm doing throughout the day, whether this issue surfaces for me.

**Comment by cakesoft-swati** [comment]
- Unable to reproduce this issue on dev app v2.0.75(463)
