### ISSUE TITLE
Android Recovery key error: Loader keeps on rotating (restore)

### ISSUE THREAD

**Issue by GourabSanyal** [bithyve/hexa#5376]
Occurring in both 70 dev and 69 live.

Android version: 11

https://user-images.githubusercontent.com/63765514/152747641-941303d2-23c8-4a9a-8fcd-70b842679fa7.mp4

Uninstalled and re-installed the app, still same error occurred.

**Comment by GourabSanyal** [comment]
Re-uploaded Video

**Comment by Pawan2792** [comment]
@GourabSanyal i am not able to reproduce this issue or you can share steps to reproduce this issue.

**Comment by cakesoft-swati** [comment]
- Unable to reproduce this issue .Tested on dev app v2.0.75(463)
