### ISSUE TITLE
Donation account set up: Overlapping UI

### ISSUE THREAD

**Issue by GourabSanyal** [bithyve/hexa#5377]
While setting up the donation account, a pop-up is overlapping with the 'Proceed' button while checking on 2FA option.

![Screenshot_2022-02-07-13-33-35-776_io hexawallet hexa development](https://user-images.githubusercontent.com/63765514/152749012-6de0e8fc-57e2-4f81-a860-dabf3a46f2e8.jpg)
.

**Comment by tumul-vikash** [comment]
Resolved. Need to show during standup

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(455)
