### ISSUE TITLE
Backup on a device

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5379]
https://user-images.githubusercontent.com/62699947/152771786-33dc11b0-ec78-46d8-952a-5cf28ac9a876.mp4

- When we click on "Share Now" then we associate a contact or do a skip then it shows QR code to scan but there are 2 loader coming over the QR. I scan and accept the request on receiver side but can't click on "Done scanning QR".After that I killed the app and reopened it then it was confirmed.
- Every time I have to kill the app, only then the loader disappears.

**Comment by Parsh** [comment]
This seems to be working fine on 75. 
@cakesoft-swati Once a build from 75 is out for test, we can see if this is still happening(on android).

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(455)
