### ISSUE TITLE
Voucher screen changes.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#538]
Following are some changes on voucher screen:
-Take out the Note, and we will need a way to manually enter voucher code
![takeoutnote](https://user-images.githubusercontent.com/62699947/82435649-34dd5c80-9ab2-11ea-8bd8-4ab9b7f7c852.jpg)

-Title should be ‘Scan a FastBitcoin voucher’ instead of Voucher.
![title](https://user-images.githubusercontent.com/62699947/82435904-9ac9e400-9ab2-11ea-9ff5-80921671c18a.jpg)

-Need a header here, “Deposit Account”. This screen may need UX inputs
![needheader](https://user-images.githubusercontent.com/62699947/82436031-ccdb4600-9ab2-11ea-8e44-05b6d39e4dc0.jpg)

Do not need Test Account here. Also add a heading “Chose the deposit Account”
![notestacc](https://user-images.githubusercontent.com/62699947/82436145-fd22e480-9ab2-11ea-97c1-1d78855cdbdd.jpg)

**Comment by shreyasnisal** [comment]
Changed header to "Scan a FastBitCoin Voucher".
Removed note and added a text-input to enter voucher code, but text-input does not have functionality yet.
