### ISSUE TITLE
Encryption password.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5382]
![temp (181)](https://user-images.githubusercontent.com/62699947/152777195-aa4cf570-8864-4c45-a8c1-960023fa1f03.jpg)

- "Change" button of Encryption password is not working.Already have an issue in 2.0.80 release so need to remove this option for now.

**Comment by Parsh** [comment]
@cakesoft-swati This issue becomes unnecessary now as #5259 is in the same release as this issue is in(2.0.75).
