### ISSUE TITLE
Password Screen - minor changes 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5392]
@summikhan11 - we need a "Recommended" tag on the AGSP option. 

Also as we are recommending that, we want the user to be able to skip the step totally if they are new and feel overwhelmed with that recommended option. So they can skip the whole thing. This means we will need a skip button for the whole step and the cloud backup option checkbox goes away.

**Comment by antuz123** [comment]
0 # too guessable: risky password. (guesses < 10^3) 
 
  1 # very guessable: protection from throttled online attacks. (guesses < 10^6) 
 
  2 # somewhat guessable: protection from unthrottled online attacks. (guesses < 10^8) 
 
  3 # safely unguessable: moderate protection from offline slow-hash scenario. (guesses < 10^10) 
 
  4 # very unguessable: strong protection from offline slow-hash scenario. (guesses >= 10^10)

**Comment by antuz123** [comment]
Language to be used: 

"Weak" - Red - 0 and 1 - not allowed 
"Could be stronger" - Amber - 2 and 3 - allowed 
"Strong" - Green - 4 - allowed

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/d7c94aa6-eb66-403c-8246-4cfe87d6bab9-829a/screen/a7cf0ef9-9ae7-4225-b081-03f2fca03516/
scroll to find the other two

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(465)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(467)
