### ISSUE TITLE
LN account ui changes and improvements 

### ISSUE THREAD

**Issue by cakesoft-shashank** [bithyve/hexa#5394]
1. Button placement
![image](https://user-images.githubusercontent.com/50690016/152921720-d9b9357b-afbf-4ea8-91ad-b8e70301ebae.png)

2. Open channel button
![image](https://user-images.githubusercontent.com/50690016/152921834-1047fb74-62fc-4d70-b7fe-73fe46042af6.png)

3. Pay invoice UI
![simulator_screenshot_47D8BFF9-8D2A-4B4C-A244-A958237F8C51](https://user-images.githubusercontent.com/50690016/152921988-d55c4372-d111-4843-96e8-ed7596a5f4b8.png)

4. Receive screen
![simulator_screenshot_838750C7-F7EA-41E0-B555-A502CF226736](https://user-images.githubusercontent.com/50690016/152923428-f1d57f9d-61e8-4056-b452-31f5b0632da1.png)
![simulator_screenshot_55B4D99F-70BA-4AAD-A996-F5E3779AF3C5](https://user-images.githubusercontent.com/50690016/152923462-fa80595d-67b7-4114-bfbb-d1fc479711e4.png)
![simulator_screenshot_60CE6374-4BFC-4E33-BD32-10DD4476F8B0](https://user-images.githubusercontent.com/50690016/152923514-98a1eff2-e6dd-4aa9-aab2-56db08f639f6.png)

**Comment by summikhan11** [comment]
Channel Detail Screen
https://xd.adobe.com/view/1b7355c9-e125-47f4-895c-1a6d1d5dc438-4e20/screen/bc4d8ef6-d5d0-4f14-8db7-d91ad0e76be3/

Channel Dashboard
https://xd.adobe.com/view/1b7355c9-e125-47f4-895c-1a6d1d5dc438-4e20/screen/23cf53d4-2066-4a14-b9b2-8660f6f04cca/

Pay Invoice
pending...

Receive 
https://xd.adobe.com/view/1b7355c9-e125-47f4-895c-1a6d1d5dc438-4e20/screen/8e4d140f-bc7f-411c-871a-5a659f004769/
scroll for all options
@ASN-BitHyve can you suggest page titles

**Comment by cakesoft-swati** [comment]
![temp_14](https://user-images.githubusercontent.com/62699947/154476696-8e837226-7061-4fb9-a12e-d097e139a835.jpg)
- There is no Bar for Total offline balance on Channnel Dashboard.

![temp_13](https://user-images.githubusercontent.com/62699947/154477159-ac12ef2a-8419-4bde-98f0-856becba3462.jpg)
- The text "sats" is getting cut.Check the proportion.

**Comment by GourabSanyal** [comment]
Not able to replicate @cakesoft-swati

**Comment by GourabSanyal** [comment]
![Screenshot_20220421-192454_hexa dev.jpg](https://user-images.githubusercontent.com/63765514/164644915-ecd1f003-52a8-442d-9156-cfb57844e76e.jpg)

1. Tested in 2.0.75.
2. Screenshot from USB debugging on Android.

Issue must be device specific.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(467)
