### ISSUE TITLE
Path field UI in Payment Details Screen

### ISSUE THREAD

**Issue by violet360** [bithyve/hexa#5400]
### Current representation:
![IMG_0066](https://user-images.githubusercontent.com/46649871/153145923-30249d38-4ce7-4bba-a9df-845d532b5966.jpg)

This field is a list of peers through which the payment got forwarded through, each element in the list represents `<peerID> [Forwarded: <forwarded amount>, Fee: <fees the node charged>]` currently looking cluttered up, can we create a UI to represent this field ?

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/1b7355c9-e125-47f4-895c-1a6d1d5dc438-4e20/screen/3c35a3ab-597c-4f35-a982-31684251a5d0

the screen before this is the screenshot on top

**Comment by cakesoft-shashank** [comment]
@cakesoft-swati we are skipping this one

**Comment by cakesoft-swati** [comment]
- Closing this issue for now.
