### ISSUE TITLE
On-chain Bitcoin: The latest transaction shows up last in the transaction list.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5406]

**Comment by cakesoft-swati** [comment]
- Still the latest on- chain transaction is last in the transaction list.
![File (116)](https://user-images.githubusercontent.com/62699947/153577509-de6390e5-1d17-47c9-b2a7-342dea629695.jpg)
- Every time when I kill the app, the latest transaction comes to the top of the list.
- Tested on dev app v2.0.70(436)

**Comment by cakesoft-shashank** [comment]
![simulator_screenshot_7BEEFDAF-5639-4451-BAAB-8C25B1C57AD0](https://user-images.githubusercontent.com/50690016/154636593-ac3c373e-2afc-445c-a437-fb02280ae982.png)
@cakesoft-swati

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(439)
