### ISSUE TITLE
Personal Device:QR code is not being generated.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5411]
![Image from iOS (13)](https://user-images.githubusercontent.com/62699947/153367457-5a41bc0f-1ab2-43aa-8ddc-edb5d0bda668.jpg)
- One of our users is trying to complete Level 2. But the QR code is not showing since few days.
- I asked her to uninstall and reinstall the app and then it showed the QR code.
- But very often Personal devices do not generate QR.

**Comment by Parsh** [comment]
@cakesoft-swati Can we try to reproduce this and jot down the steps? Right now, I'm not able to replicate this.

**Comment by cakesoft-swati** [comment]
https://user-images.githubusercontent.com/62699947/155126728-e2b7cd02-90c5-4572-88e2-bb6286452e99.mp4

- In latest dev app v2.0.70(441) it is not even generating the QR.This is happening on android device.And in ios it is generating the QR but taking more time to show it.It is taking atleast 2/3 minutes.Sometimes it takes 10/15 seconds.

**Comment by cakesoft-swati** [comment]
- Now in ios dev app v2.0.75(446) It is not generation the QR.

**Comment by Parsh** [comment]
![Image from iOS](https://user-images.githubusercontent.com/17980466/156165998-17d13212-cd6a-48ac-b8d0-367057f04a7d.png)

Not able to replicate it. Though it took a while, however, it always got generated on iOS.

**Comment by cakesoft-swati** [comment]
- closing this issue for now.we anyway don’t want people to use level 2
