### ISSUE TITLE
Text change required while changing name of wallet

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5415]
The text should be:
"Step 1: Confirm Encryption Password"

![photo6064648565784948880](https://user-images.githubusercontent.com/68264080/153395163-a0a88d11-716d-49bb-bf4d-175d8315d23b.jpg)

**Comment by ASN-BitHyve** [comment]
@cakesoft-swati please put screenshots of the places that mention security question for me to suggest appropriate text to replace the security question text.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(446)
