### ISSUE TITLE
Redux type def

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#5420]
We'll need type definitions in order to avoid these `state not exists on type DefaultRootState` errors on the UI screens.

<img width="1440" alt="Screenshot 2022-02-11 at 1 18 33 PM" src="https://user-images.githubusercontent.com/17980466/153554736-d674fa95-4b09-4a64-bcbe-3cf36acddcfc.png">

**Comment by Raheel1258** [comment]
I have discussed this with @cakesoft-shashank. We are skipping this for now

**Comment by cakesoft-shashank** [comment]
This is done in keeper with redux-toolkit

**Comment by Deveshshankar** [comment]
Fixed cc @cakesoft-shashank
