### ISSUE TITLE
Need icons for these options

### ISSUE THREAD

**Issue by cakesoft-shashank** [bithyve/hexa#5426]
![](https://user-images.githubusercontent.com/62699947/153571097-852c74c8-c408-4c0f-be28-d1b7dcd13f46.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/1b7355c9-e125-47f4-895c-1a6d1d5dc438-4e20/screen/176c8469-7f2e-4482-8e42-be67502a2730/

please amend the design as well

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(438)
