### ISSUE TITLE
Inaccurate invoice creation/expiration/settle dates

### ISSUE THREAD

**Issue by niteshbalusu11** [bithyve/hexa#5485]
Open any payment req in payments history, the invoice creation, expiration and settle dates show random dates from 1970. 

![image](https://user-images.githubusercontent.com/84944042/154844941-616f0bd2-85b7-4aaa-87e1-6d9dee1ffcce.jpeg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(441)
