### ISSUE TITLE
Open channel option shows "keep channel private"

### ISSUE THREAD

**Issue by niteshbalusu11** [bithyve/hexa#5486]
When trying to open a channel, there is a free text at the bottom that says "keep channel private" even though private channel opening was disabled. 

Either we have to give the option to open private channels or remove the text. 

![image](https://user-images.githubusercontent.com/84944042/154845344-f43871f9-44db-467a-9b93-247229475394.jpeg)

**Comment by cakesoft-swati** [comment]
- verified this issue on dev app v 2.0.70(440)
