### ISSUE TITLE
Swan Account does not auto refresh.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5488]

**Comment by Parsh** [comment]
Unable to replicate this. @cakesoft-swati 

Swan account is auto-refreshing just like all other accounts.


https://user-images.githubusercontent.com/17980466/156760397-3c8b6f54-d332-4c60-ba75-b5844a5c6bfa.mp4

**Comment by cakesoft-swati** [comment]
- Unable to replicate this issue.
