### ISSUE TITLE
Gift: Showing two transactions when it is added to the account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5489]
![Image from iOS (14)](https://user-images.githubusercontent.com/62699947/154900329-7bb461df-3142-44f5-a744-975d478eec3f.jpg)
- The gift is having two transaction when added to the account as soon as you accept.

https://user-images.githubusercontent.com/62699947/154925384-c35bd9e6-42ed-4c7b-8021-18772aec928d.MP4

- 
1.Date/ time is incorrect
2.The gift adds in and goes out as soon as I add them to the account
3.It is showing Lightning in the encryption method when no encryption was used

**Comment by antuz123** [comment]
This is a gift created from an old app (67) and scanned on a new app (69)

**Comment by Parsh** [comment]
Could be linked to status override issue: https://github.com/bithyve/hexa/issues/5196
