### ISSUE TITLE
GAC Web View (GiftQRFeb22)

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5498]
GAC stands for Gift Agent for Campaigns. Refer to the user story here https://github.com/bithyve/internal-docs/issues/190 

(This is for HEXA as a company and not a end user feature)

1. Get a QR for redirection to hexawallet.io/GiftQR/Feb22
2. When a user scan this QR or clicks on the link (not from within Hexa), it checks for the standard checks to avoid multiple requests from the same device/ IP address (this is slightly different to the DDOS attack check and may include items like IP check, VPN check timing analysis, using Captcha etc). This is also probabilistic and cannot be exact, which is fine. We just need to implement what is standard available out there. 
3. If there is an indication that this is a repeated request, then an error is shown to the user on the web view. "Heading: Something is not right!! Description: Too many requests, please try again later or try with another device"
4. If the request is genuine, they should get a message "Make sure you have installed Hexa Wallet before you proceed. If not, please install and come back here to continue the process" 
5. CTAs will be "I have Hexa Wallet" and "Download Hexa Wallet"
6. Download Hexa Wallet takes them to the store directly 
7. "I have Hexa Wallet": If no wallet then it goes to the store, if wallet present: it will ask the GAC Relay (#5499) (parameter to pass = GiftQRFeb22) for a gift link and redirect there

**Comment by cakesoft-shashank** [comment]
## Campaign collection
    id:FEB22 -> unique
    title: ''
    description: ""
    createdAt: ""
    isActive: true
    links: [
        {
            url: "https://gift.hexawallet.io/mgpwNaN8zwi76Hq17",
            visited: true,
            claimedBy: "ip"
        }
    ]
    
## APIs
   POST /createCampaign
accept {
        id:FEB22
    title: ''
    description: ""
    createdAt: ""
    isActive: true
    }

POST /addGifts
{
    id: "",
    links:["", ""]
}

GET /getCampaign/{id}
retutn {
        id:FEB22
    title: ''
    description: ""
    createdAt: ""
    isActive: true
    }

POST /claimGift
{
    ip: ""
}

**Comment by cakesoft-shashank** [comment]
Elements

- title
- decscription
- captcha
- get link button

**Comment by ASN-BitHyve** [comment]
Point number 7: "If no wallet then it goes to the store..." statement irrelevant?

**Comment by antuz123** [comment]
Title: Stack Some Sats (bitcoin)
Description: You have received a bitcoin gift from the Hexa Wallet team. Bitcoin is a new type of money that is not controlled by any government or company. Download the wallet and claim your gift before it expires.
CTAs:
Download Hexa Wallet
Go to the app

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/ff175839-dd75-4d46-8208-5fe20355d683-aa44/

**Comment by tumul-vikash** [comment]
Can we close this issue now
