### ISSUE TITLE
GAC Relay (GiftQRFeb22)

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5499]
GAC stands for Gift Agent for Campaigns. Refer to the user story here https://github.com/bithyve/internal-docs/issues/190

(This is for HEXA as a company and not a end user feature)

1. The Gift Relay receives a request from the GAC Web View (#5498) with the parameter "GiftQRFeb22" (For now this is the only use case but in future the Web View can send any param so as to identify a specific GAC)
2. Against the GAC identifier GiftQRFeb22, a numbered array of gift links is stored (this will redirect to a campaign ID array which will be manually set up for now using data from #5501). Plus a total to say how many gifts are there and an index to identify which gift link are they on currently. Initial value of index = 1. 
3. On receiving a request from GAC Web View, if index > Total an error is shown to the user. Heading: Something is not right!!! Description: The gifts are temporarily not available or the campaign is over" 
4. If Index <= Total, redirect to the Gift Link on the index and Index++

**Comment by cakesoft-shashank** [comment]
## Campaign collection
    id:FEB22 -> unique
    title: ''
    description: ""
    createdAt: ""
    isActive: true
    links: [
        {
            url: "https://gift.hexawallet.io/mgpwNaN8zwi76Hq17",
            visited: true,
            claimedBy: "ip"
        }
    ]
    
## APIs
   POST /createCampaign
accept {
        id:FEB22
    title: ''
    description: ""
    createdAt: ""
    isActive: true
    }

POST /addGifts
{
    id: "",
    links:["", ""]
}

GET /getCampaign/{id}
retutn {
        id:FEB22
    title: ''
    description: ""
    createdAt: ""
    isActive: true
    }

POST /claimGift
{
    ip: ""
}
