### ISSUE TITLE
GAC - App Gift List (GiftQRFeb22)

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5501]
GAC stands for Gift Agent for Campaigns. Refer to the user story here https://github.com/bithyve/internal-docs/issues/190 

(This is for HEXA as a company and not a end user feature)

1. This is a manual step to be done by the team for GiftQRFeb22
2. Manually create N gifts of 5000 sats and go through the send flow and choose No Encryption as an option
3. Copy the link for each gift in a list 
4. This list is the array for #5499 with Total = N and is updated there manually on the backend 

N depends on how many gifts we want for Advancing Bitcoin conference week. Also the gifts should be created 2 days before the conference as they have an expiry of 1 week (TBC)

**Comment by antuz123** [comment]
@channel 
1. The QR for hoodie will have to be the static QR that Summi has given @Prasad
2. The QR for the cards will have to different and a direct gift QR not the static QR in 1 @Abhilash Nair
3. For 2, it will have to be encrypted with the question. “Best conference in town”. “Advancing Bitcoin” @Abhilash Nair@Prasad
4. This is because we are giving it to them as a private key, so better if they have it encrypted
5. @Abhilash Nair- 1 and 2 will have to be different sets so 200 for the cards and 100 for the static QR 
6. Prasad, imp to understand the difference between the two

**Comment by ASN-BitHyve** [comment]
@antuz123 is this issue ready to be closed? Or does it become an operate issue for us to check whether we're doing any promotions in a given month?

**Comment by ASN-BitHyve** [comment]
@antuz123 need your comment on my comment above from March 16th.
