### ISSUE TITLE
Ui Issues- Lightning Screen

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#5513]
![Image from iOS (4)](https://user-images.githubusercontent.com/85475736/155293911-96255fdc-b304-403c-a6f7-a1a971df89e1.jpg)

https://xd.adobe.com/view/1b7355c9-e125-47f4-895c-1a6d1d5dc438-4e20/screen/22c2cce4-d167-4b3d-8bcf-73a9b73fdc86/

Check back icon
The bitcoin-dollar switch has wrong colors,check size
Increase the size of the account card in the background and change the color to grey
Account Icon is missing
add content next to the Account heading 
Check size and opacity of "Bitcoin Icon"
check icon size for address icon in transactions
Check opacity of two dividers
Move CTA's to the bottom of the screen
Remove the border on CTA's and add shadow

**Comment by cakesoft-swati** [comment]
![simulator_screenshot_A8D2A1C0-655B-48DA-B876-93261456CCF3](https://user-images.githubusercontent.com/62699947/156302178-46ac699e-cfaa-4984-8bdc-281e061240e2.png)


![temp (195)](https://user-images.githubusercontent.com/62699947/156302271-9fb48938-7432-44ab-886b-1d8e0cc91ee2.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(452)
