### ISSUE TITLE
Ui Issues - Lightning Settings

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#5514]
![Image from iOS (5)](https://user-images.githubusercontent.com/85475736/155296536-386e41ac-a7cf-4282-b398-f82e3100fa50.jpg)

https://xd.adobe.com/view/1b7355c9-e125-47f4-895c-1a6d1d5dc438-4e20/screen/176c8469-7f2e-4482-8e42-be67502a2730/

Heading is missing
Remove row dividers and add cards
check icon sizes

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.71(451)
