### ISSUE TITLE
Ui Issues - Node Information

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#5515]
![Image from iOS (6)](https://user-images.githubusercontent.com/85475736/155297191-75dd1fa5-76cf-464c-bdc1-8c41059cf6f0.jpg)

https://xd.adobe.com/view/1b7355c9-e125-47f4-895c-1a6d1d5dc438-4e20/screen/4a526798-6126-4898-849d-41d089490a78/

Status Bar not visible here
Remove the top white bar
"Settings" title is missing
Check colors of the screen and cards
Check spacing between cards
Check Placement of CTA's
CTA's shouldnt be all Caps

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.71(450)
