### ISSUE TITLE
Ui Issues - Channels

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#5516]
![Image from iOS (8)](https://user-images.githubusercontent.com/85475736/155298679-9a0f40ab-25c9-484e-b299-dd55063bb885.jpg)
https://xd.adobe.com/view/1b7355c9-e125-47f4-895c-1a6d1d5dc438-4e20/screen/23cf53d4-2066-4a14-b9b2-8660f6f04cca/

Remove white header from the top
Status bar is not visible
Check "open a channel" colors
I've defined the size of 0sats, lets have that as a minimum size

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(447)

**Comment by GourabSanyal** [comment]
not replicable. tested in 0.75 using USB debugging.
