### ISSUE TITLE
Ui Issues - Channel Details

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#5517]
![Image from iOS (7)](https://user-images.githubusercontent.com/85475736/155299123-099836fd-37d3-49ee-b3cb-6588be3a784b.jpg)
https://xd.adobe.com/view/1b7355c9-e125-47f4-895c-1a6d1d5dc438-4e20/screen/bc4d8ef6-d5d0-4f14-8db7-d91ad0e76be3/

Remove the white element on top
Check heading orientation and size
add the channel element from the screen before
check the screen and card colors
Move Cta's to the bottom of the page, check colors and icons

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(467)
