### ISSUE TITLE
Ui Change - Status when a user first logs in

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#5518]
Remove the red dot from bottom navigation, change the status and status icon

@ASN-BitHyve please take a look at the status

![File (5)](https://user-images.githubusercontent.com/85475736/155323040-f7e2263e-0fb1-4520-8ff9-02711885ea10.jpg)

https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/

**Comment by ASN-BitHyve** [comment]
"Backup your wallet to safeguard your sats"

**Comment by cakesoft-swati** [comment]
![temp_18](https://user-images.githubusercontent.com/62699947/155482088-eae20879-a2af-4dfa-9857-bf4c81ef90db.jpg)
- The red dot is still visible at bottom navigation.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(447)
