### ISSUE TITLE
GAC - Hexa QR redirect

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5521]
When scanned from Hexa Wallet scanner:

1. If the QR is not a recognised Hexa QR, then it simply redirects to a browser 
2. In the above case, if the user ends up scanning from within Hexa, they will be redirected to the Web View and everything from there will continue as is.

**Comment by cakesoft-swati** [comment]
- When I scan the QR it takes me to the web view and nothing happens when I click on the "Go to App" button.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(447)
