### ISSUE TITLE
Regarding Orange alert icon on home screen

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5527]
Changing the color to Orange doesn't really help a lot. Scenario: I'm a new user, and the first thing I see is the alert. There is an exclamation there, so I know it's important. But that text message is not clickable, so I have no clue where to go from there. This ends up becoming my very first experience with Hexa Wallet.

Solution: We give a pleasant looking backup themed icon and make the text clickable. On clicking the text, the user is led to the security center.

IMHO: We should also remove the Red dot in the backup section, cos otherwise the eyes are drawn there right at the start with the user having no context (right now) on why it is glowing red.

![ss](https://user-images.githubusercontent.com/68264080/155476469-ac37e842-0c67-4147-9b75-9bd8f9a1bc84.jpg)

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/be4bd2ea-118c-4aff-959f-e3243e25ca8f-eb18/

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.70(447)
