### ISSUE TITLE
Gift sats:UI change.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5532]
![tempFileForShare_20220224-135435](https://user-images.githubusercontent.com/62699947/155490350-7ff63780-e71e-4ff7-9e15-6bf23856248e.jpg)
- Long pressing on plus icon should continuously create gifts. Same way long pressing on minus should reduce.

**Comment by GourabSanyal** [comment]
"Long press to create gifts continuously" is not working

**Comment by Raheel1258** [comment]
I have tested this on android and IOS both. It is working fine in `featue/2.0.75`

**Comment by GourabSanyal** [comment]
fixed
