### ISSUE TITLE
Bitcoin4India Website

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5533]
Start developing the website:

Navigation tab: About | Resources | Stories | Gallery | Upcoming Events | Support

Within Resources:
1) Resources for Devs
2) Resources to learn about Bitcoin
3) India and Bitcoin
3.1) Twitter handle of Indian Bitcoiners + A link to Hive.one list.
3.2) Status of Bitcoin in India.

Within Stories:
1) Snapshots of Indian Bitcoiners.
2) Stories of the work being facilitated by Indian Bitcoiners 
3) Blogs written by Indian Bitcoiners

Gallery:
1) Photos and videos of past events. Taken by us as well as attendees.

Upcoming Events:
1) Give meetup link.
2) Conferences
3) Online Seminars - TBD.

Bitcoin Jobs:
Summer Of Bitcoin
Bitcoiner Jobs

(Mention curated by) 

_________________________________________________________________________________________________________________________________

- [ ] Wix template setup
- [ ] Images upload as per template
- [ ] Sections created as per the sitemap above
- [ ] Insert images if need be
- [ ] Stabilize on wix

**Comment by Pawan2792** [comment]
@ASN-BitHyve  asked for Closed
