### ISSUE TITLE
Pause Hexa 1

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5540]
Can we pause Hexa 1 on the stores and resume it later if needed? 

Idea is to have an option to release a patch if needed.

If this is possible, we will stop publishing the 1.0 app on the stores. The backend will be monitored and kept up for now

**Comment by cakesoft-shashank** [comment]
Android app is unpublished from playstore

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
