### ISSUE TITLE
Gift:UI change on 'No of Gifts' field.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5557]
![tempFileForShare_20220302-154601](https://user-images.githubusercontent.com/62699947/156347474-4217a152-fdc6-42dd-94d5-943d071f8ffc.jpg)
- This field is unresposive. If we have to keep that field non-responsive, then the he UX needs to change to convey a sense that that area is unclickable.

**Comment by Raheel1258** [comment]
@summikhan11, kindly provide design for that field

**Comment by GourabSanyal** [comment]
fixed
