### ISSUE TITLE
New Repos for all apps 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5575]
- [ ] Env setup
- [ ] Lint
- [ ] Localisation
- [ ] Firebase
- [ ] Build variants and scripts
- [ ] Appcenter
- [ ] Git, GitHub hooks setup?

**Comment by cakesoft-shashank** [comment]
Hexa pay: https://github.com/bithyve/hexapay

**Comment by cakesoft-shashank** [comment]
All repos are setup
