### ISSUE TITLE
Send Unsuccessful:

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5584]
![Screenshot_20220307-182850](https://user-images.githubusercontent.com/62699947/157048939-2cf9a7e6-99f9-4300-8cbc-1cee52055ae1.jpg)
- Got this error 2 times while sending to contact,one with low priority and second time with custom priority and third time I did the "Send Max" and it went successfully. 
- Live app v2.0.71(453)

**Comment by Parsh** [comment]
I've not been able to replicate it, generally, the dust limit is pre-handled by coin-select mechanism, in some cases, it might fail. Once we improve on the UTXO selection mechanism(SoB) this error would vanish.

**Comment by cakesoft-swati** [comment]
- Closing this issue for now as per the above comment.
- Also not able to replicate it again on dev app v2.0.75(461)
