### ISSUE TITLE
Encryption Password:Change button is not working.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5597]
![File (122)](https://user-images.githubusercontent.com/62699947/157445830-f6cd9029-c837-40bd-a9e3-d413ecdcf7e7.jpg)
- When I click on change button nothing is happening.
- Tested on dev app v2.0.75(455)

**Comment by Parsh** [comment]
We'll enable Change encryption password after addressing the following issue #5259

**Comment by cakesoft-swati** [comment]
For now closing this issue.
