### ISSUE TITLE
GAC: Twitter follow button

### ISSUE THREAD

**Issue by cakesoft-shashank** [bithyve/hexa#5612]
- Add follow hexawallet on twitter button 
- When click on follow open hexawallet's twitter page in a new tab
- Then enable go to app button

**Comment by cakesoft-swati** [comment]
![temp (204)](https://user-images.githubusercontent.com/62699947/159912832-8fc01fb9-7bc6-4b93-b1ed-18c6e8d6de7e.jpg)
-  Follow Us button doesn't look right.Need to fix the margin.

**Comment by tumul-vikash** [comment]
this issue has been resolved
