### ISSUE TITLE
icloud Backup

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5613]
https://user-images.githubusercontent.com/62699947/158554803-cd7a7874-3cc8-48a5-8959-c99a95adee17.MP4

- icloud backup is not getting confirmed again.When red ouline appeared I went to confirm it again.When backed up it was showing a confirmation message on the history page but there was still a red outline on the level 1>icloud backup.
- Tested on dev app v2.0.75(455)

**Comment by Pawan2792** [comment]
unable to Reproduce

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(462)
