### ISSUE TITLE
Change backup method.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5634]
- I changed the backup method from cloud to personal copy.I shared the PDF and came back but it was still showing the cloud icon and text was personal copy.
![temp (210)](https://user-images.githubusercontent.com/62699947/163134586-d03db6fd-e7a2-46d6-939e-7ad97f19c735.jpg)

**Comment by Parsh** [comment]
As of 75 and post
-   Level 0  move to Level 1: Cloud and Seed(change is allowed b/w the two) 
- Already on Level 1: They will be on the cloud and the backup can be changed to seed
-  Already on Level 2: They can’t have seed option, nothing changes over there(Level1: Cloud cannot be changed)   

As of 80 
- Level1: Introduction of and change to Device, PDF, Contact.

**Comment by Pawan2792** [comment]
@antuz123 can you please share Content when we complete backup on seed & cloud.

**Comment by Pawan2792** [comment]
80 onwards:

Level 1: Introduction of and change to Cloud and Seed(change is allowed b/w the two) .
Level 2/3: No changes

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(483)
