### ISSUE TITLE
Donation web view

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5635]
![temp (211)](https://user-images.githubusercontent.com/62699947/163170732-9c8c11e4-c622-47f0-ae95-c80ab4af5109.jpg)
- Donation QR or address is not visible.
- Tested on dev app v2.0.75(462)

**Comment by cakesoft-swati** [comment]
- Still the QR/address is not visible on web.
- Also donation acc name and details are not visible on web.
![temp (220)](https://user-images.githubusercontent.com/62699947/165769407-65a4804d-2eaf-4f88-bff2-f2c645d2052c.jpg)

- Tested on dev app v20.75(466)

**Comment by tumul-vikash** [comment]
This issue exist only for hexa-dev app and it will work perfectly for production one. Also we are disabling donation in 2.0.75
