### ISSUE TITLE
Version History

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5648]
![Screenshot_20220418-183312](https://user-images.githubusercontent.com/62699947/163812599-3cabdb3b-2895-41de-967e-620a367d3e7f.jpg)
- I upgraded the old version of the dev app. After that I uninstalled the app and reinstalled it and then the version history page was showing blank.

**Comment by Pawan2792** [comment]
@cakesoft-swati Not able to Reproduce

**Comment by cakesoft-swati** [comment]
- I'm still able to reproduce this issue on device.
**_- Steps to reproduce:_**
1.Install older version of the app.
2.Upgrade to latest version
3.Now uninstall the app and recover it.Check the version history.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(470)
