### ISSUE TITLE
Backup using seed words.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5650]
- When at Level 0, the user should be able to select seed words as an option at Level 1.
- When at Level 1, a user can change the backup type to note down the seed words.
- This change option does not apply if you are at Level 2 or 3.

> Note:  Opting for 12 words seed instead of 24

**- The backup now and change backup screen will require additional option of using seed words**

**_UX Link:_**

https://xd.adobe.com/view/3c76a519-ed48-4944-a7a5-026a2aca5a6d-6925/screen/e0e1d4ab-450e-436e-a563-0b29396f5eb1/

**Comment by Parsh** [comment]
So we’ll need to create a dummy flow @Pawan2792  (till @summikhan11  sends the UX)

Here it is:
- We need to have a prompt to ask the user what he/she wanna do(when they hit on any button of level 1)
- If they select seed, then we just show the seed on a bottomsheet
- If they select anyting else, we make them setup the password and then they can do iCloud or Device/Contact or PDF

Also, the bottomsheet on which we’ve these options of selecting backup method like iCloud, Contact, Device and PDF, on the same bottomsheet we need to have an option for seed as well, upon clicking it we’ll route the user to a screen with a text area on which there will be seed written(or we can reuse the seed bottomsheet that we use a level 0: no-backup-setup scenario)

**Comment by summikhan11** [comment]
link is updated,
will work on additonal screens after reviewing the video

**Comment by Pawan2792** [comment]
@summikhan11 is the link Updated?

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/3c76a519-ed48-4944-a7a5-026a2aca5a6d-6925/screen/dd008045-bf2d-46c5-b5c1-fffcf38aa49b/

Seed words

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/24cad77c-7eb9-4623-a2dc-edf64b9e4743-7199/screen/96c52b18-a7d3-4d41-91ac-aea5480eae58/

home screens

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(421)
