### ISSUE TITLE
Restore using Seed words.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5652]
- [x] User should be able to recover using the seed words in the recovery flow. The wallet image should have all the other info.
- [x] Even though I have selected any recovery key other than cloud at the time of backup, it is showing cloud option at the time of restore.
- [x] This will also apply when cloud is not available as a backup option. In addition to the above:
- [x] When no backup is found on the cloud, this modal should not come.
- [x] Even if there are backups available on the cloud and the modal comes up, the user should have a clear indication that they don't want to use that backup. This will close the modal
- [x] On the main screen when cloud is not chosen, the user can scan a QR (for app or PDF) - this already exists. 
- [x] But also they can input the seed to recover from
- [x] This needs to either work or show apt message even when a non Hexa seed is put in. Options: if recreating the wallet is not possible with an external seed, it should say that. ~~Or if possible but only Checking account it should create with a warning~~.

**_UX Link:_**
**- Restore using Seed words:**
https://xd.adobe.com/view/182db13e-dc6a-40ec-a319-5bf018182399-4d7e/screen/b164a85b-68e7-40f3-891b-83672956f994/

**Comment by summikhan11** [comment]
link is updated,
let me know if any additional screens are required

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/182db13e-dc6a-40ec-a319-5bf018182399-4d7e/screen/e2b5fd4a-d31d-464e-8b14-3202deb28a52/

Notes:
1. from our very early discussions entering the seed words was 4-6 at a time, also suggestions we required as you can see reflected in the design. let me know if we want to stick to the scroll showed in the video
2. @ASN-BitHyve need content on the popup

**Comment by antuz123** [comment]
Suggestions not needed

**Comment by cakesoft-swati** [comment]
- Two tasks that are marked as fixed have been verified on the dev app v2.0.75(471)
- I am moving this issue to 80 for the pending task.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(485)
