### ISSUE TITLE
Unable to BACKUP on Google Drive

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5664]
![Screenshot_20220427-144921](https://user-images.githubusercontent.com/62699947/165496181-480e7885-1a1c-42c8-a644-a45238c91e4d.jpg)
- Unable to backup on google drive.I did the whole process of cloud backup but it still showed the exclamation mark on the Security Center page and the message on the home screen didn't change.

**Comment by cakesoft-swati** [comment]
- Now Google Drive backup is not happening in Dev App v2.0.75(468). It is giving cloud backup error.
![Screenshot_20220504-150556](https://user-images.githubusercontent.com/62699947/166657124-dda060d8-5095-4298-8ff4-af37db58928a.jpg)

**Comment by ASN-BitHyve** [comment]
When going into Recover flow, the wallet is not asking for the email address to recover the wallet from. Thus the user is unable to retrieve his/her wallet from the cloud. 

Thus there are atleast 2 issues here. One is unable to BACKUP to the cloud and second is unable to RECOVER from the cloud.

CC: @Pawan2792

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(469)
