### ISSUE TITLE
Subheading says iCloud. It should be GDrive.

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5677]
![photo6293909607898263655](https://user-images.githubusercontent.com/68264080/165888154-38798c67-b141-451d-bd7b-fc3854b9c188.jpg)

**Comment by cakesoft-swati** [comment]
- Message is missing.Check the above image we just need to replace word icloud.Because we are recovering our wallet from Gdrive not from icloud.
![temp (223)](https://user-images.githubusercontent.com/62699947/167367558-3de6c5f5-a0aa-4b31-85d7-65663be7bb93.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(471)
