### ISSUE TITLE
Hide Send request button + Change text

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5683]
In the Recovery flow, as I understand from Swati, we are not currently using a link to help with wallet recovery. So that button of "Send request" needs to be hidden. Thus the button will only be Scan Key.

Correspondingly the text message above the buttons will also change. It should be:

" Scan Recovery Key to restore your wallet"

![Screenshot_20220429-153953_hexa dev](https://user-images.githubusercontent.com/68264080/165927008-72c741de-1f86-458b-b68e-4d53775e501b.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(468)
