### ISSUE TITLE
Modal look inconsistency

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5684]
Invalid mnemonic modal does not look like other modals.

Remove Contact modal doesn't match the rest of the UX

![photo6296161407711949174](https://user-images.githubusercontent.com/68264080/165929134-c45fbc5b-e18a-488c-9b4a-ecd162b48378.jpg)
![photo6296161407711949175](https://user-images.githubusercontent.com/68264080/165929140-b097ef19-f0be-4c7b-ad4c-b1717fc7329c.jpg)

**Comment by GourabSanyal** [comment]
need XD links from @summikhan11

**Comment by Raheel1258** [comment]
need XD links from @summikhan11

**Comment by GourabSanyal** [comment]
https://github.com/bithyve/hexa/pull/5749

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(485)
