### ISSUE TITLE
Backup Options messaging

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5689]
Backup Recovery Key mentions that one can backup in multiple ways, but only gives Backup on cloud option.

Either the message should be removed. Or options should be given. 

![photo6296161407711949182](https://user-images.githubusercontent.com/68264080/165931417-aad5835c-12f6-4c3c-9c76-565aa2b3a564.jpg)

**Comment by Pawan2792** [comment]
we will give 2 options.
1. Cloud
2. Seed word.

**Comment by Pawan2792** [comment]
Removed Message

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(468)
