### ISSUE TITLE
Passcode:

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5721]
**_Create passcode:_**
- Add a message on the create passcode screen:

“Make sure you remember the passcode and backup your wallet. If you forget your passcode, you can access your wallet only by restoring it”

**_Forgot passcode:_**
- When the user
1.has password set up: the flow is above with hint and all
![Screenshot_20220505-151720](https://user-images.githubusercontent.com/62699947/166904822-21579041-fa74-4e66-8350-cff178a9987b.jpg)

2.has not set the password: show a message asking them to restore the wallet from the backup they have
![temp - 2022-05-05T154150 410](https://user-images.githubusercontent.com/62699947/166904319-511303c5-962b-4290-962d-d05ed90d0ea6.jpg)

**Comment by Pawan2792** [comment]
@ASN-BitHyve can you Please share a Message.
2.has not set the password: show a message asking them to restore the wallet from the backup they have

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(471)
