### ISSUE TITLE
Savings account:Need to remove.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5722]
![temp - 2022-05-05T172925 041](https://user-images.githubusercontent.com/62699947/166918790-ee8e295d-7d95-4b60-93cb-c140b021c21a.jpg)
- If we are not showing the savings account on the home page then there is no point in showing it here on the account management screen.The mention of Savings account needs to be removed from everywhere.

**Comment by Raheel1258** [comment]
I have tested this, It is not appearing on my side.

**Comment by cakesoft-swati** [comment]
- I can see the savings account in account management section.Tested on dev app v2.0.80(480)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(483)
