### ISSUE TITLE
Resend Request button placement

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5727]
The resend request button placement is weird. It should definitely not be in the Know More section. @summikhan11  to suggest as per nomenclature. @cakesoft-swati to assign dev once Summi gives go ahead.

![tempFileForShare_20220506-155745](https://user-images.githubusercontent.com/68264080/167131942-3fe5b2cb-1632-41e9-a5b4-d650bf947d4f.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(480)
