### ISSUE TITLE
Button position

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5728]
Button to be positioned as per Summi's design.

![tempFileForShare_20220506-160258](https://user-images.githubusercontent.com/68264080/167132633-2451dc2e-4393-40b6-8ec8-b5339ba750f8.jpg)

**Comment by cakesoft-swati** [comment]
- still not as per the xd.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(486)
