### ISSUE TITLE
Bugs in gift section

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5729]
1) I changed the currency from BTC to pound. The "insufficient balance" text vanished. It should remain when there is insufficient balance even in fiat!
2) When I changed currency from BTC to pound, still the text says, "Sats would be deducted from. " It should say, "Money would be deducted from"
![tempFileForShare_20220506-160753](https://user-images.githubusercontent.com/68264080/167133033-23409ed4-0132-4f78-8e18-a9ef17f063df.jpg)

**Comment by cakesoft-swati** [comment]
- "I changed the currency from BTC to pound. The "insufficient balance" text vanished. It should remain when there is insufficient balance even in fiat!"- this is still happening on dev app v2.0.80(485)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(486)
