### ISSUE TITLE
Gifts are not getting restored after recovering wallet with cloud.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5755]
- I created a gift and just did the send procedure.After sending it was in sent section of gift.
- After that I did a backup on cloud and restored the wallet.
- After wallet recovery that sent gift was not there in sent section but I can see the gifted transaction in checking account.
- It's only happening with cloud backup.

**Comment by Deveshshankar** [comment]
User is able to perform the above task.
![WhatsApp Image 2022-07-18 at 3 06 13 PM](https://user-images.githubusercontent.com/107177634/179485921-5b1ff389-b4c2-4247-8447-26c326eed28a.jpeg)
![WhatsApp Image 2022-07-18 at 3 12 22 PM](https://user-images.githubusercontent.com/107177634/179485933-3209763c-f65a-4880-bb24-fa40f2646ae9.jpeg)
