### ISSUE TITLE
Cloud Backup flow updation 

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5762]
In the flow below, the third screen “Automated Drive Backup” should be the one that comes (with the correct message) when the user clicks on "Backup on Google Drive". And then the process starts.
https://user-images.githubusercontent.com/68264080/168791717-79ce61e3-8b51-4ccd-930b-8cceb692b035.mp4

The message: "Backup the wallet to easily restore it in case your phone gets damaged or lost"

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(483)
