### ISSUE TITLE
Upgraded app is crashing on savings account.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5793]
- 2.0.67 app was installed in my device. My level 2 was completed in this app and there were some sats in the savings account, it was working properly with 2FA. I upgraded it to 2.0.75 and clicked on the savings account  and as soon as I clicked on savings account app got crashed.

- I upgrded the 2.0.67app to 2.0.74.My level 2 was completed and 2FA was also set up.After upgrade I tried to send from savings account but it gave me error "Txn failed due to invalid OTP" .After that I upgrdae it to 2.0.75 app and again tried to send from savings account and I stuck on this screen.
![Screenshot_20220524-104429](https://user-images.githubusercontent.com/62699947/169954220-533fb73f-75bf-4dc7-a60c-94aef9953bd2.jpg)

**Comment by Pawan2792** [comment]
@cakesoft-swati  Not able to Reproduce crash at my end 
tried with 67 to 75 & 68 to 75
but no crash reproduce

**Comment by cakesoft-swati** [comment]
- I installed 2.0.67.Level 2 was completed.Savings account was working properly.I upgrade it to 2.0.70 and still the saving account was working prperly.After this I installed 2.0.74 and send from savings account was working properly.I again upgrade this to 2.0.75 and as soon as I clicked on savings account and app crashed.
- Tested on android.

**Comment by Parsh** [comment]
Not able to reproduce the crash scenario but yes the app is definitely stuck on the OTP screen due to the bottomsheet.

https://user-images.githubusercontent.com/17980466/170247427-caa8b6d7-4729-4118-9d08-cfcd6ae24261.mp4

**Comment by cakesoft-swati** [comment]
- Verified this issue on staging app v2.0.75(475)
