### ISSUE TITLE
Reset 2FA and sweep funds are not working properly.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5798]
- 2FA reset/sweep funds: After scanning the approval key nothing is happening beyond that.
- If I scan wrong approval key then loader comes up and it continuously loading.If I relogin to the app then also that loader is loading continuously and I am getting stuck on that page.Everytime I have to kill the app to get out of this page.
- This is happening in all the scenarioes(Upgrade,restore).

**Comment by Parsh** [comment]
Reset 2FA worked properly for me on scanning appropriate Approval Key(thought the savings account had that sending bottom sheet issue), however, when we scan wrong QR, the loader never goes away and doesn't clear even after the app restart.

![Simulator Screen Shot - iPhone 12 - 2022-05-25 at 17 13 03](https://user-images.githubusercontent.com/17980466/170255132-fb77c2a9-df4d-456c-ace4-4d7b0cb030e3.png)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(475)
