### ISSUE TITLE
Forgot passcode scenario after restore. 

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5813]
- Forgot Passcode scenario after restore is not asking me sees word confirmations to reset the passcode. Put for 80. Hope it is working fine for pre-restore app.
![original (6)](https://user-images.githubusercontent.com/62699947/170641560-6df87c82-e037-4e1f-b74a-c3d32040800e.jpg)

**Comment by cakesoft-swati** [comment]
- The app crashes when I click the "Confirm" button while confirming the seed word in case of 'forgot password'.
- Tested on dev app v2.0.80(483)

https://user-images.githubusercontent.com/62699947/173040933-73e2ccfa-0448-47f7-80ab-32e2875c212b.mp4

**Comment by Pawan2792** [comment]
Not able to reproduce working fine in android & io

https://user-images.githubusercontent.com/99478432/173580690-cd0e4ec3-e2ce-406d-9319-d0769d430a9c.mov

s

**Comment by cakesoft-swati** [comment]
- In case of seed word backup: After recovery if we forgot passcode then it asks to confirm passcode and when we click on 'Confirm' button after entering word, app crashes.

https://user-images.githubusercontent.com/62699947/177324748-47082d58-9315-492b-847c-a2b2392b2046.mp4
