### ISSUE TITLE
Minor text updates

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5822]
Backup using Seed Words modal: 

1) E should be capital in "English"
2) Remove fullstop after privately
![photo6100536328962813892](https://user-images.githubusercontent.com/68264080/170977151-29a0534b-0c56-4fc5-a968-59ea271e3575.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.75(478)
