### ISSUE TITLE
Modal not as per standard design

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5826]
1) The Modal is not as per standard design
2) Should say seed "word" and not "name"

![photo6100536328962813900](https://user-images.githubusercontent.com/68264080/170982954-da46c319-b7cb-4f15-8008-84b349eba5d9.jpg)

**Comment by cakesoft-swati** [comment]
- no change in dev app v2.0.8(479)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(483)
