### ISSUE TITLE
Seed words:UI changes.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5832]
![original (10)](https://user-images.githubusercontent.com/62699947/171569486-497f72f0-effe-4292-9e5c-e4dbdaab665a.jpg)

- This ui is for entering, display is a little different. Doesn't have two columns and no space at the bottom.

**Comment by Pawan2792** [comment]
@cakesoft-swati  & @summikhan11  can you please explain UI changes here.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(485)
