### ISSUE TITLE
Live app:Post restore+Upgrade issue.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5850]
https://user-images.githubusercontent.com/62699947/173773979-fbaa0778-cca7-41a5-807b-66f4494260c2.MP4
- One of our user was not able to send from swan account.Then when he restored his wallet using cloud backup the accounts all showed with the correct names up but they were empty.And when he try to open his swan account the app crashed.
- He is on 2.0.75 but when he clicked the version history page it was blank.
- After the last upgrade his balance in the account was updated but the transaction history below wasn't updating.

**Comment by ASN-BitHyve** [comment]
@cakesoft-swati to test and either close or assign back to Pawan.

**Comment by Deveshshankar** [comment]
@cakesoft-swati was not able to reproduce.
