### ISSUE TITLE
Live app:Not able to restore the wallet.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5851]
- I had an upgraded app in ios which was upgraded from 2.0.65. In this app I had level 2 backup with personal device and personal copy. But at the time of wallet recovery, when I scanned the personal device QR, nothing happened and I was not able to login to the wallet.
![File (133)](https://user-images.githubusercontent.com/62699947/174035206-d9b46a04-5229-4f4c-b55a-70630613fca1.jpg)
![File (134)](https://user-images.githubusercontent.com/62699947/174035209-fe5e9ece-f9cb-4ab9-8f6c-52d8fac31d66.jpg)

- This is happening on ios Live app v2.0.75.I tried the same scenario on android dev app but didn't able to reproduce this.

**Comment by Parsh** [comment]
> The send issue was independent of the above issue, it was due to mainnet-wrapper going down which is now resolved.
