### ISSUE TITLE
Transaction list is not showing latest transactions.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5853]
- In live app 2.0.75 account is refreshing and it looks like received the funds but the transaction list  it's not showing the latest transaction[User Feedback].
- User picked up the send to address from Coinbase and used it to search on mempool.He found the sats but there were no receive transaction on Hexa.
- I also had the same issue in one of the previous live app.I had so many transactions in checking account.Then I sent some amount to that checking account.Send was successful but I didn't even see that amount in 'view more'.

**Comment by antuz123** [comment]
This is reported by a lot of people, the amount is getting updated but the transaction is not showing. This got introduced in 75 release I think

**Comment by bhumireddy99** [comment]
I have cross checked it yesterday, and i couldn't find any issues as such. Transactions are being updated properly
