### ISSUE TITLE
Live app:Not able to restore wallet.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5854]
- One of our user is having problem with his wallet hexa 2.0. He stored some sats in his checking account with the recovery key generated. Now he wanted to send there some more, but that never arrived, so he installed it on another device, but he could not restore it. The spin turns and turns but never anything shows up to enter that key. Then he  uninstall hexa with the checking account and now he can´t restore that as well.
![IMG_20220621_192124_894__01](https://user-images.githubusercontent.com/62699947/174817754-1d628799-f3d1-4291-a677-e034488c684d.jpg)
![IMG_20220621_192118_258__01](https://user-images.githubusercontent.com/62699947/174817748-71d78976-4e9d-418f-a1d9-dd6b14c49cb7.jpg)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(490)
- Unable to reproduce this issue.

**Comment by ASN-BitHyve** [comment]
@ASN-BitHyve to test
