### ISSUE TITLE
User unable to access Checking Account

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5857]
iPhone 7, software 15.5

"Since the latest update  2.0.75, I can’t access my checking account. When I try, the app shuts down. Please advise." 

![Upgrade history](https://user-images.githubusercontent.com/68264080/176826970-208263ed-e8c5-4bb6-8500-1630da18b169.jpg)

![ss](https://user-images.githubusercontent.com/68264080/183411404-02dcc534-106c-434a-a47b-31ae10b996db.jpg)

Source:
Gr*g - Twitter DM

**Comment by Pawan2792** [comment]
it's working at my end @cakesoft-swati  @ASN-BitHyve

**Comment by cakesoft-swati** [comment]
@ASN-BitHyve Can you please confirm it again?

**Comment by cakesoft-swati** [comment]
- Unable tp reproduce this issue.
- Tested on dev app v2.0.80(490)

**Comment by ASN-BitHyve** [comment]
User was able to access his funds after fix.
