### ISSUE TITLE
Gifts getting passed around not getting accepted

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5860]
I was testing the gift flow with Anant.

I had 2 kinds of gifts: 1) Freshly created gifts. 2) Ones that I had created earlier, had sent out earlier, and got back as they were unclaimed.

The first kind went and was accepted easily. Regarding the second kind, the app said gift expired in receiver phone and rejected in sender phone.

Also, the phone in which it said rejected... when I tried to reclaim the gift, the app just didn't respond. It didn't crash. But no response to the reclaim call to action.

Both my app and Anant's app were upgraded apps.

**Comment by Deveshshankar** [comment]
When user Clicks on accept gift the screen doesn't respond.
![WhatsApp Image 2022-07-18 at 1 41 29 PM](https://user-images.githubusercontent.com/107177634/179470960-5186f86e-6827-4a21-a1fc-4bcd8c46bccc.jpeg)
![WhatsApp Image 2022-07-18 at 1 42 22 PM](https://user-images.githubusercontent.com/107177634/179470975-f830003e-622e-449d-903b-e1ea19395ac3.jpeg)

**Comment by Deveshshankar** [comment]
After Accepting a gift this loading screen appears on the screen
![WhatsApp Image 2022-07-18 at 1 41 29 PM](https://user-images.githubusercontent.com/107177634/179907250-1c543860-15ee-485b-9cac-ee541dce8503.jpeg)
