### ISSUE TITLE
Keeper rejection notification Saying "F&F request rejected". It should say "Keeper request rejected"

### ISSUE THREAD

**Issue by Pawan2792** [bithyve/hexa#5863]

**Comment by Deveshshankar** [comment]
The above bug Resolved.
![Screenshot_20220721-172833_hexa dev](https://user-images.githubusercontent.com/107177634/180211098-de7b9234-ab9e-4bcc-80c2-96e46eafd5d9.jpg)
![Screenshot_20220721-172840_hexa dev](https://user-images.githubusercontent.com/107177634/180211116-14833487-8e18-4fc9-b541-252ca0162078.jpg)
