### ISSUE TITLE
Seed word transition

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5868]
Need a way for users having 24 seedwords backup recover in the 12 seedwords app.

A user had the live app that we released having 24 seedword backup. He backed-up using 24 seed words.

Then we went to 12 seedwords. He upgraded the app. 

Now he wants to recover his wallet, but has 24 seedwords while our app allows 12.

![photo_6226652000590868692_y](https://user-images.githubusercontent.com/68264080/178411000-0f8e5206-38f6-4408-be88-2380ba811a88.jpg)

Platform: TG
User: Cu**x

**Comment by Deveshshankar** [comment]
Resolved 
![Screenshot_2022-07-21-16-52-25-37_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/180204715-43ee89b9-ba43-49bf-ac1c-96cac8a5ed41.jpg)
![Screenshot_2022-07-21-16-59-25-94_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/180204719-b6ca2474-356c-440a-972b-ba6f3a97f2cc.jpg)
![Screenshot_2022-07-21-17-01-30-04_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/180204724-f09ce448-0a77-4760-a21e-137ba091fd16.jpg)
