### ISSUE TITLE
Redesign Hexa

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#5869]
some additional pieces to consider when adding new Backup/ Security screens to Hexa from HexaPay
1. As backup is now simpler it does not need its own tab and can go into settings. (Similar to HexaPay. Though there is no profile needed in Hexa at this point). We are only considering Seed Words and Cloud Backup at this point and not Keeper.
2.When there is a alert from the backup for health check, the CTA is driven from the messages on the screen. And the user directly lands on the backup history page with the relevant CTA to confirm the backup
3.In the settings the user will have the option of “Wallet Backup”. When no setup is done it will give the option of choosing one (like in Hexa Pay).
4.And when one is set up, it will show the history page of that backup e.g. Seed Backup or Cloud Backup. With CTAs to Change (to the other option) or to Confirm the backup.
5.The tab space available now, needs to be used for Gifts which is hidden away in the F&F tab. And needs to be taken away from the F&F tab.
6. So the tabs will be Home, F&F, Gifts and Settings.
7. Have also Shared the flows 
8. Check Image for reference

![Hexa Design ](https://user-images.githubusercontent.com/107177634/178486769-2ac26a3e-c93c-4d7a-ae92-b018d82902be.png)

**Comment by antuz123** [comment]
https://xd.adobe.com/view/2883dbb1-761e-4f51-91ae-4f76114e8fdb-7dd0/
