### ISSUE TITLE
Transaction priority:Text is getting cut off from the top.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5870]
![Screenshot_2022-07-13-13-46-53-41_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/62699947/178685804-b4820f72-cc68-4b34-b79a-049157190963.jpg)
- The text of the transaction priority is getting cut off from the top.

**Comment by Deveshshankar** [comment]
Fixed 
![33b90c13-9a50-4b86-8e6e-91e37e316afa](https://user-images.githubusercontent.com/107177634/179181678-6faa8d8e-8f85-43af-8d07-38ce800d66e1.jpg)
