### ISSUE TITLE
UI screen Required 

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5878]
- I had an app which was v 2.0.67(409). In that I was on level 2. After that I upgraded this app to 2.0.68(421) and again I upgraded it to 2.0.80(486). Then I went to security center and I changed google drive backup to seed word. In this it showed me the 24 word seed word, I confirmed it and it backed up successfully. After all this i restored the wallet with seed but it asked me only 12 seed words and when i restored it with cloud, its backed up successfully.

https://user-images.githubusercontent.com/62699947/179154919-c481ddb8-504f-4f1c-96e8-1bced7a18cdc.mp4

**Comment by Deveshshankar** [comment]
- I had an app which was v 2.0.67(409). In that I was on level 2. After that I upgraded this app to 2.0.68(421) and again I upgraded it to 2.0.80(486). Then I went to security center and I changed google drive backup to seed word. In this it showed me the 24 word seed word, I confirmed it and it backed up successfully. After all this i restored the wallet with seed but it asked me only 12 seed words and when i restored it with cloud, its backed up successfully.
- 
In this case we need UI Screen
We might Need to option when a user wants Restore wallet  Via seed word in above scenario.
1. I have 12 Seed Word 
2. I have 24 seed word
3. Individual Screen to Enter 12 and 24 seed to recover wallet
It Depends on you how you name it as in terms of UX.
