### ISSUE TITLE
Option to send Gift with FnF invite

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5885]
User Can share FnF invite and also they can add gift to the invitation.

**Comment by ASN-BitHyve** [comment]
@mide66 please speak with @Deveshshankar for context. This is to be done for Sprint 8.

**Comment by mide66** [comment]
https://xd.adobe.com/view/81d78db1-c1a6-4f7d-974f-eb56167a821d-d484/
@Pawan2792

**Comment by Deveshshankar** [comment]
Duplicate issue
