### ISSUE TITLE
Receive Sats

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#5888]
If we look at the Receive sats flow
step 1 User copy receive address and Clicks on enter amount to receive.
Step 2 The screen pops up with an option to enter an amount.
Step 3 The user Enters the amount and clicks on Receive or back.
Current Flow (Error )The first step that happens is the keypad is getting removed instead of Receive or back. This should not happen because our primary function must be to receive or Back.
It becomes 2 click process that can be done in one click.

https://user-images.githubusercontent.com/107177634/179978515-77d232b9-be80-43ab-8446-33dda025edab.mp4

**Comment by Vatsal032** [comment]
Duplicate issue. Same as #5904.

**Comment by Deveshshankar** [comment]
Completed
