### ISSUE TITLE
Gifting 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#5896]
On build 2.0.80(490)
When the user sends a gift via add recipient. 

1. If receiver accept the gift the screen loads and nothing happens.
(it works in the case of OTP)
![WhatsApp Image 2022-07-22 at 1 41 04 PM](https://user-images.githubusercontent.com/107177634/180394760-e2406893-49f0-416e-a3ab-1ce634c6760e.jpeg)

**Comment by Vatsal032** [comment]
Duplicate #5885

**Comment by Deveshshankar** [comment]
already resolved
