### ISSUE TITLE
 cloud backup (Inappropriate behaviour)

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#5901]
If a user clicks on recovery using key and after that he realises that he wants to recover using seed user don't have any options to come back he needs to kill the app or proceed via recovery wallet with  cloud.
Tested on live app(release)

https://user-images.githubusercontent.com/107177634/180763969-3685bfa5-4669-45fe-b390-e7369d86f907.mp4

**Comment by mide66** [comment]
We can include a "Back" secondary CTA beside Try again, which takes the user back to the wallet creation screen.
@ASN-BitHyve @Pawan2792 @Deveshshankar

**Comment by antuz123** [comment]
Try Again and Start Again. SA takes go to the first screen.

**Comment by Deveshshankar** [comment]
Done
