### ISSUE TITLE
Missing .env.example file in repo

### ISSUE THREAD

**Issue by emanuelb** [bithyve/hexa#5910]
file was removed in commit https://github.com/bithyve/hexa/commit/4840f740cf882bed61cdf83f5280d3b866a9fe4a

but instructions in README.md file say:
> Copy the contents on `.env.example` to a new `.env` file.

and compiling latest version 2.80 with `./gradlew assembleRelease` shows:

```
Configure project :app
Reading env from: .env
**************************
*** Missing .env file ****
**************************
```

**Comment by cakesoft-shashank** [comment]
[src/bitcoin/HexaConfig.ts](https://github.com/bithyve/hexa/blob/development/src/bitcoin/HexaConfig.ts) picks default dev env even if .env is not present

**Comment by Deveshshankar** [comment]
Closing Approved by CC @cakesoft-shashank
