### ISSUE TITLE
Wrap macos commands in os/command check in setup.sh to avoid "pod: not found" error

### ISSUE THREAD

**Issue by emanuelb** [bithyve/hexa#5911]
Running `yarnpkg install;` on the repo on linux will run:
`chmod +x setup.sh && sh ./setup.sh` which will show at end error:
```
patch cocoapods
./setup.sh: 15: pod: not found
```

the following commands in setup.sh should be run on MACOS OS only: as `pod` exists only on MACOS and the `sdk.dir` path starts with `/Users/` thats valid for macos only.

https://github.com/bithyve/hexa/blob/5ca3573ed29d62cb0751a6b00fa4a5aacf0c0ecd/setup.sh#L14-L18

thus they need to be wrapped in code like this (something that ensure os is MACOS or `pod` command is available) etc..

```shell
case "`uname`" in
  Darwin* )
    commands_for_macos
    ;;
esac
```

**Comment by Deveshshankar** [comment]
closing CC @cakesoft-shashank
