### ISSUE TITLE
Create Gift screens updation

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5929]
1) A user is creating a gift (not the satscard flow). If he creates one gift, the button should be "Create Gift". But in case he goes into Advanced option, selects multiple gifts, and comes back to the create gift tab, the button should change to "Create Gifts" (Gift to Gifts - Plural)

2) The "I have a satscard" button should go away if the user has selected multiple gifts.
![Uploading Simulator Screen Shot - iPhone 11 - 2022-08-23 at 20.16.27.png…]()

**Comment by Pawan2792** [comment]
Resolved
![Simulator Screen Shot - iPhone 11 - 2022-08-23 at 21 24 47](https://user-images.githubusercontent.com/99478432/186205182-eac2c237-f700-47c6-9069-2a3ece29cac8.png)

**Comment by Deveshshankar** [comment]
Completed
