### ISSUE TITLE
Indication when backup is not done

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#5936]
in design
![WhatsApp Image 2022-08-10 at 9 35 42 AM](https://user-images.githubusercontent.com/107177634/183812866-7fec90ef-0c10-4b86-bc15-3ca391cba64d.jpeg)
in dev
![WhatsApp Image 2022-08-10 at 9 35 53 AM](https://user-images.githubusercontent.com/107177634/183812937-d7d1cb68-f361-44d0-80c9-cccc9fbebb5f.jpeg)

**Comment by mide66** [comment]
![Settings   More](https://user-images.githubusercontent.com/60519891/186659458-3c26c423-dd33-49fc-8f03-2d80b52709a8.png)
https://xd.adobe.com/view/393ac9be-7ab3-4f66-8e35-d3052fee7fbe-6c69/
@Pawan2792
