### ISSUE TITLE
External Seed Words

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5957]
Currently the app does not accept Seed Words if App Image is not found. 

If app image is not found, it should just create a new wallet like a new creation 

![image](https://user-images.githubusercontent.com/43998049/185567895-98b1267d-d70c-4c7e-a42d-bf5ef0cce190.png)

**Comment by antuz123** [comment]
1. Wallet not found - CTA - Create New Wallet/ Try Again
2. CNW - Wallet Name?

**Comment by mide66** [comment]
https://xd.adobe.com/view/a14b2273-19ad-4c4c-976f-09bac56e5fa6-f418/

**Comment by Deveshshankar** [comment]
completed
