### ISSUE TITLE
App Crashing 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#5962]
While testing sats card in iOS (Device Supporting NFC)
Step:- 1 In Create gift User Enters the amount and Proceeds via Satscard
Step:- 2 Clicks on Detect satsCard 
App gets crashed.

See for reference 

https://user-images.githubusercontent.com/107177634/185857894-83b98173-4ba8-4a3b-8d0e-2576c8a4879b.MP4

**Comment by Pawan2792** [comment]
not able to reproduce @Deveshshankar

**Comment by Deveshshankar** [comment]
Need to check

**Comment by Deveshshankar** [comment]
Completed
