### ISSUE TITLE
Creating gift using satscard

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#5963]
While testing sats card in Android 
Step:- 1 If Create gift User Enters the amount and Proceeds via Satscard
Step:- 2 User Clicks on Detect satsCard
Step:- 3 Satscard Detected Successfully. 
Step:- 4 Balance was Zero so the entered sats were transferred successfully but on the final screen, it was unable to show how many sats were transferred.

**Comment by ASN-BitHyve** [comment]
"The transfer is yet unconfirmed. It will be confirmed in ~<mention minutes from blockstream> minutes."

**Comment by Deveshshankar** [comment]
to be implemented

**Comment by Deveshshankar** [comment]
Fixed
