### ISSUE TITLE
Change to Seed for legacy users (Level 2/3) - Issue 1 of 2 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5968]
The user should be able to change the backup from Level 2 and Level 3 to Seed word-based backup. (Old Hexa User)

1) When such a user logs in - The notification on top should say - “Please switch to Seed Words Backup”. There is a red icon there.

2) On clicking, “Please switch to Seed Words Backup” the user is taken to the Settings tab > Wallet backup. There the user is prompted to "Change to Seed Word backup". On clicking "Change to Seed Word backup" there are 3 possible scenarios:

Scenario 1: When the Savings Account is empty and archived: - In this case the user is taken to the backup using Seed Words flow.
Scenario 2: In case there are no Sats in the savings account, a modal pops up telling the user to archive the Savings Account with the major CTA being “Archive Now”. Clicking that button would archive the Savings Account and take the user to the next screen where the seed words are shown to him.
Scenario 3: In case there are Sats in the savings account, a modal pops up telling the user to empty the Savings Account and archive it. Major CTA is “Sweep Now”. The user is taken to the Savings Account. With an intent for him to empty it. The user empties the Savings Account. The wallet recognizes if the user has come from a Seed Words backup flow. If he has, in the Sent Successfully toast message itself, we give “Archive Account” as major CTA.  After account is archived, the user is taken to the screen with the seed words for him to write it down. 
Note to Pawan: The wallet will have to identify what state the Savings Account is in and then give corresponding error message.) 

3) Also, note that the backup is now in settings, not at the Home Screen tab, so the layout will be different. 
4) The backup will have a suggested/ major CTA to " Move to Seed Words Backup". Also, the settings will have a red dot as if something is suggested, along with a red dot in Wallet Backup in settings. (The red dot goes away when the user has moved to seed word backup). 
5) Once the user notes the seed words, they cannot return to Level 2 or 3. We can reuse the screen here that allows users to back up in the first place. The seed words should be 12 words if possible, else 24 words.

**Comment by ASN-BitHyve** [comment]
User is having levels based backup.

We now want them to stop using levels based backup and start using Seed Words based backup.

When such a user logs in - The notification on top should say - “Please switch to Seed Words Backup”. There is a red icon there.

On clicking, “Please switch to Seed Words Backup” the user is taken to the Settings tab > Wallet backup. There is a Red dot here too. The subtext there should say, “Backup wallet using Seed Words.”

User clicks on the Wallet Backup button. 

He clicks on “Write Down Seed Words”. 


Case 1: In case there are no Sats in the savings account, a modal pops up telling the user to archive the Savings Account with the major CTA being “Archive Now”. Clicking that button would archive the Savings Account and take the user to the next screen where the seed words are shown to him.

Case 2: In case there are Sats in the savings account, a modal pops up telling the user to empty the Savings Account and archive it. Major CTA is “Proceed”. The user is taken to the Savings Account. With an intent for him to empty it. The user empties the Savings Account. The wallet recognizes if the user has come from a Seed Words backup flow. If he has, in the Sent Successfully toast message itself, we give “Archive Account” as major CTA. After account is archived, the user is taken to the screen with the seed words for him to write it down.

Rest of the procedure is as per normal backup for new users. 

After the backup process is complete, the levels based backup should be completely erased from the wallet and the user’s cloud.

**Comment by antuz123** [comment]
https://xd.adobe.com/view/a14b2273-19ad-4c4c-976f-09bac56e5fa6-f418/

**Comment by Pawan2792** [comment]
@Deveshshankar  Scenario 3 is pending (Sweep fund)


Scenario 3: In case there are Sats in the savings account, a modal pops up telling the user to empty the Savings Account and archive it. Major CTA is “Sweep Now”. The user is taken to the Savings Account. With an intent for him to empty it. The user empties the Savings Account. The wallet recognizes if the user has come from a Seed Words backup flow. If he has, in the Sent Successfully toast message itself, we give “Archive Account” as major CTA. After account is archived, the user is taken to the screen with the seed words for him to write it down.
