### ISSUE TITLE
Auto-populate seed words 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5969]
like other apps, the seed words should be auto-suggested when you key in a few letters

**Comment by mide66** [comment]
![Enter Seed Words – Enter 3 Word Suggestions](https://user-images.githubusercontent.com/60519891/186162718-b62ecd63-bda8-469c-9a18-126d319d0020.png)
@antuz123

**Comment by mide66** [comment]
![Enter Seed Words – Enter 3 Word Suggestions – 1](https://user-images.githubusercontent.com/60519891/186529859-e7538422-da84-4add-b32c-5f42f5a3e547.png)
@antuz123 @cakesoft-shashank

**Comment by Deveshshankar** [comment]
Completed
