### ISSUE TITLE
Remove Cloud backup option. 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5979]
See details - https://github.com/bithyve/bitcoin-keeper/issues/806

**Comment by mide66** [comment]
https://xd.adobe.com/view/a14b2273-19ad-4c4c-976f-09bac56e5fa6-f418/
@antuz123 @cakesoft-shashank

**Comment by Deveshshankar** [comment]
Cloud Backup is still available for new users (495)

**Comment by Deveshshankar** [comment]
Completed
