### ISSUE TITLE
Clipboard Reading in app

### ISSUE THREAD

**Issue by Pawan2792** [bithyve/hexa#5983]
The app should be able to automatically detect BTC addresses and lightning invoices from the clipboard.
Need to check with @antuz123 sir there was some security concern.

1. Please share assets for Screen Shot 1 & also share brand text
![Screenshot_1661406128](https://user-images.githubusercontent.com/99478432/186649085-a8c8ee41-f321-445d-83df-639c0f7b268d.png)

2. Do we need to create a new screen for Allow Clipboard? 
![Screenshot_1661406166](https://user-images.githubusercontent.com/99478432/186649164-ad097b8a-d43d-4e79-b8b0-a646d0b97e62.png)

3. when Detect address in clipboard then need to redesign modal according to Hexa Flow.
![Screenshot_1661406278](https://user-images.githubusercontent.com/99478432/186649179-d27ac033-b67d-427c-a355-1a6599bd7c22.png)

Hexa XD Link for Reference:- https://xd.adobe.com/view/24cad77c-7eb9-4623-a2dc-edf64b9e4743-7199/screen/22c50228-527f-4faf-bbb3-945a98b09ba0/

**Comment by mide66** [comment]
https://xd.adobe.com/view/ebae18ce-2577-4d53-9b75-cb9ae5317eb1-befd/
@Pawan2792 
![Screenshot (32)](https://user-images.githubusercontent.com/60519891/187318505-341ede9a-a752-49a4-b2ee-da0ed1100f5e.png)

**Comment by Deveshshankar** [comment]
Check image

**Comment by Deveshshankar** [comment]
Need to check with @antuz123 sir there was some security cocern.

**Comment by Deveshshankar** [comment]
Not as per plan
