### ISSUE TITLE
Check icon alignment

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5988]
The icons do not seem to be top/middle/bottom aligned.
![photo_6082524447304167801_y](https://user-images.githubusercontent.com/68264080/187176355-c3a878f3-cb06-45f0-a737-9432d699427a.jpg)

Yusuf: After verification if you find that the icons are misaligned, please rectify them, share the screen xd link here, remove your assignment and tag Pawan.

**Comment by mide66** [comment]
https://xd.adobe.com/view/a14b2273-19ad-4c4c-976f-09bac56e5fa6-f418/
@Pawan2792

**Comment by Deveshshankar** [comment]
Completed
