### ISSUE TITLE
Wallet Backup screen needs reimagination

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5989]
With Cloud Backup going out, this screen will have a lot of empty space. We'll have to reimagine it.
![photo_6082524447304167810_y](https://user-images.githubusercontent.com/68264080/187180638-57312159-a56c-46b6-a28b-da34e0ffeb63.jpg)

Scenario 1: Reimagination for new users.
Scenario 2: Reimagination considering old users who have levels based backup.

**Comment by mide66** [comment]
So, I'm suggesting we remove this screen since there's just one option there. Settings>wallet backup>seed words history
https://xd.adobe.com/view/ebae18ce-2577-4d53-9b75-cb9ae5317eb1-befd/
