### ISSUE TITLE
Arrangement of setting tab options

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#5994]
Yusuf to decide with abhilash regarding Setting tab options as there are too many options we need to make it less adding similar options in the same options to make it sort. adding "Tor enabled" to the setting section as well.

**Comment by mide66** [comment]
https://xd.adobe.com/view/ebae18ce-2577-4d53-9b75-cb9ae5317eb1-befd/

**Comment by Deveshshankar** [comment]
Need to look at the Design made by @mide66
