### ISSUE TITLE
Change to Seed for legacy users - Part 2 of 2

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5995]
User is having levels based backup.

We now want them to stop using levels based backup and start using Seed Words based backup.

When such a user logs in - The notification on top should say - “Please switch to Seed Words Backup”. There is a red icon there.

On clicking, “Please switch to Seed Words Backup” the user is taken to the Settings tab > Wallet backup. There is a Red dot here too. The subtext there should say, “Backup wallet using Seed Words.”

User clicks on the Wallet Backup button.

He clicks on “Write Down Seed Words”.

Case 1: In case there are no Sats in the savings account, a modal pops up telling the user to archive the Savings Account with the major CTA being “Archive Now”. Clicking that button would archive the Savings Account and take the user to the next screen where the seed words are shown to him.

Case 2: In case there are Sats in the savings account, a modal pops up telling the user to empty the Savings Account and archive it. Major CTA is “Sweep Now”. The user is taken to the Savings Account. With an intent for him to empty it. The user empties the Savings Account. The wallet recognizes if the user has come from a Seed Words backup flow. If he has, in the Sent Successfully toast message itself, we give “Archive Account” as major CTA. After account is archived, the user is taken to the screen with the seed words for him to write it down.

Rest of the procedure is as per normal backup for new users.

After the backup process is complete, the levels based backup should be completely erased from the wallet and the user’s cloud.

**Comment by mide66** [comment]
https://xd.adobe.com/view/a14b2273-19ad-4c4c-976f-09bac56e5fa6-f418/
@ASN-BitHyve

**Comment by Deveshshankar** [comment]
Completed
