### ISSUE TITLE
Seed Word health - trigger 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5996]
1. Health confirmation timestamp is set every time the user confirms the SW health or when the wallet is created or restored. Seed health flag is set to true.  
2. Every log in the app checks how if the confirmation time stamp is more than 180 days old
3. If yes (**or the confirmation timestamp is null**) the Seed Health flag is set to false 
4. If the flag is false, the settings and the wallet backup have an indicator and the UAI changes to "Confirm your Wallet Backup". This is also the subtext in Wallet Backup.  
5. When user comes to Wallet Backup, they are asked to confirm the Health by providing a seed word (random) 
6. If the user confirms, the confirmation timestamp is set to the current time and the SW health is set to true

**Comment by mide66** [comment]
https://xd.adobe.com/view/ebae18ce-2577-4d53-9b75-cb9ae5317eb1-befd/

**Comment by Deveshshankar** [comment]
Fixed
