### ISSUE TITLE
Capital letters and gear image

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5997]
The gear image doesn't look right. Please use Summi's reference design.
![Screenshot_20220830-153310_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/187410272-35781497-b862-4aae-8828-2ea50e3a06ec.jpg)

**Comment by Deveshshankar** [comment]
The image bug still remains.

**Comment by Deveshshankar** [comment]
Image is not required as there is no animation.
