### ISSUE TITLE
Radio button placement to be rectified.

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5998]
![Screenshot_20220830-155408_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/187414445-4944610d-92bf-47a8-b9a5-1ddd83786e4e.jpg)

**Comment by mide66** [comment]
I don't have these screens

**Comment by mide66** [comment]
https://xd.adobe.com/view/ebae18ce-2577-4d53-9b75-cb9ae5317eb1-befd/
@Pawan2792 
![radio placement](https://user-images.githubusercontent.com/60519891/187681389-79905f47-e76f-4fce-9921-11947face75a.png)

**Comment by Deveshshankar** [comment]
done
