### ISSUE TITLE
All modal should have close button

### ISSUE THREAD

**Issue by Pawan2792** [bithyve/hexa#5999]
Need to implement all modal should have a close button on the right side.

![Uploading Screenshot 2022-08-30 at 4.10.03 PM.png…]()

Reference XD link:- https://xd.adobe.com/view/a14b2273-19ad-4c4c-976f-09bac56e5fa6-f418/screen/cab3c7c9-acf2-4974-b801-6ba8fc0055c1/

**Comment by antuz123** [comment]
No x button on log in or wallet creation modal or any such modal.

**Comment by Deveshshankar** [comment]
to test and close @Deveshshankar

**Comment by Deveshshankar** [comment]
Completed
