### ISSUE TITLE
Font size looks different 

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#6000]
There Should be a proper gapping between heading and subheading.
![Screenshot_20220830-162525_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/187419401-b00735d1-1851-494b-9ac1-7d07cc9fb5f1.jpg)

**Comment by mide66** [comment]
Font is Fira sans

**Comment by mide66** [comment]
Font is fira sans

**Comment by GourabSanyal** [comment]
design [link](https://xd.adobe.com/view/81d78db1-c1a6-4f7d-974f-eb56167a821d-d484/) for reference.
