### ISSUE TITLE
Position of the word sats to be checked

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#6001]
Right now it's elevated and looking weird

![Screenshot_20220830-162924_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/187420044-662070c2-e038-4413-99eb-98f7bb30eaf5.jpg)

**Comment by mide66** [comment]
Sats are bottom aligned. @Pawan2792

**Comment by Deveshshankar** [comment]
not fixed same issue

**Comment by Deveshshankar** [comment]
Completed
