### ISSUE TITLE
Removing a friend and refreshing is going into an endless loop

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#6014]
I had Hexa dev. I upgraded it. I had Anant as friend already ( from the previous version of the app). I removed him as contact and refreshed this screen. The app stopped responding apart from the refresh icon going in circles.

![Screenshot_20220902-152800_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/188115439-b6edb2b6-b78d-41f8-8d35-63cfb3548733.jpg)

**Comment by Deveshshankar** [comment]
done
