### ISSUE TITLE
Accepted yet awaited

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#6016]
Sent out a friend request by skipping contact. Anant accepted it. Got a notification. But in the FnF section Anant is not showing up as a contact. Pulled down to refresh. Killed the app and restarted. Still didn't work.
![Screenshot_20220902-154457_hexa dev.jpg](https://user-images.githubusercontent.com/68264080/188118357-a65292e9-53a3-4c19-be0c-209b27530fd5.jpg)

**Comment by Vatsal032** [comment]
Unable to reproduce. Is there something I'm missing while trying to recreate?

**Comment by Deveshshankar** [comment]
@Vatsal032 It is a bug.

**Comment by Deveshshankar** [comment]
completed user has to refresh it.
