### ISSUE TITLE
level 1 &2 to seed word

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#6025]
Step 1. The user upgraded the app. From 2.0.67(496) to 2.0.90 (496)
Step 2. There were notifications It was saying "Personal device needs your attention".
Step 3. The user skipped this and did the "Change to Seed word Backup"
Step 4. The User was able to do it.

Ideal behavior: Any user upgrading from a non-seed backup scheme. No matter if the backup is complete or not or which version they come from.
If not seed-backup, then the message should be. “Wallet backup not complete”. That message will go only after the seed backup is done.

reference image 
![Screenshot_2022-09-06-12-24-59-65_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/188572184-1cf07f5e-3a61-4d8f-ae3d-7778c33d6044.jpg)
![Screenshot_2022-09-06-12-32-44-86_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/188572202-a8398755-dc13-4f11-8c8d-b30a46bc4605.jpg)

**Comment by Pawan2792** [comment]
@Deveshshankar  Please test in new Release Build 2.0.90(497)
