### ISSUE TITLE
Invalid mnemonic

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#6026]
while recovering wallet via seed word
![Screenshot_2022-09-06-15-24-29-26_6ccb4bf936ab2cedd5e025652c6047ae (1)](https://user-images.githubusercontent.com/107177634/188606647-da04af90-44a8-45c1-b9f4-4c1e53d4e136.jpg)

**Comment by Pawan2792** [comment]
@Deveshshankar  it's working fine with hexa seed

**Comment by Deveshshankar** [comment]
Work fine in both case
