### ISSUE TITLE
Write down seed word.

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#6038]
Condition:- New User who is Creating his wallet and doing Backup with seed as we have only seed option to backup.
Do we really need that pop-up to proceed if he clicks on  "write down seed word" 
ideal: We can directly display the seed words instead of clicking on the "proceed button" and displaying the seed. 

https://user-images.githubusercontent.com/107177634/188821920-d9901610-944d-4f43-acab-2e3efb773984.mp4

**Comment by mide66** [comment]
@Deveshshankar is correct! That was what I suggested in the call yesterday. Since there's only one option, we should eliminate the "write down seed words" screen.
@Pawan2792

**Comment by Deveshshankar** [comment]
done this issue in sprint 7

**Comment by Deveshshankar** [comment]
completed
