### ISSUE TITLE
Friends and Family request Modal not opening using the link

### ISSUE THREAD

**Issue by Vatsal032** [bithyve/hexa#6039]
1. Generated a F&F request, **without selecting any contact from my address book**.
2. Shared this link and the OTP.
3. When opened the link, for both the app in background or terminated, the app opened but the Modal to enter the OTP didn't open.

The issue is required to be solved first in order to solve #6016

**Comment by Vatsal032** [comment]
The issue appears to be happening only with the links I created from my device. Rest all seem to work fine.

**Comment by Deveshshankar** [comment]
Done
