### ISSUE TITLE
An image of Seed Words backup required for App/Play Stores

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#6044]
With the new backup scheme coming in we need to replace the levels based backup image in both stores. 

We need an image with the screen depicting our UX of SeedWords. 

Headline: "Backup with Seed Words"

Please speak with Summi for dimensions of the images. We require 4 different dimensions if I remember correctly.

**Comment by mide66** [comment]
![iPhone 6 Google Pixel 2 – App Store – Backup with Seed words – 1](https://user-images.githubusercontent.com/60519891/189151577-b1ae5a15-2662-424c-b2b5-2247b7518298.png)
![iPhone XR-XS Max-11 – App Store – backup with seed words – 1](https://user-images.githubusercontent.com/60519891/189151584-a7945c47-0809-4e8b-b5b7-650573f716e6.png)
@ASN-BitHyve
