### ISSUE TITLE
Enter OTP and confirm

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#6053]
case :3  "Change to Seed word Backup"
When I tried to sweep funds In 2 FA Verification.
Some OTP-related issues as you can see if I enter OTP and confirm. The button is not responding. 
if the OTP is incorrect there should be some error message or indication.

https://user-images.githubusercontent.com/107177634/189053791-76ee61e0-585a-47d1-8297-a3e79f9ab60f.mp4

**Comment by cakesoft-swati** [comment]
Uploading Record_2022-09-08-11-40-52.mp4…

**Comment by Deveshshankar** [comment]
Done
