### ISSUE TITLE
Adding CTA to show Backup

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#6061]
Need a secondary action to “Forgot Phrase ”. This takes the user through the process of confirming the passcode, then noting it down.
Also need to Create a passcode Screen where the user will enter the passcode to reveal the backup phrase.

<img width="215" alt="Screenshot 2022-09-08 at 3 57 44 PM" src="https://user-images.githubusercontent.com/107177634/189100011-49ea0e74-941b-422e-8cef-a9accb3b2a1a.png">

**Comment by Pawan2792** [comment]
@Deveshshankar  @antuz123  is this text fine for Show seed words again ?
![Simulator Screen Shot - iPhone 8 Plus - 2022-09-09 at 01 15 08](https://user-images.githubusercontent.com/99478432/189271540-5d1f7e60-624e-4abe-ab30-f26054210c2a.png)
