### ISSUE TITLE
Seed Word Icon 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#6072]
Refer to design for Seed Word icon

<img width="253" alt="Screenshot 2022-09-09 at 10 26 34 AM" src="https://user-images.githubusercontent.com/107177634/189275076-b17bd631-e116-4e27-8ea2-ad647bcc42a0.png">

**Comment by Pawan2792** [comment]
@mide66  Please share icon or XD file i can export icon from XD

**Comment by akshay8551** [comment]
@mide66 would please share xd link with this(seed) icon.

**Comment by mide66** [comment]
![Icons - Finance-Security - receipt](https://user-images.githubusercontent.com/60519891/191704999-ee8d38cb-2e3c-4ca9-aa8d-5d0864378566.svg)
