### ISSUE TITLE
indication in Setting tab

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#6075]
To keep Indication on the "setting tab" that we have in this below image When Wallet Backup is incomplete.
<img width="186" alt="Screenshot 2022-09-09 at 10 25 34 AM" src="https://user-images.githubusercontent.com/107177634/189286807-ad7c2d93-e2cb-49f9-9bec-ce97347c3aaa.png">

**Comment by mide66** [comment]
yes
