### ISSUE TITLE
Backup phrase Screen 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/hexa#6097]
1. User should be shown 1 phrase at a time.
2. user should not be able to take ss.
![File (10)](https://user-images.githubusercontent.com/107177634/189868574-7b278fe0-66a1-49aa-912a-8fbcda4bfcfa.jpg)
g

**Comment by Pawan2792** [comment]
@Deveshshankar  it's working fine at my end
![File](https://user-images.githubusercontent.com/99478432/189886444-43028e0d-eba5-452a-b576-62acd4fd849e.jpg)
