### ISSUE TITLE
Send/Receive Acting up in the live app

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#6284]
- [ ] The wallet is able to receive gifts. But unable to transfer those gifts into the Checking Account. 
- [ ] Already existing gifts are also not getting shifted into the Checking Account when I click on "Add to Account" button.
- [ ] A user has said that he's unable to send/receive sats as well. The error he's receiving says: Send Unsuccessful - undefined is not an object (evaluating 'Object.keys(v)')

Image below is when Devesh tried to accept a gift from Anant. He was able to accept it but it didn't reflect in the Checking Account. The loading icon kept going round in circles.  
![File (1)](https://user-images.githubusercontent.com/68264080/207796997-6d4e808d-962d-4ffe-a781-b8b0a1e396f3.jpg)

Image below is when I've sent a gift to the account. It says successfully added, but its not getting there.

![photo_6111944264612164201_y](https://user-images.githubusercontent.com/68264080/207798076-67e22256-5dd4-4dbd-a0ef-bfe6ba7b79f4.jpg)

Image below is the view within the Checking Account. Separately, note how the send button says, "Transaction fee: undefined"

![photo_6111944264612164202_y](https://user-images.githubusercontent.com/68264080/207798281-74167b7f-9c24-40eb-be92-d985c88458d1.jpg)

This is happening on both iOS and Android.

**Comment by Deveshshankar** [comment]
Resolved
