### ISSUE TITLE
QR code scanner.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#636]
===============
Steps to reproduce:
===============
1.Open the app and click on QR scanner.
2.Scan any QR code and observe the scanner.

==========
Actual Result:
==========
After scanning, the screen initiated another scan.

=============
Expected Result:
=============
It should scan the QR  properly.

**Comment by antuz123** [comment]
Not sure, please check

**Comment by Arpanjainson** [comment]
Go to https://hrf.org/donate-bitcoin/payjoin/ - click pay with BTC pay to generate QR and then scan from send flow
.
[https://bithyve-workspace.slack.com/files/UEAKAPHFU/F018LLQMC3W/file_from_ios.mp4](url)

**Comment by abdulmuneer22** [comment]
<img width="389" alt="Screenshot 2020-08-11 at 08 42 29" src="https://user-images.githubusercontent.com/4398018/89853269-9b07e600-dbae-11ea-89e9-4c79ec06e306.png">


@Arpanjainson  , Tried sending to this address, but getting an error saying "Enter Correct Address"

**Comment by antuz123** [comment]
This is because this is main net address and you are trying from dev app that only has test net. Try staging or live app

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Arpanjainson** [comment]
Tested on testnet.. works fine.
try this
![image](https://user-images.githubusercontent.com/8697909/90011363-18bb1700-dcbf-11ea-8689-cf3c5135d022.png)

**Comment by cakesoft-swati** [comment]
Working for me.
