### ISSUE TITLE
Personal copy PDF

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#644]
===============
steps to reproduce:
===============
1.Go to the Manage Backup and click on Personal Copy.
2.Try to send PDF on own email id via email.
3.Observe the received email.

===========
Actual Result:
===========
-There is no attached pdf in received email.
- Sometimes there is nothing in that attached PDf.

=============
Expected Result:
=============
-Email should contain a personal copy PDF with appropriate content.

cc: @Parsh @AliMeer

**Comment by hemantsain** [comment]
Fixed and merged into development.
