### ISSUE TITLE
Internet modal on splash screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#685]
-The internet modal is still coming on the splash screen.
![iternet modal](https://user-images.githubusercontent.com/62699947/84501084-7ccb5a00-acd3-11ea-8f07-2cd1654d1911.PNG)

**Comment by antuz123** [comment]
It should never come before the login screen

**Comment by abdulmuneer22** [comment]
@cakesoft-swati , I have tried to re-produce, could not reproduce.
could you please check ?, if it's reproducible please share steps (if any)

**Comment by cakesoft-swati** [comment]
Not able to reproduce this.
