### ISSUE TITLE
Receive screen changes.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#689]
-On clicking QR or link, the modal should come up just below the contact details. 
-The contact details will move up a little as we don’t need to change the account. 
-The background should go grey like when loading.

![receiveqrht](https://user-images.githubusercontent.com/62699947/84503451-dafa3c00-acd7-11ea-9b39-84d6dc276102.jpg)

-Don’t need anything above this line. 
-The modal that opens up should be short and the rest is visible on the parent screen anyway.
![dntabovelin](https://user-images.githubusercontent.com/62699947/84503803-7f7c7e00-acd8-11ea-8b61-0bd2c1c26ae5.jpg)

-Don’t need above this line.
![aboveline](https://user-images.githubusercontent.com/62699947/84503905-ab97ff00-acd8-11ea-9ee3-b93bf5414c55.jpg)

-When coming from a certain account, this is selected and not editable. 
-Need a non editable version here. Only when generated from outside the accounts.
![nonedit](https://user-images.githubusercontent.com/62699947/84504113-ff0a4d00-acd8-11ea-9b07-559bad1c17f3.jpg)

-The link Getting cut.
![linkcut](https://user-images.githubusercontent.com/62699947/84504422-89eb4780-acd9-11ea-9aa3-a18c8a4c148d.jpg)

-In the text "Receving To",the T should be small t.
![smallt](https://user-images.githubusercontent.com/62699947/84504612-dd5d9580-acd9-11ea-9987-7045c0495233.jpg)

![t](https://user-images.githubusercontent.com/62699947/84504688-fbc39100-acd9-11ea-955f-21e260180d1a.jpg)

-we can’t change it on this "Receive via QR" screen.
- Need a UX that shows this as uneditable.
![uneditable](https://user-images.githubusercontent.com/62699947/84504825-3b8a7880-acda-11ea-9fc4-78774660ebb5.jpg)

-On receive screen,the Note should be like:
   -Sharing options. Use any of the methods shown to share the request link or Bitcoin address.
![sharingopt](https://user-images.githubusercontent.com/62699947/84504993-8efcc680-acda-11ea-88b1-aa7eb8b7dbfd.jpg)

-Remove this line from "Receive via Link" modal.
![remove](https://user-images.githubusercontent.com/62699947/84505211-f7e43e80-acda-11ea-9327-ed3a1eb959af.jpg)

**Comment by cakesoft-nikhita** [comment]
As per discussed,
1. Change the top headline to be only ‘Receive’
2. On the action buttons at the bottom, it should be ‘Share’ and ‘QR’
3. On the link modal, the heading should be ‘Share’
4. The second line should be ‘Share with your contact’ if it is a link. or ‘Share bitcoin address’ if it is an address. (this can be decided based on the checkbox selection on the main screen.
5. For QR model, the headline should be ‘QR’. Second line should be what is there now.
