### ISSUE TITLE
Some minor changes in app.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#704]
-No full stop. 
![nofullstphome](https://user-images.githubusercontent.com/62699947/84660373-5bb67380-af36-11ea-8c96-6edd0d47ae5c.jpg)

-Security Question. Not Questions. Remove s.
![removes](https://user-images.githubusercontent.com/62699947/84660500-915b5c80-af36-11ea-8b28-106439ff5456.jpg)

-Remove the last ‘s’
![removelasts](https://user-images.githubusercontent.com/62699947/84661821-84d80380-af38-11ea-93ca-d773380fe64f.jpg)

**Comment by shreyasnisal** [comment]
Text on Launch Screen (Hexa animation) cannot be changed from code since it is part of the animation video
