### ISSUE TITLE
Receive via QR

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#713]
-The QR is not rendered properly.
![QRrecv](https://user-images.githubusercontent.com/62699947/84862594-0fcc1180-b091-11ea-94a3-6d36a839c57d.jpg)

-The text should be: Scan bitcoin address
![rcvqrtxt](https://user-images.githubusercontent.com/62699947/84862750-5c175180-b091-11ea-91d1-a7f8a06cbbea.jpg)

-

**Comment by cakesoft-nikhita** [comment]
Assigning this bug to Muneer for QR issue. On development branch QR is working Perfect.
