### ISSUE TITLE
Toast behaviour which appears on Trusted contact.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#759]
-When accepting a trusted contact request, if the trusted contact already exists, it shows a toast. 
-If you click "Confirm" again and again, these toasts pile up on top of each other.
- We should check this for other toasts as well.

**Comment by shreyasnisal** [comment]
Behavior is completely different on staging and dev apps. In dev, it shows a toast "You cannot be your own keeper/guardian" and closes the bottom sheet altogether
