### ISSUE TITLE
UI issue while selecting the security question.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#760]
-At the time of Restore wallet When we select a security question, that downward arrow get overlaps with the  text.
![arrowoverlap](https://user-images.githubusercontent.com/62699947/85281129-1ac6dd80-b4a7-11ea-8e48-bb1efb80b4a9.jpg)

**Comment by shreyasnisal** [comment]
In my device, the text wraps instead of overlapping on the arrow
