### ISSUE TITLE
Changes on Friends and Family screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#768]
-Tried resharing a secret to same contact- shows up twice in address book Says pending after 24 hrs. -May be need to say expired, and once inside the card say reshare.

-Added a contact using “add trusted contact” once the modal was closed I had to refresh the main screen to see the contact which I added.
![resharetwice](https://user-images.githubusercontent.com/62699947/85290535-c7f52200-b4b6-11ea-8268-0e8bcfcbafae.jpg)

**Comment by Parsh** [comment]
Resolved
