### ISSUE TITLE
Lorem Ipsum text changes.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#776]
-Remove the Note. 
-The text will be ‘Open your PDF copy which is password protected with your Secret Answer’. 
![IMG_0616](https://user-images.githubusercontent.com/62699947/85294468-4accab80-b4bc-11ea-8547-5b19d3a40194.PNG)

-Take out the text.
![IMG_0617](https://user-images.githubusercontent.com/62699947/85294650-87000c00-b4bc-11ea-86dc-50c396c85dcf.PNG)

-Take out the note.
- The text will be: ‘Select your local currency’
![IMG_0618](https://user-images.githubusercontent.com/62699947/85294710-9da66300-b4bc-11ea-820e-8cfe957c4123.PNG)

-Sent Successfully screen:
 1. The sub title will be: Transactions successfully submitted
 2.The lorem Ipsum will be:
    The transaction has been submitted to the Bitcoin network. View transactions on the account 
    screen for details
    
![IMG_0620 (1)](https://user-images.githubusercontent.com/62699947/85391285-9720f580-b567-11ea-9ccc-21f2846bd0f4.PNG)

-Top subtitle: if your 2FA is not working follow one of the below steps
![IMG_0640](https://user-images.githubusercontent.com/62699947/85828782-c8d3cf80-b7a6-11ea-8209-864e44c699de.PNG)

**Comment by antuz123** [comment]
@cakesoft-swati to confirm
