### ISSUE TITLE
App upgrade screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#780]
-This app upgrade related screen should appear when I am on an older version not on the latest.
![upgradescreen](https://user-images.githubusercontent.com/62699947/85387200-29be9600-b562-11ea-836d-4d7f97966c41.jpg)

-Also the action is not taking us to the App Store with Hexa.
![actionbutton](https://user-images.githubusercontent.com/62699947/85387584-a0f42a00-b562-11ea-8a94-70d5b44cfaaa.jpg)

**Comment by cakesoft-nikhita** [comment]
Staging and Dev will open Prod app URL since staging and Dev do not have Play Store URLs or App store url.
