### ISSUE TITLE
Message chnage on "Reject request"

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#797]
-Wrong message on ‘Reject Request’. 
-It should just say ‘Request Rejected’
![rejectreqmsg](https://user-images.githubusercontent.com/62699947/85508736-44504800-b612-11ea-815a-4d967325bc8e.jpg)

**Comment by Parsh** [comment]
The error message is for invalid decryption (we would need to have an alternate message if the request is rejected (no input press).
