### ISSUE TITLE
Test message along with deeplink 

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#804]
In addition to the deep link, we should add a small message about the request. 

F&F request  - "Click here to accept contact request from "xxx" Hexa wallet - link will expire in xx minutes."
Keeper request  - "Click here to accept Keeper request for "xxx" Hexa wallet - link will expire in xx minutes."
Recovery Key request -"Click here to help "xxx" restore their Hexa wallet- link will expire in xx minutes.

**Comment by Arpanjainson** [comment]
@antuz123 lets prioritize this. Shreyas can handle this quickly

**Comment by Arpanjainson** [comment]
@antuz123 lets prioritize this. Shreyas can handle this quickly

**Comment by cakesoft-swati** [comment]
-The recovery request message does not have the new message.
-Message should be:Recovery Key request -"Click here to help "xxx" restore their Hexa wallet- link will expire in xx minutes
