### ISSUE TITLE
OTP mechanism for TC

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#806]
- Contacts without phone-number/email should be visible in the contact list
- Deep links for such contacts, when added as trusted contacts, should be OTP encrypted.

**Comment by cakesoft-nikhita** [comment]
Contacts without phone-number/email should be visible in the contact list 
This issue resolved in Address Book #1079 bug

**Comment by cakesoft-swati** [comment]
Does not allow access to the alphabets.
