### ISSUE TITLE
Lorem ipsum text changes.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#826]
-Scan the Regenerate/ Exit Key. This can be found on the last page of your PDF personal copy.
-Remove Note.
![Reset2FA](https://user-images.githubusercontent.com/62699947/85835382-9cbe4b80-b7b2-11ea-9994-43d6e5c4f7c0.jpg)

-Need back button.
![bckbtn](https://user-images.githubusercontent.com/62699947/85835664-0fc7c200-b7b3-11ea-8e26-350ebb96d299.jpg)

-Heading will be: ‘The Server is not responding?’
![server](https://user-images.githubusercontent.com/62699947/85836091-b744f480-b7b3-11ea-9c7d-c6761b7bc24c.jpg)

-Back button.
![sweepfund](https://user-images.githubusercontent.com/62699947/85836461-3d613b00-b7b4-11ea-9c32-909d5a664e93.jpg)

**Comment by antuz123** [comment]
Lorem Ipsum on the main selection screen and on the Server not responding
