### ISSUE TITLE
Phone checks at login.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#861]
-This should be a warning screen not just info screen.
-Text should be: Your phone does not have any secure entry like Pin or Biometric
-Add to it: “This may be a security risk to your funds on Hexa”
![Image from iOS](https://user-images.githubusercontent.com/62699947/85994993-74855580-ba1b-11ea-8cb5-e32fc202ee8d.jpg)

**Comment by cakesoft-shivani** [comment]
Warning like image change is remaining from design team

**Comment by hemantsain** [comment]
Need warning image for bottom sheet.

**Comment by antuz123** [comment]
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/c0f38435-7018-41d2-befc-b470f0eabd63

**Comment by antuz123** [comment]
There is a screen for this. We used the wrong image.

**Comment by antuz123** [comment]
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/6d0301f2-ae43-439c-9c98-e2551cc098f4

**Comment by cakesoft-swati** [comment]
-Need to do the changes as per the XD link

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/f25f3e5c-89a1-4c73-b154-35559d94e368/

@ASN-BitHyve take a look at the content
