### ISSUE TITLE
Friends and Family list.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#887]
-Even after the success message Your are now the Keeper of’, it still does not appear on this list.
- If I try again, it says contact exists.
![IMG_0666](https://user-images.githubusercontent.com/62699947/86123433-1cbc1c80-baf7-11ea-8c40-c56bf7f3dd99.PNG)

**Comment by Parsh** [comment]
Unable to replicate, will require order of actions to arrive at the issue.
