### ISSUE TITLE
2FA token

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#896]
-The 2FA token did not work after restoring was done.
![2FArestore](https://user-images.githubusercontent.com/62699947/86209328-fc8c6c00-bb8f-11ea-832b-176f181c9e13.jpg)

**Comment by Parsh** [comment]
Unable to replicate, 2FA token worked for me after consecutive restorations.

**Comment by cakesoft-swati** [comment]
2FA token working even after restoring.
