### ISSUE TITLE
FBTC deeplink.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#932]
-When coming back from the FBTC deeplink, the background screen should be the funding sources page.
![fbtccomebck](https://user-images.githubusercontent.com/62699947/86351689-4ce3f680-bc82-11ea-9da6-0d5367d96921.jpg)

**Comment by cakesoft-swati** [comment]
-Not able to see the funding source page.

**Comment by AliMeer** [comment]
@antuz123 this not relevant anymore as we don’t have a funding sources page. I think this should be closed.
