### ISSUE TITLE
Reshare of Keeper Device.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#949]
-Reshare of Keeper Device is not working properly.
-Can’t become a Keeper when you have restored.
![Image from iOS (2)](https://user-images.githubusercontent.com/62699947/86565608-c54dfe80-bf85-11ea-8ed1-d918c1b62e2e.jpg)

**Comment by Parsh** [comment]
I was able to become a keeper post-restoration, wasn't able to test the Reshare of keeper due to lack of devices (@cakesoft-swati can you test and confirm this once?)

**Comment by cakesoft-swati** [comment]
-Not able to test this scenario.
-Healch check status is not accurate.
