### ISSUE TITLE
Recovery using alink.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#952]
-When trying to recover using a link, the RK is showing in transit and not confirming.
![Image from iOS (4)](https://user-images.githubusercontent.com/62699947/86566563-8456e980-bf87-11ea-84e0-e17ab5860925.jpg)

-After scanning or any action, it keeps coming back to this screen. 
-It should go to the main screen and fetch the RK.
![Image from iOS (5)](https://user-images.githubusercontent.com/62699947/86566676-a7819900-bf87-11ea-92d0-35a71743a7d2.jpg)

**Comment by Parsh** [comment]
Unable to replicate, the deep links for recovery flow worked every time for me.

**Comment by cakesoft-swati** [comment]
Deeplinks are working for recovery flow.
