### ISSUE TITLE
request confirmation screen 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#974]
Need a new UX where the phone number is being entered to confirm a request. The user can only see the requester name in big. So ends up trying to enter their number when they have to enter their own. That is not very clear. 

Also the slider.

**Comment by Arpanjainson** [comment]
@shreyasnisal  i have sent the request to UX team. Will let you know once i hear back

**Comment by Arpanjainson** [comment]
https://xd.adobe.com/view/00485057-d5b7-4b2b-641b-20216b3a38d5-7679/screen/b23aa521-4891-4b54-b7da-98ede8a333e2/specs/@hemantsain  this is the spec link
The message needs to be updated
the second heading should be
Confirm your mobile number
Enter your mobile number to accept the request

Simialr UI changes need to be made for email address and OTP based flow.
@antuz123
