### ISSUE TITLE
Review text for the app

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#975]
Each screen should be looked at to reduce the text content and increase the size of the text

**Comment by hemantsain** [comment]
Need more clarifications over this.

**Comment by antuz123** [comment]
There is a text review exercise going on with Abhilash

**Comment by antuz123** [comment]
Change sub-title text: 

Test Account: Bitcoin Testnet 
Checking Account: SingleSig bitcoin wallet 
Saving Account: MultiSig bitcoin wallet
