### ISSUE TITLE
Keeper Device status on friends and family.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#987]
-Even though did not touch ‘Yes I have scanned’ this appeared.
![eventho](https://user-images.githubusercontent.com/62699947/86929147-25de6680-c153-11ea-9e77-2722a3903714.jpg)

**Comment by Parsh** [comment]
A probable solution to this issue:

- Getting rid of the timer or having a one-day timer for QR code will offset this issue.
- We may have to look at the timer for links as well.
- Having a delete button on the expired contacts.
